In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

In [4]:
df.shape

(23678, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23678 entries, 0 to 23677
Data columns (total 21 columns):
Suburb           23547 non-null object
Address          23547 non-null object
Rooms            23547 non-null float64
Type             23547 non-null object
Price            18396 non-null float64
Method           23547 non-null object
SellerG          23547 non-null object
Date             23547 non-null object
Distance         23546 non-null float64
Postcode         23546 non-null float64
Bedroom2         19066 non-null float64
Bathroom         19063 non-null float64
Car              18921 non-null float64
Landsize         17410 non-null float64
BuildingArea     10018 non-null float64
YearBuilt        11540 non-null float64
CouncilArea      15656 non-null object
Lattitude        19243 non-null float64
Longtitude       19243 non-null float64
Regionname       23546 non-null object
Propertycount    23546 non-null float64
dtypes: float64(13), object(8)
memory usage: 3.8+ MB

In [6]:
df.dtypes

Suburb            object
Address           object
Rooms            float64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [7]:
rows_with_nan = []
for index, row in df.iterrows():
    is_nan_series = row.isnull()
    if is_nan_series.any():
        rows_with_nan.append(index)

print(rows_with_nan)

[0, 1, 3, 5, 7, 8, 9, 10, 12, 13, 15, 16, 17, 19, 20, 21, 22, 23, 26, 27, 28, 29, 31, 32, 34, 35, 37, 40, 41, 42, 46, 47, 48, 49, 51, 53, 54, 55, 56, 61, 63, 65, 66, 70, 75, 76, 77, 78, 79, 80, 81, 85, 88, 90, 92, 93, 94, 95, 96, 97, 98, 100, 102, 103, 106, 108, 111, 112, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 131, 132, 133, 135, 138, 140, 141, 142, 144, 145, 147, 149, 151, 152, 154, 155, 157, 158, 159, 161, 164, 165, 166, 168, 170, 171, 172, 174, 175, 176, 180, 181, 182, 183, 185, 186, 188, 189, 190, 191, 193, 195, 197, 198, 199, 200, 201, 204, 207, 208, 209, 210, 211, 212, 213, 214, 219, 221, 222, 223, 224, 225, 226, 228, 229, 235, 238, 240, 241, 244, 246, 248, 249, 251, 253, 254, 255, 257, 258, 259, 261, 264, 266, 267, 268, 269, 271, 272, 273, 274, 275, 276, 278, 280, 281, 282, 284, 287, 288, 289, 291, 292, 294, 295, 297, 298, 299, 301, 303, 304, 305, 306, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 342, 345, 346, 347, 348, 349, 351, 352, 353, 354, 355, 356, 358, 359, 360, 361, 363, 364, 365, 367, 370, 371, 373, 374, 375, 377, 378, 379, 380, 382, 383, 385, 386, 387, 388, 389, 390, 391, 392, 394, 395, 396, 397, 398, 399, 400, 402, 404, 405, 406, 407, 409, 412, 413, 414, 415, 416, 418, 420, 421, 422, 423, 424, 425, 426, 428, 429, 430, 431, 432, 434, 435, 436, 437, 438, 440, 441, 443, 444, 447, 448, 449, 450, 451, 452, 453, 455, 457, 459, 460, 461, 463, 464, 465, 470, 471, 472, 473, 475, 476, 477, 478, 479, 480, 482, 483, 484, 485, 486, 489, 490, 494, 499, 503, 506, 508, 510, 511, 512, 514, 515, 517, 518, 519, 521, 522, 523, 524, 525, 530, 533, 535, 536, 543, 546, 547, 548, 550, 552, 555, 557, 559, 560, 561, 562, 563, 564, 568, 569, 572, 576, 579, 581, 582, 584, 585, 586, 587, 589, 590, 593, 594, 596, 597, 599, 601, 603, 604, 605, 606, 607, 609, 610, 611, 612, 613, 614, 618, 619, 622, 623, 625, 626, 627, 628, 630, 632, 634, 635, 636, 637, 638, 639, 640, 641, 642, 644, 645, 646, 648, 649, 650, 652, 653, 654, 656, 657, 658, 659, 661, 662, 663, 665, 669, 672, 673, 676, 677, 679, 680, 681, 682, 683, 684, 685, 688, 690, 693, 694, 697, 698, 699, 700, 701, 702, 705, 707, 708, 709, 710, 712, 713, 714, 716, 717, 718, 719, 720, 721, 722, 724, 726, 727, 728, 729, 730, 733, 735, 736, 737, 738, 739, 741, 742, 743, 745, 747, 748, 752, 753, 754, 756, 757, 758, 759, 760, 762, 763, 764, 765, 767, 768, 769, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 792, 794, 795, 796, 797, 799, 801, 802, 803, 805, 806, 807, 809, 810, 811, 812, 814, 815, 817, 818, 820, 821, 822, 823, 826, 827, 829, 830, 831, 835, 838, 842, 844, 845, 846, 847, 852, 853, 856, 857, 860, 862, 863, 864, 865, 866, 867, 868, 869, 871, 872, 873, 874, 876, 877, 878, 879, 880, 881, 883, 886, 887, 888, 890, 892, 893, 894, 895, 897, 898, 899, 903, 904, 906, 907, 908, 909, 910, 912, 913, 915, 916, 918, 919, 920, 921, 922, 923, 924, 926, 927, 928, 929, 930, 932, 934, 935, 937, 938, 939, 940, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 957, 958, 959, 960, 961, 963, 964, 965, 966, 967, 968, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 984, 985, 987, 989, 990, 991, 992, 993, 994, 995, 997, 998, 1000, 1001, 1003, 1004, 1005, 1007, 1008, 1010, 1014, 1015, 1016, 1017, 1022, 1023, 1024, 1027, 1028, 1029, 1034, 1035, 1036, 1037, 1038, 1040, 1041, 1043, 1044, 1045, 1046, 1047, 1048, 1050, 1051, 1052, 1053, 1054, 1057, 1058, 1059, 1061, 1063, 1064, 1065, 1067, 1070, 1072, 1074, 1075, 1076, 1077, 1078, 1080, 1081, 1082, 1083, 1084, 1085, 1087, 1088, 1090, 1093, 1095, 1098, 1099, 1101, 1102, 1103, 1104, 1106, 1108, 1109, 1110, 1112, 1113, 1114, 1116, 1117, 1118, 1119, 1120, 1123, 1124, 1125, 1126, 1127, 1129, 1130, 1131, 1133, 1134, 1135, 1137, 1139, 1140, 1141, 1143, 1144, 1145, 1146, 1147, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1159, 1160, 1161, 1162, 1164, 1165, 1166, 1168, 1170, 1171, 1172, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1189, 1190, 1191, 1193, 1194, 1195, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1205, 1207, 1208, 1209, 1210, 1211, 1212, 1214, 1215, 1216, 1217, 1218, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1235, 1238, 1239, 1242, 1243, 1245, 1246, 1247, 1248, 1252, 1254, 1255, 1256, 1258, 1259, 1263, 1264, 1265, 1266, 1268, 1269, 1270, 1271, 1274, 1276, 1277, 1278, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1290, 1291, 1292, 1293, 1295, 1297, 1299, 1301, 1302, 1304, 1305, 1307, 1308, 1309, 1310, 1312, 1313, 1314, 1315, 1319, 1320, 1321, 1322, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1332, 1333, 1334, 1336, 1337, 1338, 1340, 1341, 1343, 1345, 1346, 1348, 1349, 1351, 1352, 1353, 1354, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1366, 1367, 1368, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1382, 1383, 1384, 1385, 1386, 1387, 1389, 1391, 1394, 1395, 1396, 1397, 1399, 1406, 1407, 1408, 1410, 1411, 1412, 1414, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1425, 1426, 1427, 1430, 1431, 1432, 1433, 1434, 1435, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1453, 1454, 1456, 1457, 1459, 1460, 1461, 1462, 1465, 1466, 1467, 1468, 1469, 1471, 1472, 1474, 1476, 1477, 1478, 1479, 1481, 1482, 1483, 1486, 1489, 1490, 1491, 1494, 1496, 1498, 1499, 1502, 1503, 1504, 1506, 1510, 1511, 1512, 1513, 1515, 1516, 1517, 1518, 1519, 1521, 1522, 1523, 1524, 1525, 1527, 1528, 1529, 1530, 1534, 1535, 1536, 1538, 1545, 1546, 1547, 1550, 1552, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1564, 1565, 1567, 1570, 1573, 1577, 1580, 1581, 1582, 1583, 1585, 1586, 1587, 1589, 1590, 1591, 1592, 1593, 1594, 1596, 1598, 1600, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1613, 1614, 1615, 1617, 1618, 1619, 1621, 1624, 1627, 1628, 1629, 1630, 1632, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1642, 1643, 1647, 1649, 1650, 1658, 1659, 1662, 1664, 1665, 1666, 1669, 1671, 1672, 1673, 1674, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1686, 1687, 1688, 1689, 1690, 1691, 1695, 1699, 1701, 1702, 1703, 1704, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1718, 1720, 1722, 1723, 1724, 1725, 1726, 1730, 1732, 1734, 1735, 1736, 1738, 1739, 1740, 1741, 1743, 1744, 1746, 1748, 1750, 1751, 1752, 1754, 1755, 1759, 1760, 1761, 1762, 1764, 1765, 1766, 1767, 1769, 1771, 1772, 1773, 1775, 1776, 1777, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1790, 1791, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1805, 1808, 1809, 1810, 1811, 1812, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1823, 1824, 1825, 1827, 1828, 1829, 1830, 1831, 1833, 1834, 1836, 1837, 1839, 1841, 1842, 1843, 1845, 1847, 1849, 1850, 1851, 1852, 1853, 1855, 1856, 1857, 1859, 1860, 1862, 1863, 1864, 1865, 1867, 1868, 1869, 1871, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1880, 1882, 1884, 1885, 1886, 1888, 1889, 1890, 1892, 1893, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1908, 1909, 1911, 1912, 1913, 1915, 1916, 1917, 1918, 1919, 1920, 1923, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1938, 1940, 1941, 1942, 1943, 1944, 1946, 1947, 1948, 1950, 1952, 1953, 1955, 1956, 1957, 1958, 1960, 1961, 1962, 1963, 1965, 1966, 1967, 1968, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1984, 1985, 1986, 1988, 1989, 1991, 1992, 1993, 1997, 1998, 1999, 2002, 2003, 2004, 2006, 2007, 2008, 2010, 2011, 2013, 2014, 2016, 2017, 2018, 2020, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2033, 2034, 2035, 2037, 2038, 2039, 2041, 2042, 2043, 2044, 2045, 2051, 2052, 2053, 2055, 2056, 2057, 2058, 2060, 2061, 2062, 2064, 2065, 2066, 2067, 2068, 2069, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2098, 2100, 2101, 2102, 2103, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2115, 2116, 2117, 2118, 2119, 2120, 2122, 2123, 2125, 2127, 2129, 2131, 2133, 2134, 2135, 2137, 2138, 2139, 2140, 2141, 2143, 2147, 2148, 2149, 2150, 2152, 2156, 2157, 2160, 2161, 2162, 2164, 2166, 2167, 2171, 2172, 2173, 2175, 2177, 2179, 2180, 2182, 2185, 2186, 2187, 2189, 2191, 2192, 2193, 2194, 2195, 2197, 2198, 2199, 2200, 2201, 2202, 2205, 2206, 2208, 2209, 2210, 2212, 2213, 2214, 2220, 2223, 2224, 2226, 2227, 2228, 2232, 2233, 2237, 2240, 2242, 2243, 2245, 2247, 2250, 2252, 2253, 2257, 2258, 2259, 2260, 2263, 2265, 2266, 2267, 2269, 2270, 2271, 2272, 2273, 2274, 2276, 2277, 2278, 2279, 2281, 2283, 2284, 2286, 2288, 2293, 2295, 2298, 2301, 2302, 2304, 2305, 2306, 2307, 2308, 2311, 2312, 2314, 2318, 2320, 2323, 2324, 2325, 2329, 2330, 2331, 2333, 2336, 2337, 2339, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2352, 2354, 2357, 2358, 2359, 2360, 2365, 2366, 2367, 2368, 2369, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2380, 2385, 2386, 2388, 2389, 2391, 2394, 2395, 2396, 2397, 2399, 2400, 2406, 2407, 2413, 2414, 2418, 2419, 2422, 2423, 2424, 2426, 2427, 2428, 2430, 2433, 2435, 2438, 2440, 2441, 2442, 2444, 2446, 2448, 2450, 2451, 2452, 2453, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2464, 2465, 2467, 2468, 2470, 2471, 2472, 2474, 2475, 2476, 2477, 2480, 2481, 2483, 2485, 2486, 2487, 2488, 2489, 2490, 2492, 2493, 2494, 2495, 2497, 2498, 2499, 2500, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2512, 2513, 2514, 2515, 2518, 2519, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2530, 2532, 2533, 2534, 2536, 2538, 2539, 2540, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2552, 2553, 2555, 2557, 2558, 2560, 2561, 2562, 2563, 2564, 2566, 2567, 2568, 2570, 2572, 2573, 2576, 2577, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2592, 2593, 2594, 2595, 2597, 2598, 2599, 2600, 2601, 2603, 2604, 2605, 2606, 2607, 2608, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2621, 2623, 2624, 2625, 2626, 2627, 2630, 2631, 2632, 2633, 2634, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2650, 2651, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2665, 2666, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2687, 2688, 2689, 2692, 2693, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2704, 2705, 2706, 2707, 2709, 2710, 2711, 2713, 2714, 2716, 2719, 2720, 2721, 2722, 2725, 2726, 2728, 2729, 2730, 2732, 2733, 2734, 2735, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2762, 2763, 2764, 2765, 2766, 2768, 2769, 2770, 2771, 2772, 2774, 2776, 2777, 2778, 2780, 2781, 2783, 2784, 2785, 2786, 2787, 2788, 2789, 2792, 2794, 2796, 2797, 2799, 2800, 2803, 2805, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2816, 2817, 2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2829, 2830, 2833, 2837, 2839, 2842, 2843, 2845, 2846, 2848, 2850, 2853, 2855, 2856, 2857, 2858, 2859, 2860, 2862, 2863, 2864, 2865, 2866, 2867, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2882, 2883, 2884, 2885, 2888, 2889, 2890, 2892, 2893, 2894, 2896, 2898, 2899, 2901, 2902, 2903, 2904, 2905, 2907, 2908, 2910, 2912, 2913, 2915, 2916, 2917, 2918, 2920, 2923, 2924, 2927, 2928, 2930, 2931, 2932, 2935, 2941, 2944, 2945, 2948, 2949, 2950, 2951, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2961, 2965, 2966, 2968, 2969, 2970, 2971, 2972, 2973, 2977, 2978, 2979, 2981, 2983, 2984, 2986, 2988, 2991, 2994, 2995, 2996, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3007, 3011, 3012, 3013, 3014, 3015, 3016, 3019, 3020, 3022, 3023, 3024, 3026, 3027, 3028, 3031, 3033, 3036, 3037, 3038, 3040, 3042, 3045, 3046, 3048, 3051, 3052, 3053, 3056, 3058, 3060, 3061, 3062, 3063, 3065, 3066, 3068, 3069, 3070, 3072, 3074, 3076, 3078, 3080, 3081, 3082, 3083, 3085, 3086, 3087, 3089, 3090, 3091, 3092, 3093, 3094, 3096, 3097, 3098, 3100, 3101, 3102, 3104, 3106, 3107, 3110, 3111, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3130, 3132, 3134, 3137, 3138, 3139, 3140, 3141, 3143, 3144, 3145, 3147, 3148, 3150, 3152, 3154, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3164, 3165, 3167, 3168, 3170, 3171, 3172, 3173, 3174, 3177, 3178, 3179, 3181, 3182, 3183, 3185, 3186, 3188, 3189, 3190, 3191, 3192, 3194, 3195, 3196, 3197, 3198, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3208, 3209, 3210, 3212, 3214, 3215, 3216, 3217, 3219, 3222, 3223, 3229, 3231, 3232, 3233, 3235, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3245, 3246, 3247, 3248, 3250, 3251, 3252, 3254, 3255, 3256, 3257, 3259, 3260, 3261, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3272, 3273, 3275, 3276, 3277, 3279, 3281, 3282, 3283, 3285, 3286, 3287, 3288, 3291, 3293, 3294, 3295, 3297, 3298, 3302, 3303, 3304, 3305, 3307, 3309, 3310, 3318, 3320, 3321, 3323, 3325, 3326, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3338, 3339, 3340, 3341, 3343, 3346, 3350, 3352, 3354, 3355, 3356, 3357, 3360, 3361, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3371, 3372, 3373, 3374, 3375, 3377, 3378, 3379, 3380, 3381, 3382, 3385, 3386, 3387, 3388, 3389, 3393, 3395, 3396, 3400, 3401, 3403, 3404, 3405, 3410, 3413, 3415, 3417, 3418, 3420, 3421, 3422, 3424, 3426, 3427, 3428, 3431, 3433, 3436, 3437, 3438, 3439, 3443, 3445, 3449, 3450, 3451, 3452, 3455, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3469, 3471, 3472, 3473, 3475, 3477, 3478, 3481, 3483, 3485, 3486, 3487, 3490, 3491, 3493, 3496, 3498, 3499, 3500, 3501, 3502, 3503, 3504, 3505, 3506, 3507, 3508, 3509, 3510, 3511, 3512, 3513, 3516, 3517, 3518, 3521, 3522, 3523, 3524, 3525, 3526, 3527, 3532, 3533, 3534, 3535, 3536, 3540, 3541, 3542, 3543, 3545, 3548, 3549, 3551, 3552, 3555, 3556, 3558, 3559, 3562, 3564, 3566, 3567, 3569, 3571, 3574, 3575, 3576, 3577, 3578, 3579, 3581, 3583, 3584, 3588, 3590, 3592, 3594, 3595, 3596, 3598, 3599, 3601, 3603, 3604, 3605, 3606, 3607, 3608, 3610, 3611, 3613, 3614, 3617, 3619, 3620, 3625, 3627, 3628, 3630, 3631, 3633, 3635, 3636, 3637, 3638, 3639, 3641, 3642, 3643, 3644, 3645, 3646, 3647, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3657, 3658, 3660, 3662, 3664, 3667, 3670, 3671, 3672, 3673, 3674, 3675, 3677, 3678, 3679, 3680, 3685, 3686, 3687, 3690, 3691, 3692, 3693, 3695, 3698, 3699, 3700, 3701, 3703, 3704, 3705, 3712, 3714, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722, 3723, 3725, 3727, 3728, 3729, 3730, 3735, 3737, 3739, 3742, 3744, 3745, 3748, 3749, 3751, 3752, 3755, 3757, 3758, 3759, 3760, 3761, 3765, 3766, 3767, 3768, 3769, 3772, 3775, 3778, 3780, 3781, 3782, 3783, 3784, 3790, 3791, 3792, 3793, 3794, 3795, 3796, 3797, 3798, 3804, 3807, 3812, 3814, 3815, 3816, 3818, 3819, 3820, 3821, 3822, 3823, 3825, 3826, 3829, 3830, 3833, 3835, 3836, 3839, 3840, 3841, 3842, 3843, 3845, 3846, 3848, 3850, 3851, 3852, 3853, 3854, 3855, 3857, 3861, 3862, 3864, 3866, 3868, 3869, 3870, 3871, 3873, 3875, 3876, 3878, 3880, 3881, 3882, 3884, 3886, 3887, 3888, 3889, 3890, 3891, 3892, 3893, 3894, 3897, 3899, 3902, 3903, 3904, 3905, 3906, 3907, 3909, 3910, 3913, 3914, 3915, 3916, 3921, 3922, 3924, 3925, 3927, 3928, 3929, 3936, 3939, 3940, 3941, 3945, 3946, 3947, 3948, 3951, 3953, 3955, 3956, 3957, 3958, 3959, 3960, 3964, 3965, 3966, 3968, 3969, 3971, 3975, 3976, 3979, 3982, 3984, 3986, 3987, 3988, 3989, 3993, 3994, 3995, 3996, 3997, 3998, 4000, 4001, 4002, 4003, 4004, 4005, 4007, 4008, 4009, 4010, 4011, 4012, 4015, 4017, 4018, 4019, 4020, 4022, 4023, 4024, 4026, 4031, 4033, 4035, 4036, 4038, 4039, 4040, 4042, 4045, 4046, 4047, 4048, 4049, 4050, 4054, 4055, 4058, 4059, 4061, 4063, 4065, 4067, 4069, 4071, 4072, 4074, 4075, 4076, 4077, 4078, 4079, 4081, 4083, 4084, 4088, 4089, 4090, 4092, 4093, 4094, 4095, 4096, 4097, 4100, 4103, 4105, 4106, 4108, 4109, 4110, 4111, 4114, 4115, 4116, 4117, 4118, 4121, 4123, 4124, 4126, 4131, 4132, 4133, 4134, 4135, 4136, 4137, 4139, 4140, 4142, 4147, 4148, 4150, 4151, 4152, 4153, 4155, 4159, 4161, 4162, 4164, 4165, 4167, 4168, 4169, 4170, 4174, 4177, 4179, 4181, 4182, 4184, 4185, 4186, 4187, 4189, 4190, 4191, 4192, 4193, 4194, 4197, 4198, 4200, 4201, 4206, 4207, 4208, 4210, 4212, 4214, 4215, 4217, 4218, 4219, 4220, 4222, 4223, 4224, 4225, 4227, 4230, 4231, 4232, 4233, 4235, 4236, 4237, 4239, 4240, 4241, 4242, 4245, 4246, 4248, 4250, 4251, 4253, 4254, 4257, 4258, 4263, 4264, 4265, 4269, 4271, 4272, 4273, 4274, 4275, 4277, 4279, 4283, 4284, 4285, 4287, 4288, 4290, 4291, 4292, 4293, 4294, 4298, 4299, 4300, 4301, 4304, 4305, 4306, 4307, 4308, 4311, 4314, 4315, 4317, 4318, 4320, 4321, 4322, 4323, 4325, 4326, 4327, 4328, 4330, 4331, 4333, 4335, 4336, 4340, 4341, 4343, 4344, 4345, 4346, 4347, 4349, 4350, 4352, 4353, 4354, 4355, 4357, 4360, 4363, 4365, 4366, 4367, 4368, 4369, 4371, 4372, 4373, 4374, 4376, 4377, 4378, 4380, 4383, 4384, 4385, 4387, 4388, 4391, 4392, 4393, 4394, 4396, 4407, 4409, 4412, 4413, 4415, 4417, 4418, 4420, 4423, 4424, 4425, 4429, 4431, 4432, 4435, 4436, 4437, 4445, 4447, 4448, 4450, 4452, 4453, 4454, 4457, 4458, 4459, 4460, 4461, 4462, 4465, 4468, 4469, 4470, 4476, 4477, 4478, 4479, 4482, 4485, 4487, 4488, 4489, 4490, 4491, 4492, 4494, 4496, 4499, 4501, 4502, 4503, 4504, 4505, 4507, 4510, 4511, 4517, 4518, 4519, 4523, 4524, 4525, 4526, 4527, 4530, 4531, 4532, 4533, 4534, 4536, 4537, 4540, 4541, 4542, 4543, 4545, 4547, 4548, 4550, 4551, 4553, 4557, 4558, 4559, 4562, 4563, 4564, 4565, 4566, 4567, 4570, 4571, 4573, 4574, 4575, 4576, 4577, 4578, 4579, 4580, 4582, 4583, 4584, 4585, 4586, 4587, 4588, 4589, 4590, 4592, 4593, 4595, 4596, 4597, 4598, 4600, 4601, 4602, 4603, 4604, 4606, 4608, 4609, 4610, 4612, 4613, 4614, 4615, 4616, 4618, 4619, 4620, 4621, 4622, 4623, 4624, 4627, 4628, 4629, 4630, 4631, 4632, 4634, 4636, 4637, 4638, 4639, 4640, 4641, 4642, 4643, 4645, 4647, 4648, 4649, 4650, 4651, 4652, 4654, 4655, 4656, 4658, 4659, 4660, 4661, 4664, 4666, 4667, 4668, 4669, 4670, 4671, 4673, 4674, 4675, 4676, 4677, 4678, 4679, 4680, 4681, 4682, 4683, 4685, 4686, 4687, 4688, 4692, 4693, 4694, 4695, 4696, 4697, 4698, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4710, 4711, 4714, 4716, 4717, 4721, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4733, 4734, 4735, 4737, 4739, 4740, 4742, 4743, 4744, 4745, 4746, 4747, 4749, 4750, 4753, 4754, 4755, 4756, 4758, 4759, 4760, 4761, 4762, 4764, 4765, 4766, 4768, 4769, 4770, 4771, 4772, 4773, 4774, 4777, 4779, 4780, 4781, 4782, 4783, 4785, 4786, 4788, 4789, 4790, 4791, 4792, 4793, 4795, 4796, 4798, 4799, 4800, 4801, 4802, 4803, 4804, 4806, 4807, 4809, 4812, 4813, 4814, 4816, 4818, 4819, 4820, 4823, 4824, 4827, 4828, 4829, 4830, 4833, 4834, 4835, 4837, 4839, 4840, 4841, 4842, 4844, 4845, 4848, 4849, 4850, 4851, 4852, 4853, 4854, 4855, 4858, 4859, 4860, 4861, 4862, 4863, 4864, 4866, 4867, 4868, 4870, 4871, 4872, 4874, 4876, 4878, 4879, 4881, 4883, 4884, 4885, 4887, 4890, 4891, 4893, 4894, 4895, 4897, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4910, 4912, 4913, 4914, 4918, 4920, 4922, 4923, 4924, 4925, 4926, 4929, 4933, 4934, 4936, 4938, 4941, 4942, 4944, 4945, 4947, 4949, 4950, 4952, 4954, 4956, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 4972, 4975, 4976, 4979, 4980, 4983, 4985, 4988, 4989, 4991, 4993, 4994, 4997, 4998, 4999, 5000, 5001, 5003, 5005, 5006, 5007, 5008, 5009, 5011, 5012, 5013, 5017, 5019, 5021, 5023, 5024, 5027, 5028, 5029, 5030, 5032, 5033, 5034, 5035, 5036, 5037, 5038, 5039, 5043, 5044, 5045, 5046, 5048, 5049, 5052, 5053, 5055, 5057, 5058, 5059, 5060, 5061, 5062, 5063, 5064, 5065, 5067, 5068, 5069, 5071, 5072, 5073, 5074, 5075, 5077, 5079, 5080, 5082, 5083, 5084, 5085, 5086, 5088, 5089, 5091, 5092, 5093, 5095, 5096, 5098, 5099, 5100, 5101, 5102, 5103, 5104, 5105, 5108, 5109, 5110, 5112, 5113, 5115, 5116, 5118, 5120, 5121, 5122, 5123, 5126, 5127, 5128, 5129, 5130, 5131, 5133, 5135, 5136, 5137, 5138, 5139, 5141, 5142, 5143, 5144, 5145, 5147, 5149, 5150, 5151, 5152, 5153, 5154, 5156, 5157, 5158, 5159, 5160, 5161, 5162, 5163, 5164, 5165, 5166, 5167, 5168, 5169, 5170, 5171, 5172, 5173, 5174, 5178, 5179, 5181, 5183, 5184, 5185,

In [8]:
df.isnull().sum()

Suburb             131
Address            131
Rooms              131
Type               131
Price             5282
Method             131
SellerG            131
Date               131
Distance           132
Postcode           132
Bedroom2          4612
Bathroom          4615
Car               4757
Landsize          6268
BuildingArea     13660
YearBuilt        12138
CouncilArea       8022
Lattitude         4435
Longtitude        4435
Regionname         132
Propertycount      132
dtype: int64

In [9]:
df.isnull().mean() * 100

Suburb            0.553256
Address           0.553256
Rooms             0.553256
Type              0.553256
Price            22.307627
Method            0.553256
SellerG           0.553256
Date              0.553256
Distance          0.557480
Postcode          0.557480
Bedroom2         19.477996
Bathroom         19.490666
Car              20.090379
Landsize         26.471830
BuildingArea     57.690683
YearBuilt        51.262776
CouncilArea      33.879551
Lattitude        18.730467
Longtitude       18.730467
Regionname        0.557480
Propertycount     0.557480
dtype: float64

In [10]:
for i in range(len(df.index)) : 
    print(" Total NaN in row", i + 1, ":", 
          df.iloc[i].isnull().sum())

 Total NaN in row 1 : 3
 Total NaN in row 2 : 2
 Total NaN in row 3 : 0
 Total NaN in row 4 : 3
 Total NaN in row 5 : 0
 Total NaN in row 6 : 2
 Total NaN in row 7 : 0
 Total NaN in row 8 : 1
 Total NaN in row 9 : 2
 Total NaN in row 10 : 2
 Total NaN in row 11 : 2
 Total NaN in row 12 : 0
 Total NaN in row 13 : 1
 Total NaN in row 14 : 1
 Total NaN in row 15 : 0
 Total NaN in row 16 : 9
 Total NaN in row 17 : 9
 Total NaN in row 18 : 2
 Total NaN in row 19 : 0
 Total NaN in row 20 : 9
 Total NaN in row 21 : 1
 Total NaN in row 22 : 9
 Total NaN in row 23 : 9
 Total NaN in row 24 : 2
 Total NaN in row 25 : 0
 Total NaN in row 26 : 0
 Total NaN in row 27 : 7
 Total NaN in row 28 : 9
 Total NaN in row 29 : 2
 Total NaN in row 30 : 2
 Total NaN in row 31 : 0
 Total NaN in row 32 : 21
 Total NaN in row 33 : 1
 Total NaN in row 34 : 0
 Total NaN in row 35 : 9
 Total NaN in row 36 : 10
 Total NaN in row 37 : 0
 Total NaN in row 38 : 2
 Total NaN in row 39 : 0
 Total NaN in row 40 : 0
 Total NaN in row 41 : 1
 Total NaN in row 42 : 1
 Total NaN in row 43 : 1
 Total NaN in row 44 : 0
 Total NaN in row 45 : 0
 Total NaN in row 46 : 0
 Total NaN in row 47 : 9
 Total NaN in row 48 : 9
 Total NaN in row 49 : 8
 Total NaN in row 50 : 2
 Total NaN in row 51 : 0
 Total NaN in row 52 : 1
 Total NaN in row 53 : 0
 Total NaN in row 54 : 9
 Total NaN in row 55 : 2
 Total NaN in row 56 : 7
 Total NaN in row 57 : 1
 Total NaN in row 58 : 0
 Total NaN in row 59 : 0
 Total NaN in row 60 : 0
 Total NaN in row 61 : 0
 Total NaN in row 62 : 10
 Total NaN in row 63 : 0
 Total NaN in row 64 : 9
 Total NaN in row 65 : 0
 Total NaN in row 66 : 8
 Total NaN in row 67 : 9
 Total NaN in row 68 : 0
 Total NaN in row 69 : 0
 Total NaN in row 70 : 0
 Total NaN in row 71 : 1
 Total NaN in row 72 : 0
 Total NaN in row 73 : 0
 Total NaN in row 74 : 0
 Total NaN in row 75 : 0
 Total NaN in row 76 : 9
 Total NaN in row 77 : 9
 Total NaN in row 78 : 9
 Total NaN in row 79 : 9
 Total NaN in row 80 : 9
 Total NaN in row 81 : 2
 Total NaN in row 82 : 1
 Total NaN in row 83 : 0
 Total NaN in row 84 : 0
 Total NaN in row 85 : 0
 Total NaN in row 86 : 9
 Total NaN in row 87 : 0
 Total NaN in row 88 : 0
 Total NaN in row 89 : 9
 Total NaN in row 90 : 0
 Total NaN in row 91 : 9
 Total NaN in row 92 : 0
 Total NaN in row 93 : 9
 Total NaN in row 94 : 9
 Total NaN in row 95 : 9
 Total NaN in row 96 : 2
 Total NaN in row 97 : 9
 Total NaN in row 98 : 2
 Total NaN in row 99 : 9
 Total NaN in row 100 : 0
 Total NaN in row 101 : 9
 Total NaN in row 102 : 0
 Total NaN in row 103 : 1
 Total NaN in row 104 : 2
 Total NaN in row 105 : 0
 Total NaN in row 106 : 0
 Total NaN in row 107 : 2
 Total NaN in row 108 : 0
 Total NaN in row 109 : 9
 Total NaN in row 110 : 0
 Total NaN in row 111 : 0
 Total NaN in row 112 : 2
 Total NaN in row 113 : 9
 Total NaN in row 114 : 0
 Total NaN in row 115 : 0
 Total NaN in row 116 : 0
 Total NaN in row 117 : 9
 Total NaN in row 118 : 2
 Total NaN in row 119 : 1
 Total NaN in row 120 : 2
 Total NaN in row 121 : 2
 Total NaN in row 122 : 2
 Total NaN in row 123 : 10
 Total NaN in row 124 : 2
 Total NaN in row 125 : 9
 Total NaN in row 126 : 9
 Total NaN in row 127 : 9
 Total NaN in row 128 : 9
 Total NaN in row 129 : 9
 Total NaN in row 130 : 2
 Total NaN in row 131 : 0
 Total NaN in row 132 : 9
 Total NaN in row 133 : 9
 Total NaN in row 134 : 9
 Total NaN in row 135 : 0
 Total NaN in row 136 : 2
 Total NaN in row 137 : 0
 Total NaN in row 138 : 0
 Total NaN in row 139 : 2
 Total NaN in row 140 : 0
 Total NaN in row 141 : 1
 Total NaN in row 142 : 1
 Total NaN in row 143 : 2
 Total NaN in row 144 : 0
 Total NaN in row 145 : 1
 Total NaN in row 146 : 2
 Total NaN in row 147 : 0
 Total NaN in row 148 : 9
 Total NaN in row 149 : 0
 Total NaN in row 150 : 2
 Total NaN in row 151 : 0
 Total NaN in row 152 : 1
 Total NaN in row 153 : 2
 Total NaN in row 154 : 0
 Total NaN in row 155 : 2
 Total NaN in row 156 : 2
 Total NaN in row 157 : 0
 Total NaN in row 158 : 2
 Total NaN in row 159 : 1
 Total NaN in row 160 : 2
 Total NaN in row 161 : 0
 Total NaN in row 162 : 3
 Total NaN in row 163 : 0
 Total NaN in row 164 : 0
 Total NaN in row 165 : 3
 Total NaN in row 166 : 3
 Total NaN in row 167 : 1
 Total NaN in row 168 : 0
 Total NaN in row 169 : 3
 Total NaN in row 170 : 0
 Total NaN in row 171 : 3
 Total NaN in row 172 : 2
 Total NaN in row 173 : 3
 Total NaN in row 174 : 0
 Total NaN in row 175 : 1
 Total NaN in row 176 : 3
 Total NaN in row 177 : 3
 Total NaN in row 178 : 0
 Total NaN in row 179 : 0
 Total NaN in row 180 : 0
 Total NaN in row 181 : 2
 Total NaN in row 182 : 2
 Total NaN in row 183 : 2
 Total NaN in row 184 : 2
 Total NaN in row 185 : 0
 Total NaN in row 186 : 9
 Total NaN in row 187 : 2
 Total NaN in row 188 : 0
 Total NaN in row 189 : 1
 Total NaN in row 190 : 1
 Total NaN in row 191 : 3
 Total NaN in row 192 : 2
 Total NaN in row 193 : 0
 Total NaN in row 194 : 2
 Total NaN in row 195 : 0
 Total NaN in row 196 : 1
 Total NaN in row 197 : 0
 Total NaN in row 198 : 1
 Total NaN in row 199 : 2
 Total NaN in row 200 : 9
 Total NaN in row 201 : 3
 Total NaN in row 202 : 9
 Total NaN in row 203 : 0
 Total NaN in row 204 : 0
 Total NaN in row 205 : 2
 Total NaN in row 206 : 0
 Total NaN in row 207 : 0
 Total NaN in row 208 : 2
 Total NaN in row 209 : 10
 Total NaN in row 210 : 9
 Total NaN in row 211 : 2
 Total NaN in row 212 : 2
 Total NaN in row 213 : 10
 Total NaN in row 214 : 9
 Total NaN in row 215 : 2
 Total NaN in row 216 : 0
 Total NaN in row 217 : 0
 Total NaN in row 218 : 0
 Total NaN in row 219 : 0
 Total NaN in row 220 : 2
 Total NaN in row 221 : 0
 Total NaN in row 222 : 7
 Total NaN in row 223 : 3
 Total NaN in row 224 : 9
 Total NaN in row 225 : 9
 Total NaN in row 226 : 2
 Total NaN in row 227 : 9
 Total NaN in row 228 : 0
 Total NaN in row 229 : 1
 Total NaN in row 230 : 2
 Total NaN in row 231 : 0
 Total NaN in row 232 : 0
 Total NaN in row 233 : 0
 Total NaN in row 234 : 0
 Total NaN in row 235 : 0
 Total NaN in row 236 : 2
 Total NaN in row 237 : 0
 Total NaN in row 238 : 0
 Total NaN in row 239 : 2
 Total NaN in row 240 : 0
 Total NaN in row 241 : 2
 Total NaN in row 242 : 9
 Total NaN in row 243 : 0
 Total NaN in row 244 : 0
 Total NaN in row 245 : 1
 Total NaN in row 246 : 0
 Total NaN in row 247 : 2
 Total NaN in row 248 : 0
 Total NaN in row 249 : 2
 Total NaN in row 250 : 1
 Total NaN in row 251 : 0
 Total NaN in row 252 : 2
 Total NaN in row 253 : 0
 Total NaN in row 254 : 9
 Total NaN in row 255 : 1
 Total NaN in row 256 : 9
 Total NaN in row 257 : 0
 Total NaN in row 258 : 9
 Total NaN in row 259 : 1
 Total NaN in row 260 : 2
 Total NaN in row 261 : 0
 Total NaN in row 262 : 2
 Total NaN in row 263 : 0
 Total NaN in row 264 : 0
 Total NaN in row 265 : 2
 Total NaN in row 266 : 0
 Total NaN in row 267 : 2
 Total NaN in row 268 : 9
 Total NaN in row 269 : 2
 Total NaN in row 270 : 2
 Total NaN in row 271 : 0
 Total NaN in row 272 : 3
 Total NaN in row 273 : 2
 Total NaN in row 274 : 2
 Total NaN in row 275 : 9
 Total NaN in row 276 : 1
 Total NaN in row 277 : 2
 Total NaN in row 278 : 0
 Total NaN in row 279 : 2
 Total NaN in row 280 : 0
 Total NaN in row 281 : 2
 Total NaN in row 282 : 2
 Total NaN in row 283 : 1
 Total NaN in row 284 : 0
 Total NaN in row 285 : 1
 Total NaN in row 286 : 0
 Total NaN in row 287 : 0
 Total NaN in row 288 : 9
 Total NaN in row 289 : 9
 Total NaN in row 290 : 2
 Total NaN in row 291 : 0
 Total NaN in row 292 : 2
 Total NaN in row 293 : 10
 Total NaN in row 294 : 0
 Total NaN in row 295 : 10
 Total NaN in row 296 : 2
 Total NaN in row 297 : 0
 Total NaN in row 298 : 9
 Total NaN in row 299 : 9
 Total NaN in row 300 : 9
 Total NaN in row 301 : 0
 Total NaN in row 302 : 9
 Total NaN in row 303 : 0
 Total NaN in row 304 : 9
 Total NaN in row 305 : 9
 Total NaN in row 306 : 9
 Total NaN in row 307 : 10
 Total NaN in row 308 : 0
 Total NaN in row 309 : 9
 Total NaN in row 310 : 9
 Total NaN in row 311 : 1
 Total NaN in row 312 : 2
 Total NaN in row 313 : 9
 Total NaN in row 314 : 9
 Total NaN in row 315 : 1
 Total NaN in row 316 : 2
 Total NaN in row 317 : 9
 Total NaN in row 318 : 10
 Total NaN in row 319 : 10
 Total NaN in row 320 : 9
 Total NaN in row 321 : 9
 Total NaN in row 322 : 9
 Total NaN in row 323 : 0
 Total NaN in row 324 : 0
 Total NaN in row 325 : 9
 Total NaN in row 326 : 9
 Total NaN in row 327 : 2
 Total NaN in row 328 : 9
 Total NaN in row 329 : 9
 Total NaN in row 330 : 9
 Total NaN in row 331 : 9
 Total NaN in row 332 : 9
 Total NaN in row 333 : 9
 Total NaN in row 334 : 9
 Total NaN in row 335 : 9
 Total NaN in row 336 : 2
 Total NaN in row 337 : 1
 Total NaN in row 338 : 9
 Total NaN in row 339 : 1
 Total NaN in row 340 : 2
 Total NaN in row 341 : 0
 Total NaN in row 342 : 0
 Total NaN in row 343 : 9
 Total NaN in row 344 : 0
 Total NaN in row 345 : 0
 Total NaN in row 346 : 1
 Total NaN in row 347 : 9
 Total NaN in row 348 : 2
 Total NaN in row 349 : 2
 Total NaN in row 350 : 10
 Total NaN in row 351 : 0
 Total NaN in row 352 : 2
 Total NaN in row 353 : 9
 Total NaN in row 354 : 9
 Total NaN in row 355 : 2

 Total NaN in row 356 : 9
 Total NaN in row 357 : 2
 Total NaN in row 358 : 0
 Total NaN in row 359 : 9
 Total NaN in row 360 : 10
 Total NaN in row 361 : 2
 Total NaN in row 362 : 2
 Total NaN in row 363 : 0
 Total NaN in row 364 : 9
 Total NaN in row 365 : 9
 Total NaN in row 366 : 3
 Total NaN in row 367 : 0
 Total NaN in row 368 : 2
 Total NaN in row 369 : 0
 Total NaN in row 370 : 0
 Total NaN in row 371 : 1
 Total NaN in row 372 : 9
 Total NaN in row 373 : 0
 Total NaN in row 374 : 2
 Total NaN in row 375 : 9
 Total NaN in row 376 : 9
 Total NaN in row 377 : 0
 Total NaN in row 378 : 3
 Total NaN in row 379 : 2
 Total NaN in row 380 : 3
 Total NaN in row 381 : 10
 Total NaN in row 382 : 0
 Total NaN in row 383 : 3
 Total NaN in row 384 : 2
 Total NaN in row 385 : 0
 Total NaN in row 386 : 10
 Total NaN in row 387 : 1
 Total NaN in row 388 : 2
 Total NaN in row 389 : 1
 Total NaN in row 390 : 1
 Total NaN in row 391 : 9
 Total NaN in row 392 : 2
 Total NaN in row 393 : 3
 Total NaN in row 394 : 0
 Total NaN in row 395 : 2
 Total NaN in row 396 : 2
 Total NaN in row 397 : 1
 Total NaN in row 398 : 1
 Total NaN in row 399 : 1
 Total NaN in row 400 : 10
 Total NaN in row 401 : 1
 Total NaN in row 402 : 0
 Total NaN in row 403 : 1
 Total NaN in row 404 : 0
 Total NaN in row 405 : 2
 Total NaN in row 406 : 1
 Total NaN in row 407 : 2
 Total NaN in row 408 : 1
 Total NaN in row 409 : 0
 Total NaN in row 410 : 1
 Total NaN in row 411 : 0
 Total NaN in row 412 : 0
 Total NaN in row 413 : 1
 Total NaN in row 414 : 1
 Total NaN in row 415 : 1
 Total NaN in row 416 : 2
 Total NaN in row 417 : 1
 Total NaN in row 418 : 0
 Total NaN in row 419 : 10
 Total NaN in row 420 : 0
 Total NaN in row 421 : 10
 Total NaN in row 422 : 2
 Total NaN in row 423 : 3
 Total NaN in row 424 : 1
 Total NaN in row 425 : 10
 Total NaN in row 426 : 3
 Total NaN in row 427 : 2
 Total NaN in row 428 : 0
 Total NaN in row 429 : 1
 Total NaN in row 430 : 2
 Total NaN in row 431 : 2
 Total NaN in row 432 : 2
 Total NaN in row 433 : 2
 Total NaN in row 434 : 0
 Total NaN in row 435 : 10
 Total NaN in row 436 : 2
 Total NaN in row 437 : 1
 Total NaN in row 438 : 1
 Total NaN in row 439 : 2
 Total NaN in row 440 : 0
 Total NaN in row 441 : 1
 Total NaN in row 442 : 2
 Total NaN in row 443 : 0
 Total NaN in row 444 : 10
 Total NaN in row 445 : 10
 Total NaN in row 446 : 0
 Total NaN in row 447 : 0
 Total NaN in row 448 : 3
 Total NaN in row 449 : 3
 Total NaN in row 450 : 3
 Total NaN in row 451 : 2
 Total NaN in row 452 : 1
 Total NaN in row 453 : 9
 Total NaN in row 454 : 2
 Total NaN in row 455 : 0
 Total NaN in row 456 : 1
 Total NaN in row 457 : 0
 Total NaN in row 458 : 1
 Total NaN in row 459 : 0
 Total NaN in row 460 : 2
 Total NaN in row 461 : 1
 Total NaN in row 462 : 3
 Total NaN in row 463 : 0
 Total NaN in row 464 : 9
 Total NaN in row 465 : 10
 Total NaN in row 466 : 9
 Total NaN in row 467 : 0
 Total NaN in row 468 : 0
 Total NaN in row 469 : 0
 Total NaN in row 470 : 0
 Total NaN in row 471 : 3
 Total NaN in row 472 : 1
 Total NaN in row 473 : 2
 Total NaN in row 474 : 3
 Total NaN in row 475 : 0
 Total NaN in row 476 : 9
 Total NaN in row 477 : 1
 Total NaN in row 478 : 3
 Total NaN in row 479 : 9
 Total NaN in row 480 : 2
 Total NaN in row 481 : 2
 Total NaN in row 482 : 0
 Total NaN in row 483 : 2
 Total NaN in row 484 : 3
 Total NaN in row 485 : 1
 Total NaN in row 486 : 1
 Total NaN in row 487 : 2
 Total NaN in row 488 : 0
 Total NaN in row 489 : 0
 Total NaN in row 490 : 1
 Total NaN in row 491 : 9
 Total NaN in row 492 : 0
 Total NaN in row 493 : 0
 Total NaN in row 494 : 0
 Total NaN in row 495 : 1
 Total NaN in row 496 : 0
 Total NaN in row 497 : 0
 Total NaN in row 498 : 0
 Total NaN in row 499 : 0
 Total NaN in row 500 : 9
 Total NaN in row 501 : 0
 Total NaN in row 502 : 0
 Total NaN in row 503 : 0
 Total NaN in row 504 : 2
 Total NaN in row 505 : 0
 Total NaN in row 506 : 0
 Total NaN in row 507 : 1
 Total NaN in row 508 : 0
 Total NaN in row 509 : 3
 Total NaN in row 510 : 0
 Total NaN in row 511 : 2
 Total NaN in row 512 : 2
 Total NaN in row 513 : 9
 Total NaN in row 514 : 0
 Total NaN in row 515 : 9
 Total NaN in row 516 : 1
 Total NaN in row 517 : 0
 Total NaN in row 518 : 2
 Total NaN in row 519 : 1
 Total NaN in row 520 : 9
 Total NaN in row 521 : 0
 Total NaN in row 522 : 2
 Total NaN in row 523 : 1
 Total NaN in row 524 : 1
 Total NaN in row 525 : 1
 Total NaN in row 526 : 9
 Total NaN in row 527 : 0
 Total NaN in row 528 : 0
 Total NaN in row 529 : 0
 Total NaN in row 530 : 0
 Total NaN in row 531 : 9
 Total NaN in row 532 : 0
 Total NaN in row 533 : 0
 Total NaN in row 534 : 9
 Total NaN in row 535 : 0
 Total NaN in row 536 : 2
 Total NaN in row 537 : 9
 Total NaN in row 538 : 0
 Total NaN in row 539 : 0
 Total NaN in row 540 : 0
 Total NaN in row 541 : 0
 Total NaN in row 542 : 0
 Total NaN in row 543 : 0
 Total NaN in row 544 : 9
 Total NaN in row 545 : 0
 Total NaN in row 546 : 0
 Total NaN in row 547 : 2
 Total NaN in row 548 : 2
 Total NaN in row 549 : 2
 Total NaN in row 550 : 0
 Total NaN in row 551 : 1
 Total NaN in row 552 : 0
 Total NaN in row 553 : 2
 Total NaN in row 554 : 0
 Total NaN in row 555 : 0
 Total NaN in row 556 : 1
 Total NaN in row 557 : 0
 Total NaN in row 558 : 2
 Total NaN in row 559 : 0
 Total NaN in row 560 : 2
 Total NaN in row 561 : 2
 Total NaN in row 562 : 1
 Total NaN in row 563 : 9
 Total NaN in row 564 : 2
 Total NaN in row 565 : 1
 Total NaN in row 566 : 0
 Total NaN in row 567 : 0
 Total NaN in row 568 : 0
 Total NaN in row 569 : 1
 Total NaN in row 570 : 1
 Total NaN in row 571 : 0
 Total NaN in row 572 : 0
 Total NaN in row 573 : 9
 Total NaN in row 574 : 0
 Total NaN in row 575 : 0
 Total NaN in row 576 : 0
 Total NaN in row 577 : 2
 Total NaN in row 578 : 0
 Total NaN in row 579 : 0
 Total NaN in row 580 : 9
 Total NaN in row 581 : 0
 Total NaN in row 582 : 1
 Total NaN in row 583 : 7
 Total NaN in row 584 : 0
 Total NaN in row 585 : 1
 Total NaN in row 586 : 2
 Total NaN in row 587 : 2
 Total NaN in row 588 : 2
 Total NaN in row 589 : 0
 Total NaN in row 590 : 2
 Total NaN in row 591 : 2
 Total NaN in row 592 : 0
 Total NaN in row 593 : 0
 Total NaN in row 594 : 9
 Total NaN in row 595 : 9
 Total NaN in row 596 : 0
 Total NaN in row 597 : 2
 Total NaN in row 598 : 2
 Total NaN in row 599 : 0
 Total NaN in row 600 : 9
 Total NaN in row 601 : 0
 Total NaN in row 602 : 2
 Total NaN in row 603 : 0
 Total NaN in row 604 : 1
 Total NaN in row 605 : 1
 Total NaN in row 606 : 2
 Total NaN in row 607 : 9
 Total NaN in row 608 : 9
 Total NaN in row 609 : 0
 Total NaN in row 610 : 9
 Total NaN in row 611 : 10
 Total NaN in row 612 : 9
 Total NaN in row 613 : 10
 Total NaN in row 614 : 9
 Total NaN in row 615 : 9
 Total NaN in row 616 : 0
 Total NaN in row 617 : 0
 Total NaN in row 618 : 0
 Total NaN in row 619 : 1
 Total NaN in row 620 : 9
 Total NaN in row 621 : 0
 Total NaN in row 622 : 0
 Total NaN in row 623 : 3
 Total NaN in row 624 : 1
 Total NaN in row 625 : 0
 Total NaN in row 626 : 9
 Total NaN in row 627 : 9
 Total NaN in row 628 : 9
 Total NaN in row 629 : 1
 Total NaN in row 630 : 0
 Total NaN in row 631 : 9
 Total NaN in row 632 : 0
 Total NaN in row 633 : 3
 Total NaN in row 634 : 0
 Total NaN in row 635 : 1
 Total NaN in row 636 : 3
 Total NaN in row 637 : 2
 Total NaN in row 638 : 9
 Total NaN in row 639 : 9
 Total NaN in row 640 : 9
 Total NaN in row 641 : 3
 Total NaN in row 642 : 10
 Total NaN in row 643 : 3
 Total NaN in row 644 : 0
 Total NaN in row 645 : 9
 Total NaN in row 646 : 1
 Total NaN in row 647 : 2
 Total NaN in row 648 : 0
 Total NaN in row 649 : 9
 Total NaN in row 650 : 2
 Total NaN in row 651 : 9
 Total NaN in row 652 : 0
 Total NaN in row 653 : 1
 Total NaN in row 654 : 9
 Total NaN in row 655 : 10
 Total NaN in row 656 : 0
 Total NaN in row 657 : 3
 Total NaN in row 658 : 9
 Total NaN in row 659 : 9
 Total NaN in row 660 : 9
 Total NaN in row 661 : 0
 Total NaN in row 662 : 9
 Total NaN in row 663 : 10
 Total NaN in row 664 : 1
 Total NaN in row 665 : 0
 Total NaN in row 666 : 10
 Total NaN in row 667 : 0
 Total NaN in row 668 : 0
 Total NaN in row 669 : 0
 Total NaN in row 670 : 2
 Total NaN in row 671 : 0
 Total NaN in row 672 : 0
 Total NaN in row 673 : 1
 Total NaN in row 674 : 2
 Total NaN in row 675 : 0
 Total NaN in row 676 : 0
 Total NaN in row 677 : 2
 Total NaN in row 678 : 2
 Total NaN in row 679 : 0
 Total NaN in row 680 : 9
 Total NaN in row 681 : 2
 Total NaN in row 682 : 1
 Total NaN in row 683 : 3
 Total NaN in row 684 : 2
 Total NaN in row 685 : 10
 Total NaN in row 686 : 2
 Total NaN in row 687 : 0
 Total NaN in row 688 : 0
 Total NaN in row 689 : 1
 Total NaN in row 690 : 0
 Total NaN in row 691 : 2
 Total NaN in row 692 : 0
 Total NaN in row 693 : 0
 Total NaN in row 694 : 2
 Total NaN in row 695 : 2
 Total NaN in row 696 : 0
 Total NaN in row 697 : 0
 Total NaN in row 698 : 9
 Total NaN in row 699 : 3
 Total NaN in row 700 : 9
 Total NaN in row 701 : 9
 Total NaN in row 702 : 1
 Total NaN in row 703 : 2
 Total NaN in row 704 : 0
 Total NaN in row 705 : 0
 Total NaN in row 706 : 1
 Total NaN in row 707 : 0
 Total NaN in row 708 : 9
 Total NaN in row 709 : 10
 Total NaN in row 710 : 2
 Total NaN in row 711 : 9
 Total NaN in row 712 : 0
 Total NaN in row 713 : 9
 Total NaN in row 714 : 9
 Total NaN in row 715 : 1
 Total NaN in row 716 : 0
 Total NaN in row 717 : 9
 Total NaN in row 718 : 1
 Total NaN in row 719 : 2
 Total NaN in row 720 : 9
 Total NaN in row 721 : 1
 Total NaN in row 722 : 1
 Total NaN in row 723 : 1
 Total NaN in row 724 : 0
 Total NaN in row 725 : 1
 Total NaN in row 726 : 0
 Total NaN in row 727 : 9
 Total NaN in row 728 : 10
 Total NaN in row 729 : 9
 Total NaN in row 730 : 10
 Total NaN in row 731 : 2
 Total NaN in row 732 : 0
 Total NaN in row 733 : 0
 Total NaN in row 734 : 10
 Total NaN in row 735 : 0
 Total NaN in row 736 : 9
 Total NaN in row 737 : 9
 Total NaN in row 738 : 10
 Total NaN in row 739 : 9
 Total NaN in row 740 : 10
 Total NaN in row 741 : 0
 Total NaN in row 742 : 1
 Total NaN in row 743 : 1
 Total NaN in row 744 : 1
 Total NaN in row 745 : 0
 Total NaN in row 746 : 3
 Total NaN in row 747 : 0
 Total NaN in row 748 : 1
 Total NaN in row 749 : 9
 Total NaN in row 750 : 0
 Total NaN in row 751 : 0
 Total NaN in row 752 : 0
 Total NaN in row 753 : 1
 Total NaN in row 754 : 2
 Total NaN in row 755 : 1
 Total NaN in row 756 : 0
 Total NaN in row 757 : 2
 Total NaN in row 758 : 2
 Total NaN in row 759 : 2
 Total NaN in row 760 : 9
 Total NaN in row 761 : 1
 Total NaN in row 762 : 0
 Total NaN in row 763 : 1
 Total NaN in row 764 : 2
 Total NaN in row 765 : 9
 Total NaN in row 766 : 2
 Total NaN in row 767 : 0
 Total NaN in row 768 : 2
 Total NaN in row 769 : 9
 Total NaN in row 770 : 9
 Total NaN in row 771 : 0
 Total NaN in row 772 : 1
 Total NaN in row 773 : 9

 Total NaN in row 774 : 2
 Total NaN in row 775 : 9
 Total NaN in row 776 : 1
 Total NaN in row 777 : 3
 Total NaN in row 778 : 9
 Total NaN in row 779 : 1
 Total NaN in row 780 : 2
 Total NaN in row 781 : 2
 Total NaN in row 782 : 2
 Total NaN in row 783 : 2
 Total NaN in row 784 : 2
 Total NaN in row 785 : 2
 Total NaN in row 786 : 2
 Total NaN in row 787 : 1
 Total NaN in row 788 : 1
 Total NaN in row 789 : 9
 Total NaN in row 790 : 2
 Total NaN in row 791 : 0
 Total NaN in row 792 : 0
 Total NaN in row 793 : 9
 Total NaN in row 794 : 0
 Total NaN in row 795 : 9
 Total NaN in row 796 : 9
 Total NaN in row 797 : 2
 Total NaN in row 798 : 9
 Total NaN in row 799 : 0
 Total NaN in row 800 : 9
 Total NaN in row 801 : 0
 Total NaN in row 802 : 1
 Total NaN in row 803 : 1
 Total NaN in row 804 : 2
 Total NaN in row 805 : 0
 Total NaN in row 806 : 10
 Total NaN in row 807 : 2
 Total NaN in row 808 : 2
 Total NaN in row 809 : 0
 Total NaN in row 810 : 9
 Total NaN in row 811 : 9
 Total NaN in row 812 : 9
 Total NaN in row 813 : 9
 Total NaN in row 814 : 0
 Total NaN in row 815 : 2
 Total NaN in row 816 : 2
 Total NaN in row 817 : 0
 Total NaN in row 818 : 1
 Total NaN in row 819 : 2
 Total NaN in row 820 : 0
 Total NaN in row 821 : 1
 Total NaN in row 822 : 9
 Total NaN in row 823 : 2
 Total NaN in row 824 : 2
 Total NaN in row 825 : 0
 Total NaN in row 826 : 0
 Total NaN in row 827 : 2
 Total NaN in row 828 : 2
 Total NaN in row 829 : 0
 Total NaN in row 830 : 1
 Total NaN in row 831 : 9
 Total NaN in row 832 : 1
 Total NaN in row 833 : 0
 Total NaN in row 834 : 0
 Total NaN in row 835 : 0
 Total NaN in row 836 : 3
 Total NaN in row 837 : 0
 Total NaN in row 838 : 0
 Total NaN in row 839 : 2
 Total NaN in row 840 : 0
 Total NaN in row 841 : 0
 Total NaN in row 842 : 0
 Total NaN in row 843 : 3
 Total NaN in row 844 : 0
 Total NaN in row 845 : 1
 Total NaN in row 846 : 2
 Total NaN in row 847 : 2
 Total NaN in row 848 : 3
 Total NaN in row 849 : 0
 Total NaN in row 850 : 0
 Total NaN in row 851 : 0
 Total NaN in row 852 : 0
 Total NaN in row 853 : 9
 Total NaN in row 854 : 9
 Total NaN in row 855 : 0
 Total NaN in row 856 : 0
 Total NaN in row 857 : 1
 Total NaN in row 858 : 1
 Total NaN in row 859 : 0
 Total NaN in row 860 : 0
 Total NaN in row 861 : 2
 Total NaN in row 862 : 0
 Total NaN in row 863 : 9
 Total NaN in row 864 : 9
 Total NaN in row 865 : 2
 Total NaN in row 866 : 2
 Total NaN in row 867 : 10
 Total NaN in row 868 : 9
 Total NaN in row 869 : 1
 Total NaN in row 870 : 2
 Total NaN in row 871 : 0
 Total NaN in row 872 : 1
 Total NaN in row 873 : 10
 Total NaN in row 874 : 2
 Total NaN in row 875 : 2
 Total NaN in row 876 : 0
 Total NaN in row 877 : 1
 Total NaN in row 878 : 1
 Total NaN in row 879 : 1
 Total NaN in row 880 : 9
 Total NaN in row 881 : 10
 Total NaN in row 882 : 10
 Total NaN in row 883 : 0
 Total NaN in row 884 : 2
 Total NaN in row 885 : 0
 Total NaN in row 886 : 0
 Total NaN in row 887 : 9
 Total NaN in row 888 : 1
 Total NaN in row 889 : 9
 Total NaN in row 890 : 0
 Total NaN in row 891 : 9
 Total NaN in row 892 : 0
 Total NaN in row 893 : 10
 Total NaN in row 894 : 9
 Total NaN in row 895 : 9
 Total NaN in row 896 : 9
 Total NaN in row 897 : 0
 Total NaN in row 898 : 2
 Total NaN in row 899 : 1
 Total NaN in row 900 : 9
 Total NaN in row 901 : 0
 Total NaN in row 902 : 0
 Total NaN in row 903 : 0
 Total NaN in row 904 : 9
 Total NaN in row 905 : 2
 Total NaN in row 906 : 0
 Total NaN in row 907 : 9
 Total NaN in row 908 : 2
 Total NaN in row 909 : 1
 Total NaN in row 910 : 9
 Total NaN in row 911 : 9
 Total NaN in row 912 : 0
 Total NaN in row 913 : 10
 Total NaN in row 914 : 9
 Total NaN in row 915 : 0
 Total NaN in row 916 : 10
 Total NaN in row 917 : 9
 Total NaN in row 918 : 0
 Total NaN in row 919 : 2
 Total NaN in row 920 : 1
 Total NaN in row 921 : 9
 Total NaN in row 922 : 10
 Total NaN in row 923 : 1
 Total NaN in row 924 : 3
 Total NaN in row 925 : 1
 Total NaN in row 926 : 0
 Total NaN in row 927 : 9
 Total NaN in row 928 : 9
 Total NaN in row 929 : 1
 Total NaN in row 930 : 1
 Total NaN in row 931 : 2
 Total NaN in row 932 : 0
 Total NaN in row 933 : 2
 Total NaN in row 934 : 0
 Total NaN in row 935 : 1
 Total NaN in row 936 : 2
 Total NaN in row 937 : 0
 Total NaN in row 938 : 2
 Total NaN in row 939 : 2
 Total NaN in row 940 : 9
 Total NaN in row 941 : 2
 Total NaN in row 942 : 0
 Total NaN in row 943 : 3
 Total NaN in row 944 : 7
 Total NaN in row 945 : 2
 Total NaN in row 946 : 1
 Total NaN in row 947 : 2
 Total NaN in row 948 : 10
 Total NaN in row 949 : 1
 Total NaN in row 950 : 10
 Total NaN in row 951 : 1
 Total NaN in row 952 : 3
 Total NaN in row 953 : 9
 Total NaN in row 954 : 9
 Total NaN in row 955 : 10
 Total NaN in row 956 : 0
 Total NaN in row 957 : 0
 Total NaN in row 958 : 3
 Total NaN in row 959 : 2
 Total NaN in row 960 : 9
 Total NaN in row 961 : 10
 Total NaN in row 962 : 3
 Total NaN in row 963 : 0
 Total NaN in row 964 : 2
 Total NaN in row 965 : 2
 Total NaN in row 966 : 2
 Total NaN in row 967 : 9
 Total NaN in row 968 : 10
 Total NaN in row 969 : 1
 Total NaN in row 970 : 0
 Total NaN in row 971 : 0
 Total NaN in row 972 : 1
 Total NaN in row 973 : 3
 Total NaN in row 974 : 1
 Total NaN in row 975 : 9
 Total NaN in row 976 : 2
 Total NaN in row 977 : 2
 Total NaN in row 978 : 2
 Total NaN in row 979 : 9
 Total NaN in row 980 : 3
 Total NaN in row 981 : 1
 Total NaN in row 982 : 1
 Total NaN in row 983 : 0
 Total NaN in row 984 : 0
 Total NaN in row 985 : 2
 Total NaN in row 986 : 1
 Total NaN in row 987 : 0
 Total NaN in row 988 : 3
 Total NaN in row 989 : 0
 Total NaN in row 990 : 3
 Total NaN in row 991 : 2
 Total NaN in row 992 : 10
 Total NaN in row 993 : 9
 Total NaN in row 994 : 10
 Total NaN in row 995 : 9
 Total NaN in row 996 : 1
 Total NaN in row 997 : 0
 Total NaN in row 998 : 10
 Total NaN in row 999 : 2
 Total NaN in row 1000 : 0
 Total NaN in row 1001 : 2
 Total NaN in row 1002 : 10
 Total NaN in row 1003 : 0
 Total NaN in row 1004 : 9
 Total NaN in row 1005 : 1
 Total NaN in row 1006 : 2
 Total NaN in row 1007 : 0
 Total NaN in row 1008 : 1
 Total NaN in row 1009 : 1
 Total NaN in row 1010 : 0
 Total NaN in row 1011 : 2
 Total NaN in row 1012 : 0
 Total NaN in row 1013 : 0
 Total NaN in row 1014 : 0
 Total NaN in row 1015 : 2
 Total NaN in row 1016 : 9
 Total NaN in row 1017 : 9
 Total NaN in row 1018 : 2
 Total NaN in row 1019 : 0
 Total NaN in row 1020 : 0
 Total NaN in row 1021 : 0
 Total NaN in row 1022 : 0
 Total NaN in row 1023 : 1
 Total NaN in row 1024 : 1
 Total NaN in row 1025 : 9
 Total NaN in row 1026 : 0
 Total NaN in row 1027 : 0
 Total NaN in row 1028 : 1
 Total NaN in row 1029 : 10
 Total NaN in row 1030 : 2
 Total NaN in row 1031 : 0
 Total NaN in row 1032 : 0
 Total NaN in row 1033 : 0
 Total NaN in row 1034 : 0
 Total NaN in row 1035 : 2
 Total NaN in row 1036 : 2
 Total NaN in row 1037 : 2
 Total NaN in row 1038 : 10
 Total NaN in row 1039 : 3
 Total NaN in row 1040 : 0
 Total NaN in row 1041 : 10
 Total NaN in row 1042 : 2
 Total NaN in row 1043 : 0
 Total NaN in row 1044 : 1
 Total NaN in row 1045 : 1
 Total NaN in row 1046 : 1
 Total NaN in row 1047 : 2
 Total NaN in row 1048 : 2
 Total NaN in row 1049 : 9
 Total NaN in row 1050 : 0
 Total NaN in row 1051 : 3
 Total NaN in row 1052 : 1
 Total NaN in row 1053 : 2
 Total NaN in row 1054 : 2
 Total NaN in row 1055 : 10
 Total NaN in row 1056 : 0
 Total NaN in row 1057 : 0
 Total NaN in row 1058 : 1
 Total NaN in row 1059 : 2
 Total NaN in row 1060 : 2
 Total NaN in row 1061 : 0
 Total NaN in row 1062 : 2
 Total NaN in row 1063 : 0
 Total NaN in row 1064 : 9
 Total NaN in row 1065 : 3
 Total NaN in row 1066 : 2
 Total NaN in row 1067 : 0
 Total NaN in row 1068 : 10
 Total NaN in row 1069 : 0
 Total NaN in row 1070 : 0
 Total NaN in row 1071 : 1
 Total NaN in row 1072 : 0
 Total NaN in row 1073 : 9
 Total NaN in row 1074 : 0
 Total NaN in row 1075 : 2
 Total NaN in row 1076 : 2
 Total NaN in row 1077 : 1
 Total NaN in row 1078 : 2
 Total NaN in row 1079 : 1
 Total NaN in row 1080 : 0
 Total NaN in row 1081 : 9
 Total NaN in row 1082 : 2
 Total NaN in row 1083 : 1
 Total NaN in row 1084 : 2

 Total NaN in row 1085 : 2
 Total NaN in row 1086 : 9
 Total NaN in row 1087 : 0
 Total NaN in row 1088 : 1
 Total NaN in row 1089 : 2
 Total NaN in row 1090 : 0
 Total NaN in row 1091 : 1
 Total NaN in row 1092 : 0
 Total NaN in row 1093 : 0
 Total NaN in row 1094 : 1
 Total NaN in row 1095 : 0
 Total NaN in row 1096 : 9
 Total NaN in row 1097 : 0
 Total NaN in row 1098 : 0
 Total NaN in row 1099 : 1
 Total NaN in row 1100 : 1
 Total NaN in row 1101 : 0
 Total NaN in row 1102 : 3
 Total NaN in row 1103 : 2
 Total NaN in row 1104 : 9
 Total NaN in row 1105 : 3
 Total NaN in row 1106 : 0
 Total NaN in row 1107 : 1
 Total NaN in row 1108 : 0
 Total NaN in row 1109 : 9
 Total NaN in row 1110 : 1
 Total NaN in row 1111 : 9
 Total NaN in row 1112 : 0
 Total NaN in row 1113 : 3
 Total NaN in row 1114 : 9
 Total NaN in row 1115 : 2
 Total NaN in row 1116 : 0
 Total NaN in row 1117 : 10
 Total NaN in row 1118 : 2
 Total NaN in row 1119 : 2
 Total NaN in row 1120 : 1
 Total NaN in row 1121 : 9
 Total NaN in row 1122 : 0
 Total NaN in row 1123 : 0
 Total NaN in row 1124 : 1
 Total NaN in row 1125 : 2
 Total NaN in row 1126 : 9
 Total NaN in row 1127 : 2
 Total NaN in row 1128 : 3
 Total NaN in row 1129 : 0
 Total NaN in row 1130 : 9
 Total NaN in row 1131 : 2
 Total NaN in row 1132 : 10
 Total NaN in row 1133 : 0
 Total NaN in row 1134 : 1
 Total NaN in row 1135 : 1
 Total NaN in row 1136 : 2
 Total NaN in row 1137 : 0
 Total NaN in row 1138 : 2
 Total NaN in row 1139 : 0
 Total NaN in row 1140 : 1
 Total NaN in row 1141 : 1
 Total NaN in row 1142 : 1
 Total NaN in row 1143 : 0
 Total NaN in row 1144 : 1
 Total NaN in row 1145 : 2
 Total NaN in row 1146 : 21
 Total NaN in row 1147 : 2
 Total NaN in row 1148 : 3
 Total NaN in row 1149 : 0
 Total NaN in row 1150 : 1
 Total NaN in row 1151 : 1
 Total NaN in row 1152 : 2
 Total NaN in row 1153 : 9
 Total NaN in row 1154 : 2
 Total NaN in row 1155 : 1
 Total NaN in row 1156 : 1
 Total NaN in row 1157 : 1
 Total NaN in row 1158 : 5
 Total NaN in row 1159 : 0
 Total NaN in row 1160 : 3
 Total NaN in row 1161 : 1
 Total NaN in row 1162 : 2
 Total NaN in row 1163 : 2
 Total NaN in row 1164 : 0
 Total NaN in row 1165 : 1
 Total NaN in row 1166 : 1
 Total NaN in row 1167 : 9
 Total NaN in row 1168 : 0
 Total NaN in row 1169 : 1
 Total NaN in row 1170 : 0
 Total NaN in row 1171 : 10
 Total NaN in row 1172 : 9
 Total NaN in row 1173 : 9
 Total NaN in row 1174 : 0
 Total NaN in row 1175 : 9
 Total NaN in row 1176 : 10
 Total NaN in row 1177 : 10
 Total NaN in row 1178 : 9
 Total NaN in row 1179 : 3
 Total NaN in row 1180 : 9
 Total NaN in row 1181 : 9
 Total NaN in row 1182 : 1
 Total NaN in row 1183 : 1
 Total NaN in row 1184 : 3
 Total NaN in row 1185 : 1
 Total NaN in row 1186 : 1
 Total NaN in row 1187 : 0
 Total NaN in row 1188 : 0
 Total NaN in row 1189 : 0
 Total NaN in row 1190 : 2
 Total NaN in row 1191 : 2
 Total NaN in row 1192 : 9
 Total NaN in row 1193 : 0
 Total NaN in row 1194 : 10
 Total NaN in row 1195 : 10
 Total NaN in row 1196 : 3
 Total NaN in row 1197 : 0
 Total NaN in row 1198 : 10
 Total NaN in row 1199 : 1
 Total NaN in row 1200 : 3
 Total NaN in row 1201 : 2
 Total NaN in row 1202 : 2
 Total NaN in row 1203 : 2
 Total NaN in row 1204 : 1
 Total NaN in row 1205 : 0
 Total NaN in row 1206 : 9
 Total NaN in row 1207 : 0
 Total NaN in row 1208 : 1
 Total NaN in row 1209 : 10
 Total NaN in row 1210 : 1
 Total NaN in row 1211 : 3
 Total NaN in row 1212 : 1
 Total NaN in row 1213 : 2
 Total NaN in row 1214 : 0
 Total NaN in row 1215 : 9
 Total NaN in row 1216 : 1
 Total NaN in row 1217 : 9
 Total NaN in row 1218 : 2
 Total NaN in row 1219 : 2
 Total NaN in row 1220 : 0
 Total NaN in row 1221 : 0
 Total NaN in row 1222 : 0
 Total NaN in row 1223 : 10
 Total NaN in row 1224 : 10
 Total NaN in row 1225 : 9
 Total NaN in row 1226 : 9
 Total NaN in row 1227 : 2
 Total NaN in row 1228 : 9
 Total NaN in row 1229 : 2
 Total NaN in row 1230 : 1
 Total NaN in row 1231 : 2
 Total NaN in row 1232 : 1
 Total NaN in row 1233 : 0
 Total NaN in row 1234 : 0
 Total NaN in row 1235 : 0
 Total NaN in row 1236 : 10
 Total NaN in row 1237 : 0
 Total NaN in row 1238 : 0
 Total NaN in row 1239 : 9
 Total NaN in row 1240 : 9
 Total NaN in row 1241 : 0
 Total NaN in row 1242 : 0
 Total NaN in row 1243 : 2
 Total NaN in row 1244 : 1
 Total NaN in row 1245 : 0
 Total NaN in row 1246 : 9
 Total NaN in row 1247 : 2
 Total NaN in row 1248 : 2
 Total NaN in row 1249 : 3
 Total NaN in row 1250 : 0
 Total NaN in row 1251 : 0
 Total NaN in row 1252 : 0
 Total NaN in row 1253 : 9
 Total NaN in row 1254 : 0
 Total NaN in row 1255 : 10
 Total NaN in row 1256 : 1
 Total NaN in row 1257 : 1
 Total NaN in row 1258 : 0
 Total NaN in row 1259 : 2
 Total NaN in row 1260 : 3
 Total NaN in row 1261 : 0
 Total NaN in row 1262 : 0
 Total NaN in row 1263 : 0
 Total NaN in row 1264 : 1
 Total NaN in row 1265 : 3
 Total NaN in row 1266 : 2
 Total NaN in row 1267 : 3
 Total NaN in row 1268 : 0
 Total NaN in row 1269 : 9
 Total NaN in row 1270 : 9
 Total NaN in row 1271 : 2
 Total NaN in row 1272 : 2
 Total NaN in row 1273 : 0
 Total NaN in row 1274 : 0
 Total NaN in row 1275 : 9
 Total NaN in row 1276 : 0
 Total NaN in row 1277 : 9
 Total NaN in row 1278 : 1
 Total NaN in row 1279 : 2
 Total NaN in row 1280 : 0
 Total NaN in row 1281 : 0
 Total NaN in row 1282 : 2
 Total NaN in row 1283 : 2
 Total NaN in row 1284 : 3
 Total NaN in row 1285 : 2
 Total NaN in row 1286 : 9
 Total NaN in row 1287 : 9
 Total NaN in row 1288 : 2
 Total NaN in row 1289 : 2
 Total NaN in row 1290 : 0
 Total NaN in row 1291 : 2
 Total NaN in row 1292 : 9
 Total NaN in row 1293 : 1
 Total NaN in row 1294 : 2
 Total NaN in row 1295 : 0
 Total NaN in row 1296 : 2
 Total NaN in row 1297 : 0
 Total NaN in row 1298 : 9
 Total NaN in row 1299 : 0
 Total NaN in row 1300 : 3
 Total NaN in row 1301 : 0
 Total NaN in row 1302 : 9
 Total NaN in row 1303 : 1
 Total NaN in row 1304 : 0
 Total NaN in row 1305 : 1
 Total NaN in row 1306 : 2
 Total NaN in row 1307 : 0
 Total NaN in row 1308 : 9
 Total NaN in row 1309 : 2
 Total NaN in row 1310 : 9
 Total NaN in row 1311 : 9
 Total NaN in row 1312 : 0
 Total NaN in row 1313 : 9
 Total NaN in row 1314 : 2
 Total NaN in row 1315 : 1
 Total NaN in row 1316 : 2
 Total NaN in row 1317 : 0
 Total NaN in row 1318 : 0
 Total NaN in row 1319 : 0
 Total NaN in row 1320 : 9
 Total NaN in row 1321 : 2
 Total NaN in row 1322 : 2
 Total NaN in row 1323 : 2
 Total NaN in row 1324 : 0
 Total NaN in row 1325 : 2
 Total NaN in row 1326 : 1
 Total NaN in row 1327 : 9
 Total NaN in row 1328 : 9
 Total NaN in row 1329 : 9
 Total NaN in row 1330 : 9
 Total NaN in row 1331 : 1
 Total NaN in row 1332 : 0
 Total NaN in row 1333 : 9
 Total NaN in row 1334 : 9
 Total NaN in row 1335 : 9
 Total NaN in row 1336 : 0
 Total NaN in row 1337 : 9
 Total NaN in row 1338 : 9
 Total NaN in row 1339 : 3
 Total NaN in row 1340 : 0
 Total NaN in row 1341 : 2
 Total NaN in row 1342 : 10
 Total NaN in row 1343 : 0
 Total NaN in row 1344 : 3
 Total NaN in row 1345 : 0
 Total NaN in row 1346 : 3
 Total NaN in row 1347 : 9
 Total NaN in row 1348 : 0
 Total NaN in row 1349 : 21
 Total NaN in row 1350 : 2
 Total NaN in row 1351 : 0
 Total NaN in row 1352 : 1
 Total NaN in row 1353 : 2
 Total NaN in row 1354 : 9
 Total NaN in row 1355 : 1
 Total NaN in row 1356 : 0
 Total NaN in row 1357 : 2
 Total NaN in row 1358 : 1
 Total NaN in row 1359 : 1
 Total NaN in row 1360 : 10
 Total NaN in row 1361 : 2
 Total NaN in row 1362 : 9
 Total NaN in row 1363 : 9
 Total NaN in row 1364 : 2
 Total NaN in row 1365 : 0
 Total NaN in row 1366 : 0
 Total NaN in row 1367 : 9
 Total NaN in row 1368 : 2
 Total NaN in row 1369 : 9
 Total NaN in row 1370 : 0
 Total NaN in row 1371 : 9
 Total NaN in row 1372 : 2
 Total NaN in row 1373 : 9
 Total NaN in row 1374 : 2
 Total NaN in row 1375 : 9
 Total NaN in row 1376 : 1
 Total NaN in row 1377 : 1
 Total NaN in row 1378 : 9
 Total NaN in row 1379 : 2
 Total NaN in row 1380 : 2
 Total NaN in row 1381 : 2
 Total NaN in row 1382 : 0
 Total NaN in row 1383 : 9
 Total NaN in row 1384 : 2
 Total NaN in row 1385 : 2
 Total NaN in row 1386 : 9
 Total NaN in row 1387 : 9
 Total NaN in row 1388 : 10
 Total NaN in row 1389 : 0
 Total NaN in row 1390 : 2
 Total NaN in row 1391 : 0
 Total NaN in row 1392 : 2
 Total NaN in row 1393 : 0
 Total NaN in row 1394 : 0
 Total NaN in row 1395 : 2
 Total NaN in row 1396 : 1
 Total NaN in row 1397 : 9
 Total NaN in row 1398 : 1
 Total NaN in row 1399 : 0
 Total NaN in row 1400 : 9
 Total NaN in row 1401 : 0
 Total NaN in row 1402 : 0
 Total NaN in row 1403 : 0
 Total NaN in row 1404 : 0
 Total NaN in row 1405 : 0
 Total NaN in row 1406 : 0
 Total NaN in row 1407 : 1
 Total NaN in row 1408 : 2
 Total NaN in row 1409 : 2
 Total NaN in row 1410 : 0
 Total NaN in row 1411 : 1
 Total NaN in row 1412 : 9
 Total NaN in row 1413 : 2
 Total NaN in row 1414 : 0
 Total NaN in row 1415 : 1
 Total NaN in row 1416 : 0
 Total NaN in row 1417 : 1
 Total NaN in row 1418 : 9
 Total NaN in row 1419 : 9
 Total NaN in row 1420 : 9
 Total NaN in row 1421 : 10
 Total NaN in row 1422 : 2
 Total NaN in row 1423 : 9
 Total NaN in row 1424 : 1
 Total NaN in row 1425 : 0
 Total NaN in row 1426 : 3
 Total NaN in row 1427 : 2
 Total NaN in row 1428 : 2
 Total NaN in row 1429 : 0
 Total NaN in row 1430 : 0
 Total NaN in row 1431 : 2
 Total NaN in row 1432 : 9
 Total NaN in row 1433 : 9
 Total NaN in row 1434 : 2
 Total NaN in row 1435 : 9
 Total NaN in row 1436 : 1
 Total NaN in row 1437 : 0
 Total NaN in row 1438 : 0
 Total NaN in row 1439 : 0
 Total NaN in row 1440 : 2
 Total NaN in row 1441 : 3
 Total NaN in row 1442 : 9
 Total NaN in row 1443 : 2
 Total NaN in row 1444 : 9
 Total NaN in row 1445 : 2
 Total NaN in row 1446 : 2
 Total NaN in row 1447 : 9
 Total NaN in row 1448 : 2
 Total NaN in row 1449 : 9
 Total NaN in row 1450 : 9
 Total NaN in row 1451 : 9
 Total NaN in row 1452 : 9
 Total NaN in row 1453 : 0
 Total NaN in row 1454 : 10
 Total NaN in row 1455 : 8
 Total NaN in row 1456 : 0
 Total NaN in row 1457 : 2
 Total NaN in row 1458 : 9
 Total NaN in row 1459 : 0
 Total NaN in row 1460 : 3
 Total NaN in row 1461 : 2
 Total NaN in row 1462 : 2
 Total NaN in row 1463 : 9
 Total NaN in row 1464 : 0
 Total NaN in row 1465 : 0
 Total NaN in row 1466 : 1
 Total NaN in row 1467 : 9
 Total NaN in row 1468 : 9
 Total NaN in row 1469 : 2
 Total NaN in row 1470 : 1
 Total NaN in row 1471 : 0
 Total NaN in row 1472 : 2
 Total NaN in row 1473 : 10
 Total NaN in row 1474 : 0
 Total NaN in row 1475 : 2
 Total NaN in row 1476 : 0
 Total NaN in row 1477 : 1
 Total NaN in row 1478 : 2
 Total NaN in row 1479 : 9
 Total NaN in row 1480 : 2
 Total NaN in row 1481 : 0
 Total NaN in row 1482 : 2
 Total NaN in row 1483 : 9
 Total NaN in row 1484 : 2
 Total NaN in row 1485 : 0
 Total NaN in row 1486 : 0
 Total NaN in row 1487 : 9
 Total NaN in row 1488 : 0
 Total NaN in row 1489 : 0
 Total NaN in row 1490 : 1
 Total NaN in row 1491 : 9
 Total NaN in row 1492 : 2
 Total NaN in row 1493 : 0
 Total NaN in row 1494 : 0
 Total NaN in row 1495 : 2
 Total NaN in row 1496 : 0
 Total NaN in row 1497 : 9
 Total NaN in row 1498 : 0
 Total NaN in row 1499 : 10
 Total NaN in row 1500 : 9
 Total NaN in row 1501 : 0
 Total NaN in row 1502 : 0
 Total NaN in row 1503 : 2
 Total NaN in row 1504 : 2
 Total NaN in row 1505 : 2
 Total NaN in row 1506 : 0
 Total NaN in row 1507 : 2
 Total NaN in row 1508 : 0
 Total NaN in row 1509 : 0
 Total NaN in row 1510 : 0
 Total NaN in row 1511 : 1
 Total NaN in row 1512 : 2
 Total NaN in row 1513 : 1
 Total NaN in row 1514 : 2
 Total NaN in row 1515 : 0
 Total NaN in row 1516 : 2
 Total NaN in row 1517 : 3
 Total NaN in row 1518 : 2
 Total NaN in row 1519 : 1
 Total NaN in row 1520 : 2
 Total NaN in row 1521 : 0
 Total NaN in row 1522 : 2
 Total NaN in row 1523 : 9
 Total NaN in row 1524 : 1
 Total NaN in row 1525 : 2
 Total NaN in row 1526 : 1

 Total NaN in row 1527 : 0
 Total NaN in row 1528 : 9
 Total NaN in row 1529 : 9
 Total NaN in row 1530 : 2
 Total NaN in row 1531 : 1
 Total NaN in row 1532 : 0
 Total NaN in row 1533 : 0
 Total NaN in row 1534 : 0
 Total NaN in row 1535 : 9
 Total NaN in row 1536 : 2
 Total NaN in row 1537 : 2
 Total NaN in row 1538 : 0
 Total NaN in row 1539 : 1
 Total NaN in row 1540 : 0
 Total NaN in row 1541 : 0
 Total NaN in row 1542 : 0
 Total NaN in row 1543 : 0
 Total NaN in row 1544 : 0
 Total NaN in row 1545 : 0
 Total NaN in row 1546 : 1
 Total NaN in row 1547 : 9
 Total NaN in row 1548 : 2
 Total NaN in row 1549 : 0
 Total NaN in row 1550 : 0
 Total NaN in row 1551 : 1
 Total NaN in row 1552 : 0
 Total NaN in row 1553 : 2
 Total NaN in row 1554 : 0
 Total NaN in row 1555 : 9
 Total NaN in row 1556 : 9
 Total NaN in row 1557 : 3
 Total NaN in row 1558 : 9
 Total NaN in row 1559 : 2
 Total NaN in row 1560 : 1
 Total NaN in row 1561 : 2
 Total NaN in row 1562 : 9
 Total NaN in row 1563 : 0
 Total NaN in row 1564 : 0
 Total NaN in row 1565 : 2
 Total NaN in row 1566 : 9
 Total NaN in row 1567 : 0
 Total NaN in row 1568 : 9
 Total NaN in row 1569 : 0
 Total NaN in row 1570 : 0
 Total NaN in row 1571 : 3
 Total NaN in row 1572 : 0
 Total NaN in row 1573 : 0
 Total NaN in row 1574 : 1
 Total NaN in row 1575 : 0
 Total NaN in row 1576 : 0
 Total NaN in row 1577 : 0
 Total NaN in row 1578 : 10
 Total NaN in row 1579 : 0
 Total NaN in row 1580 : 0
 Total NaN in row 1581 : 2
 Total NaN in row 1582 : 1
 Total NaN in row 1583 : 2
 Total NaN in row 1584 : 2
 Total NaN in row 1585 : 0
 Total NaN in row 1586 : 9
 Total NaN in row 1587 : 2
 Total NaN in row 1588 : 2
 Total NaN in row 1589 : 0
 Total NaN in row 1590 : 2
 Total NaN in row 1591 : 9
 Total NaN in row 1592 : 2
 Total NaN in row 1593 : 2
 Total NaN in row 1594 : 10
 Total NaN in row 1595 : 2
 Total NaN in row 1596 : 0
 Total NaN in row 1597 : 2
 Total NaN in row 1598 : 0
 Total NaN in row 1599 : 2
 Total NaN in row 1600 : 0
 Total NaN in row 1601 : 2
 Total NaN in row 1602 : 0
 Total NaN in row 1603 : 2
 Total NaN in row 1604 : 9
 Total NaN in row 1605 : 9
 Total NaN in row 1606 : 2
 Total NaN in row 1607 : 2
 Total NaN in row 1608 : 2
 Total NaN in row 1609 : 2
 Total NaN in row 1610 : 9
 Total NaN in row 1611 : 2
 Total NaN in row 1612 : 9
 Total NaN in row 1613 : 0
 Total NaN in row 1614 : 9
 Total NaN in row 1615 : 2
 Total NaN in row 1616 : 10
 Total NaN in row 1617 : 0
 Total NaN in row 1618 : 9
 Total NaN in row 1619 : 1
 Total NaN in row 1620 : 2
 Total NaN in row 1621 : 0
 Total NaN in row 1622 : 9
 Total NaN in row 1623 : 0
 Total NaN in row 1624 : 0
 Total NaN in row 1625 : 1
 Total NaN in row 1626 : 0
 Total NaN in row 1627 : 0
 Total NaN in row 1628 : 2
 Total NaN in row 1629 : 9
 Total NaN in row 1630 : 2
 Total NaN in row 1631 : 2
 Total NaN in row 1632 : 0
 Total NaN in row 1633 : 1
 Total NaN in row 1634 : 0
 Total NaN in row 1635 : 2
 Total NaN in row 1636 : 1
 Total NaN in row 1637 : 1
 Total NaN in row 1638 : 10
 Total NaN in row 1639 : 1
 Total NaN in row 1640 : 1
 Total NaN in row 1641 : 10
 Total NaN in row 1642 : 0
 Total NaN in row 1643 : 1
 Total NaN in row 1644 : 2
 Total NaN in row 1645 : 0
 Total NaN in row 1646 : 0
 Total NaN in row 1647 : 0
 Total NaN in row 1648 : 1
 Total NaN in row 1649 : 0
 Total NaN in row 1650 : 1
 Total NaN in row 1651 : 2
 Total NaN in row 1652 : 0
 Total NaN in row 1653 : 0
 Total NaN in row 1654 : 0
 Total NaN in row 1655 : 0
 Total NaN in row 1656 : 0
 Total NaN in row 1657 : 0
 Total NaN in row 1658 : 0
 Total NaN in row 1659 : 2
 Total NaN in row 1660 : 2
 Total NaN in row 1661 : 0
 Total NaN in row 1662 : 0
 Total NaN in row 1663 : 2
 Total NaN in row 1664 : 0
 Total NaN in row 1665 : 1
 Total NaN in row 1666 : 2
 Total NaN in row 1667 : 1
 Total NaN in row 1668 : 0
 Total NaN in row 1669 : 0
 Total NaN in row 1670 : 1
 Total NaN in row 1671 : 0
 Total NaN in row 1672 : 1
 Total NaN in row 1673 : 2
 Total NaN in row 1674 : 1
 Total NaN in row 1675 : 2
 Total NaN in row 1676 : 0
 Total NaN in row 1677 : 0
 Total NaN in row 1678 : 9
 Total NaN in row 1679 : 9
 Total NaN in row 1680 : 1
 Total NaN in row 1681 : 10
 Total NaN in row 1682 : 1
 Total NaN in row 1683 : 7
 Total NaN in row 1684 : 2
 Total NaN in row 1685 : 0
 Total NaN in row 1686 : 0
 Total NaN in row 1687 : 1
 Total NaN in row 1688 : 1
 Total NaN in row 1689 : 1
 Total NaN in row 1690 : 1
 Total NaN in row 1691 : 1
 Total NaN in row 1692 : 2
 Total NaN in row 1693 : 0
 Total NaN in row 1694 : 0
 Total NaN in row 1695 : 0
 Total NaN in row 1696 : 2
 Total NaN in row 1697 : 0
 Total NaN in row 1698 : 0
 Total NaN in row 1699 : 0
 Total NaN in row 1700 : 10
 Total NaN in row 1701 : 0
 Total NaN in row 1702 : 9
 Total NaN in row 1703 : 9
 Total NaN in row 1704 : 10
 Total NaN in row 1705 : 1
 Total NaN in row 1706 : 0
 Total NaN in row 1707 : 0
 Total NaN in row 1708 : 0
 Total NaN in row 1709 : 2
 Total NaN in row 1710 : 9
 Total NaN in row 1711 : 2
 Total NaN in row 1712 : 10
 Total NaN in row 1713 : 1
 Total NaN in row 1714 : 9
 Total NaN in row 1715 : 1
 Total NaN in row 1716 : 1
 Total NaN in row 1717 : 9
 Total NaN in row 1718 : 0
 Total NaN in row 1719 : 9
 Total NaN in row 1720 : 0
 Total NaN in row 1721 : 1
 Total NaN in row 1722 : 0
 Total NaN in row 1723 : 1
 Total NaN in row 1724 : 9
 Total NaN in row 1725 : 2
 Total NaN in row 1726 : 1
 Total NaN in row 1727 : 9
 Total NaN in row 1728 : 0
 Total NaN in row 1729 : 0
 Total NaN in row 1730 : 0
 Total NaN in row 1731 : 2
 Total NaN in row 1732 : 0
 Total NaN in row 1733 : 2
 Total NaN in row 1734 : 0
 Total NaN in row 1735 : 2
 Total NaN in row 1736 : 1
 Total NaN in row 1737 : 1
 Total NaN in row 1738 : 0
 Total NaN in row 1739 : 3
 Total NaN in row 1740 : 1
 Total NaN in row 1741 : 2
 Total NaN in row 1742 : 9
 Total NaN in row 1743 : 0
 Total NaN in row 1744 : 1
 Total NaN in row 1745 : 1
 Total NaN in row 1746 : 0
 Total NaN in row 1747 : 1
 Total NaN in row 1748 : 0
 Total NaN in row 1749 : 2
 Total NaN in row 1750 : 0
 Total NaN in row 1751 : 10
 Total NaN in row 1752 : 3
 Total NaN in row 1753 : 1
 Total NaN in row 1754 : 0
 Total NaN in row 1755 : 2
 Total NaN in row 1756 : 10
 Total NaN in row 1757 : 0
 Total NaN in row 1758 : 0
 Total NaN in row 1759 : 0
 Total NaN in row 1760 : 3
 Total NaN in row 1761 : 2
 Total NaN in row 1762 : 2
 Total NaN in row 1763 : 3
 Total NaN in row 1764 : 0
 Total NaN in row 1765 : 2
 Total NaN in row 1766 : 10
 Total NaN in row 1767 : 10
 Total NaN in row 1768 : 9
 Total NaN in row 1769 : 0
 Total NaN in row 1770 : 2
 Total NaN in row 1771 : 0
 Total NaN in row 1772 : 1
 Total NaN in row 1773 : 10
 Total NaN in row 1774 : 2
 Total NaN in row 1775 : 0
 Total NaN in row 1776 : 2
 Total NaN in row 1777 : 2
 Total NaN in row 1778 : 3
 Total NaN in row 1779 : 0
 Total NaN in row 1780 : 0
 Total NaN in row 1781 : 0
 Total NaN in row 1782 : 0
 Total NaN in row 1783 : 9
 Total NaN in row 1784 : 1
 Total NaN in row 1785 : 2
 Total NaN in row 1786 : 2
 Total NaN in row 1787 : 2
 Total NaN in row 1788 : 2
 Total NaN in row 1789 : 2
 Total NaN in row 1790 : 0
 Total NaN in row 1791 : 2
 Total NaN in row 1792 : 1
 Total NaN in row 1793 : 0
 Total NaN in row 1794 : 2
 Total NaN in row 1795 : 10
 Total NaN in row 1796 : 3
 Total NaN in row 1797 : 3
 Total NaN in row 1798 : 1
 Total NaN in row 1799 : 1
 Total NaN in row 1800 : 1
 Total NaN in row 1801 : 1
 Total NaN in row 1802 : 1
 Total NaN in row 1803 : 1
 Total NaN in row 1804 : 3
 Total NaN in row 1805 : 0
 Total NaN in row 1806 : 3
 Total NaN in row 1807 : 0
 Total NaN in row 1808 : 0
 Total NaN in row 1809 : 2
 Total NaN in row 1810 : 2
 Total NaN in row 1811 : 9
 Total NaN in row 1812 : 9
 Total NaN in row 1813 : 1
 Total NaN in row 1814 : 0
 Total NaN in row 1815 : 2
 Total NaN in row 1816 : 9
 Total NaN in row 1817 : 2
 Total NaN in row 1818 : 3
 Total NaN in row 1819 : 2
 Total NaN in row 1820 : 1
 Total NaN in row 1821 : 1
 Total NaN in row 1822 : 0
 Total NaN in row 1823 : 0
 Total NaN in row 1824 : 2
 Total NaN in row 1825 : 2
 Total NaN in row 1826 : 10
 Total NaN in row 1827 : 0
 Total NaN in row 1828 : 1
 Total NaN in row 1829 : 3
 Total NaN in row 1830 : 9
 Total NaN in row 1831 : 1
 Total NaN in row 1832 : 1
 Total NaN in row 1833 : 0
 Total NaN in row 1834 : 2
 Total NaN in row 1835 : 3
 Total NaN in row 1836 : 0
 Total NaN in row 1837 : 1
 Total NaN in row 1838 : 2
 Total NaN in row 1839 : 0
 Total NaN in row 1840 : 2

 Total NaN in row 1841 : 0
 Total NaN in row 1842 : 1
 Total NaN in row 1843 : 10
 Total NaN in row 1844 : 1
 Total NaN in row 1845 : 0
 Total NaN in row 1846 : 9
 Total NaN in row 1847 : 0
 Total NaN in row 1848 : 1
 Total NaN in row 1849 : 0
 Total NaN in row 1850 : 3
 Total NaN in row 1851 : 2
 Total NaN in row 1852 : 10
 Total NaN in row 1853 : 9
 Total NaN in row 1854 : 9
 Total NaN in row 1855 : 0
 Total NaN in row 1856 : 2
 Total NaN in row 1857 : 2
 Total NaN in row 1858 : 9
 Total NaN in row 1859 : 0
 Total NaN in row 1860 : 1
 Total NaN in row 1861 : 2
 Total NaN in row 1862 : 0
 Total NaN in row 1863 : 1
 Total NaN in row 1864 : 1
 Total NaN in row 1865 : 2
 Total NaN in row 1866 : 2
 Total NaN in row 1867 : 0
 Total NaN in row 1868 : 2
 Total NaN in row 1869 : 2
 Total NaN in row 1870 : 3
 Total NaN in row 1871 : 0
 Total NaN in row 1872 : 10
 Total NaN in row 1873 : 3
 Total NaN in row 1874 : 9
 Total NaN in row 1875 : 3
 Total NaN in row 1876 : 7
 Total NaN in row 1877 : 0
 Total NaN in row 1878 : 3
 Total NaN in row 1879 : 9
 Total NaN in row 1880 : 1
 Total NaN in row 1881 : 3
 Total NaN in row 1882 : 0
 Total NaN in row 1883 : 10
 Total NaN in row 1884 : 0
 Total NaN in row 1885 : 9
 Total NaN in row 1886 : 9
 Total NaN in row 1887 : 2
 Total NaN in row 1888 : 0
 Total NaN in row 1889 : 9
 Total NaN in row 1890 : 9
 Total NaN in row 1891 : 9
 Total NaN in row 1892 : 0
 Total NaN in row 1893 : 1
 Total NaN in row 1894 : 1
 Total NaN in row 1895 : 0
 Total NaN in row 1896 : 1
 Total NaN in row 1897 : 10
 Total NaN in row 1898 : 2
 Total NaN in row 1899 : 2
 Total NaN in row 1900 : 9
 Total NaN in row 1901 : 2
 Total NaN in row 1902 : 3
 Total NaN in row 1903 : 2
 Total NaN in row 1904 : 2
 Total NaN in row 1905 : 2
 Total NaN in row 1906 : 10
 Total NaN in row 1907 : 0
 Total NaN in row 1908 : 0
 Total NaN in row 1909 : 1
 Total NaN in row 1910 : 1
 Total NaN in row 1911 : 0
 Total NaN in row 1912 : 1
 Total NaN in row 1913 : 2
 Total NaN in row 1914 : 2
 Total NaN in row 1915 : 0
 Total NaN in row 1916 : 9
 Total NaN in row 1917 : 9
 Total NaN in row 1918 : 9
 Total NaN in row 1919 : 2
 Total NaN in row 1920 : 9
 Total NaN in row 1921 : 3
 Total NaN in row 1922 : 0
 Total NaN in row 1923 : 0
 Total NaN in row 1924 : 9
 Total NaN in row 1925 : 0
 Total NaN in row 1926 : 2
 Total NaN in row 1927 : 3
 Total NaN in row 1928 : 9
 Total NaN in row 1929 : 1
 Total NaN in row 1930 : 2
 Total NaN in row 1931 : 2
 Total NaN in row 1932 : 2
 Total NaN in row 1933 : 1
 Total NaN in row 1934 : 9
 Total NaN in row 1935 : 2
 Total NaN in row 1936 : 8
 Total NaN in row 1937 : 0
 Total NaN in row 1938 : 0
 Total NaN in row 1939 : 2
 Total NaN in row 1940 : 0
 Total NaN in row 1941 : 1
 Total NaN in row 1942 : 2
 Total NaN in row 1943 : 9
 Total NaN in row 1944 : 1
 Total NaN in row 1945 : 1
 Total NaN in row 1946 : 0
 Total NaN in row 1947 : 2
 Total NaN in row 1948 : 9
 Total NaN in row 1949 : 1
 Total NaN in row 1950 : 0
 Total NaN in row 1951 : 1
 Total NaN in row 1952 : 0
 Total NaN in row 1953 : 9
 Total NaN in row 1954 : 1
 Total NaN in row 1955 : 0
 Total NaN in row 1956 : 9
 Total NaN in row 1957 : 1
 Total NaN in row 1958 : 1
 Total NaN in row 1959 : 9
 Total NaN in row 1960 : 0
 Total NaN in row 1961 : 10
 Total NaN in row 1962 : 9
 Total NaN in row 1963 : 2
 Total NaN in row 1964 : 1
 Total NaN in row 1965 : 0
 Total NaN in row 1966 : 2
 Total NaN in row 1967 : 1
 Total NaN in row 1968 : 1
 Total NaN in row 1969 : 2
 Total NaN in row 1970 : 0
 Total NaN in row 1971 : 10
 Total NaN in row 1972 : 9
 Total NaN in row 1973 : 9
 Total NaN in row 1974 : 10
 Total NaN in row 1975 : 1
 Total NaN in row 1976 : 1
 Total NaN in row 1977 : 2
 Total NaN in row 1978 : 1
 Total NaN in row 1979 : 3
 Total NaN in row 1980 : 2
 Total NaN in row 1981 : 3
 Total NaN in row 1982 : 0
 Total NaN in row 1983 : 0
 Total NaN in row 1984 : 0
 Total NaN in row 1985 : 1
 Total NaN in row 1986 : 1
 Total NaN in row 1987 : 1
 Total NaN in row 1988 : 0
 Total NaN in row 1989 : 2
 Total NaN in row 1990 : 2
 Total NaN in row 1991 : 0
 Total NaN in row 1992 : 2
 Total NaN in row 1993 : 1
 Total NaN in row 1994 : 10
 Total NaN in row 1995 : 0
 Total NaN in row 1996 : 0
 Total NaN in row 1997 : 0
 Total NaN in row 1998 : 9
 Total NaN in row 1999 : 9
 Total NaN in row 2000 : 1
 Total NaN in row 2001 : 0
 Total NaN in row 2002 : 0
 Total NaN in row 2003 : 1
 Total NaN in row 2004 : 10
 Total NaN in row 2005 : 2
 Total NaN in row 2006 : 0
 Total NaN in row 2007 : 1
 Total NaN in row 2008 : 10
 Total NaN in row 2009 : 3
 Total NaN in row 2010 : 0
 Total NaN in row 2011 : 2
 Total NaN in row 2012 : 2
 Total NaN in row 2013 : 0
 Total NaN in row 2014 : 1
 Total NaN in row 2015 : 1
 Total NaN in row 2016 : 0
 Total NaN in row 2017 : 2
 Total NaN in row 2018 : 1
 Total NaN in row 2019 : 2
 Total NaN in row 2020 : 0
 Total NaN in row 2021 : 3
 Total NaN in row 2022 : 0
 Total NaN in row 2023 : 0
 Total NaN in row 2024 : 0
 Total NaN in row 2025 : 1
 Total NaN in row 2026 : 1
 Total NaN in row 2027 : 2
 Total NaN in row 2028 : 9
 Total NaN in row 2029 : 1
 Total NaN in row 2030 : 1
 Total NaN in row 2031 : 9
 Total NaN in row 2032 : 0
 Total NaN in row 2033 : 0
 Total NaN in row 2034 : 9
 Total NaN in row 2035 : 1
 Total NaN in row 2036 : 9
 Total NaN in row 2037 : 0
 Total NaN in row 2038 : 9
 Total NaN in row 2039 : 9
 Total NaN in row 2040 : 9
 Total NaN in row 2041 : 0
 Total NaN in row 2042 : 2
 Total NaN in row 2043 : 1
 Total NaN in row 2044 : 9
 Total NaN in row 2045 : 9
 Total NaN in row 2046 : 9
 Total NaN in row 2047 : 0
 Total NaN in row 2048 : 0
 Total NaN in row 2049 : 0
 Total NaN in row 2050 : 0
 Total NaN in row 2051 : 0
 Total NaN in row 2052 : 9
 Total NaN in row 2053 : 2
 Total NaN in row 2054 : 9
 Total NaN in row 2055 : 0
 Total NaN in row 2056 : 2
 Total NaN in row 2057 : 9
 Total NaN in row 2058 : 10
 Total NaN in row 2059 : 1
 Total NaN in row 2060 : 0
 Total NaN in row 2061 : 2
 Total NaN in row 2062 : 2
 Total NaN in row 2063 : 3
 Total NaN in row 2064 : 0
 Total NaN in row 2065 : 9
 Total NaN in row 2066 : 3
 Total NaN in row 2067 : 3
 Total NaN in row 2068 : 9
 Total NaN in row 2069 : 10
 Total NaN in row 2070 : 2
 Total NaN in row 2071 : 0
 Total NaN in row 2072 : 9
 Total NaN in row 2073 : 1
 Total NaN in row 2074 : 9
 Total NaN in row 2075 : 9
 Total NaN in row 2076 : 9
 Total NaN in row 2077 : 10
 Total NaN in row 2078 : 1
 Total NaN in row 2079 : 9
 Total NaN in row 2080 : 1
 Total NaN in row 2081 : 10
 Total NaN in row 2082 : 2
 Total NaN in row 2083 : 2
 Total NaN in row 2084 : 0
 Total NaN in row 2085 : 2
 Total NaN in row 2086 : 2
 Total NaN in row 2087 : 9
 Total NaN in row 2088 : 2
 Total NaN in row 2089 : 2
 Total NaN in row 2090 : 1
 Total NaN in row 2091 : 2
 Total NaN in row 2092 : 9
 Total NaN in row 2093 : 2
 Total NaN in row 2094 : 2
 Total NaN in row 2095 : 3
 Total NaN in row 2096 : 1
 Total NaN in row 2097 : 1
 Total NaN in row 2098 : 0
 Total NaN in row 2099 : 2
 Total NaN in row 2100 : 0
 Total NaN in row 2101 : 1
 Total NaN in row 2102 : 3
 Total NaN in row 2103 : 7
 Total NaN in row 2104 : 10
 Total NaN in row 2105 : 0
 Total NaN in row 2106 : 1
 Total NaN in row 2107 : 1
 Total NaN in row 2108 : 2
 Total NaN in row 2109 : 2
 Total NaN in row 2110 : 10
 Total NaN in row 2111 : 9
 Total NaN in row 2112 : 1
 Total NaN in row 2113 : 2
 Total NaN in row 2114 : 0
 Total NaN in row 2115 : 0
 Total NaN in row 2116 : 9
 Total NaN in row 2117 : 1
 Total NaN in row 2118 : 1
 Total NaN in row 2119 : 1
 Total NaN in row 2120 : 21
 Total NaN in row 2121 : 9
 Total NaN in row 2122 : 0
 Total NaN in row 2123 : 1
 Total NaN in row 2124 : 2
 Total NaN in row 2125 : 0
 Total NaN in row 2126 : 9
 Total NaN in row 2127 : 0
 Total NaN in row 2128 : 9
 Total NaN in row 2129 : 0
 Total NaN in row 2130 : 9
 Total NaN in row 2131 : 0
 Total NaN in row 2132 : 3
 Total NaN in row 2133 : 0
 Total NaN in row 2134 : 1
 Total NaN in row 2135 : 1
 Total NaN in row 2136 : 10
 Total NaN in row 2137 : 0
 Total NaN in row 2138 : 1
 Total NaN in row 2139 : 10
 Total NaN in row 2140 : 2
 Total NaN in row 2141 : 1
 Total NaN in row 2142 : 1
 Total NaN in row 2143 : 0
 Total NaN in row 2144 : 1
 Total NaN in row 2145 : 0
 Total NaN in row 2146 : 0
 Total NaN in row 2147 : 0
 Total NaN in row 2148 : 10
 Total NaN in row 2149 : 9
 Total NaN in row 2150 : 9
 Total NaN in row 2151 : 9
 Total NaN in row 2152 : 0
 Total NaN in row 2153 : 2
 Total NaN in row 2154 : 0
 Total NaN in row 2155 : 0
 Total NaN in row 2156 : 0
 Total NaN in row 2157 : 9
 Total NaN in row 2158 : 3
 Total NaN in row 2159 : 0
 Total NaN in row 2160 : 0
 Total NaN in row 2161 : 3
 Total NaN in row 2162 : 1
 Total NaN in row 2163 : 1
 Total NaN in row 2164 : 0
 Total NaN in row 2165 : 1
 Total NaN in row 2166 : 0
 Total NaN in row 2167 : 1
 Total NaN in row 2168 : 3
 Total NaN in row 2169 : 0
 Total NaN in row 2170 : 0
 Total NaN in row 2171 : 0
 Total NaN in row 2172 : 2
 Total NaN in row 2173 : 2
 Total NaN in row 2174 : 2
 Total NaN in row 2175 : 0
 Total NaN in row 2176 : 9
 Total NaN in row 2177 : 0
 Total NaN in row 2178 : 3

 Total NaN in row 2179 : 0
 Total NaN in row 2180 : 2
 Total NaN in row 2181 : 9
 Total NaN in row 2182 : 0
 Total NaN in row 2183 : 1
 Total NaN in row 2184 : 0
 Total NaN in row 2185 : 0
 Total NaN in row 2186 : 9
 Total NaN in row 2187 : 1
 Total NaN in row 2188 : 9
 Total NaN in row 2189 : 0
 Total NaN in row 2190 : 1
 Total NaN in row 2191 : 0
 Total NaN in row 2192 : 1
 Total NaN in row 2193 : 2
 Total NaN in row 2194 : 9
 Total NaN in row 2195 : 2
 Total NaN in row 2196 : 1
 Total NaN in row 2197 : 0
 Total NaN in row 2198 : 2
 Total NaN in row 2199 : 2
 Total NaN in row 2200 : 2
 Total NaN in row 2201 : 2
 Total NaN in row 2202 : 1
 Total NaN in row 2203 : 9
 Total NaN in row 2204 : 0
 Total NaN in row 2205 : 0
 Total NaN in row 2206 : 2
 Total NaN in row 2207 : 9
 Total NaN in row 2208 : 0
 Total NaN in row 2209 : 2
 Total NaN in row 2210 : 2
 Total NaN in row 2211 : 1
 Total NaN in row 2212 : 0
 Total NaN in row 2213 : 1
 Total NaN in row 2214 : 7
 Total NaN in row 2215 : 2
 Total NaN in row 2216 : 0
 Total NaN in row 2217 : 0
 Total NaN in row 2218 : 0
 Total NaN in row 2219 : 0
 Total NaN in row 2220 : 0
 Total NaN in row 2221 : 1
 Total NaN in row 2222 : 0
 Total NaN in row 2223 : 0
 Total NaN in row 2224 : 1
 Total NaN in row 2225 : 1
 Total NaN in row 2226 : 0
 Total NaN in row 2227 : 1
 Total NaN in row 2228 : 2
 Total NaN in row 2229 : 2
 Total NaN in row 2230 : 0
 Total NaN in row 2231 : 0
 Total NaN in row 2232 : 0
 Total NaN in row 2233 : 2
 Total NaN in row 2234 : 3
 Total NaN in row 2235 : 0
 Total NaN in row 2236 : 0
 Total NaN in row 2237 : 0
 Total NaN in row 2238 : 1
 Total NaN in row 2239 : 0
 Total NaN in row 2240 : 0
 Total NaN in row 2241 : 9
 Total NaN in row 2242 : 0
 Total NaN in row 2243 : 1
 Total NaN in row 2244 : 9
 Total NaN in row 2245 : 0
 Total NaN in row 2246 : 2
 Total NaN in row 2247 : 0
 Total NaN in row 2248 : 4
 Total NaN in row 2249 : 0
 Total NaN in row 2250 : 0
 Total NaN in row 2251 : 1
 Total NaN in row 2252 : 0
 Total NaN in row 2253 : 2
 Total NaN in row 2254 : 2
 Total NaN in row 2255 : 0
 Total NaN in row 2256 : 0
 Total NaN in row 2257 : 0
 Total NaN in row 2258 : 1
 Total NaN in row 2259 : 2
 Total NaN in row 2260 : 2
 Total NaN in row 2261 : 1
 Total NaN in row 2262 : 0
 Total NaN in row 2263 : 0
 Total NaN in row 2264 : 2
 Total NaN in row 2265 : 0
 Total NaN in row 2266 : 2
 Total NaN in row 2267 : 2
 Total NaN in row 2268 : 9
 Total NaN in row 2269 : 0
 Total NaN in row 2270 : 2
 Total NaN in row 2271 : 2
 Total NaN in row 2272 : 9
 Total NaN in row 2273 : 3
 Total NaN in row 2274 : 9
 Total NaN in row 2275 : 2
 Total NaN in row 2276 : 0
 Total NaN in row 2277 : 9
 Total NaN in row 2278 : 2
 Total NaN in row 2279 : 3
 Total NaN in row 2280 : 2
 Total NaN in row 2281 : 0
 Total NaN in row 2282 : 2
 Total NaN in row 2283 : 0
 Total NaN in row 2284 : 3
 Total NaN in row 2285 : 1
 Total NaN in row 2286 : 0
 Total NaN in row 2287 : 1
 Total NaN in row 2288 : 0
 Total NaN in row 2289 : 2
 Total NaN in row 2290 : 0
 Total NaN in row 2291 : 0
 Total NaN in row 2292 : 0
 Total NaN in row 2293 : 0
 Total NaN in row 2294 : 2
 Total NaN in row 2295 : 0
 Total NaN in row 2296 : 1
 Total NaN in row 2297 : 0
 Total NaN in row 2298 : 0
 Total NaN in row 2299 : 2
 Total NaN in row 2300 : 0
 Total NaN in row 2301 : 0
 Total NaN in row 2302 : 1
 Total NaN in row 2303 : 9
 Total NaN in row 2304 : 0
 Total NaN in row 2305 : 2
 Total NaN in row 2306 : 1
 Total NaN in row 2307 : 10
 Total NaN in row 2308 : 9
 Total NaN in row 2309 : 1
 Total NaN in row 2310 : 0
 Total NaN in row 2311 : 0
 Total NaN in row 2312 : 9
 Total NaN in row 2313 : 1
 Total NaN in row 2314 : 0
 Total NaN in row 2315 : 9
 Total NaN in row 2316 : 0
 Total NaN in row 2317 : 0
 Total NaN in row 2318 : 0
 Total NaN in row 2319 : 2
 Total NaN in row 2320 : 0
 Total NaN in row 2321 : 2
 Total NaN in row 2322 : 0
 Total NaN in row 2323 : 0
 Total NaN in row 2324 : 9
 Total NaN in row 2325 : 9
 Total NaN in row 2326 : 9
 Total NaN in row 2327 : 0
 Total NaN in row 2328 : 0
 Total NaN in row 2329 : 0
 Total NaN in row 2330 : 9
 Total NaN in row 2331 : 2
 Total NaN in row 2332 : 2
 Total NaN in row 2333 : 0
 Total NaN in row 2334 : 1
 Total NaN in row 2335 : 0
 Total NaN in row 2336 : 0
 Total NaN in row 2337 : 3
 Total NaN in row 2338 : 1
 Total NaN in row 2339 : 0
 Total NaN in row 2340 : 2
 Total NaN in row 2341 : 0
 Total NaN in row 2342 : 3
 Total NaN in row 2343 : 2
 Total NaN in row 2344 : 2
 Total NaN in row 2345 : 1
 Total NaN in row 2346 : 2
 Total NaN in row 2347 : 3
 Total NaN in row 2348 : 2
 Total NaN in row 2349 : 9
 Total NaN in row 2350 : 0
 Total NaN in row 2351 : 0
 Total NaN in row 2352 : 0
 Total NaN in row 2353 : 10
 Total NaN in row 2354 : 0
 Total NaN in row 2355 : 9
 Total NaN in row 2356 : 0
 Total NaN in row 2357 : 0
 Total NaN in row 2358 : 1
 Total NaN in row 2359 : 9
 Total NaN in row 2360 : 1
 Total NaN in row 2361 : 9
 Total NaN in row 2362 : 0
 Total NaN in row 2363 : 0
 Total NaN in row 2364 : 0
 Total NaN in row 2365 : 0
 Total NaN in row 2366 : 1
 Total NaN in row 2367 : 9
 Total NaN in row 2368 : 2
 Total NaN in row 2369 : 9
 Total NaN in row 2370 : 2
 Total NaN in row 2371 : 0
 Total NaN in row 2372 : 0
 Total NaN in row 2373 : 1
 Total NaN in row 2374 : 10
 Total NaN in row 2375 : 9
 Total NaN in row 2376 : 2
 Total NaN in row 2377 : 9
 Total NaN in row 2378 : 1
 Total NaN in row 2379 : 1
 Total NaN in row 2380 : 0
 Total NaN in row 2381 : 9
 Total NaN in row 2382 : 0
 Total NaN in row 2383 : 0
 Total NaN in row 2384 : 0
 Total NaN in row 2385 : 0
 Total NaN in row 2386 : 2
 Total NaN in row 2387 : 2
 Total NaN in row 2388 : 0
 Total NaN in row 2389 : 1
 Total NaN in row 2390 : 1
 Total NaN in row 2391 : 0
 Total NaN in row 2392 : 2
 Total NaN in row 2393 : 0
 Total NaN in row 2394 : 0
 Total NaN in row 2395 : 2
 Total NaN in row 2396 : 9
 Total NaN in row 2397 : 2
 Total NaN in row 2398 : 1
 Total NaN in row 2399 : 0
 Total NaN in row 2400 : 9
 Total NaN in row 2401 : 9
 Total NaN in row 2402 : 0
 Total NaN in row 2403 : 0
 Total NaN in row 2404 : 0
 Total NaN in row 2405 : 0
 Total NaN in row 2406 : 0
 Total NaN in row 2407 : 2
 Total NaN in row 2408 : 2
 Total NaN in row 2409 : 0
 Total NaN in row 2410 : 0
 Total NaN in row 2411 : 0
 Total NaN in row 2412 : 0
 Total NaN in row 2413 : 0
 Total NaN in row 2414 : 9
 Total NaN in row 2415 : 9
 Total NaN in row 2416 : 0
 Total NaN in row 2417 : 0
 Total NaN in row 2418 : 0
 Total NaN in row 2419 : 9
 Total NaN in row 2420 : 9
 Total NaN in row 2421 : 0
 Total NaN in row 2422 : 0
 Total NaN in row 2423 : 1
 Total NaN in row 2424 : 2
 Total NaN in row 2425 : 9
 Total NaN in row 2426 : 0
 Total NaN in row 2427 : 1
 Total NaN in row 2428 : 9
 Total NaN in row 2429 : 1
 Total NaN in row 2430 : 0
 Total NaN in row 2431 : 2
 Total NaN in row 2432 : 0
 Total NaN in row 2433 : 0
 Total NaN in row 2434 : 1
 Total NaN in row 2435 : 0
 Total NaN in row 2436 : 9
 Total NaN in row 2437 : 0
 Total NaN in row 2438 : 0
 Total NaN in row 2439 : 2
 Total NaN in row 2440 : 0
 Total NaN in row 2441 : 9
 Total NaN in row 2442 : 1
 Total NaN in row 2443 : 9
 Total NaN in row 2444 : 0
 Total NaN in row 2445 : 2
 Total NaN in row 2446 : 0
 Total NaN in row 2447 : 2
 Total NaN in row 2448 : 0
 Total NaN in row 2449 : 2
 Total NaN in row 2450 : 0
 Total NaN in row 2451 : 2
 Total NaN in row 2452 : 3
 Total NaN in row 2453 : 1
 Total NaN in row 2454 : 1
 Total NaN in row 2455 : 0
 Total NaN in row 2456 : 0
 Total NaN in row 2457 : 9
 Total NaN in row 2458 : 1
 Total NaN in row 2459 : 1
 Total NaN in row 2460 : 1
 Total NaN in row 2461 : 9
 Total NaN in row 2462 : 9
 Total NaN in row 2463 : 1
 Total NaN in row 2464 : 0
 Total NaN in row 2465 : 2
 Total NaN in row 2466 : 9
 Total NaN in row 2467 : 0
 Total NaN in row 2468 : 2
 Total NaN in row 2469 : 9
 Total NaN in row 2470 : 0
 Total NaN in row 2471 : 1
 Total NaN in row 2472 : 1
 Total NaN in row 2473 : 9
 Total NaN in row 2474 : 0
 Total NaN in row 2475 : 9
 Total NaN in row 2476 : 2
 Total NaN in row 2477 : 9
 Total NaN in row 2478 : 1
 Total NaN in row 2479 : 0
 Total NaN in row 2480 : 0
 Total NaN in row 2481 : 3
 Total NaN in row 2482 : 9
 Total NaN in row 2483 : 0
 Total NaN in row 2484 : 3
 Total NaN in row 2485 : 0
 Total NaN in row 2486 : 2
 Total NaN in row 2487 : 2
 Total NaN in row 2488 : 2
 Total NaN in row 2489 : 9
 Total NaN in row 2490 : 2
 Total NaN in row 2491 : 9
 Total NaN in row 2492 : 0
 Total NaN in row 2493 : 9
 Total NaN in row 2494 : 1
 Total NaN in row 2495 : 9
 Total NaN in row 2496 : 2
 Total NaN in row 2497 : 0
 Total NaN in row 2498 : 1
 Total NaN in row 2499 : 2
 Total NaN in row 2500 : 2
 Total NaN in row 2501 : 9
 Total NaN in row 2502 : 0
 Total NaN in row 2503 : 10
 Total NaN in row 2504 : 9
 Total NaN in row 2505 : 9
 Total NaN in row 2506 : 9
 Total NaN in row 2507 : 2
 Total NaN in row 2508 : 2
 Total NaN in row 2509 : 2
 Total NaN in row 2510 : 3
 Total NaN in row 2511 : 9
 Total NaN in row 2512 : 0
 Total NaN in row 2513 : 2
 Total NaN in row 2514 : 3
 Total NaN in row 2515 : 3
 Total NaN in row 2516 : 1
 Total NaN in row 2517 : 0
 Total NaN in row 2518 : 0
 Total NaN in row 2519 : 2
 Total NaN in row 2520 : 2
 Total NaN in row 2521 : 0
 Total NaN in row 2522 : 9
 Total NaN in row 2523 : 1
 Total NaN in row 2524 : 1
 Total NaN in row 2525 : 3
 Total NaN in row 2526 : 9
 Total NaN in row 2527 : 1
 Total NaN in row 2528 : 9
 Total NaN in row 2529 : 9
 Total NaN in row 2530 : 0
 Total NaN in row 2531 : 1
 Total NaN in row 2532 : 0
 Total NaN in row 2533 : 3
 Total NaN in row 2534 : 3
 Total NaN in row 2535 : 10
 Total NaN in row 2536 : 0
 Total NaN in row 2537 : 9
 Total NaN in row 2538 : 0
 Total NaN in row 2539 : 10
 Total NaN in row 2540 : 9
 Total NaN in row 2541 : 2
 Total NaN in row 2542 : 0
 Total NaN in row 2543 : 0
 Total NaN in row 2544 : 2
 Total NaN in row 2545 : 2
 Total NaN in row 2546 : 9
 Total NaN in row 2547 : 10
 Total NaN in row 2548 : 2
 Total NaN in row 2549 : 9
 Total NaN in row 2550 : 2
 Total NaN in row 2551 : 10
 Total NaN in row 2552 : 0
 Total NaN in row 2553 : 3
 Total NaN in row 2554 : 3
 Total NaN in row 2555 : 0
 Total NaN in row 2556 : 9
 Total NaN in row 2557 : 0
 Total NaN in row 2558 : 3
 Total NaN in row 2559 : 1
 Total NaN in row 2560 : 0
 Total NaN in row 2561 : 2
 Total NaN in row 2562 : 2
 Total NaN in row 2563 : 2
 Total NaN in row 2564 : 2
 Total NaN in row 2565 : 1
 Total NaN in row 2566 : 0
 Total NaN in row 2567 : 10
 Total NaN in row 2568 : 10
 Total NaN in row 2569 : 1
 Total NaN in row 2570 : 0
 Total NaN in row 2571 : 2
 Total NaN in row 2572 : 0
 Total NaN in row 2573 : 9
 Total NaN in row 2574 : 1
 Total NaN in row 2575 : 0
 Total NaN in row 2576 : 0
 Total NaN in row 2577 : 4
 Total NaN in row 2578 : 1
 Total NaN in row 2579 : 0
 Total NaN in row 2580 : 2
 Total NaN in row 2581 : 1
 Total NaN in row 2582 : 3
 Total NaN in row 2583 : 9
 Total NaN in row 2584 : 10
 Total NaN in row 2585 : 9
 Total NaN in row 2586 : 10
 Total NaN in row 2587 : 9
 Total NaN in row 2588 : 2
 Total NaN in row 2589 : 9
 Total NaN in row 2590 : 9
 Total NaN in row 2591 : 1
 Total NaN in row 2592 : 0
 Total NaN in row 2593 : 2
 Total NaN in row 2594 : 10
 Total NaN in row 2595 : 3
 Total NaN in row 2596 : 7
 Total NaN in row 2597 : 0
 Total NaN in row 2598 : 9
 Total NaN in row 2599 : 9
 Total NaN in row 2600 : 9
 Total NaN in row 2601 : 9
 Total NaN in row 2602 : 9
 Total NaN in row 2603 : 0

 Total NaN in row 2604 : 10
 Total NaN in row 2605 : 9
 Total NaN in row 2606 : 9
 Total NaN in row 2607 : 10
 Total NaN in row 2608 : 9
 Total NaN in row 2609 : 1
 Total NaN in row 2610 : 0
 Total NaN in row 2611 : 2
 Total NaN in row 2612 : 2
 Total NaN in row 2613 : 9
 Total NaN in row 2614 : 10
 Total NaN in row 2615 : 9
 Total NaN in row 2616 : 2
 Total NaN in row 2617 : 2
 Total NaN in row 2618 : 7
 Total NaN in row 2619 : 2
 Total NaN in row 2620 : 0
 Total NaN in row 2621 : 0
 Total NaN in row 2622 : 10
 Total NaN in row 2623 : 0
 Total NaN in row 2624 : 2
 Total NaN in row 2625 : 1
 Total NaN in row 2626 : 2
 Total NaN in row 2627 : 2
 Total NaN in row 2628 : 1
 Total NaN in row 2629 : 0
 Total NaN in row 2630 : 0
 Total NaN in row 2631 : 10
 Total NaN in row 2632 : 10
 Total NaN in row 2633 : 1
 Total NaN in row 2634 : 10
 Total NaN in row 2635 : 10
 Total NaN in row 2636 : 0
 Total NaN in row 2637 : 10
 Total NaN in row 2638 : 1
 Total NaN in row 2639 : 10
 Total NaN in row 2640 : 2
 Total NaN in row 2641 : 9
 Total NaN in row 2642 : 9
 Total NaN in row 2643 : 1
 Total NaN in row 2644 : 1
 Total NaN in row 2645 : 10
 Total NaN in row 2646 : 1
 Total NaN in row 2647 : 9
 Total NaN in row 2648 : 1
 Total NaN in row 2649 : 9
 Total NaN in row 2650 : 0
 Total NaN in row 2651 : 1
 Total NaN in row 2652 : 9
 Total NaN in row 2653 : 0
 Total NaN in row 2654 : 0
 Total NaN in row 2655 : 0
 Total NaN in row 2656 : 0
 Total NaN in row 2657 : 1
 Total NaN in row 2658 : 1
 Total NaN in row 2659 : 2
 Total NaN in row 2660 : 1
 Total NaN in row 2661 : 10
 Total NaN in row 2662 : 10
 Total NaN in row 2663 : 2
 Total NaN in row 2664 : 0
 Total NaN in row 2665 : 0
 Total NaN in row 2666 : 1
 Total NaN in row 2667 : 3
 Total NaN in row 2668 : 0
 Total NaN in row 2669 : 1
 Total NaN in row 2670 : 2
 Total NaN in row 2671 : 2
 Total NaN in row 2672 : 1
 Total NaN in row 2673 : 9
 Total NaN in row 2674 : 9
 Total NaN in row 2675 : 9
 Total NaN in row 2676 : 9
 Total NaN in row 2677 : 1
 Total NaN in row 2678 : 1
 Total NaN in row 2679 : 2
 Total NaN in row 2680 : 2
 Total NaN in row 2681 : 1
 Total NaN in row 2682 : 1
 Total NaN in row 2683 : 9
 Total NaN in row 2684 : 9
 Total NaN in row 2685 : 10
 Total NaN in row 2686 : 0
 Total NaN in row 2687 : 0
 Total NaN in row 2688 : 9
 Total NaN in row 2689 : 2
 Total NaN in row 2690 : 1
 Total NaN in row 2691 : 0
 Total NaN in row 2692 : 0
 Total NaN in row 2693 : 3
 Total NaN in row 2694 : 1
 Total NaN in row 2695 : 0
 Total NaN in row 2696 : 9
 Total NaN in row 2697 : 9
 Total NaN in row 2698 : 10
 Total NaN in row 2699 : 1
 Total NaN in row 2700 : 1
 Total NaN in row 2701 : 1
 Total NaN in row 2702 : 1
 Total NaN in row 2703 : 3
 Total NaN in row 2704 : 0
 Total NaN in row 2705 : 9
 Total NaN in row 2706 : 1
 Total NaN in row 2707 : 1
 Total NaN in row 2708 : 9
 Total NaN in row 2709 : 0
 Total NaN in row 2710 : 10
 Total NaN in row 2711 : 3
 Total NaN in row 2712 : 9
 Total NaN in row 2713 : 0
 Total NaN in row 2714 : 1
 Total NaN in row 2715 : 1
 Total NaN in row 2716 : 0
 Total NaN in row 2717 : 10
 Total NaN in row 2718 : 0
 Total NaN in row 2719 : 0
 Total NaN in row 2720 : 10
 Total NaN in row 2721 : 1
 Total NaN in row 2722 : 9
 Total NaN in row 2723 : 2
 Total NaN in row 2724 : 0
 Total NaN in row 2725 : 0
 Total NaN in row 2726 : 1
 Total NaN in row 2727 : 1
 Total NaN in row 2728 : 0
 Total NaN in row 2729 : 9
 Total NaN in row 2730 : 1
 Total NaN in row 2731 : 2
 Total NaN in row 2732 : 0
 Total NaN in row 2733 : 10
 Total NaN in row 2734 : 1
 Total NaN in row 2735 : 2
 Total NaN in row 2736 : 2
 Total NaN in row 2737 : 0
 Total NaN in row 2738 : 1
 Total NaN in row 2739 : 9
 Total NaN in row 2740 : 2
 Total NaN in row 2741 : 9
 Total NaN in row 2742 : 2
 Total NaN in row 2743 : 10
 Total NaN in row 2744 : 9
 Total NaN in row 2745 : 10
 Total NaN in row 2746 : 10
 Total NaN in row 2747 : 9
 Total NaN in row 2748 : 10
 Total NaN in row 2749 : 10
 Total NaN in row 2750 : 10
 Total NaN in row 2751 : 3
 Total NaN in row 2752 : 2
 Total NaN in row 2753 : 9
 Total NaN in row 2754 : 9
 Total NaN in row 2755 : 9
 Total NaN in row 2756 : 9
 Total NaN in row 2757 : 2
 Total NaN in row 2758 : 1
 Total NaN in row 2759 : 9
 Total NaN in row 2760 : 2
 Total NaN in row 2761 : 3
 Total NaN in row 2762 : 0
 Total NaN in row 2763 : 9
 Total NaN in row 2764 : 3
 Total NaN in row 2765 : 3
 Total NaN in row 2766 : 2
 Total NaN in row 2767 : 9
 Total NaN in row 2768 : 0
 Total NaN in row 2769 : 2
 Total NaN in row 2770 : 9
 Total NaN in row 2771 : 9
 Total NaN in row 2772 : 9
 Total NaN in row 2773 : 1
 Total NaN in row 2774 : 0
 Total NaN in row 2775 : 3
 Total NaN in row 2776 : 0
 Total NaN in row 2777 : 2
 Total NaN in row 2778 : 9
 Total NaN in row 2779 : 1
 Total NaN in row 2780 : 0
 Total NaN in row 2781 : 3
 Total NaN in row 2782 : 1
 Total NaN in row 2783 : 0
 Total NaN in row 2784 : 2
 Total NaN in row 2785 : 3
 Total NaN in row 2786 : 2
 Total NaN in row 2787 : 2
 Total NaN in row 2788 : 2
 Total NaN in row 2789 : 10
 Total NaN in row 2790 : 1
 Total NaN in row 2791 : 0
 Total NaN in row 2792 : 0
 Total NaN in row 2793 : 2
 Total NaN in row 2794 : 0
 Total NaN in row 2795 : 2
 Total NaN in row 2796 : 0
 Total NaN in row 2797 : 9
 Total NaN in row 2798 : 3
 Total NaN in row 2799 : 0
 Total NaN in row 2800 : 1
 Total NaN in row 2801 : 9
 Total NaN in row 2802 : 0
 Total NaN in row 2803 : 0
 Total NaN in row 2804 : 1
 Total NaN in row 2805 : 0
 Total NaN in row 2806 : 1
 Total NaN in row 2807 : 0
 Total NaN in row 2808 : 0
 Total NaN in row 2809 : 1
 Total NaN in row 2810 : 1
 Total NaN in row 2811 : 10
 Total NaN in row 2812 : 10
 Total NaN in row 2813 : 9
 Total NaN in row 2814 : 10
 Total NaN in row 2815 : 1
 Total NaN in row 2816 : 0
 Total NaN in row 2817 : 1
 Total NaN in row 2818 : 10
 Total NaN in row 2819 : 0
 Total NaN in row 2820 : 10
 Total NaN in row 2821 : 3
 Total NaN in row 2822 : 1
 Total NaN in row 2823 : 10
 Total NaN in row 2824 : 10
 Total NaN in row 2825 : 2
 Total NaN in row 2826 : 10
 Total NaN in row 2827 : 9
 Total NaN in row 2828 : 2
 Total NaN in row 2829 : 0
 Total NaN in row 2830 : 1
 Total NaN in row 2831 : 9
 Total NaN in row 2832 : 0
 Total NaN in row 2833 : 0
 Total NaN in row 2834 : 3
 Total NaN in row 2835 : 0
 Total NaN in row 2836 : 0
 Total NaN in row 2837 : 0
 Total NaN in row 2838 : 2
 Total NaN in row 2839 : 0
 Total NaN in row 2840 : 1
 Total NaN in row 2841 : 0
 Total NaN in row 2842 : 0
 Total NaN in row 2843 : 1
 Total NaN in row 2844 : 2
 Total NaN in row 2845 : 0
 Total NaN in row 2846 : 1
 Total NaN in row 2847 : 1
 Total NaN in row 2848 : 0
 Total NaN in row 2849 : 2
 Total NaN in row 2850 : 0
 Total NaN in row 2851 : 1
 Total NaN in row 2852 : 0
 Total NaN in row 2853 : 0
 Total NaN in row 2854 : 1
 Total NaN in row 2855 : 0
 Total NaN in row 2856 : 9
 Total NaN in row 2857 : 3
 Total NaN in row 2858 : 3
 Total NaN in row 2859 : 2
 Total NaN in row 2860 : 1
 Total NaN in row 2861 : 3
 Total NaN in row 2862 : 0
 Total NaN in row 2863 : 2
 Total NaN in row 2864 : 2
 Total NaN in row 2865 : 2
 Total NaN in row 2866 : 1
 Total NaN in row 2867 : 2
 Total NaN in row 2868 : 1
 Total NaN in row 2869 : 0
 Total NaN in row 2870 : 10
 Total NaN in row 2871 : 1
 Total NaN in row 2872 : 2
 Total NaN in row 2873 : 2
 Total NaN in row 2874 : 9
 Total NaN in row 2875 : 9
 Total NaN in row 2876 : 10
 Total NaN in row 2877 : 2
 Total NaN in row 2878 : 1
 Total NaN in row 2879 : 2
 Total NaN in row 2880 : 1
 Total NaN in row 2881 : 2
 Total NaN in row 2882 : 0
 Total NaN in row 2883 : 2
 Total NaN in row 2884 : 3
 Total NaN in row 2885 : 2
 Total NaN in row 2886 : 3
 Total NaN in row 2887 : 0
 Total NaN in row 2888 : 0
 Total NaN in row 2889 : 9
 Total NaN in row 2890 : 1
 Total NaN in row 2891 : 1
 Total NaN in row 2892 : 0
 Total NaN in row 2893 : 2
 Total NaN in row 2894 : 3
 Total NaN in row 2895 : 1
 Total NaN in row 2896 : 0
 Total NaN in row 2897 : 1
 Total NaN in row 2898 : 0
 Total NaN in row 2899 : 2
 Total NaN in row 2900 : 2
 Total NaN in row 2901 : 0
 Total NaN in row 2902 : 2
 Total NaN in row 2903 : 1
 Total NaN in row 2904 : 1
 Total NaN in row 2905 : 1
 Total NaN in row 2906 : 2
 Total NaN in row 2907 : 0
 Total NaN in row 2908 : 2
 Total NaN in row 2909 : 2
 Total NaN in row 2910 : 0
 Total NaN in row 2911 : 2
 Total NaN in row 2912 : 0
 Total NaN in row 2913 : 1
 Total NaN in row 2914 : 2
 Total NaN in row 2915 : 0
 Total NaN in row 2916 : 3
 Total NaN in row 2917 : 9
 Total NaN in row 2918 : 9
 Total NaN in row 2919 : 1
 Total NaN in row 2920 : 0

 Total NaN in row 2921 : 2
 Total NaN in row 2922 : 0
 Total NaN in row 2923 : 0
 Total NaN in row 2924 : 3
 Total NaN in row 2925 : 1
 Total NaN in row 2926 : 0
 Total NaN in row 2927 : 0
 Total NaN in row 2928 : 1
 Total NaN in row 2929 : 2
 Total NaN in row 2930 : 0
 Total NaN in row 2931 : 9
 Total NaN in row 2932 : 2
 Total NaN in row 2933 : 1
 Total NaN in row 2934 : 0
 Total NaN in row 2935 : 0
 Total NaN in row 2936 : 1
 Total NaN in row 2937 : 0
 Total NaN in row 2938 : 0
 Total NaN in row 2939 : 0
 Total NaN in row 2940 : 0
 Total NaN in row 2941 : 0
 Total NaN in row 2942 : 2
 Total NaN in row 2943 : 0
 Total NaN in row 2944 : 0
 Total NaN in row 2945 : 1
 Total NaN in row 2946 : 2
 Total NaN in row 2947 : 0
 Total NaN in row 2948 : 0
 Total NaN in row 2949 : 1
 Total NaN in row 2950 : 2
 Total NaN in row 2951 : 1
 Total NaN in row 2952 : 1
 Total NaN in row 2953 : 0
 Total NaN in row 2954 : 2
 Total NaN in row 2955 : 2
 Total NaN in row 2956 : 10
 Total NaN in row 2957 : 9
 Total NaN in row 2958 : 9
 Total NaN in row 2959 : 9
 Total NaN in row 2960 : 2
 Total NaN in row 2961 : 0
 Total NaN in row 2962 : 9
 Total NaN in row 2963 : 0
 Total NaN in row 2964 : 0
 Total NaN in row 2965 : 0
 Total NaN in row 2966 : 1
 Total NaN in row 2967 : 9
 Total NaN in row 2968 : 0
 Total NaN in row 2969 : 9
 Total NaN in row 2970 : 3
 Total NaN in row 2971 : 2
 Total NaN in row 2972 : 2
 Total NaN in row 2973 : 9
 Total NaN in row 2974 : 9
 Total NaN in row 2975 : 0
 Total NaN in row 2976 : 0
 Total NaN in row 2977 : 0
 Total NaN in row 2978 : 10
 Total NaN in row 2979 : 2
 Total NaN in row 2980 : 2
 Total NaN in row 2981 : 0
 Total NaN in row 2982 : 2
 Total NaN in row 2983 : 0
 Total NaN in row 2984 : 1
 Total NaN in row 2985 : 2
 Total NaN in row 2986 : 0
 Total NaN in row 2987 : 3
 Total NaN in row 2988 : 0
 Total NaN in row 2989 : 2
 Total NaN in row 2990 : 0
 Total NaN in row 2991 : 0
 Total NaN in row 2992 : 1
 Total NaN in row 2993 : 0
 Total NaN in row 2994 : 0
 Total NaN in row 2995 : 2
 Total NaN in row 2996 : 2
 Total NaN in row 2997 : 2
 Total NaN in row 2998 : 0
 Total NaN in row 2999 : 9
 Total NaN in row 3000 : 9
 Total NaN in row 3001 : 7
 Total NaN in row 3002 : 2
 Total NaN in row 3003 : 3
 Total NaN in row 3004 : 3
 Total NaN in row 3005 : 9
 Total NaN in row 3006 : 0
 Total NaN in row 3007 : 0
 Total NaN in row 3008 : 9
 Total NaN in row 3009 : 0
 Total NaN in row 3010 : 0
 Total NaN in row 3011 : 0
 Total NaN in row 3012 : 2
 Total NaN in row 3013 : 1
 Total NaN in row 3014 : 1
 Total NaN in row 3015 : 2
 Total NaN in row 3016 : 1
 Total NaN in row 3017 : 1
 Total NaN in row 3018 : 0
 Total NaN in row 3019 : 0
 Total NaN in row 3020 : 10
 Total NaN in row 3021 : 2
 Total NaN in row 3022 : 0
 Total NaN in row 3023 : 1
 Total NaN in row 3024 : 2
 Total NaN in row 3025 : 1
 Total NaN in row 3026 : 0
 Total NaN in row 3027 : 1
 Total NaN in row 3028 : 2
 Total NaN in row 3029 : 9
 Total NaN in row 3030 : 0
 Total NaN in row 3031 : 0
 Total NaN in row 3032 : 2
 Total NaN in row 3033 : 0
 Total NaN in row 3034 : 2
 Total NaN in row 3035 : 0
 Total NaN in row 3036 : 0
 Total NaN in row 3037 : 1
 Total NaN in row 3038 : 9
 Total NaN in row 3039 : 2
 Total NaN in row 3040 : 0
 Total NaN in row 3041 : 9
 Total NaN in row 3042 : 0
 Total NaN in row 3043 : 1
 Total NaN in row 3044 : 0
 Total NaN in row 3045 : 0
 Total NaN in row 3046 : 9
 Total NaN in row 3047 : 1
 Total NaN in row 3048 : 0
 Total NaN in row 3049 : 10
 Total NaN in row 3050 : 0
 Total NaN in row 3051 : 0
 Total NaN in row 3052 : 9
 Total NaN in row 3053 : 9
 Total NaN in row 3054 : 1
 Total NaN in row 3055 : 0
 Total NaN in row 3056 : 0
 Total NaN in row 3057 : 1
 Total NaN in row 3058 : 0
 Total NaN in row 3059 : 2
 Total NaN in row 3060 : 0
 Total NaN in row 3061 : 2
 Total NaN in row 3062 : 2
 Total NaN in row 3063 : 1
 Total NaN in row 3064 : 2
 Total NaN in row 3065 : 0
 Total NaN in row 3066 : 9
 Total NaN in row 3067 : 2
 Total NaN in row 3068 : 0
 Total NaN in row 3069 : 1
 Total NaN in row 3070 : 2
 Total NaN in row 3071 : 2
 Total NaN in row 3072 : 0
 Total NaN in row 3073 : 3
 Total NaN in row 3074 : 0
 Total NaN in row 3075 : 1
 Total NaN in row 3076 : 0
 Total NaN in row 3077 : 1
 Total NaN in row 3078 : 0
 Total NaN in row 3079 : 9
 Total NaN in row 3080 : 0
 Total NaN in row 3081 : 2
 Total NaN in row 3082 : 2
 Total NaN in row 3083 : 1
 Total NaN in row 3084 : 2
 Total NaN in row 3085 : 0
 Total NaN in row 3086 : 2
 Total NaN in row 3087 : 1
 Total NaN in row 3088 : 8
 Total NaN in row 3089 : 0
 Total NaN in row 3090 : 9
 Total NaN in row 3091 : 9
 Total NaN in row 3092 : 9
 Total NaN in row 3093 : 1
 Total NaN in row 3094 : 2
 Total NaN in row 3095 : 2
 Total NaN in row 3096 : 0
 Total NaN in row 3097 : 1
 Total NaN in row 3098 : 9
 Total NaN in row 3099 : 2
 Total NaN in row 3100 : 0
 Total NaN in row 3101 : 9
 Total NaN in row 3102 : 2
 Total NaN in row 3103 : 9
 Total NaN in row 3104 : 0
 Total NaN in row 3105 : 8
 Total NaN in row 3106 : 0
 Total NaN in row 3107 : 9
 Total NaN in row 3108 : 1
 Total NaN in row 3109 : 0
 Total NaN in row 3110 : 0
 Total NaN in row 3111 : 1
 Total NaN in row 3112 : 1
 Total NaN in row 3113 : 0
 Total NaN in row 3114 : 3
 Total NaN in row 3115 : 1
 Total NaN in row 3116 : 3
 Total NaN in row 3117 : 1
 Total NaN in row 3118 : 9
 Total NaN in row 3119 : 2
 Total NaN in row 3120 : 1
 Total NaN in row 3121 : 9
 Total NaN in row 3122 : 1
 Total NaN in row 3123 : 1
 Total NaN in row 3124 : 2
 Total NaN in row 3125 : 1
 Total NaN in row 3126 : 2
 Total NaN in row 3127 : 10
 Total NaN in row 3128 : 0
 Total NaN in row 3129 : 0
 Total NaN in row 3130 : 0
 Total NaN in row 3131 : 1
 Total NaN in row 3132 : 0
 Total NaN in row 3133 : 1
 Total NaN in row 3134 : 0
 Total NaN in row 3135 : 2
 Total NaN in row 3136 : 0
 Total NaN in row 3137 : 0
 Total NaN in row 3138 : 2
 Total NaN in row 3139 : 1
 Total NaN in row 3140 : 2
 Total NaN in row 3141 : 3
 Total NaN in row 3142 : 2
 Total NaN in row 3143 : 0
 Total NaN in row 3144 : 1
 Total NaN in row 3145 : 3
 Total NaN in row 3146 : 3
 Total NaN in row 3147 : 0
 Total NaN in row 3148 : 3
 Total NaN in row 3149 : 2
 Total NaN in row 3150 : 0
 Total NaN in row 3151 : 9
 Total NaN in row 3152 : 0
 Total NaN in row 3153 : 1
 Total NaN in row 3154 : 0
 Total NaN in row 3155 : 1
 Total NaN in row 3156 : 0
 Total NaN in row 3157 : 2
 Total NaN in row 3158 : 3
 Total NaN in row 3159 : 9
 Total NaN in row 3160 : 2
 Total NaN in row 3161 : 9
 Total NaN in row 3162 : 10
 Total NaN in row 3163 : 2
 Total NaN in row 3164 : 0
 Total NaN in row 3165 : 9
 Total NaN in row 3166 : 9
 Total NaN in row 3167 : 0
 Total NaN in row 3168 : 9
 Total NaN in row 3169 : 2
 Total NaN in row 3170 : 0
 Total NaN in row 3171 : 9
 Total NaN in row 3172 : 1
 Total NaN in row 3173 : 9
 Total NaN in row 3174 : 9
 Total NaN in row 3175 : 9
 Total NaN in row 3176 : 0
 Total NaN in row 3177 : 0
 Total NaN in row 3178 : 1
 Total NaN in row 3179 : 2
 Total NaN in row 3180 : 10
 Total NaN in row 3181 : 0
 Total NaN in row 3182 : 9
 Total NaN in row 3183 : 2
 Total NaN in row 3184 : 10
 Total NaN in row 3185 : 0
 Total NaN in row 3186 : 2
 Total NaN in row 3187 : 3
 Total NaN in row 3188 : 0
 Total NaN in row 3189 : 9
 Total NaN in row 3190 : 9
 Total NaN in row 3191 : 9
 Total NaN in row 3192 : 1
 Total NaN in row 3193 : 9
 Total NaN in row 3194 : 0
 Total NaN in row 3195 : 9
 Total NaN in row 3196 : 9
 Total NaN in row 3197 : 9
 Total NaN in row 3198 : 1
 Total NaN in row 3199 : 3
 Total NaN in row 3200 : 0
 Total NaN in row 3201 : 10
 Total NaN in row 3202 : 1
 Total NaN in row 3203 : 10
 Total NaN in row 3204 : 10
 Total NaN in row 3205 : 9
 Total NaN in row 3206 : 9
 Total NaN in row 3207 : 2
 Total NaN in row 3208 : 0
 Total NaN in row 3209 : 9
 Total NaN in row 3210 : 10
 Total NaN in row 3211 : 1
 Total NaN in row 3212 : 0
 Total NaN in row 3213 : 10
 Total NaN in row 3214 : 0
 Total NaN in row 3215 : 5
 Total NaN in row 3216 : 2
 Total NaN in row 3217 : 9
 Total NaN in row 3218 : 1
 Total NaN in row 3219 : 0
 Total NaN in row 3220 : 1
 Total NaN in row 3221 : 0
 Total NaN in row 3222 : 0
 Total NaN in row 3223 : 2
 Total NaN in row 3224 : 2
 Total NaN in row 3225 : 0
 Total NaN in row 3226 : 0
 Total NaN in row 3227 : 0
 Total NaN in row 3228 : 0
 Total NaN in row 3229 : 0
 Total NaN in row 3230 : 2
 Total NaN in row 3231 : 0
 Total NaN in row 3232 : 3
 Total NaN in row 3233 : 1
 Total NaN in row 3234 : 2
 Total NaN in row 3235 : 0
 Total NaN in row 3236 : 2
 Total NaN in row 3237 : 0
 Total NaN in row 3238 : 3
 Total NaN in row 3239 : 9
 Total NaN in row 3240 : 2
 Total NaN in row 3241 : 1
 Total NaN in row 3242 : 1
 Total NaN in row 3243 : 2
 Total NaN in row 3244 : 2
 Total NaN in row 3245 : 0
 Total NaN in row 3246 : 2
 Total NaN in row 3247 : 3
 Total NaN in row 3248 : 3
 Total NaN in row 3249 : 9
 Total NaN in row 3250 : 0
 Total NaN in row 3251 : 2
 Total NaN in row 3252 : 10
 Total NaN in row 3253 : 2
 Total NaN in row 3254 : 0
 Total NaN in row 3255 : 1
 Total NaN in row 3256 : 1
 Total NaN in row 3257 : 1
 Total NaN in row 3258 : 3
 Total NaN in row 3259 : 0
 Total NaN in row 3260 : 2
 Total NaN in row 3261 : 3
 Total NaN in row 3262 : 4
 Total NaN in row 3263 : 0
 Total NaN in row 3264 : 9
 Total NaN in row 3265 : 9
 Total NaN in row 3266 : 9
 Total NaN in row 3267 : 2
 Total NaN in row 3268 : 9
 Total NaN in row 3269 : 2
 Total NaN in row 3270 : 3
 Total NaN in row 3271 : 1
 Total NaN in row 3272 : 0
 Total NaN in row 3273 : 1
 Total NaN in row 3274 : 1
 Total NaN in row 3275 : 0
 Total NaN in row 3276 : 1
 Total NaN in row 3277 : 9
 Total NaN in row 3278 : 21
 Total NaN in row 3279 : 0
 Total NaN in row 3280 : 2
 Total NaN in row 3281 : 0
 Total NaN in row 3282 : 2
 Total NaN in row 3283 : 2
 Total NaN in row 3284 : 9
 Total NaN in row 3285 : 0
 Total NaN in row 3286 : 1
 Total NaN in row 3287 : 9
 Total NaN in row 3288 : 1
 Total NaN in row 3289 : 21
 Total NaN in row 3290 : 0
 Total NaN in row 3291 : 0
 Total NaN in row 3292 : 2
 Total NaN in row 3293 : 0
 Total NaN in row 3294 : 2
 Total NaN in row 3295 : 2
 Total NaN in row 3296 : 1
 Total NaN in row 3297 : 0
 Total NaN in row 3298 : 2
 Total NaN in row 3299 : 3
 Total NaN in row 3300 : 0

 Total NaN in row 3301 : 0
 Total NaN in row 3302 : 0
 Total NaN in row 3303 : 3
 Total NaN in row 3304 : 1
 Total NaN in row 3305 : 9
 Total NaN in row 3306 : 2
 Total NaN in row 3307 : 0
 Total NaN in row 3308 : 1
 Total NaN in row 3309 : 0
 Total NaN in row 3310 : 1
 Total NaN in row 3311 : 1
 Total NaN in row 3312 : 0
 Total NaN in row 3313 : 0
 Total NaN in row 3314 : 0
 Total NaN in row 3315 : 0
 Total NaN in row 3316 : 0
 Total NaN in row 3317 : 0
 Total NaN in row 3318 : 0
 Total NaN in row 3319 : 2
 Total NaN in row 3320 : 0
 Total NaN in row 3321 : 3
 Total NaN in row 3322 : 10
 Total NaN in row 3323 : 0
 Total NaN in row 3324 : 3
 Total NaN in row 3325 : 0
 Total NaN in row 3326 : 1
 Total NaN in row 3327 : 1
 Total NaN in row 3328 : 0
 Total NaN in row 3329 : 10
 Total NaN in row 3330 : 1
 Total NaN in row 3331 : 2
 Total NaN in row 3332 : 2
 Total NaN in row 3333 : 2
 Total NaN in row 3334 : 9
 Total NaN in row 3335 : 3
 Total NaN in row 3336 : 2
 Total NaN in row 3337 : 1
 Total NaN in row 3338 : 0
 Total NaN in row 3339 : 2
 Total NaN in row 3340 : 2
 Total NaN in row 3341 : 3
 Total NaN in row 3342 : 1
 Total NaN in row 3343 : 0
 Total NaN in row 3344 : 1
 Total NaN in row 3345 : 0
 Total NaN in row 3346 : 0
 Total NaN in row 3347 : 1
 Total NaN in row 3348 : 0
 Total NaN in row 3349 : 0
 Total NaN in row 3350 : 0
 Total NaN in row 3351 : 9
 Total NaN in row 3352 : 0
 Total NaN in row 3353 : 2
 Total NaN in row 3354 : 0
 Total NaN in row 3355 : 1
 Total NaN in row 3356 : 1
 Total NaN in row 3357 : 1
 Total NaN in row 3358 : 2
 Total NaN in row 3359 : 0
 Total NaN in row 3360 : 0
 Total NaN in row 3361 : 9
 Total NaN in row 3362 : 2
 Total NaN in row 3363 : 10
 Total NaN in row 3364 : 2
 Total NaN in row 3365 : 2
 Total NaN in row 3366 : 1
 Total NaN in row 3367 : 2
 Total NaN in row 3368 : 1
 Total NaN in row 3369 : 1
 Total NaN in row 3370 : 2
 Total NaN in row 3371 : 0
 Total NaN in row 3372 : 2
 Total NaN in row 3373 : 3
 Total NaN in row 3374 : 1
 Total NaN in row 3375 : 3
 Total NaN in row 3376 : 9
 Total NaN in row 3377 : 0
 Total NaN in row 3378 : 1
 Total NaN in row 3379 : 1
 Total NaN in row 3380 : 2
 Total NaN in row 3381 : 2
 Total NaN in row 3382 : 3
 Total NaN in row 3383 : 1
 Total NaN in row 3384 : 0
 Total NaN in row 3385 : 0
 Total NaN in row 3386 : 1
 Total NaN in row 3387 : 3
 Total NaN in row 3388 : 1
 Total NaN in row 3389 : 2
 Total NaN in row 3390 : 9
 Total NaN in row 3391 : 0
 Total NaN in row 3392 : 0
 Total NaN in row 3393 : 0
 Total NaN in row 3394 : 2
 Total NaN in row 3395 : 0
 Total NaN in row 3396 : 9
 Total NaN in row 3397 : 2
 Total NaN in row 3398 : 0
 Total NaN in row 3399 : 0
 Total NaN in row 3400 : 0
 Total NaN in row 3401 : 1
 Total NaN in row 3402 : 1
 Total NaN in row 3403 : 0
 Total NaN in row 3404 : 9
 Total NaN in row 3405 : 2
 Total NaN in row 3406 : 2
 Total NaN in row 3407 : 0
 Total NaN in row 3408 : 0
 Total NaN in row 3409 : 0
 Total NaN in row 3410 : 0
 Total NaN in row 3411 : 2
 Total NaN in row 3412 : 0
 Total NaN in row 3413 : 0
 Total NaN in row 3414 : 1
 Total NaN in row 3415 : 0
 Total NaN in row 3416 : 2
 Total NaN in row 3417 : 0
 Total NaN in row 3418 : 1
 Total NaN in row 3419 : 1
 Total NaN in row 3420 : 0
 Total NaN in row 3421 : 2
 Total NaN in row 3422 : 9
 Total NaN in row 3423 : 3
 Total NaN in row 3424 : 0
 Total NaN in row 3425 : 9
 Total NaN in row 3426 : 0
 Total NaN in row 3427 : 1
 Total NaN in row 3428 : 1
 Total NaN in row 3429 : 1
 Total NaN in row 3430 : 0
 Total NaN in row 3431 : 0
 Total NaN in row 3432 : 2
 Total NaN in row 3433 : 0
 Total NaN in row 3434 : 3
 Total NaN in row 3435 : 0
 Total NaN in row 3436 : 0
 Total NaN in row 3437 : 1
 Total NaN in row 3438 : 1
 Total NaN in row 3439 : 2
 Total NaN in row 3440 : 2
 Total NaN in row 3441 : 0
 Total NaN in row 3442 : 0
 Total NaN in row 3443 : 0
 Total NaN in row 3444 : 1
 Total NaN in row 3445 : 0
 Total NaN in row 3446 : 2
 Total NaN in row 3447 : 0
 Total NaN in row 3448 : 0
 Total NaN in row 3449 : 0
 Total NaN in row 3450 : 1
 Total NaN in row 3451 : 2
 Total NaN in row 3452 : 3
 Total NaN in row 3453 : 1
 Total NaN in row 3454 : 0
 Total NaN in row 3455 : 0
 Total NaN in row 3456 : 3
 Total NaN in row 3457 : 0
 Total NaN in row 3458 : 2
 Total NaN in row 3459 : 2
 Total NaN in row 3460 : 2
 Total NaN in row 3461 : 2
 Total NaN in row 3462 : 3
 Total NaN in row 3463 : 10
 Total NaN in row 3464 : 9
 Total NaN in row 3465 : 9
 Total NaN in row 3466 : 2
 Total NaN in row 3467 : 0
 Total NaN in row 3468 : 0
 Total NaN in row 3469 : 0
 Total NaN in row 3470 : 2
 Total NaN in row 3471 : 0
 Total NaN in row 3472 : 10
 Total NaN in row 3473 : 2
 Total NaN in row 3474 : 9
 Total NaN in row 3475 : 0
 Total NaN in row 3476 : 9
 Total NaN in row 3477 : 0
 Total NaN in row 3478 : 9
 Total NaN in row 3479 : 2
 Total NaN in row 3480 : 0
 Total NaN in row 3481 : 0
 Total NaN in row 3482 : 9
 Total NaN in row 3483 : 0
 Total NaN in row 3484 : 9
 Total NaN in row 3485 : 0
 Total NaN in row 3486 : 1
 Total NaN in row 3487 : 9
 Total NaN in row 3488 : 10
 Total NaN in row 3489 : 0
 Total NaN in row 3490 : 0
 Total NaN in row 3491 : 1
 Total NaN in row 3492 : 2
 Total NaN in row 3493 : 0
 Total NaN in row 3494 : 1
 Total NaN in row 3495 : 0
 Total NaN in row 3496 : 0
 Total NaN in row 3497 : 9
 Total NaN in row 3498 : 0
 Total NaN in row 3499 : 9
 Total NaN in row 3500 : 9
 Total NaN in row 3501 : 9
 Total NaN in row 3502 : 2
 Total NaN in row 3503 : 9
 Total NaN in row 3504 : 10
 Total NaN in row 3505 : 10
 Total NaN in row 3506 : 9
 Total NaN in row 3507 : 10
 Total NaN in row 3508 : 1
 Total NaN in row 3509 : 1
 Total NaN in row 3510 : 2
 Total NaN in row 3511 : 9
 Total NaN in row 3512 : 1
 Total NaN in row 3513 : 2
 Total NaN in row 3514 : 2
 Total NaN in row 3515 : 0
 Total NaN in row 3516 : 0
 Total NaN in row 3517 : 2
 Total NaN in row 3518 : 1
 Total NaN in row 3519 : 9
 Total NaN in row 3520 : 0
 Total NaN in row 3521 : 0
 Total NaN in row 3522 : 1
 Total NaN in row 3523 : 1
 Total NaN in row 3524 : 2
 Total NaN in row 3525 : 8
 Total NaN in row 3526 : 9
 Total NaN in row 3527 : 2
 Total NaN in row 3528 : 2
 Total NaN in row 3529 : 0
 Total NaN in row 3530 : 0
 Total NaN in row 3531 : 0
 Total NaN in row 3532 : 0
 Total NaN in row 3533 : 1
 Total NaN in row 3534 : 2
 Total NaN in row 3535 : 9
 Total NaN in row 3536 : 1
 Total NaN in row 3537 : 2
 Total NaN in row 3538 : 0
 Total NaN in row 3539 : 0
 Total NaN in row 3540 : 0
 Total NaN in row 3541 : 1
 Total NaN in row 3542 : 1
 Total NaN in row 3543 : 2
 Total NaN in row 3544 : 2
 Total NaN in row 3545 : 0
 Total NaN in row 3546 : 2
 Total NaN in row 3547 : 0
 Total NaN in row 3548 : 0
 Total NaN in row 3549 : 1
 Total NaN in row 3550 : 3
 Total NaN in row 3551 : 0
 Total NaN in row 3552 : 1
 Total NaN in row 3553 : 2
 Total NaN in row 3554 : 0
 Total NaN in row 3555 : 0
 Total NaN in row 3556 : 9
 Total NaN in row 3557 : 2
 Total NaN in row 3558 : 0
 Total NaN in row 3559 : 1
 Total NaN in row 3560 : 1
 Total NaN in row 3561 : 0
 Total NaN in row 3562 : 0
 Total NaN in row 3563 : 9
 Total NaN in row 3564 : 0
 Total NaN in row 3565 : 2
 Total NaN in row 3566 : 0
 Total NaN in row 3567 : 2
 Total NaN in row 3568 : 2
 Total NaN in row 3569 : 0
 Total NaN in row 3570 : 2
 Total NaN in row 3571 : 0
 Total NaN in row 3572 : 2
 Total NaN in row 3573 : 0
 Total NaN in row 3574 : 0
 Total NaN in row 3575 : 2
 Total NaN in row 3576 : 2
 Total NaN in row 3577 : 3
 Total NaN in row 3578 : 1
 Total NaN in row 3579 : 2
 Total NaN in row 3580 : 2
 Total NaN in row 3581 : 0
 Total NaN in row 3582 : 9
 Total NaN in row 3583 : 0
 Total NaN in row 3584 : 9
 Total NaN in row 3585 : 3
 Total NaN in row 3586 : 0
 Total NaN in row 3587 : 0
 Total NaN in row 3588 : 0
 Total NaN in row 3589 : 1
 Total NaN in row 3590 : 0
 Total NaN in row 3591 : 1
 Total NaN in row 3592 : 0
 Total NaN in row 3593 : 1
 Total NaN in row 3594 : 0
 Total NaN in row 3595 : 2
 Total NaN in row 3596 : 9
 Total NaN in row 3597 : 1
 Total NaN in row 3598 : 0
 Total NaN in row 3599 : 2
 Total NaN in row 3600 : 2
 Total NaN in row 3601 : 0
 Total NaN in row 3602 : 2
 Total NaN in row 3603 : 0
 Total NaN in row 3604 : 3
 Total NaN in row 3605 : 9
 Total NaN in row 3606 : 9
 Total NaN in row 3607 : 10
 Total NaN in row 3608 : 9
 Total NaN in row 3609 : 2
 Total NaN in row 3610 : 0
 Total NaN in row 3611 : 1
 Total NaN in row 3612 : 9
 Total NaN in row 3613 : 0
 Total NaN in row 3614 : 9
 Total NaN in row 3615 : 1
 Total NaN in row 3616 : 0
 Total NaN in row 3617 : 0
 Total NaN in row 3618 : 2
 Total NaN in row 3619 : 0
 Total NaN in row 3620 : 9
 Total NaN in row 3621 : 9
 Total NaN in row 3622 : 0
 Total NaN in row 3623 : 0
 Total NaN in row 3624 : 0
 Total NaN in row 3625 : 0
 Total NaN in row 3626 : 2
 Total NaN in row 3627 : 0
 Total NaN in row 3628 : 9
 Total NaN in row 3629 : 1
 Total NaN in row 3630 : 0
 Total NaN in row 3631 : 9
 Total NaN in row 3632 : 9
 Total NaN in row 3633 : 0
 Total NaN in row 3634 : 2
 Total NaN in row 3635 : 0
 Total NaN in row 3636 : 2
 Total NaN in row 3637 : 9
 Total NaN in row 3638 : 9
 Total NaN in row 3639 : 2
 Total NaN in row 3640 : 1
 Total NaN in row 3641 : 0
 Total NaN in row 3642 : 1
 Total NaN in row 3643 : 2
 Total NaN in row 3644 : 10
 Total NaN in row 3645 : 9
 Total NaN in row 3646 : 2
 Total NaN in row 3647 : 2
 Total NaN in row 3648 : 1
 Total NaN in row 3649 : 0
 Total NaN in row 3650 : 1
 Total NaN in row 3651 : 1
 Total NaN in row 3652 : 9
 Total NaN in row 3653 : 9
 Total NaN in row 3654 : 9
 Total NaN in row 3655 : 1
 Total NaN in row 3656 : 2
 Total NaN in row 3657 : 0
 Total NaN in row 3658 : 1
 Total NaN in row 3659 : 1
 Total NaN in row 3660 : 0
 Total NaN in row 3661 : 2
 Total NaN in row 3662 : 0
 Total NaN in row 3663 : 9
 Total NaN in row 3664 : 0
 Total NaN in row 3665 : 10
 Total NaN in row 3666 : 0
 Total NaN in row 3667 : 0
 Total NaN in row 3668 : 9
 Total NaN in row 3669 : 0
 Total NaN in row 3670 : 0
 Total NaN in row 3671 : 10
 Total NaN in row 3672 : 2
 Total NaN in row 3673 : 1
 Total NaN in row 3674 : 2
 Total NaN in row 3675 : 2
 Total NaN in row 3676 : 2
 Total NaN in row 3677 : 0
 Total NaN in row 3678 : 3
 Total NaN in row 3679 : 1
 Total NaN in row 3680 : 2
 Total NaN in row 3681 : 1
 Total NaN in row 3682 : 0
 Total NaN in row 3683 : 0
 Total NaN in row 3684 : 0
 Total NaN in row 3685 : 0
 Total NaN in row 3686 : 2
 Total NaN in row 3687 : 1
 Total NaN in row 3688 : 10
 Total NaN in row 3689 : 0
 Total NaN in row 3690 : 0
 Total NaN in row 3691 : 2
 Total NaN in row 3692 : 1
 Total NaN in row 3693 : 9
 Total NaN in row 3694 : 2
 Total NaN in row 3695 : 0
 Total NaN in row 3696 : 1
 Total NaN in row 3697 : 0
 Total NaN in row 3698 : 0
 Total NaN in row 3699 : 9
 Total NaN in row 3700 : 2
 Total NaN in row 3701 : 3
 Total NaN in row 3702 : 2
 Total NaN in row 3703 : 0
 Total NaN in row 3704 : 2
 Total NaN in row 3705 : 1
 Total NaN in row 3706 : 2
 Total NaN in row 3707 : 0
 Total NaN in row 3708 : 0
 Total NaN in row 3709 : 0
 Total NaN in row 3710 : 0
 Total NaN in row 3711 : 0
 Total NaN in row 3712 : 0
 Total NaN in row 3713 : 9
 Total NaN in row 3714 : 0
 Total NaN in row 3715 : 9
 Total NaN in row 3716 : 9
 Total NaN in row 3717 : 1
 Total NaN in row 3718 : 2
 Total NaN in row 3719 : 2
 Total NaN in row 3720 : 9
 Total NaN in row 3721 : 1
 Total NaN in row 3722 : 10
 Total NaN in row 3723 : 1
 Total NaN in row 3724 : 3
 Total NaN in row 3725 : 0
 Total NaN in row 3726 : 1
 Total NaN in row 3727 : 0
 Total NaN in row 3728 : 2
 Total NaN in row 3729 : 9
 Total NaN in row 3730 : 1
 Total NaN in row 3731 : 1
 Total NaN in row 3732 : 0
 Total NaN in row 3733 : 0
 Total NaN in row 3734 : 0
 Total NaN in row 3735 : 0
 Total NaN in row 3736 : 2
 Total NaN in row 3737 : 0
 Total NaN in row 3738 : 1
 Total NaN in row 3739 : 0
 Total NaN in row 3740 : 2
 Total NaN in row 3741 : 0
 Total NaN in row 3742 : 0
 Total NaN in row 3743 : 1
 Total NaN in row 3744 : 0
 Total NaN in row 3745 : 9
 Total NaN in row 3746 : 21
 Total NaN in row 3747 : 0
 Total NaN in row 3748 : 0
 Total NaN in row 3749 : 9
 Total NaN in row 3750 : 3
 Total NaN in row 3751 : 0
 Total NaN in row 3752 : 9
 Total NaN in row 3753 : 21
 Total NaN in row 3754 : 0
 Total NaN in row 3755 : 0
 Total NaN in row 3756 : 2
 Total NaN in row 3757 : 0
 Total NaN in row 3758 : 1
 Total NaN in row 3759 : 1
 Total NaN in row 3760 : 2
 Total NaN in row 3761 : 1
 Total NaN in row 3762 : 7
 Total NaN in row 3763 : 0
 Total NaN in row 3764 : 0
 Total NaN in row 3765 : 0
 Total NaN in row 3766 : 1
 Total NaN in row 3767 : 1

 Total NaN in row 3768 : 2
 Total NaN in row 3769 : 10
 Total NaN in row 3770 : 1
 Total NaN in row 3771 : 0
 Total NaN in row 3772 : 0
 Total NaN in row 3773 : 2
 Total NaN in row 3774 : 0
 Total NaN in row 3775 : 0
 Total NaN in row 3776 : 1
 Total NaN in row 3777 : 0
 Total NaN in row 3778 : 0
 Total NaN in row 3779 : 1
 Total NaN in row 3780 : 0
 Total NaN in row 3781 : 3
 Total NaN in row 3782 : 1
 Total NaN in row 3783 : 2
 Total NaN in row 3784 : 1
 Total NaN in row 3785 : 1
 Total NaN in row 3786 : 0
 Total NaN in row 3787 : 0
 Total NaN in row 3788 : 0
 Total NaN in row 3789 : 0
 Total NaN in row 3790 : 0
 Total NaN in row 3791 : 1
 Total NaN in row 3792 : 9
 Total NaN in row 3793 : 9
 Total NaN in row 3794 : 1
 Total NaN in row 3795 : 1
 Total NaN in row 3796 : 2
 Total NaN in row 3797 : 1
 Total NaN in row 3798 : 9
 Total NaN in row 3799 : 21
 Total NaN in row 3800 : 0
 Total NaN in row 3801 : 0
 Total NaN in row 3802 : 0
 Total NaN in row 3803 : 0
 Total NaN in row 3804 : 0
 Total NaN in row 3805 : 1
 Total NaN in row 3806 : 0
 Total NaN in row 3807 : 0
 Total NaN in row 3808 : 10
 Total NaN in row 3809 : 0
 Total NaN in row 3810 : 0
 Total NaN in row 3811 : 0
 Total NaN in row 3812 : 0
 Total NaN in row 3813 : 2
 Total NaN in row 3814 : 0
 Total NaN in row 3815 : 1
 Total NaN in row 3816 : 1
 Total NaN in row 3817 : 1
 Total NaN in row 3818 : 0
 Total NaN in row 3819 : 1
 Total NaN in row 3820 : 2
 Total NaN in row 3821 : 1
 Total NaN in row 3822 : 2
 Total NaN in row 3823 : 2
 Total NaN in row 3824 : 1
 Total NaN in row 3825 : 0
 Total NaN in row 3826 : 2
 Total NaN in row 3827 : 2
 Total NaN in row 3828 : 0
 Total NaN in row 3829 : 0
 Total NaN in row 3830 : 2
 Total NaN in row 3831 : 3
 Total NaN in row 3832 : 0
 Total NaN in row 3833 : 0
 Total NaN in row 3834 : 2
 Total NaN in row 3835 : 0
 Total NaN in row 3836 : 1
 Total NaN in row 3837 : 1
 Total NaN in row 3838 : 0
 Total NaN in row 3839 : 0
 Total NaN in row 3840 : 3
 Total NaN in row 3841 : 1
 Total NaN in row 3842 : 2
 Total NaN in row 3843 : 2
 Total NaN in row 3844 : 1
 Total NaN in row 3845 : 0
 Total NaN in row 3846 : 1
 Total NaN in row 3847 : 9
 Total NaN in row 3848 : 0
 Total NaN in row 3849 : 1
 Total NaN in row 3850 : 0
 Total NaN in row 3851 : 9
 Total NaN in row 3852 : 1
 Total NaN in row 3853 : 1
 Total NaN in row 3854 : 2
 Total NaN in row 3855 : 9
 Total NaN in row 3856 : 21
 Total NaN in row 3857 : 0
 Total NaN in row 3858 : 1
 Total NaN in row 3859 : 0
 Total NaN in row 3860 : 0
 Total NaN in row 3861 : 0
 Total NaN in row 3862 : 1
 Total NaN in row 3863 : 2
 Total NaN in row 3864 : 0
 Total NaN in row 3865 : 2
 Total NaN in row 3866 : 0
 Total NaN in row 3867 : 3
 Total NaN in row 3868 : 0
 Total NaN in row 3869 : 3
 Total NaN in row 3870 : 3
 Total NaN in row 3871 : 1
 Total NaN in row 3872 : 3
 Total NaN in row 3873 : 0
 Total NaN in row 3874 : 2
 Total NaN in row 3875 : 0
 Total NaN in row 3876 : 1
 Total NaN in row 3877 : 9
 Total NaN in row 3878 : 0
 Total NaN in row 3879 : 2
 Total NaN in row 3880 : 0
 Total NaN in row 3881 : 2
 Total NaN in row 3882 : 9
 Total NaN in row 3883 : 9
 Total NaN in row 3884 : 0
 Total NaN in row 3885 : 1
 Total NaN in row 3886 : 0
 Total NaN in row 3887 : 2
 Total NaN in row 3888 : 1
 Total NaN in row 3889 : 3
 Total NaN in row 3890 : 2
 Total NaN in row 3891 : 1
 Total NaN in row 3892 : 3
 Total NaN in row 3893 : 1
 Total NaN in row 3894 : 1
 Total NaN in row 3895 : 1
 Total NaN in row 3896 : 0
 Total NaN in row 3897 : 0
 Total NaN in row 3898 : 1
 Total NaN in row 3899 : 0
 Total NaN in row 3900 : 1
 Total NaN in row 3901 : 0
 Total NaN in row 3902 : 0
 Total NaN in row 3903 : 1
 Total NaN in row 3904 : 9
 Total NaN in row 3905 : 1
 Total NaN in row 3906 : 1
 Total NaN in row 3907 : 2
 Total NaN in row 3908 : 1
 Total NaN in row 3909 : 0
 Total NaN in row 3910 : 10
 Total NaN in row 3911 : 1
 Total NaN in row 3912 : 0
 Total NaN in row 3913 : 0
 Total NaN in row 3914 : 1
 Total NaN in row 3915 : 9
 Total NaN in row 3916 : 3
 Total NaN in row 3917 : 3
 Total NaN in row 3918 : 0
 Total NaN in row 3919 : 0
 Total NaN in row 3920 : 0
 Total NaN in row 3921 : 0
 Total NaN in row 3922 : 2
 Total NaN in row 3923 : 2
 Total NaN in row 3924 : 0
 Total NaN in row 3925 : 2
 Total NaN in row 3926 : 3
 Total NaN in row 3927 : 0
 Total NaN in row 3928 : 2
 Total NaN in row 3929 : 2
 Total NaN in row 3930 : 3
 Total NaN in row 3931 : 0
 Total NaN in row 3932 : 0
 Total NaN in row 3933 : 0
 Total NaN in row 3934 : 0
 Total NaN in row 3935 : 0
 Total NaN in row 3936 : 0
 Total NaN in row 3937 : 3
 Total NaN in row 3938 : 0
 Total NaN in row 3939 : 0
 Total NaN in row 3940 : 2
 Total NaN in row 3941 : 3
 Total NaN in row 3942 : 2
 Total NaN in row 3943 : 0
 Total NaN in row 3944 : 0
 Total NaN in row 3945 : 0
 Total NaN in row 3946 : 9
 Total NaN in row 3947 : 1
 Total NaN in row 3948 : 1
 Total NaN in row 3949 : 10
 Total NaN in row 3950 : 0
 Total NaN in row 3951 : 0
 Total NaN in row 3952 : 9
 Total NaN in row 3953 : 0
 Total NaN in row 3954 : 9
 Total NaN in row 3955 : 0
 Total NaN in row 3956 : 1
 Total NaN in row 3957 : 1
 Total NaN in row 3958 : 1
 Total NaN in row 3959 : 1
 Total NaN in row 3960 : 1
 Total NaN in row 3961 : 1
 Total NaN in row 3962 : 0
 Total NaN in row 3963 : 0
 Total NaN in row 3964 : 0
 Total NaN in row 3965 : 2
 Total NaN in row 3966 : 2
 Total NaN in row 3967 : 9
 Total NaN in row 3968 : 0
 Total NaN in row 3969 : 3
 Total NaN in row 3970 : 2
 Total NaN in row 3971 : 0
 Total NaN in row 3972 : 1
 Total NaN in row 3973 : 0
 Total NaN in row 3974 : 0
 Total NaN in row 3975 : 0
 Total NaN in row 3976 : 2
 Total NaN in row 3977 : 2
 Total NaN in row 3978 : 0
 Total NaN in row 3979 : 0
 Total NaN in row 3980 : 3
 Total NaN in row 3981 : 0
 Total NaN in row 3982 : 0
 Total NaN in row 3983 : 9
 Total NaN in row 3984 : 0
 Total NaN in row 3985 : 1
 Total NaN in row 3986 : 0
 Total NaN in row 3987 : 9
 Total NaN in row 3988 : 9
 Total NaN in row 3989 : 2
 Total NaN in row 3990 : 3
 Total NaN in row 3991 : 0
 Total NaN in row 3992 : 0
 Total NaN in row 3993 : 0
 Total NaN in row 3994 : 2
 Total NaN in row 3995 : 1
 Total NaN in row 3996 : 2
 Total NaN in row 3997 : 2
 Total NaN in row 3998 : 3
 Total NaN in row 3999 : 2
 Total NaN in row 4000 : 0
 Total NaN in row 4001 : 1
 Total NaN in row 4002 : 9
 Total NaN in row 4003 : 9
 Total NaN in row 4004 : 1
 Total NaN in row 4005 : 1
 Total NaN in row 4006 : 2
 Total NaN in row 4007 : 0
 Total NaN in row 4008 : 9
 Total NaN in row 4009 : 10
 Total NaN in row 4010 : 1
 Total NaN in row 4011 : 10
 Total NaN in row 4012 : 2
 Total NaN in row 4013 : 1
 Total NaN in row 4014 : 0
 Total NaN in row 4015 : 0
 Total NaN in row 4016 : 2
 Total NaN in row 4017 : 0
 Total NaN in row 4018 : 1
 Total NaN in row 4019 : 2
 Total NaN in row 4020 : 2
 Total NaN in row 4021 : 2
 Total NaN in row 4022 : 0
 Total NaN in row 4023 : 2
 Total NaN in row 4024 : 1
 Total NaN in row 4025 : 2
 Total NaN in row 4026 : 0
 Total NaN in row 4027 : 2
 Total NaN in row 4028 : 0
 Total NaN in row 4029 : 0
 Total NaN in row 4030 : 0
 Total NaN in row 4031 : 0
 Total NaN in row 4032 : 9
 Total NaN in row 4033 : 0
 Total NaN in row 4034 : 9
 Total NaN in row 4035 : 0
 Total NaN in row 4036 : 2
 Total NaN in row 4037 : 2
 Total NaN in row 4038 : 0
 Total NaN in row 4039 : 1
 Total NaN in row 4040 : 2
 Total NaN in row 4041 : 2
 Total NaN in row 4042 : 0
 Total NaN in row 4043 : 2
 Total NaN in row 4044 : 0
 Total NaN in row 4045 : 0
 Total NaN in row 4046 : 2
 Total NaN in row 4047 : 2
 Total NaN in row 4048 : 1
 Total NaN in row 4049 : 2
 Total NaN in row 4050 : 9
 Total NaN in row 4051 : 2
 Total NaN in row 4052 : 0
 Total NaN in row 4053 : 0
 Total NaN in row 4054 : 0
 Total NaN in row 4055 : 2
 Total NaN in row 4056 : 2
 Total NaN in row 4057 : 0
 Total NaN in row 4058 : 0
 Total NaN in row 4059 : 2
 Total NaN in row 4060 : 2
 Total NaN in row 4061 : 0
 Total NaN in row 4062 : 2
 Total NaN in row 4063 : 0
 Total NaN in row 4064 : 1
 Total NaN in row 4065 : 0
 Total NaN in row 4066 : 2
 Total NaN in row 4067 : 0
 Total NaN in row 4068 : 2
 Total NaN in row 4069 : 0
 Total NaN in row 4070 : 2
 Total NaN in row 4071 : 0
 Total NaN in row 4072 : 2
 Total NaN in row 4073 : 2
 Total NaN in row 4074 : 0
 Total NaN in row 4075 : 7
 Total NaN in row 4076 : 2
 Total NaN in row 4077 : 1
 Total NaN in row 4078 : 9
 Total NaN in row 4079 : 1
 Total NaN in row 4080 : 1
 Total NaN in row 4081 : 0
 Total NaN in row 4082 : 9
 Total NaN in row 4083 : 0
 Total NaN in row 4084 : 2
 Total NaN in row 4085 : 4
 Total NaN in row 4086 : 0
 Total NaN in row 4087 : 0
 Total NaN in row 4088 : 0
 Total NaN in row 4089 : 1
 Total NaN in row 4090 : 21
 Total NaN in row 4091 : 2
 Total NaN in row 4092 : 0
 Total NaN in row 4093 : 3
 Total NaN in row 4094 : 9
 Total NaN in row 4095 : 9
 Total NaN in row 4096 : 1

 Total NaN in row 4097 : 21
 Total NaN in row 4098 : 2
 Total NaN in row 4099 : 0
 Total NaN in row 4100 : 0
 Total NaN in row 4101 : 1
 Total NaN in row 4102 : 0
 Total NaN in row 4103 : 0
 Total NaN in row 4104 : 3
 Total NaN in row 4105 : 0
 Total NaN in row 4106 : 2
 Total NaN in row 4107 : 1
 Total NaN in row 4108 : 0
 Total NaN in row 4109 : 2
 Total NaN in row 4110 : 1
 Total NaN in row 4111 : 10
 Total NaN in row 4112 : 2
 Total NaN in row 4113 : 0
 Total NaN in row 4114 : 0
 Total NaN in row 4115 : 9
 Total NaN in row 4116 : 9
 Total NaN in row 4117 : 1
 Total NaN in row 4118 : 2
 Total NaN in row 4119 : 2
 Total NaN in row 4120 : 0
 Total NaN in row 4121 : 0
 Total NaN in row 4122 : 9
 Total NaN in row 4123 : 0
 Total NaN in row 4124 : 2
 Total NaN in row 4125 : 2
 Total NaN in row 4126 : 0
 Total NaN in row 4127 : 2
 Total NaN in row 4128 : 0
 Total NaN in row 4129 : 0
 Total NaN in row 4130 : 0
 Total NaN in row 4131 : 0
 Total NaN in row 4132 : 1
 Total NaN in row 4133 : 1
 Total NaN in row 4134 : 9
 Total NaN in row 4135 : 2
 Total NaN in row 4136 : 9
 Total NaN in row 4137 : 1
 Total NaN in row 4138 : 2
 Total NaN in row 4139 : 0
 Total NaN in row 4140 : 2
 Total NaN in row 4141 : 2
 Total NaN in row 4142 : 0
 Total NaN in row 4143 : 2
 Total NaN in row 4144 : 0
 Total NaN in row 4145 : 0
 Total NaN in row 4146 : 0
 Total NaN in row 4147 : 0
 Total NaN in row 4148 : 2
 Total NaN in row 4149 : 1
 Total NaN in row 4150 : 0
 Total NaN in row 4151 : 2
 Total NaN in row 4152 : 1
 Total NaN in row 4153 : 2
 Total NaN in row 4154 : 2
 Total NaN in row 4155 : 0
 Total NaN in row 4156 : 1
 Total NaN in row 4157 : 0
 Total NaN in row 4158 : 0
 Total NaN in row 4159 : 0
 Total NaN in row 4160 : 1
 Total NaN in row 4161 : 0
 Total NaN in row 4162 : 2
 Total NaN in row 4163 : 9
 Total NaN in row 4164 : 0
 Total NaN in row 4165 : 21
 Total NaN in row 4166 : 3
 Total NaN in row 4167 : 0
 Total NaN in row 4168 : 1
 Total NaN in row 4169 : 2
 Total NaN in row 4170 : 1
 Total NaN in row 4171 : 9
 Total NaN in row 4172 : 0
 Total NaN in row 4173 : 0
 Total NaN in row 4174 : 0
 Total NaN in row 4175 : 1
 Total NaN in row 4176 : 0
 Total NaN in row 4177 : 0
 Total NaN in row 4178 : 10
 Total NaN in row 4179 : 0
 Total NaN in row 4180 : 2
 Total NaN in row 4181 : 0
 Total NaN in row 4182 : 1
 Total NaN in row 4183 : 1
 Total NaN in row 4184 : 0
 Total NaN in row 4185 : 2
 Total NaN in row 4186 : 1
 Total NaN in row 4187 : 9
 Total NaN in row 4188 : 2
 Total NaN in row 4189 : 0
 Total NaN in row 4190 : 1
 Total NaN in row 4191 : 2
 Total NaN in row 4192 : 2
 Total NaN in row 4193 : 2
 Total NaN in row 4194 : 1
 Total NaN in row 4195 : 1
 Total NaN in row 4196 : 0
 Total NaN in row 4197 : 0
 Total NaN in row 4198 : 2
 Total NaN in row 4199 : 1
 Total NaN in row 4200 : 0
 Total NaN in row 4201 : 3
 Total NaN in row 4202 : 3
 Total NaN in row 4203 : 0
 Total NaN in row 4204 : 0
 Total NaN in row 4205 : 0
 Total NaN in row 4206 : 0
 Total NaN in row 4207 : 2
 Total NaN in row 4208 : 1
 Total NaN in row 4209 : 9
 Total NaN in row 4210 : 0
 Total NaN in row 4211 : 2
 Total NaN in row 4212 : 0
 Total NaN in row 4213 : 2
 Total NaN in row 4214 : 0
 Total NaN in row 4215 : 3
 Total NaN in row 4216 : 3
 Total NaN in row 4217 : 0
 Total NaN in row 4218 : 2
 Total NaN in row 4219 : 21
 Total NaN in row 4220 : 1
 Total NaN in row 4221 : 1
 Total NaN in row 4222 : 0
 Total NaN in row 4223 : 21
 Total NaN in row 4224 : 10
 Total NaN in row 4225 : 1
 Total NaN in row 4226 : 1
 Total NaN in row 4227 : 0
 Total NaN in row 4228 : 2
 Total NaN in row 4229 : 0
 Total NaN in row 4230 : 0
 Total NaN in row 4231 : 1
 Total NaN in row 4232 : 2
 Total NaN in row 4233 : 1
 Total NaN in row 4234 : 9
 Total NaN in row 4235 : 0
 Total NaN in row 4236 : 2
 Total NaN in row 4237 : 1
 Total NaN in row 4238 : 2
 Total NaN in row 4239 : 0
 Total NaN in row 4240 : 1
 Total NaN in row 4241 : 9
 Total NaN in row 4242 : 2
 Total NaN in row 4243 : 1
 Total NaN in row 4244 : 0
 Total NaN in row 4245 : 0
 Total NaN in row 4246 : 10
 Total NaN in row 4247 : 2
 Total NaN in row 4248 : 0
 Total NaN in row 4249 : 2
 Total NaN in row 4250 : 0
 Total NaN in row 4251 : 10
 Total NaN in row 4252 : 2
 Total NaN in row 4253 : 0
 Total NaN in row 4254 : 1
 Total NaN in row 4255 : 9
 Total NaN in row 4256 : 0
 Total NaN in row 4257 : 0
 Total NaN in row 4258 : 1
 Total NaN in row 4259 : 1
 Total NaN in row 4260 : 0
 Total NaN in row 4261 : 0
 Total NaN in row 4262 : 0
 Total NaN in row 4263 : 0
 Total NaN in row 4264 : 1
 Total NaN in row 4265 : 2
 Total NaN in row 4266 : 1
 Total NaN in row 4267 : 0
 Total NaN in row 4268 : 0
 Total NaN in row 4269 : 0
 Total NaN in row 4270 : 2
 Total NaN in row 4271 : 0
 Total NaN in row 4272 : 1
 Total NaN in row 4273 : 9
 Total NaN in row 4274 : 1
 Total NaN in row 4275 : 2
 Total NaN in row 4276 : 1
 Total NaN in row 4277 : 0
 Total NaN in row 4278 : 2
 Total NaN in row 4279 : 0
 Total NaN in row 4280 : 10
 Total NaN in row 4281 : 0
 Total NaN in row 4282 : 0
 Total NaN in row 4283 : 0
 Total NaN in row 4284 : 2
 Total NaN in row 4285 : 2
 Total NaN in row 4286 : 1
 Total NaN in row 4287 : 0
 Total NaN in row 4288 : 1
 Total NaN in row 4289 : 2
 Total NaN in row 4290 : 0
 Total NaN in row 4291 : 1
 Total NaN in row 4292 : 2
 Total NaN in row 4293 : 2
 Total NaN in row 4294 : 9
 Total NaN in row 4295 : 1
 Total NaN in row 4296 : 0
 Total NaN in row 4297 : 0
 Total NaN in row 4298 : 0
 Total NaN in row 4299 : 1
 Total NaN in row 4300 : 2
 Total NaN in row 4301 : 3
 Total NaN in row 4302 : 10
 Total NaN in row 4303 : 0
 Total NaN in row 4304 : 0
 Total NaN in row 4305 : 1
 Total NaN in row 4306 : 2
 Total NaN in row 4307 : 1
 Total NaN in row 4308 : 2
 Total NaN in row 4309 : 2
 Total NaN in row 4310 : 0
 Total NaN in row 4311 : 0
 Total NaN in row 4312 : 2
 Total NaN in row 4313 : 0
 Total NaN in row 4314 : 0
 Total NaN in row 4315 : 9
 Total NaN in row 4316 : 2
 Total NaN in row 4317 : 0
 Total NaN in row 4318 : 2
 Total NaN in row 4319 : 1
 Total NaN in row 4320 : 0
 Total NaN in row 4321 : 1
 Total NaN in row 4322 : 2
 Total NaN in row 4323 : 2
 Total NaN in row 4324 : 2
 Total NaN in row 4325 : 0
 Total NaN in row 4326 : 1
 Total NaN in row 4327 : 21
 Total NaN in row 4328 : 1
 Total NaN in row 4329 : 2
 Total NaN in row 4330 : 0
 Total NaN in row 4331 : 2
 Total NaN in row 4332 : 1
 Total NaN in row 4333 : 0
 Total NaN in row 4334 : 2
 Total NaN in row 4335 : 0
 Total NaN in row 4336 : 2
 Total NaN in row 4337 : 7
 Total NaN in row 4338 : 0
 Total NaN in row 4339 : 0
 Total NaN in row 4340 : 0
 Total NaN in row 4341 : 2
 Total NaN in row 4342 : 2
 Total NaN in row 4343 : 0
 Total NaN in row 4344 : 2
 Total NaN in row 4345 : 2
 Total NaN in row 4346 : 3
 Total NaN in row 4347 : 2
 Total NaN in row 4348 : 1
 Total NaN in row 4349 : 0
 Total NaN in row 4350 : 9
 Total NaN in row 4351 : 2
 Total NaN in row 4352 : 0
 Total NaN in row 4353 : 1
 Total NaN in row 4354 : 1
 Total NaN in row 4355 : 9
 Total NaN in row 4356 : 2
 Total NaN in row 4357 : 0
 Total NaN in row 4358 : 1
 Total NaN in row 4359 : 0
 Total NaN in row 4360 : 0
 Total NaN in row 4361 : 2
 Total NaN in row 4362 : 0
 Total NaN in row 4363 : 0
 Total NaN in row 4364 : 2
 Total NaN in row 4365 : 0
 Total NaN in row 4366 : 1
 Total NaN in row 4367 : 9
 Total NaN in row 4368 : 2
 Total NaN in row 4369 : 1
 Total NaN in row 4370 : 9
 Total NaN in row 4371 : 0
 Total NaN in row 4372 : 2
 Total NaN in row 4373 : 1
 Total NaN in row 4374 : 2
 Total NaN in row 4375 : 2
 Total NaN in row 4376 : 0
 Total NaN in row 4377 : 2
 Total NaN in row 4378 : 2
 Total NaN in row 4379 : 9
 Total NaN in row 4380 : 0
 Total NaN in row 4381 : 1
 Total NaN in row 4382 : 0
 Total NaN in row 4383 : 0
 Total NaN in row 4384 : 2
 Total NaN in row 4385 : 1
 Total NaN in row 4386 : 1
 Total NaN in row 4387 : 0
 Total NaN in row 4388 : 9
 Total NaN in row 4389 : 1
 Total NaN in row 4390 : 0
 Total NaN in row 4391 : 0
 Total NaN in row 4392 : 1
 Total NaN in row 4393 : 3
 Total NaN in row 4394 : 2
 Total NaN in row 4395 : 1
 Total NaN in row 4396 : 0
 Total NaN in row 4397 : 2
 Total NaN in row 4398 : 0
 Total NaN in row 4399 : 0
 Total NaN in row 4400 : 0
 Total NaN in row 4401 : 0
 Total NaN in row 4402 : 0
 Total NaN in row 4403 : 0
 Total NaN in row 4404 : 0
 Total NaN in row 4405 : 0
 Total NaN in row 4406 : 0
 Total NaN in row 4407 : 0
 Total NaN in row 4408 : 2
 Total NaN in row 4409 : 0
 Total NaN in row 4410 : 1
 Total NaN in row 4411 : 0
 Total NaN in row 4412 : 0
 Total NaN in row 4413 : 1
 Total NaN in row 4414 : 7
 Total NaN in row 4415 : 0
 Total NaN in row 4416 : 1
 Total NaN in row 4417 : 0
 Total NaN in row 4418 : 2
 Total NaN in row 4419 : 2
 Total NaN in row 4420 : 0
 Total NaN in row 4421 : 2
 Total NaN in row 4422 : 0
 Total NaN in row 4423 : 0
 Total NaN in row 4424 : 1
 Total NaN in row 4425 : 1
 Total NaN in row 4426 : 1
 Total NaN in row 4427 : 0
 Total NaN in row 4428 : 0
 Total NaN in row 4429 : 0
 Total NaN in row 4430 : 2
 Total NaN in row 4431 : 0
 Total NaN in row 4432 : 2
 Total NaN in row 4433 : 9
 Total NaN in row 4434 : 0
 Total NaN in row 4435 : 0
 Total NaN in row 4436 : 2
 Total NaN in row 4437 : 1
 Total NaN in row 4438 : 2
 Total NaN in row 4439 : 0
 Total NaN in row 4440 : 0
 Total NaN in row 4441 : 0
 Total NaN in row 4442 : 0
 Total NaN in row 4443 : 0
 Total NaN in row 4444 : 0
 Total NaN in row 4445 : 0
 Total NaN in row 4446 : 1
 Total NaN in row 4447 : 0
 Total NaN in row 4448 : 1
 Total NaN in row 4449 : 2
 Total NaN in row 4450 : 0
 Total NaN in row 4451 : 3
 Total NaN in row 4452 : 0
 Total NaN in row 4453 : 1
 Total NaN in row 4454 : 2
 Total NaN in row 4455 : 1
 Total NaN in row 4456 : 0
 Total NaN in row 4457 : 0
 Total NaN in row 4458 : 1
 Total NaN in row 4459 : 2
 Total NaN in row 4460 : 2
 Total NaN in row 4461 : 9
 Total NaN in row 4462 : 1
 Total NaN in row 4463 : 2
 Total NaN in row 4464 : 0
 Total NaN in row 4465 : 0
 Total NaN in row 4466 : 2
 Total NaN in row 4467 : 0
 Total NaN in row 4468 : 0
 Total NaN in row 4469 : 9
 Total NaN in row 4470 : 9
 Total NaN in row 4471 : 1
 Total NaN in row 4472 : 0
 Total NaN in row 4473 : 0
 Total NaN in row 4474 : 0
 Total NaN in row 4475 : 0
 Total NaN in row 4476 : 0
 Total NaN in row 4477 : 1
 Total NaN in row 4478 : 1
 Total NaN in row 4479 : 1
 Total NaN in row 4480 : 9
 Total NaN in row 4481 : 0
 Total NaN in row 4482 : 0
 Total NaN in row 4483 : 2
 Total NaN in row 4484 : 0
 Total NaN in row 4485 : 0
 Total NaN in row 4486 : 9
 Total NaN in row 4487 : 0
 Total NaN in row 4488 : 1
 Total NaN in row 4489 : 7
 Total NaN in row 4490 : 2
 Total NaN in row 4491 : 3
 Total NaN in row 4492 : 1
 Total NaN in row 4493 : 9
 Total NaN in row 4494 : 0
 Total NaN in row 4495 : 2
 Total NaN in row 4496 : 0
 Total NaN in row 4497 : 1
 Total NaN in row 4498 : 0
 Total NaN in row 4499 : 0
 Total NaN in row 4500 : 2
 Total NaN in row 4501 : 0
 Total NaN in row 4502 : 2
 Total NaN in row 4503 : 2
 Total NaN in row 4504 : 2
 Total NaN in row 4505 : 1
 Total NaN in row 4506 : 2
 Total NaN in row 4507 : 0
 Total NaN in row 4508 : 9
 Total NaN in row 4509 : 0
 Total NaN in row 4510 : 0
 Total NaN in row 4511 : 9
 Total NaN in row 4512 : 1
 Total NaN in row 4513 : 0
 Total NaN in row 4514 : 0
 Total NaN in row 4515 : 0
 Total NaN in row 4516 : 0
 Total NaN in row 4517 : 0
 Total NaN in row 4518 : 9
 Total NaN in row 4519 : 2
 Total NaN in row 4520 : 1
 Total NaN in row 4521 : 0
 Total NaN in row 4522 : 0
 Total NaN in row 4523 : 0
 Total NaN in row 4524 : 10
 Total NaN in row 4525 : 9
 Total NaN in row 4526 : 9

 Total NaN in row 4527 : 9
 Total NaN in row 4528 : 1
 Total NaN in row 4529 : 0
 Total NaN in row 4530 : 0
 Total NaN in row 4531 : 9
 Total NaN in row 4532 : 9
 Total NaN in row 4533 : 10
 Total NaN in row 4534 : 2
 Total NaN in row 4535 : 2
 Total NaN in row 4536 : 0
 Total NaN in row 4537 : 3
 Total NaN in row 4538 : 9
 Total NaN in row 4539 : 0
 Total NaN in row 4540 : 0
 Total NaN in row 4541 : 2
 Total NaN in row 4542 : 9
 Total NaN in row 4543 : 1
 Total NaN in row 4544 : 2
 Total NaN in row 4545 : 0
 Total NaN in row 4546 : 1
 Total NaN in row 4547 : 0
 Total NaN in row 4548 : 3
 Total NaN in row 4549 : 3
 Total NaN in row 4550 : 0
 Total NaN in row 4551 : 1
 Total NaN in row 4552 : 1
 Total NaN in row 4553 : 0
 Total NaN in row 4554 : 9
 Total NaN in row 4555 : 0
 Total NaN in row 4556 : 0
 Total NaN in row 4557 : 0
 Total NaN in row 4558 : 2
 Total NaN in row 4559 : 9
 Total NaN in row 4560 : 1
 Total NaN in row 4561 : 0
 Total NaN in row 4562 : 0
 Total NaN in row 4563 : 3
 Total NaN in row 4564 : 1
 Total NaN in row 4565 : 2
 Total NaN in row 4566 : 2
 Total NaN in row 4567 : 9
 Total NaN in row 4568 : 2
 Total NaN in row 4569 : 0
 Total NaN in row 4570 : 0
 Total NaN in row 4571 : 9
 Total NaN in row 4572 : 10
 Total NaN in row 4573 : 0
 Total NaN in row 4574 : 2
 Total NaN in row 4575 : 3
 Total NaN in row 4576 : 2
 Total NaN in row 4577 : 3
 Total NaN in row 4578 : 1
 Total NaN in row 4579 : 1
 Total NaN in row 4580 : 2
 Total NaN in row 4581 : 9
 Total NaN in row 4582 : 0
 Total NaN in row 4583 : 1
 Total NaN in row 4584 : 2
 Total NaN in row 4585 : 1
 Total NaN in row 4586 : 3
 Total NaN in row 4587 : 10
 Total NaN in row 4588 : 2
 Total NaN in row 4589 : 1
 Total NaN in row 4590 : 2
 Total NaN in row 4591 : 1
 Total NaN in row 4592 : 0
 Total NaN in row 4593 : 10
 Total NaN in row 4594 : 9
 Total NaN in row 4595 : 0
 Total NaN in row 4596 : 3
 Total NaN in row 4597 : 2
 Total NaN in row 4598 : 2
 Total NaN in row 4599 : 10
 Total NaN in row 4600 : 0
 Total NaN in row 4601 : 2
 Total NaN in row 4602 : 2
 Total NaN in row 4603 : 3
 Total NaN in row 4604 : 1
 Total NaN in row 4605 : 2
 Total NaN in row 4606 : 0
 Total NaN in row 4607 : 2
 Total NaN in row 4608 : 0
 Total NaN in row 4609 : 2
 Total NaN in row 4610 : 9
 Total NaN in row 4611 : 1
 Total NaN in row 4612 : 0
 Total NaN in row 4613 : 9
 Total NaN in row 4614 : 9
 Total NaN in row 4615 : 9
 Total NaN in row 4616 : 1
 Total NaN in row 4617 : 1
 Total NaN in row 4618 : 0
 Total NaN in row 4619 : 2
 Total NaN in row 4620 : 2
 Total NaN in row 4621 : 1
 Total NaN in row 4622 : 1
 Total NaN in row 4623 : 1
 Total NaN in row 4624 : 10
 Total NaN in row 4625 : 2
 Total NaN in row 4626 : 0
 Total NaN in row 4627 : 0
 Total NaN in row 4628 : 2
 Total NaN in row 4629 : 1
 Total NaN in row 4630 : 1
 Total NaN in row 4631 : 2
 Total NaN in row 4632 : 1
 Total NaN in row 4633 : 2
 Total NaN in row 4634 : 0
 Total NaN in row 4635 : 1
 Total NaN in row 4636 : 0
 Total NaN in row 4637 : 10
 Total NaN in row 4638 : 2
 Total NaN in row 4639 : 1
 Total NaN in row 4640 : 9
 Total NaN in row 4641 : 1
 Total NaN in row 4642 : 3
 Total NaN in row 4643 : 1
 Total NaN in row 4644 : 1
 Total NaN in row 4645 : 0
 Total NaN in row 4646 : 1
 Total NaN in row 4647 : 0
 Total NaN in row 4648 : 3
 Total NaN in row 4649 : 2
 Total NaN in row 4650 : 21
 Total NaN in row 4651 : 3
 Total NaN in row 4652 : 1
 Total NaN in row 4653 : 1
 Total NaN in row 4654 : 0
 Total NaN in row 4655 : 2
 Total NaN in row 4656 : 9
 Total NaN in row 4657 : 2
 Total NaN in row 4658 : 0
 Total NaN in row 4659 : 9
 Total NaN in row 4660 : 2
 Total NaN in row 4661 : 2
 Total NaN in row 4662 : 3
 Total NaN in row 4663 : 0
 Total NaN in row 4664 : 0
 Total NaN in row 4665 : 7
 Total NaN in row 4666 : 0
 Total NaN in row 4667 : 2
 Total NaN in row 4668 : 2
 Total NaN in row 4669 : 10
 Total NaN in row 4670 : 3
 Total NaN in row 4671 : 2
 Total NaN in row 4672 : 1
 Total NaN in row 4673 : 0
 Total NaN in row 4674 : 1
 Total NaN in row 4675 : 2
 Total NaN in row 4676 : 2
 Total NaN in row 4677 : 2
 Total NaN in row 4678 : 9
 Total NaN in row 4679 : 1
 Total NaN in row 4680 : 1
 Total NaN in row 4681 : 2
 Total NaN in row 4682 : 2
 Total NaN in row 4683 : 1
 Total NaN in row 4684 : 2
 Total NaN in row 4685 : 0
 Total NaN in row 4686 : 1
 Total NaN in row 4687 : 1
 Total NaN in row 4688 : 1
 Total NaN in row 4689 : 10
 Total NaN in row 4690 : 0
 Total NaN in row 4691 : 0
 Total NaN in row 4692 : 0
 Total NaN in row 4693 : 10
 Total NaN in row 4694 : 1
 Total NaN in row 4695 : 3
 Total NaN in row 4696 : 9
 Total NaN in row 4697 : 1
 Total NaN in row 4698 : 2
 Total NaN in row 4699 : 1
 Total NaN in row 4700 : 1
 Total NaN in row 4701 : 2
 Total NaN in row 4702 : 2
 Total NaN in row 4703 : 1
 Total NaN in row 4704 : 2
 Total NaN in row 4705 : 3
 Total NaN in row 4706 : 10
 Total NaN in row 4707 : 0
 Total NaN in row 4708 : 0
 Total NaN in row 4709 : 0
 Total NaN in row 4710 : 0
 Total NaN in row 4711 : 2
 Total NaN in row 4712 : 10
 Total NaN in row 4713 : 0
 Total NaN in row 4714 : 0
 Total NaN in row 4715 : 10
 Total NaN in row 4716 : 0
 Total NaN in row 4717 : 2
 Total NaN in row 4718 : 2
 Total NaN in row 4719 : 0
 Total NaN in row 4720 : 0
 Total NaN in row 4721 : 0
 Total NaN in row 4722 : 10
 Total NaN in row 4723 : 0
 Total NaN in row 4724 : 10
 Total NaN in row 4725 : 10
 Total NaN in row 4726 : 9
 Total NaN in row 4727 : 2
 Total NaN in row 4728 : 1
 Total NaN in row 4729 : 1
 Total NaN in row 4730 : 1
 Total NaN in row 4731 : 2
 Total NaN in row 4732 : 1
 Total NaN in row 4733 : 0
 Total NaN in row 4734 : 1
 Total NaN in row 4735 : 1
 Total NaN in row 4736 : 1
 Total NaN in row 4737 : 0
 Total NaN in row 4738 : 1
 Total NaN in row 4739 : 0
 Total NaN in row 4740 : 1
 Total NaN in row 4741 : 2
 Total NaN in row 4742 : 0
 Total NaN in row 4743 : 1
 Total NaN in row 4744 : 2
 Total NaN in row 4745 : 1
 Total NaN in row 4746 : 10
 Total NaN in row 4747 : 9
 Total NaN in row 4748 : 2
 Total NaN in row 4749 : 0
 Total NaN in row 4750 : 9
 Total NaN in row 4751 : 2
 Total NaN in row 4752 : 0
 Total NaN in row 4753 : 0
 Total NaN in row 4754 : 2
 Total NaN in row 4755 : 3
 Total NaN in row 4756 : 9
 Total NaN in row 4757 : 9
 Total NaN in row 4758 : 0
 Total NaN in row 4759 : 9
 Total NaN in row 4760 : 9
 Total NaN in row 4761 : 9
 Total NaN in row 4762 : 9
 Total NaN in row 4763 : 2
 Total NaN in row 4764 : 0
 Total NaN in row 4765 : 1
 Total NaN in row 4766 : 2
 Total NaN in row 4767 : 9
 Total NaN in row 4768 : 0
 Total NaN in row 4769 : 1
 Total NaN in row 4770 : 2
 Total NaN in row 4771 : 2
 Total NaN in row 4772 : 10
 Total NaN in row 4773 : 9
 Total NaN in row 4774 : 9
 Total NaN in row 4775 : 9
 Total NaN in row 4776 : 0
 Total NaN in row 4777 : 0
 Total NaN in row 4778 : 1
 Total NaN in row 4779 : 0
 Total NaN in row 4780 : 9
 Total NaN in row 4781 : 9
 Total NaN in row 4782 : 9
 Total NaN in row 4783 : 3
 Total NaN in row 4784 : 2
 Total NaN in row 4785 : 0
 Total NaN in row 4786 : 2
 Total NaN in row 4787 : 2
 Total NaN in row 4788 : 0
 Total NaN in row 4789 : 9
 Total NaN in row 4790 : 9
 Total NaN in row 4791 : 9
 Total NaN in row 4792 : 2
 Total NaN in row 4793 : 3
 Total NaN in row 4794 : 1
 Total NaN in row 4795 : 0
 Total NaN in row 4796 : 2
 Total NaN in row 4797 : 2
 Total NaN in row 4798 : 0
 Total NaN in row 4799 : 1
 Total NaN in row 4800 : 10
 Total NaN in row 4801 : 2
 Total NaN in row 4802 : 2
 Total NaN in row 4803 : 9
 Total NaN in row 4804 : 9
 Total NaN in row 4805 : 9
 Total NaN in row 4806 : 0
 Total NaN in row 4807 : 10
 Total NaN in row 4808 : 9
 Total NaN in row 4809 : 0
 Total NaN in row 4810 : 2
 Total NaN in row 4811 : 0
 Total NaN in row 4812 : 0
 Total NaN in row 4813 : 9
 Total NaN in row 4814 : 9
 Total NaN in row 4815 : 9
 Total NaN in row 4816 : 0
 Total NaN in row 4817 : 2
 Total NaN in row 4818 : 0
 Total NaN in row 4819 : 9
 Total NaN in row 4820 : 9
 Total NaN in row 4821 : 10
 Total NaN in row 4822 : 0
 Total NaN in row 4823 : 0
 Total NaN in row 4824 : 9
 Total NaN in row 4825 : 9
 Total NaN in row 4826 : 0
 Total NaN in row 4827 : 0
 Total NaN in row 4828 : 2
 Total NaN in row 4829 : 9
 Total NaN in row 4830 : 9
 Total NaN in row 4831 : 9
 Total NaN in row 4832 : 0
 Total NaN in row 4833 : 0
 Total NaN in row 4834 : 1
 Total NaN in row 4835 : 1
 Total NaN in row 4836 : 9
 Total NaN in row 4837 : 0
 Total NaN in row 4838 : 10
 Total NaN in row 4839 : 0
 Total NaN in row 4840 : 2
 Total NaN in row 4841 : 2
 Total NaN in row 4842 : 9
 Total NaN in row 4843 : 9
 Total NaN in row 4844 : 0
 Total NaN in row 4845 : 9
 Total NaN in row 4846 : 3
 Total NaN in row 4847 : 0
 Total NaN in row 4848 : 0
 Total NaN in row 4849 : 1
 Total NaN in row 4850 : 9
 Total NaN in row 4851 : 2
 Total NaN in row 4852 : 3
 Total NaN in row 4853 : 2
 Total NaN in row 4854 : 9
 Total NaN in row 4855 : 9
 Total NaN in row 4856 : 2
 Total NaN in row 4857 : 0
 Total NaN in row 4858 : 0
 Total NaN in row 4859 : 1
 Total NaN in row 4860 : 9
 Total NaN in row 4861 : 9
 Total NaN in row 4862 : 1
 Total NaN in row 4863 : 9
 Total NaN in row 4864 : 1
 Total NaN in row 4865 : 9
 Total NaN in row 4866 : 0
 Total NaN in row 4867 : 1
 Total NaN in row 4868 : 9
 Total NaN in row 4869 : 9
 Total NaN in row 4870 : 0
 Total NaN in row 4871 : 3
 Total NaN in row 4872 : 9
 Total NaN in row 4873 : 1
 Total NaN in row 4874 : 0
 Total NaN in row 4875 : 9
 Total NaN in row 4876 : 0
 Total NaN in row 4877 : 10
 Total NaN in row 4878 : 0
 Total NaN in row 4879 : 2
 Total NaN in row 4880 : 9
 Total NaN in row 4881 : 0
 Total NaN in row 4882 : 9
 Total NaN in row 4883 : 0
 Total NaN in row 4884 : 2
 Total NaN in row 4885 : 9
 Total NaN in row 4886 : 10
 Total NaN in row 4887 : 0
 Total NaN in row 4888 : 9
 Total NaN in row 4889 : 0
 Total NaN in row 4890 : 0
 Total NaN in row 4891 : 9
 Total NaN in row 4892 : 9
 Total NaN in row 4893 : 0
 Total NaN in row 4894 : 2
 Total NaN in row 4895 : 9
 Total NaN in row 4896 : 2
 Total NaN in row 4897 : 0
 Total NaN in row 4898 : 21
 Total NaN in row 4899 : 0
 Total NaN in row 4900 : 0
 Total NaN in row 4901 : 1
 Total NaN in row 4902 : 1
 Total NaN in row 4903 : 2
 Total NaN in row 4904 : 2
 Total NaN in row 4905 : 10
 Total NaN in row 4906 : 9
 Total NaN in row 4907 : 9
 Total NaN in row 4908 : 9
 Total NaN in row 4909 : 10
 Total NaN in row 4910 : 0
 Total NaN in row 4911 : 2
 Total NaN in row 4912 : 0
 Total NaN in row 4913 : 10
 Total NaN in row 4914 : 9
 Total NaN in row 4915 : 9
 Total NaN in row 4916 : 0
 Total NaN in row 4917 : 0
 Total NaN in row 4918 : 0
 Total NaN in row 4919 : 9
 Total NaN in row 4920 : 0
 Total NaN in row 4921 : 2
 Total NaN in row 4922 : 0
 Total NaN in row 4923 : 9
 Total NaN in row 4924 : 9
 Total NaN in row 4925 : 9
 Total NaN in row 4926 : 9
 Total NaN in row 4927 : 2
 Total NaN in row 4928 : 0
 Total NaN in row 4929 : 0
 Total NaN in row 4930 : 9
 Total NaN in row 4931 : 0
 Total NaN in row 4932 : 0
 Total NaN in row 4933 : 0
 Total NaN in row 4934 : 9
 Total NaN in row 4935 : 2
 Total NaN in row 4936 : 0
 Total NaN in row 4937 : 1
 Total NaN in row 4938 : 0
 Total NaN in row 4939 : 9
 Total NaN in row 4940 : 0
 Total NaN in row 4941 : 0
 Total NaN in row 4942 : 2
 Total NaN in row 4943 : 21
 Total NaN in row 4944 : 0
 Total NaN in row 4945 : 2
 Total NaN in row 4946 : 9
 Total NaN in row 4947 : 0
 Total NaN in row 4948 : 9
 Total NaN in row 4949 : 0
 Total NaN in row 4950 : 9
 Total NaN in row 4951 : 9
 Total NaN in row 4952 : 0
 Total NaN in row 4953 : 2
 Total NaN in row 4954 : 0
 Total NaN in row 4955 : 9
 Total NaN in row 4956 : 0
 Total NaN in row 4957 : 9
 Total NaN in row 4958 : 0
 Total NaN in row 4959 : 0
 Total NaN in row 4960 : 0
 Total NaN in row 4961 : 0
 Total NaN in row 4962 : 0
 Total NaN in row 4963 : 2
 Total NaN in row 4964 : 2

 Total NaN in row 4965 : 1
 Total NaN in row 4966 : 1
 Total NaN in row 4967 : 9
 Total NaN in row 4968 : 9
 Total NaN in row 4969 : 1
 Total NaN in row 4970 : 0
 Total NaN in row 4971 : 0
 Total NaN in row 4972 : 0
 Total NaN in row 4973 : 1
 Total NaN in row 4974 : 0
 Total NaN in row 4975 : 0
 Total NaN in row 4976 : 2
 Total NaN in row 4977 : 2
 Total NaN in row 4978 : 0
 Total NaN in row 4979 : 0
 Total NaN in row 4980 : 1
 Total NaN in row 4981 : 1
 Total NaN in row 4982 : 0
 Total NaN in row 4983 : 0
 Total NaN in row 4984 : 2
 Total NaN in row 4985 : 0
 Total NaN in row 4986 : 9
 Total NaN in row 4987 : 0
 Total NaN in row 4988 : 0
 Total NaN in row 4989 : 9
 Total NaN in row 4990 : 9
 Total NaN in row 4991 : 0
 Total NaN in row 4992 : 1
 Total NaN in row 4993 : 0
 Total NaN in row 4994 : 2
 Total NaN in row 4995 : 2
 Total NaN in row 4996 : 0
 Total NaN in row 4997 : 0
 Total NaN in row 4998 : 10
 Total NaN in row 4999 : 2
 Total NaN in row 5000 : 1
 Total NaN in row 5001 : 2
 Total NaN in row 5002 : 1
 Total NaN in row 5003 : 0
 Total NaN in row 5004 : 2
 Total NaN in row 5005 : 0
 Total NaN in row 5006 : 10
 Total NaN in row 5007 : 9
 Total NaN in row 5008 : 3
 Total NaN in row 5009 : 1
 Total NaN in row 5010 : 2
 Total NaN in row 5011 : 0
 Total NaN in row 5012 : 2
 Total NaN in row 5013 : 2
 Total NaN in row 5014 : 2
 Total NaN in row 5015 : 0
 Total NaN in row 5016 : 0
 Total NaN in row 5017 : 0
 Total NaN in row 5018 : 2
 Total NaN in row 5019 : 0
 Total NaN in row 5020 : 9
 Total NaN in row 5021 : 0
 Total NaN in row 5022 : 2
 Total NaN in row 5023 : 0
 Total NaN in row 5024 : 1
 Total NaN in row 5025 : 2
 Total NaN in row 5026 : 0
 Total NaN in row 5027 : 0
 Total NaN in row 5028 : 2
 Total NaN in row 5029 : 2
 Total NaN in row 5030 : 10
 Total NaN in row 5031 : 1
 Total NaN in row 5032 : 0
 Total NaN in row 5033 : 9
 Total NaN in row 5034 : 1
 Total NaN in row 5035 : 9
 Total NaN in row 5036 : 2
 Total NaN in row 5037 : 9
 Total NaN in row 5038 : 10
 Total NaN in row 5039 : 1
 Total NaN in row 5040 : 9
 Total NaN in row 5041 : 0
 Total NaN in row 5042 : 0
 Total NaN in row 5043 : 0
 Total NaN in row 5044 : 1
 Total NaN in row 5045 : 1
 Total NaN in row 5046 : 3
 Total NaN in row 5047 : 2
 Total NaN in row 5048 : 0
 Total NaN in row 5049 : 1
 Total NaN in row 5050 : 9
 Total NaN in row 5051 : 0
 Total NaN in row 5052 : 0
 Total NaN in row 5053 : 21
 Total NaN in row 5054 : 2
 Total NaN in row 5055 : 0
 Total NaN in row 5056 : 2
 Total NaN in row 5057 : 0
 Total NaN in row 5058 : 9
 Total NaN in row 5059 : 1
 Total NaN in row 5060 : 2
 Total NaN in row 5061 : 9
 Total NaN in row 5062 : 9
 Total NaN in row 5063 : 2
 Total NaN in row 5064 : 2
 Total NaN in row 5065 : 2
 Total NaN in row 5066 : 1
 Total NaN in row 5067 : 0
 Total NaN in row 5068 : 2
 Total NaN in row 5069 : 1
 Total NaN in row 5070 : 2
 Total NaN in row 5071 : 0
 Total NaN in row 5072 : 1
 Total NaN in row 5073 : 2
 Total NaN in row 5074 : 1
 Total NaN in row 5075 : 2
 Total NaN in row 5076 : 9
 Total NaN in row 5077 : 0
 Total NaN in row 5078 : 2
 Total NaN in row 5079 : 0
 Total NaN in row 5080 : 1
 Total NaN in row 5081 : 10
 Total NaN in row 5082 : 0
 Total NaN in row 5083 : 2
 Total NaN in row 5084 : 9
 Total NaN in row 5085 : 1
 Total NaN in row 5086 : 1
 Total NaN in row 5087 : 1
 Total NaN in row 5088 : 0
 Total NaN in row 5089 : 9
 Total NaN in row 5090 : 1
 Total NaN in row 5091 : 0
 Total NaN in row 5092 : 9
 Total NaN in row 5093 : 1
 Total NaN in row 5094 : 2
 Total NaN in row 5095 : 0
 Total NaN in row 5096 : 2
 Total NaN in row 5097 : 9
 Total NaN in row 5098 : 0
 Total NaN in row 5099 : 9
 Total NaN in row 5100 : 2
 Total NaN in row 5101 : 9
 Total NaN in row 5102 : 1
 Total NaN in row 5103 : 2
 Total NaN in row 5104 : 2
 Total NaN in row 5105 : 2
 Total NaN in row 5106 : 1
 Total NaN in row 5107 : 0
 Total NaN in row 5108 : 0
 Total NaN in row 5109 : 1
 Total NaN in row 5110 : 9
 Total NaN in row 5111 : 1
 Total NaN in row 5112 : 0
 Total NaN in row 5113 : 1
 Total NaN in row 5114 : 2
 Total NaN in row 5115 : 0
 Total NaN in row 5116 : 1
 Total NaN in row 5117 : 2
 Total NaN in row 5118 : 0
 Total NaN in row 5119 : 2
 Total NaN in row 5120 : 0
 Total NaN in row 5121 : 9
 Total NaN in row 5122 : 2
 Total NaN in row 5123 : 1
 Total NaN in row 5124 : 9
 Total NaN in row 5125 : 0
 Total NaN in row 5126 : 0
 Total NaN in row 5127 : 3
 Total NaN in row 5128 : 2
 Total NaN in row 5129 : 2
 Total NaN in row 5130 : 1
 Total NaN in row 5131 : 9
 Total NaN in row 5132 : 1
 Total NaN in row 5133 : 0
 Total NaN in row 5134 : 2
 Total NaN in row 5135 : 0
 Total NaN in row 5136 : 10
 Total NaN in row 5137 : 9
 Total NaN in row 5138 : 9
 Total NaN in row 5139 : 3
 Total NaN in row 5140 : 9
 Total NaN in row 5141 : 0
 Total NaN in row 5142 : 9
 Total NaN in row 5143 : 1
 Total NaN in row 5144 : 9
 Total NaN in row 5145 : 2
 Total NaN in row 5146 : 1
 Total NaN in row 5147 : 0
 Total NaN in row 5148 : 9
 Total NaN in row 5149 : 0
 Total NaN in row 5150 : 2
 Total NaN in row 5151 : 9
 Total NaN in row 5152 : 10
 Total NaN in row 5153 : 10
 Total NaN in row 5154 : 10
 Total NaN in row 5155 : 10
 Total NaN in row 5156 : 0
 Total NaN in row 5157 : 9
 Total NaN in row 5158 : 9
 Total NaN in row 5159 : 9
 Total NaN in row 5160 : 9
 Total NaN in row 5161 : 3
 Total NaN in row 5162 : 3
 Total NaN in row 5163 : 3
 Total NaN in row 5164 : 9
 Total NaN in row 5165 : 10
 Total NaN in row 5166 : 9
 Total NaN in row 5167 : 9
 Total NaN in row 5168 : 10
 Total NaN in row 5169 : 2
 Total NaN in row 5170 : 9
 Total NaN in row 5171 : 2
 Total NaN in row 5172 : 9
 Total NaN in row 5173 : 1
 Total NaN in row 5174 : 9
 Total NaN in row 5175 : 9
 Total NaN in row 5176 : 0
 Total NaN in row 5177 : 0
 Total NaN in row 5178 : 0
 Total NaN in row 5179 : 10
 Total NaN in row 5180 : 9
 Total NaN in row 5181 : 0
 Total NaN in row 5182 : 9
 Total NaN in row 5183 : 0
 Total NaN in row 5184 : 2
 Total NaN in row 5185 : 9
 Total NaN in row 5186 : 2
 Total NaN in row 5187 : 9
 Total NaN in row 5188 : 10
 Total NaN in row 5189 : 2
 Total NaN in row 5190 : 9
 Total NaN in row 5191 : 4
 Total NaN in row 5192 : 0
 Total NaN in row 5193 : 2
 Total NaN in row 5194 : 0
 Total NaN in row 5195 : 2
 Total NaN in row 5196 : 2
 Total NaN in row 5197 : 9
 Total NaN in row 5198 : 9
 Total NaN in row 5199 : 1
 Total NaN in row 5200 : 0
 Total NaN in row 5201 : 2
 Total NaN in row 5202 : 0
 Total NaN in row 5203 : 3
 Total NaN in row 5204 : 2
 Total NaN in row 5205 : 1
 Total NaN in row 5206 : 0
 Total NaN in row 5207 : 1
 Total NaN in row 5208 : 2
 Total NaN in row 5209 : 1
 Total NaN in row 5210 : 0
 Total NaN in row 5211 : 0
 Total NaN in row 5212 : 1
 Total NaN in row 5213 : 2
 Total NaN in row 5214 : 2
 Total NaN in row 5215 : 0
 Total NaN in row 5216 : 1
 Total NaN in row 5217 : 0
 Total NaN in row 5218 : 3
 Total NaN in row 5219 : 9
 Total NaN in row 5220 : 3
 Total NaN in row 5221 : 2
 Total NaN in row 5222 : 3
 Total NaN in row 5223 : 3
 Total NaN in row 5224 : 21
 Total NaN in row 5225 : 0
 Total NaN in row 5226 : 1
 Total NaN in row 5227 : 1
 Total NaN in row 5228 : 3
 Total NaN in row 5229 : 1
 Total NaN in row 5230 : 3
 Total NaN in row 5231 : 9
 Total NaN in row 5232 : 0
 Total NaN in row 5233 : 0
 Total NaN in row 5234 : 1
 Total NaN in row 5235 : 0
 Total NaN in row 5236 : 9
 Total NaN in row 5237 : 2
 Total NaN in row 5238 : 2
 Total NaN in row 5239 : 0
 Total NaN in row 5240 : 2
 Total NaN in row 5241 : 0
 Total NaN in row 5242 : 2
 Total NaN in row 5243 : 1
 Total NaN in row 5244 : 0
 Total NaN in row 5245 : 0
 Total NaN in row 5246 : 0
 Total NaN in row 5247 : 3
 Total NaN in row 5248 : 1
 Total NaN in row 5249 : 2
 Total NaN in row 5250 : 3
 Total NaN in row 5251 : 9
 Total NaN in row 5252 : 2
 Total NaN in row 5253 : 1
 Total NaN in row 5254 : 0
 Total NaN in row 5255 : 0
 Total NaN in row 5256 : 2
 Total NaN in row 5257 : 7
 Total NaN in row 5258 : 3
 Total NaN in row 5259 : 0
 Total NaN in row 5260 : 10
 Total NaN in row 5261 : 2
 Total NaN in row 5262 : 1
 Total NaN in row 5263 : 0
 Total NaN in row 5264 : 1
 Total NaN in row 5265 : 0
 Total NaN in row 5266 : 21
 Total NaN in row 5267 : 2
 Total NaN in row 5268 : 1
 Total NaN in row 5269 : 1
 Total NaN in row 5270 : 1
 Total NaN in row 5271 : 1
 Total NaN in row 5272 : 3
 Total NaN in row 5273 : 9
 Total NaN in row 5274 : 2
 Total NaN in row 5275 : 0
 Total NaN in row 5276 : 9
 Total NaN in row 5277 : 0
 Total NaN in row 5278 : 9
 Total NaN in row 5279 : 2
 Total NaN in row 5280 : 1
 Total NaN in row 5281 : 0
 Total NaN in row 5282 : 2
 Total NaN in row 5283 : 2
 Total NaN in row 5284 : 0
 Total NaN in row 5285 : 9

 Total NaN in row 5286 : 3
 Total NaN in row 5287 : 2
 Total NaN in row 5288 : 0
 Total NaN in row 5289 : 1
 Total NaN in row 5290 : 3
 Total NaN in row 5291 : 2
 Total NaN in row 5292 : 2
 Total NaN in row 5293 : 2
 Total NaN in row 5294 : 2
 Total NaN in row 5295 : 1
 Total NaN in row 5296 : 3
 Total NaN in row 5297 : 0
 Total NaN in row 5298 : 0
 Total NaN in row 5299 : 0
 Total NaN in row 5300 : 1
 Total NaN in row 5301 : 0
 Total NaN in row 5302 : 0
 Total NaN in row 5303 : 1
 Total NaN in row 5304 : 2
 Total NaN in row 5305 : 0
 Total NaN in row 5306 : 0
 Total NaN in row 5307 : 1
 Total NaN in row 5308 : 9
 Total NaN in row 5309 : 2
 Total NaN in row 5310 : 1
 Total NaN in row 5311 : 0
 Total NaN in row 5312 : 0
 Total NaN in row 5313 : 2
 Total NaN in row 5314 : 9
 Total NaN in row 5315 : 0
 Total NaN in row 5316 : 0
 Total NaN in row 5317 : 2
 Total NaN in row 5318 : 10
 Total NaN in row 5319 : 9
 Total NaN in row 5320 : 2
 Total NaN in row 5321 : 3
 Total NaN in row 5322 : 1
 Total NaN in row 5323 : 0
 Total NaN in row 5324 : 1
 Total NaN in row 5325 : 10
 Total NaN in row 5326 : 0
 Total NaN in row 5327 : 1
 Total NaN in row 5328 : 3
 Total NaN in row 5329 : 21
 Total NaN in row 5330 : 1
 Total NaN in row 5331 : 10
 Total NaN in row 5332 : 21
 Total NaN in row 5333 : 2
 Total NaN in row 5334 : 10
 Total NaN in row 5335 : 0
 Total NaN in row 5336 : 1
 Total NaN in row 5337 : 0
 Total NaN in row 5338 : 0
 Total NaN in row 5339 : 1
 Total NaN in row 5340 : 0
 Total NaN in row 5341 : 0
 Total NaN in row 5342 : 0
 Total NaN in row 5343 : 2
 Total NaN in row 5344 : 1
 Total NaN in row 5345 : 0
 Total NaN in row 5346 : 1
 Total NaN in row 5347 : 1
 Total NaN in row 5348 : 0
 Total NaN in row 5349 : 1
 Total NaN in row 5350 : 3
 Total NaN in row 5351 : 0
 Total NaN in row 5352 : 2
 Total NaN in row 5353 : 2
 Total NaN in row 5354 : 0
 Total NaN in row 5355 : 2
 Total NaN in row 5356 : 2
 Total NaN in row 5357 : 9
 Total NaN in row 5358 : 2
 Total NaN in row 5359 : 2
 Total NaN in row 5360 : 0
 Total NaN in row 5361 : 0
 Total NaN in row 5362 : 2
 Total NaN in row 5363 : 9
 Total NaN in row 5364 : 2
 Total NaN in row 5365 : 0
 Total NaN in row 5366 : 2
 Total NaN in row 5367 : 4
 Total NaN in row 5368 : 9
 Total NaN in row 5369 : 2
 Total NaN in row 5370 : 0
 Total NaN in row 5371 : 0
 Total NaN in row 5372 : 2
 Total NaN in row 5373 : 9
 Total NaN in row 5374 : 0
 Total NaN in row 5375 : 0
 Total NaN in row 5376 : 0
 Total NaN in row 5377 : 1
 Total NaN in row 5378 : 0
 Total NaN in row 5379 : 0
 Total NaN in row 5380 : 0
 Total NaN in row 5381 : 10
 Total NaN in row 5382 : 2
 Total NaN in row 5383 : 2
 Total NaN in row 5384 : 21
 Total NaN in row 5385 : 2
 Total NaN in row 5386 : 2
 Total NaN in row 5387 : 9
 Total NaN in row 5388 : 1
 Total NaN in row 5389 : 1
 Total NaN in row 5390 : 0
 Total NaN in row 5391 : 3
 Total NaN in row 5392 : 3
 Total NaN in row 5393 : 2
 Total NaN in row 5394 : 2
 Total NaN in row 5395 : 2
 Total NaN in row 5396 : 2
 Total NaN in row 5397 : 2
 Total NaN in row 5398 : 0
 Total NaN in row 5399 : 1
 Total NaN in row 5400 : 3
 Total NaN in row 5401 : 9
 Total NaN in row 5402 : 9
 Total NaN in row 5403 : 10
 Total NaN in row 5404 : 1
 Total NaN in row 5405 : 1
 Total NaN in row 5406 : 21
 Total NaN in row 5407 : 2
 Total NaN in row 5408 : 0
 Total NaN in row 5409 : 3
 Total NaN in row 5410 : 2
 Total NaN in row 5411 : 1
 Total NaN in row 5412 : 1
 Total NaN in row 5413 : 0
 Total NaN in row 5414 : 1
 Total NaN in row 5415 : 0
 Total NaN in row 5416 : 2
 Total NaN in row 5417 : 0
 Total NaN in row 5418 : 9
 Total NaN in row 5419 : 0
 Total NaN in row 5420 : 0
 Total NaN in row 5421 : 0
 Total NaN in row 5422 : 1
 Total NaN in row 5423 : 0
 Total NaN in row 5424 : 1
 Total NaN in row 5425 : 1
 Total NaN in row 5426 : 0
 Total NaN in row 5427 : 0
 Total NaN in row 5428 : 0
 Total NaN in row 5429 : 2
 Total NaN in row 5430 : 9
 Total NaN in row 5431 : 9
 Total NaN in row 5432 : 9
 Total NaN in row 5433 : 1
 Total NaN in row 5434 : 2
 Total NaN in row 5435 : 0
 Total NaN in row 5436 : 0
 Total NaN in row 5437 : 0
 Total NaN in row 5438 : 0
 Total NaN in row 5439 : 0
 Total NaN in row 5440 : 1
 Total NaN in row 5441 : 9
 Total NaN in row 5442 : 9
 Total NaN in row 5443 : 2
 Total NaN in row 5444 : 2
 Total NaN in row 5445 : 9
 Total NaN in row 5446 : 2
 Total NaN in row 5447 : 1
 Total NaN in row 5448 : 0
 Total NaN in row 5449 : 0
 Total NaN in row 5450 : 1
 Total NaN in row 5451 : 1
 Total NaN in row 5452 : 2
 Total NaN in row 5453 : 0
 Total NaN in row 5454 : 2
 Total NaN in row 5455 : 0
 Total NaN in row 5456 : 0
 Total NaN in row 5457 : 0
 Total NaN in row 5458 : 2
 Total NaN in row 5459 : 0
 Total NaN in row 5460 : 0
 Total NaN in row 5461 : 3
 Total NaN in row 5462 : 2
 Total NaN in row 5463 : 0
 Total NaN in row 5464 : 0
 Total NaN in row 5465 : 2
 Total NaN in row 5466 : 9
 Total NaN in row 5467 : 2
 Total NaN in row 5468 : 1
 Total NaN in row 5469 : 9
 Total NaN in row 5470 : 2
 Total NaN in row 5471 : 2
 Total NaN in row 5472 : 2
 Total NaN in row 5473 : 0
 Total NaN in row 5474 : 0
 Total NaN in row 5475 : 1
 Total NaN in row 5476 : 2
 Total NaN in row 5477 : 2
 Total NaN in row 5478 : 2
 Total NaN in row 5479 : 3
 Total NaN in row 5480 : 1
 Total NaN in row 5481 : 3
 Total NaN in row 5482 : 1
 Total NaN in row 5483 : 2
 Total NaN in row 5484 : 2
 Total NaN in row 5485 : 0
 Total NaN in row 5486 : 0
 Total NaN in row 5487 : 9
 Total NaN in row 5488 : 1
 Total NaN in row 5489 : 2
 Total NaN in row 5490 : 0
 Total NaN in row 5491 : 2
 Total NaN in row 5492 : 0
 Total NaN in row 5493 : 0
 Total NaN in row 5494 : 0
 Total NaN in row 5495 : 2
 Total NaN in row 5496 : 1
 Total NaN in row 5497 : 2
 Total NaN in row 5498 : 1
 Total NaN in row 5499 : 2
 Total NaN in row 5500 : 2
 Total NaN in row 5501 : 0
 Total NaN in row 5502 : 0
 Total NaN in row 5503 : 2
 Total NaN in row 5504 : 0
 Total NaN in row 5505 : 0
 Total NaN in row 5506 : 9
 Total NaN in row 5507 : 3
 Total NaN in row 5508 : 0
 Total NaN in row 5509 : 9
 Total NaN in row 5510 : 2
 Total NaN in row 5511 : 2
 Total NaN in row 5512 : 2
 Total NaN in row 5513 : 2
 Total NaN in row 5514 : 0
 Total NaN in row 5515 : 2
 Total NaN in row 5516 : 2
 Total NaN in row 5517 : 2
 Total NaN in row 5518 : 2
 Total NaN in row 5519 : 2
 Total NaN in row 5520 : 9
 Total NaN in row 5521 : 2
 Total NaN in row 5522 : 0
 Total NaN in row 5523 : 2
 Total NaN in row 5524 : 3
 Total NaN in row 5525 : 0
 Total NaN in row 5526 : 0
 Total NaN in row 5527 : 9
 Total NaN in row 5528 : 0
 Total NaN in row 5529 : 2
 Total NaN in row 5530 : 0
 Total NaN in row 5531 : 0
 Total NaN in row 5532 : 2
 Total NaN in row 5533 : 0
 Total NaN in row 5534 : 10
 Total NaN in row 5535 : 0
 Total NaN in row 5536 : 0
 Total NaN in row 5537 : 0
 Total NaN in row 5538 : 1
 Total NaN in row 5539 : 0
 Total NaN in row 5540 : 0
 Total NaN in row 5541 : 1
 Total NaN in row 5542 : 2
 Total NaN in row 5543 : 2
 Total NaN in row 5544 : 3
 Total NaN in row 5545 : 2
 Total NaN in row 5546 : 9
 Total NaN in row 5547 : 0
 Total NaN in row 5548 : 0
 Total NaN in row 5549 : 9
 Total NaN in row 5550 : 0
 Total NaN in row 5551 : 2
 Total NaN in row 5552 : 9
 Total NaN in row 5553 : 10
 Total NaN in row 5554 : 0
 Total NaN in row 5555 : 3
 Total NaN in row 5556 : 9
 Total NaN in row 5557 : 0
 Total NaN in row 5558 : 0
 Total NaN in row 5559 : 2
 Total NaN in row 5560 : 0
 Total NaN in row 5561 : 2
 Total NaN in row 5562 : 1
 Total NaN in row 5563 : 1
 Total NaN in row 5564 : 2
 Total NaN in row 5565 : 9
 Total NaN in row 5566 : 1
 Total NaN in row 5567 : 0
 Total NaN in row 5568 : 2
 Total NaN in row 5569 : 9
 Total NaN in row 5570 : 1
 Total NaN in row 5571 : 2
 Total NaN in row 5572 : 2
 Total NaN in row 5573 : 0
 Total NaN in row 5574 : 0
 Total NaN in row 5575 : 0
 Total NaN in row 5576 : 9
 Total NaN in row 5577 : 1
 Total NaN in row 5578 : 1
 Total NaN in row 5579 : 0
 Total NaN in row 5580 : 2
 Total NaN in row 5581 : 1
 Total NaN in row 5582 : 0
 Total NaN in row 5583 : 0
 Total NaN in row 5584 : 1
 Total NaN in row 5585 : 2
 Total NaN in row 5586 : 0
 Total NaN in row 5587 : 2
 Total NaN in row 5588 : 2
 Total NaN in row 5589 : 0
 Total NaN in row 5590 : 0
 Total NaN in row 5591 : 2
 Total NaN in row 5592 : 2
 Total NaN in row 5593 : 0
 Total NaN in row 5594 : 1
 Total NaN in row 5595 : 1
 Total NaN in row 5596 : 0
 Total NaN in row 5597 : 3
 Total NaN in row 5598 : 0
 Total NaN in row 5599 : 0
 Total NaN in row 5600 : 9
 Total NaN in row 5601 : 1
 Total NaN in row 5602 : 9
 Total NaN in row 5603 : 9
 Total NaN in row 5604 : 3
 Total NaN in row 5605 : 1
 Total NaN in row 5606 : 1
 Total NaN in row 5607 : 1
 Total NaN in row 5608 : 2
 Total NaN in row 5609 : 1
 Total NaN in row 5610 : 1
 Total NaN in row 5611 : 0
 Total NaN in row 5612 : 10
 Total NaN in row 5613 : 0
 Total NaN in row 5614 : 0
 Total NaN in row 5615 : 1
 Total NaN in row 5616 : 1
 Total NaN in row 5617 : 2
 Total NaN in row 5618 : 2
 Total NaN in row 5619 : 1
 Total NaN in row 5620 : 0
 Total NaN in row 5621 : 1
 Total NaN in row 5622 : 1
 Total NaN in row 5623 : 0
 Total NaN in row 5624 : 2
 Total NaN in row 5625 : 9
 Total NaN in row 5626 : 21
 Total NaN in row 5627 : 2
 Total NaN in row 5628 : 1
 Total NaN in row 5629 : 0
 Total NaN in row 5630 : 3
 Total NaN in row 5631 : 0
 Total NaN in row 5632 : 2
 Total NaN in row 5633 : 1
 Total NaN in row 5634 : 2
 Total NaN in row 5635 : 1
 Total NaN in row 5636 : 0
 Total NaN in row 5637 : 0
 Total NaN in row 5638 : 2
 Total NaN in row 5639 : 0
 Total NaN in row 5640 : 0
 Total NaN in row 5641 : 1
 Total NaN in row 5642 : 0
 Total NaN in row 5643 : 3
 Total NaN in row 5644 : 1
 Total NaN in row 5645 : 0
 Total NaN in row 5646 : 2
 Total NaN in row 5647 : 0
 Total NaN in row 5648 : 0
 Total NaN in row 5649 : 10
 Total NaN in row 5650 : 1
 Total NaN in row 5651 : 0
 Total NaN in row 5652 : 3
 Total NaN in row 5653 : 4
 Total NaN in row 5654 : 2
 Total NaN in row 5655 : 2
 Total NaN in row 5656 : 1
 Total NaN in row 5657 : 10
 Total NaN in row 5658 : 0
 Total NaN in row 5659 : 1
 Total NaN in row 5660 : 10
 Total NaN in row 5661 : 9
 Total NaN in row 5662 : 1
 Total NaN in row 5663 : 0
 Total NaN in row 5664 : 9
 Total NaN in row 5665 : 0
 Total NaN in row 5666 : 0
 Total NaN in row 5667 : 9
 Total NaN in row 5668 : 1
 Total NaN in row 5669 : 1
 Total NaN in row 5670 : 1
 Total NaN in row 5671 : 2
 Total NaN in row 5672 : 10
 Total NaN in row 5673 : 9
 Total NaN in row 5674 : 1
 Total NaN in row 5675 : 2
 Total NaN in row 5676 : 2
 Total NaN in row 5677 : 9
 Total NaN in row 5678 : 2
 Total NaN in row 5679 : 1
 Total NaN in row 5680 : 9
 Total NaN in row 5681 : 0
 Total NaN in row 5682 : 1
 Total NaN in row 5683 : 0
 Total NaN in row 5684 : 0
 Total NaN in row 5685 : 2
 Total NaN in row 5686 : 0
 Total NaN in row 5687 : 0
 Total NaN in row 5688 : 0
 Total NaN in row 5689 : 2
 Total NaN in row 5690 : 2
 Total NaN in row 5691 : 0
 Total NaN in row 5692 : 9
 Total NaN in row 5693 : 0
 Total NaN in row 5694 : 0
 Total NaN in row 5695 : 1
 Total NaN in row 5696 : 1
 Total NaN in row 5697 : 0
 Total NaN in row 5698 : 3
 Total NaN in row 5699 : 2
 Total NaN in row 5700 : 0
 Total NaN in row 5701 : 9
 Total NaN in row 5702 : 2
 Total NaN in row 5703 : 0
 Total NaN in row 5704 : 9
 Total NaN in row 5705 : 0
 Total NaN in row 5706 : 1
 Total NaN in row 5707 : 9
 Total NaN in row 5708 : 0
 Total NaN in row 5709 : 10
 Total NaN in row 5710 : 0
 Total NaN in row 5711 : 0
 Total NaN in row 5712 : 9

 Total NaN in row 5713 : 0
 Total NaN in row 5714 : 2
 Total NaN in row 5715 : 0
 Total NaN in row 5716 : 1
 Total NaN in row 5717 : 0
 Total NaN in row 5718 : 0
 Total NaN in row 5719 : 0
 Total NaN in row 5720 : 2
 Total NaN in row 5721 : 0
 Total NaN in row 5722 : 2
 Total NaN in row 5723 : 2
 Total NaN in row 5724 : 2
 Total NaN in row 5725 : 2
 Total NaN in row 5726 : 0
 Total NaN in row 5727 : 2
 Total NaN in row 5728 : 0
 Total NaN in row 5729 : 1
 Total NaN in row 5730 : 0
 Total NaN in row 5731 : 1
 Total NaN in row 5732 : 9
 Total NaN in row 5733 : 1
 Total NaN in row 5734 : 2
 Total NaN in row 5735 : 2
 Total NaN in row 5736 : 2
 Total NaN in row 5737 : 0
 Total NaN in row 5738 : 0
 Total NaN in row 5739 : 2
 Total NaN in row 5740 : 9
 Total NaN in row 5741 : 2
 Total NaN in row 5742 : 21
 Total NaN in row 5743 : 9
 Total NaN in row 5744 : 9
 Total NaN in row 5745 : 0
 Total NaN in row 5746 : 0
 Total NaN in row 5747 : 9
 Total NaN in row 5748 : 10
 Total NaN in row 5749 : 0
 Total NaN in row 5750 : 2
 Total NaN in row 5751 : 9
 Total NaN in row 5752 : 9
 Total NaN in row 5753 : 2
 Total NaN in row 5754 : 2
 Total NaN in row 5755 : 9
 Total NaN in row 5756 : 0
 Total NaN in row 5757 : 1
 Total NaN in row 5758 : 0
 Total NaN in row 5759 : 2
 Total NaN in row 5760 : 0
 Total NaN in row 5761 : 0
 Total NaN in row 5762 : 2
 Total NaN in row 5763 : 0
 Total NaN in row 5764 : 9
 Total NaN in row 5765 : 0
 Total NaN in row 5766 : 0
 Total NaN in row 5767 : 0
 Total NaN in row 5768 : 2
 Total NaN in row 5769 : 9
 Total NaN in row 5770 : 1
 Total NaN in row 5771 : 1
 Total NaN in row 5772 : 0
 Total NaN in row 5773 : 10
 Total NaN in row 5774 : 0
 Total NaN in row 5775 : 0
 Total NaN in row 5776 : 9
 Total NaN in row 5777 : 2
 Total NaN in row 5778 : 0
 Total NaN in row 5779 : 2
 Total NaN in row 5780 : 2
 Total NaN in row 5781 : 10
 Total NaN in row 5782 : 2
 Total NaN in row 5783 : 2
 Total NaN in row 5784 : 2
 Total NaN in row 5785 : 9
 Total NaN in row 5786 : 0
 Total NaN in row 5787 : 0
 Total NaN in row 5788 : 1
 Total NaN in row 5789 : 0
 Total NaN in row 5790 : 0
 Total NaN in row 5791 : 1
 Total NaN in row 5792 : 0
 Total NaN in row 5793 : 0
 Total NaN in row 5794 : 2
 Total NaN in row 5795 : 0
 Total NaN in row 5796 : 2
 Total NaN in row 5797 : 1
 Total NaN in row 5798 : 0
 Total NaN in row 5799 : 0
 Total NaN in row 5800 : 2
 Total NaN in row 5801 : 9
 Total NaN in row 5802 : 1
 Total NaN in row 5803 : 2
 Total NaN in row 5804 : 0
 Total NaN in row 5805 : 9
 Total NaN in row 5806 : 9
 Total NaN in row 5807 : 2
 Total NaN in row 5808 : 0
 Total NaN in row 5809 : 0
 Total NaN in row 5810 : 0
 Total NaN in row 5811 : 2
 Total NaN in row 5812 : 9
 Total NaN in row 5813 : 9
 Total NaN in row 5814 : 0
 Total NaN in row 5815 : 3
 Total NaN in row 5816 : 0
 Total NaN in row 5817 : 0
 Total NaN in row 5818 : 1
 Total NaN in row 5819 : 0
 Total NaN in row 5820 : 0
 Total NaN in row 5821 : 0
 Total NaN in row 5822 : 1
 Total NaN in row 5823 : 2
 Total NaN in row 5824 : 0
 Total NaN in row 5825 : 0
 Total NaN in row 5826 : 2
 Total NaN in row 5827 : 0
 Total NaN in row 5828 : 0
 Total NaN in row 5829 : 10
 Total NaN in row 5830 : 0
 Total NaN in row 5831 : 9
 Total NaN in row 5832 : 1
 Total NaN in row 5833 : 0
 Total NaN in row 5834 : 2
 Total NaN in row 5835 : 9
 Total NaN in row 5836 : 0
 Total NaN in row 5837 : 0
 Total NaN in row 5838 : 10
 Total NaN in row 5839 : 9
 Total NaN in row 5840 : 9
 Total NaN in row 5841 : 0
 Total NaN in row 5842 : 2
 Total NaN in row 5843 : 10
 Total NaN in row 5844 : 2
 Total NaN in row 5845 : 2
 Total NaN in row 5846 : 0
 Total NaN in row 5847 : 0
 Total NaN in row 5848 : 9
 Total NaN in row 5849 : 0
 Total NaN in row 5850 : 0
 Total NaN in row 5851 : 0
 Total NaN in row 5852 : 0
 Total NaN in row 5853 : 0
 Total NaN in row 5854 : 1
 Total NaN in row 5855 : 2
 Total NaN in row 5856 : 2
 Total NaN in row 5857 : 0
 Total NaN in row 5858 : 2
 Total NaN in row 5859 : 0
 Total NaN in row 5860 : 2
 Total NaN in row 5861 : 0
 Total NaN in row 5862 : 9
 Total NaN in row 5863 : 9
 Total NaN in row 5864 : 0
 Total NaN in row 5865 : 0
 Total NaN in row 5866 : 2
 Total NaN in row 5867 : 0
 Total NaN in row 5868 : 9
 Total NaN in row 5869 : 9
 Total NaN in row 5870 : 9
 Total NaN in row 5871 : 9
 Total NaN in row 5872 : 2
 Total NaN in row 5873 : 10
 Total NaN in row 5874 : 0
 Total NaN in row 5875 : 1
 Total NaN in row 5876 : 0
 Total NaN in row 5877 : 0
 Total NaN in row 5878 : 3
 Total NaN in row 5879 : 0
 Total NaN in row 5880 : 9
 Total NaN in row 5881 : 0
 Total NaN in row 5882 : 3
 Total NaN in row 5883 : 2
 Total NaN in row 5884 : 2
 Total NaN in row 5885 : 2
 Total NaN in row 5886 : 10
 Total NaN in row 5887 : 9
 Total NaN in row 5888 : 9
 Total NaN in row 5889 : 2
 Total NaN in row 5890 : 2
 Total NaN in row 5891 : 2
 Total NaN in row 5892 : 1
 Total NaN in row 5893 : 10
 Total NaN in row 5894 : 2
 Total NaN in row 5895 : 9
 Total NaN in row 5896 : 9
 Total NaN in row 5897 : 2
 Total NaN in row 5898 : 5
 Total NaN in row 5899 : 1
 Total NaN in row 5900 : 9
 Total NaN in row 5901 : 1
 Total NaN in row 5902 : 2
 Total NaN in row 5903 : 1
 Total NaN in row 5904 : 2
 Total NaN in row 5905 : 9
 Total NaN in row 5906 : 0
 Total NaN in row 5907 : 1
 Total NaN in row 5908 : 1
 Total NaN in row 5909 : 10
 Total NaN in row 5910 : 10
 Total NaN in row 5911 : 4
 Total NaN in row 5912 : 1
 Total NaN in row 5913 : 1
 Total NaN in row 5914 : 9
 Total NaN in row 5915 : 9
 Total NaN in row 5916 : 0
 Total NaN in row 5917 : 1
 Total NaN in row 5918 : 1
 Total NaN in row 5919 : 1
 Total NaN in row 5920 : 2
 Total NaN in row 5921 : 2
 Total NaN in row 5922 : 1
 Total NaN in row 5923 : 2
 Total NaN in row 5924 : 9
 Total NaN in row 5925 : 9
 Total NaN in row 5926 : 2
 Total NaN in row 5927 : 1
 Total NaN in row 5928 : 1
 Total NaN in row 5929 : 9
 Total NaN in row 5930 : 0
 Total NaN in row 5931 : 0
 Total NaN in row 5932 : 1
 Total NaN in row 5933 : 3
 Total NaN in row 5934 : 1
 Total NaN in row 5935 : 0
 Total NaN in row 5936 : 9
 Total NaN in row 5937 : 2
 Total NaN in row 5938 : 2
 Total NaN in row 5939 : 9
 Total NaN in row 5940 : 0
 Total NaN in row 5941 : 3
 Total NaN in row 5942 : 1
 Total NaN in row 5943 : 10
 Total NaN in row 5944 : 0
 Total NaN in row 5945 : 9
 Total NaN in row 5946 : 1
 Total NaN in row 5947 : 0
 Total NaN in row 5948 : 9
 Total NaN in row 5949 : 0
 Total NaN in row 5950 : 2
 Total NaN in row 5951 : 0
 Total NaN in row 5952 : 1
 Total NaN in row 5953 : 21
 Total NaN in row 5954 : 2
 Total NaN in row 5955 : 0
 Total NaN in row 5956 : 0
 Total NaN in row 5957 : 2
 Total NaN in row 5958 : 1
 Total NaN in row 5959 : 2
 Total NaN in row 5960 : 0
 Total NaN in row 5961 : 1
 Total NaN in row 5962 : 3
 Total NaN in row 5963 : 3
 Total NaN in row 5964 : 9
 Total NaN in row 5965 : 10
 Total NaN in row 5966 : 1
 Total NaN in row 5967 : 0
 Total NaN in row 5968 : 9
 Total NaN in row 5969 : 9
 Total NaN in row 5970 : 9
 Total NaN in row 5971 : 1
 Total NaN in row 5972 : 0
 Total NaN in row 5973 : 1
 Total NaN in row 5974 : 2
 Total NaN in row 5975 : 0
 Total NaN in row 5976 : 0
 Total NaN in row 5977 : 9
 Total NaN in row 5978 : 0
 Total NaN in row 5979 : 0
 Total NaN in row 5980 : 1
 Total NaN in row 5981 : 1
 Total NaN in row 5982 : 9
 Total NaN in row 5983 : 2
 Total NaN in row 5984 : 0
 Total NaN in row 5985 : 0
 Total NaN in row 5986 : 1
 Total NaN in row 5987 : 1
 Total NaN in row 5988 : 2
 Total NaN in row 5989 : 10
 Total NaN in row 5990 : 9
 Total NaN in row 5991 : 9
 Total NaN in row 5992 : 1
 Total NaN in row 5993 : 1
 Total NaN in row 5994 : 9
 Total NaN in row 5995 : 0
 Total NaN in row 5996 : 0
 Total NaN in row 5997 : 0
 Total NaN in row 5998 : 1
 Total NaN in row 5999 : 2
 Total NaN in row 6000 : 0
 Total NaN in row 6001 : 0
 Total NaN in row 6002 : 2
 Total NaN in row 6003 : 2
 Total NaN in row 6004 : 1
 Total NaN in row 6005 : 1
 Total NaN in row 6006 : 3
 Total NaN in row 6007 : 10
 Total NaN in row 6008 : 0
 Total NaN in row 6009 : 0
 Total NaN in row 6010 : 0
 Total NaN in row 6011 : 1
 Total NaN in row 6012 : 1
 Total NaN in row 6013 : 3
 Total NaN in row 6014 : 9
 Total NaN in row 6015 : 7
 Total NaN in row 6016 : 0
 Total NaN in row 6017 : 10
 Total NaN in row 6018 : 3
 Total NaN in row 6019 : 3
 Total NaN in row 6020 : 2
 Total NaN in row 6021 : 3
 Total NaN in row 6022 : 0
 Total NaN in row 6023 : 1
 Total NaN in row 6024 : 3
 Total NaN in row 6025 : 2
 Total NaN in row 6026 : 0
 Total NaN in row 6027 : 9
 Total NaN in row 6028 : 2
 Total NaN in row 6029 : 2
 Total NaN in row 6030 : 10
 Total NaN in row 6031 : 0
 Total NaN in row 6032 : 2
 Total NaN in row 6033 : 10
 Total NaN in row 6034 : 10
 Total NaN in row 6035 : 0
 Total NaN in row 6036 : 10
 Total NaN in row 6037 : 9
 Total NaN in row 6038 : 3
 Total NaN in row 6039 : 0
 Total NaN in row 6040 : 9
 Total NaN in row 6041 : 8
 Total NaN in row 6042 : 0
 Total NaN in row 6043 : 3
 Total NaN in row 6044 : 2
 Total NaN in row 6045 : 9
 Total NaN in row 6046 : 2
 Total NaN in row 6047 : 1
 Total NaN in row 6048 : 2
 Total NaN in row 6049 : 2
 Total NaN in row 6050 : 1
 Total NaN in row 6051 : 1
 Total NaN in row 6052 : 0
 Total NaN in row 6053 : 2
 Total NaN in row 6054 : 3
 Total NaN in row 6055 : 0
 Total NaN in row 6056 : 9
 Total NaN in row 6057 : 2
 Total NaN in row 6058 : 10
 Total NaN in row 6059 : 0
 Total NaN in row 6060 : 0
 Total NaN in row 6061 : 9
 Total NaN in row 6062 : 0
 Total NaN in row 6063 : 0
 Total NaN in row 6064 : 9
 Total NaN in row 6065 : 2
 Total NaN in row 6066 : 3
 Total NaN in row 6067 : 0
 Total NaN in row 6068 : 0
 Total NaN in row 6069 : 1
 Total NaN in row 6070 : 1
 Total NaN in row 6071 : 2
 Total NaN in row 6072 : 1
 Total NaN in row 6073 : 4
 Total NaN in row 6074 : 10
 Total NaN in row 6075 : 1
 Total NaN in row 6076 : 9
 Total NaN in row 6077 : 0
 Total NaN in row 6078 : 0
 Total NaN in row 6079 : 0
 Total NaN in row 6080 : 2
 Total NaN in row 6081 : 0
 Total NaN in row 6082 : 0
 Total NaN in row 6083 : 0
 Total NaN in row 6084 : 2
 Total NaN in row 6085 : 0
 Total NaN in row 6086 : 3
 Total NaN in row 6087 : 9
 Total NaN in row 6088 : 2
 Total NaN in row 6089 : 2
 Total NaN in row 6090 : 1
 Total NaN in row 6091 : 2
 Total NaN in row 6092 : 9
 Total NaN in row 6093 : 2
 Total NaN in row 6094 : 1
 Total NaN in row 6095 : 2
 Total NaN in row 6096 : 9
 Total NaN in row 6097 : 9
 Total NaN in row 6098 : 10
 Total NaN in row 6099 : 0

 Total NaN in row 6100 : 0
 Total NaN in row 6101 : 1
 Total NaN in row 6102 : 1
 Total NaN in row 6103 : 7
 Total NaN in row 6104 : 0
 Total NaN in row 6105 : 3
 Total NaN in row 6106 : 0
 Total NaN in row 6107 : 1
 Total NaN in row 6108 : 0
 Total NaN in row 6109 : 9
 Total NaN in row 6110 : 2
 Total NaN in row 6111 : 2
 Total NaN in row 6112 : 0
 Total NaN in row 6113 : 0
 Total NaN in row 6114 : 2
 Total NaN in row 6115 : 9
 Total NaN in row 6116 : 8
 Total NaN in row 6117 : 1
 Total NaN in row 6118 : 1
 Total NaN in row 6119 : 2
 Total NaN in row 6120 : 9
 Total NaN in row 6121 : 0
 Total NaN in row 6122 : 2
 Total NaN in row 6123 : 0
 Total NaN in row 6124 : 9
 Total NaN in row 6125 : 9
 Total NaN in row 6126 : 21
 Total NaN in row 6127 : 9
 Total NaN in row 6128 : 0
 Total NaN in row 6129 : 10
 Total NaN in row 6130 : 1
 Total NaN in row 6131 : 9
 Total NaN in row 6132 : 9
 Total NaN in row 6133 : 2
 Total NaN in row 6134 : 21
 Total NaN in row 6135 : 2
 Total NaN in row 6136 : 0
 Total NaN in row 6137 : 9
 Total NaN in row 6138 : 9
 Total NaN in row 6139 : 1
 Total NaN in row 6140 : 2
 Total NaN in row 6141 : 21
 Total NaN in row 6142 : 2
 Total NaN in row 6143 : 0
 Total NaN in row 6144 : 21
 Total NaN in row 6145 : 0
 Total NaN in row 6146 : 1
 Total NaN in row 6147 : 9
 Total NaN in row 6148 : 0
 Total NaN in row 6149 : 2
 Total NaN in row 6150 : 3
 Total NaN in row 6151 : 10
 Total NaN in row 6152 : 0
 Total NaN in row 6153 : 2
 Total NaN in row 6154 : 1
 Total NaN in row 6155 : 1
 Total NaN in row 6156 : 0
 Total NaN in row 6157 : 9
 Total NaN in row 6158 : 1
 Total NaN in row 6159 : 9
 Total NaN in row 6160 : 1
 Total NaN in row 6161 : 0
 Total NaN in row 6162 : 1
 Total NaN in row 6163 : 9
 Total NaN in row 6164 : 0
 Total NaN in row 6165 : 10
 Total NaN in row 6166 : 2
 Total NaN in row 6167 : 1
 Total NaN in row 6168 : 10
 Total NaN in row 6169 : 9
 Total NaN in row 6170 : 1
 Total NaN in row 6171 : 9
 Total NaN in row 6172 : 10
 Total NaN in row 6173 : 2
 Total NaN in row 6174 : 3
 Total NaN in row 6175 : 1
 Total NaN in row 6176 : 9
 Total NaN in row 6177 : 2
 Total NaN in row 6178 : 1
 Total NaN in row 6179 : 3
 Total NaN in row 6180 : 1
 Total NaN in row 6181 : 1
 Total NaN in row 6182 : 9
 Total NaN in row 6183 : 2
 Total NaN in row 6184 : 0
 Total NaN in row 6185 : 0
 Total NaN in row 6186 : 1
 Total NaN in row 6187 : 0
 Total NaN in row 6188 : 0
 Total NaN in row 6189 : 0
 Total NaN in row 6190 : 2
 Total NaN in row 6191 : 2
 Total NaN in row 6192 : 1
 Total NaN in row 6193 : 0
 Total NaN in row 6194 : 2
 Total NaN in row 6195 : 10
 Total NaN in row 6196 : 2
 Total NaN in row 6197 : 0
 Total NaN in row 6198 : 9
 Total NaN in row 6199 : 2
 Total NaN in row 6200 : 2
 Total NaN in row 6201 : 0
 Total NaN in row 6202 : 0
 Total NaN in row 6203 : 9
 Total NaN in row 6204 : 1
 Total NaN in row 6205 : 1
 Total NaN in row 6206 : 2
 Total NaN in row 6207 : 2
 Total NaN in row 6208 : 0
 Total NaN in row 6209 : 0
 Total NaN in row 6210 : 9
 Total NaN in row 6211 : 2
 Total NaN in row 6212 : 0
 Total NaN in row 6213 : 0
 Total NaN in row 6214 : 1
 Total NaN in row 6215 : 1
 Total NaN in row 6216 : 0
 Total NaN in row 6217 : 2
 Total NaN in row 6218 : 9
 Total NaN in row 6219 : 1
 Total NaN in row 6220 : 0
 Total NaN in row 6221 : 2
 Total NaN in row 6222 : 0
 Total NaN in row 6223 : 9
 Total NaN in row 6224 : 9
 Total NaN in row 6225 : 0
 Total NaN in row 6226 : 2
 Total NaN in row 6227 : 2
 Total NaN in row 6228 : 2
 Total NaN in row 6229 : 0
 Total NaN in row 6230 : 2
 Total NaN in row 6231 : 2
 Total NaN in row 6232 : 10
 Total NaN in row 6233 : 0
 Total NaN in row 6234 : 2
 Total NaN in row 6235 : 0
 Total NaN in row 6236 : 2
 Total NaN in row 6237 : 1
 Total NaN in row 6238 : 2
 Total NaN in row 6239 : 1
 Total NaN in row 6240 : 1
 Total NaN in row 6241 : 1
 Total NaN in row 6242 : 2
 Total NaN in row 6243 : 9
 Total NaN in row 6244 : 1
 Total NaN in row 6245 : 1
 Total NaN in row 6246 : 0
 Total NaN in row 6247 : 2
 Total NaN in row 6248 : 3
 Total NaN in row 6249 : 2
 Total NaN in row 6250 : 1
 Total NaN in row 6251 : 0
 Total NaN in row 6252 : 21
 Total NaN in row 6253 : 0
 Total NaN in row 6254 : 0
 Total NaN in row 6255 : 0
 Total NaN in row 6256 : 2
 Total NaN in row 6257 : 1
 Total NaN in row 6258 : 9
 Total NaN in row 6259 : 9
 Total NaN in row 6260 : 3
 Total NaN in row 6261 : 9
 Total NaN in row 6262 : 10
 Total NaN in row 6263 : 1
 Total NaN in row 6264 : 2
 Total NaN in row 6265 : 2
 Total NaN in row 6266 : 9
 Total NaN in row 6267 : 0
 Total NaN in row 6268 : 1
 Total NaN in row 6269 : 1
 Total NaN in row 6270 : 0
 Total NaN in row 6271 : 3
 Total NaN in row 6272 : 2
 Total NaN in row 6273 : 0
 Total NaN in row 6274 : 3
 Total NaN in row 6275 : 1
 Total NaN in row 6276 : 0
 Total NaN in row 6277 : 3
 Total NaN in row 6278 : 1
 Total NaN in row 6279 : 1
 Total NaN in row 6280 : 2
 Total NaN in row 6281 : 2
 Total NaN in row 6282 : 1
 Total NaN in row 6283 : 2
 Total NaN in row 6284 : 3
 Total NaN in row 6285 : 1
 Total NaN in row 6286 : 2
 Total NaN in row 6287 : 1
 Total NaN in row 6288 : 0
 Total NaN in row 6289 : 1
 Total NaN in row 6290 : 9
 Total NaN in row 6291 : 3
 Total NaN in row 6292 : 1
 Total NaN in row 6293 : 1
 Total NaN in row 6294 : 2
 Total NaN in row 6295 : 3
 Total NaN in row 6296 : 0
 Total NaN in row 6297 : 0
 Total NaN in row 6298 : 2
 Total NaN in row 6299 : 2
 Total NaN in row 6300 : 10
 Total NaN in row 6301 : 0
 Total NaN in row 6302 : 3
 Total NaN in row 6303 : 9
 Total NaN in row 6304 : 3
 Total NaN in row 6305 : 0
 Total NaN in row 6306 : 0
 Total NaN in row 6307 : 0
 Total NaN in row 6308 : 1
 Total NaN in row 6309 : 1
 Total NaN in row 6310 : 1
 Total NaN in row 6311 : 3
 Total NaN in row 6312 : 3
 Total NaN in row 6313 : 3
 Total NaN in row 6314 : 2
 Total NaN in row 6315 : 3
 Total NaN in row 6316 : 3
 Total NaN in row 6317 : 2
 Total NaN in row 6318 : 1
 Total NaN in row 6319 : 2
 Total NaN in row 6320 : 0
 Total NaN in row 6321 : 0
 Total NaN in row 6322 : 3
 Total NaN in row 6323 : 3
 Total NaN in row 6324 : 10
 Total NaN in row 6325 : 0
 Total NaN in row 6326 : 2
 Total NaN in row 6327 : 21
 Total NaN in row 6328 : 3
 Total NaN in row 6329 : 10
 Total NaN in row 6330 : 9
 Total NaN in row 6331 : 0
 Total NaN in row 6332 : 0
 Total NaN in row 6333 : 3
 Total NaN in row 6334 : 3
 Total NaN in row 6335 : 10
 Total NaN in row 6336 : 2
 Total NaN in row 6337 : 2
 Total NaN in row 6338 : 3
 Total NaN in row 6339 : 0
 Total NaN in row 6340 : 2
 Total NaN in row 6341 : 0
 Total NaN in row 6342 : 0
 Total NaN in row 6343 : 1
 Total NaN in row 6344 : 1
 Total NaN in row 6345 : 3
 Total NaN in row 6346 : 10
 Total NaN in row 6347 : 9
 Total NaN in row 6348 : 0
 Total NaN in row 6349 : 10
 Total NaN in row 6350 : 0
 Total NaN in row 6351 : 2
 Total NaN in row 6352 : 0
 Total NaN in row 6353 : 2
 Total NaN in row 6354 : 3
 Total NaN in row 6355 : 1
 Total NaN in row 6356 : 9
 Total NaN in row 6357 : 3
 Total NaN in row 6358 : 2
 Total NaN in row 6359 : 0
 Total NaN in row 6360 : 9
 Total NaN in row 6361 : 2
 Total NaN in row 6362 : 1
 Total NaN in row 6363 : 3
 Total NaN in row 6364 : 9
 Total NaN in row 6365 : 2
 Total NaN in row 6366 : 10
 Total NaN in row 6367 : 9
 Total NaN in row 6368 : 1
 Total NaN in row 6369 : 0
 Total NaN in row 6370 : 0
 Total NaN in row 6371 : 2
 Total NaN in row 6372 : 2
 Total NaN in row 6373 : 1
 Total NaN in row 6374 : 10
 Total NaN in row 6375 : 1
 Total NaN in row 6376 : 10
 Total NaN in row 6377 : 9
 Total NaN in row 6378 : 2
 Total NaN in row 6379 : 0
 Total NaN in row 6380 : 0
 Total NaN in row 6381 : 1
 Total NaN in row 6382 : 2
 Total NaN in row 6383 : 0
 Total NaN in row 6384 : 10
 Total NaN in row 6385 : 0
 Total NaN in row 6386 : 9
 Total NaN in row 6387 : 2
 Total NaN in row 6388 : 1
 Total NaN in row 6389 : 3
 Total NaN in row 6390 : 2
 Total NaN in row 6391 : 1
 Total NaN in row 6392 : 9
 Total NaN in row 6393 : 0
 Total NaN in row 6394 : 10
 Total NaN in row 6395 : 0
 Total NaN in row 6396 : 2
 Total NaN in row 6397 : 3
 Total NaN in row 6398 : 9
 Total NaN in row 6399 : 0
 Total NaN in row 6400 : 9
 Total NaN in row 6401 : 3
 Total NaN in row 6402 : 0
 Total NaN in row 6403 : 2
 Total NaN in row 6404 : 2
 Total NaN in row 6405 : 2
 Total NaN in row 6406 : 3
 Total NaN in row 6407 : 21
 Total NaN in row 6408 : 10
 Total NaN in row 6409 : 10
 Total NaN in row 6410 : 3
 Total NaN in row 6411 : 9
 Total NaN in row 6412 : 0
 Total NaN in row 6413 : 2
 Total NaN in row 6414 : 2
 Total NaN in row 6415 : 10
 Total NaN in row 6416 : 9
 Total NaN in row 6417 : 2
 Total NaN in row 6418 : 10
 Total NaN in row 6419 : 2

 Total NaN in row 6420 : 2
 Total NaN in row 6421 : 2
 Total NaN in row 6422 : 1
 Total NaN in row 6423 : 1
 Total NaN in row 6424 : 3
 Total NaN in row 6425 : 1
 Total NaN in row 6426 : 1
 Total NaN in row 6427 : 0
 Total NaN in row 6428 : 0
 Total NaN in row 6429 : 10
 Total NaN in row 6430 : 0
 Total NaN in row 6431 : 3
 Total NaN in row 6432 : 9
 Total NaN in row 6433 : 3
 Total NaN in row 6434 : 0
 Total NaN in row 6435 : 1
 Total NaN in row 6436 : 3
 Total NaN in row 6437 : 0
 Total NaN in row 6438 : 1
 Total NaN in row 6439 : 3
 Total NaN in row 6440 : 9
 Total NaN in row 6441 : 9
 Total NaN in row 6442 : 9
 Total NaN in row 6443 : 2
 Total NaN in row 6444 : 2
 Total NaN in row 6445 : 10
 Total NaN in row 6446 : 3
 Total NaN in row 6447 : 21
 Total NaN in row 6448 : 0
 Total NaN in row 6449 : 2
 Total NaN in row 6450 : 1
 Total NaN in row 6451 : 0
 Total NaN in row 6452 : 2
 Total NaN in row 6453 : 0
 Total NaN in row 6454 : 0
 Total NaN in row 6455 : 1
 Total NaN in row 6456 : 9
 Total NaN in row 6457 : 9
 Total NaN in row 6458 : 0
 Total NaN in row 6459 : 1
 Total NaN in row 6460 : 10
 Total NaN in row 6461 : 10
 Total NaN in row 6462 : 0
 Total NaN in row 6463 : 0
 Total NaN in row 6464 : 3
 Total NaN in row 6465 : 2
 Total NaN in row 6466 : 9
 Total NaN in row 6467 : 3
 Total NaN in row 6468 : 2
 Total NaN in row 6469 : 0
 Total NaN in row 6470 : 1
 Total NaN in row 6471 : 10
 Total NaN in row 6472 : 2
 Total NaN in row 6473 : 1
 Total NaN in row 6474 : 0
 Total NaN in row 6475 : 1
 Total NaN in row 6476 : 0
 Total NaN in row 6477 : 9
 Total NaN in row 6478 : 1
 Total NaN in row 6479 : 10
 Total NaN in row 6480 : 1
 Total NaN in row 6481 : 0
 Total NaN in row 6482 : 9
 Total NaN in row 6483 : 3
 Total NaN in row 6484 : 9
 Total NaN in row 6485 : 0
 Total NaN in row 6486 : 1
 Total NaN in row 6487 : 10
 Total NaN in row 6488 : 0
 Total NaN in row 6489 : 1
 Total NaN in row 6490 : 0
 Total NaN in row 6491 : 1
 Total NaN in row 6492 : 2
 Total NaN in row 6493 : 1
 Total NaN in row 6494 : 0
 Total NaN in row 6495 : 2
 Total NaN in row 6496 : 2
 Total NaN in row 6497 : 3
 Total NaN in row 6498 : 2
 Total NaN in row 6499 : 3
 Total NaN in row 6500 : 2
 Total NaN in row 6501 : 1
 Total NaN in row 6502 : 0
 Total NaN in row 6503 : 0
 Total NaN in row 6504 : 0
 Total NaN in row 6505 : 2
 Total NaN in row 6506 : 9
 Total NaN in row 6507 : 9
 Total NaN in row 6508 : 1
 Total NaN in row 6509 : 9
 Total NaN in row 6510 : 1
 Total NaN in row 6511 : 3
 Total NaN in row 6512 : 2
 Total NaN in row 6513 : 3
 Total NaN in row 6514 : 1
 Total NaN in row 6515 : 0
 Total NaN in row 6516 : 0
 Total NaN in row 6517 : 9
 Total NaN in row 6518 : 9
 Total NaN in row 6519 : 9
 Total NaN in row 6520 : 1
 Total NaN in row 6521 : 1
 Total NaN in row 6522 : 1
 Total NaN in row 6523 : 0
 Total NaN in row 6524 : 0
 Total NaN in row 6525 : 1
 Total NaN in row 6526 : 1
 Total NaN in row 6527 : 0
 Total NaN in row 6528 : 9
 Total NaN in row 6529 : 2
 Total NaN in row 6530 : 0
 Total NaN in row 6531 : 0
 Total NaN in row 6532 : 2
 Total NaN in row 6533 : 9
 Total NaN in row 6534 : 0
 Total NaN in row 6535 : 0
 Total NaN in row 6536 : 0
 Total NaN in row 6537 : 10
 Total NaN in row 6538 : 0
 Total NaN in row 6539 : 9
 Total NaN in row 6540 : 3
 Total NaN in row 6541 : 2
 Total NaN in row 6542 : 1
 Total NaN in row 6543 : 1
 Total NaN in row 6544 : 1
 Total NaN in row 6545 : 1
 Total NaN in row 6546 : 9
 Total NaN in row 6547 : 0
 Total NaN in row 6548 : 0
 Total NaN in row 6549 : 10
 Total NaN in row 6550 : 2
 Total NaN in row 6551 : 2
 Total NaN in row 6552 : 1
 Total NaN in row 6553 : 1
 Total NaN in row 6554 : 9
 Total NaN in row 6555 : 1
 Total NaN in row 6556 : 3
 Total NaN in row 6557 : 1
 Total NaN in row 6558 : 0
 Total NaN in row 6559 : 1
 Total NaN in row 6560 : 9
 Total NaN in row 6561 : 2
 Total NaN in row 6562 : 2
 Total NaN in row 6563 : 0
 Total NaN in row 6564 : 0
 Total NaN in row 6565 : 1
 Total NaN in row 6566 : 10
 Total NaN in row 6567 : 9
 Total NaN in row 6568 : 9
 Total NaN in row 6569 : 9
 Total NaN in row 6570 : 1
 Total NaN in row 6571 : 0
 Total NaN in row 6572 : 0
 Total NaN in row 6573 : 0
 Total NaN in row 6574 : 9
 Total NaN in row 6575 : 0
 Total NaN in row 6576 : 2
 Total NaN in row 6577 : 0
 Total NaN in row 6578 : 0
 Total NaN in row 6579 : 2
 Total NaN in row 6580 : 0
 Total NaN in row 6581 : 9
 Total NaN in row 6582 : 9
 Total NaN in row 6583 : 2
 Total NaN in row 6584 : 9
 Total NaN in row 6585 : 0
 Total NaN in row 6586 : 2
 Total NaN in row 6587 : 0
 Total NaN in row 6588 : 0
 Total NaN in row 6589 : 0
 Total NaN in row 6590 : 2
 Total NaN in row 6591 : 2
 Total NaN in row 6592 : 1
 Total NaN in row 6593 : 2
 Total NaN in row 6594 : 10
 Total NaN in row 6595 : 9
 Total NaN in row 6596 : 9
 Total NaN in row 6597 : 2
 Total NaN in row 6598 : 9
 Total NaN in row 6599 : 9
 Total NaN in row 6600 : 9
 Total NaN in row 6601 : 9
 Total NaN in row 6602 : 9
 Total NaN in row 6603 : 10
 Total NaN in row 6604 : 0
 Total NaN in row 6605 : 0
 Total NaN in row 6606 : 1
 Total NaN in row 6607 : 9
 Total NaN in row 6608 : 1
 Total NaN in row 6609 : 2
 Total NaN in row 6610 : 0
 Total NaN in row 6611 : 2
 Total NaN in row 6612 : 2
 Total NaN in row 6613 : 2
 Total NaN in row 6614 : 0
 Total NaN in row 6615 : 9
 Total NaN in row 6616 : 10
 Total NaN in row 6617 : 9
 Total NaN in row 6618 : 0
 Total NaN in row 6619 : 2
 Total NaN in row 6620 : 1
 Total NaN in row 6621 : 0
 Total NaN in row 6622 : 3
 Total NaN in row 6623 : 2
 Total NaN in row 6624 : 10
 Total NaN in row 6625 : 9
 Total NaN in row 6626 : 1
 Total NaN in row 6627 : 0
 Total NaN in row 6628 : 0
 Total NaN in row 6629 : 2
 Total NaN in row 6630 : 10
 Total NaN in row 6631 : 2
 Total NaN in row 6632 : 3
 Total NaN in row 6633 : 0
 Total NaN in row 6634 : 0
 Total NaN in row 6635 : 0
 Total NaN in row 6636 : 2
 Total NaN in row 6637 : 9
 Total NaN in row 6638 : 0
 Total NaN in row 6639 : 2
 Total NaN in row 6640 : 0
 Total NaN in row 6641 : 2
 Total NaN in row 6642 : 10
 Total NaN in row 6643 : 10
 Total NaN in row 6644 : 0
 Total NaN in row 6645 : 9
 Total NaN in row 6646 : 9
 Total NaN in row 6647 : 0
 Total NaN in row 6648 : 0
 Total NaN in row 6649 : 0
 Total NaN in row 6650 : 0
 Total NaN in row 6651 : 0
 Total NaN in row 6652 : 0
 Total NaN in row 6653 : 2
 Total NaN in row 6654 : 9
 Total NaN in row 6655 : 0
 Total NaN in row 6656 : 3
 Total NaN in row 6657 : 2
 Total NaN in row 6658 : 0
 Total NaN in row 6659 : 9
 Total NaN in row 6660 : 9
 Total NaN in row 6661 : 0
 Total NaN in row 6662 : 0
 Total NaN in row 6663 : 9
 Total NaN in row 6664 : 0
 Total NaN in row 6665 : 0
 Total NaN in row 6666 : 9
 Total NaN in row 6667 : 0
 Total NaN in row 6668 : 2
 Total NaN in row 6669 : 1
 Total NaN in row 6670 : 0
 Total NaN in row 6671 : 9
 Total NaN in row 6672 : 1
 Total NaN in row 6673 : 0
 Total NaN in row 6674 : 1
 Total NaN in row 6675 : 2
 Total NaN in row 6676 : 0
 Total NaN in row 6677 : 1
 Total NaN in row 6678 : 1
 Total NaN in row 6679 : 9
 Total NaN in row 6680 : 9
 Total NaN in row 6681 : 2
 Total NaN in row 6682 : 9
 Total NaN in row 6683 : 9
 Total NaN in row 6684 : 1
 Total NaN in row 6685 : 9
 Total NaN in row 6686 : 10
 Total NaN in row 6687 : 9
 Total NaN in row 6688 : 0
 Total NaN in row 6689 : 10
 Total NaN in row 6690 : 9
 Total NaN in row 6691 : 9
 Total NaN in row 6692 : 9
 Total NaN in row 6693 : 9
 Total NaN in row 6694 : 10
 Total NaN in row 6695 : 10
 Total NaN in row 6696 : 0
 Total NaN in row 6697 : 10
 Total NaN in row 6698 : 1
 Total NaN in row 6699 : 1
 Total NaN in row 6700 : 9
 Total NaN in row 6701 : 9
 Total NaN in row 6702 : 0
 Total NaN in row 6703 : 1
 Total NaN in row 6704 : 21
 Total NaN in row 6705 : 10
 Total NaN in row 6706 : 0
 Total NaN in row 6707 : 9
 Total NaN in row 6708 : 9
 Total NaN in row 6709 : 9
 Total NaN in row 6710 : 0
 Total NaN in row 6711 : 9
 Total NaN in row 6712 : 9
 Total NaN in row 6713 : 9
 Total NaN in row 6714 : 0
 Total NaN in row 6715 : 0
 Total NaN in row 6716 : 9
 Total NaN in row 6717 : 2
 Total NaN in row 6718 : 21
 Total NaN in row 6719 : 1
 Total NaN in row 6720 : 10
 Total NaN in row 6721 : 1
 Total NaN in row 6722 : 0
 Total NaN in row 6723 : 0
 Total NaN in row 6724 : 9
 Total NaN in row 6725 : 0

 Total NaN in row 6726 : 9
 Total NaN in row 6727 : 1
 Total NaN in row 6728 : 2
 Total NaN in row 6729 : 1
 Total NaN in row 6730 : 10
 Total NaN in row 6731 : 9
 Total NaN in row 6732 : 9
 Total NaN in row 6733 : 0
 Total NaN in row 6734 : 0
 Total NaN in row 6735 : 9
 Total NaN in row 6736 : 10
 Total NaN in row 6737 : 10
 Total NaN in row 6738 : 9
 Total NaN in row 6739 : 9
 Total NaN in row 6740 : 9
 Total NaN in row 6741 : 10
 Total NaN in row 6742 : 9
 Total NaN in row 6743 : 9
 Total NaN in row 6744 : 10
 Total NaN in row 6745 : 0
 Total NaN in row 6746 : 10
 Total NaN in row 6747 : 9
 Total NaN in row 6748 : 0
 Total NaN in row 6749 : 1
 Total NaN in row 6750 : 9
 Total NaN in row 6751 : 1
 Total NaN in row 6752 : 0
 Total NaN in row 6753 : 3
 Total NaN in row 6754 : 9
 Total NaN in row 6755 : 2
 Total NaN in row 6756 : 0
 Total NaN in row 6757 : 1
 Total NaN in row 6758 : 0
 Total NaN in row 6759 : 9
 Total NaN in row 6760 : 10
 Total NaN in row 6761 : 9
 Total NaN in row 6762 : 0
 Total NaN in row 6763 : 2
 Total NaN in row 6764 : 9
 Total NaN in row 6765 : 9
 Total NaN in row 6766 : 0
 Total NaN in row 6767 : 1
 Total NaN in row 6768 : 9
 Total NaN in row 6769 : 9
 Total NaN in row 6770 : 9
 Total NaN in row 6771 : 2
 Total NaN in row 6772 : 9
 Total NaN in row 6773 : 10
 Total NaN in row 6774 : 10
 Total NaN in row 6775 : 10
 Total NaN in row 6776 : 9
 Total NaN in row 6777 : 2
 Total NaN in row 6778 : 1
 Total NaN in row 6779 : 9
 Total NaN in row 6780 : 0
 Total NaN in row 6781 : 1
 Total NaN in row 6782 : 10
 Total NaN in row 6783 : 0
 Total NaN in row 6784 : 9
 Total NaN in row 6785 : 1
 Total NaN in row 6786 : 10
 Total NaN in row 6787 : 9
 Total NaN in row 6788 : 9
 Total NaN in row 6789 : 9
 Total NaN in row 6790 : 0
 Total NaN in row 6791 : 3
 Total NaN in row 6792 : 0
 Total NaN in row 6793 : 2
 Total NaN in row 6794 : 0
 Total NaN in row 6795 : 2
 Total NaN in row 6796 : 10
 Total NaN in row 6797 : 1
 Total NaN in row 6798 : 9
 Total NaN in row 6799 : 2
 Total NaN in row 6800 : 1
 Total NaN in row 6801 : 2
 Total NaN in row 6802 : 0
 Total NaN in row 6803 : 10
 Total NaN in row 6804 : 3
 Total NaN in row 6805 : 1
 Total NaN in row 6806 : 2
 Total NaN in row 6807 : 1
 Total NaN in row 6808 : 1
 Total NaN in row 6809 : 0
 Total NaN in row 6810 : 0
 Total NaN in row 6811 : 3
 Total NaN in row 6812 : 0
 Total NaN in row 6813 : 0
 Total NaN in row 6814 : 10
 Total NaN in row 6815 : 0
 Total NaN in row 6816 : 0
 Total NaN in row 6817 : 0
 Total NaN in row 6818 : 1
 Total NaN in row 6819 : 0
 Total NaN in row 6820 : 2
 Total NaN in row 6821 : 0
 Total NaN in row 6822 : 1
 Total NaN in row 6823 : 1
 Total NaN in row 6824 : 9
 Total NaN in row 6825 : 0
 Total NaN in row 6826 : 2
 Total NaN in row 6827 : 9
 Total NaN in row 6828 : 0
 Total NaN in row 6829 : 10
 Total NaN in row 6830 : 9
 Total NaN in row 6831 : 9
 Total NaN in row 6832 : 2
 Total NaN in row 6833 : 2
 Total NaN in row 6834 : 2
 Total NaN in row 6835 : 9
 Total NaN in row 6836 : 1
 Total NaN in row 6837 : 0
 Total NaN in row 6838 : 1
 Total NaN in row 6839 : 2
 Total NaN in row 6840 : 0
 Total NaN in row 6841 : 1
 Total NaN in row 6842 : 10
 Total NaN in row 6843 : 7
 Total NaN in row 6844 : 3
 Total NaN in row 6845 : 10
 Total NaN in row 6846 : 0
 Total NaN in row 6847 : 10
 Total NaN in row 6848 : 10
 Total NaN in row 6849 : 1
 Total NaN in row 6850 : 9
 Total NaN in row 6851 : 0
 Total NaN in row 6852 : 9
 Total NaN in row 6853 : 0
 Total NaN in row 6854 : 21
 Total NaN in row 6855 : 3
 Total NaN in row 6856 : 9
 Total NaN in row 6857 : 0
 Total NaN in row 6858 : 10
 Total NaN in row 6859 : 9
 Total NaN in row 6860 : 2
 Total NaN in row 6861 : 0
 Total NaN in row 6862 : 9
 Total NaN in row 6863 : 9
 Total NaN in row 6864 : 10
 Total NaN in row 6865 : 0
 Total NaN in row 6866 : 9
 Total NaN in row 6867 : 10
 Total NaN in row 6868 : 0
 Total NaN in row 6869 : 0
 Total NaN in row 6870 : 2
 Total NaN in row 6871 : 3
 Total NaN in row 6872 : 0
 Total NaN in row 6873 : 0
 Total NaN in row 6874 : 0
 Total NaN in row 6875 : 2
 Total NaN in row 6876 : 2
 Total NaN in row 6877 : 0
 Total NaN in row 6878 : 1
 Total NaN in row 6879 : 10
 Total NaN in row 6880 : 0
 Total NaN in row 6881 : 0
 Total NaN in row 6882 : 9
 Total NaN in row 6883 : 10
 Total NaN in row 6884 : 0
 Total NaN in row 6885 : 2
 Total NaN in row 6886 : 0
 Total NaN in row 6887 : 0
 Total NaN in row 6888 : 0
 Total NaN in row 6889 : 2
 Total NaN in row 6890 : 2
 Total NaN in row 6891 : 2
 Total NaN in row 6892 : 0
 Total NaN in row 6893 : 1
 Total NaN in row 6894 : 0
 Total NaN in row 6895 : 0
 Total NaN in row 6896 : 0
 Total NaN in row 6897 : 0
 Total NaN in row 6898 : 0
 Total NaN in row 6899 : 0
 Total NaN in row 6900 : 2
 Total NaN in row 6901 : 2
 Total NaN in row 6902 : 0
 Total NaN in row 6903 : 0
 Total NaN in row 6904 : 2
 Total NaN in row 6905 : 0
 Total NaN in row 6906 : 0
 Total NaN in row 6907 : 0
 Total NaN in row 6908 : 0
 Total NaN in row 6909 : 2
 Total NaN in row 6910 : 0
 Total NaN in row 6911 : 3
 Total NaN in row 6912 : 0
 Total NaN in row 6913 : 0
 Total NaN in row 6914 : 2
 Total NaN in row 6915 : 10
 Total NaN in row 6916 : 0
 Total NaN in row 6917 : 2
 Total NaN in row 6918 : 0
 Total NaN in row 6919 : 0
 Total NaN in row 6920 : 2
 Total NaN in row 6921 : 2
 Total NaN in row 6922 : 21
 Total NaN in row 6923 : 0
 Total NaN in row 6924 : 9
 Total NaN in row 6925 : 2
 Total NaN in row 6926 : 0
 Total NaN in row 6927 : 1
 Total NaN in row 6928 : 0
 Total NaN in row 6929 : 3
 Total NaN in row 6930 : 2
 Total NaN in row 6931 : 0
 Total NaN in row 6932 : 2
 Total NaN in row 6933 : 2
 Total NaN in row 6934 : 2
 Total NaN in row 6935 : 1
 Total NaN in row 6936 : 0
 Total NaN in row 6937 : 0
 Total NaN in row 6938 : 9
 Total NaN in row 6939 : 1
 Total NaN in row 6940 : 0
 Total NaN in row 6941 : 1
 Total NaN in row 6942 : 0
 Total NaN in row 6943 : 10
 Total NaN in row 6944 : 2
 Total NaN in row 6945 : 2
 Total NaN in row 6946 : 2
 Total NaN in row 6947 : 2
 Total NaN in row 6948 : 7
 Total NaN in row 6949 : 0
 Total NaN in row 6950 : 0
 Total NaN in row 6951 : 0
 Total NaN in row 6952 : 1
 Total NaN in row 6953 : 0
 Total NaN in row 6954 : 0
 Total NaN in row 6955 : 0
 Total NaN in row 6956 : 0
 Total NaN in row 6957 : 0
 Total NaN in row 6958 : 0
 Total NaN in row 6959 : 0
 Total NaN in row 6960 : 2
 Total NaN in row 6961 : 9
 Total NaN in row 6962 : 0
 Total NaN in row 6963 : 3
 Total NaN in row 6964 : 1
 Total NaN in row 6965 : 2
 Total NaN in row 6966 : 9
 Total NaN in row 6967 : 10
 Total NaN in row 6968 : 9
 Total NaN in row 6969 : 2
 Total NaN in row 6970 : 0
 Total NaN in row 6971 : 0
 Total NaN in row 6972 : 1
 Total NaN in row 6973 : 0
 Total NaN in row 6974 : 0
 Total NaN in row 6975 : 3
 Total NaN in row 6976 : 1
 Total NaN in row 6977 : 9
 Total NaN in row 6978 : 0
 Total NaN in row 6979 : 1
 Total NaN in row 6980 : 1
 Total NaN in row 6981 : 2
 Total NaN in row 6982 : 0
 Total NaN in row 6983 : 0
 Total NaN in row 6984 : 2
 Total NaN in row 6985 : 1
 Total NaN in row 6986 : 2
 Total NaN in row 6987 : 0
 Total NaN in row 6988 : 2
 Total NaN in row 6989 : 2
 Total NaN in row 6990 : 2
 Total NaN in row 6991 : 1
 Total NaN in row 6992 : 2
 Total NaN in row 6993 : 0
 Total NaN in row 6994 : 0
 Total NaN in row 6995 : 1
 Total NaN in row 6996 : 0
 Total NaN in row 6997 : 2
 Total NaN in row 6998 : 0
 Total NaN in row 6999 : 0
 Total NaN in row 7000 : 1
 Total NaN in row 7001 : 0
 Total NaN in row 7002 : 1
 Total NaN in row 7003 : 0
 Total NaN in row 7004 : 0
 Total NaN in row 7005 : 1
 Total NaN in row 7006 : 9
 Total NaN in row 7007 : 2
 Total NaN in row 7008 : 0
 Total NaN in row 7009 : 3
 Total NaN in row 7010 : 9
 Total NaN in row 7011 : 0
 Total NaN in row 7012 : 1
 Total NaN in row 7013 : 0
 Total NaN in row 7014 : 9
 Total NaN in row 7015 : 2
 Total NaN in row 7016 : 0
 Total NaN in row 7017 : 2
 Total NaN in row 7018 : 0
 Total NaN in row 7019 : 0
 Total NaN in row 7020 : 0
 Total NaN in row 7021 : 0
 Total NaN in row 7022 : 1
 Total NaN in row 7023 : 2
 Total NaN in row 7024 : 0
 Total NaN in row 7025 : 2
 Total NaN in row 7026 : 2
 Total NaN in row 7027 : 1
 Total NaN in row 7028 : 9
 Total NaN in row 7029 : 9
 Total NaN in row 7030 : 2
 Total NaN in row 7031 : 0
 Total NaN in row 7032 : 0
 Total NaN in row 7033 : 0
 Total NaN in row 7034 : 0
 Total NaN in row 7035 : 0
 Total NaN in row 7036 : 0
 Total NaN in row 7037 : 0
 Total NaN in row 7038 : 0
 Total NaN in row 7039 : 2
 Total NaN in row 7040 : 9
 Total NaN in row 7041 : 2
 Total NaN in row 7042 : 9
 Total NaN in row 7043 : 9
 Total NaN in row 7044 : 9
 Total NaN in row 7045 : 0
 Total NaN in row 7046 : 2
 Total NaN in row 7047 : 0
 Total NaN in row 7048 : 0
 Total NaN in row 7049 : 0
 Total NaN in row 7050 : 0
 Total NaN in row 7051 : 1
 Total NaN in row 7052 : 0
 Total NaN in row 7053 : 0
 Total NaN in row 7054 : 2
 Total NaN in row 7055 : 0
 Total NaN in row 7056 : 2
 Total NaN in row 7057 : 1
 Total NaN in row 7058 : 3
 Total NaN in row 7059 : 0
 Total NaN in row 7060 : 0
 Total NaN in row 7061 : 1
 Total NaN in row 7062 : 0
 Total NaN in row 7063 : 0
 Total NaN in row 7064 : 9
 Total NaN in row 7065 : 0
 Total NaN in row 7066 : 0
 Total NaN in row 7067 : 9
 Total NaN in row 7068 : 9
 Total NaN in row 7069 : 9
 Total NaN in row 7070 : 1
 Total NaN in row 7071 : 10
 Total NaN in row 7072 : 9
 Total NaN in row 7073 : 0
 Total NaN in row 7074 : 1
 Total NaN in row 7075 : 0
 Total NaN in row 7076 : 0
 Total NaN in row 7077 : 0
 Total NaN in row 7078 : 1
 Total NaN in row 7079 : 0
 Total NaN in row 7080 : 1
 Total NaN in row 7081 : 0
 Total NaN in row 7082 : 9
 Total NaN in row 7083 : 0
 Total NaN in row 7084 : 0
 Total NaN in row 7085 : 0
 Total NaN in row 7086 : 0
 Total NaN in row 7087 : 21
 Total NaN in row 7088 : 2
 Total NaN in row 7089 : 3
 Total NaN in row 7090 : 2
 Total NaN in row 7091 : 1
 Total NaN in row 7092 : 2
 Total NaN in row 7093 : 9
 Total NaN in row 7094 : 7
 Total NaN in row 7095 : 0
 Total NaN in row 7096 : 1
 Total NaN in row 7097 : 2
 Total NaN in row 7098 : 2
 Total NaN in row 7099 : 2
 Total NaN in row 7100 : 0
 Total NaN in row 7101 : 0
 Total NaN in row 7102 : 1
 Total NaN in row 7103 : 0
 Total NaN in row 7104 : 2
 Total NaN in row 7105 : 2
 Total NaN in row 7106 : 9
 Total NaN in row 7107 : 0

 Total NaN in row 7108 : 2
 Total NaN in row 7109 : 2
 Total NaN in row 7110 : 1
 Total NaN in row 7111 : 2
 Total NaN in row 7112 : 1
 Total NaN in row 7113 : 0
 Total NaN in row 7114 : 0
 Total NaN in row 7115 : 0
 Total NaN in row 7116 : 0
 Total NaN in row 7117 : 1
 Total NaN in row 7118 : 2
 Total NaN in row 7119 : 0
 Total NaN in row 7120 : 0
 Total NaN in row 7121 : 0
 Total NaN in row 7122 : 2
 Total NaN in row 7123 : 0
 Total NaN in row 7124 : 0
 Total NaN in row 7125 : 0
 Total NaN in row 7126 : 1
 Total NaN in row 7127 : 0
 Total NaN in row 7128 : 1
 Total NaN in row 7129 : 1
 Total NaN in row 7130 : 3
 Total NaN in row 7131 : 9
 Total NaN in row 7132 : 0
 Total NaN in row 7133 : 2
 Total NaN in row 7134 : 0
 Total NaN in row 7135 : 10
 Total NaN in row 7136 : 0
 Total NaN in row 7137 : 0
 Total NaN in row 7138 : 2
 Total NaN in row 7139 : 0
 Total NaN in row 7140 : 2
 Total NaN in row 7141 : 0
 Total NaN in row 7142 : 2
 Total NaN in row 7143 : 0
 Total NaN in row 7144 : 1
 Total NaN in row 7145 : 0
 Total NaN in row 7146 : 1
 Total NaN in row 7147 : 9
 Total NaN in row 7148 : 0
 Total NaN in row 7149 : 0
 Total NaN in row 7150 : 2
 Total NaN in row 7151 : 0
 Total NaN in row 7152 : 3
 Total NaN in row 7153 : 2
 Total NaN in row 7154 : 10
 Total NaN in row 7155 : 0
 Total NaN in row 7156 : 2
 Total NaN in row 7157 : 0
 Total NaN in row 7158 : 3
 Total NaN in row 7159 : 0
 Total NaN in row 7160 : 2
 Total NaN in row 7161 : 9
 Total NaN in row 7162 : 2
 Total NaN in row 7163 : 2
 Total NaN in row 7164 : 0
 Total NaN in row 7165 : 1
 Total NaN in row 7166 : 0
 Total NaN in row 7167 : 3
 Total NaN in row 7168 : 0
 Total NaN in row 7169 : 3
 Total NaN in row 7170 : 2
 Total NaN in row 7171 : 2
 Total NaN in row 7172 : 1
 Total NaN in row 7173 : 0
 Total NaN in row 7174 : 0
 Total NaN in row 7175 : 0
 Total NaN in row 7176 : 0
 Total NaN in row 7177 : 0
 Total NaN in row 7178 : 0
 Total NaN in row 7179 : 0
 Total NaN in row 7180 : 9
 Total NaN in row 7181 : 2
 Total NaN in row 7182 : 9
 Total NaN in row 7183 : 9
 Total NaN in row 7184 : 2
 Total NaN in row 7185 : 2
 Total NaN in row 7186 : 0
 Total NaN in row 7187 : 0
 Total NaN in row 7188 : 0
 Total NaN in row 7189 : 0
 Total NaN in row 7190 : 9
 Total NaN in row 7191 : 0
 Total NaN in row 7192 : 2
 Total NaN in row 7193 : 0
 Total NaN in row 7194 : 0
 Total NaN in row 7195 : 9
 Total NaN in row 7196 : 2
 Total NaN in row 7197 : 9
 Total NaN in row 7198 : 2
 Total NaN in row 7199 : 2
 Total NaN in row 7200 : 9
 Total NaN in row 7201 : 0
 Total NaN in row 7202 : 1
 Total NaN in row 7203 : 9
 Total NaN in row 7204 : 1
 Total NaN in row 7205 : 0
 Total NaN in row 7206 : 9
 Total NaN in row 7207 : 0
 Total NaN in row 7208 : 2
 Total NaN in row 7209 : 2
 Total NaN in row 7210 : 2
 Total NaN in row 7211 : 2
 Total NaN in row 7212 : 2
 Total NaN in row 7213 : 9
 Total NaN in row 7214 : 0
 Total NaN in row 7215 : 2
 Total NaN in row 7216 : 2
 Total NaN in row 7217 : 0
 Total NaN in row 7218 : 0
 Total NaN in row 7219 : 2
 Total NaN in row 7220 : 9
 Total NaN in row 7221 : 2
 Total NaN in row 7222 : 2
 Total NaN in row 7223 : 1
 Total NaN in row 7224 : 2
 Total NaN in row 7225 : 1
 Total NaN in row 7226 : 0
 Total NaN in row 7227 : 1
 Total NaN in row 7228 : 2
 Total NaN in row 7229 : 2
 Total NaN in row 7230 : 2
 Total NaN in row 7231 : 9
 Total NaN in row 7232 : 2
 Total NaN in row 7233 : 2
 Total NaN in row 7234 : 3
 Total NaN in row 7235 : 0
 Total NaN in row 7236 : 2
 Total NaN in row 7237 : 2
 Total NaN in row 7238 : 2
 Total NaN in row 7239 : 9
 Total NaN in row 7240 : 9
 Total NaN in row 7241 : 0
 Total NaN in row 7242 : 2
 Total NaN in row 7243 : 2
 Total NaN in row 7244 : 2
 Total NaN in row 7245 : 2
 Total NaN in row 7246 : 0
 Total NaN in row 7247 : 2
 Total NaN in row 7248 : 2
 Total NaN in row 7249 : 0
 Total NaN in row 7250 : 2
 Total NaN in row 7251 : 0
 Total NaN in row 7252 : 0
 Total NaN in row 7253 : 0
 Total NaN in row 7254 : 0
 Total NaN in row 7255 : 0
 Total NaN in row 7256 : 2
 Total NaN in row 7257 : 1
 Total NaN in row 7258 : 2
 Total NaN in row 7259 : 0
 Total NaN in row 7260 : 0
 Total NaN in row 7261 : 2
 Total NaN in row 7262 : 21
 Total NaN in row 7263 : 0
 Total NaN in row 7264 : 1
 Total NaN in row 7265 : 2
 Total NaN in row 7266 : 0
 Total NaN in row 7267 : 2
 Total NaN in row 7268 : 1
 Total NaN in row 7269 : 0
 Total NaN in row 7270 : 2
 Total NaN in row 7271 : 1
 Total NaN in row 7272 : 1
 Total NaN in row 7273 : 0
 Total NaN in row 7274 : 0
 Total NaN in row 7275 : 1
 Total NaN in row 7276 : 0
 Total NaN in row 7277 : 0
 Total NaN in row 7278 : 1
 Total NaN in row 7279 : 0
 Total NaN in row 7280 : 1
 Total NaN in row 7281 : 1
 Total NaN in row 7282 : 0
 Total NaN in row 7283 : 0
 Total NaN in row 7284 : 0
 Total NaN in row 7285 : 2
 Total NaN in row 7286 : 2
 Total NaN in row 7287 : 3
 Total NaN in row 7288 : 0
 Total NaN in row 7289 : 0
 Total NaN in row 7290 : 0
 Total NaN in row 7291 : 1
 Total NaN in row 7292 : 9
 Total NaN in row 7293 : 9
 Total NaN in row 7294 : 1
 Total NaN in row 7295 : 9
 Total NaN in row 7296 : 2
 Total NaN in row 7297 : 0
 Total NaN in row 7298 : 9
 Total NaN in row 7299 : 1
 Total NaN in row 7300 : 0
 Total NaN in row 7301 : 1
 Total NaN in row 7302 : 0
 Total NaN in row 7303 : 0
 Total NaN in row 7304 : 0
 Total NaN in row 7305 : 0
 Total NaN in row 7306 : 0
 Total NaN in row 7307 : 0
 Total NaN in row 7308 : 1
 Total NaN in row 7309 : 1
 Total NaN in row 7310 : 0
 Total NaN in row 7311 : 3
 Total NaN in row 7312 : 1
 Total NaN in row 7313 : 0
 Total NaN in row 7314 : 1
 Total NaN in row 7315 : 0
 Total NaN in row 7316 : 0
 Total NaN in row 7317 : 0
 Total NaN in row 7318 : 2
 Total NaN in row 7319 : 0
 Total NaN in row 7320 : 1
 Total NaN in row 7321 : 1
 Total NaN in row 7322 : 1
 Total NaN in row 7323 : 1
 Total NaN in row 7324 : 2
 Total NaN in row 7325 : 2
 Total NaN in row 7326 : 2
 Total NaN in row 7327 : 2
 Total NaN in row 7328 : 0
 Total NaN in row 7329 : 1
 Total NaN in row 7330 : 1
 Total NaN in row 7331 : 9
 Total NaN in row 7332 : 0
 Total NaN in row 7333 : 9
 Total NaN in row 7334 : 3
 Total NaN in row 7335 : 0
 Total NaN in row 7336 : 2
 Total NaN in row 7337 : 3
 Total NaN in row 7338 : 2
 Total NaN in row 7339 : 0
 Total NaN in row 7340 : 9
 Total NaN in row 7341 : 1
 Total NaN in row 7342 : 2
 Total NaN in row 7343 : 0
 Total NaN in row 7344 : 0
 Total NaN in row 7345 : 0
 Total NaN in row 7346 : 9
 Total NaN in row 7347 : 0
 Total NaN in row 7348 : 1
 Total NaN in row 7349 : 21
 Total NaN in row 7350 : 9
 Total NaN in row 7351 : 2
 Total NaN in row 7352 : 0
 Total NaN in row 7353 : 2
 Total NaN in row 7354 : 0
 Total NaN in row 7355 : 9
 Total NaN in row 7356 : 0
 Total NaN in row 7357 : 0
 Total NaN in row 7358 : 2
 Total NaN in row 7359 : 0
 Total NaN in row 7360 : 10
 Total NaN in row 7361 : 10
 Total NaN in row 7362 : 9
 Total NaN in row 7363 : 1
 Total NaN in row 7364 : 0
 Total NaN in row 7365 : 9
 Total NaN in row 7366 : 2
 Total NaN in row 7367 : 2
 Total NaN in row 7368 : 2
 Total NaN in row 7369 : 2
 Total NaN in row 7370 : 9
 Total NaN in row 7371 : 2
 Total NaN in row 7372 : 2
 Total NaN in row 7373 : 1
 Total NaN in row 7374 : 1
 Total NaN in row 7375 : 1
 Total NaN in row 7376 : 10
 Total NaN in row 7377 : 9
 Total NaN in row 7378 : 1
 Total NaN in row 7379 : 1
 Total NaN in row 7380 : 10
 Total NaN in row 7381 : 2
 Total NaN in row 7382 : 9
 Total NaN in row 7383 : 0
 Total NaN in row 7384 : 3
 Total NaN in row 7385 : 0
 Total NaN in row 7386 : 2
 Total NaN in row 7387 : 1
 Total NaN in row 7388 : 0
 Total NaN in row 7389 : 2
 Total NaN in row 7390 : 0
 Total NaN in row 7391 : 1
 Total NaN in row 7392 : 2
 Total NaN in row 7393 : 0
 Total NaN in row 7394 : 2
 Total NaN in row 7395 : 9
 Total NaN in row 7396 : 0
 Total NaN in row 7397 : 0
 Total NaN in row 7398 : 9
 Total NaN in row 7399 : 2
 Total NaN in row 7400 : 1
 Total NaN in row 7401 : 0
 Total NaN in row 7402 : 0
 Total NaN in row 7403 : 1
 Total NaN in row 7404 : 3
 Total NaN in row 7405 : 1
 Total NaN in row 7406 : 0
 Total NaN in row 7407 : 0
 Total NaN in row 7408 : 0
 Total NaN in row 7409 : 2
 Total NaN in row 7410 : 0
 Total NaN in row 7411 : 2
 Total NaN in row 7412 : 2
 Total NaN in row 7413 : 0
 Total NaN in row 7414 : 0
 Total NaN in row 7415 : 0
 Total NaN in row 7416 : 1
 Total NaN in row 7417 : 0
 Total NaN in row 7418 : 2
 Total NaN in row 7419 : 1
 Total NaN in row 7420 : 9
 Total NaN in row 7421 : 9
 Total NaN in row 7422 : 0
 Total NaN in row 7423 : 9
 Total NaN in row 7424 : 1
 Total NaN in row 7425 : 1
 Total NaN in row 7426 : 0
 Total NaN in row 7427 : 2
 Total NaN in row 7428 : 0
 Total NaN in row 7429 : 2
 Total NaN in row 7430 : 1
 Total NaN in row 7431 : 0
 Total NaN in row 7432 : 2
 Total NaN in row 7433 : 0
 Total NaN in row 7434 : 0
 Total NaN in row 7435 : 1
 Total NaN in row 7436 : 2
 Total NaN in row 7437 : 0
 Total NaN in row 7438 : 0
 Total NaN in row 7439 : 0
 Total NaN in row 7440 : 9
 Total NaN in row 7441 : 1
 Total NaN in row 7442 : 3
 Total NaN in row 7443 : 1
 Total NaN in row 7444 : 0
 Total NaN in row 7445 : 2
 Total NaN in row 7446 : 2
 Total NaN in row 7447 : 0
 Total NaN in row 7448 : 2
 Total NaN in row 7449 : 0
 Total NaN in row 7450 : 1
 Total NaN in row 7451 : 2
 Total NaN in row 7452 : 2
 Total NaN in row 7453 : 0
 Total NaN in row 7454 : 2
 Total NaN in row 7455 : 2
 Total NaN in row 7456 : 0
 Total NaN in row 7457 : 2
 Total NaN in row 7458 : 3
 Total NaN in row 7459 : 1
 Total NaN in row 7460 : 9
 Total NaN in row 7461 : 9
 Total NaN in row 7462 : 2
 Total NaN in row 7463 : 9
 Total NaN in row 7464 : 2
 Total NaN in row 7465 : 1
 Total NaN in row 7466 : 0
 Total NaN in row 7467 : 9
 Total NaN in row 7468 : 0
 Total NaN in row 7469 : 0
 Total NaN in row 7470 : 9
 Total NaN in row 7471 : 3
 Total NaN in row 7472 : 2
 Total NaN in row 7473 : 0
 Total NaN in row 7474 : 0
 Total NaN in row 7475 : 3
 Total NaN in row 7476 : 0
 Total NaN in row 7477 : 0
 Total NaN in row 7478 : 2
 Total NaN in row 7479 : 0
 Total NaN in row 7480 : 1
 Total NaN in row 7481 : 3
 Total NaN in row 7482 : 3
 Total NaN in row 7483 : 0
 Total NaN in row 7484 : 1
 Total NaN in row 7485 : 3
 Total NaN in row 7486 : 1
 Total NaN in row 7487 : 0
 Total NaN in row 7488 : 2
 Total NaN in row 7489 : 1
 Total NaN in row 7490 : 0
 Total NaN in row 7491 : 0
 Total NaN in row 7492 : 3
 Total NaN in row 7493 : 0
 Total NaN in row 7494 : 0
 Total NaN in row 7495 : 2
 Total NaN in row 7496 : 1
 Total NaN in row 7497 : 1
 Total NaN in row 7498 : 0
 Total NaN in row 7499 : 1
 Total NaN in row 7500 : 2
 Total NaN in row 7501 : 9
 Total NaN in row 7502 : 2
 Total NaN in row 7503 : 2
 Total NaN in row 7504 : 2
 Total NaN in row 7505 : 10
 Total NaN in row 7506 : 0
 Total NaN in row 7507 : 1

 Total NaN in row 7508 : 9
 Total NaN in row 7509 : 0
 Total NaN in row 7510 : 1
 Total NaN in row 7511 : 1
 Total NaN in row 7512 : 1
 Total NaN in row 7513 : 10
 Total NaN in row 7514 : 0
 Total NaN in row 7515 : 0
 Total NaN in row 7516 : 10
 Total NaN in row 7517 : 1
 Total NaN in row 7518 : 0
 Total NaN in row 7519 : 1
 Total NaN in row 7520 : 2
 Total NaN in row 7521 : 0
 Total NaN in row 7522 : 1
 Total NaN in row 7523 : 9
 Total NaN in row 7524 : 2
 Total NaN in row 7525 : 1
 Total NaN in row 7526 : 0
 Total NaN in row 7527 : 0
 Total NaN in row 7528 : 10
 Total NaN in row 7529 : 2
 Total NaN in row 7530 : 9
 Total NaN in row 7531 : 1
 Total NaN in row 7532 : 9
 Total NaN in row 7533 : 1
 Total NaN in row 7534 : 0
 Total NaN in row 7535 : 1
 Total NaN in row 7536 : 1
 Total NaN in row 7537 : 9
 Total NaN in row 7538 : 9
 Total NaN in row 7539 : 0
 Total NaN in row 7540 : 2
 Total NaN in row 7541 : 2
 Total NaN in row 7542 : 0
 Total NaN in row 7543 : 0
 Total NaN in row 7544 : 9
 Total NaN in row 7545 : 0
 Total NaN in row 7546 : 0
 Total NaN in row 7547 : 9
 Total NaN in row 7548 : 2
 Total NaN in row 7549 : 1
 Total NaN in row 7550 : 1
 Total NaN in row 7551 : 0
 Total NaN in row 7552 : 0
 Total NaN in row 7553 : 9
 Total NaN in row 7554 : 9
 Total NaN in row 7555 : 9
 Total NaN in row 7556 : 9
 Total NaN in row 7557 : 9
 Total NaN in row 7558 : 9
 Total NaN in row 7559 : 2
 Total NaN in row 7560 : 9
 Total NaN in row 7561 : 0
 Total NaN in row 7562 : 9
 Total NaN in row 7563 : 0
 Total NaN in row 7564 : 2
 Total NaN in row 7565 : 9
 Total NaN in row 7566 : 9
 Total NaN in row 7567 : 9
 Total NaN in row 7568 : 1
 Total NaN in row 7569 : 2
 Total NaN in row 7570 : 9
 Total NaN in row 7571 : 2
 Total NaN in row 7572 : 0
 Total NaN in row 7573 : 1
 Total NaN in row 7574 : 10
 Total NaN in row 7575 : 0
 Total NaN in row 7576 : 0
 Total NaN in row 7577 : 2
 Total NaN in row 7578 : 9
 Total NaN in row 7579 : 2
 Total NaN in row 7580 : 9
 Total NaN in row 7581 : 9
 Total NaN in row 7582 : 9
 Total NaN in row 7583 : 0
 Total NaN in row 7584 : 2
 Total NaN in row 7585 : 2
 Total NaN in row 7586 : 1
 Total NaN in row 7587 : 9
 Total NaN in row 7588 : 10
 Total NaN in row 7589 : 2
 Total NaN in row 7590 : 2
 Total NaN in row 7591 : 0
 Total NaN in row 7592 : 9
 Total NaN in row 7593 : 9
 Total NaN in row 7594 : 1
 Total NaN in row 7595 : 2
 Total NaN in row 7596 : 0
 Total NaN in row 7597 : 21
 Total NaN in row 7598 : 9
 Total NaN in row 7599 : 9
 Total NaN in row 7600 : 0
 Total NaN in row 7601 : 0
 Total NaN in row 7602 : 0
 Total NaN in row 7603 : 10
 Total NaN in row 7604 : 2
 Total NaN in row 7605 : 9
 Total NaN in row 7606 : 9
 Total NaN in row 7607 : 1
 Total NaN in row 7608 : 9
 Total NaN in row 7609 : 2
 Total NaN in row 7610 : 9
 Total NaN in row 7611 : 3
 Total NaN in row 7612 : 0
 Total NaN in row 7613 : 1
 Total NaN in row 7614 : 2
 Total NaN in row 7615 : 0
 Total NaN in row 7616 : 7
 Total NaN in row 7617 : 1
 Total NaN in row 7618 : 0
 Total NaN in row 7619 : 2
 Total NaN in row 7620 : 2
 Total NaN in row 7621 : 0
 Total NaN in row 7622 : 9
 Total NaN in row 7623 : 9
 Total NaN in row 7624 : 9
 Total NaN in row 7625 : 0
 Total NaN in row 7626 : 9
 Total NaN in row 7627 : 9
 Total NaN in row 7628 : 0
 Total NaN in row 7629 : 0
 Total NaN in row 7630 : 0
 Total NaN in row 7631 : 1
 Total NaN in row 7632 : 9
 Total NaN in row 7633 : 3
 Total NaN in row 7634 : 0
 Total NaN in row 7635 : 2
 Total NaN in row 7636 : 9
 Total NaN in row 7637 : 9
 Total NaN in row 7638 : 1
 Total NaN in row 7639 : 2
 Total NaN in row 7640 : 10
 Total NaN in row 7641 : 2
 Total NaN in row 7642 : 0
 Total NaN in row 7643 : 2
 Total NaN in row 7644 : 7
 Total NaN in row 7645 : 1
 Total NaN in row 7646 : 2
 Total NaN in row 7647 : 0
 Total NaN in row 7648 : 2
 Total NaN in row 7649 : 2
 Total NaN in row 7650 : 9
 Total NaN in row 7651 : 1
 Total NaN in row 7652 : 1
 Total NaN in row 7653 : 0
 Total NaN in row 7654 : 0
 Total NaN in row 7655 : 0
 Total NaN in row 7656 : 2
 Total NaN in row 7657 : 0
 Total NaN in row 7658 : 2
 Total NaN in row 7659 : 2
 Total NaN in row 7660 : 1
 Total NaN in row 7661 : 2
 Total NaN in row 7662 : 0
 Total NaN in row 7663 : 0
 Total NaN in row 7664 : 9
 Total NaN in row 7665 : 1
 Total NaN in row 7666 : 1
 Total NaN in row 7667 : 3
 Total NaN in row 7668 : 0
 Total NaN in row 7669 : 2
 Total NaN in row 7670 : 0
 Total NaN in row 7671 : 9
 Total NaN in row 7672 : 0
 Total NaN in row 7673 : 2
 Total NaN in row 7674 : 3
 Total NaN in row 7675 : 3
 Total NaN in row 7676 : 0
 Total NaN in row 7677 : 2
 Total NaN in row 7678 : 0
 Total NaN in row 7679 : 0
 Total NaN in row 7680 : 2
 Total NaN in row 7681 : 0
 Total NaN in row 7682 : 9
 Total NaN in row 7683 : 0
 Total NaN in row 7684 : 0
 Total NaN in row 7685 : 2
 Total NaN in row 7686 : 0
 Total NaN in row 7687 : 0
 Total NaN in row 7688 : 9
 Total NaN in row 7689 : 0
 Total NaN in row 7690 : 0
 Total NaN in row 7691 : 1
 Total NaN in row 7692 : 2
 Total NaN in row 7693 : 1
 Total NaN in row 7694 : 0
 Total NaN in row 7695 : 10
 Total NaN in row 7696 : 1
 Total NaN in row 7697 : 2
 Total NaN in row 7698 : 0
 Total NaN in row 7699 : 0
 Total NaN in row 7700 : 2
 Total NaN in row 7701 : 1
 Total NaN in row 7702 : 2
 Total NaN in row 7703 : 0
 Total NaN in row 7704 : 9
 Total NaN in row 7705 : 2
 Total NaN in row 7706 : 0
 Total NaN in row 7707 : 1
 Total NaN in row 7708 : 2
 Total NaN in row 7709 : 0
 Total NaN in row 7710 : 9
 Total NaN in row 7711 : 2
 Total NaN in row 7712 : 2
 Total NaN in row 7713 : 9
 Total NaN in row 7714 : 0
 Total NaN in row 7715 : 0
 Total NaN in row 7716 : 0
 Total NaN in row 7717 : 2
 Total NaN in row 7718 : 0
 Total NaN in row 7719 : 0
 Total NaN in row 7720 : 3
 Total NaN in row 7721 : 0
 Total NaN in row 7722 : 0
 Total NaN in row 7723 : 1
 Total NaN in row 7724 : 3
 Total NaN in row 7725 : 0
 Total NaN in row 7726 : 2
 Total NaN in row 7727 : 9
 Total NaN in row 7728 : 2
 Total NaN in row 7729 : 0
 Total NaN in row 7730 : 0
 Total NaN in row 7731 : 2
 Total NaN in row 7732 : 0
 Total NaN in row 7733 : 0
 Total NaN in row 7734 : 2
 Total NaN in row 7735 : 9
 Total NaN in row 7736 : 9
 Total NaN in row 7737 : 9
 Total NaN in row 7738 : 1
 Total NaN in row 7739 : 9
 Total NaN in row 7740 : 0
 Total NaN in row 7741 : 0
 Total NaN in row 7742 : 1
 Total NaN in row 7743 : 0
 Total NaN in row 7744 : 21
 Total NaN in row 7745 : 0
 Total NaN in row 7746 : 2
 Total NaN in row 7747 : 3
 Total NaN in row 7748 : 8
 Total NaN in row 7749 : 2
 Total NaN in row 7750 : 9
 Total NaN in row 7751 : 1
 Total NaN in row 7752 : 2
 Total NaN in row 7753 : 9
 Total NaN in row 7754 : 0
 Total NaN in row 7755 : 9
 Total NaN in row 7756 : 0
 Total NaN in row 7757 : 9
 Total NaN in row 7758 : 9
 Total NaN in row 7759 : 3
 Total NaN in row 7760 : 21
 Total NaN in row 7761 : 2
 Total NaN in row 7762 : 3
 Total NaN in row 7763 : 21
 Total NaN in row 7764 : 2
 Total NaN in row 7765 : 0
 Total NaN in row 7766 : 1
 Total NaN in row 7767 : 0
 Total NaN in row 7768 : 0
 Total NaN in row 7769 : 1
 Total NaN in row 7770 : 2
 Total NaN in row 7771 : 0
 Total NaN in row 7772 : 10
 Total NaN in row 7773 : 2
 Total NaN in row 7774 : 9
 Total NaN in row 7775 : 0
 Total NaN in row 7776 : 21
 Total NaN in row 7777 : 0
 Total NaN in row 7778 : 10
 Total NaN in row 7779 : 0
 Total NaN in row 7780 : 10
 Total NaN in row 7781 : 2
 Total NaN in row 7782 : 9
 Total NaN in row 7783 : 9
 Total NaN in row 7784 : 0
 Total NaN in row 7785 : 0
 Total NaN in row 7786 : 2
 Total NaN in row 7787 : 1
 Total NaN in row 7788 : 3
 Total NaN in row 7789 : 3
 Total NaN in row 7790 : 0
 Total NaN in row 7791 : 1
 Total NaN in row 7792 : 2
 Total NaN in row 7793 : 9
 Total NaN in row 7794 : 0
 Total NaN in row 7795 : 9
 Total NaN in row 7796 : 2
 Total NaN in row 7797 : 9
 Total NaN in row 7798 : 0
 Total NaN in row 7799 : 0
 Total NaN in row 7800 : 0
 Total NaN in row 7801 : 2
 Total NaN in row 7802 : 2
 Total NaN in row 7803 : 9
 Total NaN in row 7804 : 2
 Total NaN in row 7805 : 0
 Total NaN in row 7806 : 0
 Total NaN in row 7807 : 9
 Total NaN in row 7808 : 0
 Total NaN in row 7809 : 0
 Total NaN in row 7810 : 0
 Total NaN in row 7811 : 1
 Total NaN in row 7812 : 1
 Total NaN in row 7813 : 2
 Total NaN in row 7814 : 0
 Total NaN in row 7815 : 9
 Total NaN in row 7816 : 3
 Total NaN in row 7817 : 2
 Total NaN in row 7818 : 2
 Total NaN in row 7819 : 0
 Total NaN in row 7820 : 1
 Total NaN in row 7821 : 0
 Total NaN in row 7822 : 3
 Total NaN in row 7823 : 2
 Total NaN in row 7824 : 9
 Total NaN in row 7825 : 9
 Total NaN in row 7826 : 1
 Total NaN in row 7827 : 1
 Total NaN in row 7828 : 2
 Total NaN in row 7829 : 9
 Total NaN in row 7830 : 9
 Total NaN in row 7831 : 2
 Total NaN in row 7832 : 0
 Total NaN in row 7833 : 0
 Total NaN in row 7834 : 10
 Total NaN in row 7835 : 0
 Total NaN in row 7836 : 1
 Total NaN in row 7837 : 0
 Total NaN in row 7838 : 0
 Total NaN in row 7839 : 0
 Total NaN in row 7840 : 3
 Total NaN in row 7841 : 2
 Total NaN in row 7842 : 2
 Total NaN in row 7843 : 0
 Total NaN in row 7844 : 9
 Total NaN in row 7845 : 1
 Total NaN in row 7846 : 0
 Total NaN in row 7847 : 0

 Total NaN in row 7848 : 0
 Total NaN in row 7849 : 0
 Total NaN in row 7850 : 1
 Total NaN in row 7851 : 0
 Total NaN in row 7852 : 0
 Total NaN in row 7853 : 0
 Total NaN in row 7854 : 0
 Total NaN in row 7855 : 0
 Total NaN in row 7856 : 1
 Total NaN in row 7857 : 3
 Total NaN in row 7858 : 10
 Total NaN in row 7859 : 0
 Total NaN in row 7860 : 1
 Total NaN in row 7861 : 1
 Total NaN in row 7862 : 2
 Total NaN in row 7863 : 2
 Total NaN in row 7864 : 0
 Total NaN in row 7865 : 0
 Total NaN in row 7866 : 0
 Total NaN in row 7867 : 2
 Total NaN in row 7868 : 2
 Total NaN in row 7869 : 1
 Total NaN in row 7870 : 1
 Total NaN in row 7871 : 0
 Total NaN in row 7872 : 2
 Total NaN in row 7873 : 1
 Total NaN in row 7874 : 0
 Total NaN in row 7875 : 9
 Total NaN in row 7876 : 0
 Total NaN in row 7877 : 1
 Total NaN in row 7878 : 1
 Total NaN in row 7879 : 1
 Total NaN in row 7880 : 0
 Total NaN in row 7881 : 0
 Total NaN in row 7882 : 9
 Total NaN in row 7883 : 9
 Total NaN in row 7884 : 0
 Total NaN in row 7885 : 1
 Total NaN in row 7886 : 0
 Total NaN in row 7887 : 2
 Total NaN in row 7888 : 1
 Total NaN in row 7889 : 9
 Total NaN in row 7890 : 0
 Total NaN in row 7891 : 0
 Total NaN in row 7892 : 0
 Total NaN in row 7893 : 0
 Total NaN in row 7894 : 1
 Total NaN in row 7895 : 2
 Total NaN in row 7896 : 2
 Total NaN in row 7897 : 0
 Total NaN in row 7898 : 1
 Total NaN in row 7899 : 0
 Total NaN in row 7900 : 1
 Total NaN in row 7901 : 10
 Total NaN in row 7902 : 2
 Total NaN in row 7903 : 9
 Total NaN in row 7904 : 9
 Total NaN in row 7905 : 2
 Total NaN in row 7906 : 0
 Total NaN in row 7907 : 2
 Total NaN in row 7908 : 1
 Total NaN in row 7909 : 0
 Total NaN in row 7910 : 1
 Total NaN in row 7911 : 9
 Total NaN in row 7912 : 9
 Total NaN in row 7913 : 0
 Total NaN in row 7914 : 3
 Total NaN in row 7915 : 2
 Total NaN in row 7916 : 10
 Total NaN in row 7917 : 9
 Total NaN in row 7918 : 1
 Total NaN in row 7919 : 2
 Total NaN in row 7920 : 0
 Total NaN in row 7921 : 7
 Total NaN in row 7922 : 2
 Total NaN in row 7923 : 2
 Total NaN in row 7924 : 0
 Total NaN in row 7925 : 2
 Total NaN in row 7926 : 0
 Total NaN in row 7927 : 0
 Total NaN in row 7928 : 1
 Total NaN in row 7929 : 2
 Total NaN in row 7930 : 2
 Total NaN in row 7931 : 1
 Total NaN in row 7932 : 2
 Total NaN in row 7933 : 0
 Total NaN in row 7934 : 1
 Total NaN in row 7935 : 1
 Total NaN in row 7936 : 0
 Total NaN in row 7937 : 0
 Total NaN in row 7938 : 0
 Total NaN in row 7939 : 2
 Total NaN in row 7940 : 9
 Total NaN in row 7941 : 2
 Total NaN in row 7942 : 2
 Total NaN in row 7943 : 1
 Total NaN in row 7944 : 2
 Total NaN in row 7945 : 1
 Total NaN in row 7946 : 2
 Total NaN in row 7947 : 2
 Total NaN in row 7948 : 1
 Total NaN in row 7949 : 1
 Total NaN in row 7950 : 3
 Total NaN in row 7951 : 0
 Total NaN in row 7952 : 0
 Total NaN in row 7953 : 2
 Total NaN in row 7954 : 0
 Total NaN in row 7955 : 2
 Total NaN in row 7956 : 9
 Total NaN in row 7957 : 9
 Total NaN in row 7958 : 2
 Total NaN in row 7959 : 2
 Total NaN in row 7960 : 1
 Total NaN in row 7961 : 1
 Total NaN in row 7962 : 0
 Total NaN in row 7963 : 1
 Total NaN in row 7964 : 10
 Total NaN in row 7965 : 3
 Total NaN in row 7966 : 9
 Total NaN in row 7967 : 9
 Total NaN in row 7968 : 1
 Total NaN in row 7969 : 0
 Total NaN in row 7970 : 2
 Total NaN in row 7971 : 0
 Total NaN in row 7972 : 1
 Total NaN in row 7973 : 0
 Total NaN in row 7974 : 2
 Total NaN in row 7975 : 0
 Total NaN in row 7976 : 1
 Total NaN in row 7977 : 0
 Total NaN in row 7978 : 0
 Total NaN in row 7979 : 3
 Total NaN in row 7980 : 3
 Total NaN in row 7981 : 2
 Total NaN in row 7982 : 3
 Total NaN in row 7983 : 1
 Total NaN in row 7984 : 1
 Total NaN in row 7985 : 0
 Total NaN in row 7986 : 9
 Total NaN in row 7987 : 0
 Total NaN in row 7988 : 2
 Total NaN in row 7989 : 9
 Total NaN in row 7990 : 2
 Total NaN in row 7991 : 3
 Total NaN in row 7992 : 3
 Total NaN in row 7993 : 3
 Total NaN in row 7994 : 2
 Total NaN in row 7995 : 0
 Total NaN in row 7996 : 9
 Total NaN in row 7997 : 0
 Total NaN in row 7998 : 0
 Total NaN in row 7999 : 0
 Total NaN in row 8000 : 1
 Total NaN in row 8001 : 3
 Total NaN in row 8002 : 1
 Total NaN in row 8003 : 1
 Total NaN in row 8004 : 0
 Total NaN in row 8005 : 1
 Total NaN in row 8006 : 9
 Total NaN in row 8007 : 0
 Total NaN in row 8008 : 1
 Total NaN in row 8009 : 2
 Total NaN in row 8010 : 0
 Total NaN in row 8011 : 1
 Total NaN in row 8012 : 0
 Total NaN in row 8013 : 9
 Total NaN in row 8014 : 0
 Total NaN in row 8015 : 0
 Total NaN in row 8016 : 1
 Total NaN in row 8017 : 2
 Total NaN in row 8018 : 3
 Total NaN in row 8019 : 0
 Total NaN in row 8020 : 2
 Total NaN in row 8021 : 3
 Total NaN in row 8022 : 1
 Total NaN in row 8023 : 0
 Total NaN in row 8024 : 0
 Total NaN in row 8025 : 10
 Total NaN in row 8026 : 1
 Total NaN in row 8027 : 0
 Total NaN in row 8028 : 1
 Total NaN in row 8029 : 3
 Total NaN in row 8030 : 1
 Total NaN in row 8031 : 2
 Total NaN in row 8032 : 1
 Total NaN in row 8033 : 2
 Total NaN in row 8034 : 2
 Total NaN in row 8035 : 0
 Total NaN in row 8036 : 0
 Total NaN in row 8037 : 2
 Total NaN in row 8038 : 10
 Total NaN in row 8039 : 0
 Total NaN in row 8040 : 1
 Total NaN in row 8041 : 0
 Total NaN in row 8042 : 9
 Total NaN in row 8043 : 1
 Total NaN in row 8044 : 3
 Total NaN in row 8045 : 9
 Total NaN in row 8046 : 2
 Total NaN in row 8047 : 2
 Total NaN in row 8048 : 1
 Total NaN in row 8049 : 9
 Total NaN in row 8050 : 10
 Total NaN in row 8051 : 2
 Total NaN in row 8052 : 0
 Total NaN in row 8053 : 1
 Total NaN in row 8054 : 2
 Total NaN in row 8055 : 21
 Total NaN in row 8056 : 3
 Total NaN in row 8057 : 3
 Total NaN in row 8058 : 9
 Total NaN in row 8059 : 2
 Total NaN in row 8060 : 9
 Total NaN in row 8061 : 1
 Total NaN in row 8062 : 3
 Total NaN in row 8063 : 10
 Total NaN in row 8064 : 0
 Total NaN in row 8065 : 2
 Total NaN in row 8066 : 3
 Total NaN in row 8067 : 2
 Total NaN in row 8068 : 10
 Total NaN in row 8069 : 3
 Total NaN in row 8070 : 9
 Total NaN in row 8071 : 10
 Total NaN in row 8072 : 0
 Total NaN in row 8073 : 10
 Total NaN in row 8074 : 10
 Total NaN in row 8075 : 2
 Total NaN in row 8076 : 10
 Total NaN in row 8077 : 1
 Total NaN in row 8078 : 1
 Total NaN in row 8079 : 9
 Total NaN in row 8080 : 1
 Total NaN in row 8081 : 0
 Total NaN in row 8082 : 0
 Total NaN in row 8083 : 1
 Total NaN in row 8084 : 3
 Total NaN in row 8085 : 2
 Total NaN in row 8086 : 2
 Total NaN in row 8087 : 10
 Total NaN in row 8088 : 9
 Total NaN in row 8089 : 0
 Total NaN in row 8090 : 3
 Total NaN in row 8091 : 9
 Total NaN in row 8092 : 1
 Total NaN in row 8093 : 1
 Total NaN in row 8094 : 2
 Total NaN in row 8095 : 0
 Total NaN in row 8096 : 21
 Total NaN in row 8097 : 1
 Total NaN in row 8098 : 3
 Total NaN in row 8099 : 2
 Total NaN in row 8100 : 5
 Total NaN in row 8101 : 10
 Total NaN in row 8102 : 0
 Total NaN in row 8103 : 0
 Total NaN in row 8104 : 3
 Total NaN in row 8105 : 1
 Total NaN in row 8106 : 0
 Total NaN in row 8107 : 0
 Total NaN in row 8108 : 9
 Total NaN in row 8109 : 9
 Total NaN in row 8110 : 3
 Total NaN in row 8111 : 3
 Total NaN in row 8112 : 0
 Total NaN in row 8113 : 1
 Total NaN in row 8114 : 1
 Total NaN in row 8115 : 2
 Total NaN in row 8116 : 9
 Total NaN in row 8117 : 3
 Total NaN in row 8118 : 1
 Total NaN in row 8119 : 21
 Total NaN in row 8120 : 1
 Total NaN in row 8121 : 3
 Total NaN in row 8122 : 10
 Total NaN in row 8123 : 3
 Total NaN in row 8124 : 0
 Total NaN in row 8125 : 0
 Total NaN in row 8126 : 0
 Total NaN in row 8127 : 1
 Total NaN in row 8128 : 3
 Total NaN in row 8129 : 3
 Total NaN in row 8130 : 10
 Total NaN in row 8131 : 1
 Total NaN in row 8132 : 3
 Total NaN in row 8133 : 0
 Total NaN in row 8134 : 9
 Total NaN in row 8135 : 1
 Total NaN in row 8136 : 9
 Total NaN in row 8137 : 9
 Total NaN in row 8138 : 0
 Total NaN in row 8139 : 0
 Total NaN in row 8140 : 0
 Total NaN in row 8141 : 2
 Total NaN in row 8142 : 1
 Total NaN in row 8143 : 10
 Total NaN in row 8144 : 0
 Total NaN in row 8145 : 2
 Total NaN in row 8146 : 3
 Total NaN in row 8147 : 0
 Total NaN in row 8148 : 2
 Total NaN in row 8149 : 2
 Total NaN in row 8150 : 3
 Total NaN in row 8151 : 0
 Total NaN in row 8152 : 2
 Total NaN in row 8153 : 3
 Total NaN in row 8154 : 0
 Total NaN in row 8155 : 2
 Total NaN in row 8156 : 0
 Total NaN in row 8157 : 1
 Total NaN in row 8158 : 9
 Total NaN in row 8159 : 2
 Total NaN in row 8160 : 9
 Total NaN in row 8161 : 2
 Total NaN in row 8162 : 2
 Total NaN in row 8163 : 2
 Total NaN in row 8164 : 0
 Total NaN in row 8165 : 10
 Total NaN in row 8166 : 9
 Total NaN in row 8167 : 2
 Total NaN in row 8168 : 2
 Total NaN in row 8169 : 2
 Total NaN in row 8170 : 1
 Total NaN in row 8171 : 2
 Total NaN in row 8172 : 0
 Total NaN in row 8173 : 1
 Total NaN in row 8174 : 0
 Total NaN in row 8175 : 1

 Total NaN in row 8176 : 1
 Total NaN in row 8177 : 9
 Total NaN in row 8178 : 0
 Total NaN in row 8179 : 1
 Total NaN in row 8180 : 2
 Total NaN in row 8181 : 0
 Total NaN in row 8182 : 9
 Total NaN in row 8183 : 2
 Total NaN in row 8184 : 2
 Total NaN in row 8185 : 1
 Total NaN in row 8186 : 10
 Total NaN in row 8187 : 9
 Total NaN in row 8188 : 3
 Total NaN in row 8189 : 1
 Total NaN in row 8190 : 0
 Total NaN in row 8191 : 21
 Total NaN in row 8192 : 2
 Total NaN in row 8193 : 1
 Total NaN in row 8194 : 0
 Total NaN in row 8195 : 0
 Total NaN in row 8196 : 9
 Total NaN in row 8197 : 2
 Total NaN in row 8198 : 1
 Total NaN in row 8199 : 9
 Total NaN in row 8200 : 2
 Total NaN in row 8201 : 0
 Total NaN in row 8202 : 2
 Total NaN in row 8203 : 0
 Total NaN in row 8204 : 9
 Total NaN in row 8205 : 9
 Total NaN in row 8206 : 9
 Total NaN in row 8207 : 2
 Total NaN in row 8208 : 2
 Total NaN in row 8209 : 2
 Total NaN in row 8210 : 9
 Total NaN in row 8211 : 9
 Total NaN in row 8212 : 0
 Total NaN in row 8213 : 2
 Total NaN in row 8214 : 0
 Total NaN in row 8215 : 9
 Total NaN in row 8216 : 1
 Total NaN in row 8217 : 1
 Total NaN in row 8218 : 2
 Total NaN in row 8219 : 1
 Total NaN in row 8220 : 2
 Total NaN in row 8221 : 2
 Total NaN in row 8222 : 1
 Total NaN in row 8223 : 2
 Total NaN in row 8224 : 0
 Total NaN in row 8225 : 9
 Total NaN in row 8226 : 1
 Total NaN in row 8227 : 2
 Total NaN in row 8228 : 0
 Total NaN in row 8229 : 1
 Total NaN in row 8230 : 1
 Total NaN in row 8231 : 9
 Total NaN in row 8232 : 2
 Total NaN in row 8233 : 2
 Total NaN in row 8234 : 1
 Total NaN in row 8235 : 9
 Total NaN in row 8236 : 2
 Total NaN in row 8237 : 2
 Total NaN in row 8238 : 0
 Total NaN in row 8239 : 9
 Total NaN in row 8240 : 2
 Total NaN in row 8241 : 0
 Total NaN in row 8242 : 2
 Total NaN in row 8243 : 2
 Total NaN in row 8244 : 2
 Total NaN in row 8245 : 0
 Total NaN in row 8246 : 0
 Total NaN in row 8247 : 0
 Total NaN in row 8248 : 0
 Total NaN in row 8249 : 1
 Total NaN in row 8250 : 2
 Total NaN in row 8251 : 2
 Total NaN in row 8252 : 2
 Total NaN in row 8253 : 2
 Total NaN in row 8254 : 0
 Total NaN in row 8255 : 3
 Total NaN in row 8256 : 0
 Total NaN in row 8257 : 9
 Total NaN in row 8258 : 0
 Total NaN in row 8259 : 2
 Total NaN in row 8260 : 0
 Total NaN in row 8261 : 3
 Total NaN in row 8262 : 2
 Total NaN in row 8263 : 9
 Total NaN in row 8264 : 1
 Total NaN in row 8265 : 1
 Total NaN in row 8266 : 9
 Total NaN in row 8267 : 0
 Total NaN in row 8268 : 2
 Total NaN in row 8269 : 9
 Total NaN in row 8270 : 2
 Total NaN in row 8271 : 2
 Total NaN in row 8272 : 0
 Total NaN in row 8273 : 0
 Total NaN in row 8274 : 2
 Total NaN in row 8275 : 0
 Total NaN in row 8276 : 0
 Total NaN in row 8277 : 0
 Total NaN in row 8278 : 0
 Total NaN in row 8279 : 0
 Total NaN in row 8280 : 2
 Total NaN in row 8281 : 2
 Total NaN in row 8282 : 2
 Total NaN in row 8283 : 2
 Total NaN in row 8284 : 1
 Total NaN in row 8285 : 1
 Total NaN in row 8286 : 0
 Total NaN in row 8287 : 9
 Total NaN in row 8288 : 3
 Total NaN in row 8289 : 0
 Total NaN in row 8290 : 2
 Total NaN in row 8291 : 0
 Total NaN in row 8292 : 1
 Total NaN in row 8293 : 0
 Total NaN in row 8294 : 2
 Total NaN in row 8295 : 9
 Total NaN in row 8296 : 10
 Total NaN in row 8297 : 2
 Total NaN in row 8298 : 2
 Total NaN in row 8299 : 1
 Total NaN in row 8300 : 3
 Total NaN in row 8301 : 9
 Total NaN in row 8302 : 0
 Total NaN in row 8303 : 0
 Total NaN in row 8304 : 2
 Total NaN in row 8305 : 0
 Total NaN in row 8306 : 10
 Total NaN in row 8307 : 1
 Total NaN in row 8308 : 2
 Total NaN in row 8309 : 2
 Total NaN in row 8310 : 9
 Total NaN in row 8311 : 0
 Total NaN in row 8312 : 2
 Total NaN in row 8313 : 0
 Total NaN in row 8314 : 0
 Total NaN in row 8315 : 9
 Total NaN in row 8316 : 2
 Total NaN in row 8317 : 1
 Total NaN in row 8318 : 9
 Total NaN in row 8319 : 1
 Total NaN in row 8320 : 0
 Total NaN in row 8321 : 9
 Total NaN in row 8322 : 0
 Total NaN in row 8323 : 0
 Total NaN in row 8324 : 1
 Total NaN in row 8325 : 2
 Total NaN in row 8326 : 9
 Total NaN in row 8327 : 0
 Total NaN in row 8328 : 0
 Total NaN in row 8329 : 2
 Total NaN in row 8330 : 0
 Total NaN in row 8331 : 0
 Total NaN in row 8332 : 2
 Total NaN in row 8333 : 2
 Total NaN in row 8334 : 0
 Total NaN in row 8335 : 0
 Total NaN in row 8336 : 0
 Total NaN in row 8337 : 2
 Total NaN in row 8338 : 0
 Total NaN in row 8339 : 2
 Total NaN in row 8340 : 2
 Total NaN in row 8341 : 2
 Total NaN in row 8342 : 9
 Total NaN in row 8343 : 0
 Total NaN in row 8344 : 2
 Total NaN in row 8345 : 10
 Total NaN in row 8346 : 2
 Total NaN in row 8347 : 2
 Total NaN in row 8348 : 1
 Total NaN in row 8349 : 1
 Total NaN in row 8350 : 0
 Total NaN in row 8351 : 0
 Total NaN in row 8352 : 1
 Total NaN in row 8353 : 1
 Total NaN in row 8354 : 1
 Total NaN in row 8355 : 2
 Total NaN in row 8356 : 2
 Total NaN in row 8357 : 2
 Total NaN in row 8358 : 0
 Total NaN in row 8359 : 0
 Total NaN in row 8360 : 1
 Total NaN in row 8361 : 9
 Total NaN in row 8362 : 0
 Total NaN in row 8363 : 10
 Total NaN in row 8364 : 0
 Total NaN in row 8365 : 0
 Total NaN in row 8366 : 9
 Total NaN in row 8367 : 9
 Total NaN in row 8368 : 9
 Total NaN in row 8369 : 0
 Total NaN in row 8370 : 2
 Total NaN in row 8371 : 0
 Total NaN in row 8372 : 0
 Total NaN in row 8373 : 9
 Total NaN in row 8374 : 9
 Total NaN in row 8375 : 2
 Total NaN in row 8376 : 0
 Total NaN in row 8377 : 10
 Total NaN in row 8378 : 9
 Total NaN in row 8379 : 9
 Total NaN in row 8380 : 9
 Total NaN in row 8381 : 1
 Total NaN in row 8382 : 0
 Total NaN in row 8383 : 9
 Total NaN in row 8384 : 0
 Total NaN in row 8385 : 9
 Total NaN in row 8386 : 9
 Total NaN in row 8387 : 0
 Total NaN in row 8388 : 0
 Total NaN in row 8389 : 0
 Total NaN in row 8390 : 0
 Total NaN in row 8391 : 9
 Total NaN in row 8392 : 3
 Total NaN in row 8393 : 1
 Total NaN in row 8394 : 2
 Total NaN in row 8395 : 0
 Total NaN in row 8396 : 0
 Total NaN in row 8397 : 9
 Total NaN in row 8398 : 0
 Total NaN in row 8399 : 2
 Total NaN in row 8400 : 9
 Total NaN in row 8401 : 9
 Total NaN in row 8402 : 1
 Total NaN in row 8403 : 0
 Total NaN in row 8404 : 2
 Total NaN in row 8405 : 2
 Total NaN in row 8406 : 9
 Total NaN in row 8407 : 9
 Total NaN in row 8408 : 9
 Total NaN in row 8409 : 0
 Total NaN in row 8410 : 21
 Total NaN in row 8411 : 1
 Total NaN in row 8412 : 9
 Total NaN in row 8413 : 2
 Total NaN in row 8414 : 0
 Total NaN in row 8415 : 0
 Total NaN in row 8416 : 10
 Total NaN in row 8417 : 0
 Total NaN in row 8418 : 3
 Total NaN in row 8419 : 2
 Total NaN in row 8420 : 0
 Total NaN in row 8421 : 0
 Total NaN in row 8422 : 10
 Total NaN in row 8423 : 0
 Total NaN in row 8424 : 2
 Total NaN in row 8425 : 0
 Total NaN in row 8426 : 2
 Total NaN in row 8427 : 0
 Total NaN in row 8428 : 2
 Total NaN in row 8429 : 9
 Total NaN in row 8430 : 9
 Total NaN in row 8431 : 9
 Total NaN in row 8432 : 9
 Total NaN in row 8433 : 0
 Total NaN in row 8434 : 0
 Total NaN in row 8435 : 0
 Total NaN in row 8436 : 10
 Total NaN in row 8437 : 0
 Total NaN in row 8438 : 2
 Total NaN in row 8439 : 0
 Total NaN in row 8440 : 2
 Total NaN in row 8441 : 2
 Total NaN in row 8442 : 2
 Total NaN in row 8443 : 2
 Total NaN in row 8444 : 2
 Total NaN in row 8445 : 0
 Total NaN in row 8446 : 0
 Total NaN in row 8447 : 1
 Total NaN in row 8448 : 2
 Total NaN in row 8449 : 1
 Total NaN in row 8450 : 0
 Total NaN in row 8451 : 2
 Total NaN in row 8452 : 0
 Total NaN in row 8453 : 7
 Total NaN in row 8454 : 0
 Total NaN in row 8455 : 10
 Total NaN in row 8456 : 9
 Total NaN in row 8457 : 2
 Total NaN in row 8458 : 1
 Total NaN in row 8459 : 0
 Total NaN in row 8460 : 0
 Total NaN in row 8461 : 0
 Total NaN in row 8462 : 2
 Total NaN in row 8463 : 2
 Total NaN in row 8464 : 0
 Total NaN in row 8465 : 0
 Total NaN in row 8466 : 9
 Total NaN in row 8467 : 1
 Total NaN in row 8468 : 9
 Total NaN in row 8469 : 1
 Total NaN in row 8470 : 2
 Total NaN in row 8471 : 0
 Total NaN in row 8472 : 9
 Total NaN in row 8473 : 2
 Total NaN in row 8474 : 9
 Total NaN in row 8475 : 9
 Total NaN in row 8476 : 9
 Total NaN in row 8477 : 0
 Total NaN in row 8478 : 2
 Total NaN in row 8479 : 0
 Total NaN in row 8480 : 9
 Total NaN in row 8481 : 2
 Total NaN in row 8482 : 0
 Total NaN in row 8483 : 2
 Total NaN in row 8484 : 9
 Total NaN in row 8485 : 1
 Total NaN in row 8486 : 1
 Total NaN in row 8487 : 2
 Total NaN in row 8488 : 10
 Total NaN in row 8489 : 0
 Total NaN in row 8490 : 0
 Total NaN in row 8491 : 0
 Total NaN in row 8492 : 1
 Total NaN in row 8493 : 1
 Total NaN in row 8494 : 10
 Total NaN in row 8495 : 1
 Total NaN in row 8496 : 1
 Total NaN in row 8497 : 0
 Total NaN in row 8498 : 9
 Total NaN in row 8499 : 9
 Total NaN in row 8500 : 0
 Total NaN in row 8501 : 0
 Total NaN in row 8502 : 21
 Total NaN in row 8503 : 0
 Total NaN in row 8504 : 9
 Total NaN in row 8505 : 0
 Total NaN in row 8506 : 1
 Total NaN in row 8507 : 9
 Total NaN in row 8508 : 2
 Total NaN in row 8509 : 0
 Total NaN in row 8510 : 2
 Total NaN in row 8511 : 9
 Total NaN in row 8512 : 9
 Total NaN in row 8513 : 2
 Total NaN in row 8514 : 2
 Total NaN in row 8515 : 0
 Total NaN in row 8516 : 2
 Total NaN in row 8517 : 0
 Total NaN in row 8518 : 2
 Total NaN in row 8519 : 9
 Total NaN in row 8520 : 10
 Total NaN in row 8521 : 9
 Total NaN in row 8522 : 9
 Total NaN in row 8523 : 2
 Total NaN in row 8524 : 1
 Total NaN in row 8525 : 3
 Total NaN in row 8526 : 0
 Total NaN in row 8527 : 9
 Total NaN in row 8528 : 0
 Total NaN in row 8529 : 2
 Total NaN in row 8530 : 2
 Total NaN in row 8531 : 9
 Total NaN in row 8532 : 1
 Total NaN in row 8533 : 0
 Total NaN in row 8534 : 2
 Total NaN in row 8535 : 9
 Total NaN in row 8536 : 9
 Total NaN in row 8537 : 0
 Total NaN in row 8538 : 0
 Total NaN in row 8539 : 2
 Total NaN in row 8540 : 1
 Total NaN in row 8541 : 1
 Total NaN in row 8542 : 2
 Total NaN in row 8543 : 9
 Total NaN in row 8544 : 1
 Total NaN in row 8545 : 9
 Total NaN in row 8546 : 3
 Total NaN in row 8547 : 2
 Total NaN in row 8548 : 0
 Total NaN in row 8549 : 9
 Total NaN in row 8550 : 9
 Total NaN in row 8551 : 2
 Total NaN in row 8552 : 9
 Total NaN in row 8553 : 2
 Total NaN in row 8554 : 1
 Total NaN in row 8555 : 0
 Total NaN in row 8556 : 0
 Total NaN in row 8557 : 0
 Total NaN in row 8558 : 0
 Total NaN in row 8559 : 9
 Total NaN in row 8560 : 9
 Total NaN in row 8561 : 0
 Total NaN in row 8562 : 10
 Total NaN in row 8563 : 0
 Total NaN in row 8564 : 1
 Total NaN in row 8565 : 0

 Total NaN in row 8566 : 2
 Total NaN in row 8567 : 9
 Total NaN in row 8568 : 2
 Total NaN in row 8569 : 0
 Total NaN in row 8570 : 9
 Total NaN in row 8571 : 2
 Total NaN in row 8572 : 0
 Total NaN in row 8573 : 9
 Total NaN in row 8574 : 0
 Total NaN in row 8575 : 10
 Total NaN in row 8576 : 10
 Total NaN in row 8577 : 9
 Total NaN in row 8578 : 9
 Total NaN in row 8579 : 1
 Total NaN in row 8580 : 9
 Total NaN in row 8581 : 9
 Total NaN in row 8582 : 9
 Total NaN in row 8583 : 3
 Total NaN in row 8584 : 0
 Total NaN in row 8585 : 0
 Total NaN in row 8586 : 0
 Total NaN in row 8587 : 0
 Total NaN in row 8588 : 3
 Total NaN in row 8589 : 9
 Total NaN in row 8590 : 9
 Total NaN in row 8591 : 2
 Total NaN in row 8592 : 9
 Total NaN in row 8593 : 9
 Total NaN in row 8594 : 2
 Total NaN in row 8595 : 10
 Total NaN in row 8596 : 0
 Total NaN in row 8597 : 2
 Total NaN in row 8598 : 9
 Total NaN in row 8599 : 2
 Total NaN in row 8600 : 0
 Total NaN in row 8601 : 9
 Total NaN in row 8602 : 2
 Total NaN in row 8603 : 2
 Total NaN in row 8604 : 0
 Total NaN in row 8605 : 9
 Total NaN in row 8606 : 9
 Total NaN in row 8607 : 0
 Total NaN in row 8608 : 9
 Total NaN in row 8609 : 0
 Total NaN in row 8610 : 2
 Total NaN in row 8611 : 9
 Total NaN in row 8612 : 9
 Total NaN in row 8613 : 0
 Total NaN in row 8614 : 3
 Total NaN in row 8615 : 2
 Total NaN in row 8616 : 1
 Total NaN in row 8617 : 9
 Total NaN in row 8618 : 2
 Total NaN in row 8619 : 0
 Total NaN in row 8620 : 9
 Total NaN in row 8621 : 9
 Total NaN in row 8622 : 0
 Total NaN in row 8623 : 1
 Total NaN in row 8624 : 7
 Total NaN in row 8625 : 9
 Total NaN in row 8626 : 10
 Total NaN in row 8627 : 0
 Total NaN in row 8628 : 2
 Total NaN in row 8629 : 0
 Total NaN in row 8630 : 0
 Total NaN in row 8631 : 0
 Total NaN in row 8632 : 9
 Total NaN in row 8633 : 2
 Total NaN in row 8634 : 0
 Total NaN in row 8635 : 9
 Total NaN in row 8636 : 0
 Total NaN in row 8637 : 9
 Total NaN in row 8638 : 9
 Total NaN in row 8639 : 10
 Total NaN in row 8640 : 0
 Total NaN in row 8641 : 0
 Total NaN in row 8642 : 9
 Total NaN in row 8643 : 0
 Total NaN in row 8644 : 0
 Total NaN in row 8645 : 2
 Total NaN in row 8646 : 2
 Total NaN in row 8647 : 0
 Total NaN in row 8648 : 0
 Total NaN in row 8649 : 9
 Total NaN in row 8650 : 9
 Total NaN in row 8651 : 1
 Total NaN in row 8652 : 2
 Total NaN in row 8653 : 21
 Total NaN in row 8654 : 1
 Total NaN in row 8655 : 2
 Total NaN in row 8656 : 2
 Total NaN in row 8657 : 9
 Total NaN in row 8658 : 2
 Total NaN in row 8659 : 2
 Total NaN in row 8660 : 9
 Total NaN in row 8661 : 1
 Total NaN in row 8662 : 9
 Total NaN in row 8663 : 9
 Total NaN in row 8664 : 2
 Total NaN in row 8665 : 2
 Total NaN in row 8666 : 10
 Total NaN in row 8667 : 2
 Total NaN in row 8668 : 9
 Total NaN in row 8669 : 2
 Total NaN in row 8670 : 2
 Total NaN in row 8671 : 9
 Total NaN in row 8672 : 3
 Total NaN in row 8673 : 9
 Total NaN in row 8674 : 1
 Total NaN in row 8675 : 1
 Total NaN in row 8676 : 0
 Total NaN in row 8677 : 0
 Total NaN in row 8678 : 9
 Total NaN in row 8679 : 2
 Total NaN in row 8680 : 10
 Total NaN in row 8681 : 0
 Total NaN in row 8682 : 9
 Total NaN in row 8683 : 1
 Total NaN in row 8684 : 0
 Total NaN in row 8685 : 2
 Total NaN in row 8686 : 9
 Total NaN in row 8687 : 0
 Total NaN in row 8688 : 10
 Total NaN in row 8689 : 9
 Total NaN in row 8690 : 9
 Total NaN in row 8691 : 2
 Total NaN in row 8692 : 0
 Total NaN in row 8693 : 2
 Total NaN in row 8694 : 9
 Total NaN in row 8695 : 2
 Total NaN in row 8696 : 1
 Total NaN in row 8697 : 2
 Total NaN in row 8698 : 0
 Total NaN in row 8699 : 0
 Total NaN in row 8700 : 0
 Total NaN in row 8701 : 1
 Total NaN in row 8702 : 0
 Total NaN in row 8703 : 0
 Total NaN in row 8704 : 0
 Total NaN in row 8705 : 9
 Total NaN in row 8706 : 3
 Total NaN in row 8707 : 9
 Total NaN in row 8708 : 9
 Total NaN in row 8709 : 0
 Total NaN in row 8710 : 3
 Total NaN in row 8711 : 2
 Total NaN in row 8712 : 9
 Total NaN in row 8713 : 10
 Total NaN in row 8714 : 0
 Total NaN in row 8715 : 2
 Total NaN in row 8716 : 0
 Total NaN in row 8717 : 9
 Total NaN in row 8718 : 1
 Total NaN in row 8719 : 3
 Total NaN in row 8720 : 9
 Total NaN in row 8721 : 9
 Total NaN in row 8722 : 0
 Total NaN in row 8723 : 9
 Total NaN in row 8724 : 2
 Total NaN in row 8725 : 1
 Total NaN in row 8726 : 2
 Total NaN in row 8727 : 2
 Total NaN in row 8728 : 0
 Total NaN in row 8729 : 2
 Total NaN in row 8730 : 2
 Total NaN in row 8731 : 1
 Total NaN in row 8732 : 9
 Total NaN in row 8733 : 9
 Total NaN in row 8734 : 0
 Total NaN in row 8735 : 0
 Total NaN in row 8736 : 2
 Total NaN in row 8737 : 1
 Total NaN in row 8738 : 9
 Total NaN in row 8739 : 1
 Total NaN in row 8740 : 9
 Total NaN in row 8741 : 0
 Total NaN in row 8742 : 9
 Total NaN in row 8743 : 0
 Total NaN in row 8744 : 0
 Total NaN in row 8745 : 9
 Total NaN in row 8746 : 2
 Total NaN in row 8747 : 9
 Total NaN in row 8748 : 10
 Total NaN in row 8749 : 1
 Total NaN in row 8750 : 1
 Total NaN in row 8751 : 3
 Total NaN in row 8752 : 1
 Total NaN in row 8753 : 10
 Total NaN in row 8754 : 2
 Total NaN in row 8755 : 3
 Total NaN in row 8756 : 9
 Total NaN in row 8757 : 0
 Total NaN in row 8758 : 2
 Total NaN in row 8759 : 2
 Total NaN in row 8760 : 0
 Total NaN in row 8761 : 1
 Total NaN in row 8762 : 2
 Total NaN in row 8763 : 9
 Total NaN in row 8764 : 2
 Total NaN in row 8765 : 1
 Total NaN in row 8766 : 10
 Total NaN in row 8767 : 3
 Total NaN in row 8768 : 0
 Total NaN in row 8769 : 1
 Total NaN in row 8770 : 0
 Total NaN in row 8771 : 0
 Total NaN in row 8772 : 9
 Total NaN in row 8773 : 2
 Total NaN in row 8774 : 2
 Total NaN in row 8775 : 0
 Total NaN in row 8776 : 0
 Total NaN in row 8777 : 2
 Total NaN in row 8778 : 2
 Total NaN in row 8779 : 2
 Total NaN in row 8780 : 0
 Total NaN in row 8781 : 2
 Total NaN in row 8782 : 1
 Total NaN in row 8783 : 9
 Total NaN in row 8784 : 9
 Total NaN in row 8785 : 1
 Total NaN in row 8786 : 1
 Total NaN in row 8787 : 7
 Total NaN in row 8788 : 1
 Total NaN in row 8789 : 7
 Total NaN in row 8790 : 2
 Total NaN in row 8791 : 2
 Total NaN in row 8792 : 1
 Total NaN in row 8793 : 1
 Total NaN in row 8794 : 0
 Total NaN in row 8795 : 1
 Total NaN in row 8796 : 0
 Total NaN in row 8797 : 0
 Total NaN in row 8798 : 3
 Total NaN in row 8799 : 2
 Total NaN in row 8800 : 0
 Total NaN in row 8801 : 2
 Total NaN in row 8802 : 0
 Total NaN in row 8803 : 0
 Total NaN in row 8804 : 0
 Total NaN in row 8805 : 0
 Total NaN in row 8806 : 7
 Total NaN in row 8807 : 2
 Total NaN in row 8808 : 7
 Total NaN in row 8809 : 0
 Total NaN in row 8810 : 3
 Total NaN in row 8811 : 2
 Total NaN in row 8812 : 0
 Total NaN in row 8813 : 2
 Total NaN in row 8814 : 0
 Total NaN in row 8815 : 0
 Total NaN in row 8816 : 2
 Total NaN in row 8817 : 21
 Total NaN in row 8818 : 1
 Total NaN in row 8819 : 3
 Total NaN in row 8820 : 0
 Total NaN in row 8821 : 1
 Total NaN in row 8822 : 0
 Total NaN in row 8823 : 0
 Total NaN in row 8824 : 0
 Total NaN in row 8825 : 1
 Total NaN in row 8826 : 3
 Total NaN in row 8827 : 0
 Total NaN in row 8828 : 9
 Total NaN in row 8829 : 2
 Total NaN in row 8830 : 1
 Total NaN in row 8831 : 0
 Total NaN in row 8832 : 0
 Total NaN in row 8833 : 10
 Total NaN in row 8834 : 1
 Total NaN in row 8835 : 0
 Total NaN in row 8836 : 0
 Total NaN in row 8837 : 0
 Total NaN in row 8838 : 9
 Total NaN in row 8839 : 0
 Total NaN in row 8840 : 0
 Total NaN in row 8841 : 1
 Total NaN in row 8842 : 0
 Total NaN in row 8843 : 0
 Total NaN in row 8844 : 0
 Total NaN in row 8845 : 0
 Total NaN in row 8846 : 0
 Total NaN in row 8847 : 9
 Total NaN in row 8848 : 1
 Total NaN in row 8849 : 0
 Total NaN in row 8850 : 0
 Total NaN in row 8851 : 3
 Total NaN in row 8852 : 0
 Total NaN in row 8853 : 0
 Total NaN in row 8854 : 10
 Total NaN in row 8855 : 3
 Total NaN in row 8856 : 0
 Total NaN in row 8857 : 1
 Total NaN in row 8858 : 2
 Total NaN in row 8859 : 0
 Total NaN in row 8860 : 9
 Total NaN in row 8861 : 2
 Total NaN in row 8862 : 9
 Total NaN in row 8863 : 0
 Total NaN in row 8864 : 2
 Total NaN in row 8865 : 2
 Total NaN in row 8866 : 0
 Total NaN in row 8867 : 2
 Total NaN in row 8868 : 0
 Total NaN in row 8869 : 9
 Total NaN in row 8870 : 1
 Total NaN in row 8871 : 0
 Total NaN in row 8872 : 0
 Total NaN in row 8873 : 1
 Total NaN in row 8874 : 1
 Total NaN in row 8875 : 0
 Total NaN in row 8876 : 0
 Total NaN in row 8877 : 1
 Total NaN in row 8878 : 0
 Total NaN in row 8879 : 1
 Total NaN in row 8880 : 0
 Total NaN in row 8881 : 0
 Total NaN in row 8882 : 0
 Total NaN in row 8883 : 2
 Total NaN in row 8884 : 0
 Total NaN in row 8885 : 0
 Total NaN in row 8886 : 2
 Total NaN in row 8887 : 9
 Total NaN in row 8888 : 2
 Total NaN in row 8889 : 0
 Total NaN in row 8890 : 1
 Total NaN in row 8891 : 0
 Total NaN in row 8892 : 0

 Total NaN in row 8893 : 3
 Total NaN in row 8894 : 9
 Total NaN in row 8895 : 2
 Total NaN in row 8896 : 0
 Total NaN in row 8897 : 10
 Total NaN in row 8898 : 1
 Total NaN in row 8899 : 0
 Total NaN in row 8900 : 0
 Total NaN in row 8901 : 9
 Total NaN in row 8902 : 0
 Total NaN in row 8903 : 0
 Total NaN in row 8904 : 0
 Total NaN in row 8905 : 9
 Total NaN in row 8906 : 2
 Total NaN in row 8907 : 0
 Total NaN in row 8908 : 1
 Total NaN in row 8909 : 2
 Total NaN in row 8910 : 2
 Total NaN in row 8911 : 1
 Total NaN in row 8912 : 2
 Total NaN in row 8913 : 1
 Total NaN in row 8914 : 2
 Total NaN in row 8915 : 9
 Total NaN in row 8916 : 0
 Total NaN in row 8917 : 2
 Total NaN in row 8918 : 0
 Total NaN in row 8919 : 8
 Total NaN in row 8920 : 0
 Total NaN in row 8921 : 2
 Total NaN in row 8922 : 2
 Total NaN in row 8923 : 9
 Total NaN in row 8924 : 9
 Total NaN in row 8925 : 0
 Total NaN in row 8926 : 0
 Total NaN in row 8927 : 2
 Total NaN in row 8928 : 0
 Total NaN in row 8929 : 2
 Total NaN in row 8930 : 2
 Total NaN in row 8931 : 2
 Total NaN in row 8932 : 2
 Total NaN in row 8933 : 2
 Total NaN in row 8934 : 1
 Total NaN in row 8935 : 0
 Total NaN in row 8936 : 0
 Total NaN in row 8937 : 9
 Total NaN in row 8938 : 9
 Total NaN in row 8939 : 3
 Total NaN in row 8940 : 0
 Total NaN in row 8941 : 1
 Total NaN in row 8942 : 2
 Total NaN in row 8943 : 1
 Total NaN in row 8944 : 0
 Total NaN in row 8945 : 2
 Total NaN in row 8946 : 2
 Total NaN in row 8947 : 2
 Total NaN in row 8948 : 0
 Total NaN in row 8949 : 1
 Total NaN in row 8950 : 0
 Total NaN in row 8951 : 0
 Total NaN in row 8952 : 9
 Total NaN in row 8953 : 0
 Total NaN in row 8954 : 1
 Total NaN in row 8955 : 1
 Total NaN in row 8956 : 0
 Total NaN in row 8957 : 9
 Total NaN in row 8958 : 2
 Total NaN in row 8959 : 2
 Total NaN in row 8960 : 2
 Total NaN in row 8961 : 9
 Total NaN in row 8962 : 0
 Total NaN in row 8963 : 9
 Total NaN in row 8964 : 0
 Total NaN in row 8965 : 0
 Total NaN in row 8966 : 0
 Total NaN in row 8967 : 1
 Total NaN in row 8968 : 0
 Total NaN in row 8969 : 0
 Total NaN in row 8970 : 1
 Total NaN in row 8971 : 2
 Total NaN in row 8972 : 1
 Total NaN in row 8973 : 1
 Total NaN in row 8974 : 9
 Total NaN in row 8975 : 21
 Total NaN in row 8976 : 2
 Total NaN in row 8977 : 2
 Total NaN in row 8978 : 10
 Total NaN in row 8979 : 0
 Total NaN in row 8980 : 1
 Total NaN in row 8981 : 0
 Total NaN in row 8982 : 1
 Total NaN in row 8983 : 0
 Total NaN in row 8984 : 0
 Total NaN in row 8985 : 1
 Total NaN in row 8986 : 2
 Total NaN in row 8987 : 2
 Total NaN in row 8988 : 10
 Total NaN in row 8989 : 3
 Total NaN in row 8990 : 2
 Total NaN in row 8991 : 0
 Total NaN in row 8992 : 9
 Total NaN in row 8993 : 0
 Total NaN in row 8994 : 0
 Total NaN in row 8995 : 0
 Total NaN in row 8996 : 0
 Total NaN in row 8997 : 1
 Total NaN in row 8998 : 2
 Total NaN in row 8999 : 0
 Total NaN in row 9000 : 7
 Total NaN in row 9001 : 1
 Total NaN in row 9002 : 0
 Total NaN in row 9003 : 9
 Total NaN in row 9004 : 2
 Total NaN in row 9005 : 2
 Total NaN in row 9006 : 0
 Total NaN in row 9007 : 0
 Total NaN in row 9008 : 0
 Total NaN in row 9009 : 0
 Total NaN in row 9010 : 1
 Total NaN in row 9011 : 2
 Total NaN in row 9012 : 2
 Total NaN in row 9013 : 2
 Total NaN in row 9014 : 0
 Total NaN in row 9015 : 2
 Total NaN in row 9016 : 2
 Total NaN in row 9017 : 0
 Total NaN in row 9018 : 0
 Total NaN in row 9019 : 2
 Total NaN in row 9020 : 0
 Total NaN in row 9021 : 2
 Total NaN in row 9022 : 0
 Total NaN in row 9023 : 0
 Total NaN in row 9024 : 10
 Total NaN in row 9025 : 1
 Total NaN in row 9026 : 0
 Total NaN in row 9027 : 1
 Total NaN in row 9028 : 1
 Total NaN in row 9029 : 1
 Total NaN in row 9030 : 0
 Total NaN in row 9031 : 2
 Total NaN in row 9032 : 2
 Total NaN in row 9033 : 1
 Total NaN in row 9034 : 0
 Total NaN in row 9035 : 0
 Total NaN in row 9036 : 0
 Total NaN in row 9037 : 10
 Total NaN in row 9038 : 2
 Total NaN in row 9039 : 0
 Total NaN in row 9040 : 9
 Total NaN in row 9041 : 3
 Total NaN in row 9042 : 1
 Total NaN in row 9043 : 1
 Total NaN in row 9044 : 9
 Total NaN in row 9045 : 9
 Total NaN in row 9046 : 2
 Total NaN in row 9047 : 9
 Total NaN in row 9048 : 1
 Total NaN in row 9049 : 9
 Total NaN in row 9050 : 9
 Total NaN in row 9051 : 0
 Total NaN in row 9052 : 0
 Total NaN in row 9053 : 0
 Total NaN in row 9054 : 9
 Total NaN in row 9055 : 3
 Total NaN in row 9056 : 2
 Total NaN in row 9057 : 9
 Total NaN in row 9058 : 0
 Total NaN in row 9059 : 9
 Total NaN in row 9060 : 3
 Total NaN in row 9061 : 0
 Total NaN in row 9062 : 0
 Total NaN in row 9063 : 1
 Total NaN in row 9064 : 2
 Total NaN in row 9065 : 1
 Total NaN in row 9066 : 2
 Total NaN in row 9067 : 2
 Total NaN in row 9068 : 2
 Total NaN in row 9069 : 1
 Total NaN in row 9070 : 9
 Total NaN in row 9071 : 1
 Total NaN in row 9072 : 0
 Total NaN in row 9073 : 0
 Total NaN in row 9074 : 1
 Total NaN in row 9075 : 0
 Total NaN in row 9076 : 10
 Total NaN in row 9077 : 9
 Total NaN in row 9078 : 2
 Total NaN in row 9079 : 0
 Total NaN in row 9080 : 9
 Total NaN in row 9081 : 2
 Total NaN in row 9082 : 0
 Total NaN in row 9083 : 0
 Total NaN in row 9084 : 2
 Total NaN in row 9085 : 2
 Total NaN in row 9086 : 10
 Total NaN in row 9087 : 9
 Total NaN in row 9088 : 2
 Total NaN in row 9089 : 2
 Total NaN in row 9090 : 3
 Total NaN in row 9091 : 10
 Total NaN in row 9092 : 0
 Total NaN in row 9093 : 3
 Total NaN in row 9094 : 3
 Total NaN in row 9095 : 9
 Total NaN in row 9096 : 9
 Total NaN in row 9097 : 1
 Total NaN in row 9098 : 9
 Total NaN in row 9099 : 21
 Total NaN in row 9100 : 0
 Total NaN in row 9101 : 2
 Total NaN in row 9102 : 2
 Total NaN in row 9103 : 0
 Total NaN in row 9104 : 0
 Total NaN in row 9105 : 9
 Total NaN in row 9106 : 3
 Total NaN in row 9107 : 10
 Total NaN in row 9108 : 0
 Total NaN in row 9109 : 2
 Total NaN in row 9110 : 9
 Total NaN in row 9111 : 1
 Total NaN in row 9112 : 0
 Total NaN in row 9113 : 1
 Total NaN in row 9114 : 1
 Total NaN in row 9115 : 9
 Total NaN in row 9116 : 9
 Total NaN in row 9117 : 10
 Total NaN in row 9118 : 1
 Total NaN in row 9119 : 2
 Total NaN in row 9120 : 1
 Total NaN in row 9121 : 2
 Total NaN in row 9122 : 0
 Total NaN in row 9123 : 0
 Total NaN in row 9124 : 1
 Total NaN in row 9125 : 0
 Total NaN in row 9126 : 0
 Total NaN in row 9127 : 0
 Total NaN in row 9128 : 1
 Total NaN in row 9129 : 0
 Total NaN in row 9130 : 0
 Total NaN in row 9131 : 2
 Total NaN in row 9132 : 0
 Total NaN in row 9133 : 1
 Total NaN in row 9134 : 0
 Total NaN in row 9135 : 0
 Total NaN in row 9136 : 3
 Total NaN in row 9137 : 0
 Total NaN in row 9138 : 2
 Total NaN in row 9139 : 2
 Total NaN in row 9140 : 0
 Total NaN in row 9141 : 0
 Total NaN in row 9142 : 0
 Total NaN in row 9143 : 0
 Total NaN in row 9144 : 0
 Total NaN in row 9145 : 2
 Total NaN in row 9146 : 2
 Total NaN in row 9147 : 0
 Total NaN in row 9148 : 0
 Total NaN in row 9149 : 2
 Total NaN in row 9150 : 0
 Total NaN in row 9151 : 3
 Total NaN in row 9152 : 2
 Total NaN in row 9153 : 2
 Total NaN in row 9154 : 0
 Total NaN in row 9155 : 2
 Total NaN in row 9156 : 0
 Total NaN in row 9157 : 0
 Total NaN in row 9158 : 2
 Total NaN in row 9159 : 1
 Total NaN in row 9160 : 0
 Total NaN in row 9161 : 2
 Total NaN in row 9162 : 1
 Total NaN in row 9163 : 0
 Total NaN in row 9164 : 0
 Total NaN in row 9165 : 3
 Total NaN in row 9166 : 0
 Total NaN in row 9167 : 2
 Total NaN in row 9168 : 1
 Total NaN in row 9169 : 1
 Total NaN in row 9170 : 9
 Total NaN in row 9171 : 9
 Total NaN in row 9172 : 2
 Total NaN in row 9173 : 0
 Total NaN in row 9174 : 2
 Total NaN in row 9175 : 0
 Total NaN in row 9176 : 1
 Total NaN in row 9177 : 0
 Total NaN in row 9178 : 9
 Total NaN in row 9179 : 0
 Total NaN in row 9180 : 2
 Total NaN in row 9181 : 2
 Total NaN in row 9182 : 0
 Total NaN in row 9183 : 1
 Total NaN in row 9184 : 2
 Total NaN in row 9185 : 1
 Total NaN in row 9186 : 0
 Total NaN in row 9187 : 1
 Total NaN in row 9188 : 0
 Total NaN in row 9189 : 0
 Total NaN in row 9190 : 10
 Total NaN in row 9191 : 1
 Total NaN in row 9192 : 2
 Total NaN in row 9193 : 0
 Total NaN in row 9194 : 2
 Total NaN in row 9195 : 0
 Total NaN in row 9196 : 0
 Total NaN in row 9197 : 0
 Total NaN in row 9198 : 0
 Total NaN in row 9199 : 3
 Total NaN in row 9200 : 1
 Total NaN in row 9201 : 7
 Total NaN in row 9202 : 9
 Total NaN in row 9203 : 0
 Total NaN in row 9204 : 0
 Total NaN in row 9205 : 2
 Total NaN in row 9206 : 0
 Total NaN in row 9207 : 3
 Total NaN in row 9208 : 1
 Total NaN in row 9209 : 2
 Total NaN in row 9210 : 9
 Total NaN in row 9211 : 21
 Total NaN in row 9212 : 3
 Total NaN in row 9213 : 1
 Total NaN in row 9214 : 9
 Total NaN in row 9215 : 0
 Total NaN in row 9216 : 1
 Total NaN in row 9217 : 0
 Total NaN in row 9218 : 7
 Total NaN in row 9219 : 0
 Total NaN in row 9220 : 2
 Total NaN in row 9221 : 0
 Total NaN in row 9222 : 0
 Total NaN in row 9223 : 3
 Total NaN in row 9224 : 10
 Total NaN in row 9225 : 2
 Total NaN in row 9226 : 0
 Total NaN in row 9227 : 0
 Total NaN in row 9228 : 0
 Total NaN in row 9229 : 1
 Total NaN in row 9230 : 2
 Total NaN in row 9231 : 2
 Total NaN in row 9232 : 2
 Total NaN in row 9233 : 21
 Total NaN in row 9234 : 0
 Total NaN in row 9235 : 0
 Total NaN in row 9236 : 3
 Total NaN in row 9237 : 1
 Total NaN in row 9238 : 1
 Total NaN in row 9239 : 0
 Total NaN in row 9240 : 1
 Total NaN in row 9241 : 2

 Total NaN in row 9242 : 2
 Total NaN in row 9243 : 0
 Total NaN in row 9244 : 0
 Total NaN in row 9245 : 1
 Total NaN in row 9246 : 1
 Total NaN in row 9247 : 9
 Total NaN in row 9248 : 9
 Total NaN in row 9249 : 3
 Total NaN in row 9250 : 2
 Total NaN in row 9251 : 2
 Total NaN in row 9252 : 9
 Total NaN in row 9253 : 9
 Total NaN in row 9254 : 1
 Total NaN in row 9255 : 0
 Total NaN in row 9256 : 1
 Total NaN in row 9257 : 2
 Total NaN in row 9258 : 2
 Total NaN in row 9259 : 0
 Total NaN in row 9260 : 0
 Total NaN in row 9261 : 2
 Total NaN in row 9262 : 1
 Total NaN in row 9263 : 2
 Total NaN in row 9264 : 3
 Total NaN in row 9265 : 1
 Total NaN in row 9266 : 9
 Total NaN in row 9267 : 1
 Total NaN in row 9268 : 1
 Total NaN in row 9269 : 3
 Total NaN in row 9270 : 2
 Total NaN in row 9271 : 2
 Total NaN in row 9272 : 0
 Total NaN in row 9273 : 0
 Total NaN in row 9274 : 2
 Total NaN in row 9275 : 0
 Total NaN in row 9276 : 3
 Total NaN in row 9277 : 1
 Total NaN in row 9278 : 1
 Total NaN in row 9279 : 9
 Total NaN in row 9280 : 2
 Total NaN in row 9281 : 1
 Total NaN in row 9282 : 1
 Total NaN in row 9283 : 2
 Total NaN in row 9284 : 2
 Total NaN in row 9285 : 1
 Total NaN in row 9286 : 1
 Total NaN in row 9287 : 9
 Total NaN in row 9288 : 0
 Total NaN in row 9289 : 0
 Total NaN in row 9290 : 1
 Total NaN in row 9291 : 0
 Total NaN in row 9292 : 1
 Total NaN in row 9293 : 1
 Total NaN in row 9294 : 0
 Total NaN in row 9295 : 0
 Total NaN in row 9296 : 2
 Total NaN in row 9297 : 0
 Total NaN in row 9298 : 1
 Total NaN in row 9299 : 2
 Total NaN in row 9300 : 0
 Total NaN in row 9301 : 0
 Total NaN in row 9302 : 1
 Total NaN in row 9303 : 0
 Total NaN in row 9304 : 2
 Total NaN in row 9305 : 2
 Total NaN in row 9306 : 1
 Total NaN in row 9307 : 0
 Total NaN in row 9308 : 0
 Total NaN in row 9309 : 0
 Total NaN in row 9310 : 2
 Total NaN in row 9311 : 1
 Total NaN in row 9312 : 2
 Total NaN in row 9313 : 9
 Total NaN in row 9314 : 1
 Total NaN in row 9315 : 2
 Total NaN in row 9316 : 1
 Total NaN in row 9317 : 0
 Total NaN in row 9318 : 3
 Total NaN in row 9319 : 1
 Total NaN in row 9320 : 2
 Total NaN in row 9321 : 1
 Total NaN in row 9322 : 9
 Total NaN in row 9323 : 2
 Total NaN in row 9324 : 2
 Total NaN in row 9325 : 2
 Total NaN in row 9326 : 0
 Total NaN in row 9327 : 2
 Total NaN in row 9328 : 2
 Total NaN in row 9329 : 10
 Total NaN in row 9330 : 0
 Total NaN in row 9331 : 0
 Total NaN in row 9332 : 1
 Total NaN in row 9333 : 2
 Total NaN in row 9334 : 2
 Total NaN in row 9335 : 3
 Total NaN in row 9336 : 1
 Total NaN in row 9337 : 1
 Total NaN in row 9338 : 0
 Total NaN in row 9339 : 9
 Total NaN in row 9340 : 2
 Total NaN in row 9341 : 0
 Total NaN in row 9342 : 2
 Total NaN in row 9343 : 0
 Total NaN in row 9344 : 1
 Total NaN in row 9345 : 0
 Total NaN in row 9346 : 2
 Total NaN in row 9347 : 2
 Total NaN in row 9348 : 2
 Total NaN in row 9349 : 1
 Total NaN in row 9350 : 1
 Total NaN in row 9351 : 1
 Total NaN in row 9352 : 2
 Total NaN in row 9353 : 1
 Total NaN in row 9354 : 1
 Total NaN in row 9355 : 0
 Total NaN in row 9356 : 2
 Total NaN in row 9357 : 1
 Total NaN in row 9358 : 0
 Total NaN in row 9359 : 0
 Total NaN in row 9360 : 1
 Total NaN in row 9361 : 0
 Total NaN in row 9362 : 1
 Total NaN in row 9363 : 2
 Total NaN in row 9364 : 2
 Total NaN in row 9365 : 0
 Total NaN in row 9366 : 2
 Total NaN in row 9367 : 2
 Total NaN in row 9368 : 2
 Total NaN in row 9369 : 1
 Total NaN in row 9370 : 9
 Total NaN in row 9371 : 3
 Total NaN in row 9372 : 2
 Total NaN in row 9373 : 1
 Total NaN in row 9374 : 0
 Total NaN in row 9375 : 1
 Total NaN in row 9376 : 0
 Total NaN in row 9377 : 2
 Total NaN in row 9378 : 10
 Total NaN in row 9379 : 2
 Total NaN in row 9380 : 1
 Total NaN in row 9381 : 0
 Total NaN in row 9382 : 0
 Total NaN in row 9383 : 1
 Total NaN in row 9384 : 2
 Total NaN in row 9385 : 3
 Total NaN in row 9386 : 7
 Total NaN in row 9387 : 4
 Total NaN in row 9388 : 0
 Total NaN in row 9389 : 0
 Total NaN in row 9390 : 2
 Total NaN in row 9391 : 0
 Total NaN in row 9392 : 0
 Total NaN in row 9393 : 0
 Total NaN in row 9394 : 9
 Total NaN in row 9395 : 0
 Total NaN in row 9396 : 9
 Total NaN in row 9397 : 0
 Total NaN in row 9398 : 0
 Total NaN in row 9399 : 9
 Total NaN in row 9400 : 0
 Total NaN in row 9401 : 1
 Total NaN in row 9402 : 0
 Total NaN in row 9403 : 0
 Total NaN in row 9404 : 9
 Total NaN in row 9405 : 0
 Total NaN in row 9406 : 1
 Total NaN in row 9407 : 0
 Total NaN in row 9408 : 10
 Total NaN in row 9409 : 3
 Total NaN in row 9410 : 0
 Total NaN in row 9411 : 9
 Total NaN in row 9412 : 9
 Total NaN in row 9413 : 2
 Total NaN in row 9414 : 0
 Total NaN in row 9415 : 1
 Total NaN in row 9416 : 0
 Total NaN in row 9417 : 1
 Total NaN in row 9418 : 2
 Total NaN in row 9419 : 0
 Total NaN in row 9420 : 1
 Total NaN in row 9421 : 3
 Total NaN in row 9422 : 1
 Total NaN in row 9423 : 0
 Total NaN in row 9424 : 9
 Total NaN in row 9425 : 0
 Total NaN in row 9426 : 1
 Total NaN in row 9427 : 1
 Total NaN in row 9428 : 2
 Total NaN in row 9429 : 3
 Total NaN in row 9430 : 1
 Total NaN in row 9431 : 2
 Total NaN in row 9432 : 1
 Total NaN in row 9433 : 9
 Total NaN in row 9434 : 1
 Total NaN in row 9435 : 0
 Total NaN in row 9436 : 0
 Total NaN in row 9437 : 2
 Total NaN in row 9438 : 9
 Total NaN in row 9439 : 2
 Total NaN in row 9440 : 2
 Total NaN in row 9441 : 3
 Total NaN in row 9442 : 3
 Total NaN in row 9443 : 1
 Total NaN in row 9444 : 1
 Total NaN in row 9445 : 0
 Total NaN in row 9446 : 0
 Total NaN in row 9447 : 10
 Total NaN in row 9448 : 9
 Total NaN in row 9449 : 0
 Total NaN in row 9450 : 1
 Total NaN in row 9451 : 21
 Total NaN in row 9452 : 2
 Total NaN in row 9453 : 2
 Total NaN in row 9454 : 0
 Total NaN in row 9455 : 0
 Total NaN in row 9456 : 21
 Total NaN in row 9457 : 9
 Total NaN in row 9458 : 1
 Total NaN in row 9459 : 2
 Total NaN in row 9460 : 9
 Total NaN in row 9461 : 0
 Total NaN in row 9462 : 10
 Total NaN in row 9463 : 1
 Total NaN in row 9464 : 9
 Total NaN in row 9465 : 0
 Total NaN in row 9466 : 1
 Total NaN in row 9467 : 0
 Total NaN in row 9468 : 2
 Total NaN in row 9469 : 0
 Total NaN in row 9470 : 0
 Total NaN in row 9471 : 1
 Total NaN in row 9472 : 0
 Total NaN in row 9473 : 1
 Total NaN in row 9474 : 0
 Total NaN in row 9475 : 1
 Total NaN in row 9476 : 0
 Total NaN in row 9477 : 1
 Total NaN in row 9478 : 1
 Total NaN in row 9479 : 2
 Total NaN in row 9480 : 0
 Total NaN in row 9481 : 1
 Total NaN in row 9482 : 9
 Total NaN in row 9483 : 1
 Total NaN in row 9484 : 1
 Total NaN in row 9485 : 0
 Total NaN in row 9486 : 2
 Total NaN in row 9487 : 0
 Total NaN in row 9488 : 1
 Total NaN in row 9489 : 9
 Total NaN in row 9490 : 1
 Total NaN in row 9491 : 0
 Total NaN in row 9492 : 0
 Total NaN in row 9493 : 1
 Total NaN in row 9494 : 1
 Total NaN in row 9495 : 1
 Total NaN in row 9496 : 1
 Total NaN in row 9497 : 10
 Total NaN in row 9498 : 0
 Total NaN in row 9499 : 0
 Total NaN in row 9500 : 1
 Total NaN in row 9501 : 0
 Total NaN in row 9502 : 1
 Total NaN in row 9503 : 1
 Total NaN in row 9504 : 3
 Total NaN in row 9505 : 9
 Total NaN in row 9506 : 9
 Total NaN in row 9507 : 0
 Total NaN in row 9508 : 0
 Total NaN in row 9509 : 0
 Total NaN in row 9510 : 0
 Total NaN in row 9511 : 2
 Total NaN in row 9512 : 0
 Total NaN in row 9513 : 9
 Total NaN in row 9514 : 0
 Total NaN in row 9515 : 0
 Total NaN in row 9516 : 2
 Total NaN in row 9517 : 0
 Total NaN in row 9518 : 9
 Total NaN in row 9519 : 9
 Total NaN in row 9520 : 0
 Total NaN in row 9521 : 2
 Total NaN in row 9522 : 0
 Total NaN in row 9523 : 2
 Total NaN in row 9524 : 0
 Total NaN in row 9525 : 0
 Total NaN in row 9526 : 0
 Total NaN in row 9527 : 1
 Total NaN in row 9528 : 0
 Total NaN in row 9529 : 8
 Total NaN in row 9530 : 2
 Total NaN in row 9531 : 7
 Total NaN in row 9532 : 0
 Total NaN in row 9533 : 7
 Total NaN in row 9534 : 3
 Total NaN in row 9535 : 2
 Total NaN in row 9536 : 3
 Total NaN in row 9537 : 7
 Total NaN in row 9538 : 0
 Total NaN in row 9539 : 9
 Total NaN in row 9540 : 7
 Total NaN in row 9541 : 2
 Total NaN in row 9542 : 9
 Total NaN in row 9543 : 0
 Total NaN in row 9544 : 9
 Total NaN in row 9545 : 7
 Total NaN in row 9546 : 0
 Total NaN in row 9547 : 9
 Total NaN in row 9548 : 10
 Total NaN in row 9549 : 9
 Total NaN in row 9550 : 8
 Total NaN in row 9551 : 0
 Total NaN in row 9552 : 1
 Total NaN in row 9553 : 0
 Total NaN in row 9554 : 9
 Total NaN in row 9555 : 2
 Total NaN in row 9556 : 0
 Total NaN in row 9557 : 7
 Total NaN in row 9558 : 0
 Total NaN in row 9559 : 1
 Total NaN in row 9560 : 1
 Total NaN in row 9561 : 0
 Total NaN in row 9562 : 2
 Total NaN in row 9563 : 0
 Total NaN in row 9564 : 0
 Total NaN in row 9565 : 0
 Total NaN in row 9566 : 0
 Total NaN in row 9567 : 1
 Total NaN in row 9568 : 0
 Total NaN in row 9569 : 9
 Total NaN in row 9570 : 2
 Total NaN in row 9571 : 9
 Total NaN in row 9572 : 9
 Total NaN in row 9573 : 1
 Total NaN in row 9574 : 7
 Total NaN in row 9575 : 2
 Total NaN in row 9576 : 7
 Total NaN in row 9577 : 0
 Total NaN in row 9578 : 8
 Total NaN in row 9579 : 9
 Total NaN in row 9580 : 10
 Total NaN in row 9581 : 2
 Total NaN in row 9582 : 0
 Total NaN in row 9583 : 7
 Total NaN in row 9584 : 0
 Total NaN in row 9585 : 2
 Total NaN in row 9586 : 7
 Total NaN in row 9587 : 21
 Total NaN in row 9588 : 8
 Total NaN in row 9589 : 7
 Total NaN in row 9590 : 2
 Total NaN in row 9591 : 0
 Total NaN in row 9592 : 1
 Total NaN in row 9593 : 2
 Total NaN in row 9594 : 9
 Total NaN in row 9595 : 0
 Total NaN in row 9596 : 1
 Total NaN in row 9597 : 8
 Total NaN in row 9598 : 2
 Total NaN in row 9599 : 0
 Total NaN in row 9600 : 0
 Total NaN in row 9601 : 0
 Total NaN in row 9602 : 0
 Total NaN in row 9603 : 10
 Total NaN in row 9604 : 2
 Total NaN in row 9605 : 0
 Total NaN in row 9606 : 0
 Total NaN in row 9607 : 9
 Total NaN in row 9608 : 8
 Total NaN in row 9609 : 8
 Total NaN in row 9610 : 2
 Total NaN in row 9611 : 1
 Total NaN in row 9612 : 0
 Total NaN in row 9613 : 1
 Total NaN in row 9614 : 0
 Total NaN in row 9615 : 0
 Total NaN in row 9616 : 9
 Total NaN in row 9617 : 1
 Total NaN in row 9618 : 7
 Total NaN in row 9619 : 1
 Total NaN in row 9620 : 0
 Total NaN in row 9621 : 0
 Total NaN in row 9622 : 1
 Total NaN in row 9623 : 0
 Total NaN in row 9624 : 2
 Total NaN in row 9625 : 9
 Total NaN in row 9626 : 0

 Total NaN in row 9627 : 7
 Total NaN in row 9628 : 2
 Total NaN in row 9629 : 0
 Total NaN in row 9630 : 2
 Total NaN in row 9631 : 9
 Total NaN in row 9632 : 0
 Total NaN in row 9633 : 7
 Total NaN in row 9634 : 0
 Total NaN in row 9635 : 2
 Total NaN in row 9636 : 1
 Total NaN in row 9637 : 1
 Total NaN in row 9638 : 0
 Total NaN in row 9639 : 0
 Total NaN in row 9640 : 3
 Total NaN in row 9641 : 0
 Total NaN in row 9642 : 7
 Total NaN in row 9643 : 0
 Total NaN in row 9644 : 1
 Total NaN in row 9645 : 0
 Total NaN in row 9646 : 2
 Total NaN in row 9647 : 1
 Total NaN in row 9648 : 7
 Total NaN in row 9649 : 2
 Total NaN in row 9650 : 2
 Total NaN in row 9651 : 9
 Total NaN in row 9652 : 0
 Total NaN in row 9653 : 0
 Total NaN in row 9654 : 0
 Total NaN in row 9655 : 0
 Total NaN in row 9656 : 7
 Total NaN in row 9657 : 0
 Total NaN in row 9658 : 8
 Total NaN in row 9659 : 7
 Total NaN in row 9660 : 10
 Total NaN in row 9661 : 0
 Total NaN in row 9662 : 9
 Total NaN in row 9663 : 0
 Total NaN in row 9664 : 2
 Total NaN in row 9665 : 2
 Total NaN in row 9666 : 2
 Total NaN in row 9667 : 0
 Total NaN in row 9668 : 9
 Total NaN in row 9669 : 1
 Total NaN in row 9670 : 2
 Total NaN in row 9671 : 7
 Total NaN in row 9672 : 7
 Total NaN in row 9673 : 2
 Total NaN in row 9674 : 2
 Total NaN in row 9675 : 1
 Total NaN in row 9676 : 0
 Total NaN in row 9677 : 10
 Total NaN in row 9678 : 8
 Total NaN in row 9679 : 8
 Total NaN in row 9680 : 8
 Total NaN in row 9681 : 7
 Total NaN in row 9682 : 0
 Total NaN in row 9683 : 7
 Total NaN in row 9684 : 1
 Total NaN in row 9685 : 0
 Total NaN in row 9686 : 2
 Total NaN in row 9687 : 0
 Total NaN in row 9688 : 1
 Total NaN in row 9689 : 2
 Total NaN in row 9690 : 0
 Total NaN in row 9691 : 0
 Total NaN in row 9692 : 2
 Total NaN in row 9693 : 1
 Total NaN in row 9694 : 10
 Total NaN in row 9695 : 0
 Total NaN in row 9696 : 0
 Total NaN in row 9697 : 9
 Total NaN in row 9698 : 7
 Total NaN in row 9699 : 0
 Total NaN in row 9700 : 2
 Total NaN in row 9701 : 1
 Total NaN in row 9702 : 8
 Total NaN in row 9703 : 0
 Total NaN in row 9704 : 3
 Total NaN in row 9705 : 0
 Total NaN in row 9706 : 3
 Total NaN in row 9707 : 0
 Total NaN in row 9708 : 9
 Total NaN in row 9709 : 1
 Total NaN in row 9710 : 9
 Total NaN in row 9711 : 7
 Total NaN in row 9712 : 7
 Total NaN in row 9713 : 2
 Total NaN in row 9714 : 7
 Total NaN in row 9715 : 0
 Total NaN in row 9716 : 2
 Total NaN in row 9717 : 10
 Total NaN in row 9718 : 10
 Total NaN in row 9719 : 2
 Total NaN in row 9720 : 0
 Total NaN in row 9721 : 2
 Total NaN in row 9722 : 0
 Total NaN in row 9723 : 2
 Total NaN in row 9724 : 9
 Total NaN in row 9725 : 7
 Total NaN in row 9726 : 0
 Total NaN in row 9727 : 1
 Total NaN in row 9728 : 2
 Total NaN in row 9729 : 0
 Total NaN in row 9730 : 2
 Total NaN in row 9731 : 2
 Total NaN in row 9732 : 0
 Total NaN in row 9733 : 2
 Total NaN in row 9734 : 2
 Total NaN in row 9735 : 2
 Total NaN in row 9736 : 1
 Total NaN in row 9737 : 9
 Total NaN in row 9738 : 9
 Total NaN in row 9739 : 2
 Total NaN in row 9740 : 3
 Total NaN in row 9741 : 9
 Total NaN in row 9742 : 1
 Total NaN in row 9743 : 3
 Total NaN in row 9744 : 1
 Total NaN in row 9745 : 9
 Total NaN in row 9746 : 1
 Total NaN in row 9747 : 9
 Total NaN in row 9748 : 1
 Total NaN in row 9749 : 0
 Total NaN in row 9750 : 9
 Total NaN in row 9751 : 0
 Total NaN in row 9752 : 9
 Total NaN in row 9753 : 0
 Total NaN in row 9754 : 9
 Total NaN in row 9755 : 2
 Total NaN in row 9756 : 9
 Total NaN in row 9757 : 10
 Total NaN in row 9758 : 9
 Total NaN in row 9759 : 2
 Total NaN in row 9760 : 7
 Total NaN in row 9761 : 0
 Total NaN in row 9762 : 21
 Total NaN in row 9763 : 0
 Total NaN in row 9764 : 0
 Total NaN in row 9765 : 9
 Total NaN in row 9766 : 0
 Total NaN in row 9767 : 9
 Total NaN in row 9768 : 9
 Total NaN in row 9769 : 9
 Total NaN in row 9770 : 3
 Total NaN in row 9771 : 10
 Total NaN in row 9772 : 0
 Total NaN in row 9773 : 0
 Total NaN in row 9774 : 9
 Total NaN in row 9775 : 0
 Total NaN in row 9776 : 0
 Total NaN in row 9777 : 2
 Total NaN in row 9778 : 9
 Total NaN in row 9779 : 0
 Total NaN in row 9780 : 0
 Total NaN in row 9781 : 2
 Total NaN in row 9782 : 0
 Total NaN in row 9783 : 0
 Total NaN in row 9784 : 0
 Total NaN in row 9785 : 0
 Total NaN in row 9786 : 9
 Total NaN in row 9787 : 9
 Total NaN in row 9788 : 9
 Total NaN in row 9789 : 0
 Total NaN in row 9790 : 0
 Total NaN in row 9791 : 9
 Total NaN in row 9792 : 3
 Total NaN in row 9793 : 9
 Total NaN in row 9794 : 2
 Total NaN in row 9795 : 2
 Total NaN in row 9796 : 3
 Total NaN in row 9797 : 2
 Total NaN in row 9798 : 2
 Total NaN in row 9799 : 10
 Total NaN in row 9800 : 2
 Total NaN in row 9801 : 2
 Total NaN in row 9802 : 2
 Total NaN in row 9803 : 1
 Total NaN in row 9804 : 7
 Total NaN in row 9805 : 2
 Total NaN in row 9806 : 0
 Total NaN in row 9807 : 9
 Total NaN in row 9808 : 9
 Total NaN in row 9809 : 9
 Total NaN in row 9810 : 9
 Total NaN in row 9811 : 9
 Total NaN in row 9812 : 2
 Total NaN in row 9813 : 2
 Total NaN in row 9814 : 2
 Total NaN in row 9815 : 3
 Total NaN in row 9816 : 9
 Total NaN in row 9817 : 2
 Total NaN in row 9818 : 0
 Total NaN in row 9819 : 0
 Total NaN in row 9820 : 1
 Total NaN in row 9821 : 2
 Total NaN in row 9822 : 2
 Total NaN in row 9823 : 2
 Total NaN in row 9824 : 0
 Total NaN in row 9825 : 2
 Total NaN in row 9826 : 0
 Total NaN in row 9827 : 0
 Total NaN in row 9828 : 2
 Total NaN in row 9829 : 9
 Total NaN in row 9830 : 2
 Total NaN in row 9831 : 10
 Total NaN in row 9832 : 2
 Total NaN in row 9833 : 0
 Total NaN in row 9834 : 0
 Total NaN in row 9835 : 0
 Total NaN in row 9836 : 2
 Total NaN in row 9837 : 2
 Total NaN in row 9838 : 2
 Total NaN in row 9839 : 2
 Total NaN in row 9840 : 2
 Total NaN in row 9841 : 1
 Total NaN in row 9842 : 2
 Total NaN in row 9843 : 9
 Total NaN in row 9844 : 0
 Total NaN in row 9845 : 2
 Total NaN in row 9846 : 0
 Total NaN in row 9847 : 9
 Total NaN in row 9848 : 2
 Total NaN in row 9849 : 0
 Total NaN in row 9850 : 0
 Total NaN in row 9851 : 9
 Total NaN in row 9852 : 0
 Total NaN in row 9853 : 2
 Total NaN in row 9854 : 2
 Total NaN in row 9855 : 0
 Total NaN in row 9856 : 2
 Total NaN in row 9857 : 2
 Total NaN in row 9858 : 2
 Total NaN in row 9859 : 0
 Total NaN in row 9860 : 2
 Total NaN in row 9861 : 0
 Total NaN in row 9862 : 9
 Total NaN in row 9863 : 2
 Total NaN in row 9864 : 2
 Total NaN in row 9865 : 2
 Total NaN in row 9866 : 2
 Total NaN in row 9867 : 2
 Total NaN in row 9868 : 2
 Total NaN in row 9869 : 0
 Total NaN in row 9870 : 2
 Total NaN in row 9871 : 10
 Total NaN in row 9872 : 2
 Total NaN in row 9873 : 2
 Total NaN in row 9874 : 0
 Total NaN in row 9875 : 2
 Total NaN in row 9876 : 2
 Total NaN in row 9877 : 1
 Total NaN in row 9878 : 2
 Total NaN in row 9879 : 2
 Total NaN in row 9880 : 9
 Total NaN in row 9881 : 7
 Total NaN in row 9882 : 0
 Total NaN in row 9883 : 0
 Total NaN in row 9884 : 1
 Total NaN in row 9885 : 2
 Total NaN in row 9886 : 0
 Total NaN in row 9887 : 0
 Total NaN in row 9888 : 0
 Total NaN in row 9889 : 21
 Total NaN in row 9890 : 1
 Total NaN in row 9891 : 1
 Total NaN in row 9892 : 9
 Total NaN in row 9893 : 0
 Total NaN in row 9894 : 0
 Total NaN in row 9895 : 21
 Total NaN in row 9896 : 2
 Total NaN in row 9897 : 2
 Total NaN in row 9898 : 1
 Total NaN in row 9899 : 0
 Total NaN in row 9900 : 9
 Total NaN in row 9901 : 0
 Total NaN in row 9902 : 0
 Total NaN in row 9903 : 1
 Total NaN in row 9904 : 0
 Total NaN in row 9905 : 0
 Total NaN in row 9906 : 2
 Total NaN in row 9907 : 2
 Total NaN in row 9908 : 0
 Total NaN in row 9909 : 2
 Total NaN in row 9910 : 2
 Total NaN in row 9911 : 0
 Total NaN in row 9912 : 2
 Total NaN in row 9913 : 2
 Total NaN in row 9914 : 1
 Total NaN in row 9915 : 1
 Total NaN in row 9916 : 2
 Total NaN in row 9917 : 9
 Total NaN in row 9918 : 2
 Total NaN in row 9919 : 2
 Total NaN in row 9920 : 9
 Total NaN in row 9921 : 2
 Total NaN in row 9922 : 2
 Total NaN in row 9923 : 9
 Total NaN in row 9924 : 2
 Total NaN in row 9925 : 9
 Total NaN in row 9926 : 0
 Total NaN in row 9927 : 0
 Total NaN in row 9928 : 2
 Total NaN in row 9929 : 2
 Total NaN in row 9930 : 0
 Total NaN in row 9931 : 9
 Total NaN in row 9932 : 0
 Total NaN in row 9933 : 2
 Total NaN in row 9934 : 0
 Total NaN in row 9935 : 2
 Total NaN in row 9936 : 9
 Total NaN in row 9937 : 9
 Total NaN in row 9938 : 2
 Total NaN in row 9939 : 2
 Total NaN in row 9940 : 2
 Total NaN in row 9941 : 0
 Total NaN in row 9942 : 2
 Total NaN in row 9943 : 2
 Total NaN in row 9944 : 9
 Total NaN in row 9945 : 0
 Total NaN in row 9946 : 0
 Total NaN in row 9947 : 2
 Total NaN in row 9948 : 10
 Total NaN in row 9949 : 0
 Total NaN in row 9950 : 2
 Total NaN in row 9951 : 9
 Total NaN in row 9952 : 2
 Total NaN in row 9953 : 2
 Total NaN in row 9954 : 2
 Total NaN in row 9955 : 0
 Total NaN in row 9956 : 2
 Total NaN in row 9957 : 10
 Total NaN in row 9958 : 2
 Total NaN in row 9959 : 2
 Total NaN in row 9960 : 9
 Total NaN in row 9961 : 2
 Total NaN in row 9962 : 1
 Total NaN in row 9963 : 0
 Total NaN in row 9964 : 9
 Total NaN in row 9965 : 2
 Total NaN in row 9966 : 9
 Total NaN in row 9967 : 0
 Total NaN in row 9968 : 9
 Total NaN in row 9969 : 0
 Total NaN in row 9970 : 0
 Total NaN in row 9971 : 2
 Total NaN in row 9972 : 9
 Total NaN in row 9973 : 2
 Total NaN in row 9974 : 9
 Total NaN in row 9975 : 2
 Total NaN in row 9976 : 2
 Total NaN in row 9977 : 2
 Total NaN in row 9978 : 9
 Total NaN in row 9979 : 0
 Total NaN in row 9980 : 3
 Total NaN in row 9981 : 0
 Total NaN in row 9982 : 9
 Total NaN in row 9983 : 1
 Total NaN in row 9984 : 9
 Total NaN in row 9985 : 0
 Total NaN in row 9986 : 9
 Total NaN in row 9987 : 2
 Total NaN in row 9988 : 9
 Total NaN in row 9989 : 2
 Total NaN in row 9990 : 9
 Total NaN in row 9991 : 9
 Total NaN in row 9992 : 2
 Total NaN in row 9993 : 2
 Total NaN in row 9994 : 3
 Total NaN in row 9995 : 0
 Total NaN in row 9996 : 9
 Total NaN in row 9997 : 0
 Total NaN in row 9998 : 1
 Total NaN in row 9999 : 3
 Total NaN in row 10000 : 0
 Total NaN in row 10001 : 9
 Total NaN in row 10002 : 1
 Total NaN in row 10003 : 9
 Total NaN in row 10004 : 1
 Total NaN in row 10005 : 2
 Total NaN in row 10006 : 9
 Total NaN in row 10007 : 0
 Total NaN in row 10008 : 9
 Total NaN in row 10009 : 9

 Total NaN in row 10010 : 21
 Total NaN in row 10011 : 0
 Total NaN in row 10012 : 9
 Total NaN in row 10013 : 0
 Total NaN in row 10014 : 0
 Total NaN in row 10015 : 1
 Total NaN in row 10016 : 9
 Total NaN in row 10017 : 9
 Total NaN in row 10018 : 2
 Total NaN in row 10019 : 0
 Total NaN in row 10020 : 1
 Total NaN in row 10021 : 0
 Total NaN in row 10022 : 10
 Total NaN in row 10023 : 0
 Total NaN in row 10024 : 2
 Total NaN in row 10025 : 0
 Total NaN in row 10026 : 9
 Total NaN in row 10027 : 3
 Total NaN in row 10028 : 2
 Total NaN in row 10029 : 0
 Total NaN in row 10030 : 9
 Total NaN in row 10031 : 9
 Total NaN in row 10032 : 1
 Total NaN in row 10033 : 2
 Total NaN in row 10034 : 10
 Total NaN in row 10035 : 9
 Total NaN in row 10036 : 0
 Total NaN in row 10037 : 2
 Total NaN in row 10038 : 1
 Total NaN in row 10039 : 2
 Total NaN in row 10040 : 0
 Total NaN in row 10041 : 2
 Total NaN in row 10042 : 2
 Total NaN in row 10043 : 9
 Total NaN in row 10044 : 2
 Total NaN in row 10045 : 0
 Total NaN in row 10046 : 2
 Total NaN in row 10047 : 9
 Total NaN in row 10048 : 0
 Total NaN in row 10049 : 9
 Total NaN in row 10050 : 0
 Total NaN in row 10051 : 2
 Total NaN in row 10052 : 0
 Total NaN in row 10053 : 0
 Total NaN in row 10054 : 9
 Total NaN in row 10055 : 9
 Total NaN in row 10056 : 0
 Total NaN in row 10057 : 0
 Total NaN in row 10058 : 2
 Total NaN in row 10059 : 0
 Total NaN in row 10060 : 1
 Total NaN in row 10061 : 0
 Total NaN in row 10062 : 0
 Total NaN in row 10063 : 9
 Total NaN in row 10064 : 0
 Total NaN in row 10065 : 0
 Total NaN in row 10066 : 0
 Total NaN in row 10067 : 2
 Total NaN in row 10068 : 0
 Total NaN in row 10069 : 10
 Total NaN in row 10070 : 2
 Total NaN in row 10071 : 0
 Total NaN in row 10072 : 0
 Total NaN in row 10073 : 10
 Total NaN in row 10074 : 9
 Total NaN in row 10075 : 2
 Total NaN in row 10076 : 9
 Total NaN in row 10077 : 2
 Total NaN in row 10078 : 9
 Total NaN in row 10079 : 9
 Total NaN in row 10080 : 0
 Total NaN in row 10081 : 0
 Total NaN in row 10082 : 0
 Total NaN in row 10083 : 0
 Total NaN in row 10084 : 0
 Total NaN in row 10085 : 2
 Total NaN in row 10086 : 0
 Total NaN in row 10087 : 3
 Total NaN in row 10088 : 1
 Total NaN in row 10089 : 2
 Total NaN in row 10090 : 1
 Total NaN in row 10091 : 1
 Total NaN in row 10092 : 0
 Total NaN in row 10093 : 3
 Total NaN in row 10094 : 2
 Total NaN in row 10095 : 1
 Total NaN in row 10096 : 1
 Total NaN in row 10097 : 2
 Total NaN in row 10098 : 0
 Total NaN in row 10099 : 0
 Total NaN in row 10100 : 2
 Total NaN in row 10101 : 1
 Total NaN in row 10102 : 2
 Total NaN in row 10103 : 0
 Total NaN in row 10104 : 2
 Total NaN in row 10105 : 10
 Total NaN in row 10106 : 1
 Total NaN in row 10107 : 2
 Total NaN in row 10108 : 1
 Total NaN in row 10109 : 2
 Total NaN in row 10110 : 0
 Total NaN in row 10111 : 9
 Total NaN in row 10112 : 2
 Total NaN in row 10113 : 1
 Total NaN in row 10114 : 0
 Total NaN in row 10115 : 0
 Total NaN in row 10116 : 0
 Total NaN in row 10117 : 9
 Total NaN in row 10118 : 0
 Total NaN in row 10119 : 2
 Total NaN in row 10120 : 1
 Total NaN in row 10121 : 2
 Total NaN in row 10122 : 10
 Total NaN in row 10123 : 0
 Total NaN in row 10124 : 2
 Total NaN in row 10125 : 2
 Total NaN in row 10126 : 21
 Total NaN in row 10127 : 0
 Total NaN in row 10128 : 3
 Total NaN in row 10129 : 0
 Total NaN in row 10130 : 1
 Total NaN in row 10131 : 1
 Total NaN in row 10132 : 0
 Total NaN in row 10133 : 0
 Total NaN in row 10134 : 9
 Total NaN in row 10135 : 2
 Total NaN in row 10136 : 0
 Total NaN in row 10137 : 9
 Total NaN in row 10138 : 0
 Total NaN in row 10139 : 1
 Total NaN in row 10140 : 2
 Total NaN in row 10141 : 3
 Total NaN in row 10142 : 1
 Total NaN in row 10143 : 10
 Total NaN in row 10144 : 1
 Total NaN in row 10145 : 2
 Total NaN in row 10146 : 0
 Total NaN in row 10147 : 1
 Total NaN in row 10148 : 0
 Total NaN in row 10149 : 0
 Total NaN in row 10150 : 0
 Total NaN in row 10151 : 1
 Total NaN in row 10152 : 2
 Total NaN in row 10153 : 0
 Total NaN in row 10154 : 1
 Total NaN in row 10155 : 3
 Total NaN in row 10156 : 0
 Total NaN in row 10157 : 9
 Total NaN in row 10158 : 9
 Total NaN in row 10159 : 3
 Total NaN in row 10160 : 2
 Total NaN in row 10161 : 2
 Total NaN in row 10162 : 2
 Total NaN in row 10163 : 2
 Total NaN in row 10164 : 3
 Total NaN in row 10165 : 1
 Total NaN in row 10166 : 1
 Total NaN in row 10167 : 9
 Total NaN in row 10168 : 2
 Total NaN in row 10169 : 1
 Total NaN in row 10170 : 2
 Total NaN in row 10171 : 2
 Total NaN in row 10172 : 0
 Total NaN in row 10173 : 0
 Total NaN in row 10174 : 1
 Total NaN in row 10175 : 3
 Total NaN in row 10176 : 0
 Total NaN in row 10177 : 0
 Total NaN in row 10178 : 10
 Total NaN in row 10179 : 1
 Total NaN in row 10180 : 1
 Total NaN in row 10181 : 0
 Total NaN in row 10182 : 2
 Total NaN in row 10183 : 0
 Total NaN in row 10184 : 1
 Total NaN in row 10185 : 1
 Total NaN in row 10186 : 1
 Total NaN in row 10187 : 3
 Total NaN in row 10188 : 0
 Total NaN in row 10189 : 2
 Total NaN in row 10190 : 2
 Total NaN in row 10191 : 3
 Total NaN in row 10192 : 3
 Total NaN in row 10193 : 0
 Total NaN in row 10194 : 3
 Total NaN in row 10195 : 0
 Total NaN in row 10196 : 1
 Total NaN in row 10197 : 2
 Total NaN in row 10198 : 2
 Total NaN in row 10199 : 0
 Total NaN in row 10200 : 1
 Total NaN in row 10201 : 0
 Total NaN in row 10202 : 10
 Total NaN in row 10203 : 2
 Total NaN in row 10204 : 1
 Total NaN in row 10205 : 0
 Total NaN in row 10206 : 0
 Total NaN in row 10207 : 1
 Total NaN in row 10208 : 2
 Total NaN in row 10209 : 3
 Total NaN in row 10210 : 2
 Total NaN in row 10211 : 1
 Total NaN in row 10212 : 2
 Total NaN in row 10213 : 0
 Total NaN in row 10214 : 0
 Total NaN in row 10215 : 1
 Total NaN in row 10216 : 1
 Total NaN in row 10217 : 0
 Total NaN in row 10218 : 2
 Total NaN in row 10219 : 2
 Total NaN in row 10220 : 10
 Total NaN in row 10221 : 10
 Total NaN in row 10222 : 9
 Total NaN in row 10223 : 1
 Total NaN in row 10224 : 0
 Total NaN in row 10225 : 2
 Total NaN in row 10226 : 9
 Total NaN in row 10227 : 2
 Total NaN in row 10228 : 9
 Total NaN in row 10229 : 2
 Total NaN in row 10230 : 0
 Total NaN in row 10231 : 0
 Total NaN in row 10232 : 0
 Total NaN in row 10233 : 10
 Total NaN in row 10234 : 1
 Total NaN in row 10235 : 10
 Total NaN in row 10236 : 10
 Total NaN in row 10237 : 0
 Total NaN in row 10238 : 9
 Total NaN in row 10239 : 3
 Total NaN in row 10240 : 0
 Total NaN in row 10241 : 0
 Total NaN in row 10242 : 0
 Total NaN in row 10243 : 10
 Total NaN in row 10244 : 0
 Total NaN in row 10245 : 2
 Total NaN in row 10246 : 10
 Total NaN in row 10247 : 2
 Total NaN in row 10248 : 9
 Total NaN in row 10249 : 0
 Total NaN in row 10250 : 1
 Total NaN in row 10251 : 0
 Total NaN in row 10252 : 0
 Total NaN in row 10253 : 9
 Total NaN in row 10254 : 9
 Total NaN in row 10255 : 0
 Total NaN in row 10256 : 0
 Total NaN in row 10257 : 1
 Total NaN in row 10258 : 9
 Total NaN in row 10259 : 0
 Total NaN in row 10260 : 9
 Total NaN in row 10261 : 9
 Total NaN in row 10262 : 2
 Total NaN in row 10263 : 9
 Total NaN in row 10264 : 9
 Total NaN in row 10265 : 0
 Total NaN in row 10266 : 2
 Total NaN in row 10267 : 2
 Total NaN in row 10268 : 0
 Total NaN in row 10269 : 0
 Total NaN in row 10270 : 2
 Total NaN in row 10271 : 0
 Total NaN in row 10272 : 9
 Total NaN in row 10273 : 0
 Total NaN in row 10274 : 2
 Total NaN in row 10275 : 9
 Total NaN in row 10276 : 1
 Total NaN in row 10277 : 9
 Total NaN in row 10278 : 1
 Total NaN in row 10279 : 2
 Total NaN in row 10280 : 1
 Total NaN in row 10281 : 9
 Total NaN in row 10282 : 0
 Total NaN in row 10283 : 10
 Total NaN in row 10284 : 9
 Total NaN in row 10285 : 1
 Total NaN in row 10286 : 9
 Total NaN in row 10287 : 9
 Total NaN in row 10288 : 0
 Total NaN in row 10289 : 0
 Total NaN in row 10290 : 9
 Total NaN in row 10291 : 1
 Total NaN in row 10292 : 0
 Total NaN in row 10293 : 3
 Total NaN in row 10294 : 2
 Total NaN in row 10295 : 0
 Total NaN in row 10296 : 0
 Total NaN in row 10297 : 2
 Total NaN in row 10298 : 9
 Total NaN in row 10299 : 2
 Total NaN in row 10300 : 9
 Total NaN in row 10301 : 9
 Total NaN in row 10302 : 0
 Total NaN in row 10303 : 0
 Total NaN in row 10304 : 0
 Total NaN in row 10305 : 9
 Total NaN in row 10306 : 1
 Total NaN in row 10307 : 1
 Total NaN in row 10308 : 0
 Total NaN in row 10309 : 1
 Total NaN in row 10310 : 9
 Total NaN in row 10311 : 0
 Total NaN in row 10312 : 9
 Total NaN in row 10313 : 9
 Total NaN in row 10314 : 2
 Total NaN in row 10315 : 9
 Total NaN in row 10316 : 10
 Total NaN in row 10317 : 2
 Total NaN in row 10318 : 1
 Total NaN in row 10319 : 1
 Total NaN in row 10320 : 9
 Total NaN in row 10321 : 2
 Total NaN in row 10322 : 0
 Total NaN in row 10323 : 1
 Total NaN in row 10324 : 0
 Total NaN in row 10325 : 9
 Total NaN in row 10326 : 0
 Total NaN in row 10327 : 9
 Total NaN in row 10328 : 9
 Total NaN in row 10329 : 1
 Total NaN in row 10330 : 0
 Total NaN in row 10331 : 1
 Total NaN in row 10332 : 0
 Total NaN in row 10333 : 0
 Total NaN in row 10334 : 2
 Total NaN in row 10335 : 2
 Total NaN in row 10336 : 2
 Total NaN in row 10337 : 9
 Total NaN in row 10338 : 9
 Total NaN in row 10339 : 2
 Total NaN in row 10340 : 1
 Total NaN in row 10341 : 2
 Total NaN in row 10342 : 1
 Total NaN in row 10343 : 9
 Total NaN in row 10344 : 1
 Total NaN in row 10345 : 10
 Total NaN in row 10346 : 0
 Total NaN in row 10347 : 2
 Total NaN in row 10348 : 10
 Total NaN in row 10349 : 0
 Total NaN in row 10350 : 2
 Total NaN in row 10351 : 0
 Total NaN in row 10352 : 2
 Total NaN in row 10353 : 0
 Total NaN in row 10354 : 9
 Total NaN in row 10355 : 2
 Total NaN in row 10356 : 0
 Total NaN in row 10357 : 2
 Total NaN in row 10358 : 0
 Total NaN in row 10359 : 9
 Total NaN in row 10360 : 2
 Total NaN in row 10361 : 9
 Total NaN in row 10362 : 0
 Total NaN in row 10363 : 9
 Total NaN in row 10364 : 0
 Total NaN in row 10365 : 0
 Total NaN in row 10366 : 0
 Total NaN in row 10367 : 0
 Total NaN in row 10368 : 0
 Total NaN in row 10369 : 0
 Total NaN in row 10370 : 0
 Total NaN in row 10371 : 0
 Total NaN in row 10372 : 0
 Total NaN in row 10373 : 2
 Total NaN in row 10374 : 2
 Total NaN in row 10375 : 0
 Total NaN in row 10376 : 0
 Total NaN in row 10377 : 2

 Total NaN in row 10378 : 9
 Total NaN in row 10379 : 10
 Total NaN in row 10380 : 0
 Total NaN in row 10381 : 2
 Total NaN in row 10382 : 1
 Total NaN in row 10383 : 2
 Total NaN in row 10384 : 1
 Total NaN in row 10385 : 2
 Total NaN in row 10386 : 3
 Total NaN in row 10387 : 1
 Total NaN in row 10388 : 9
 Total NaN in row 10389 : 1
 Total NaN in row 10390 : 10
 Total NaN in row 10391 : 21
 Total NaN in row 10392 : 0
 Total NaN in row 10393 : 0
 Total NaN in row 10394 : 10
 Total NaN in row 10395 : 2
 Total NaN in row 10396 : 0
 Total NaN in row 10397 : 2
 Total NaN in row 10398 : 1
 Total NaN in row 10399 : 9
 Total NaN in row 10400 : 2
 Total NaN in row 10401 : 0
 Total NaN in row 10402 : 1
 Total NaN in row 10403 : 9
 Total NaN in row 10404 : 0
 Total NaN in row 10405 : 2
 Total NaN in row 10406 : 2
 Total NaN in row 10407 : 0
 Total NaN in row 10408 : 2
 Total NaN in row 10409 : 9
 Total NaN in row 10410 : 1
 Total NaN in row 10411 : 0
 Total NaN in row 10412 : 0
 Total NaN in row 10413 : 1
 Total NaN in row 10414 : 0
 Total NaN in row 10415 : 0
 Total NaN in row 10416 : 1
 Total NaN in row 10417 : 0
 Total NaN in row 10418 : 2
 Total NaN in row 10419 : 0
 Total NaN in row 10420 : 0
 Total NaN in row 10421 : 9
 Total NaN in row 10422 : 2
 Total NaN in row 10423 : 2
 Total NaN in row 10424 : 0
 Total NaN in row 10425 : 3
 Total NaN in row 10426 : 1
 Total NaN in row 10427 : 2
 Total NaN in row 10428 : 0
 Total NaN in row 10429 : 3
 Total NaN in row 10430 : 0
 Total NaN in row 10431 : 0
 Total NaN in row 10432 : 1
 Total NaN in row 10433 : 2
 Total NaN in row 10434 : 2
 Total NaN in row 10435 : 0
 Total NaN in row 10436 : 1
 Total NaN in row 10437 : 9
 Total NaN in row 10438 : 0
 Total NaN in row 10439 : 0
 Total NaN in row 10440 : 1
 Total NaN in row 10441 : 2
 Total NaN in row 10442 : 1
 Total NaN in row 10443 : 3
 Total NaN in row 10444 : 2
 Total NaN in row 10445 : 1
 Total NaN in row 10446 : 10
 Total NaN in row 10447 : 2
 Total NaN in row 10448 : 0
 Total NaN in row 10449 : 1
 Total NaN in row 10450 : 2
 Total NaN in row 10451 : 2
 Total NaN in row 10452 : 10
 Total NaN in row 10453 : 9
 Total NaN in row 10454 : 0
 Total NaN in row 10455 : 0
 Total NaN in row 10456 : 2
 Total NaN in row 10457 : 2
 Total NaN in row 10458 : 1
 Total NaN in row 10459 : 10
 Total NaN in row 10460 : 1
 Total NaN in row 10461 : 1
 Total NaN in row 10462 : 1
 Total NaN in row 10463 : 10
 Total NaN in row 10464 : 0
 Total NaN in row 10465 : 2
 Total NaN in row 10466 : 0
 Total NaN in row 10467 : 2
 Total NaN in row 10468 : 0
 Total NaN in row 10469 : 9
 Total NaN in row 10470 : 9
 Total NaN in row 10471 : 1
 Total NaN in row 10472 : 2
 Total NaN in row 10473 : 1
 Total NaN in row 10474 : 0
 Total NaN in row 10475 : 0
 Total NaN in row 10476 : 21
 Total NaN in row 10477 : 9
 Total NaN in row 10478 : 0
 Total NaN in row 10479 : 3
 Total NaN in row 10480 : 1
 Total NaN in row 10481 : 10
 Total NaN in row 10482 : 1
 Total NaN in row 10483 : 10
 Total NaN in row 10484 : 2
 Total NaN in row 10485 : 2
 Total NaN in row 10486 : 9
 Total NaN in row 10487 : 1
 Total NaN in row 10488 : 1
 Total NaN in row 10489 : 3
 Total NaN in row 10490 : 2
 Total NaN in row 10491 : 3
 Total NaN in row 10492 : 2
 Total NaN in row 10493 : 2
 Total NaN in row 10494 : 9
 Total NaN in row 10495 : 1
 Total NaN in row 10496 : 2
 Total NaN in row 10497 : 9
 Total NaN in row 10498 : 0
 Total NaN in row 10499 : 9
 Total NaN in row 10500 : 10
 Total NaN in row 10501 : 0
 Total NaN in row 10502 : 1
 Total NaN in row 10503 : 3
 Total NaN in row 10504 : 0
 Total NaN in row 10505 : 1
 Total NaN in row 10506 : 9
 Total NaN in row 10507 : 0
 Total NaN in row 10508 : 0
 Total NaN in row 10509 : 3
 Total NaN in row 10510 : 10
 Total NaN in row 10511 : 1
 Total NaN in row 10512 : 2
 Total NaN in row 10513 : 3
 Total NaN in row 10514 : 10
 Total NaN in row 10515 : 1
 Total NaN in row 10516 : 1
 Total NaN in row 10517 : 1
 Total NaN in row 10518 : 2
 Total NaN in row 10519 : 1
 Total NaN in row 10520 : 3
 Total NaN in row 10521 : 1
 Total NaN in row 10522 : 10
 Total NaN in row 10523 : 0
 Total NaN in row 10524 : 0
 Total NaN in row 10525 : 2
 Total NaN in row 10526 : 0
 Total NaN in row 10527 : 0
 Total NaN in row 10528 : 0
 Total NaN in row 10529 : 2
 Total NaN in row 10530 : 1
 Total NaN in row 10531 : 3
 Total NaN in row 10532 : 2
 Total NaN in row 10533 : 1
 Total NaN in row 10534 : 2
 Total NaN in row 10535 : 2
 Total NaN in row 10536 : 9
 Total NaN in row 10537 : 0
 Total NaN in row 10538 : 10
 Total NaN in row 10539 : 3
 Total NaN in row 10540 : 2
 Total NaN in row 10541 : 10
 Total NaN in row 10542 : 9
 Total NaN in row 10543 : 9
 Total NaN in row 10544 : 1
 Total NaN in row 10545 : 0
 Total NaN in row 10546 : 10
 Total NaN in row 10547 : 0
 Total NaN in row 10548 : 2
 Total NaN in row 10549 : 0
 Total NaN in row 10550 : 2
 Total NaN in row 10551 : 9
 Total NaN in row 10552 : 0
 Total NaN in row 10553 : 9
 Total NaN in row 10554 : 2
 Total NaN in row 10555 : 9
 Total NaN in row 10556 : 3
 Total NaN in row 10557 : 2
 Total NaN in row 10558 : 10
 Total NaN in row 10559 : 8
 Total NaN in row 10560 : 9
 Total NaN in row 10561 : 0
 Total NaN in row 10562 : 10
 Total NaN in row 10563 : 9
 Total NaN in row 10564 : 2
 Total NaN in row 10565 : 3
 Total NaN in row 10566 : 3
 Total NaN in row 10567 : 2
 Total NaN in row 10568 : 0
 Total NaN in row 10569 : 2
 Total NaN in row 10570 : 2
 Total NaN in row 10571 : 9
 Total NaN in row 10572 : 1
 Total NaN in row 10573 : 9
 Total NaN in row 10574 : 2
 Total NaN in row 10575 : 0
 Total NaN in row 10576 : 2
 Total NaN in row 10577 : 1
 Total NaN in row 10578 : 1
 Total NaN in row 10579 : 3
 Total NaN in row 10580 : 4
 Total NaN in row 10581 : 2
 Total NaN in row 10582 : 0
 Total NaN in row 10583 : 0
 Total NaN in row 10584 : 10
 Total NaN in row 10585 : 9
 Total NaN in row 10586 : 0
 Total NaN in row 10587 : 3
 Total NaN in row 10588 : 0
 Total NaN in row 10589 : 1
 Total NaN in row 10590 : 2
 Total NaN in row 10591 : 3
 Total NaN in row 10592 : 2
 Total NaN in row 10593 : 9
 Total NaN in row 10594 : 1
 Total NaN in row 10595 : 2
 Total NaN in row 10596 : 0
 Total NaN in row 10597 : 1
 Total NaN in row 10598 : 0
 Total NaN in row 10599 : 1
 Total NaN in row 10600 : 0
 Total NaN in row 10601 : 2
 Total NaN in row 10602 : 2
 Total NaN in row 10603 : 0
 Total NaN in row 10604 : 0
 Total NaN in row 10605 : 2
 Total NaN in row 10606 : 1
 Total NaN in row 10607 : 3
 Total NaN in row 10608 : 1
 Total NaN in row 10609 : 3
 Total NaN in row 10610 : 0
 Total NaN in row 10611 : 10
 Total NaN in row 10612 : 0
 Total NaN in row 10613 : 9
 Total NaN in row 10614 : 0
 Total NaN in row 10615 : 1
 Total NaN in row 10616 : 0
 Total NaN in row 10617 : 0
 Total NaN in row 10618 : 9
 Total NaN in row 10619 : 2
 Total NaN in row 10620 : 2
 Total NaN in row 10621 : 9
 Total NaN in row 10622 : 2
 Total NaN in row 10623 : 9
 Total NaN in row 10624 : 2
 Total NaN in row 10625 : 0
 Total NaN in row 10626 : 2
 Total NaN in row 10627 : 0
 Total NaN in row 10628 : 1
 Total NaN in row 10629 : 0
 Total NaN in row 10630 : 9
 Total NaN in row 10631 : 0
 Total NaN in row 10632 : 2
 Total NaN in row 10633 : 2
 Total NaN in row 10634 : 0
 Total NaN in row 10635 : 10
 Total NaN in row 10636 : 1
 Total NaN in row 10637 : 9
 Total NaN in row 10638 : 2
 Total NaN in row 10639 : 9
 Total NaN in row 10640 : 0
 Total NaN in row 10641 : 0
 Total NaN in row 10642 : 9
 Total NaN in row 10643 : 2
 Total NaN in row 10644 : 2
 Total NaN in row 10645 : 0
 Total NaN in row 10646 : 0
 Total NaN in row 10647 : 1
 Total NaN in row 10648 : 3
 Total NaN in row 10649 : 0
 Total NaN in row 10650 : 0
 Total NaN in row 10651 : 0
 Total NaN in row 10652 : 0
 Total NaN in row 10653 : 2
 Total NaN in row 10654 : 2
 Total NaN in row 10655 : 1
 Total NaN in row 10656 : 2
 Total NaN in row 10657 : 0
 Total NaN in row 10658 : 0
 Total NaN in row 10659 : 0
 Total NaN in row 10660 : 0
 Total NaN in row 10661 : 1
 Total NaN in row 10662 : 9
 Total NaN in row 10663 : 0
 Total NaN in row 10664 : 2
 Total NaN in row 10665 : 0
 Total NaN in row 10666 : 9
 Total NaN in row 10667 : 0
 Total NaN in row 10668 : 0
 Total NaN in row 10669 : 2
 Total NaN in row 10670 : 2
 Total NaN in row 10671 : 0
 Total NaN in row 10672 : 2
 Total NaN in row 10673 : 1
 Total NaN in row 10674 : 0
 Total NaN in row 10675 : 0
 Total NaN in row 10676 : 1
 Total NaN in row 10677 : 2
 Total NaN in row 10678 : 0

 Total NaN in row 10679 : 2
 Total NaN in row 10680 : 0
 Total NaN in row 10681 : 1
 Total NaN in row 10682 : 0
 Total NaN in row 10683 : 3
 Total NaN in row 10684 : 0
 Total NaN in row 10685 : 0
 Total NaN in row 10686 : 0
 Total NaN in row 10687 : 0
 Total NaN in row 10688 : 9
 Total NaN in row 10689 : 0
 Total NaN in row 10690 : 1
 Total NaN in row 10691 : 1
 Total NaN in row 10692 : 2
 Total NaN in row 10693 : 1
 Total NaN in row 10694 : 9
 Total NaN in row 10695 : 1
 Total NaN in row 10696 : 0
 Total NaN in row 10697 : 1
 Total NaN in row 10698 : 1
 Total NaN in row 10699 : 0
 Total NaN in row 10700 : 0
 Total NaN in row 10701 : 9
 Total NaN in row 10702 : 0
 Total NaN in row 10703 : 0
 Total NaN in row 10704 : 2
 Total NaN in row 10705 : 0
 Total NaN in row 10706 : 2
 Total NaN in row 10707 : 0
 Total NaN in row 10708 : 9
 Total NaN in row 10709 : 0
 Total NaN in row 10710 : 0
 Total NaN in row 10711 : 2
 Total NaN in row 10712 : 0
 Total NaN in row 10713 : 1
 Total NaN in row 10714 : 2
 Total NaN in row 10715 : 0
 Total NaN in row 10716 : 0
 Total NaN in row 10717 : 2
 Total NaN in row 10718 : 0
 Total NaN in row 10719 : 9
 Total NaN in row 10720 : 1
 Total NaN in row 10721 : 9
 Total NaN in row 10722 : 3
 Total NaN in row 10723 : 9
 Total NaN in row 10724 : 0
 Total NaN in row 10725 : 0
 Total NaN in row 10726 : 0
 Total NaN in row 10727 : 0
 Total NaN in row 10728 : 3
 Total NaN in row 10729 : 0
 Total NaN in row 10730 : 0
 Total NaN in row 10731 : 2
 Total NaN in row 10732 : 2
 Total NaN in row 10733 : 1
 Total NaN in row 10734 : 0
 Total NaN in row 10735 : 0
 Total NaN in row 10736 : 0
 Total NaN in row 10737 : 1
 Total NaN in row 10738 : 1
 Total NaN in row 10739 : 21
 Total NaN in row 10740 : 3
 Total NaN in row 10741 : 1
 Total NaN in row 10742 : 10
 Total NaN in row 10743 : 1
 Total NaN in row 10744 : 0
 Total NaN in row 10745 : 1
 Total NaN in row 10746 : 0
 Total NaN in row 10747 : 2
 Total NaN in row 10748 : 0
 Total NaN in row 10749 : 2
 Total NaN in row 10750 : 2
 Total NaN in row 10751 : 2
 Total NaN in row 10752 : 0
 Total NaN in row 10753 : 3
 Total NaN in row 10754 : 2
 Total NaN in row 10755 : 0
 Total NaN in row 10756 : 0
 Total NaN in row 10757 : 1
 Total NaN in row 10758 : 9
 Total NaN in row 10759 : 1
 Total NaN in row 10760 : 1
 Total NaN in row 10761 : 2
 Total NaN in row 10762 : 9
 Total NaN in row 10763 : 0
 Total NaN in row 10764 : 2
 Total NaN in row 10765 : 2
 Total NaN in row 10766 : 2
 Total NaN in row 10767 : 1
 Total NaN in row 10768 : 3
 Total NaN in row 10769 : 10
 Total NaN in row 10770 : 2
 Total NaN in row 10771 : 1
 Total NaN in row 10772 : 0
 Total NaN in row 10773 : 1
 Total NaN in row 10774 : 0
 Total NaN in row 10775 : 2
 Total NaN in row 10776 : 0
 Total NaN in row 10777 : 1
 Total NaN in row 10778 : 0
 Total NaN in row 10779 : 3
 Total NaN in row 10780 : 2
 Total NaN in row 10781 : 1
 Total NaN in row 10782 : 1
 Total NaN in row 10783 : 2
 Total NaN in row 10784 : 0
 Total NaN in row 10785 : 0
 Total NaN in row 10786 : 2
 Total NaN in row 10787 : 9
 Total NaN in row 10788 : 1
 Total NaN in row 10789 : 2
 Total NaN in row 10790 : 0
 Total NaN in row 10791 : 2
 Total NaN in row 10792 : 1
 Total NaN in row 10793 : 0
 Total NaN in row 10794 : 0
 Total NaN in row 10795 : 9
 Total NaN in row 10796 : 0
 Total NaN in row 10797 : 1
 Total NaN in row 10798 : 0
 Total NaN in row 10799 : 3
 Total NaN in row 10800 : 0
 Total NaN in row 10801 : 2
 Total NaN in row 10802 : 1
 Total NaN in row 10803 : 9
 Total NaN in row 10804 : 1
 Total NaN in row 10805 : 2
 Total NaN in row 10806 : 1
 Total NaN in row 10807 : 9
 Total NaN in row 10808 : 9
 Total NaN in row 10809 : 1
 Total NaN in row 10810 : 2
 Total NaN in row 10811 : 2
 Total NaN in row 10812 : 1
 Total NaN in row 10813 : 1
 Total NaN in row 10814 : 9
 Total NaN in row 10815 : 0
 Total NaN in row 10816 : 1
 Total NaN in row 10817 : 0
 Total NaN in row 10818 : 3
 Total NaN in row 10819 : 0
 Total NaN in row 10820 : 0
 Total NaN in row 10821 : 2
 Total NaN in row 10822 : 2
 Total NaN in row 10823 : 10
 Total NaN in row 10824 : 0
 Total NaN in row 10825 : 1
 Total NaN in row 10826 : 3
 Total NaN in row 10827 : 2
 Total NaN in row 10828 : 0
 Total NaN in row 10829 : 3
 Total NaN in row 10830 : 2
 Total NaN in row 10831 : 2
 Total NaN in row 10832 : 0
 Total NaN in row 10833 : 0
 Total NaN in row 10834 : 2
 Total NaN in row 10835 : 0
 Total NaN in row 10836 : 1
 Total NaN in row 10837 : 3
 Total NaN in row 10838 : 0
 Total NaN in row 10839 : 9
 Total NaN in row 10840 : 3
 Total NaN in row 10841 : 1
 Total NaN in row 10842 : 1
 Total NaN in row 10843 : 1
 Total NaN in row 10844 : 1
 Total NaN in row 10845 : 2
 Total NaN in row 10846 : 0
 Total NaN in row 10847 : 2
 Total NaN in row 10848 : 3
 Total NaN in row 10849 : 3
 Total NaN in row 10850 : 1
 Total NaN in row 10851 : 1
 Total NaN in row 10852 : 2
 Total NaN in row 10853 : 3
 Total NaN in row 10854 : 2
 Total NaN in row 10855 : 0
 Total NaN in row 10856 : 0
 Total NaN in row 10857 : 1
 Total NaN in row 10858 : 1
 Total NaN in row 10859 : 1
 Total NaN in row 10860 : 0
 Total NaN in row 10861 : 2
 Total NaN in row 10862 : 0
 Total NaN in row 10863 : 3
 Total NaN in row 10864 : 3
 Total NaN in row 10865 : 1
 Total NaN in row 10866 : 0
 Total NaN in row 10867 : 0
 Total NaN in row 10868 : 0
 Total NaN in row 10869 : 2
 Total NaN in row 10870 : 2
 Total NaN in row 10871 : 1
 Total NaN in row 10872 : 0
 Total NaN in row 10873 : 2
 Total NaN in row 10874 : 2
 Total NaN in row 10875 : 1
 Total NaN in row 10876 : 2
 Total NaN in row 10877 : 1
 Total NaN in row 10878 : 3
 Total NaN in row 10879 : 2
 Total NaN in row 10880 : 1
 Total NaN in row 10881 : 3
 Total NaN in row 10882 : 2
 Total NaN in row 10883 : 2
 Total NaN in row 10884 : 3
 Total NaN in row 10885 : 1
 Total NaN in row 10886 : 1
 Total NaN in row 10887 : 0
 Total NaN in row 10888 : 3
 Total NaN in row 10889 : 0
 Total NaN in row 10890 : 0
 Total NaN in row 10891 : 9
 Total NaN in row 10892 : 2
 Total NaN in row 10893 : 0
 Total NaN in row 10894 : 9
 Total NaN in row 10895 : 9
 Total NaN in row 10896 : 9
 Total NaN in row 10897 : 0
 Total NaN in row 10898 : 0
 Total NaN in row 10899 : 10
 Total NaN in row 10900 : 0
 Total NaN in row 10901 : 0
 Total NaN in row 10902 : 0
 Total NaN in row 10903 : 1
 Total NaN in row 10904 : 0
 Total NaN in row 10905 : 2
 Total NaN in row 10906 : 2
 Total NaN in row 10907 : 0
 Total NaN in row 10908 : 9
 Total NaN in row 10909 : 0
 Total NaN in row 10910 : 9
 Total NaN in row 10911 : 9
 Total NaN in row 10912 : 1
 Total NaN in row 10913 : 2
 Total NaN in row 10914 : 1
 Total NaN in row 10915 : 0
 Total NaN in row 10916 : 9
 Total NaN in row 10917 : 2
 Total NaN in row 10918 : 0
 Total NaN in row 10919 : 2
 Total NaN in row 10920 : 0
 Total NaN in row 10921 : 9
 Total NaN in row 10922 : 0
 Total NaN in row 10923 : 2
 Total NaN in row 10924 : 0
 Total NaN in row 10925 : 10
 Total NaN in row 10926 : 0
 Total NaN in row 10927 : 0
 Total NaN in row 10928 : 0
 Total NaN in row 10929 : 0
 Total NaN in row 10930 : 0
 Total NaN in row 10931 : 0
 Total NaN in row 10932 : 9
 Total NaN in row 10933 : 1
 Total NaN in row 10934 : 2
 Total NaN in row 10935 : 0
 Total NaN in row 10936 : 2
 Total NaN in row 10937 : 2
 Total NaN in row 10938 : 0
 Total NaN in row 10939 : 2
 Total NaN in row 10940 : 0
 Total NaN in row 10941 : 0
 Total NaN in row 10942 : 0
 Total NaN in row 10943 : 2
 Total NaN in row 10944 : 0
 Total NaN in row 10945 : 2
 Total NaN in row 10946 : 0
 Total NaN in row 10947 : 0
 Total NaN in row 10948 : 0
 Total NaN in row 10949 : 1
 Total NaN in row 10950 : 0
 Total NaN in row 10951 : 1
 Total NaN in row 10952 : 2
 Total NaN in row 10953 : 21
 Total NaN in row 10954 : 2
 Total NaN in row 10955 : 0
 Total NaN in row 10956 : 3
 Total NaN in row 10957 : 9
 Total NaN in row 10958 : 3
 Total NaN in row 10959 : 1
 Total NaN in row 10960 : 1
 Total NaN in row 10961 : 0
 Total NaN in row 10962 : 0
 Total NaN in row 10963 : 3
 Total NaN in row 10964 : 0
 Total NaN in row 10965 : 2
 Total NaN in row 10966 : 1
 Total NaN in row 10967 : 1
 Total NaN in row 10968 : 1
 Total NaN in row 10969 : 0
 Total NaN in row 10970 : 1
 Total NaN in row 10971 : 3
 Total NaN in row 10972 : 2
 Total NaN in row 10973 : 0
 Total NaN in row 10974 : 0

 Total NaN in row 10975 : 0
 Total NaN in row 10976 : 1
 Total NaN in row 10977 : 1
 Total NaN in row 10978 : 0
 Total NaN in row 10979 : 2
 Total NaN in row 10980 : 0
 Total NaN in row 10981 : 9
 Total NaN in row 10982 : 1
 Total NaN in row 10983 : 3
 Total NaN in row 10984 : 1
 Total NaN in row 10985 : 0
 Total NaN in row 10986 : 9
 Total NaN in row 10987 : 1
 Total NaN in row 10988 : 3
 Total NaN in row 10989 : 2
 Total NaN in row 10990 : 0
 Total NaN in row 10991 : 0
 Total NaN in row 10992 : 1
 Total NaN in row 10993 : 2
 Total NaN in row 10994 : 0
 Total NaN in row 10995 : 9
 Total NaN in row 10996 : 0
 Total NaN in row 10997 : 2
 Total NaN in row 10998 : 2
 Total NaN in row 10999 : 3
 Total NaN in row 11000 : 2
 Total NaN in row 11001 : 0
 Total NaN in row 11002 : 2
 Total NaN in row 11003 : 0
 Total NaN in row 11004 : 2
 Total NaN in row 11005 : 2
 Total NaN in row 11006 : 9
 Total NaN in row 11007 : 2
 Total NaN in row 11008 : 1
 Total NaN in row 11009 : 2
 Total NaN in row 11010 : 2
 Total NaN in row 11011 : 1
 Total NaN in row 11012 : 3
 Total NaN in row 11013 : 0
 Total NaN in row 11014 : 3
 Total NaN in row 11015 : 0
 Total NaN in row 11016 : 0
 Total NaN in row 11017 : 0
 Total NaN in row 11018 : 0
 Total NaN in row 11019 : 1
 Total NaN in row 11020 : 0
 Total NaN in row 11021 : 10
 Total NaN in row 11022 : 2
 Total NaN in row 11023 : 9
 Total NaN in row 11024 : 2
 Total NaN in row 11025 : 0
 Total NaN in row 11026 : 2
 Total NaN in row 11027 : 0
 Total NaN in row 11028 : 0
 Total NaN in row 11029 : 0
 Total NaN in row 11030 : 0
 Total NaN in row 11031 : 1
 Total NaN in row 11032 : 2
 Total NaN in row 11033 : 2
 Total NaN in row 11034 : 2
 Total NaN in row 11035 : 0
 Total NaN in row 11036 : 0
 Total NaN in row 11037 : 0
 Total NaN in row 11038 : 0
 Total NaN in row 11039 : 1
 Total NaN in row 11040 : 9
 Total NaN in row 11041 : 0
 Total NaN in row 11042 : 2
 Total NaN in row 11043 : 0
 Total NaN in row 11044 : 1
 Total NaN in row 11045 : 0
 Total NaN in row 11046 : 1
 Total NaN in row 11047 : 3
 Total NaN in row 11048 : 0
 Total NaN in row 11049 : 0
 Total NaN in row 11050 : 2
 Total NaN in row 11051 : 0
 Total NaN in row 11052 : 10
 Total NaN in row 11053 : 2
 Total NaN in row 11054 : 0
 Total NaN in row 11055 : 2
 Total NaN in row 11056 : 0
 Total NaN in row 11057 : 1
 Total NaN in row 11058 : 1
 Total NaN in row 11059 : 0
 Total NaN in row 11060 : 0
 Total NaN in row 11061 : 2
 Total NaN in row 11062 : 0
 Total NaN in row 11063 : 3
 Total NaN in row 11064 : 0
 Total NaN in row 11065 : 0
 Total NaN in row 11066 : 1
 Total NaN in row 11067 : 2
 Total NaN in row 11068 : 0
 Total NaN in row 11069 : 1
 Total NaN in row 11070 : 0
 Total NaN in row 11071 : 2
 Total NaN in row 11072 : 0
 Total NaN in row 11073 : 9
 Total NaN in row 11074 : 9
 Total NaN in row 11075 : 0
 Total NaN in row 11076 : 1
 Total NaN in row 11077 : 0
 Total NaN in row 11078 : 0
 Total NaN in row 11079 : 0
 Total NaN in row 11080 : 0
 Total NaN in row 11081 : 1
 Total NaN in row 11082 : 2
 Total NaN in row 11083 : 0
 Total NaN in row 11084 : 2
 Total NaN in row 11085 : 2
 Total NaN in row 11086 : 0
 Total NaN in row 11087 : 2
 Total NaN in row 11088 : 10
 Total NaN in row 11089 : 0
 Total NaN in row 11090 : 2
 Total NaN in row 11091 : 0
 Total NaN in row 11092 : 2
 Total NaN in row 11093 : 2
 Total NaN in row 11094 : 0
 Total NaN in row 11095 : 2
 Total NaN in row 11096 : 0
 Total NaN in row 11097 : 10
 Total NaN in row 11098 : 10
 Total NaN in row 11099 : 0
 Total NaN in row 11100 : 9
 Total NaN in row 11101 : 2
 Total NaN in row 11102 : 1
 Total NaN in row 11103 : 1
 Total NaN in row 11104 : 9
 Total NaN in row 11105 : 2
 Total NaN in row 11106 : 9
 Total NaN in row 11107 : 0
 Total NaN in row 11108 : 9
 Total NaN in row 11109 : 0
 Total NaN in row 11110 : 0
 Total NaN in row 11111 : 2
 Total NaN in row 11112 : 2
 Total NaN in row 11113 : 0
 Total NaN in row 11114 : 0
 Total NaN in row 11115 : 3
 Total NaN in row 11116 : 9
 Total NaN in row 11117 : 0
 Total NaN in row 11118 : 2
 Total NaN in row 11119 : 1
 Total NaN in row 11120 : 2
 Total NaN in row 11121 : 0
 Total NaN in row 11122 : 2
 Total NaN in row 11123 : 0
 Total NaN in row 11124 : 10
 Total NaN in row 11125 : 0
 Total NaN in row 11126 : 0
 Total NaN in row 11127 : 9
 Total NaN in row 11128 : 0
 Total NaN in row 11129 : 0
 Total NaN in row 11130 : 1
 Total NaN in row 11131 : 9
 Total NaN in row 11132 : 3
 Total NaN in row 11133 : 0
 Total NaN in row 11134 : 2
 Total NaN in row 11135 : 2
 Total NaN in row 11136 : 0
 Total NaN in row 11137 : 2
 Total NaN in row 11138 : 0
 Total NaN in row 11139 : 1
 Total NaN in row 11140 : 2
 Total NaN in row 11141 : 3
 Total NaN in row 11142 : 3
 Total NaN in row 11143 : 1
 Total NaN in row 11144 : 2
 Total NaN in row 11145 : 2
 Total NaN in row 11146 : 0
 Total NaN in row 11147 : 0
 Total NaN in row 11148 : 0
 Total NaN in row 11149 : 2
 Total NaN in row 11150 : 9
 Total NaN in row 11151 : 2
 Total NaN in row 11152 : 9
 Total NaN in row 11153 : 9
 Total NaN in row 11154 : 10
 Total NaN in row 11155 : 1
 Total NaN in row 11156 : 2
 Total NaN in row 11157 : 0
 Total NaN in row 11158 : 0
 Total NaN in row 11159 : 9
 Total NaN in row 11160 : 2
 Total NaN in row 11161 : 0
 Total NaN in row 11162 : 9
 Total NaN in row 11163 : 9
 Total NaN in row 11164 : 0
 Total NaN in row 11165 : 0
 Total NaN in row 11166 : 9
 Total NaN in row 11167 : 1
 Total NaN in row 11168 : 1
 Total NaN in row 11169 : 9
 Total NaN in row 11170 : 0
 Total NaN in row 11171 : 9
 Total NaN in row 11172 : 2
 Total NaN in row 11173 : 2
 Total NaN in row 11174 : 1
 Total NaN in row 11175 : 0
 Total NaN in row 11176 : 0
 Total NaN in row 11177 : 3
 Total NaN in row 11178 : 2
 Total NaN in row 11179 : 2
 Total NaN in row 11180 : 1
 Total NaN in row 11181 : 2
 Total NaN in row 11182 : 2
 Total NaN in row 11183 : 1
 Total NaN in row 11184 : 10
 Total NaN in row 11185 : 9
 Total NaN in row 11186 : 0
 Total NaN in row 11187 : 2
 Total NaN in row 11188 : 0
 Total NaN in row 11189 : 1
 Total NaN in row 11190 : 2
 Total NaN in row 11191 : 0
 Total NaN in row 11192 : 0
 Total NaN in row 11193 : 0
 Total NaN in row 11194 : 0
 Total NaN in row 11195 : 2
 Total NaN in row 11196 : 9
 Total NaN in row 11197 : 2
 Total NaN in row 11198 : 9
 Total NaN in row 11199 : 10
 Total NaN in row 11200 : 9
 Total NaN in row 11201 : 9
 Total NaN in row 11202 : 3
 Total NaN in row 11203 : 2
 Total NaN in row 11204 : 2
 Total NaN in row 11205 : 0
 Total NaN in row 11206 : 2
 Total NaN in row 11207 : 0
 Total NaN in row 11208 : 0
 Total NaN in row 11209 : 0
 Total NaN in row 11210 : 0
 Total NaN in row 11211 : 1
 Total NaN in row 11212 : 2
 Total NaN in row 11213 : 0
 Total NaN in row 11214 : 2
 Total NaN in row 11215 : 9
 Total NaN in row 11216 : 9
 Total NaN in row 11217 : 0
 Total NaN in row 11218 : 1
 Total NaN in row 11219 : 2
 Total NaN in row 11220 : 0
 Total NaN in row 11221 : 2
 Total NaN in row 11222 : 1
 Total NaN in row 11223 : 1
 Total NaN in row 11224 : 0
 Total NaN in row 11225 : 2
 Total NaN in row 11226 : 3
 Total NaN in row 11227 : 0
 Total NaN in row 11228 : 2
 Total NaN in row 11229 : 0
 Total NaN in row 11230 : 2
 Total NaN in row 11231 : 1
 Total NaN in row 11232 : 2
 Total NaN in row 11233 : 3
 Total NaN in row 11234 : 2
 Total NaN in row 11235 : 2
 Total NaN in row 11236 : 0
 Total NaN in row 11237 : 2
 Total NaN in row 11238 : 2
 Total NaN in row 11239 : 1
 Total NaN in row 11240 : 0
 Total NaN in row 11241 : 2
 Total NaN in row 11242 : 0
 Total NaN in row 11243 : 9
 Total NaN in row 11244 : 2
 Total NaN in row 11245 : 2
 Total NaN in row 11246 : 1
 Total NaN in row 11247 : 2
 Total NaN in row 11248 : 2
 Total NaN in row 11249 : 2
 Total NaN in row 11250 : 2
 Total NaN in row 11251 : 3
 Total NaN in row 11252 : 3
 Total NaN in row 11253 : 3
 Total NaN in row 11254 : 1
 Total NaN in row 11255 : 9
 Total NaN in row 11256 : 0
 Total NaN in row 11257 : 2
 Total NaN in row 11258 : 1
 Total NaN in row 11259 : 9
 Total NaN in row 11260 : 0
 Total NaN in row 11261 : 9
 Total NaN in row 11262 : 2
 Total NaN in row 11263 : 2
 Total NaN in row 11264 : 2
 Total NaN in row 11265 : 8
 Total NaN in row 11266 : 0
 Total NaN in row 11267 : 2
 Total NaN in row 11268 : 2
 Total NaN in row 11269 : 9
 Total NaN in row 11270 : 9
 Total NaN in row 11271 : 2
 Total NaN in row 11272 : 0
 Total NaN in row 11273 : 3

 Total NaN in row 11274 : 2
 Total NaN in row 11275 : 9
 Total NaN in row 11276 : 2
 Total NaN in row 11277 : 3
 Total NaN in row 11278 : 0
 Total NaN in row 11279 : 1
 Total NaN in row 11280 : 1
 Total NaN in row 11281 : 10
 Total NaN in row 11282 : 0
 Total NaN in row 11283 : 2
 Total NaN in row 11284 : 0
 Total NaN in row 11285 : 0
 Total NaN in row 11286 : 2
 Total NaN in row 11287 : 0
 Total NaN in row 11288 : 1
 Total NaN in row 11289 : 0
 Total NaN in row 11290 : 1
 Total NaN in row 11291 : 2
 Total NaN in row 11292 : 9
 Total NaN in row 11293 : 1
 Total NaN in row 11294 : 0
 Total NaN in row 11295 : 10
 Total NaN in row 11296 : 1
 Total NaN in row 11297 : 0
 Total NaN in row 11298 : 2
 Total NaN in row 11299 : 1
 Total NaN in row 11300 : 3
 Total NaN in row 11301 : 2
 Total NaN in row 11302 : 2
 Total NaN in row 11303 : 0
 Total NaN in row 11304 : 0
 Total NaN in row 11305 : 10
 Total NaN in row 11306 : 0
 Total NaN in row 11307 : 1
 Total NaN in row 11308 : 0
 Total NaN in row 11309 : 9
 Total NaN in row 11310 : 2
 Total NaN in row 11311 : 0
 Total NaN in row 11312 : 9
 Total NaN in row 11313 : 1
 Total NaN in row 11314 : 2
 Total NaN in row 11315 : 2
 Total NaN in row 11316 : 0
 Total NaN in row 11317 : 0
 Total NaN in row 11318 : 0
 Total NaN in row 11319 : 10
 Total NaN in row 11320 : 1
 Total NaN in row 11321 : 0
 Total NaN in row 11322 : 0
 Total NaN in row 11323 : 2
 Total NaN in row 11324 : 1
 Total NaN in row 11325 : 0
 Total NaN in row 11326 : 1
 Total NaN in row 11327 : 0
 Total NaN in row 11328 : 1
 Total NaN in row 11329 : 0
 Total NaN in row 11330 : 2
 Total NaN in row 11331 : 9
 Total NaN in row 11332 : 2
 Total NaN in row 11333 : 9
 Total NaN in row 11334 : 0
 Total NaN in row 11335 : 21
 Total NaN in row 11336 : 1
 Total NaN in row 11337 : 0
 Total NaN in row 11338 : 1
 Total NaN in row 11339 : 2
 Total NaN in row 11340 : 1
 Total NaN in row 11341 : 1
 Total NaN in row 11342 : 1
 Total NaN in row 11343 : 3
 Total NaN in row 11344 : 1
 Total NaN in row 11345 : 0
 Total NaN in row 11346 : 0
 Total NaN in row 11347 : 2
 Total NaN in row 11348 : 2
 Total NaN in row 11349 : 21
 Total NaN in row 11350 : 2
 Total NaN in row 11351 : 9
 Total NaN in row 11352 : 0
 Total NaN in row 11353 : 0
 Total NaN in row 11354 : 2
 Total NaN in row 11355 : 0
 Total NaN in row 11356 : 3
 Total NaN in row 11357 : 2
 Total NaN in row 11358 : 9
 Total NaN in row 11359 : 1
 Total NaN in row 11360 : 2
 Total NaN in row 11361 : 2
 Total NaN in row 11362 : 0
 Total NaN in row 11363 : 2
 Total NaN in row 11364 : 2
 Total NaN in row 11365 : 0
 Total NaN in row 11366 : 3
 Total NaN in row 11367 : 10
 Total NaN in row 11368 : 1
 Total NaN in row 11369 : 0
 Total NaN in row 11370 : 2
 Total NaN in row 11371 : 0
 Total NaN in row 11372 : 3
 Total NaN in row 11373 : 2
 Total NaN in row 11374 : 0
 Total NaN in row 11375 : 2
 Total NaN in row 11376 : 0
 Total NaN in row 11377 : 2
 Total NaN in row 11378 : 1
 Total NaN in row 11379 : 2
 Total NaN in row 11380 : 0
 Total NaN in row 11381 : 10
 Total NaN in row 11382 : 3
 Total NaN in row 11383 : 0
 Total NaN in row 11384 : 0
 Total NaN in row 11385 : 2
 Total NaN in row 11386 : 1
 Total NaN in row 11387 : 2
 Total NaN in row 11388 : 0
 Total NaN in row 11389 : 0
 Total NaN in row 11390 : 2
 Total NaN in row 11391 : 1
 Total NaN in row 11392 : 0
 Total NaN in row 11393 : 9
 Total NaN in row 11394 : 0
 Total NaN in row 11395 : 1
 Total NaN in row 11396 : 2
 Total NaN in row 11397 : 10
 Total NaN in row 11398 : 3
 Total NaN in row 11399 : 2
 Total NaN in row 11400 : 1
 Total NaN in row 11401 : 2
 Total NaN in row 11402 : 1
 Total NaN in row 11403 : 1
 Total NaN in row 11404 : 2
 Total NaN in row 11405 : 9
 Total NaN in row 11406 : 1
 Total NaN in row 11407 : 2
 Total NaN in row 11408 : 2
 Total NaN in row 11409 : 0
 Total NaN in row 11410 : 1
 Total NaN in row 11411 : 9
 Total NaN in row 11412 : 9
 Total NaN in row 11413 : 0
 Total NaN in row 11414 : 1
 Total NaN in row 11415 : 1
 Total NaN in row 11416 : 2
 Total NaN in row 11417 : 1
 Total NaN in row 11418 : 2
 Total NaN in row 11419 : 10
 Total NaN in row 11420 : 1
 Total NaN in row 11421 : 3
 Total NaN in row 11422 : 2
 Total NaN in row 11423 : 0
 Total NaN in row 11424 : 1
 Total NaN in row 11425 : 2
 Total NaN in row 11426 : 2
 Total NaN in row 11427 : 9
 Total NaN in row 11428 : 0
 Total NaN in row 11429 : 1
 Total NaN in row 11430 : 1
 Total NaN in row 11431 : 0
 Total NaN in row 11432 : 1
 Total NaN in row 11433 : 0
 Total NaN in row 11434 : 1
 Total NaN in row 11435 : 1
 Total NaN in row 11436 : 0
 Total NaN in row 11437 : 3
 Total NaN in row 11438 : 0
 Total NaN in row 11439 : 0
 Total NaN in row 11440 : 0
 Total NaN in row 11441 : 2
 Total NaN in row 11442 : 9
 Total NaN in row 11443 : 2
 Total NaN in row 11444 : 2
 Total NaN in row 11445 : 0
 Total NaN in row 11446 : 1
 Total NaN in row 11447 : 1
 Total NaN in row 11448 : 0
 Total NaN in row 11449 : 10
 Total NaN in row 11450 : 9
 Total NaN in row 11451 : 1
 Total NaN in row 11452 : 0
 Total NaN in row 11453 : 3
 Total NaN in row 11454 : 9
 Total NaN in row 11455 : 0
 Total NaN in row 11456 : 9
 Total NaN in row 11457 : 1
 Total NaN in row 11458 : 0
 Total NaN in row 11459 : 0
 Total NaN in row 11460 : 2
 Total NaN in row 11461 : 10
 Total NaN in row 11462 : 0
 Total NaN in row 11463 : 2
 Total NaN in row 11464 : 1
 Total NaN in row 11465 : 3
 Total NaN in row 11466 : 2
 Total NaN in row 11467 : 0
 Total NaN in row 11468 : 0
 Total NaN in row 11469 : 2
 Total NaN in row 11470 : 1
 Total NaN in row 11471 : 3
 Total NaN in row 11472 : 0
 Total NaN in row 11473 : 0
 Total NaN in row 11474 : 1
 Total NaN in row 11475 : 0
 Total NaN in row 11476 : 1
 Total NaN in row 11477 : 2
 Total NaN in row 11478 : 3
 Total NaN in row 11479 : 1
 Total NaN in row 11480 : 0
 Total NaN in row 11481 : 0
 Total NaN in row 11482 : 2
 Total NaN in row 11483 : 0
 Total NaN in row 11484 : 0
 Total NaN in row 11485 : 2
 Total NaN in row 11486 : 1
 Total NaN in row 11487 : 1
 Total NaN in row 11488 : 0
 Total NaN in row 11489 : 0
 Total NaN in row 11490 : 9
 Total NaN in row 11491 : 1
 Total NaN in row 11492 : 0
 Total NaN in row 11493 : 2
 Total NaN in row 11494 : 2
 Total NaN in row 11495 : 2
 Total NaN in row 11496 : 1
 Total NaN in row 11497 : 1
 Total NaN in row 11498 : 0
 Total NaN in row 11499 : 0
 Total NaN in row 11500 : 0
 Total NaN in row 11501 : 0
 Total NaN in row 11502 : 0
 Total NaN in row 11503 : 0
 Total NaN in row 11504 : 2
 Total NaN in row 11505 : 0
 Total NaN in row 11506 : 3
 Total NaN in row 11507 : 1
 Total NaN in row 11508 : 3
 Total NaN in row 11509 : 3
 Total NaN in row 11510 : 9
 Total NaN in row 11511 : 2
 Total NaN in row 11512 : 0
 Total NaN in row 11513 : 2
 Total NaN in row 11514 : 1
 Total NaN in row 11515 : 3
 Total NaN in row 11516 : 9
 Total NaN in row 11517 : 3
 Total NaN in row 11518 : 0
 Total NaN in row 11519 : 0
 Total NaN in row 11520 : 1
 Total NaN in row 11521 : 2
 Total NaN in row 11522 : 2
 Total NaN in row 11523 : 1
 Total NaN in row 11524 : 0
 Total NaN in row 11525 : 1
 Total NaN in row 11526 : 2
 Total NaN in row 11527 : 2
 Total NaN in row 11528 : 1
 Total NaN in row 11529 : 2
 Total NaN in row 11530 : 0
 Total NaN in row 11531 : 1
 Total NaN in row 11532 : 3
 Total NaN in row 11533 : 0
 Total NaN in row 11534 : 1
 Total NaN in row 11535 : 1
 Total NaN in row 11536 : 9
 Total NaN in row 11537 : 0
 Total NaN in row 11538 : 0
 Total NaN in row 11539 : 1
 Total NaN in row 11540 : 0
 Total NaN in row 11541 : 1
 Total NaN in row 11542 : 1
 Total NaN in row 11543 : 3
 Total NaN in row 11544 : 2
 Total NaN in row 11545 : 3
 Total NaN in row 11546 : 0
 Total NaN in row 11547 : 2
 Total NaN in row 11548 : 10
 Total NaN in row 11549 : 0
 Total NaN in row 11550 : 0
 Total NaN in row 11551 : 9
 Total NaN in row 11552 : 3
 Total NaN in row 11553 : 21
 Total NaN in row 11554 : 0
 Total NaN in row 11555 : 1
 Total NaN in row 11556 : 2
 Total NaN in row 11557 : 2
 Total NaN in row 11558 : 2
 Total NaN in row 11559 : 10
 Total NaN in row 11560 : 3
 Total NaN in row 11561 : 2
 Total NaN in row 11562 : 2
 Total NaN in row 11563 : 0
 Total NaN in row 11564 : 10
 Total NaN in row 11565 : 2
 Total NaN in row 11566 : 2
 Total NaN in row 11567 : 1
 Total NaN in row 11568 : 1
 Total NaN in row 11569 : 1
 Total NaN in row 11570 : 0
 Total NaN in row 11571 : 1
 Total NaN in row 11572 : 2
 Total NaN in row 11573 : 2
 Total NaN in row 11574 : 2
 Total NaN in row 11575 : 0
 Total NaN in row 11576 : 3
 Total NaN in row 11577 : 0
 Total NaN in row 11578 : 3
 Total NaN in row 11579 : 0
 Total NaN in row 11580 : 3
 Total NaN in row 11581 : 1
 Total NaN in row 11582 : 0
 Total NaN in row 11583 : 2
 Total NaN in row 11584 : 0
 Total NaN in row 11585 : 1
 Total NaN in row 11586 : 0
 Total NaN in row 11587 : 9
 Total NaN in row 11588 : 0
 Total NaN in row 11589 : 0
 Total NaN in row 11590 : 0
 Total NaN in row 11591 : 9

 Total NaN in row 11592 : 1
 Total NaN in row 11593 : 2
 Total NaN in row 11594 : 0
 Total NaN in row 11595 : 1
 Total NaN in row 11596 : 0
 Total NaN in row 11597 : 1
 Total NaN in row 11598 : 0
 Total NaN in row 11599 : 2
 Total NaN in row 11600 : 3
 Total NaN in row 11601 : 1
 Total NaN in row 11602 : 0
 Total NaN in row 11603 : 10
 Total NaN in row 11604 : 0
 Total NaN in row 11605 : 0
 Total NaN in row 11606 : 9
 Total NaN in row 11607 : 1
 Total NaN in row 11608 : 9
 Total NaN in row 11609 : 2
 Total NaN in row 11610 : 1
 Total NaN in row 11611 : 9
 Total NaN in row 11612 : 9
 Total NaN in row 11613 : 9
 Total NaN in row 11614 : 0
 Total NaN in row 11615 : 9
 Total NaN in row 11616 : 0
 Total NaN in row 11617 : 9
 Total NaN in row 11618 : 1
 Total NaN in row 11619 : 9
 Total NaN in row 11620 : 2
 Total NaN in row 11621 : 0
 Total NaN in row 11622 : 2
 Total NaN in row 11623 : 0
 Total NaN in row 11624 : 0
 Total NaN in row 11625 : 0
 Total NaN in row 11626 : 9
 Total NaN in row 11627 : 0
 Total NaN in row 11628 : 0
 Total NaN in row 11629 : 2
 Total NaN in row 11630 : 0
 Total NaN in row 11631 : 9
 Total NaN in row 11632 : 0
 Total NaN in row 11633 : 1
 Total NaN in row 11634 : 2
 Total NaN in row 11635 : 0
 Total NaN in row 11636 : 9
 Total NaN in row 11637 : 1
 Total NaN in row 11638 : 10
 Total NaN in row 11639 : 2
 Total NaN in row 11640 : 2
 Total NaN in row 11641 : 9
 Total NaN in row 11642 : 9
 Total NaN in row 11643 : 0
 Total NaN in row 11644 : 1
 Total NaN in row 11645 : 0
 Total NaN in row 11646 : 9
 Total NaN in row 11647 : 1
 Total NaN in row 11648 : 0
 Total NaN in row 11649 : 1
 Total NaN in row 11650 : 0
 Total NaN in row 11651 : 0
 Total NaN in row 11652 : 9
 Total NaN in row 11653 : 0
 Total NaN in row 11654 : 9
 Total NaN in row 11655 : 2
 Total NaN in row 11656 : 0
 Total NaN in row 11657 : 0
 Total NaN in row 11658 : 3
 Total NaN in row 11659 : 1
 Total NaN in row 11660 : 0
 Total NaN in row 11661 : 1
 Total NaN in row 11662 : 0
 Total NaN in row 11663 : 9
 Total NaN in row 11664 : 2
 Total NaN in row 11665 : 0
 Total NaN in row 11666 : 1
 Total NaN in row 11667 : 9
 Total NaN in row 11668 : 0
 Total NaN in row 11669 : 0
 Total NaN in row 11670 : 9
 Total NaN in row 11671 : 2
 Total NaN in row 11672 : 0
 Total NaN in row 11673 : 1
 Total NaN in row 11674 : 0
 Total NaN in row 11675 : 9
 Total NaN in row 11676 : 0
 Total NaN in row 11677 : 1
 Total NaN in row 11678 : 3
 Total NaN in row 11679 : 0
 Total NaN in row 11680 : 3
 Total NaN in row 11681 : 9
 Total NaN in row 11682 : 10
 Total NaN in row 11683 : 1
 Total NaN in row 11684 : 1
 Total NaN in row 11685 : 1
 Total NaN in row 11686 : 0
 Total NaN in row 11687 : 1
 Total NaN in row 11688 : 2
 Total NaN in row 11689 : 0
 Total NaN in row 11690 : 1
 Total NaN in row 11691 : 0
 Total NaN in row 11692 : 2
 Total NaN in row 11693 : 9
 Total NaN in row 11694 : 0
 Total NaN in row 11695 : 9
 Total NaN in row 11696 : 0
 Total NaN in row 11697 : 0
 Total NaN in row 11698 : 3
 Total NaN in row 11699 : 1
 Total NaN in row 11700 : 0
 Total NaN in row 11701 : 1
 Total NaN in row 11702 : 10
 Total NaN in row 11703 : 0
 Total NaN in row 11704 : 1
 Total NaN in row 11705 : 1
 Total NaN in row 11706 : 0
 Total NaN in row 11707 : 0
 Total NaN in row 11708 : 2
 Total NaN in row 11709 : 1
 Total NaN in row 11710 : 2
 Total NaN in row 11711 : 0
 Total NaN in row 11712 : 2
 Total NaN in row 11713 : 3
 Total NaN in row 11714 : 2
 Total NaN in row 11715 : 9
 Total NaN in row 11716 : 1
 Total NaN in row 11717 : 2
 Total NaN in row 11718 : 9
 Total NaN in row 11719 : 2
 Total NaN in row 11720 : 9
 Total NaN in row 11721 : 0
 Total NaN in row 11722 : 9
 Total NaN in row 11723 : 2
 Total NaN in row 11724 : 1
 Total NaN in row 11725 : 0
 Total NaN in row 11726 : 0
 Total NaN in row 11727 : 1
 Total NaN in row 11728 : 3
 Total NaN in row 11729 : 0
 Total NaN in row 11730 : 0
 Total NaN in row 11731 : 2
 Total NaN in row 11732 : 0
 Total NaN in row 11733 : 1
 Total NaN in row 11734 : 0
 Total NaN in row 11735 : 2
 Total NaN in row 11736 : 0
 Total NaN in row 11737 : 1
 Total NaN in row 11738 : 2
 Total NaN in row 11739 : 0
 Total NaN in row 11740 : 2
 Total NaN in row 11741 : 9
 Total NaN in row 11742 : 0
 Total NaN in row 11743 : 9
 Total NaN in row 11744 : 9
 Total NaN in row 11745 : 1
 Total NaN in row 11746 : 2
 Total NaN in row 11747 : 3
 Total NaN in row 11748 : 1
 Total NaN in row 11749 : 0
 Total NaN in row 11750 : 1
 Total NaN in row 11751 : 0
 Total NaN in row 11752 : 9
 Total NaN in row 11753 : 0
 Total NaN in row 11754 : 0
 Total NaN in row 11755 : 2
 Total NaN in row 11756 : 21
 Total NaN in row 11757 : 9
 Total NaN in row 11758 : 0
 Total NaN in row 11759 : 2
 Total NaN in row 11760 : 2
 Total NaN in row 11761 : 2
 Total NaN in row 11762 : 9
 Total NaN in row 11763 : 0
 Total NaN in row 11764 : 1
 Total NaN in row 11765 : 0
 Total NaN in row 11766 : 0
 Total NaN in row 11767 : 1
 Total NaN in row 11768 : 9
 Total NaN in row 11769 : 2
 Total NaN in row 11770 : 1
 Total NaN in row 11771 : 0
 Total NaN in row 11772 : 2
 Total NaN in row 11773 : 2
 Total NaN in row 11774 : 0
 Total NaN in row 11775 : 1
 Total NaN in row 11776 : 2
 Total NaN in row 11777 : 9
 Total NaN in row 11778 : 9
 Total NaN in row 11779 : 1
 Total NaN in row 11780 : 1
 Total NaN in row 11781 : 9
 Total NaN in row 11782 : 0
 Total NaN in row 11783 : 0
 Total NaN in row 11784 : 0
 Total NaN in row 11785 : 1
 Total NaN in row 11786 : 2
 Total NaN in row 11787 : 2
 Total NaN in row 11788 : 0
 Total NaN in row 11789 : 0
 Total NaN in row 11790 : 0
 Total NaN in row 11791 : 0
 Total NaN in row 11792 : 0
 Total NaN in row 11793 : 1
 Total NaN in row 11794 : 1
 Total NaN in row 11795 : 0
 Total NaN in row 11796 : 0
 Total NaN in row 11797 : 9
 Total NaN in row 11798 : 1
 Total NaN in row 11799 : 3
 Total NaN in row 11800 : 0
 Total NaN in row 11801 : 9
 Total NaN in row 11802 : 2
 Total NaN in row 11803 : 1
 Total NaN in row 11804 : 1
 Total NaN in row 11805 : 0
 Total NaN in row 11806 : 9
 Total NaN in row 11807 : 0
 Total NaN in row 11808 : 1
 Total NaN in row 11809 : 0
 Total NaN in row 11810 : 2
 Total NaN in row 11811 : 9
 Total NaN in row 11812 : 0
 Total NaN in row 11813 : 2
 Total NaN in row 11814 : 0
 Total NaN in row 11815 : 9
 Total NaN in row 11816 : 0
 Total NaN in row 11817 : 0
 Total NaN in row 11818 : 1
 Total NaN in row 11819 : 2
 Total NaN in row 11820 : 2
 Total NaN in row 11821 : 0
 Total NaN in row 11822 : 0
 Total NaN in row 11823 : 1
 Total NaN in row 11824 : 2
 Total NaN in row 11825 : 0
 Total NaN in row 11826 : 1
 Total NaN in row 11827 : 1
 Total NaN in row 11828 : 9
 Total NaN in row 11829 : 2
 Total NaN in row 11830 : 0
 Total NaN in row 11831 : 0
 Total NaN in row 11832 : 3
 Total NaN in row 11833 : 9
 Total NaN in row 11834 : 1
 Total NaN in row 11835 : 2
 Total NaN in row 11836 : 1
 Total NaN in row 11837 : 1
 Total NaN in row 11838 : 0
 Total NaN in row 11839 : 9
 Total NaN in row 11840 : 3
 Total NaN in row 11841 : 0
 Total NaN in row 11842 : 2
 Total NaN in row 11843 : 0
 Total NaN in row 11844 : 2
 Total NaN in row 11845 : 0
 Total NaN in row 11846 : 10
 Total NaN in row 11847 : 0
 Total NaN in row 11848 : 2
 Total NaN in row 11849 : 0
 Total NaN in row 11850 : 1
 Total NaN in row 11851 : 3
 Total NaN in row 11852 : 1
 Total NaN in row 11853 : 2
 Total NaN in row 11854 : 0
 Total NaN in row 11855 : 0
 Total NaN in row 11856 : 0
 Total NaN in row 11857 : 1
 Total NaN in row 11858 : 1
 Total NaN in row 11859 : 0
 Total NaN in row 11860 : 0
 Total NaN in row 11861 : 1
 Total NaN in row 11862 : 2
 Total NaN in row 11863 : 0
 Total NaN in row 11864 : 2
 Total NaN in row 11865 : 0
 Total NaN in row 11866 : 2
 Total NaN in row 11867 : 2
 Total NaN in row 11868 : 0
 Total NaN in row 11869 : 2
 Total NaN in row 11870 : 9
 Total NaN in row 11871 : 2
 Total NaN in row 11872 : 1
 Total NaN in row 11873 : 0
 Total NaN in row 11874 : 2
 Total NaN in row 11875 : 0
 Total NaN in row 11876 : 2
 Total NaN in row 11877 : 2
 Total NaN in row 11878 : 0
 Total NaN in row 11879 : 1
 Total NaN in row 11880 : 1
 Total NaN in row 11881 : 2
 Total NaN in row 11882 : 0
 Total NaN in row 11883 : 1
 Total NaN in row 11884 : 2
 Total NaN in row 11885 : 9
 Total NaN in row 11886 : 2
 Total NaN in row 11887 : 0
 Total NaN in row 11888 : 0
 Total NaN in row 11889 : 2
 Total NaN in row 11890 : 2
 Total NaN in row 11891 : 1
 Total NaN in row 11892 : 1
 Total NaN in row 11893 : 2
 Total NaN in row 11894 : 0
 Total NaN in row 11895 : 0
 Total NaN in row 11896 : 0
 Total NaN in row 11897 : 2
 Total NaN in row 11898 : 2
 Total NaN in row 11899 : 0
 Total NaN in row 11900 : 0
 Total NaN in row 11901 : 0
 Total NaN in row 11902 : 1
 Total NaN in row 11903 : 0
 Total NaN in row 11904 : 2
 Total NaN in row 11905 : 0
 Total NaN in row 11906 : 1
 Total NaN in row 11907 : 1
 Total NaN in row 11908 : 1
 Total NaN in row 11909 : 2
 Total NaN in row 11910 : 0
 Total NaN in row 11911 : 2
 Total NaN in row 11912 : 2
 Total NaN in row 11913 : 0
 Total NaN in row 11914 : 0
 Total NaN in row 11915 : 0
 Total NaN in row 11916 : 0
 Total NaN in row 11917 : 0
 Total NaN in row 11918 : 0
 Total NaN in row 11919 : 2
 Total NaN in row 11920 : 1
 Total NaN in row 11921 : 1
 Total NaN in row 11922 : 9
 Total NaN in row 11923 : 2
 Total NaN in row 11924 : 0
 Total NaN in row 11925 : 0
 Total NaN in row 11926 : 0
 Total NaN in row 11927 : 2
 Total NaN in row 11928 : 0
 Total NaN in row 11929 : 2
 Total NaN in row 11930 : 0
 Total NaN in row 11931 : 2
 Total NaN in row 11932 : 1
 Total NaN in row 11933 : 9
 Total NaN in row 11934 : 2
 Total NaN in row 11935 : 2
 Total NaN in row 11936 : 0
 Total NaN in row 11937 : 2
 Total NaN in row 11938 : 1
 Total NaN in row 11939 : 2
 Total NaN in row 11940 : 9
 Total NaN in row 11941 : 9
 Total NaN in row 11942 : 9
 Total NaN in row 11943 : 9
 Total NaN in row 11944 : 10
 Total NaN in row 11945 : 10
 Total NaN in row 11946 : 2
 Total NaN in row 11947 : 10
 Total NaN in row 11948 : 9
 Total NaN in row 11949 : 9
 Total NaN in row 11950 : 9
 Total NaN in row 11951 : 9
 Total NaN in row 11952 : 9
 Total NaN in row 11953 : 10
 Total NaN in row 11954 : 0
 Total NaN in row 11955 : 9
 Total NaN in row 11956 : 9
 Total NaN in row 11957 : 9
 Total NaN in row 11958 : 2
 Total NaN in row 11959 : 1
 Total NaN in row 11960 : 9
 Total NaN in row 11961 : 2
 Total NaN in row 11962 : 9
 Total NaN in row 11963 : 9
 Total NaN in row 11964 : 7
 Total NaN in row 11965 : 0
 Total NaN in row 11966 : 9
 Total NaN in row 11967 : 0
 Total NaN in row 11968 : 9
 Total NaN in row 11969 : 1
 Total NaN in row 11970 : 9
 Total NaN in row 11971 : 9
 Total NaN in row 11972 : 9
 Total NaN in row 11973 : 10
 Total NaN in row 11974 : 9
 Total NaN in row 11975 : 1
 Total NaN in row 11976 : 9
 Total NaN in row 11977 : 1
 Total NaN in row 11978 : 1
 Total NaN in row 11979 : 2
 Total NaN in row 11980 : 1
 Total NaN in row 11981 : 0
 Total NaN in row 11982 : 0
 Total NaN in row 11983 : 2
 Total NaN in row 11984 : 9
 Total NaN in row 11985 : 0
 Total NaN in row 11986 : 0
 Total NaN in row 11987 : 1
 Total NaN in row 11988 : 1
 Total NaN in row 11989 : 0
 Total NaN in row 11990 : 9
 Total NaN in row 11991 : 3
 Total NaN in row 11992 : 0
 Total NaN in row 11993 : 0
 Total NaN in row 11994 : 1
 Total NaN in row 11995 : 2
 Total NaN in row 11996 : 1
 Total NaN in row 11997 : 0
 Total NaN in row 11998 : 1
 Total NaN in row 11999 : 2
 Total NaN in row 12000 : 2
 Total NaN in row 12001 : 9
 Total NaN in row 12002 : 0
 Total NaN in row 12003 : 9
 Total NaN in row 12004 : 0
 Total NaN in row 12005 : 1
 Total NaN in row 12006 : 9
 Total NaN in row 12007 : 1
 Total NaN in row 12008 : 2
 Total NaN in row 12009 : 2
 Total NaN in row 12010 : 0

 Total NaN in row 12011 : 1
 Total NaN in row 12012 : 9
 Total NaN in row 12013 : 0
 Total NaN in row 12014 : 2
 Total NaN in row 12015 : 1
 Total NaN in row 12016 : 2
 Total NaN in row 12017 : 1
 Total NaN in row 12018 : 2
 Total NaN in row 12019 : 9
 Total NaN in row 12020 : 0
 Total NaN in row 12021 : 3
 Total NaN in row 12022 : 1
 Total NaN in row 12023 : 0
 Total NaN in row 12024 : 1
 Total NaN in row 12025 : 1
 Total NaN in row 12026 : 0
 Total NaN in row 12027 : 1
 Total NaN in row 12028 : 0
 Total NaN in row 12029 : 9
 Total NaN in row 12030 : 2
 Total NaN in row 12031 : 10
 Total NaN in row 12032 : 0
 Total NaN in row 12033 : 9
 Total NaN in row 12034 : 2
 Total NaN in row 12035 : 0
 Total NaN in row 12036 : 9
 Total NaN in row 12037 : 2
 Total NaN in row 12038 : 1
 Total NaN in row 12039 : 1
 Total NaN in row 12040 : 2
 Total NaN in row 12041 : 9
 Total NaN in row 12042 : 2
 Total NaN in row 12043 : 9
 Total NaN in row 12044 : 1
 Total NaN in row 12045 : 0
 Total NaN in row 12046 : 2
 Total NaN in row 12047 : 0
 Total NaN in row 12048 : 0
 Total NaN in row 12049 : 2
 Total NaN in row 12050 : 0
 Total NaN in row 12051 : 2
 Total NaN in row 12052 : 0
 Total NaN in row 12053 : 2
 Total NaN in row 12054 : 1
 Total NaN in row 12055 : 0
 Total NaN in row 12056 : 2
 Total NaN in row 12057 : 1
 Total NaN in row 12058 : 0
 Total NaN in row 12059 : 0
 Total NaN in row 12060 : 2
 Total NaN in row 12061 : 10
 Total NaN in row 12062 : 0
 Total NaN in row 12063 : 0
 Total NaN in row 12064 : 2
 Total NaN in row 12065 : 2
 Total NaN in row 12066 : 1
 Total NaN in row 12067 : 0
 Total NaN in row 12068 : 3
 Total NaN in row 12069 : 0
 Total NaN in row 12070 : 1
 Total NaN in row 12071 : 10
 Total NaN in row 12072 : 0
 Total NaN in row 12073 : 1
 Total NaN in row 12074 : 9
 Total NaN in row 12075 : 10
 Total NaN in row 12076 : 2
 Total NaN in row 12077 : 10
 Total NaN in row 12078 : 2
 Total NaN in row 12079 : 1
 Total NaN in row 12080 : 9
 Total NaN in row 12081 : 0
 Total NaN in row 12082 : 0
 Total NaN in row 12083 : 1
 Total NaN in row 12084 : 0
 Total NaN in row 12085 : 3
 Total NaN in row 12086 : 1
 Total NaN in row 12087 : 9
 Total NaN in row 12088 : 21
 Total NaN in row 12089 : 0
 Total NaN in row 12090 : 2
 Total NaN in row 12091 : 2
 Total NaN in row 12092 : 2
 Total NaN in row 12093 : 2
 Total NaN in row 12094 : 1
 Total NaN in row 12095 : 0
 Total NaN in row 12096 : 0
 Total NaN in row 12097 : 9
 Total NaN in row 12098 : 1
 Total NaN in row 12099 : 0
 Total NaN in row 12100 : 2
 Total NaN in row 12101 : 0
 Total NaN in row 12102 : 0
 Total NaN in row 12103 : 9
 Total NaN in row 12104 : 0
 Total NaN in row 12105 : 0
 Total NaN in row 12106 : 9
 Total NaN in row 12107 : 9
 Total NaN in row 12108 : 2
 Total NaN in row 12109 : 2
 Total NaN in row 12110 : 2
 Total NaN in row 12111 : 9
 Total NaN in row 12112 : 2
 Total NaN in row 12113 : 2
 Total NaN in row 12114 : 1
 Total NaN in row 12115 : 0
 Total NaN in row 12116 : 0
 Total NaN in row 12117 : 2
 Total NaN in row 12118 : 0
 Total NaN in row 12119 : 1
 Total NaN in row 12120 : 1
 Total NaN in row 12121 : 0
 Total NaN in row 12122 : 2
 Total NaN in row 12123 : 9
 Total NaN in row 12124 : 2
 Total NaN in row 12125 : 2
 Total NaN in row 12126 : 0
 Total NaN in row 12127 : 10
 Total NaN in row 12128 : 9
 Total NaN in row 12129 : 9
 Total NaN in row 12130 : 9
 Total NaN in row 12131 : 1
 Total NaN in row 12132 : 9
 Total NaN in row 12133 : 2
 Total NaN in row 12134 : 9
 Total NaN in row 12135 : 0
 Total NaN in row 12136 : 9
 Total NaN in row 12137 : 9
 Total NaN in row 12138 : 1
 Total NaN in row 12139 : 9
 Total NaN in row 12140 : 0
 Total NaN in row 12141 : 0
 Total NaN in row 12142 : 9
 Total NaN in row 12143 : 2
 Total NaN in row 12144 : 0
 Total NaN in row 12145 : 9
 Total NaN in row 12146 : 2
 Total NaN in row 12147 : 0
 Total NaN in row 12148 : 0
 Total NaN in row 12149 : 9
 Total NaN in row 12150 : 9
 Total NaN in row 12151 : 2
 Total NaN in row 12152 : 0
 Total NaN in row 12153 : 1
 Total NaN in row 12154 : 0
 Total NaN in row 12155 : 0
 Total NaN in row 12156 : 0
 Total NaN in row 12157 : 0
 Total NaN in row 12158 : 0
 Total NaN in row 12159 : 1
 Total NaN in row 12160 : 0
 Total NaN in row 12161 : 9
 Total NaN in row 12162 : 0
 Total NaN in row 12163 : 9
 Total NaN in row 12164 : 1
 Total NaN in row 12165 : 2
 Total NaN in row 12166 : 0
 Total NaN in row 12167 : 3
 Total NaN in row 12168 : 2
 Total NaN in row 12169 : 1
 Total NaN in row 12170 : 9
 Total NaN in row 12171 : 0
 Total NaN in row 12172 : 0
 Total NaN in row 12173 : 9
 Total NaN in row 12174 : 1
 Total NaN in row 12175 : 0
 Total NaN in row 12176 : 3
 Total NaN in row 12177 : 0
 Total NaN in row 12178 : 0
 Total NaN in row 12179 : 3
 Total NaN in row 12180 : 2
 Total NaN in row 12181 : 2
 Total NaN in row 12182 : 2
 Total NaN in row 12183 : 3
 Total NaN in row 12184 : 1
 Total NaN in row 12185 : 2
 Total NaN in row 12186 : 1
 Total NaN in row 12187 : 2
 Total NaN in row 12188 : 0
 Total NaN in row 12189 : 3
 Total NaN in row 12190 : 2
 Total NaN in row 12191 : 1
 Total NaN in row 12192 : 2
 Total NaN in row 12193 : 0
 Total NaN in row 12194 : 9
 Total NaN in row 12195 : 2
 Total NaN in row 12196 : 9
 Total NaN in row 12197 : 1
 Total NaN in row 12198 : 2
 Total NaN in row 12199 : 2
 Total NaN in row 12200 : 9
 Total NaN in row 12201 : 9
 Total NaN in row 12202 : 9
 Total NaN in row 12203 : 9
 Total NaN in row 12204 : 9
 Total NaN in row 12205 : 0
 Total NaN in row 12206 : 9
 Total NaN in row 12207 : 2
 Total NaN in row 12208 : 9
 Total NaN in row 12209 : 9
 Total NaN in row 12210 : 10
 Total NaN in row 12211 : 10
 Total NaN in row 12212 : 0
 Total NaN in row 12213 : 2
 Total NaN in row 12214 : 2
 Total NaN in row 12215 : 2
 Total NaN in row 12216 : 3
 Total NaN in row 12217 : 0
 Total NaN in row 12218 : 9
 Total NaN in row 12219 : 3
 Total NaN in row 12220 : 10
 Total NaN in row 12221 : 1
 Total NaN in row 12222 : 10
 Total NaN in row 12223 : 1
 Total NaN in row 12224 : 2
 Total NaN in row 12225 : 2
 Total NaN in row 12226 : 0
 Total NaN in row 12227 : 2
 Total NaN in row 12228 : 1
 Total NaN in row 12229 : 1
 Total NaN in row 12230 : 2
 Total NaN in row 12231 : 0
 Total NaN in row 12232 : 0
 Total NaN in row 12233 : 1
 Total NaN in row 12234 : 0
 Total NaN in row 12235 : 0
 Total NaN in row 12236 : 1
 Total NaN in row 12237 : 2
 Total NaN in row 12238 : 0
 Total NaN in row 12239 : 0
 Total NaN in row 12240 : 9
 Total NaN in row 12241 : 9
 Total NaN in row 12242 : 2
 Total NaN in row 12243 : 2
 Total NaN in row 12244 : 2
 Total NaN in row 12245 : 2
 Total NaN in row 12246 : 10
 Total NaN in row 12247 : 2
 Total NaN in row 12248 : 2
 Total NaN in row 12249 : 9
 Total NaN in row 12250 : 0
 Total NaN in row 12251 : 2
 Total NaN in row 12252 : 9
 Total NaN in row 12253 : 0
 Total NaN in row 12254 : 1
 Total NaN in row 12255 : 10
 Total NaN in row 12256 : 3
 Total NaN in row 12257 : 3
 Total NaN in row 12258 : 10
 Total NaN in row 12259 : 1
 Total NaN in row 12260 : 0
 Total NaN in row 12261 : 9
 Total NaN in row 12262 : 9
 Total NaN in row 12263 : 0
 Total NaN in row 12264 : 9
 Total NaN in row 12265 : 9
 Total NaN in row 12266 : 2
 Total NaN in row 12267 : 2
 Total NaN in row 12268 : 9
 Total NaN in row 12269 : 0
 Total NaN in row 12270 : 2
 Total NaN in row 12271 : 3
 Total NaN in row 12272 : 0
 Total NaN in row 12273 : 9
 Total NaN in row 12274 : 2
 Total NaN in row 12275 : 10
 Total NaN in row 12276 : 1
 Total NaN in row 12277 : 0
 Total NaN in row 12278 : 1
 Total NaN in row 12279 : 9
 Total NaN in row 12280 : 2
 Total NaN in row 12281 : 10
 Total NaN in row 12282 : 9
 Total NaN in row 12283 : 2
 Total NaN in row 12284 : 0
 Total NaN in row 12285 : 0
 Total NaN in row 12286 : 9
 Total NaN in row 12287 : 2
 Total NaN in row 12288 : 10
 Total NaN in row 12289 : 3
 Total NaN in row 12290 : 1
 Total NaN in row 12291 : 10
 Total NaN in row 12292 : 9
 Total NaN in row 12293 : 1
 Total NaN in row 12294 : 10
 Total NaN in row 12295 : 2
 Total NaN in row 12296 : 2
 Total NaN in row 12297 : 1
 Total NaN in row 12298 : 9
 Total NaN in row 12299 : 0
 Total NaN in row 12300 : 2
 Total NaN in row 12301 : 0
 Total NaN in row 12302 : 1
 Total NaN in row 12303 : 2
 Total NaN in row 12304 : 2
 Total NaN in row 12305 : 1
 Total NaN in row 12306 : 2
 Total NaN in row 12307 : 1
 Total NaN in row 12308 : 2
 Total NaN in row 12309 : 1
 Total NaN in row 12310 : 1
 Total NaN in row 12311 : 9
 Total NaN in row 12312 : 1
 Total NaN in row 12313 : 1
 Total NaN in row 12314 : 1
 Total NaN in row 12315 : 9
 Total NaN in row 12316 : 1
 Total NaN in row 12317 : 0
 Total NaN in row 12318 : 2
 Total NaN in row 12319 : 2
 Total NaN in row 12320 : 1
 Total NaN in row 12321 : 2
 Total NaN in row 12322 : 9
 Total NaN in row 12323 : 2
 Total NaN in row 12324 : 2
 Total NaN in row 12325 : 1
 Total NaN in row 12326 : 0
 Total NaN in row 12327 : 7
 Total NaN in row 12328 : 3
 Total NaN in row 12329 : 0
 Total NaN in row 12330 : 1
 Total NaN in row 12331 : 0
 Total NaN in row 12332 : 3
 Total NaN in row 12333 : 1
 Total NaN in row 12334 : 1
 Total NaN in row 12335 : 2
 Total NaN in row 12336 : 2
 Total NaN in row 12337 : 9
 Total NaN in row 12338 : 3
 Total NaN in row 12339 : 2
 Total NaN in row 12340 : 2
 Total NaN in row 12341 : 0
 Total NaN in row 12342 : 9
 Total NaN in row 12343 : 10
 Total NaN in row 12344 : 1
 Total NaN in row 12345 : 9
 Total NaN in row 12346 : 9
 Total NaN in row 12347 : 2
 Total NaN in row 12348 : 2
 Total NaN in row 12349 : 9
 Total NaN in row 12350 : 9
 Total NaN in row 12351 : 0
 Total NaN in row 12352 : 2
 Total NaN in row 12353 : 9
 Total NaN in row 12354 : 0
 Total NaN in row 12355 : 2
 Total NaN in row 12356 : 10
 Total NaN in row 12357 : 8
 Total NaN in row 12358 : 2
 Total NaN in row 12359 : 2
 Total NaN in row 12360 : 9
 Total NaN in row 12361 : 9
 Total NaN in row 12362 : 0
 Total NaN in row 12363 : 1
 Total NaN in row 12364 : 0
 Total NaN in row 12365 : 9
 Total NaN in row 12366 : 2
 Total NaN in row 12367 : 1
 Total NaN in row 12368 : 0
 Total NaN in row 12369 : 1
 Total NaN in row 12370 : 3
 Total NaN in row 12371 : 2
 Total NaN in row 12372 : 2
 Total NaN in row 12373 : 0
 Total NaN in row 12374 : 2
 Total NaN in row 12375 : 2
 Total NaN in row 12376 : 1
 Total NaN in row 12377 : 0
 Total NaN in row 12378 : 3
 Total NaN in row 12379 : 10
 Total NaN in row 12380 : 9
 Total NaN in row 12381 : 0
 Total NaN in row 12382 : 9
 Total NaN in row 12383 : 2
 Total NaN in row 12384 : 9
 Total NaN in row 12385 : 0
 Total NaN in row 12386 : 2
 Total NaN in row 12387 : 0
 Total NaN in row 12388 : 0
 Total NaN in row 12389 : 2
 Total NaN in row 12390 : 10
 Total NaN in row 12391 : 1
 Total NaN in row 12392 : 1
 Total NaN in row 12393 : 0
 Total NaN in row 12394 : 0
 Total NaN in row 12395 : 1
 Total NaN in row 12396 : 2
 Total NaN in row 12397 : 0
 Total NaN in row 12398 : 0
 Total NaN in row 12399 : 0
 Total NaN in row 12400 : 0
 Total NaN in row 12401 : 2
 Total NaN in row 12402 : 1
 Total NaN in row 12403 : 2
 Total NaN in row 12404 : 0
 Total NaN in row 12405 : 9
 Total NaN in row 12406 : 9
 Total NaN in row 12407 : 0
 Total NaN in row 12408 : 2
 Total NaN in row 12409 : 1
 Total NaN in row 12410 : 2
 Total NaN in row 12411 : 1
 Total NaN in row 12412 : 2
 Total NaN in row 12413 : 2
 Total NaN in row 12414 : 2
 Total NaN in row 12415 : 1
 Total NaN in row 12416 : 0
 Total NaN in row 12417 : 1
 Total NaN in row 12418 : 0
 Total NaN in row 12419 : 9
 Total NaN in row 12420 : 9
 Total NaN in row 12421 : 2
 Total NaN in row 12422 : 0
 Total NaN in row 12423 : 1
 Total NaN in row 12424 : 2
 Total NaN in row 12425 : 3
 Total NaN in row 12426 : 9
 Total NaN in row 12427 : 10
 Total NaN in row 12428 : 9
 Total NaN in row 12429 : 2
 Total NaN in row 12430 : 0
 Total NaN in row 12431 : 2
 Total NaN in row 12432 : 2
 Total NaN in row 12433 : 2
 Total NaN in row 12434 : 0
 Total NaN in row 12435 : 7
 Total NaN in row 12436 : 2
 Total NaN in row 12437 : 2
 Total NaN in row 12438 : 1
 Total NaN in row 12439 : 9
 Total NaN in row 12440 : 3
 Total NaN in row 12441 : 9
 Total NaN in row 12442 : 21
 Total NaN in row 12443 : 10
 Total NaN in row 12444 : 1
 Total NaN in row 12445 : 1
 Total NaN in row 12446 : 2
 Total NaN in row 12447 : 9
 Total NaN in row 12448 : 3
 Total NaN in row 12449 : 2
 Total NaN in row 12450 : 5
 Total NaN in row 12451 : 1
 Total NaN in row 12452 : 2
 Total NaN in row 12453 : 3
 Total NaN in row 12454 : 9
 Total NaN in row 12455 : 0
 Total NaN in row 12456 : 0
 Total NaN in row 12457 : 0

 Total NaN in row 12458 : 9
 Total NaN in row 12459 : 0
 Total NaN in row 12460 : 0
 Total NaN in row 12461 : 0
 Total NaN in row 12462 : 2
 Total NaN in row 12463 : 0
 Total NaN in row 12464 : 0
 Total NaN in row 12465 : 2
 Total NaN in row 12466 : 0
 Total NaN in row 12467 : 2
 Total NaN in row 12468 : 0
 Total NaN in row 12469 : 0
 Total NaN in row 12470 : 9
 Total NaN in row 12471 : 1
 Total NaN in row 12472 : 2
 Total NaN in row 12473 : 1
 Total NaN in row 12474 : 2
 Total NaN in row 12475 : 2
 Total NaN in row 12476 : 0
 Total NaN in row 12477 : 0
 Total NaN in row 12478 : 0
 Total NaN in row 12479 : 0
 Total NaN in row 12480 : 3
 Total NaN in row 12481 : 0
 Total NaN in row 12482 : 2
 Total NaN in row 12483 : 2
 Total NaN in row 12484 : 1
 Total NaN in row 12485 : 2
 Total NaN in row 12486 : 0
 Total NaN in row 12487 : 9
 Total NaN in row 12488 : 2
 Total NaN in row 12489 : 0
 Total NaN in row 12490 : 2
 Total NaN in row 12491 : 9
 Total NaN in row 12492 : 2
 Total NaN in row 12493 : 1
 Total NaN in row 12494 : 9
 Total NaN in row 12495 : 0
 Total NaN in row 12496 : 10
 Total NaN in row 12497 : 1
 Total NaN in row 12498 : 2
 Total NaN in row 12499 : 0
 Total NaN in row 12500 : 2
 Total NaN in row 12501 : 0
 Total NaN in row 12502 : 1
 Total NaN in row 12503 : 2
 Total NaN in row 12504 : 2
 Total NaN in row 12505 : 2
 Total NaN in row 12506 : 0
 Total NaN in row 12507 : 2
 Total NaN in row 12508 : 2
 Total NaN in row 12509 : 1
 Total NaN in row 12510 : 10
 Total NaN in row 12511 : 0
 Total NaN in row 12512 : 7
 Total NaN in row 12513 : 0
 Total NaN in row 12514 : 9
 Total NaN in row 12515 : 0
 Total NaN in row 12516 : 9
 Total NaN in row 12517 : 1
 Total NaN in row 12518 : 0
 Total NaN in row 12519 : 0
 Total NaN in row 12520 : 9
 Total NaN in row 12521 : 1
 Total NaN in row 12522 : 10
 Total NaN in row 12523 : 2
 Total NaN in row 12524 : 2
 Total NaN in row 12525 : 2
 Total NaN in row 12526 : 9
 Total NaN in row 12527 : 0
 Total NaN in row 12528 : 2
 Total NaN in row 12529 : 0
 Total NaN in row 12530 : 2
 Total NaN in row 12531 : 0
 Total NaN in row 12532 : 0
 Total NaN in row 12533 : 2
 Total NaN in row 12534 : 3
 Total NaN in row 12535 : 10
 Total NaN in row 12536 : 2
 Total NaN in row 12537 : 0
 Total NaN in row 12538 : 9
 Total NaN in row 12539 : 0
 Total NaN in row 12540 : 0
 Total NaN in row 12541 : 0
 Total NaN in row 12542 : 2
 Total NaN in row 12543 : 0
 Total NaN in row 12544 : 3
 Total NaN in row 12545 : 0
 Total NaN in row 12546 : 0
 Total NaN in row 12547 : 10
 Total NaN in row 12548 : 10
 Total NaN in row 12549 : 2
 Total NaN in row 12550 : 2
 Total NaN in row 12551 : 2
 Total NaN in row 12552 : 2
 Total NaN in row 12553 : 2
 Total NaN in row 12554 : 10
 Total NaN in row 12555 : 9
 Total NaN in row 12556 : 0
 Total NaN in row 12557 : 3
 Total NaN in row 12558 : 1
 Total NaN in row 12559 : 1
 Total NaN in row 12560 : 21
 Total NaN in row 12561 : 3
 Total NaN in row 12562 : 0
 Total NaN in row 12563 : 2
 Total NaN in row 12564 : 3
 Total NaN in row 12565 : 1
 Total NaN in row 12566 : 2
 Total NaN in row 12567 : 0
 Total NaN in row 12568 : 0
 Total NaN in row 12569 : 1
 Total NaN in row 12570 : 3
 Total NaN in row 12571 : 10
 Total NaN in row 12572 : 3
 Total NaN in row 12573 : 1
 Total NaN in row 12574 : 5
 Total NaN in row 12575 : 3
 Total NaN in row 12576 : 10
 Total NaN in row 12577 : 1
 Total NaN in row 12578 : 0
 Total NaN in row 12579 : 2
 Total NaN in row 12580 : 0
 Total NaN in row 12581 : 1
 Total NaN in row 12582 : 9
 Total NaN in row 12583 : 0
 Total NaN in row 12584 : 2
 Total NaN in row 12585 : 10
 Total NaN in row 12586 : 0
 Total NaN in row 12587 : 0
 Total NaN in row 12588 : 2
 Total NaN in row 12589 : 2
 Total NaN in row 12590 : 9
 Total NaN in row 12591 : 2
 Total NaN in row 12592 : 0
 Total NaN in row 12593 : 9
 Total NaN in row 12594 : 0
 Total NaN in row 12595 : 0
 Total NaN in row 12596 : 2
 Total NaN in row 12597 : 1
 Total NaN in row 12598 : 2
 Total NaN in row 12599 : 1
 Total NaN in row 12600 : 2
 Total NaN in row 12601 : 10
 Total NaN in row 12602 : 0
 Total NaN in row 12603 : 1
 Total NaN in row 12604 : 2
 Total NaN in row 12605 : 0
 Total NaN in row 12606 : 1
 Total NaN in row 12607 : 2
 Total NaN in row 12608 : 9
 Total NaN in row 12609 : 2
 Total NaN in row 12610 : 0
 Total NaN in row 12611 : 3
 Total NaN in row 12612 : 10
 Total NaN in row 12613 : 3
 Total NaN in row 12614 : 4
 Total NaN in row 12615 : 1
 Total NaN in row 12616 : 2
 Total NaN in row 12617 : 3
 Total NaN in row 12618 : 1
 Total NaN in row 12619 : 2
 Total NaN in row 12620 : 0
 Total NaN in row 12621 : 2
 Total NaN in row 12622 : 1
 Total NaN in row 12623 : 3
 Total NaN in row 12624 : 0
 Total NaN in row 12625 : 3
 Total NaN in row 12626 : 1
 Total NaN in row 12627 : 2
 Total NaN in row 12628 : 2
 Total NaN in row 12629 : 1
 Total NaN in row 12630 : 7
 Total NaN in row 12631 : 2
 Total NaN in row 12632 : 2
 Total NaN in row 12633 : 9
 Total NaN in row 12634 : 1
 Total NaN in row 12635 : 0
 Total NaN in row 12636 : 2
 Total NaN in row 12637 : 2
 Total NaN in row 12638 : 9
 Total NaN in row 12639 : 9
 Total NaN in row 12640 : 0
 Total NaN in row 12641 : 9
 Total NaN in row 12642 : 1
 Total NaN in row 12643 : 9
 Total NaN in row 12644 : 10
 Total NaN in row 12645 : 1
 Total NaN in row 12646 : 0
 Total NaN in row 12647 : 0
 Total NaN in row 12648 : 2
 Total NaN in row 12649 : 2
 Total NaN in row 12650 : 9
 Total NaN in row 12651 : 9
 Total NaN in row 12652 : 0
 Total NaN in row 12653 : 0
 Total NaN in row 12654 : 9
 Total NaN in row 12655 : 0
 Total NaN in row 12656 : 2
 Total NaN in row 12657 : 3
 Total NaN in row 12658 : 9
 Total NaN in row 12659 : 9
 Total NaN in row 12660 : 0
 Total NaN in row 12661 : 2
 Total NaN in row 12662 : 2
 Total NaN in row 12663 : 1
 Total NaN in row 12664 : 2
 Total NaN in row 12665 : 2
 Total NaN in row 12666 : 1
 Total NaN in row 12667 : 1
 Total NaN in row 12668 : 0
 Total NaN in row 12669 : 9
 Total NaN in row 12670 : 9
 Total NaN in row 12671 : 2
 Total NaN in row 12672 : 2
 Total NaN in row 12673 : 10
 Total NaN in row 12674 : 0
 Total NaN in row 12675 : 0
 Total NaN in row 12676 : 2
 Total NaN in row 12677 : 0
 Total NaN in row 12678 : 9
 Total NaN in row 12679 : 3
 Total NaN in row 12680 : 10
 Total NaN in row 12681 : 0
 Total NaN in row 12682 : 9
 Total NaN in row 12683 : 10
 Total NaN in row 12684 : 0
 Total NaN in row 12685 : 0
 Total NaN in row 12686 : 0
 Total NaN in row 12687 : 2
 Total NaN in row 12688 : 0
 Total NaN in row 12689 : 9
 Total NaN in row 12690 : 9
 Total NaN in row 12691 : 0
 Total NaN in row 12692 : 0
 Total NaN in row 12693 : 0
 Total NaN in row 12694 : 2
 Total NaN in row 12695 : 2
 Total NaN in row 12696 : 0
 Total NaN in row 12697 : 2
 Total NaN in row 12698 : 2
 Total NaN in row 12699 : 2
 Total NaN in row 12700 : 3
 Total NaN in row 12701 : 2
 Total NaN in row 12702 : 10
 Total NaN in row 12703 : 0
 Total NaN in row 12704 : 0
 Total NaN in row 12705 : 10
 Total NaN in row 12706 : 10
 Total NaN in row 12707 : 0
 Total NaN in row 12708 : 2
 Total NaN in row 12709 : 0
 Total NaN in row 12710 : 1
 Total NaN in row 12711 : 2
 Total NaN in row 12712 : 0
 Total NaN in row 12713 : 2
 Total NaN in row 12714 : 2
 Total NaN in row 12715 : 0
 Total NaN in row 12716 : 2
 Total NaN in row 12717 : 3
 Total NaN in row 12718 : 2
 Total NaN in row 12719 : 2
 Total NaN in row 12720 : 1
 Total NaN in row 12721 : 3
 Total NaN in row 12722 : 9
 Total NaN in row 12723 : 0
 Total NaN in row 12724 : 2
 Total NaN in row 12725 : 0
 Total NaN in row 12726 : 1
 Total NaN in row 12727 : 0
 Total NaN in row 12728 : 0
 Total NaN in row 12729 : 0
 Total NaN in row 12730 : 0
 Total NaN in row 12731 : 1
 Total NaN in row 12732 : 0
 Total NaN in row 12733 : 0
 Total NaN in row 12734 : 9
 Total NaN in row 12735 : 0
 Total NaN in row 12736 : 0
 Total NaN in row 12737 : 9
 Total NaN in row 12738 : 1
 Total NaN in row 12739 : 2
 Total NaN in row 12740 : 10
 Total NaN in row 12741 : 2
 Total NaN in row 12742 : 2
 Total NaN in row 12743 : 2
 Total NaN in row 12744 : 9
 Total NaN in row 12745 : 1
 Total NaN in row 12746 : 9
 Total NaN in row 12747 : 3
 Total NaN in row 12748 : 9
 Total NaN in row 12749 : 9
 Total NaN in row 12750 : 0
 Total NaN in row 12751 : 1
 Total NaN in row 12752 : 3
 Total NaN in row 12753 : 1
 Total NaN in row 12754 : 0
 Total NaN in row 12755 : 1
 Total NaN in row 12756 : 2
 Total NaN in row 12757 : 2
 Total NaN in row 12758 : 0
 Total NaN in row 12759 : 3
 Total NaN in row 12760 : 9
 Total NaN in row 12761 : 0
 Total NaN in row 12762 : 9
 Total NaN in row 12763 : 3
 Total NaN in row 12764 : 0
 Total NaN in row 12765 : 2
 Total NaN in row 12766 : 10
 Total NaN in row 12767 : 1
 Total NaN in row 12768 : 10
 Total NaN in row 12769 : 3
 Total NaN in row 12770 : 9
 Total NaN in row 12771 : 1
 Total NaN in row 12772 : 9
 Total NaN in row 12773 : 1
 Total NaN in row 12774 : 0
 Total NaN in row 12775 : 0
 Total NaN in row 12776 : 2
 Total NaN in row 12777 : 10
 Total NaN in row 12778 : 10
 Total NaN in row 12779 : 9
 Total NaN in row 12780 : 9
 Total NaN in row 12781 : 9
 Total NaN in row 12782 : 9
 Total NaN in row 12783 : 0
 Total NaN in row 12784 : 9
 Total NaN in row 12785 : 10
 Total NaN in row 12786 : 1
 Total NaN in row 12787 : 1
 Total NaN in row 12788 : 1
 Total NaN in row 12789 : 2
 Total NaN in row 12790 : 0
 Total NaN in row 12791 : 2
 Total NaN in row 12792 : 2
 Total NaN in row 12793 : 2
 Total NaN in row 12794 : 9
 Total NaN in row 12795 : 2
 Total NaN in row 12796 : 2
 Total NaN in row 12797 : 2
 Total NaN in row 12798 : 9
 Total NaN in row 12799 : 3
 Total NaN in row 12800 : 2
 Total NaN in row 12801 : 2
 Total NaN in row 12802 : 9
 Total NaN in row 12803 : 2
 Total NaN in row 12804 : 1
 Total NaN in row 12805 : 2
 Total NaN in row 12806 : 1
 Total NaN in row 12807 : 2
 Total NaN in row 12808 : 2
 Total NaN in row 12809 : 9
 Total NaN in row 12810 : 0
 Total NaN in row 12811 : 0
 Total NaN in row 12812 : 2
 Total NaN in row 12813 : 1
 Total NaN in row 12814 : 0
 Total NaN in row 12815 : 2
 Total NaN in row 12816 : 2

 Total NaN in row 12817 : 2
 Total NaN in row 12818 : 1
 Total NaN in row 12819 : 2
 Total NaN in row 12820 : 9
 Total NaN in row 12821 : 2
 Total NaN in row 12822 : 0
 Total NaN in row 12823 : 10
 Total NaN in row 12824 : 3
 Total NaN in row 12825 : 2
 Total NaN in row 12826 : 0
 Total NaN in row 12827 : 0
 Total NaN in row 12828 : 1
 Total NaN in row 12829 : 3
 Total NaN in row 12830 : 0
 Total NaN in row 12831 : 0
 Total NaN in row 12832 : 1
 Total NaN in row 12833 : 1
 Total NaN in row 12834 : 0
 Total NaN in row 12835 : 9
 Total NaN in row 12836 : 2
 Total NaN in row 12837 : 0
 Total NaN in row 12838 : 0
 Total NaN in row 12839 : 9
 Total NaN in row 12840 : 9
 Total NaN in row 12841 : 2
 Total NaN in row 12842 : 0
 Total NaN in row 12843 : 2
 Total NaN in row 12844 : 2
 Total NaN in row 12845 : 2
 Total NaN in row 12846 : 0
 Total NaN in row 12847 : 7
 Total NaN in row 12848 : 2
 Total NaN in row 12849 : 2
 Total NaN in row 12850 : 9
 Total NaN in row 12851 : 2
 Total NaN in row 12852 : 1
 Total NaN in row 12853 : 2
 Total NaN in row 12854 : 0
 Total NaN in row 12855 : 0
 Total NaN in row 12856 : 3
 Total NaN in row 12857 : 2
 Total NaN in row 12858 : 0
 Total NaN in row 12859 : 0
 Total NaN in row 12860 : 1
 Total NaN in row 12861 : 2
 Total NaN in row 12862 : 1
 Total NaN in row 12863 : 2
 Total NaN in row 12864 : 2
 Total NaN in row 12865 : 2
 Total NaN in row 12866 : 2
 Total NaN in row 12867 : 10
 Total NaN in row 12868 : 0
 Total NaN in row 12869 : 2
 Total NaN in row 12870 : 2
 Total NaN in row 12871 : 0
 Total NaN in row 12872 : 9
 Total NaN in row 12873 : 9
 Total NaN in row 12874 : 0
 Total NaN in row 12875 : 1
 Total NaN in row 12876 : 0
 Total NaN in row 12877 : 0
 Total NaN in row 12878 : 0
 Total NaN in row 12879 : 0
 Total NaN in row 12880 : 0
 Total NaN in row 12881 : 0
 Total NaN in row 12882 : 2
 Total NaN in row 12883 : 0
 Total NaN in row 12884 : 1
 Total NaN in row 12885 : 0
 Total NaN in row 12886 : 0
 Total NaN in row 12887 : 1
 Total NaN in row 12888 : 2
 Total NaN in row 12889 : 4
 Total NaN in row 12890 : 9
 Total NaN in row 12891 : 9
 Total NaN in row 12892 : 0
 Total NaN in row 12893 : 1
 Total NaN in row 12894 : 0
 Total NaN in row 12895 : 0
 Total NaN in row 12896 : 2
 Total NaN in row 12897 : 1
 Total NaN in row 12898 : 0
 Total NaN in row 12899 : 10
 Total NaN in row 12900 : 2
 Total NaN in row 12901 : 2
 Total NaN in row 12902 : 2
 Total NaN in row 12903 : 4
 Total NaN in row 12904 : 3
 Total NaN in row 12905 : 0
 Total NaN in row 12906 : 0
 Total NaN in row 12907 : 9
 Total NaN in row 12908 : 9
 Total NaN in row 12909 : 0
 Total NaN in row 12910 : 9
 Total NaN in row 12911 : 9
 Total NaN in row 12912 : 2
 Total NaN in row 12913 : 9
 Total NaN in row 12914 : 10
 Total NaN in row 12915 : 9
 Total NaN in row 12916 : 0
 Total NaN in row 12917 : 1
 Total NaN in row 12918 : 0
 Total NaN in row 12919 : 0
 Total NaN in row 12920 : 3
 Total NaN in row 12921 : 1
 Total NaN in row 12922 : 3
 Total NaN in row 12923 : 10
 Total NaN in row 12924 : 1
 Total NaN in row 12925 : 1
 Total NaN in row 12926 : 1
 Total NaN in row 12927 : 10
 Total NaN in row 12928 : 2
 Total NaN in row 12929 : 0
 Total NaN in row 12930 : 2
 Total NaN in row 12931 : 2
 Total NaN in row 12932 : 3
 Total NaN in row 12933 : 0
 Total NaN in row 12934 : 10
 Total NaN in row 12935 : 1
 Total NaN in row 12936 : 0
 Total NaN in row 12937 : 1
 Total NaN in row 12938 : 1
 Total NaN in row 12939 : 1
 Total NaN in row 12940 : 0
 Total NaN in row 12941 : 2
 Total NaN in row 12942 : 2
 Total NaN in row 12943 : 2
 Total NaN in row 12944 : 2
 Total NaN in row 12945 : 0
 Total NaN in row 12946 : 0
 Total NaN in row 12947 : 0
 Total NaN in row 12948 : 9
 Total NaN in row 12949 : 9
 Total NaN in row 12950 : 9
 Total NaN in row 12951 : 9
 Total NaN in row 12952 : 0
 Total NaN in row 12953 : 0
 Total NaN in row 12954 : 2
 Total NaN in row 12955 : 2
 Total NaN in row 12956 : 0
 Total NaN in row 12957 : 9
 Total NaN in row 12958 : 2
 Total NaN in row 12959 : 9
 Total NaN in row 12960 : 9
 Total NaN in row 12961 : 1
 Total NaN in row 12962 : 2
 Total NaN in row 12963 : 9
 Total NaN in row 12964 : 9
 Total NaN in row 12965 : 9
 Total NaN in row 12966 : 9
 Total NaN in row 12967 : 2
 Total NaN in row 12968 : 0
 Total NaN in row 12969 : 0
 Total NaN in row 12970 : 1
 Total NaN in row 12971 : 0
 Total NaN in row 12972 : 1
 Total NaN in row 12973 : 2
 Total NaN in row 12974 : 0
 Total NaN in row 12975 : 10
 Total NaN in row 12976 : 0
 Total NaN in row 12977 : 0
 Total NaN in row 12978 : 9
 Total NaN in row 12979 : 0
 Total NaN in row 12980 : 1
 Total NaN in row 12981 : 10
 Total NaN in row 12982 : 2
 Total NaN in row 12983 : 0
 Total NaN in row 12984 : 1
 Total NaN in row 12985 : 2
 Total NaN in row 12986 : 2
 Total NaN in row 12987 : 1
 Total NaN in row 12988 : 1
 Total NaN in row 12989 : 3
 Total NaN in row 12990 : 2
 Total NaN in row 12991 : 1
 Total NaN in row 12992 : 2
 Total NaN in row 12993 : 2
 Total NaN in row 12994 : 3
 Total NaN in row 12995 : 2
 Total NaN in row 12996 : 0
 Total NaN in row 12997 : 3
 Total NaN in row 12998 : 21
 Total NaN in row 12999 : 0
 Total NaN in row 13000 : 1
 Total NaN in row 13001 : 1
 Total NaN in row 13002 : 1
 Total NaN in row 13003 : 2
 Total NaN in row 13004 : 1
 Total NaN in row 13005 : 1
 Total NaN in row 13006 : 0
 Total NaN in row 13007 : 2
 Total NaN in row 13008 : 2
 Total NaN in row 13009 : 10
 Total NaN in row 13010 : 9
 Total NaN in row 13011 : 9
 Total NaN in row 13012 : 10
 Total NaN in row 13013 : 9
 Total NaN in row 13014 : 9
 Total NaN in row 13015 : 10
 Total NaN in row 13016 : 10
 Total NaN in row 13017 : 10
 Total NaN in row 13018 : 9
 Total NaN in row 13019 : 9
 Total NaN in row 13020 : 7
 Total NaN in row 13021 : 1
 Total NaN in row 13022 : 0
 Total NaN in row 13023 : 0
 Total NaN in row 13024 : 2
 Total NaN in row 13025 : 0
 Total NaN in row 13026 : 10
 Total NaN in row 13027 : 0
 Total NaN in row 13028 : 0
 Total NaN in row 13029 : 1
 Total NaN in row 13030 : 3
 Total NaN in row 13031 : 0
 Total NaN in row 13032 : 2
 Total NaN in row 13033 : 3
 Total NaN in row 13034 : 3
 Total NaN in row 13035 : 10
 Total NaN in row 13036 : 2
 Total NaN in row 13037 : 1
 Total NaN in row 13038 : 0
 Total NaN in row 13039 : 0
 Total NaN in row 13040 : 2
 Total NaN in row 13041 : 7
 Total NaN in row 13042 : 0
 Total NaN in row 13043 : 2
 Total NaN in row 13044 : 1
 Total NaN in row 13045 : 2
 Total NaN in row 13046 : 2
 Total NaN in row 13047 : 3
 Total NaN in row 13048 : 0
 Total NaN in row 13049 : 3
 Total NaN in row 13050 : 1
 Total NaN in row 13051 : 2
 Total NaN in row 13052 : 3
 Total NaN in row 13053 : 2
 Total NaN in row 13054 : 10
 Total NaN in row 13055 : 2
 Total NaN in row 13056 : 0
 Total NaN in row 13057 : 2
 Total NaN in row 13058 : 1
 Total NaN in row 13059 : 2
 Total NaN in row 13060 : 2
 Total NaN in row 13061 : 1
 Total NaN in row 13062 : 0
 Total NaN in row 13063 : 1
 Total NaN in row 13064 : 2
 Total NaN in row 13065 : 2
 Total NaN in row 13066 : 0
 Total NaN in row 13067 : 21
 Total NaN in row 13068 : 1
 Total NaN in row 13069 : 1
 Total NaN in row 13070 : 2
 Total NaN in row 13071 : 1
 Total NaN in row 13072 : 9
 Total NaN in row 13073 : 1
 Total NaN in row 13074 : 0
 Total NaN in row 13075 : 2
 Total NaN in row 13076 : 3
 Total NaN in row 13077 : 1
 Total NaN in row 13078 : 1
 Total NaN in row 13079 : 1
 Total NaN in row 13080 : 2
 Total NaN in row 13081 : 2
 Total NaN in row 13082 : 0
 Total NaN in row 13083 : 1
 Total NaN in row 13084 : 3
 Total NaN in row 13085 : 9
 Total NaN in row 13086 : 2
 Total NaN in row 13087 : 0
 Total NaN in row 13088 : 0
 Total NaN in row 13089 : 1
 Total NaN in row 13090 : 0
 Total NaN in row 13091 : 2
 Total NaN in row 13092 : 9
 Total NaN in row 13093 : 2
 Total NaN in row 13094 : 1
 Total NaN in row 13095 : 2
 Total NaN in row 13096 : 2
 Total NaN in row 13097 : 9
 Total NaN in row 13098 : 2
 Total NaN in row 13099 : 0
 Total NaN in row 13100 : 1
 Total NaN in row 13101 : 10
 Total NaN in row 13102 : 0
 Total NaN in row 13103 : 2
 Total NaN in row 13104 : 2
 Total NaN in row 13105 : 0
 Total NaN in row 13106 : 0
 Total NaN in row 13107 : 1
 Total NaN in row 13108 : 0
 Total NaN in row 13109 : 0
 Total NaN in row 13110 : 2
 Total NaN in row 13111 : 2
 Total NaN in row 13112 : 2
 Total NaN in row 13113 : 2
 Total NaN in row 13114 : 3
 Total NaN in row 13115 : 9
 Total NaN in row 13116 : 1
 Total NaN in row 13117 : 0
 Total NaN in row 13118 : 2
 Total NaN in row 13119 : 1
 Total NaN in row 13120 : 2
 Total NaN in row 13121 : 1
 Total NaN in row 13122 : 9
 Total NaN in row 13123 : 9
 Total NaN in row 13124 : 0
 Total NaN in row 13125 : 9
 Total NaN in row 13126 : 2
 Total NaN in row 13127 : 0
 Total NaN in row 13128 : 2
 Total NaN in row 13129 : 3
 Total NaN in row 13130 : 2
 Total NaN in row 13131 : 2
 Total NaN in row 13132 : 9
 Total NaN in row 13133 : 0
 Total NaN in row 13134 : 2

 Total NaN in row 13135 : 10
 Total NaN in row 13136 : 3
 Total NaN in row 13137 : 1
 Total NaN in row 13138 : 9
 Total NaN in row 13139 : 3
 Total NaN in row 13140 : 10
 Total NaN in row 13141 : 1
 Total NaN in row 13142 : 10
 Total NaN in row 13143 : 2
 Total NaN in row 13144 : 0
 Total NaN in row 13145 : 0
 Total NaN in row 13146 : 2
 Total NaN in row 13147 : 9
 Total NaN in row 13148 : 9
 Total NaN in row 13149 : 0
 Total NaN in row 13150 : 2
 Total NaN in row 13151 : 9
 Total NaN in row 13152 : 9
 Total NaN in row 13153 : 0
 Total NaN in row 13154 : 0
 Total NaN in row 13155 : 0
 Total NaN in row 13156 : 1
 Total NaN in row 13157 : 0
 Total NaN in row 13158 : 9
 Total NaN in row 13159 : 9
 Total NaN in row 13160 : 9
 Total NaN in row 13161 : 10
 Total NaN in row 13162 : 0
 Total NaN in row 13163 : 2
 Total NaN in row 13164 : 9
 Total NaN in row 13165 : 2
 Total NaN in row 13166 : 2
 Total NaN in row 13167 : 9
 Total NaN in row 13168 : 9
 Total NaN in row 13169 : 9
 Total NaN in row 13170 : 3
 Total NaN in row 13171 : 9
 Total NaN in row 13172 : 3
 Total NaN in row 13173 : 2
 Total NaN in row 13174 : 2
 Total NaN in row 13175 : 1
 Total NaN in row 13176 : 9
 Total NaN in row 13177 : 0
 Total NaN in row 13178 : 2
 Total NaN in row 13179 : 0
 Total NaN in row 13180 : 10
 Total NaN in row 13181 : 0
 Total NaN in row 13182 : 1
 Total NaN in row 13183 : 2
 Total NaN in row 13184 : 10
 Total NaN in row 13185 : 2
 Total NaN in row 13186 : 0
 Total NaN in row 13187 : 10
 Total NaN in row 13188 : 0
 Total NaN in row 13189 : 2
 Total NaN in row 13190 : 0
 Total NaN in row 13191 : 1
 Total NaN in row 13192 : 10
 Total NaN in row 13193 : 10
 Total NaN in row 13194 : 2
 Total NaN in row 13195 : 2
 Total NaN in row 13196 : 2
 Total NaN in row 13197 : 1
 Total NaN in row 13198 : 0
 Total NaN in row 13199 : 9
 Total NaN in row 13200 : 3
 Total NaN in row 13201 : 2
 Total NaN in row 13202 : 1
 Total NaN in row 13203 : 2
 Total NaN in row 13204 : 9
 Total NaN in row 13205 : 10
 Total NaN in row 13206 : 9
 Total NaN in row 13207 : 9
 Total NaN in row 13208 : 10
 Total NaN in row 13209 : 10
 Total NaN in row 13210 : 3
 Total NaN in row 13211 : 0
 Total NaN in row 13212 : 0
 Total NaN in row 13213 : 2
 Total NaN in row 13214 : 9
 Total NaN in row 13215 : 9
 Total NaN in row 13216 : 9
 Total NaN in row 13217 : 0
 Total NaN in row 13218 : 0
 Total NaN in row 13219 : 0
 Total NaN in row 13220 : 9
 Total NaN in row 13221 : 3
 Total NaN in row 13222 : 3
 Total NaN in row 13223 : 2
 Total NaN in row 13224 : 2
 Total NaN in row 13225 : 2
 Total NaN in row 13226 : 1
 Total NaN in row 13227 : 2
 Total NaN in row 13228 : 9
 Total NaN in row 13229 : 0
 Total NaN in row 13230 : 3
 Total NaN in row 13231 : 0
 Total NaN in row 13232 : 0
 Total NaN in row 13233 : 1
 Total NaN in row 13234 : 1
 Total NaN in row 13235 : 0
 Total NaN in row 13236 : 3
 Total NaN in row 13237 : 0
 Total NaN in row 13238 : 2
 Total NaN in row 13239 : 3
 Total NaN in row 13240 : 10
 Total NaN in row 13241 : 2
 Total NaN in row 13242 : 0
 Total NaN in row 13243 : 10
 Total NaN in row 13244 : 10
 Total NaN in row 13245 : 2
 Total NaN in row 13246 : 3
 Total NaN in row 13247 : 3
 Total NaN in row 13248 : 3
 Total NaN in row 13249 : 3
 Total NaN in row 13250 : 3
 Total NaN in row 13251 : 3
 Total NaN in row 13252 : 3
 Total NaN in row 13253 : 2
 Total NaN in row 13254 : 3
 Total NaN in row 13255 : 9
 Total NaN in row 13256 : 7
 Total NaN in row 13257 : 10
 Total NaN in row 13258 : 0
 Total NaN in row 13259 : 1
 Total NaN in row 13260 : 10
 Total NaN in row 13261 : 2
 Total NaN in row 13262 : 0
 Total NaN in row 13263 : 2
 Total NaN in row 13264 : 3
 Total NaN in row 13265 : 2
 Total NaN in row 13266 : 1
 Total NaN in row 13267 : 1
 Total NaN in row 13268 : 9
 Total NaN in row 13269 : 2
 Total NaN in row 13270 : 3
 Total NaN in row 13271 : 0
 Total NaN in row 13272 : 1
 Total NaN in row 13273 : 0
 Total NaN in row 13274 : 10
 Total NaN in row 13275 : 3
 Total NaN in row 13276 : 0
 Total NaN in row 13277 : 0
 Total NaN in row 13278 : 1
 Total NaN in row 13279 : 0
 Total NaN in row 13280 : 2
 Total NaN in row 13281 : 9
 Total NaN in row 13282 : 9
 Total NaN in row 13283 : 2
 Total NaN in row 13284 : 9
 Total NaN in row 13285 : 9
 Total NaN in row 13286 : 10
 Total NaN in row 13287 : 9
 Total NaN in row 13288 : 9
 Total NaN in row 13289 : 1
 Total NaN in row 13290 : 0
 Total NaN in row 13291 : 0
 Total NaN in row 13292 : 1
 Total NaN in row 13293 : 9
 Total NaN in row 13294 : 0
 Total NaN in row 13295 : 0
 Total NaN in row 13296 : 9
 Total NaN in row 13297 : 0
 Total NaN in row 13298 : 9
 Total NaN in row 13299 : 9
 Total NaN in row 13300 : 10
 Total NaN in row 13301 : 2
 Total NaN in row 13302 : 0
 Total NaN in row 13303 : 0
 Total NaN in row 13304 : 1
 Total NaN in row 13305 : 0
 Total NaN in row 13306 : 4
 Total NaN in row 13307 : 9
 Total NaN in row 13308 : 9
 Total NaN in row 13309 : 2
 Total NaN in row 13310 : 9
 Total NaN in row 13311 : 10
 Total NaN in row 13312 : 9
 Total NaN in row 13313 : 0
 Total NaN in row 13314 : 3
 Total NaN in row 13315 : 9
 Total NaN in row 13316 : 9
 Total NaN in row 13317 : 1
 Total NaN in row 13318 : 2
 Total NaN in row 13319 : 1
 Total NaN in row 13320 : 9
 Total NaN in row 13321 : 1
 Total NaN in row 13322 : 2
 Total NaN in row 13323 : 2
 Total NaN in row 13324 : 0
 Total NaN in row 13325 : 0
 Total NaN in row 13326 : 0
 Total NaN in row 13327 : 1
 Total NaN in row 13328 : 0
 Total NaN in row 13329 : 0
 Total NaN in row 13330 : 2
 Total NaN in row 13331 : 0
 Total NaN in row 13332 : 2
 Total NaN in row 13333 : 2
 Total NaN in row 13334 : 0
 Total NaN in row 13335 : 2
 Total NaN in row 13336 : 2
 Total NaN in row 13337 : 0
 Total NaN in row 13338 : 9
 Total NaN in row 13339 : 0
 Total NaN in row 13340 : 1
 Total NaN in row 13341 : 0
 Total NaN in row 13342 : 0
 Total NaN in row 13343 : 0
 Total NaN in row 13344 : 9
 Total NaN in row 13345 : 3
 Total NaN in row 13346 : 2
 Total NaN in row 13347 : 1
 Total NaN in row 13348 : 0
 Total NaN in row 13349 : 3
 Total NaN in row 13350 : 1
 Total NaN in row 13351 : 2
 Total NaN in row 13352 : 0
 Total NaN in row 13353 : 9
 Total NaN in row 13354 : 1
 Total NaN in row 13355 : 2
 Total NaN in row 13356 : 9
 Total NaN in row 13357 : 3
 Total NaN in row 13358 : 0
 Total NaN in row 13359 : 2
 Total NaN in row 13360 : 1
 Total NaN in row 13361 : 0
 Total NaN in row 13362 : 9
 Total NaN in row 13363 : 0
 Total NaN in row 13364 : 1
 Total NaN in row 13365 : 0
 Total NaN in row 13366 : 0
 Total NaN in row 13367 : 2
 Total NaN in row 13368 : 3
 Total NaN in row 13369 : 2
 Total NaN in row 13370 : 2
 Total NaN in row 13371 : 2
 Total NaN in row 13372 : 2
 Total NaN in row 13373 : 2
 Total NaN in row 13374 : 1
 Total NaN in row 13375 : 9
 Total NaN in row 13376 : 3
 Total NaN in row 13377 : 4
 Total NaN in row 13378 : 10
 Total NaN in row 13379 : 0
 Total NaN in row 13380 : 0
 Total NaN in row 13381 : 0
 Total NaN in row 13382 : 21
 Total NaN in row 13383 : 9
 Total NaN in row 13384 : 10
 Total NaN in row 13385 : 2
 Total NaN in row 13386 : 2
 Total NaN in row 13387 : 3
 Total NaN in row 13388 : 0
 Total NaN in row 13389 : 2
 Total NaN in row 13390 : 2
 Total NaN in row 13391 : 0
 Total NaN in row 13392 : 0
 Total NaN in row 13393 : 2
 Total NaN in row 13394 : 2
 Total NaN in row 13395 : 0
 Total NaN in row 13396 : 2
 Total NaN in row 13397 : 10
 Total NaN in row 13398 : 2
 Total NaN in row 13399 : 2
 Total NaN in row 13400 : 2
 Total NaN in row 13401 : 0
 Total NaN in row 13402 : 2
 Total NaN in row 13403 : 2
 Total NaN in row 13404 : 2
 Total NaN in row 13405 : 0
 Total NaN in row 13406 : 0
 Total NaN in row 13407 : 0
 Total NaN in row 13408 : 2
 Total NaN in row 13409 : 0
 Total NaN in row 13410 : 2
 Total NaN in row 13411 : 2
 Total NaN in row 13412 : 0
 Total NaN in row 13413 : 1
 Total NaN in row 13414 : 2
 Total NaN in row 13415 : 0
 Total NaN in row 13416 : 0
 Total NaN in row 13417 : 0
 Total NaN in row 13418 : 1
 Total NaN in row 13419 : 1
 Total NaN in row 13420 : 1
 Total NaN in row 13421 : 3
 Total NaN in row 13422 : 2
 Total NaN in row 13423 : 9
 Total NaN in row 13424 : 2
 Total NaN in row 13425 : 2
 Total NaN in row 13426 : 2
 Total NaN in row 13427 : 9
 Total NaN in row 13428 : 9
 Total NaN in row 13429 : 2
 Total NaN in row 13430 : 9
 Total NaN in row 13431 : 0
 Total NaN in row 13432 : 2
 Total NaN in row 13433 : 2
 Total NaN in row 13434 : 0
 Total NaN in row 13435 : 2
 Total NaN in row 13436 : 0
 Total NaN in row 13437 : 1
 Total NaN in row 13438 : 0
 Total NaN in row 13439 : 0
 Total NaN in row 13440 : 2
 Total NaN in row 13441 : 2
 Total NaN in row 13442 : 2
 Total NaN in row 13443 : 2
 Total NaN in row 13444 : 9
 Total NaN in row 13445 : 10
 Total NaN in row 13446 : 2
 Total NaN in row 13447 : 0
 Total NaN in row 13448 : 3
 Total NaN in row 13449 : 1
 Total NaN in row 13450 : 2
 Total NaN in row 13451 : 0
 Total NaN in row 13452 : 0
 Total NaN in row 13453 : 0
 Total NaN in row 13454 : 2
 Total NaN in row 13455 : 2
 Total NaN in row 13456 : 2
 Total NaN in row 13457 : 0
 Total NaN in row 13458 : 0
 Total NaN in row 13459 : 9
 Total NaN in row 13460 : 1
 Total NaN in row 13461 : 0
 Total NaN in row 13462 : 0
 Total NaN in row 13463 : 10
 Total NaN in row 13464 : 0
 Total NaN in row 13465 : 2
 Total NaN in row 13466 : 9
 Total NaN in row 13467 : 1
 Total NaN in row 13468 : 0
 Total NaN in row 13469 : 9
 Total NaN in row 13470 : 2
 Total NaN in row 13471 : 1
 Total NaN in row 13472 : 2
 Total NaN in row 13473 : 0
 Total NaN in row 13474 : 9
 Total NaN in row 13475 : 9
 Total NaN in row 13476 : 1
 Total NaN in row 13477 : 0
 Total NaN in row 13478 : 2
 Total NaN in row 13479 : 9
 Total NaN in row 13480 : 1
 Total NaN in row 13481 : 0
 Total NaN in row 13482 : 2
 Total NaN in row 13483 : 0
 Total NaN in row 13484 : 2
 Total NaN in row 13485 : 9
 Total NaN in row 13486 : 1
 Total NaN in row 13487 : 9
 Total NaN in row 13488 : 0
 Total NaN in row 13489 : 2
 Total NaN in row 13490 : 0
 Total NaN in row 13491 : 2
 Total NaN in row 13492 : 10
 Total NaN in row 13493 : 0
 Total NaN in row 13494 : 1
 Total NaN in row 13495 : 2
 Total NaN in row 13496 : 2
 Total NaN in row 13497 : 0
 Total NaN in row 13498 : 9
 Total NaN in row 13499 : 1
 Total NaN in row 13500 : 0
 Total NaN in row 13501 : 9
 Total NaN in row 13502 : 2
 Total NaN in row 13503 : 0
 Total NaN in row 13504 : 9
 Total NaN in row 13505 : 2
 Total NaN in row 13506 : 3
 Total NaN in row 13507 : 2
 Total NaN in row 13508 : 9
 Total NaN in row 13509 : 9
 Total NaN in row 13510 : 9
 Total NaN in row 13511 : 0
 Total NaN in row 13512 : 2
 Total NaN in row 13513 : 0
 Total NaN in row 13514 : 1
 Total NaN in row 13515 : 1
 Total NaN in row 13516 : 0
 Total NaN in row 13517 : 3
 Total NaN in row 13518 : 1
 Total NaN in row 13519 : 2
 Total NaN in row 13520 : 0
 Total NaN in row 13521 : 1
 Total NaN in row 13522 : 1
 Total NaN in row 13523 : 0
 Total NaN in row 13524 : 1
 Total NaN in row 13525 : 3
 Total NaN in row 13526 : 9
 Total NaN in row 13527 : 1
 Total NaN in row 13528 : 0
 Total NaN in row 13529 : 9
 Total NaN in row 13530 : 1
 Total NaN in row 13531 : 10
 Total NaN in row 13532 : 9
 Total NaN in row 13533 : 10
 Total NaN in row 13534 : 10
 Total NaN in row 13535 : 1
 Total NaN in row 13536 : 10
 Total NaN in row 13537 : 1
 Total NaN in row 13538 : 2
 Total NaN in row 13539 : 2
 Total NaN in row 13540 : 2
 Total NaN in row 13541 : 0
 Total NaN in row 13542 : 2
 Total NaN in row 13543 : 9
 Total NaN in row 13544 : 10

 Total NaN in row 13545 : 0
 Total NaN in row 13546 : 0
 Total NaN in row 13547 : 10
 Total NaN in row 13548 : 2
 Total NaN in row 13549 : 1
 Total NaN in row 13550 : 2
 Total NaN in row 13551 : 1
 Total NaN in row 13552 : 9
 Total NaN in row 13553 : 1
 Total NaN in row 13554 : 10
 Total NaN in row 13555 : 9
 Total NaN in row 13556 : 3
 Total NaN in row 13557 : 9
 Total NaN in row 13558 : 0
 Total NaN in row 13559 : 3
 Total NaN in row 13560 : 0
 Total NaN in row 13561 : 2
 Total NaN in row 13562 : 1
 Total NaN in row 13563 : 2
 Total NaN in row 13564 : 0
 Total NaN in row 13565 : 0
 Total NaN in row 13566 : 1
 Total NaN in row 13567 : 2
 Total NaN in row 13568 : 3
 Total NaN in row 13569 : 0
 Total NaN in row 13570 : 9
 Total NaN in row 13571 : 2
 Total NaN in row 13572 : 2
 Total NaN in row 13573 : 2
 Total NaN in row 13574 : 3
 Total NaN in row 13575 : 9
 Total NaN in row 13576 : 9
 Total NaN in row 13577 : 1
 Total NaN in row 13578 : 0
 Total NaN in row 13579 : 2
 Total NaN in row 13580 : 2
 Total NaN in row 13581 : 0
 Total NaN in row 13582 : 3
 Total NaN in row 13583 : 1
 Total NaN in row 13584 : 1
 Total NaN in row 13585 : 2
 Total NaN in row 13586 : 3
 Total NaN in row 13587 : 0
 Total NaN in row 13588 : 1
 Total NaN in row 13589 : 2
 Total NaN in row 13590 : 0
 Total NaN in row 13591 : 0
 Total NaN in row 13592 : 2
 Total NaN in row 13593 : 9
 Total NaN in row 13594 : 9
 Total NaN in row 13595 : 1
 Total NaN in row 13596 : 1
 Total NaN in row 13597 : 9
 Total NaN in row 13598 : 0
 Total NaN in row 13599 : 2
 Total NaN in row 13600 : 9
 Total NaN in row 13601 : 1
 Total NaN in row 13602 : 2
 Total NaN in row 13603 : 0
 Total NaN in row 13604 : 2
 Total NaN in row 13605 : 2
 Total NaN in row 13606 : 1
 Total NaN in row 13607 : 9
 Total NaN in row 13608 : 2
 Total NaN in row 13609 : 9
 Total NaN in row 13610 : 2
 Total NaN in row 13611 : 0
 Total NaN in row 13612 : 9
 Total NaN in row 13613 : 1
 Total NaN in row 13614 : 0
 Total NaN in row 13615 : 2
 Total NaN in row 13616 : 2
 Total NaN in row 13617 : 0
 Total NaN in row 13618 : 1
 Total NaN in row 13619 : 9
 Total NaN in row 13620 : 1
 Total NaN in row 13621 : 2
 Total NaN in row 13622 : 2
 Total NaN in row 13623 : 2
 Total NaN in row 13624 : 2
 Total NaN in row 13625 : 9
 Total NaN in row 13626 : 2
 Total NaN in row 13627 : 2
 Total NaN in row 13628 : 2
 Total NaN in row 13629 : 0
 Total NaN in row 13630 : 9
 Total NaN in row 13631 : 9
 Total NaN in row 13632 : 2
 Total NaN in row 13633 : 2
 Total NaN in row 13634 : 9
 Total NaN in row 13635 : 0
 Total NaN in row 13636 : 0
 Total NaN in row 13637 : 0
 Total NaN in row 13638 : 0
 Total NaN in row 13639 : 2
 Total NaN in row 13640 : 0
 Total NaN in row 13641 : 9
 Total NaN in row 13642 : 2
 Total NaN in row 13643 : 0
 Total NaN in row 13644 : 0
 Total NaN in row 13645 : 2
 Total NaN in row 13646 : 2
 Total NaN in row 13647 : 0
 Total NaN in row 13648 : 21
 Total NaN in row 13649 : 0
 Total NaN in row 13650 : 9
 Total NaN in row 13651 : 0
 Total NaN in row 13652 : 3
 Total NaN in row 13653 : 9
 Total NaN in row 13654 : 2
 Total NaN in row 13655 : 2
 Total NaN in row 13656 : 9
 Total NaN in row 13657 : 9
 Total NaN in row 13658 : 2
 Total NaN in row 13659 : 1
 Total NaN in row 13660 : 0
 Total NaN in row 13661 : 2
 Total NaN in row 13662 : 9
 Total NaN in row 13663 : 2
 Total NaN in row 13664 : 9
 Total NaN in row 13665 : 9
 Total NaN in row 13666 : 1
 Total NaN in row 13667 : 9
 Total NaN in row 13668 : 9
 Total NaN in row 13669 : 9
 Total NaN in row 13670 : 2
 Total NaN in row 13671 : 0
 Total NaN in row 13672 : 2
 Total NaN in row 13673 : 2
 Total NaN in row 13674 : 0
 Total NaN in row 13675 : 0
 Total NaN in row 13676 : 2
 Total NaN in row 13677 : 0
 Total NaN in row 13678 : 9
 Total NaN in row 13679 : 1
 Total NaN in row 13680 : 0
 Total NaN in row 13681 : 2
 Total NaN in row 13682 : 9
 Total NaN in row 13683 : 1
 Total NaN in row 13684 : 0
 Total NaN in row 13685 : 0
 Total NaN in row 13686 : 0
 Total NaN in row 13687 : 1
 Total NaN in row 13688 : 0
 Total NaN in row 13689 : 2
 Total NaN in row 13690 : 9
 Total NaN in row 13691 : 1
 Total NaN in row 13692 : 9
 Total NaN in row 13693 : 3
 Total NaN in row 13694 : 2
 Total NaN in row 13695 : 0
 Total NaN in row 13696 : 1
 Total NaN in row 13697 : 0
 Total NaN in row 13698 : 9
 Total NaN in row 13699 : 1
 Total NaN in row 13700 : 0
 Total NaN in row 13701 : 9
 Total NaN in row 13702 : 1
 Total NaN in row 13703 : 5
 Total NaN in row 13704 : 2
 Total NaN in row 13705 : 3
 Total NaN in row 13706 : 0
 Total NaN in row 13707 : 2
 Total NaN in row 13708 : 10
 Total NaN in row 13709 : 9
 Total NaN in row 13710 : 2
 Total NaN in row 13711 : 9
 Total NaN in row 13712 : 1
 Total NaN in row 13713 : 10
 Total NaN in row 13714 : 10
 Total NaN in row 13715 : 2
 Total NaN in row 13716 : 1
 Total NaN in row 13717 : 2
 Total NaN in row 13718 : 10
 Total NaN in row 13719 : 0
 Total NaN in row 13720 : 2
 Total NaN in row 13721 : 9
 Total NaN in row 13722 : 9
 Total NaN in row 13723 : 0
 Total NaN in row 13724 : 1
 Total NaN in row 13725 : 9
 Total NaN in row 13726 : 21
 Total NaN in row 13727 : 2
 Total NaN in row 13728 : 2
 Total NaN in row 13729 : 2
 Total NaN in row 13730 : 0
 Total NaN in row 13731 : 2
 Total NaN in row 13732 : 0
 Total NaN in row 13733 : 3
 Total NaN in row 13734 : 0
 Total NaN in row 13735 : 0
 Total NaN in row 13736 : 2
 Total NaN in row 13737 : 0
 Total NaN in row 13738 : 9
 Total NaN in row 13739 : 3
 Total NaN in row 13740 : 2
 Total NaN in row 13741 : 1
 Total NaN in row 13742 : 1
 Total NaN in row 13743 : 0
 Total NaN in row 13744 : 7
 Total NaN in row 13745 : 1
 Total NaN in row 13746 : 0
 Total NaN in row 13747 : 1
 Total NaN in row 13748 : 9
 Total NaN in row 13749 : 1
 Total NaN in row 13750 : 1
 Total NaN in row 13751 : 1
 Total NaN in row 13752 : 3
 Total NaN in row 13753 : 1
 Total NaN in row 13754 : 2
 Total NaN in row 13755 : 1
 Total NaN in row 13756 : 1
 Total NaN in row 13757 : 3
 Total NaN in row 13758 : 0
 Total NaN in row 13759 : 10
 Total NaN in row 13760 : 0
 Total NaN in row 13761 : 3
 Total NaN in row 13762 : 1
 Total NaN in row 13763 : 1
 Total NaN in row 13764 : 2
 Total NaN in row 13765 : 1
 Total NaN in row 13766 : 2
 Total NaN in row 13767 : 1
 Total NaN in row 13768 : 9
 Total NaN in row 13769 : 2
 Total NaN in row 13770 : 0
 Total NaN in row 13771 : 1
 Total NaN in row 13772 : 1
 Total NaN in row 13773 : 2
 Total NaN in row 13774 : 2
 Total NaN in row 13775 : 9
 Total NaN in row 13776 : 2
 Total NaN in row 13777 : 1
 Total NaN in row 13778 : 0
 Total NaN in row 13779 : 4
 Total NaN in row 13780 : 0
 Total NaN in row 13781 : 1
 Total NaN in row 13782 : 2
 Total NaN in row 13783 : 2
 Total NaN in row 13784 : 2
 Total NaN in row 13785 : 7
 Total NaN in row 13786 : 1
 Total NaN in row 13787 : 2
 Total NaN in row 13788 : 0
 Total NaN in row 13789 : 1
 Total NaN in row 13790 : 0
 Total NaN in row 13791 : 1
 Total NaN in row 13792 : 7
 Total NaN in row 13793 : 9
 Total NaN in row 13794 : 1
 Total NaN in row 13795 : 0
 Total NaN in row 13796 : 0
 Total NaN in row 13797 : 1
 Total NaN in row 13798 : 0
 Total NaN in row 13799 : 9
 Total NaN in row 13800 : 10
 Total NaN in row 13801 : 2
 Total NaN in row 13802 : 2
 Total NaN in row 13803 : 0
 Total NaN in row 13804 : 7
 Total NaN in row 13805 : 1
 Total NaN in row 13806 : 9
 Total NaN in row 13807 : 3
 Total NaN in row 13808 : 2
 Total NaN in row 13809 : 0
 Total NaN in row 13810 : 2
 Total NaN in row 13811 : 1
 Total NaN in row 13812 : 0
 Total NaN in row 13813 : 2
 Total NaN in row 13814 : 0
 Total NaN in row 13815 : 1
 Total NaN in row 13816 : 9
 Total NaN in row 13817 : 0
 Total NaN in row 13818 : 1
 Total NaN in row 13819 : 0
 Total NaN in row 13820 : 9
 Total NaN in row 13821 : 1
 Total NaN in row 13822 : 2
 Total NaN in row 13823 : 10
 Total NaN in row 13824 : 9
 Total NaN in row 13825 : 1
 Total NaN in row 13826 : 9
 Total NaN in row 13827 : 2
 Total NaN in row 13828 : 10
 Total NaN in row 13829 : 0
 Total NaN in row 13830 : 0
 Total NaN in row 13831 : 2
 Total NaN in row 13832 : 2
 Total NaN in row 13833 : 0
 Total NaN in row 13834 : 2
 Total NaN in row 13835 : 9
 Total NaN in row 13836 : 9
 Total NaN in row 13837 : 9
 Total NaN in row 13838 : 3
 Total NaN in row 13839 : 2
 Total NaN in row 13840 : 1
 Total NaN in row 13841 : 0

 Total NaN in row 13842 : 0
 Total NaN in row 13843 : 2
 Total NaN in row 13844 : 2
 Total NaN in row 13845 : 2
 Total NaN in row 13846 : 2
 Total NaN in row 13847 : 9
 Total NaN in row 13848 : 7
 Total NaN in row 13849 : 1
 Total NaN in row 13850 : 2
 Total NaN in row 13851 : 9
 Total NaN in row 13852 : 10
 Total NaN in row 13853 : 1
 Total NaN in row 13854 : 0
 Total NaN in row 13855 : 9
 Total NaN in row 13856 : 0
 Total NaN in row 13857 : 0
 Total NaN in row 13858 : 1
 Total NaN in row 13859 : 9
 Total NaN in row 13860 : 2
 Total NaN in row 13861 : 0
 Total NaN in row 13862 : 0
 Total NaN in row 13863 : 0
 Total NaN in row 13864 : 9
 Total NaN in row 13865 : 1
 Total NaN in row 13866 : 3
 Total NaN in row 13867 : 2
 Total NaN in row 13868 : 0
 Total NaN in row 13869 : 0
 Total NaN in row 13870 : 7
 Total NaN in row 13871 : 2
 Total NaN in row 13872 : 2
 Total NaN in row 13873 : 9
 Total NaN in row 13874 : 1
 Total NaN in row 13875 : 0
 Total NaN in row 13876 : 0
 Total NaN in row 13877 : 3
 Total NaN in row 13878 : 0
 Total NaN in row 13879 : 1
 Total NaN in row 13880 : 1
 Total NaN in row 13881 : 0
 Total NaN in row 13882 : 0
 Total NaN in row 13883 : 2
 Total NaN in row 13884 : 3
 Total NaN in row 13885 : 1
 Total NaN in row 13886 : 9
 Total NaN in row 13887 : 0
 Total NaN in row 13888 : 2
 Total NaN in row 13889 : 1
 Total NaN in row 13890 : 9
 Total NaN in row 13891 : 3
 Total NaN in row 13892 : 1
 Total NaN in row 13893 : 3
 Total NaN in row 13894 : 0
 Total NaN in row 13895 : 1
 Total NaN in row 13896 : 2
 Total NaN in row 13897 : 2
 Total NaN in row 13898 : 2
 Total NaN in row 13899 : 2
 Total NaN in row 13900 : 2
 Total NaN in row 13901 : 9
 Total NaN in row 13902 : 9
 Total NaN in row 13903 : 10
 Total NaN in row 13904 : 2
 Total NaN in row 13905 : 9
 Total NaN in row 13906 : 1
 Total NaN in row 13907 : 9
 Total NaN in row 13908 : 2
 Total NaN in row 13909 : 2
 Total NaN in row 13910 : 9
 Total NaN in row 13911 : 9
 Total NaN in row 13912 : 9
 Total NaN in row 13913 : 9
 Total NaN in row 13914 : 2
 Total NaN in row 13915 : 2
 Total NaN in row 13916 : 2
 Total NaN in row 13917 : 3
 Total NaN in row 13918 : 0
 Total NaN in row 13919 : 0
 Total NaN in row 13920 : 3
 Total NaN in row 13921 : 1
 Total NaN in row 13922 : 1
 Total NaN in row 13923 : 2
 Total NaN in row 13924 : 2
 Total NaN in row 13925 : 0
 Total NaN in row 13926 : 0
 Total NaN in row 13927 : 0
 Total NaN in row 13928 : 2
 Total NaN in row 13929 : 1
 Total NaN in row 13930 : 0
 Total NaN in row 13931 : 2
 Total NaN in row 13932 : 3
 Total NaN in row 13933 : 3
 Total NaN in row 13934 : 2
 Total NaN in row 13935 : 1
 Total NaN in row 13936 : 9
 Total NaN in row 13937 : 0
 Total NaN in row 13938 : 0
 Total NaN in row 13939 : 9
 Total NaN in row 13940 : 0
 Total NaN in row 13941 : 0
 Total NaN in row 13942 : 2
 Total NaN in row 13943 : 2
 Total NaN in row 13944 : 2
 Total NaN in row 13945 : 1
 Total NaN in row 13946 : 10
 Total NaN in row 13947 : 0
 Total NaN in row 13948 : 2
 Total NaN in row 13949 : 9
 Total NaN in row 13950 : 2
 Total NaN in row 13951 : 0
 Total NaN in row 13952 : 2
 Total NaN in row 13953 : 2
 Total NaN in row 13954 : 1
 Total NaN in row 13955 : 0
 Total NaN in row 13956 : 2
 Total NaN in row 13957 : 0
 Total NaN in row 13958 : 2
 Total NaN in row 13959 : 0
 Total NaN in row 13960 : 0
 Total NaN in row 13961 : 0
 Total NaN in row 13962 : 3
 Total NaN in row 13963 : 0
 Total NaN in row 13964 : 1
 Total NaN in row 13965 : 1
 Total NaN in row 13966 : 1
 Total NaN in row 13967 : 0
 Total NaN in row 13968 : 1
 Total NaN in row 13969 : 0
 Total NaN in row 13970 : 2
 Total NaN in row 13971 : 2
 Total NaN in row 13972 : 0
 Total NaN in row 13973 : 2
 Total NaN in row 13974 : 0
 Total NaN in row 13975 : 2
 Total NaN in row 13976 : 2
 Total NaN in row 13977 : 0
 Total NaN in row 13978 : 2
 Total NaN in row 13979 : 3
 Total NaN in row 13980 : 3
 Total NaN in row 13981 : 2
 Total NaN in row 13982 : 0
 Total NaN in row 13983 : 0
 Total NaN in row 13984 : 0
 Total NaN in row 13985 : 0
 Total NaN in row 13986 : 0
 Total NaN in row 13987 : 2
 Total NaN in row 13988 : 2
 Total NaN in row 13989 : 0
 Total NaN in row 13990 : 10
 Total NaN in row 13991 : 2
 Total NaN in row 13992 : 0
 Total NaN in row 13993 : 9
 Total NaN in row 13994 : 2
 Total NaN in row 13995 : 0
 Total NaN in row 13996 : 2
 Total NaN in row 13997 : 0
 Total NaN in row 13998 : 2
 Total NaN in row 13999 : 2
 Total NaN in row 14000 : 2
 Total NaN in row 14001 : 2
 Total NaN in row 14002 : 0
 Total NaN in row 14003 : 2
 Total NaN in row 14004 : 2
 Total NaN in row 14005 : 1
 Total NaN in row 14006 : 2
 Total NaN in row 14007 : 8
 Total NaN in row 14008 : 0
 Total NaN in row 14009 : 0
 Total NaN in row 14010 : 21
 Total NaN in row 14011 : 0
 Total NaN in row 14012 : 2
 Total NaN in row 14013 : 0
 Total NaN in row 14014 : 0
 Total NaN in row 14015 : 1
 Total NaN in row 14016 : 0
 Total NaN in row 14017 : 2
 Total NaN in row 14018 : 2
 Total NaN in row 14019 : 0
 Total NaN in row 14020 : 2
 Total NaN in row 14021 : 0
 Total NaN in row 14022 : 2
 Total NaN in row 14023 : 0
 Total NaN in row 14024 : 1
 Total NaN in row 14025 : 0
 Total NaN in row 14026 : 0
 Total NaN in row 14027 : 7
 Total NaN in row 14028 : 0
 Total NaN in row 14029 : 0
 Total NaN in row 14030 : 0
 Total NaN in row 14031 : 0
 Total NaN in row 14032 : 0
 Total NaN in row 14033 : 5
 Total NaN in row 14034 : 9
 Total NaN in row 14035 : 0
 Total NaN in row 14036 : 3
 Total NaN in row 14037 : 7
 Total NaN in row 14038 : 9
 Total NaN in row 14039 : 0
 Total NaN in row 14040 : 9
 Total NaN in row 14041 : 10
 Total NaN in row 14042 : 0
 Total NaN in row 14043 : 0
 Total NaN in row 14044 : 0
 Total NaN in row 14045 : 1
 Total NaN in row 14046 : 0
 Total NaN in row 14047 : 9
 Total NaN in row 14048 : 9
 Total NaN in row 14049 : 2
 Total NaN in row 14050 : 0
 Total NaN in row 14051 : 0
 Total NaN in row 14052 : 9
 Total NaN in row 14053 : 0
 Total NaN in row 14054 : 0
 Total NaN in row 14055 : 2
 Total NaN in row 14056 : 0
 Total NaN in row 14057 : 0
 Total NaN in row 14058 : 1
 Total NaN in row 14059 : 0
 Total NaN in row 14060 : 2
 Total NaN in row 14061 : 9
 Total NaN in row 14062 : 0
 Total NaN in row 14063 : 9
 Total NaN in row 14064 : 2
 Total NaN in row 14065 : 1
 Total NaN in row 14066 : 1
 Total NaN in row 14067 : 2
 Total NaN in row 14068 : 2
 Total NaN in row 14069 : 2
 Total NaN in row 14070 : 2
 Total NaN in row 14071 : 0
 Total NaN in row 14072 : 9
 Total NaN in row 14073 : 2
 Total NaN in row 14074 : 1
 Total NaN in row 14075 : 3
 Total NaN in row 14076 : 2
 Total NaN in row 14077 : 3
 Total NaN in row 14078 : 1
 Total NaN in row 14079 : 2
 Total NaN in row 14080 : 9
 Total NaN in row 14081 : 9
 Total NaN in row 14082 : 10
 Total NaN in row 14083 : 9
 Total NaN in row 14084 : 2
 Total NaN in row 14085 : 9
 Total NaN in row 14086 : 10
 Total NaN in row 14087 : 2
 Total NaN in row 14088 : 3
 Total NaN in row 14089 : 7
 Total NaN in row 14090 : 2
 Total NaN in row 14091 : 0
 Total NaN in row 14092 : 9
 Total NaN in row 14093 : 9
 Total NaN in row 14094 : 9
 Total NaN in row 14095 : 4
 Total NaN in row 14096 : 0
 Total NaN in row 14097 : 1
 Total NaN in row 14098 : 2
 Total NaN in row 14099 : 0
 Total NaN in row 14100 : 0
 Total NaN in row 14101 : 0
 Total NaN in row 14102 : 2
 Total NaN in row 14103 : 1
 Total NaN in row 14104 : 0
 Total NaN in row 14105 : 1
 Total NaN in row 14106 : 2
 Total NaN in row 14107 : 2
 Total NaN in row 14108 : 1
 Total NaN in row 14109 : 3
 Total NaN in row 14110 : 2
 Total NaN in row 14111 : 0
 Total NaN in row 14112 : 0
 Total NaN in row 14113 : 9
 Total NaN in row 14114 : 3
 Total NaN in row 14115 : 1
 Total NaN in row 14116 : 2
 Total NaN in row 14117 : 9
 Total NaN in row 14118 : 2
 Total NaN in row 14119 : 0
 Total NaN in row 14120 : 1
 Total NaN in row 14121 : 0
 Total NaN in row 14122 : 2
 Total NaN in row 14123 : 1
 Total NaN in row 14124 : 7
 Total NaN in row 14125 : 2
 Total NaN in row 14126 : 0
 Total NaN in row 14127 : 2
 Total NaN in row 14128 : 2
 Total NaN in row 14129 : 1
 Total NaN in row 14130 : 0
 Total NaN in row 14131 : 1
 Total NaN in row 14132 : 0
 Total NaN in row 14133 : 2
 Total NaN in row 14134 : 0
 Total NaN in row 14135 : 1
 Total NaN in row 14136 : 1
 Total NaN in row 14137 : 3
 Total NaN in row 14138 : 0
 Total NaN in row 14139 : 0
 Total NaN in row 14140 : 9

 Total NaN in row 14141 : 9
 Total NaN in row 14142 : 2
 Total NaN in row 14143 : 1
 Total NaN in row 14144 : 9
 Total NaN in row 14145 : 0
 Total NaN in row 14146 : 0
 Total NaN in row 14147 : 1
 Total NaN in row 14148 : 2
 Total NaN in row 14149 : 1
 Total NaN in row 14150 : 1
 Total NaN in row 14151 : 1
 Total NaN in row 14152 : 9
 Total NaN in row 14153 : 3
 Total NaN in row 14154 : 1
 Total NaN in row 14155 : 0
 Total NaN in row 14156 : 2
 Total NaN in row 14157 : 10
 Total NaN in row 14158 : 1
 Total NaN in row 14159 : 9
 Total NaN in row 14160 : 9
 Total NaN in row 14161 : 1
 Total NaN in row 14162 : 1
 Total NaN in row 14163 : 1
 Total NaN in row 14164 : 9
 Total NaN in row 14165 : 2
 Total NaN in row 14166 : 10
 Total NaN in row 14167 : 0
 Total NaN in row 14168 : 2
 Total NaN in row 14169 : 0
 Total NaN in row 14170 : 0
 Total NaN in row 14171 : 0
 Total NaN in row 14172 : 9
 Total NaN in row 14173 : 2
 Total NaN in row 14174 : 9
 Total NaN in row 14175 : 9
 Total NaN in row 14176 : 1
 Total NaN in row 14177 : 9
 Total NaN in row 14178 : 2
 Total NaN in row 14179 : 0
 Total NaN in row 14180 : 2
 Total NaN in row 14181 : 0
 Total NaN in row 14182 : 0
 Total NaN in row 14183 : 0
 Total NaN in row 14184 : 0
 Total NaN in row 14185 : 2
 Total NaN in row 14186 : 0
 Total NaN in row 14187 : 1
 Total NaN in row 14188 : 2
 Total NaN in row 14189 : 9
 Total NaN in row 14190 : 2
 Total NaN in row 14191 : 2
 Total NaN in row 14192 : 0
 Total NaN in row 14193 : 2
 Total NaN in row 14194 : 1
 Total NaN in row 14195 : 2
 Total NaN in row 14196 : 2
 Total NaN in row 14197 : 2
 Total NaN in row 14198 : 3
 Total NaN in row 14199 : 2
 Total NaN in row 14200 : 1
 Total NaN in row 14201 : 1
 Total NaN in row 14202 : 0
 Total NaN in row 14203 : 2
 Total NaN in row 14204 : 2
 Total NaN in row 14205 : 2
 Total NaN in row 14206 : 0
 Total NaN in row 14207 : 2
 Total NaN in row 14208 : 2
 Total NaN in row 14209 : 10
 Total NaN in row 14210 : 1
 Total NaN in row 14211 : 0
 Total NaN in row 14212 : 0
 Total NaN in row 14213 : 3
 Total NaN in row 14214 : 3
 Total NaN in row 14215 : 0
 Total NaN in row 14216 : 1
 Total NaN in row 14217 : 1
 Total NaN in row 14218 : 0
 Total NaN in row 14219 : 2
 Total NaN in row 14220 : 0
 Total NaN in row 14221 : 7
 Total NaN in row 14222 : 0
 Total NaN in row 14223 : 1
 Total NaN in row 14224 : 0
 Total NaN in row 14225 : 2
 Total NaN in row 14226 : 4
 Total NaN in row 14227 : 0
 Total NaN in row 14228 : 8
 Total NaN in row 14229 : 2
 Total NaN in row 14230 : 4
 Total NaN in row 14231 : 10
 Total NaN in row 14232 : 9
 Total NaN in row 14233 : 1
 Total NaN in row 14234 : 2
 Total NaN in row 14235 : 1
 Total NaN in row 14236 : 2
 Total NaN in row 14237 : 2
 Total NaN in row 14238 : 1
 Total NaN in row 14239 : 2
 Total NaN in row 14240 : 0
 Total NaN in row 14241 : 0
 Total NaN in row 14242 : 0
 Total NaN in row 14243 : 2
 Total NaN in row 14244 : 2
 Total NaN in row 14245 : 0
 Total NaN in row 14246 : 10
 Total NaN in row 14247 : 0
 Total NaN in row 14248 : 0
 Total NaN in row 14249 : 2
 Total NaN in row 14250 : 2
 Total NaN in row 14251 : 0
 Total NaN in row 14252 : 0
 Total NaN in row 14253 : 0
 Total NaN in row 14254 : 3
 Total NaN in row 14255 : 3
 Total NaN in row 14256 : 10
 Total NaN in row 14257 : 3
 Total NaN in row 14258 : 2
 Total NaN in row 14259 : 10
 Total NaN in row 14260 : 9
 Total NaN in row 14261 : 1
 Total NaN in row 14262 : 9
 Total NaN in row 14263 : 2
 Total NaN in row 14264 : 1
 Total NaN in row 14265 : 2
 Total NaN in row 14266 : 9
 Total NaN in row 14267 : 0
 Total NaN in row 14268 : 1
 Total NaN in row 14269 : 2
 Total NaN in row 14270 : 1
 Total NaN in row 14271 : 0
 Total NaN in row 14272 : 0
 Total NaN in row 14273 : 0
 Total NaN in row 14274 : 2
 Total NaN in row 14275 : 0
 Total NaN in row 14276 : 9
 Total NaN in row 14277 : 0
 Total NaN in row 14278 : 0
 Total NaN in row 14279 : 2
 Total NaN in row 14280 : 0
 Total NaN in row 14281 : 1
 Total NaN in row 14282 : 0
 Total NaN in row 14283 : 10
 Total NaN in row 14284 : 9
 Total NaN in row 14285 : 2
 Total NaN in row 14286 : 0
 Total NaN in row 14287 : 9
 Total NaN in row 14288 : 2
 Total NaN in row 14289 : 0
 Total NaN in row 14290 : 2
 Total NaN in row 14291 : 1
 Total NaN in row 14292 : 2
 Total NaN in row 14293 : 2
 Total NaN in row 14294 : 0
 Total NaN in row 14295 : 2
 Total NaN in row 14296 : 3
 Total NaN in row 14297 : 1
 Total NaN in row 14298 : 0
 Total NaN in row 14299 : 2
 Total NaN in row 14300 : 3
 Total NaN in row 14301 : 1
 Total NaN in row 14302 : 1
 Total NaN in row 14303 : 1
 Total NaN in row 14304 : 2
 Total NaN in row 14305 : 3
 Total NaN in row 14306 : 9
 Total NaN in row 14307 : 0
 Total NaN in row 14308 : 10
 Total NaN in row 14309 : 9
 Total NaN in row 14310 : 9
 Total NaN in row 14311 : 9
 Total NaN in row 14312 : 0
 Total NaN in row 14313 : 1
 Total NaN in row 14314 : 1
 Total NaN in row 14315 : 0
 Total NaN in row 14316 : 2
 Total NaN in row 14317 : 10
 Total NaN in row 14318 : 1
 Total NaN in row 14319 : 0
 Total NaN in row 14320 : 10
 Total NaN in row 14321 : 9
 Total NaN in row 14322 : 9
 Total NaN in row 14323 : 2
 Total NaN in row 14324 : 9
 Total NaN in row 14325 : 1
 Total NaN in row 14326 : 2
 Total NaN in row 14327 : 9
 Total NaN in row 14328 : 2
 Total NaN in row 14329 : 2
 Total NaN in row 14330 : 2
 Total NaN in row 14331 : 9
 Total NaN in row 14332 : 3
 Total NaN in row 14333 : 2
 Total NaN in row 14334 : 2
 Total NaN in row 14335 : 10
 Total NaN in row 14336 : 0
 Total NaN in row 14337 : 0
 Total NaN in row 14338 : 1
 Total NaN in row 14339 : 9
 Total NaN in row 14340 : 10
 Total NaN in row 14341 : 9
 Total NaN in row 14342 : 1
 Total NaN in row 14343 : 9
 Total NaN in row 14344 : 1
 Total NaN in row 14345 : 2
 Total NaN in row 14346 : 2
 Total NaN in row 14347 : 2
 Total NaN in row 14348 : 0
 Total NaN in row 14349 : 0
 Total NaN in row 14350 : 2
 Total NaN in row 14351 : 9
 Total NaN in row 14352 : 3
 Total NaN in row 14353 : 9
 Total NaN in row 14354 : 10
 Total NaN in row 14355 : 2
 Total NaN in row 14356 : 0
 Total NaN in row 14357 : 0
 Total NaN in row 14358 : 0
 Total NaN in row 14359 : 2
 Total NaN in row 14360 : 0
 Total NaN in row 14361 : 0
 Total NaN in row 14362 : 0
 Total NaN in row 14363 : 9
 Total NaN in row 14364 : 2
 Total NaN in row 14365 : 2
 Total NaN in row 14366 : 3
 Total NaN in row 14367 : 2
 Total NaN in row 14368 : 1
 Total NaN in row 14369 : 2
 Total NaN in row 14370 : 3
 Total NaN in row 14371 : 2
 Total NaN in row 14372 : 2
 Total NaN in row 14373 : 9
 Total NaN in row 14374 : 0
 Total NaN in row 14375 : 1
 Total NaN in row 14376 : 2
 Total NaN in row 14377 : 0
 Total NaN in row 14378 : 0
 Total NaN in row 14379 : 10
 Total NaN in row 14380 : 2
 Total NaN in row 14381 : 0
 Total NaN in row 14382 : 0
 Total NaN in row 14383 : 0
 Total NaN in row 14384 : 1
 Total NaN in row 14385 : 2
 Total NaN in row 14386 : 9
 Total NaN in row 14387 : 2
 Total NaN in row 14388 : 9
 Total NaN in row 14389 : 2
 Total NaN in row 14390 : 3
 Total NaN in row 14391 : 2
 Total NaN in row 14392 : 0
 Total NaN in row 14393 : 9
 Total NaN in row 14394 : 2
 Total NaN in row 14395 : 2
 Total NaN in row 14396 : 3
 Total NaN in row 14397 : 1
 Total NaN in row 14398 : 2
 Total NaN in row 14399 : 1
 Total NaN in row 14400 : 9
 Total NaN in row 14401 : 0
 Total NaN in row 14402 : 9
 Total NaN in row 14403 : 0
 Total NaN in row 14404 : 10
 Total NaN in row 14405 : 2
 Total NaN in row 14406 : 9
 Total NaN in row 14407 : 2
 Total NaN in row 14408 : 0
 Total NaN in row 14409 : 9
 Total NaN in row 14410 : 0
 Total NaN in row 14411 : 9
 Total NaN in row 14412 : 0
 Total NaN in row 14413 : 2
 Total NaN in row 14414 : 0
 Total NaN in row 14415 : 9
 Total NaN in row 14416 : 0
 Total NaN in row 14417 : 2
 Total NaN in row 14418 : 1
 Total NaN in row 14419 : 7
 Total NaN in row 14420 : 9
 Total NaN in row 14421 : 2
 Total NaN in row 14422 : 0
 Total NaN in row 14423 : 2
 Total NaN in row 14424 : 0
 Total NaN in row 14425 : 1
 Total NaN in row 14426 : 2
 Total NaN in row 14427 : 9
 Total NaN in row 14428 : 0
 Total NaN in row 14429 : 0
 Total NaN in row 14430 : 9
 Total NaN in row 14431 : 9
 Total NaN in row 14432 : 0
 Total NaN in row 14433 : 3
 Total NaN in row 14434 : 1
 Total NaN in row 14435 : 9
 Total NaN in row 14436 : 2
 Total NaN in row 14437 : 0
 Total NaN in row 14438 : 9
 Total NaN in row 14439 : 3
 Total NaN in row 14440 : 3
 Total NaN in row 14441 : 3
 Total NaN in row 14442 : 9
 Total NaN in row 14443 : 3
 Total NaN in row 14444 : 1
 Total NaN in row 14445 : 10
 Total NaN in row 14446 : 0
 Total NaN in row 14447 : 0
 Total NaN in row 14448 : 2
 Total NaN in row 14449 : 2
 Total NaN in row 14450 : 2
 Total NaN in row 14451 : 1
 Total NaN in row 14452 : 0
 Total NaN in row 14453 : 0
 Total NaN in row 14454 : 3
 Total NaN in row 14455 : 0
 Total NaN in row 14456 : 9
 Total NaN in row 14457 : 9
 Total NaN in row 14458 : 2
 Total NaN in row 14459 : 9
 Total NaN in row 14460 : 2
 Total NaN in row 14461 : 9
 Total NaN in row 14462 : 0
 Total NaN in row 14463 : 0
 Total NaN in row 14464 : 2
 Total NaN in row 14465 : 3
 Total NaN in row 14466 : 9
 Total NaN in row 14467 : 0
 Total NaN in row 14468 : 1

 Total NaN in row 14469 : 2
 Total NaN in row 14470 : 9
 Total NaN in row 14471 : 2
 Total NaN in row 14472 : 21
 Total NaN in row 14473 : 10
 Total NaN in row 14474 : 0
 Total NaN in row 14475 : 2
 Total NaN in row 14476 : 0
 Total NaN in row 14477 : 0
 Total NaN in row 14478 : 2
 Total NaN in row 14479 : 9
 Total NaN in row 14480 : 2
 Total NaN in row 14481 : 9
 Total NaN in row 14482 : 0
 Total NaN in row 14483 : 2
 Total NaN in row 14484 : 1
 Total NaN in row 14485 : 9
 Total NaN in row 14486 : 1
 Total NaN in row 14487 : 10
 Total NaN in row 14488 : 9
 Total NaN in row 14489 : 9
 Total NaN in row 14490 : 9
 Total NaN in row 14491 : 3
 Total NaN in row 14492 : 0
 Total NaN in row 14493 : 2
 Total NaN in row 14494 : 2
 Total NaN in row 14495 : 9
 Total NaN in row 14496 : 9
 Total NaN in row 14497 : 0
 Total NaN in row 14498 : 9
 Total NaN in row 14499 : 1
 Total NaN in row 14500 : 2
 Total NaN in row 14501 : 2
 Total NaN in row 14502 : 0
 Total NaN in row 14503 : 9
 Total NaN in row 14504 : 1
 Total NaN in row 14505 : 1
 Total NaN in row 14506 : 3
 Total NaN in row 14507 : 3
 Total NaN in row 14508 : 2
 Total NaN in row 14509 : 0
 Total NaN in row 14510 : 2
 Total NaN in row 14511 : 0
 Total NaN in row 14512 : 9
 Total NaN in row 14513 : 0
 Total NaN in row 14514 : 0
 Total NaN in row 14515 : 3
 Total NaN in row 14516 : 1
 Total NaN in row 14517 : 2
 Total NaN in row 14518 : 3
 Total NaN in row 14519 : 3
 Total NaN in row 14520 : 2
 Total NaN in row 14521 : 2
 Total NaN in row 14522 : 0
 Total NaN in row 14523 : 2
 Total NaN in row 14524 : 10
 Total NaN in row 14525 : 3
 Total NaN in row 14526 : 0
 Total NaN in row 14527 : 0
 Total NaN in row 14528 : 9
 Total NaN in row 14529 : 9
 Total NaN in row 14530 : 9
 Total NaN in row 14531 : 1
 Total NaN in row 14532 : 0
 Total NaN in row 14533 : 1
 Total NaN in row 14534 : 1
 Total NaN in row 14535 : 0
 Total NaN in row 14536 : 0
 Total NaN in row 14537 : 9
 Total NaN in row 14538 : 2
 Total NaN in row 14539 : 0
 Total NaN in row 14540 : 9
 Total NaN in row 14541 : 9
 Total NaN in row 14542 : 0
 Total NaN in row 14543 : 1
 Total NaN in row 14544 : 0
 Total NaN in row 14545 : 2
 Total NaN in row 14546 : 2
 Total NaN in row 14547 : 0
 Total NaN in row 14548 : 2
 Total NaN in row 14549 : 2
 Total NaN in row 14550 : 9
 Total NaN in row 14551 : 0
 Total NaN in row 14552 : 2
 Total NaN in row 14553 : 0
 Total NaN in row 14554 : 2
 Total NaN in row 14555 : 0
 Total NaN in row 14556 : 3
 Total NaN in row 14557 : 2
 Total NaN in row 14558 : 2
 Total NaN in row 14559 : 0
 Total NaN in row 14560 : 2
 Total NaN in row 14561 : 2
 Total NaN in row 14562 : 2
 Total NaN in row 14563 : 2
 Total NaN in row 14564 : 9
 Total NaN in row 14565 : 9
 Total NaN in row 14566 : 0
 Total NaN in row 14567 : 2
 Total NaN in row 14568 : 0
 Total NaN in row 14569 : 9
 Total NaN in row 14570 : 3
 Total NaN in row 14571 : 2
 Total NaN in row 14572 : 10
 Total NaN in row 14573 : 2
 Total NaN in row 14574 : 1
 Total NaN in row 14575 : 10
 Total NaN in row 14576 : 0
 Total NaN in row 14577 : 0
 Total NaN in row 14578 : 9
 Total NaN in row 14579 : 3
 Total NaN in row 14580 : 9
 Total NaN in row 14581 : 0
 Total NaN in row 14582 : 1
 Total NaN in row 14583 : 2
 Total NaN in row 14584 : 1
 Total NaN in row 14585 : 0
 Total NaN in row 14586 : 2
 Total NaN in row 14587 : 0
 Total NaN in row 14588 : 9
 Total NaN in row 14589 : 0
 Total NaN in row 14590 : 2
 Total NaN in row 14591 : 2
 Total NaN in row 14592 : 9
 Total NaN in row 14593 : 0
 Total NaN in row 14594 : 2
 Total NaN in row 14595 : 1
 Total NaN in row 14596 : 1
 Total NaN in row 14597 : 2
 Total NaN in row 14598 : 2
 Total NaN in row 14599 : 2
 Total NaN in row 14600 : 2
 Total NaN in row 14601 : 2
 Total NaN in row 14602 : 9
 Total NaN in row 14603 : 1
 Total NaN in row 14604 : 0
 Total NaN in row 14605 : 2
 Total NaN in row 14606 : 2
 Total NaN in row 14607 : 2
 Total NaN in row 14608 : 0
 Total NaN in row 14609 : 9
 Total NaN in row 14610 : 0
 Total NaN in row 14611 : 10
 Total NaN in row 14612 : 2
 Total NaN in row 14613 : 1
 Total NaN in row 14614 : 9
 Total NaN in row 14615 : 0
 Total NaN in row 14616 : 9
 Total NaN in row 14617 : 2
 Total NaN in row 14618 : 9
 Total NaN in row 14619 : 1
 Total NaN in row 14620 : 2
 Total NaN in row 14621 : 1
 Total NaN in row 14622 : 2
 Total NaN in row 14623 : 9
 Total NaN in row 14624 : 2
 Total NaN in row 14625 : 2
 Total NaN in row 14626 : 2
 Total NaN in row 14627 : 2
 Total NaN in row 14628 : 9
 Total NaN in row 14629 : 0
 Total NaN in row 14630 : 1
 Total NaN in row 14631 : 0
 Total NaN in row 14632 : 9
 Total NaN in row 14633 : 2
 Total NaN in row 14634 : 2
 Total NaN in row 14635 : 1
 Total NaN in row 14636 : 1
 Total NaN in row 14637 : 3
 Total NaN in row 14638 : 0
 Total NaN in row 14639 : 0
 Total NaN in row 14640 : 0
 Total NaN in row 14641 : 9
 Total NaN in row 14642 : 1
 Total NaN in row 14643 : 2
 Total NaN in row 14644 : 2
 Total NaN in row 14645 : 21
 Total NaN in row 14646 : 0
 Total NaN in row 14647 : 3
 Total NaN in row 14648 : 2
 Total NaN in row 14649 : 0
 Total NaN in row 14650 : 1
 Total NaN in row 14651 : 0
 Total NaN in row 14652 : 2
 Total NaN in row 14653 : 1
 Total NaN in row 14654 : 9
 Total NaN in row 14655 : 2
 Total NaN in row 14656 : 2
 Total NaN in row 14657 : 0
 Total NaN in row 14658 : 2
 Total NaN in row 14659 : 2
 Total NaN in row 14660 : 9
 Total NaN in row 14661 : 3
 Total NaN in row 14662 : 7
 Total NaN in row 14663 : 9
 Total NaN in row 14664 : 9
 Total NaN in row 14665 : 0
 Total NaN in row 14666 : 2
 Total NaN in row 14667 : 10
 Total NaN in row 14668 : 2
 Total NaN in row 14669 : 9
 Total NaN in row 14670 : 2
 Total NaN in row 14671 : 2
 Total NaN in row 14672 : 7
 Total NaN in row 14673 : 0
 Total NaN in row 14674 : 2
 Total NaN in row 14675 : 9
 Total NaN in row 14676 : 0
 Total NaN in row 14677 : 3
 Total NaN in row 14678 : 9
 Total NaN in row 14679 : 9
 Total NaN in row 14680 : 2
 Total NaN in row 14681 : 9
 Total NaN in row 14682 : 1
 Total NaN in row 14683 : 9
 Total NaN in row 14684 : 1
 Total NaN in row 14685 : 10
 Total NaN in row 14686 : 1
 Total NaN in row 14687 : 2
 Total NaN in row 14688 : 9
 Total NaN in row 14689 : 1
 Total NaN in row 14690 : 0
 Total NaN in row 14691 : 1
 Total NaN in row 14692 : 9
 Total NaN in row 14693 : 0
 Total NaN in row 14694 : 9
 Total NaN in row 14695 : 9
 Total NaN in row 14696 : 9
 Total NaN in row 14697 : 0
 Total NaN in row 14698 : 9
 Total NaN in row 14699 : 9
 Total NaN in row 14700 : 2
 Total NaN in row 14701 : 0
 Total NaN in row 14702 : 2
 Total NaN in row 14703 : 2
 Total NaN in row 14704 : 9
 Total NaN in row 14705 : 0
 Total NaN in row 14706 : 10
 Total NaN in row 14707 : 10
 Total NaN in row 14708 : 2
 Total NaN in row 14709 : 1
 Total NaN in row 14710 : 10
 Total NaN in row 14711 : 2
 Total NaN in row 14712 : 1
 Total NaN in row 14713 : 1
 Total NaN in row 14714 : 0
 Total NaN in row 14715 : 3
 Total NaN in row 14716 : 3
 Total NaN in row 14717 : 0
 Total NaN in row 14718 : 9
 Total NaN in row 14719 : 0
 Total NaN in row 14720 : 9
 Total NaN in row 14721 : 3
 Total NaN in row 14722 : 9
 Total NaN in row 14723 : 0
 Total NaN in row 14724 : 0
 Total NaN in row 14725 : 0
 Total NaN in row 14726 : 0
 Total NaN in row 14727 : 2
 Total NaN in row 14728 : 9
 Total NaN in row 14729 : 1
 Total NaN in row 14730 : 9
 Total NaN in row 14731 : 9
 Total NaN in row 14732 : 0
 Total NaN in row 14733 : 9
 Total NaN in row 14734 : 0
 Total NaN in row 14735 : 1
 Total NaN in row 14736 : 2
 Total NaN in row 14737 : 2
 Total NaN in row 14738 : 2
 Total NaN in row 14739 : 9
 Total NaN in row 14740 : 0
 Total NaN in row 14741 : 1
 Total NaN in row 14742 : 9
 Total NaN in row 14743 : 10
 Total NaN in row 14744 : 9
 Total NaN in row 14745 : 2
 Total NaN in row 14746 : 0
 Total NaN in row 14747 : 0
 Total NaN in row 14748 : 9
 Total NaN in row 14749 : 2
 Total NaN in row 14750 : 3
 Total NaN in row 14751 : 9
 Total NaN in row 14752 : 3
 Total NaN in row 14753 : 3
 Total NaN in row 14754 : 0
 Total NaN in row 14755 : 2
 Total NaN in row 14756 : 3
 Total NaN in row 14757 : 2
 Total NaN in row 14758 : 2
 Total NaN in row 14759 : 1
 Total NaN in row 14760 : 10
 Total NaN in row 14761 : 0
 Total NaN in row 14762 : 2
 Total NaN in row 14763 : 2
 Total NaN in row 14764 : 2
 Total NaN in row 14765 : 1
 Total NaN in row 14766 : 2
 Total NaN in row 14767 : 1
 Total NaN in row 14768 : 10
 Total NaN in row 14769 : 2
 Total NaN in row 14770 : 0
 Total NaN in row 14771 : 10
 Total NaN in row 14772 : 2
 Total NaN in row 14773 : 2
 Total NaN in row 14774 : 1
 Total NaN in row 14775 : 1
 Total NaN in row 14776 : 0
 Total NaN in row 14777 : 2
 Total NaN in row 14778 : 2
 Total NaN in row 14779 : 9
 Total NaN in row 14780 : 9
 Total NaN in row 14781 : 0
 Total NaN in row 14782 : 2
 Total NaN in row 14783 : 1
 Total NaN in row 14784 : 2
 Total NaN in row 14785 : 1
 Total NaN in row 14786 : 2
 Total NaN in row 14787 : 1
 Total NaN in row 14788 : 0
 Total NaN in row 14789 : 9
 Total NaN in row 14790 : 2
 Total NaN in row 14791 : 1
 Total NaN in row 14792 : 1
 Total NaN in row 14793 : 0
 Total NaN in row 14794 : 2
 Total NaN in row 14795 : 2
 Total NaN in row 14796 : 9
 Total NaN in row 14797 : 2
 Total NaN in row 14798 : 2
 Total NaN in row 14799 : 2
 Total NaN in row 14800 : 2
 Total NaN in row 14801 : 0
 Total NaN in row 14802 : 2
 Total NaN in row 14803 : 2
 Total NaN in row 14804 : 0
 Total NaN in row 14805 : 3
 Total NaN in row 14806 : 0
 Total NaN in row 14807 : 1
 Total NaN in row 14808 : 4
 Total NaN in row 14809 : 9
 Total NaN in row 14810 : 2
 Total NaN in row 14811 : 2
 Total NaN in row 14812 : 0
 Total NaN in row 14813 : 9
 Total NaN in row 14814 : 10
 Total NaN in row 14815 : 0
 Total NaN in row 14816 : 0
 Total NaN in row 14817 : 2
 Total NaN in row 14818 : 2
 Total NaN in row 14819 : 0
 Total NaN in row 14820 : 9
 Total NaN in row 14821 : 9
 Total NaN in row 14822 : 9
 Total NaN in row 14823 : 2
 Total NaN in row 14824 : 1
 Total NaN in row 14825 : 2
 Total NaN in row 14826 : 2
 Total NaN in row 14827 : 1
 Total NaN in row 14828 : 9
 Total NaN in row 14829 : 3
 Total NaN in row 14830 : 3
 Total NaN in row 14831 : 2
 Total NaN in row 14832 : 1
 Total NaN in row 14833 : 9
 Total NaN in row 14834 : 3
 Total NaN in row 14835 : 9
 Total NaN in row 14836 : 0
 Total NaN in row 14837 : 0
 Total NaN in row 14838 : 0
 Total NaN in row 14839 : 9
 Total NaN in row 14840 : 1
 Total NaN in row 14841 : 0
 Total NaN in row 14842 : 9
 Total NaN in row 14843 : 2
 Total NaN in row 14844 : 9
 Total NaN in row 14845 : 1
 Total NaN in row 14846 : 2
 Total NaN in row 14847 : 0
 Total NaN in row 14848 : 2
 Total NaN in row 14849 : 9
 Total NaN in row 14850 : 9
 Total NaN in row 14851 : 9
 Total NaN in row 14852 : 3
 Total NaN in row 14853 : 1
 Total NaN in row 14854 : 1
 Total NaN in row 14855 : 9
 Total NaN in row 14856 : 3
 Total NaN in row 14857 : 3
 Total NaN in row 14858 : 1
 Total NaN in row 14859 : 2
 Total NaN in row 14860 : 0
 Total NaN in row 14861 : 0
 Total NaN in row 14862 : 1
 Total NaN in row 14863 : 9
 Total NaN in row 14864 : 3
 Total NaN in row 14865 : 1
 Total NaN in row 14866 : 1
 Total NaN in row 14867 : 2
 Total NaN in row 14868 : 0
 Total NaN in row 14869 : 9
 Total NaN in row 14870 : 1
 Total NaN in row 14871 : 9
 Total NaN in row 14872 : 3
 Total NaN in row 14873 : 0
 Total NaN in row 14874 : 0
 Total NaN in row 14875 : 0
 Total NaN in row 14876 : 1
 Total NaN in row 14877 : 2
 Total NaN in row 14878 : 2
 Total NaN in row 14879 : 3
 Total NaN in row 14880 : 10
 Total NaN in row 14881 : 0
 Total NaN in row 14882 : 2
 Total NaN in row 14883 : 3
 Total NaN in row 14884 : 1
 Total NaN in row 14885 : 0
 Total NaN in row 14886 : 10
 Total NaN in row 14887 : 1
 Total NaN in row 14888 : 9
 Total NaN in row 14889 : 0

 Total NaN in row 14890 : 2
 Total NaN in row 14891 : 2
 Total NaN in row 14892 : 3
 Total NaN in row 14893 : 1
 Total NaN in row 14894 : 3
 Total NaN in row 14895 : 0
 Total NaN in row 14896 : 3
 Total NaN in row 14897 : 10
 Total NaN in row 14898 : 10
 Total NaN in row 14899 : 10
 Total NaN in row 14900 : 9
 Total NaN in row 14901 : 9
 Total NaN in row 14902 : 2
 Total NaN in row 14903 : 0
 Total NaN in row 14904 : 0
 Total NaN in row 14905 : 1
 Total NaN in row 14906 : 0
 Total NaN in row 14907 : 4
 Total NaN in row 14908 : 2
 Total NaN in row 14909 : 0
 Total NaN in row 14910 : 0
 Total NaN in row 14911 : 0
 Total NaN in row 14912 : 2
 Total NaN in row 14913 : 10
 Total NaN in row 14914 : 1
 Total NaN in row 14915 : 9
 Total NaN in row 14916 : 9
 Total NaN in row 14917 : 0
 Total NaN in row 14918 : 2
 Total NaN in row 14919 : 1
 Total NaN in row 14920 : 1
 Total NaN in row 14921 : 3
 Total NaN in row 14922 : 2
 Total NaN in row 14923 : 2
 Total NaN in row 14924 : 2
 Total NaN in row 14925 : 9
 Total NaN in row 14926 : 2
 Total NaN in row 14927 : 9
 Total NaN in row 14928 : 2
 Total NaN in row 14929 : 10
 Total NaN in row 14930 : 3
 Total NaN in row 14931 : 1
 Total NaN in row 14932 : 1
 Total NaN in row 14933 : 1
 Total NaN in row 14934 : 0
 Total NaN in row 14935 : 0
 Total NaN in row 14936 : 9
 Total NaN in row 14937 : 9
 Total NaN in row 14938 : 1
 Total NaN in row 14939 : 2
 Total NaN in row 14940 : 2
 Total NaN in row 14941 : 0
 Total NaN in row 14942 : 2
 Total NaN in row 14943 : 0
 Total NaN in row 14944 : 0
 Total NaN in row 14945 : 9
 Total NaN in row 14946 : 0
 Total NaN in row 14947 : 2
 Total NaN in row 14948 : 9
 Total NaN in row 14949 : 9
 Total NaN in row 14950 : 9
 Total NaN in row 14951 : 1
 Total NaN in row 14952 : 2
 Total NaN in row 14953 : 0
 Total NaN in row 14954 : 2
 Total NaN in row 14955 : 0
 Total NaN in row 14956 : 2
 Total NaN in row 14957 : 0
 Total NaN in row 14958 : 0
 Total NaN in row 14959 : 2
 Total NaN in row 14960 : 1
 Total NaN in row 14961 : 0
 Total NaN in row 14962 : 3
 Total NaN in row 14963 : 0
 Total NaN in row 14964 : 21
 Total NaN in row 14965 : 10
 Total NaN in row 14966 : 2
 Total NaN in row 14967 : 0
 Total NaN in row 14968 : 3
 Total NaN in row 14969 : 1
 Total NaN in row 14970 : 0
 Total NaN in row 14971 : 9
 Total NaN in row 14972 : 0
 Total NaN in row 14973 : 9
 Total NaN in row 14974 : 9
 Total NaN in row 14975 : 0
 Total NaN in row 14976 : 0
 Total NaN in row 14977 : 0
 Total NaN in row 14978 : 9
 Total NaN in row 14979 : 10
 Total NaN in row 14980 : 3
 Total NaN in row 14981 : 2
 Total NaN in row 14982 : 3
 Total NaN in row 14983 : 2
 Total NaN in row 14984 : 2
 Total NaN in row 14985 : 1
 Total NaN in row 14986 : 0
 Total NaN in row 14987 : 2
 Total NaN in row 14988 : 0
 Total NaN in row 14989 : 2
 Total NaN in row 14990 : 2
 Total NaN in row 14991 : 0
 Total NaN in row 14992 : 1
 Total NaN in row 14993 : 1
 Total NaN in row 14994 : 2
 Total NaN in row 14995 : 1
 Total NaN in row 14996 : 10
 Total NaN in row 14997 : 0
 Total NaN in row 14998 : 1
 Total NaN in row 14999 : 10
 Total NaN in row 15000 : 9
 Total NaN in row 15001 : 9
 Total NaN in row 15002 : 10
 Total NaN in row 15003 : 3
 Total NaN in row 15004 : 0
 Total NaN in row 15005 : 1
 Total NaN in row 15006 : 9
 Total NaN in row 15007 : 2
 Total NaN in row 15008 : 1
 Total NaN in row 15009 : 3
 Total NaN in row 15010 : 9
 Total NaN in row 15011 : 1
 Total NaN in row 15012 : 3
 Total NaN in row 15013 : 9
 Total NaN in row 15014 : 0
 Total NaN in row 15015 : 0
 Total NaN in row 15016 : 0
 Total NaN in row 15017 : 1
 Total NaN in row 15018 : 9
 Total NaN in row 15019 : 0
 Total NaN in row 15020 : 1
 Total NaN in row 15021 : 0
 Total NaN in row 15022 : 2
 Total NaN in row 15023 : 0
 Total NaN in row 15024 : 0
 Total NaN in row 15025 : 2
 Total NaN in row 15026 : 9
 Total NaN in row 15027 : 2
 Total NaN in row 15028 : 0
 Total NaN in row 15029 : 10
 Total NaN in row 15030 : 9
 Total NaN in row 15031 : 1
 Total NaN in row 15032 : 0
 Total NaN in row 15033 : 0
 Total NaN in row 15034 : 1
 Total NaN in row 15035 : 10
 Total NaN in row 15036 : 10
 Total NaN in row 15037 : 10
 Total NaN in row 15038 : 1
 Total NaN in row 15039 : 0
 Total NaN in row 15040 : 2
 Total NaN in row 15041 : 2
 Total NaN in row 15042 : 1
 Total NaN in row 15043 : 9
 Total NaN in row 15044 : 0
 Total NaN in row 15045 : 0
 Total NaN in row 15046 : 0
 Total NaN in row 15047 : 1
 Total NaN in row 15048 : 0
 Total NaN in row 15049 : 9
 Total NaN in row 15050 : 0
 Total NaN in row 15051 : 9
 Total NaN in row 15052 : 0
 Total NaN in row 15053 : 1
 Total NaN in row 15054 : 2
 Total NaN in row 15055 : 9
 Total NaN in row 15056 : 1
 Total NaN in row 15057 : 2
 Total NaN in row 15058 : 0
 Total NaN in row 15059 : 2
 Total NaN in row 15060 : 2
 Total NaN in row 15061 : 1
 Total NaN in row 15062 : 0
 Total NaN in row 15063 : 2
 Total NaN in row 15064 : 1
 Total NaN in row 15065 : 0
 Total NaN in row 15066 : 4
 Total NaN in row 15067 : 9
 Total NaN in row 15068 : 2
 Total NaN in row 15069 : 0
 Total NaN in row 15070 : 0
 Total NaN in row 15071 : 0
 Total NaN in row 15072 : 2
 Total NaN in row 15073 : 2
 Total NaN in row 15074 : 2
 Total NaN in row 15075 : 1
 Total NaN in row 15076 : 1
 Total NaN in row 15077 : 2
 Total NaN in row 15078 : 1
 Total NaN in row 15079 : 1
 Total NaN in row 15080 : 2
 Total NaN in row 15081 : 1
 Total NaN in row 15082 : 2
 Total NaN in row 15083 : 2
 Total NaN in row 15084 : 1
 Total NaN in row 15085 : 1
 Total NaN in row 15086 : 9
 Total NaN in row 15087 : 9
 Total NaN in row 15088 : 0
 Total NaN in row 15089 : 0
 Total NaN in row 15090 : 3
 Total NaN in row 15091 : 1
 Total NaN in row 15092 : 0
 Total NaN in row 15093 : 2
 Total NaN in row 15094 : 10
 Total NaN in row 15095 : 21
 Total NaN in row 15096 : 10
 Total NaN in row 15097 : 0
 Total NaN in row 15098 : 0
 Total NaN in row 15099 : 1
 Total NaN in row 15100 : 3
 Total NaN in row 15101 : 2
 Total NaN in row 15102 : 0
 Total NaN in row 15103 : 10
 Total NaN in row 15104 : 3
 Total NaN in row 15105 : 0
 Total NaN in row 15106 : 2
 Total NaN in row 15107 : 0
 Total NaN in row 15108 : 0
 Total NaN in row 15109 : 9
 Total NaN in row 15110 : 0
 Total NaN in row 15111 : 2
 Total NaN in row 15112 : 0
 Total NaN in row 15113 : 0
 Total NaN in row 15114 : 1
 Total NaN in row 15115 : 1
 Total NaN in row 15116 : 3
 Total NaN in row 15117 : 1
 Total NaN in row 15118 : 0
 Total NaN in row 15119 : 0
 Total NaN in row 15120 : 0
 Total NaN in row 15121 : 0
 Total NaN in row 15122 : 1
 Total NaN in row 15123 : 0
 Total NaN in row 15124 : 10
 Total NaN in row 15125 : 2
 Total NaN in row 15126 : 1
 Total NaN in row 15127 : 0
 Total NaN in row 15128 : 9
 Total NaN in row 15129 : 0
 Total NaN in row 15130 : 0
 Total NaN in row 15131 : 9
 Total NaN in row 15132 : 0
 Total NaN in row 15133 : 0
 Total NaN in row 15134 : 2
 Total NaN in row 15135 : 1
 Total NaN in row 15136 : 1
 Total NaN in row 15137 : 0
 Total NaN in row 15138 : 9
 Total NaN in row 15139 : 10
 Total NaN in row 15140 : 2
 Total NaN in row 15141 : 0
 Total NaN in row 15142 : 10
 Total NaN in row 15143 : 1
 Total NaN in row 15144 : 9
 Total NaN in row 15145 : 2
 Total NaN in row 15146 : 2
 Total NaN in row 15147 : 9
 Total NaN in row 15148 : 2
 Total NaN in row 15149 : 0
 Total NaN in row 15150 : 2
 Total NaN in row 15151 : 9
 Total NaN in row 15152 : 3
 Total NaN in row 15153 : 9
 Total NaN in row 15154 : 9
 Total NaN in row 15155 : 3
 Total NaN in row 15156 : 2
 Total NaN in row 15157 : 0
 Total NaN in row 15158 : 0
 Total NaN in row 15159 : 0
 Total NaN in row 15160 : 2
 Total NaN in row 15161 : 2
 Total NaN in row 15162 : 0
 Total NaN in row 15163 : 2
 Total NaN in row 15164 : 0
 Total NaN in row 15165 : 3
 Total NaN in row 15166 : 1
 Total NaN in row 15167 : 0
 Total NaN in row 15168 : 2
 Total NaN in row 15169 : 0
 Total NaN in row 15170 : 3
 Total NaN in row 15171 : 1
 Total NaN in row 15172 : 10
 Total NaN in row 15173 : 9
 Total NaN in row 15174 : 0
 Total NaN in row 15175 : 1
 Total NaN in row 15176 : 0
 Total NaN in row 15177 : 0
 Total NaN in row 15178 : 1
 Total NaN in row 15179 : 0
 Total NaN in row 15180 : 2
 Total NaN in row 15181 : 0
 Total NaN in row 15182 : 9
 Total NaN in row 15183 : 9
 Total NaN in row 15184 : 9
 Total NaN in row 15185 : 9
 Total NaN in row 15186 : 3
 Total NaN in row 15187 : 2
 Total NaN in row 15188 : 1
 Total NaN in row 15189 : 2
 Total NaN in row 15190 : 0
 Total NaN in row 15191 : 10
 Total NaN in row 15192 : 3
 Total NaN in row 15193 : 1
 Total NaN in row 15194 : 9
 Total NaN in row 15195 : 3
 Total NaN in row 15196 : 2
 Total NaN in row 15197 : 10
 Total NaN in row 15198 : 0
 Total NaN in row 15199 : 1
 Total NaN in row 15200 : 0
 Total NaN in row 15201 : 9
 Total NaN in row 15202 : 0
 Total NaN in row 15203 : 9
 Total NaN in row 15204 : 2
 Total NaN in row 15205 : 10
 Total NaN in row 15206 : 9
 Total NaN in row 15207 : 1
 Total NaN in row 15208 : 1

 Total NaN in row 15209 : 3
 Total NaN in row 15210 : 9
 Total NaN in row 15211 : 0
 Total NaN in row 15212 : 0
 Total NaN in row 15213 : 2
 Total NaN in row 15214 : 0
 Total NaN in row 15215 : 21
 Total NaN in row 15216 : 0
 Total NaN in row 15217 : 9
 Total NaN in row 15218 : 1
 Total NaN in row 15219 : 9
 Total NaN in row 15220 : 0
 Total NaN in row 15221 : 1
 Total NaN in row 15222 : 0
 Total NaN in row 15223 : 2
 Total NaN in row 15224 : 2
 Total NaN in row 15225 : 0
 Total NaN in row 15226 : 0
 Total NaN in row 15227 : 9
 Total NaN in row 15228 : 0
 Total NaN in row 15229 : 9
 Total NaN in row 15230 : 9
 Total NaN in row 15231 : 9
 Total NaN in row 15232 : 1
 Total NaN in row 15233 : 3
 Total NaN in row 15234 : 9
 Total NaN in row 15235 : 9
 Total NaN in row 15236 : 1
 Total NaN in row 15237 : 0
 Total NaN in row 15238 : 2
 Total NaN in row 15239 : 2
 Total NaN in row 15240 : 9
 Total NaN in row 15241 : 0
 Total NaN in row 15242 : 1
 Total NaN in row 15243 : 1
 Total NaN in row 15244 : 0
 Total NaN in row 15245 : 0
 Total NaN in row 15246 : 1
 Total NaN in row 15247 : 0
 Total NaN in row 15248 : 2
 Total NaN in row 15249 : 1
 Total NaN in row 15250 : 1
 Total NaN in row 15251 : 9
 Total NaN in row 15252 : 9
 Total NaN in row 15253 : 2
 Total NaN in row 15254 : 3
 Total NaN in row 15255 : 0
 Total NaN in row 15256 : 2
 Total NaN in row 15257 : 2
 Total NaN in row 15258 : 1
 Total NaN in row 15259 : 9
 Total NaN in row 15260 : 1
 Total NaN in row 15261 : 9
 Total NaN in row 15262 : 2
 Total NaN in row 15263 : 2
 Total NaN in row 15264 : 2
 Total NaN in row 15265 : 3
 Total NaN in row 15266 : 9
 Total NaN in row 15267 : 2
 Total NaN in row 15268 : 3
 Total NaN in row 15269 : 3
 Total NaN in row 15270 : 2
 Total NaN in row 15271 : 0
 Total NaN in row 15272 : 1
 Total NaN in row 15273 : 0
 Total NaN in row 15274 : 9
 Total NaN in row 15275 : 1
 Total NaN in row 15276 : 9
 Total NaN in row 15277 : 2
 Total NaN in row 15278 : 9
 Total NaN in row 15279 : 2
 Total NaN in row 15280 : 0
 Total NaN in row 15281 : 9
 Total NaN in row 15282 : 2
 Total NaN in row 15283 : 2
 Total NaN in row 15284 : 0
 Total NaN in row 15285 : 0
 Total NaN in row 15286 : 0
 Total NaN in row 15287 : 2
 Total NaN in row 15288 : 0
 Total NaN in row 15289 : 0
 Total NaN in row 15290 : 9
 Total NaN in row 15291 : 0
 Total NaN in row 15292 : 9
 Total NaN in row 15293 : 0
 Total NaN in row 15294 : 3
 Total NaN in row 15295 : 2
 Total NaN in row 15296 : 2
 Total NaN in row 15297 : 1
 Total NaN in row 15298 : 10
 Total NaN in row 15299 : 9
 Total NaN in row 15300 : 0
 Total NaN in row 15301 : 2
 Total NaN in row 15302 : 1
 Total NaN in row 15303 : 2
 Total NaN in row 15304 : 0
 Total NaN in row 15305 : 7
 Total NaN in row 15306 : 9
 Total NaN in row 15307 : 0
 Total NaN in row 15308 : 1
 Total NaN in row 15309 : 3
 Total NaN in row 15310 : 2
 Total NaN in row 15311 : 3
 Total NaN in row 15312 : 9
 Total NaN in row 15313 : 0
 Total NaN in row 15314 : 9
 Total NaN in row 15315 : 2
 Total NaN in row 15316 : 9
 Total NaN in row 15317 : 0
 Total NaN in row 15318 : 0
 Total NaN in row 15319 : 1
 Total NaN in row 15320 : 0
 Total NaN in row 15321 : 0
 Total NaN in row 15322 : 1
 Total NaN in row 15323 : 1
 Total NaN in row 15324 : 0
 Total NaN in row 15325 : 10
 Total NaN in row 15326 : 2
 Total NaN in row 15327 : 0
 Total NaN in row 15328 : 0
 Total NaN in row 15329 : 0
 Total NaN in row 15330 : 3
 Total NaN in row 15331 : 2
 Total NaN in row 15332 : 10
 Total NaN in row 15333 : 1
 Total NaN in row 15334 : 2
 Total NaN in row 15335 : 9
 Total NaN in row 15336 : 10
 Total NaN in row 15337 : 9
 Total NaN in row 15338 : 1
 Total NaN in row 15339 : 2
 Total NaN in row 15340 : 0
 Total NaN in row 15341 : 9
 Total NaN in row 15342 : 0
 Total NaN in row 15343 : 0
 Total NaN in row 15344 : 9
 Total NaN in row 15345 : 2
 Total NaN in row 15346 : 2
 Total NaN in row 15347 : 1
 Total NaN in row 15348 : 0
 Total NaN in row 15349 : 10
 Total NaN in row 15350 : 2
 Total NaN in row 15351 : 0
 Total NaN in row 15352 : 0
 Total NaN in row 15353 : 9
 Total NaN in row 15354 : 9
 Total NaN in row 15355 : 10
 Total NaN in row 15356 : 1
 Total NaN in row 15357 : 1
 Total NaN in row 15358 : 2
 Total NaN in row 15359 : 1
 Total NaN in row 15360 : 2
 Total NaN in row 15361 : 0
 Total NaN in row 15362 : 0
 Total NaN in row 15363 : 0
 Total NaN in row 15364 : 9
 Total NaN in row 15365 : 0
 Total NaN in row 15366 : 1
 Total NaN in row 15367 : 0
 Total NaN in row 15368 : 0
 Total NaN in row 15369 : 0
 Total NaN in row 15370 : 4
 Total NaN in row 15371 : 0
 Total NaN in row 15372 : 0
 Total NaN in row 15373 : 2
 Total NaN in row 15374 : 0
 Total NaN in row 15375 : 0
 Total NaN in row 15376 : 9
 Total NaN in row 15377 : 0
 Total NaN in row 15378 : 0
 Total NaN in row 15379 : 9
 Total NaN in row 15380 : 0
 Total NaN in row 15381 : 0
 Total NaN in row 15382 : 0
 Total NaN in row 15383 : 3
 Total NaN in row 15384 : 1
 Total NaN in row 15385 : 1
 Total NaN in row 15386 : 0
 Total NaN in row 15387 : 9
 Total NaN in row 15388 : 0
 Total NaN in row 15389 : 2
 Total NaN in row 15390 : 1
 Total NaN in row 15391 : 1
 Total NaN in row 15392 : 1
 Total NaN in row 15393 : 10
 Total NaN in row 15394 : 9
 Total NaN in row 15395 : 10
 Total NaN in row 15396 : 1
 Total NaN in row 15397 : 10
 Total NaN in row 15398 : 9
 Total NaN in row 15399 : 9
 Total NaN in row 15400 : 2
 Total NaN in row 15401 : 2
 Total NaN in row 15402 : 9
 Total NaN in row 15403 : 9
 Total NaN in row 15404 : 2
 Total NaN in row 15405 : 0
 Total NaN in row 15406 : 2
 Total NaN in row 15407 : 0
 Total NaN in row 15408 : 9
 Total NaN in row 15409 : 2
 Total NaN in row 15410 : 2
 Total NaN in row 15411 : 2
 Total NaN in row 15412 : 9
 Total NaN in row 15413 : 10
 Total NaN in row 15414 : 9
 Total NaN in row 15415 : 3
 Total NaN in row 15416 : 0
 Total NaN in row 15417 : 0
 Total NaN in row 15418 : 1
 Total NaN in row 15419 : 2
 Total NaN in row 15420 : 1
 Total NaN in row 15421 : 2
 Total NaN in row 15422 : 9
 Total NaN in row 15423 : 0
 Total NaN in row 15424 : 10
 Total NaN in row 15425 : 9
 Total NaN in row 15426 : 0
 Total NaN in row 15427 : 2
 Total NaN in row 15428 : 2
 Total NaN in row 15429 : 0
 Total NaN in row 15430 : 0
 Total NaN in row 15431 : 2
 Total NaN in row 15432 : 2
 Total NaN in row 15433 : 0
 Total NaN in row 15434 : 1
 Total NaN in row 15435 : 2
 Total NaN in row 15436 : 0
 Total NaN in row 15437 : 9
 Total NaN in row 15438 : 2
 Total NaN in row 15439 : 1
 Total NaN in row 15440 : 2
 Total NaN in row 15441 : 0
 Total NaN in row 15442 : 1
 Total NaN in row 15443 : 2
 Total NaN in row 15444 : 2
 Total NaN in row 15445 : 0
 Total NaN in row 15446 : 0
 Total NaN in row 15447 : 2
 Total NaN in row 15448 : 1
 Total NaN in row 15449 : 2
 Total NaN in row 15450 : 9
 Total NaN in row 15451 : 2
 Total NaN in row 15452 : 3
 Total NaN in row 15453 : 0
 Total NaN in row 15454 : 9
 Total NaN in row 15455 : 9
 Total NaN in row 15456 : 2
 Total NaN in row 15457 : 2
 Total NaN in row 15458 : 0
 Total NaN in row 15459 : 0
 Total NaN in row 15460 : 2
 Total NaN in row 15461 : 2
 Total NaN in row 15462 : 0
 Total NaN in row 15463 : 9
 Total NaN in row 15464 : 0
 Total NaN in row 15465 : 2
 Total NaN in row 15466 : 0
 Total NaN in row 15467 : 2
 Total NaN in row 15468 : 0
 Total NaN in row 15469 : 0
 Total NaN in row 15470 : 2
 Total NaN in row 15471 : 2
 Total NaN in row 15472 : 2
 Total NaN in row 15473 : 2
 Total NaN in row 15474 : 0
 Total NaN in row 15475 : 2
 Total NaN in row 15476 : 2
 Total NaN in row 15477 : 9
 Total NaN in row 15478 : 9
 Total NaN in row 15479 : 9
 Total NaN in row 15480 : 9
 Total NaN in row 15481 : 0
 Total NaN in row 15482 : 0
 Total NaN in row 15483 : 2
 Total NaN in row 15484 : 9
 Total NaN in row 15485 : 0
 Total NaN in row 15486 : 0
 Total NaN in row 15487 : 1
 Total NaN in row 15488 : 0
 Total NaN in row 15489 : 1
 Total NaN in row 15490 : 0
 Total NaN in row 15491 : 9
 Total NaN in row 15492 : 2
 Total NaN in row 15493 : 2
 Total NaN in row 15494 : 2
 Total NaN in row 15495 : 0
 Total NaN in row 15496 : 0
 Total NaN in row 15497 : 2
 Total NaN in row 15498 : 3
 Total NaN in row 15499 : 9
 Total NaN in row 15500 : 9

 Total NaN in row 15501 : 0
 Total NaN in row 15502 : 9
 Total NaN in row 15503 : 3
 Total NaN in row 15504 : 2
 Total NaN in row 15505 : 0
 Total NaN in row 15506 : 2
 Total NaN in row 15507 : 9
 Total NaN in row 15508 : 9
 Total NaN in row 15509 : 0
 Total NaN in row 15510 : 9
 Total NaN in row 15511 : 1
 Total NaN in row 15512 : 2
 Total NaN in row 15513 : 3
 Total NaN in row 15514 : 2
 Total NaN in row 15515 : 10
 Total NaN in row 15516 : 9
 Total NaN in row 15517 : 10
 Total NaN in row 15518 : 0
 Total NaN in row 15519 : 2
 Total NaN in row 15520 : 9
 Total NaN in row 15521 : 0
 Total NaN in row 15522 : 9
 Total NaN in row 15523 : 1
 Total NaN in row 15524 : 2
 Total NaN in row 15525 : 0
 Total NaN in row 15526 : 0
 Total NaN in row 15527 : 0
 Total NaN in row 15528 : 9
 Total NaN in row 15529 : 0
 Total NaN in row 15530 : 2
 Total NaN in row 15531 : 9
 Total NaN in row 15532 : 0
 Total NaN in row 15533 : 2
 Total NaN in row 15534 : 2
 Total NaN in row 15535 : 9
 Total NaN in row 15536 : 0
 Total NaN in row 15537 : 2
 Total NaN in row 15538 : 2
 Total NaN in row 15539 : 9
 Total NaN in row 15540 : 0
 Total NaN in row 15541 : 0
 Total NaN in row 15542 : 0
 Total NaN in row 15543 : 1
 Total NaN in row 15544 : 9
 Total NaN in row 15545 : 9
 Total NaN in row 15546 : 3
 Total NaN in row 15547 : 0
 Total NaN in row 15548 : 1
 Total NaN in row 15549 : 2
 Total NaN in row 15550 : 1
 Total NaN in row 15551 : 1
 Total NaN in row 15552 : 2
 Total NaN in row 15553 : 2
 Total NaN in row 15554 : 0
 Total NaN in row 15555 : 0
 Total NaN in row 15556 : 9
 Total NaN in row 15557 : 2
 Total NaN in row 15558 : 2
 Total NaN in row 15559 : 0
 Total NaN in row 15560 : 0
 Total NaN in row 15561 : 2
 Total NaN in row 15562 : 2
 Total NaN in row 15563 : 2
 Total NaN in row 15564 : 2
 Total NaN in row 15565 : 0
 Total NaN in row 15566 : 2
 Total NaN in row 15567 : 2
 Total NaN in row 15568 : 3
 Total NaN in row 15569 : 2
 Total NaN in row 15570 : 0
 Total NaN in row 15571 : 2
 Total NaN in row 15572 : 2
 Total NaN in row 15573 : 1
 Total NaN in row 15574 : 2
 Total NaN in row 15575 : 1
 Total NaN in row 15576 : 0
 Total NaN in row 15577 : 10
 Total NaN in row 15578 : 2
 Total NaN in row 15579 : 3
 Total NaN in row 15580 : 1
 Total NaN in row 15581 : 0
 Total NaN in row 15582 : 2
 Total NaN in row 15583 : 9
 Total NaN in row 15584 : 9
 Total NaN in row 15585 : 0
 Total NaN in row 15586 : 0
 Total NaN in row 15587 : 0
 Total NaN in row 15588 : 0
 Total NaN in row 15589 : 2
 Total NaN in row 15590 : 9
 Total NaN in row 15591 : 9
 Total NaN in row 15592 : 0
 Total NaN in row 15593 : 0
 Total NaN in row 15594 : 1
 Total NaN in row 15595 : 1
 Total NaN in row 15596 : 2
 Total NaN in row 15597 : 2
 Total NaN in row 15598 : 2
 Total NaN in row 15599 : 0
 Total NaN in row 15600 : 1
 Total NaN in row 15601 : 9
 Total NaN in row 15602 : 0
 Total NaN in row 15603 : 2
 Total NaN in row 15604 : 2
 Total NaN in row 15605 : 2
 Total NaN in row 15606 : 9
 Total NaN in row 15607 : 2
 Total NaN in row 15608 : 2
 Total NaN in row 15609 : 0
 Total NaN in row 15610 : 2
 Total NaN in row 15611 : 3
 Total NaN in row 15612 : 9
 Total NaN in row 15613 : 2
 Total NaN in row 15614 : 2
 Total NaN in row 15615 : 0
 Total NaN in row 15616 : 3
 Total NaN in row 15617 : 9
 Total NaN in row 15618 : 10
 Total NaN in row 15619 : 0
 Total NaN in row 15620 : 2
 Total NaN in row 15621 : 10
 Total NaN in row 15622 : 2
 Total NaN in row 15623 : 0
 Total NaN in row 15624 : 1
 Total NaN in row 15625 : 2
 Total NaN in row 15626 : 9
 Total NaN in row 15627 : 2
 Total NaN in row 15628 : 7
 Total NaN in row 15629 : 2
 Total NaN in row 15630 : 0
 Total NaN in row 15631 : 1
 Total NaN in row 15632 : 3
 Total NaN in row 15633 : 2
 Total NaN in row 15634 : 0
 Total NaN in row 15635 : 1
 Total NaN in row 15636 : 9
 Total NaN in row 15637 : 4
 Total NaN in row 15638 : 3
 Total NaN in row 15639 : 1
 Total NaN in row 15640 : 2
 Total NaN in row 15641 : 2
 Total NaN in row 15642 : 10
 Total NaN in row 15643 : 9
 Total NaN in row 15644 : 1
 Total NaN in row 15645 : 1
 Total NaN in row 15646 : 0
 Total NaN in row 15647 : 10
 Total NaN in row 15648 : 9
 Total NaN in row 15649 : 1
 Total NaN in row 15650 : 2
 Total NaN in row 15651 : 2
 Total NaN in row 15652 : 1
 Total NaN in row 15653 : 4
 Total NaN in row 15654 : 0
 Total NaN in row 15655 : 2
 Total NaN in row 15656 : 9
 Total NaN in row 15657 : 2
 Total NaN in row 15658 : 2
 Total NaN in row 15659 : 2
 Total NaN in row 15660 : 9
 Total NaN in row 15661 : 0
 Total NaN in row 15662 : 2
 Total NaN in row 15663 : 2
 Total NaN in row 15664 : 3
 Total NaN in row 15665 : 0
 Total NaN in row 15666 : 2
 Total NaN in row 15667 : 9
 Total NaN in row 15668 : 9
 Total NaN in row 15669 : 2
 Total NaN in row 15670 : 9
 Total NaN in row 15671 : 2
 Total NaN in row 15672 : 0
 Total NaN in row 15673 : 9
 Total NaN in row 15674 : 1
 Total NaN in row 15675 : 0
 Total NaN in row 15676 : 9
 Total NaN in row 15677 : 1
 Total NaN in row 15678 : 2
 Total NaN in row 15679 : 0
 Total NaN in row 15680 : 0
 Total NaN in row 15681 : 0
 Total NaN in row 15682 : 0
 Total NaN in row 15683 : 2
 Total NaN in row 15684 : 2
 Total NaN in row 15685 : 0
 Total NaN in row 15686 : 9
 Total NaN in row 15687 : 0
 Total NaN in row 15688 : 2
 Total NaN in row 15689 : 2
 Total NaN in row 15690 : 1
 Total NaN in row 15691 : 1
 Total NaN in row 15692 : 0
 Total NaN in row 15693 : 9
 Total NaN in row 15694 : 2
 Total NaN in row 15695 : 1
 Total NaN in row 15696 : 0
 Total NaN in row 15697 : 1
 Total NaN in row 15698 : 1
 Total NaN in row 15699 : 0
 Total NaN in row 15700 : 9
 Total NaN in row 15701 : 9
 Total NaN in row 15702 : 0
 Total NaN in row 15703 : 0
 Total NaN in row 15704 : 9
 Total NaN in row 15705 : 3
 Total NaN in row 15706 : 0
 Total NaN in row 15707 : 0
 Total NaN in row 15708 : 1
 Total NaN in row 15709 : 2
 Total NaN in row 15710 : 0
 Total NaN in row 15711 : 0
 Total NaN in row 15712 : 0
 Total NaN in row 15713 : 1
 Total NaN in row 15714 : 9
 Total NaN in row 15715 : 3
 Total NaN in row 15716 : 2
 Total NaN in row 15717 : 0
 Total NaN in row 15718 : 1
 Total NaN in row 15719 : 10
 Total NaN in row 15720 : 0
 Total NaN in row 15721 : 10
 Total NaN in row 15722 : 0
 Total NaN in row 15723 : 3
 Total NaN in row 15724 : 1
 Total NaN in row 15725 : 1
 Total NaN in row 15726 : 2
 Total NaN in row 15727 : 1
 Total NaN in row 15728 : 1
 Total NaN in row 15729 : 0
 Total NaN in row 15730 : 2
 Total NaN in row 15731 : 0
 Total NaN in row 15732 : 2
 Total NaN in row 15733 : 2
 Total NaN in row 15734 : 2
 Total NaN in row 15735 : 2
 Total NaN in row 15736 : 1
 Total NaN in row 15737 : 0
 Total NaN in row 15738 : 1
 Total NaN in row 15739 : 9
 Total NaN in row 15740 : 0
 Total NaN in row 15741 : 2
 Total NaN in row 15742 : 2
 Total NaN in row 15743 : 9
 Total NaN in row 15744 : 3
 Total NaN in row 15745 : 1
 Total NaN in row 15746 : 2
 Total NaN in row 15747 : 1
 Total NaN in row 15748 : 9
 Total NaN in row 15749 : 1
 Total NaN in row 15750 : 3
 Total NaN in row 15751 : 3
 Total NaN in row 15752 : 0
 Total NaN in row 15753 : 2
 Total NaN in row 15754 : 2
 Total NaN in row 15755 : 1
 Total NaN in row 15756 : 1
 Total NaN in row 15757 : 0
 Total NaN in row 15758 : 9
 Total NaN in row 15759 : 9
 Total NaN in row 15760 : 9
 Total NaN in row 15761 : 0
 Total NaN in row 15762 : 0
 Total NaN in row 15763 : 2
 Total NaN in row 15764 : 0
 Total NaN in row 15765 : 1
 Total NaN in row 15766 : 1
 Total NaN in row 15767 : 9
 Total NaN in row 15768 : 0
 Total NaN in row 15769 : 0
 Total NaN in row 15770 : 9
 Total NaN in row 15771 : 9
 Total NaN in row 15772 : 21
 Total NaN in row 15773 : 9
 Total NaN in row 15774 : 0
 Total NaN in row 15775 : 9
 Total NaN in row 15776 : 2
 Total NaN in row 15777 : 2
 Total NaN in row 15778 : 0
 Total NaN in row 15779 : 3
 Total NaN in row 15780 : 0
 Total NaN in row 15781 : 2
 Total NaN in row 15782 : 1
 Total NaN in row 15783 : 1
 Total NaN in row 15784 : 9
 Total NaN in row 15785 : 1
 Total NaN in row 15786 : 2
 Total NaN in row 15787 : 1
 Total NaN in row 15788 : 2
 Total NaN in row 15789 : 0
 Total NaN in row 15790 : 0
 Total NaN in row 15791 : 2
 Total NaN in row 15792 : 0
 Total NaN in row 15793 : 1
 Total NaN in row 15794 : 0
 Total NaN in row 15795 : 7
 Total NaN in row 15796 : 9
 Total NaN in row 15797 : 0
 Total NaN in row 15798 : 2
 Total NaN in row 15799 : 9
 Total NaN in row 15800 : 2
 Total NaN in row 15801 : 2
 Total NaN in row 15802 : 0
 Total NaN in row 15803 : 3
 Total NaN in row 15804 : 0
 Total NaN in row 15805 : 0
 Total NaN in row 15806 : 10
 Total NaN in row 15807 : 9

 Total NaN in row 15808 : 3
 Total NaN in row 15809 : 9
 Total NaN in row 15810 : 9
 Total NaN in row 15811 : 2
 Total NaN in row 15812 : 2
 Total NaN in row 15813 : 1
 Total NaN in row 15814 : 1
 Total NaN in row 15815 : 2
 Total NaN in row 15816 : 1
 Total NaN in row 15817 : 2
 Total NaN in row 15818 : 9
 Total NaN in row 15819 : 1
 Total NaN in row 15820 : 0
 Total NaN in row 15821 : 3
 Total NaN in row 15822 : 1
 Total NaN in row 15823 : 9
 Total NaN in row 15824 : 10
 Total NaN in row 15825 : 2
 Total NaN in row 15826 : 1
 Total NaN in row 15827 : 0
 Total NaN in row 15828 : 10
 Total NaN in row 15829 : 2
 Total NaN in row 15830 : 2
 Total NaN in row 15831 : 2
 Total NaN in row 15832 : 2
 Total NaN in row 15833 : 2
 Total NaN in row 15834 : 0
 Total NaN in row 15835 : 0
 Total NaN in row 15836 : 0
 Total NaN in row 15837 : 0
 Total NaN in row 15838 : 1
 Total NaN in row 15839 : 1
 Total NaN in row 15840 : 2
 Total NaN in row 15841 : 0
 Total NaN in row 15842 : 1
 Total NaN in row 15843 : 2
 Total NaN in row 15844 : 3
 Total NaN in row 15845 : 2
 Total NaN in row 15846 : 3
 Total NaN in row 15847 : 10
 Total NaN in row 15848 : 1
 Total NaN in row 15849 : 2
 Total NaN in row 15850 : 3
 Total NaN in row 15851 : 0
 Total NaN in row 15852 : 2
 Total NaN in row 15853 : 10
 Total NaN in row 15854 : 1
 Total NaN in row 15855 : 2
 Total NaN in row 15856 : 9
 Total NaN in row 15857 : 1
 Total NaN in row 15858 : 9
 Total NaN in row 15859 : 10
 Total NaN in row 15860 : 9
 Total NaN in row 15861 : 0
 Total NaN in row 15862 : 9
 Total NaN in row 15863 : 0
 Total NaN in row 15864 : 2
 Total NaN in row 15865 : 2
 Total NaN in row 15866 : 2
 Total NaN in row 15867 : 0
 Total NaN in row 15868 : 10
 Total NaN in row 15869 : 9
 Total NaN in row 15870 : 0
 Total NaN in row 15871 : 2
 Total NaN in row 15872 : 9
 Total NaN in row 15873 : 0
 Total NaN in row 15874 : 2
 Total NaN in row 15875 : 2
 Total NaN in row 15876 : 9
 Total NaN in row 15877 : 0
 Total NaN in row 15878 : 7
 Total NaN in row 15879 : 1
 Total NaN in row 15880 : 2
 Total NaN in row 15881 : 2
 Total NaN in row 15882 : 2
 Total NaN in row 15883 : 1
 Total NaN in row 15884 : 10
 Total NaN in row 15885 : 0
 Total NaN in row 15886 : 0
 Total NaN in row 15887 : 0
 Total NaN in row 15888 : 1
 Total NaN in row 15889 : 3
 Total NaN in row 15890 : 9
 Total NaN in row 15891 : 9
 Total NaN in row 15892 : 0
 Total NaN in row 15893 : 2
 Total NaN in row 15894 : 2
 Total NaN in row 15895 : 0
 Total NaN in row 15896 : 9
 Total NaN in row 15897 : 9
 Total NaN in row 15898 : 2
 Total NaN in row 15899 : 3
 Total NaN in row 15900 : 2
 Total NaN in row 15901 : 0
 Total NaN in row 15902 : 1
 Total NaN in row 15903 : 9
 Total NaN in row 15904 : 1
 Total NaN in row 15905 : 0
 Total NaN in row 15906 : 1
 Total NaN in row 15907 : 9
 Total NaN in row 15908 : 1
 Total NaN in row 15909 : 9
 Total NaN in row 15910 : 2
 Total NaN in row 15911 : 9
 Total NaN in row 15912 : 10
 Total NaN in row 15913 : 0
 Total NaN in row 15914 : 2
 Total NaN in row 15915 : 1
 Total NaN in row 15916 : 9
 Total NaN in row 15917 : 0
 Total NaN in row 15918 : 9
 Total NaN in row 15919 : 1
 Total NaN in row 15920 : 2
 Total NaN in row 15921 : 2
 Total NaN in row 15922 : 2
 Total NaN in row 15923 : 0
 Total NaN in row 15924 : 1
 Total NaN in row 15925 : 3
 Total NaN in row 15926 : 2
 Total NaN in row 15927 : 0
 Total NaN in row 15928 : 2
 Total NaN in row 15929 : 0
 Total NaN in row 15930 : 1
 Total NaN in row 15931 : 3
 Total NaN in row 15932 : 2
 Total NaN in row 15933 : 1
 Total NaN in row 15934 : 1
 Total NaN in row 15935 : 2
 Total NaN in row 15936 : 3
 Total NaN in row 15937 : 10
 Total NaN in row 15938 : 2
 Total NaN in row 15939 : 2
 Total NaN in row 15940 : 2
 Total NaN in row 15941 : 2
 Total NaN in row 15942 : 2
 Total NaN in row 15943 : 1
 Total NaN in row 15944 : 2
 Total NaN in row 15945 : 1
 Total NaN in row 15946 : 9
 Total NaN in row 15947 : 10
 Total NaN in row 15948 : 0
 Total NaN in row 15949 : 1
 Total NaN in row 15950 : 1
 Total NaN in row 15951 : 1
 Total NaN in row 15952 : 2
 Total NaN in row 15953 : 0
 Total NaN in row 15954 : 2
 Total NaN in row 15955 : 0
 Total NaN in row 15956 : 1
 Total NaN in row 15957 : 0
 Total NaN in row 15958 : 0
 Total NaN in row 15959 : 0
 Total NaN in row 15960 : 0
 Total NaN in row 15961 : 9
 Total NaN in row 15962 : 9
 Total NaN in row 15963 : 0
 Total NaN in row 15964 : 0
 Total NaN in row 15965 : 0
 Total NaN in row 15966 : 2
 Total NaN in row 15967 : 1
 Total NaN in row 15968 : 2
 Total NaN in row 15969 : 2
 Total NaN in row 15970 : 2
 Total NaN in row 15971 : 9
 Total NaN in row 15972 : 0
 Total NaN in row 15973 : 1
 Total NaN in row 15974 : 2
 Total NaN in row 15975 : 9
 Total NaN in row 15976 : 2
 Total NaN in row 15977 : 1
 Total NaN in row 15978 : 2
 Total NaN in row 15979 : 0
 Total NaN in row 15980 : 2
 Total NaN in row 15981 : 2
 Total NaN in row 15982 : 2
 Total NaN in row 15983 : 2
 Total NaN in row 15984 : 0
 Total NaN in row 15985 : 1
 Total NaN in row 15986 : 1
 Total NaN in row 15987 : 0
 Total NaN in row 15988 : 4
 Total NaN in row 15989 : 9
 Total NaN in row 15990 : 2
 Total NaN in row 15991 : 2
 Total NaN in row 15992 : 0
 Total NaN in row 15993 : 9
 Total NaN in row 15994 : 9
 Total NaN in row 15995 : 0
 Total NaN in row 15996 : 2
 Total NaN in row 15997 : 2
 Total NaN in row 15998 : 2
 Total NaN in row 15999 : 2
 Total NaN in row 16000 : 0
 Total NaN in row 16001 : 10
 Total NaN in row 16002 : 2
 Total NaN in row 16003 : 1
 Total NaN in row 16004 : 0
 Total NaN in row 16005 : 0
 Total NaN in row 16006 : 9
 Total NaN in row 16007 : 0
 Total NaN in row 16008 : 9
 Total NaN in row 16009 : 0
 Total NaN in row 16010 : 1
 Total NaN in row 16011 : 0
 Total NaN in row 16012 : 1
 Total NaN in row 16013 : 3
 Total NaN in row 16014 : 1
 Total NaN in row 16015 : 9
 Total NaN in row 16016 : 10
 Total NaN in row 16017 : 2
 Total NaN in row 16018 : 3
 Total NaN in row 16019 : 3
 Total NaN in row 16020 : 0
 Total NaN in row 16021 : 3
 Total NaN in row 16022 : 10
 Total NaN in row 16023 : 0
 Total NaN in row 16024 : 10
 Total NaN in row 16025 : 1
 Total NaN in row 16026 : 2
 Total NaN in row 16027 : 10
 Total NaN in row 16028 : 10
 Total NaN in row 16029 : 0
 Total NaN in row 16030 : 2
 Total NaN in row 16031 : 1
 Total NaN in row 16032 : 2
 Total NaN in row 16033 : 3
 Total NaN in row 16034 : 2
 Total NaN in row 16035 : 2
 Total NaN in row 16036 : 2
 Total NaN in row 16037 : 2
 Total NaN in row 16038 : 1
 Total NaN in row 16039 : 0
 Total NaN in row 16040 : 0
 Total NaN in row 16041 : 9
 Total NaN in row 16042 : 3
 Total NaN in row 16043 : 0
 Total NaN in row 16044 : 10
 Total NaN in row 16045 : 21
 Total NaN in row 16046 : 9
 Total NaN in row 16047 : 9
 Total NaN in row 16048 : 9
 Total NaN in row 16049 : 2
 Total NaN in row 16050 : 2
 Total NaN in row 16051 : 0
 Total NaN in row 16052 : 1
 Total NaN in row 16053 : 10
 Total NaN in row 16054 : 0
 Total NaN in row 16055 : 1
 Total NaN in row 16056 : 0
 Total NaN in row 16057 : 9
 Total NaN in row 16058 : 2
 Total NaN in row 16059 : 10
 Total NaN in row 16060 : 3
 Total NaN in row 16061 : 0
 Total NaN in row 16062 : 0
 Total NaN in row 16063 : 10
 Total NaN in row 16064 : 9
 Total NaN in row 16065 : 0
 Total NaN in row 16066 : 1
 Total NaN in row 16067 : 1
 Total NaN in row 16068 : 0
 Total NaN in row 16069 : 0
 Total NaN in row 16070 : 10
 Total NaN in row 16071 : 1
 Total NaN in row 16072 : 1
 Total NaN in row 16073 : 3
 Total NaN in row 16074 : 0
 Total NaN in row 16075 : 9
 Total NaN in row 16076 : 2
 Total NaN in row 16077 : 1
 Total NaN in row 16078 : 3
 Total NaN in row 16079 : 0
 Total NaN in row 16080 : 9
 Total NaN in row 16081 : 10
 Total NaN in row 16082 : 0
 Total NaN in row 16083 : 0
 Total NaN in row 16084 : 9
 Total NaN in row 16085 : 2
 Total NaN in row 16086 : 1
 Total NaN in row 16087 : 9
 Total NaN in row 16088 : 0
 Total NaN in row 16089 : 1
 Total NaN in row 16090 : 0
 Total NaN in row 16091 : 9
 Total NaN in row 16092 : 9
 Total NaN in row 16093 : 9
 Total NaN in row 16094 : 2
 Total NaN in row 16095 : 1
 Total NaN in row 16096 : 2
 Total NaN in row 16097 : 9
 Total NaN in row 16098 : 3
 Total NaN in row 16099 : 1
 Total NaN in row 16100 : 9
 Total NaN in row 16101 : 3
 Total NaN in row 16102 : 2
 Total NaN in row 16103 : 0
 Total NaN in row 16104 : 2
 Total NaN in row 16105 : 0
 Total NaN in row 16106 : 3
 Total NaN in row 16107 : 2
 Total NaN in row 16108 : 1
 Total NaN in row 16109 : 2
 Total NaN in row 16110 : 2
 Total NaN in row 16111 : 1
 Total NaN in row 16112 : 2
 Total NaN in row 16113 : 0
 Total NaN in row 16114 : 9
 Total NaN in row 16115 : 9
 Total NaN in row 16116 : 9
 Total NaN in row 16117 : 2
 Total NaN in row 16118 : 9
 Total NaN in row 16119 : 10
 Total NaN in row 16120 : 9
 Total NaN in row 16121 : 1
 Total NaN in row 16122 : 2
 Total NaN in row 16123 : 3
 Total NaN in row 16124 : 0
 Total NaN in row 16125 : 2
 Total NaN in row 16126 : 1
 Total NaN in row 16127 : 10
 Total NaN in row 16128 : 9
 Total NaN in row 16129 : 1
 Total NaN in row 16130 : 2
 Total NaN in row 16131 : 3
 Total NaN in row 16132 : 0
 Total NaN in row 16133 : 2
 Total NaN in row 16134 : 9
 Total NaN in row 16135 : 2
 Total NaN in row 16136 : 0
 Total NaN in row 16137 : 2
 Total NaN in row 16138 : 2
 Total NaN in row 16139 : 3
 Total NaN in row 16140 : 9
 Total NaN in row 16141 : 2
 Total NaN in row 16142 : 9

 Total NaN in row 16143 : 3
 Total NaN in row 16144 : 3
 Total NaN in row 16145 : 0
 Total NaN in row 16146 : 1
 Total NaN in row 16147 : 2
 Total NaN in row 16148 : 0
 Total NaN in row 16149 : 2
 Total NaN in row 16150 : 2
 Total NaN in row 16151 : 2
 Total NaN in row 16152 : 2
 Total NaN in row 16153 : 2
 Total NaN in row 16154 : 1
 Total NaN in row 16155 : 0
 Total NaN in row 16156 : 2
 Total NaN in row 16157 : 1
 Total NaN in row 16158 : 3
 Total NaN in row 16159 : 9
 Total NaN in row 16160 : 9
 Total NaN in row 16161 : 2
 Total NaN in row 16162 : 1
 Total NaN in row 16163 : 0
 Total NaN in row 16164 : 3
 Total NaN in row 16165 : 1
 Total NaN in row 16166 : 9
 Total NaN in row 16167 : 9
 Total NaN in row 16168 : 9
 Total NaN in row 16169 : 1
 Total NaN in row 16170 : 1
 Total NaN in row 16171 : 3
 Total NaN in row 16172 : 2
 Total NaN in row 16173 : 0
 Total NaN in row 16174 : 10
 Total NaN in row 16175 : 9
 Total NaN in row 16176 : 2
 Total NaN in row 16177 : 2
 Total NaN in row 16178 : 9
 Total NaN in row 16179 : 1
 Total NaN in row 16180 : 2
 Total NaN in row 16181 : 0
 Total NaN in row 16182 : 10
 Total NaN in row 16183 : 0
 Total NaN in row 16184 : 9
 Total NaN in row 16185 : 0
 Total NaN in row 16186 : 0
 Total NaN in row 16187 : 2
 Total NaN in row 16188 : 9
 Total NaN in row 16189 : 2
 Total NaN in row 16190 : 3
 Total NaN in row 16191 : 3
 Total NaN in row 16192 : 3
 Total NaN in row 16193 : 0
 Total NaN in row 16194 : 2
 Total NaN in row 16195 : 9
 Total NaN in row 16196 : 2
 Total NaN in row 16197 : 0
 Total NaN in row 16198 : 0
 Total NaN in row 16199 : 1
 Total NaN in row 16200 : 9
 Total NaN in row 16201 : 2
 Total NaN in row 16202 : 9
 Total NaN in row 16203 : 0
 Total NaN in row 16204 : 9
 Total NaN in row 16205 : 9
 Total NaN in row 16206 : 3
 Total NaN in row 16207 : 9
 Total NaN in row 16208 : 0
 Total NaN in row 16209 : 9
 Total NaN in row 16210 : 3
 Total NaN in row 16211 : 0
 Total NaN in row 16212 : 2
 Total NaN in row 16213 : 2
 Total NaN in row 16214 : 7
 Total NaN in row 16215 : 0
 Total NaN in row 16216 : 2
 Total NaN in row 16217 : 1
 Total NaN in row 16218 : 9
 Total NaN in row 16219 : 0
 Total NaN in row 16220 : 0
 Total NaN in row 16221 : 9
 Total NaN in row 16222 : 2
 Total NaN in row 16223 : 2
 Total NaN in row 16224 : 2
 Total NaN in row 16225 : 10
 Total NaN in row 16226 : 9
 Total NaN in row 16227 : 2
 Total NaN in row 16228 : 2
 Total NaN in row 16229 : 2
 Total NaN in row 16230 : 1
 Total NaN in row 16231 : 2
 Total NaN in row 16232 : 1
 Total NaN in row 16233 : 9
 Total NaN in row 16234 : 2
 Total NaN in row 16235 : 3
 Total NaN in row 16236 : 9
 Total NaN in row 16237 : 1
 Total NaN in row 16238 : 2
 Total NaN in row 16239 : 9
 Total NaN in row 16240 : 3
 Total NaN in row 16241 : 0
 Total NaN in row 16242 : 2
 Total NaN in row 16243 : 1
 Total NaN in row 16244 : 2
 Total NaN in row 16245 : 2
 Total NaN in row 16246 : 3
 Total NaN in row 16247 : 2
 Total NaN in row 16248 : 2
 Total NaN in row 16249 : 3
 Total NaN in row 16250 : 0
 Total NaN in row 16251 : 2
 Total NaN in row 16252 : 9
 Total NaN in row 16253 : 21
 Total NaN in row 16254 : 1
 Total NaN in row 16255 : 9
 Total NaN in row 16256 : 2
 Total NaN in row 16257 : 0
 Total NaN in row 16258 : 2
 Total NaN in row 16259 : 0
 Total NaN in row 16260 : 0
 Total NaN in row 16261 : 0
 Total NaN in row 16262 : 1
 Total NaN in row 16263 : 0
 Total NaN in row 16264 : 9
 Total NaN in row 16265 : 2
 Total NaN in row 16266 : 2
 Total NaN in row 16267 : 9
 Total NaN in row 16268 : 9
 Total NaN in row 16269 : 0
 Total NaN in row 16270 : 2
 Total NaN in row 16271 : 3
 Total NaN in row 16272 : 3
 Total NaN in row 16273 : 2
 Total NaN in row 16274 : 0
 Total NaN in row 16275 : 10
 Total NaN in row 16276 : 0
 Total NaN in row 16277 : 9
 Total NaN in row 16278 : 10
 Total NaN in row 16279 : 3
 Total NaN in row 16280 : 0
 Total NaN in row 16281 : 1
 Total NaN in row 16282 : 9
 Total NaN in row 16283 : 9
 Total NaN in row 16284 : 9
 Total NaN in row 16285 : 1
 Total NaN in row 16286 : 9
 Total NaN in row 16287 : 0
 Total NaN in row 16288 : 0
 Total NaN in row 16289 : 9
 Total NaN in row 16290 : 3
 Total NaN in row 16291 : 1
 Total NaN in row 16292 : 10
 Total NaN in row 16293 : 9
 Total NaN in row 16294 : 9
 Total NaN in row 16295 : 2
 Total NaN in row 16296 : 2
 Total NaN in row 16297 : 0
 Total NaN in row 16298 : 1
 Total NaN in row 16299 : 2
 Total NaN in row 16300 : 2
 Total NaN in row 16301 : 2
 Total NaN in row 16302 : 3
 Total NaN in row 16303 : 3
 Total NaN in row 16304 : 2
 Total NaN in row 16305 : 9
 Total NaN in row 16306 : 2
 Total NaN in row 16307 : 1
 Total NaN in row 16308 : 9
 Total NaN in row 16309 : 1
 Total NaN in row 16310 : 2
 Total NaN in row 16311 : 0
 Total NaN in row 16312 : 0
 Total NaN in row 16313 : 1
 Total NaN in row 16314 : 9
 Total NaN in row 16315 : 2
 Total NaN in row 16316 : 9
 Total NaN in row 16317 : 2
 Total NaN in row 16318 : 3
 Total NaN in row 16319 : 2
 Total NaN in row 16320 : 10
 Total NaN in row 16321 : 3
 Total NaN in row 16322 : 10
 Total NaN in row 16323 : 2
 Total NaN in row 16324 : 3
 Total NaN in row 16325 : 10
 Total NaN in row 16326 : 2
 Total NaN in row 16327 : 10
 Total NaN in row 16328 : 0
 Total NaN in row 16329 : 0
 Total NaN in row 16330 : 0
 Total NaN in row 16331 : 10
 Total NaN in row 16332 : 1
 Total NaN in row 16333 : 1
 Total NaN in row 16334 : 0
 Total NaN in row 16335 : 0
 Total NaN in row 16336 : 2
 Total NaN in row 16337 : 9
 Total NaN in row 16338 : 2
 Total NaN in row 16339 : 10
 Total NaN in row 16340 : 1
 Total NaN in row 16341 : 0
 Total NaN in row 16342 : 0
 Total NaN in row 16343 : 10
 Total NaN in row 16344 : 2
 Total NaN in row 16345 : 2
 Total NaN in row 16346 : 1
 Total NaN in row 16347 : 9
 Total NaN in row 16348 : 9
 Total NaN in row 16349 : 2
 Total NaN in row 16350 : 9
 Total NaN in row 16351 : 1
 Total NaN in row 16352 : 3
 Total NaN in row 16353 : 10
 Total NaN in row 16354 : 2
 Total NaN in row 16355 : 0
 Total NaN in row 16356 : 2
 Total NaN in row 16357 : 9
 Total NaN in row 16358 : 9
 Total NaN in row 16359 : 9
 Total NaN in row 16360 : 2
 Total NaN in row 16361 : 3
 Total NaN in row 16362 : 2
 Total NaN in row 16363 : 3
 Total NaN in row 16364 : 2
 Total NaN in row 16365 : 2
 Total NaN in row 16366 : 10
 Total NaN in row 16367 : 1
 Total NaN in row 16368 : 2
 Total NaN in row 16369 : 9
 Total NaN in row 16370 : 2
 Total NaN in row 16371 : 9
 Total NaN in row 16372 : 1
 Total NaN in row 16373 : 10
 Total NaN in row 16374 : 3
 Total NaN in row 16375 : 9
 Total NaN in row 16376 : 1
 Total NaN in row 16377 : 1
 Total NaN in row 16378 : 9
 Total NaN in row 16379 : 1
 Total NaN in row 16380 : 1
 Total NaN in row 16381 : 9
 Total NaN in row 16382 : 9
 Total NaN in row 16383 : 1
 Total NaN in row 16384 : 10
 Total NaN in row 16385 : 2
 Total NaN in row 16386 : 3
 Total NaN in row 16387 : 9
 Total NaN in row 16388 : 0
 Total NaN in row 16389 : 2
 Total NaN in row 16390 : 1
 Total NaN in row 16391 : 2
 Total NaN in row 16392 : 0
 Total NaN in row 16393 : 2
 Total NaN in row 16394 : 0
 Total NaN in row 16395 : 0
 Total NaN in row 16396 : 2
 Total NaN in row 16397 : 0
 Total NaN in row 16398 : 0
 Total NaN in row 16399 : 2
 Total NaN in row 16400 : 1
 Total NaN in row 16401 : 2
 Total NaN in row 16402 : 2
 Total NaN in row 16403 : 0
 Total NaN in row 16404 : 0
 Total NaN in row 16405 : 1
 Total NaN in row 16406 : 0
 Total NaN in row 16407 : 9
 Total NaN in row 16408 : 10
 Total NaN in row 16409 : 9
 Total NaN in row 16410 : 1
 Total NaN in row 16411 : 1
 Total NaN in row 16412 : 2
 Total NaN in row 16413 : 3
 Total NaN in row 16414 : 1
 Total NaN in row 16415 : 0
 Total NaN in row 16416 : 10
 Total NaN in row 16417 : 2
 Total NaN in row 16418 : 0
 Total NaN in row 16419 : 1
 Total NaN in row 16420 : 1
 Total NaN in row 16421 : 3
 Total NaN in row 16422 : 2
 Total NaN in row 16423 : 1
 Total NaN in row 16424 : 1
 Total NaN in row 16425 : 2
 Total NaN in row 16426 : 1
 Total NaN in row 16427 : 1
 Total NaN in row 16428 : 3
 Total NaN in row 16429 : 2
 Total NaN in row 16430 : 10
 Total NaN in row 16431 : 2
 Total NaN in row 16432 : 9
 Total NaN in row 16433 : 2
 Total NaN in row 16434 : 0
 Total NaN in row 16435 : 2
 Total NaN in row 16436 : 1
 Total NaN in row 16437 : 9
 Total NaN in row 16438 : 2
 Total NaN in row 16439 : 2
 Total NaN in row 16440 : 0
 Total NaN in row 16441 : 1
 Total NaN in row 16442 : 2
 Total NaN in row 16443 : 2
 Total NaN in row 16444 : 0
 Total NaN in row 16445 : 9
 Total NaN in row 16446 : 9
 Total NaN in row 16447 : 9
 Total NaN in row 16448 : 1
 Total NaN in row 16449 : 9

 Total NaN in row 16450 : 2
 Total NaN in row 16451 : 2
 Total NaN in row 16452 : 2
 Total NaN in row 16453 : 2
 Total NaN in row 16454 : 2
 Total NaN in row 16455 : 1
 Total NaN in row 16456 : 9
 Total NaN in row 16457 : 2
 Total NaN in row 16458 : 1
 Total NaN in row 16459 : 2
 Total NaN in row 16460 : 2
 Total NaN in row 16461 : 7
 Total NaN in row 16462 : 3
 Total NaN in row 16463 : 9
 Total NaN in row 16464 : 2
 Total NaN in row 16465 : 2
 Total NaN in row 16466 : 0
 Total NaN in row 16467 : 0
 Total NaN in row 16468 : 9
 Total NaN in row 16469 : 9
 Total NaN in row 16470 : 10
 Total NaN in row 16471 : 9
 Total NaN in row 16472 : 1
 Total NaN in row 16473 : 9
 Total NaN in row 16474 : 10
 Total NaN in row 16475 : 3
 Total NaN in row 16476 : 10
 Total NaN in row 16477 : 10
 Total NaN in row 16478 : 2
 Total NaN in row 16479 : 1
 Total NaN in row 16480 : 1
 Total NaN in row 16481 : 1
 Total NaN in row 16482 : 0
 Total NaN in row 16483 : 10
 Total NaN in row 16484 : 0
 Total NaN in row 16485 : 2
 Total NaN in row 16486 : 9
 Total NaN in row 16487 : 7
 Total NaN in row 16488 : 9
 Total NaN in row 16489 : 0
 Total NaN in row 16490 : 0
 Total NaN in row 16491 : 2
 Total NaN in row 16492 : 1
 Total NaN in row 16493 : 1
 Total NaN in row 16494 : 9
 Total NaN in row 16495 : 9
 Total NaN in row 16496 : 3
 Total NaN in row 16497 : 2
 Total NaN in row 16498 : 0
 Total NaN in row 16499 : 9
 Total NaN in row 16500 : 9
 Total NaN in row 16501 : 0
 Total NaN in row 16502 : 0
 Total NaN in row 16503 : 9
 Total NaN in row 16504 : 1
 Total NaN in row 16505 : 3
 Total NaN in row 16506 : 9
 Total NaN in row 16507 : 2
 Total NaN in row 16508 : 1
 Total NaN in row 16509 : 2
 Total NaN in row 16510 : 0
 Total NaN in row 16511 : 1
 Total NaN in row 16512 : 2
 Total NaN in row 16513 : 9
 Total NaN in row 16514 : 2
 Total NaN in row 16515 : 2
 Total NaN in row 16516 : 0
 Total NaN in row 16517 : 2
 Total NaN in row 16518 : 0
 Total NaN in row 16519 : 0
 Total NaN in row 16520 : 2
 Total NaN in row 16521 : 3
 Total NaN in row 16522 : 2
 Total NaN in row 16523 : 2
 Total NaN in row 16524 : 2
 Total NaN in row 16525 : 9
 Total NaN in row 16526 : 2
 Total NaN in row 16527 : 0
 Total NaN in row 16528 : 1
 Total NaN in row 16529 : 2
 Total NaN in row 16530 : 2
 Total NaN in row 16531 : 2
 Total NaN in row 16532 : 0
 Total NaN in row 16533 : 9
 Total NaN in row 16534 : 2
 Total NaN in row 16535 : 2
 Total NaN in row 16536 : 0
 Total NaN in row 16537 : 0
 Total NaN in row 16538 : 2
 Total NaN in row 16539 : 0
 Total NaN in row 16540 : 1
 Total NaN in row 16541 : 0
 Total NaN in row 16542 : 2
 Total NaN in row 16543 : 0
 Total NaN in row 16544 : 2
 Total NaN in row 16545 : 2
 Total NaN in row 16546 : 2
 Total NaN in row 16547 : 2
 Total NaN in row 16548 : 1
 Total NaN in row 16549 : 9
 Total NaN in row 16550 : 1
 Total NaN in row 16551 : 0
 Total NaN in row 16552 : 1
 Total NaN in row 16553 : 3
 Total NaN in row 16554 : 2
 Total NaN in row 16555 : 0
 Total NaN in row 16556 : 0
 Total NaN in row 16557 : 2
 Total NaN in row 16558 : 0
 Total NaN in row 16559 : 3
 Total NaN in row 16560 : 0
 Total NaN in row 16561 : 9
 Total NaN in row 16562 : 2
 Total NaN in row 16563 : 1
 Total NaN in row 16564 : 21
 Total NaN in row 16565 : 2
 Total NaN in row 16566 : 2
 Total NaN in row 16567 : 2
 Total NaN in row 16568 : 2
 Total NaN in row 16569 : 2
 Total NaN in row 16570 : 9
 Total NaN in row 16571 : 9
 Total NaN in row 16572 : 0
 Total NaN in row 16573 : 1
 Total NaN in row 16574 : 2
 Total NaN in row 16575 : 2
 Total NaN in row 16576 : 3
 Total NaN in row 16577 : 0
 Total NaN in row 16578 : 2
 Total NaN in row 16579 : 2
 Total NaN in row 16580 : 1
 Total NaN in row 16581 : 0
 Total NaN in row 16582 : 0
 Total NaN in row 16583 : 10
 Total NaN in row 16584 : 0
 Total NaN in row 16585 : 0
 Total NaN in row 16586 : 2
 Total NaN in row 16587 : 2
 Total NaN in row 16588 : 1
 Total NaN in row 16589 : 2
 Total NaN in row 16590 : 0
 Total NaN in row 16591 : 1
 Total NaN in row 16592 : 0
 Total NaN in row 16593 : 9
 Total NaN in row 16594 : 2
 Total NaN in row 16595 : 9
 Total NaN in row 16596 : 2
 Total NaN in row 16597 : 0
 Total NaN in row 16598 : 7
 Total NaN in row 16599 : 1
 Total NaN in row 16600 : 0
 Total NaN in row 16601 : 0
 Total NaN in row 16602 : 9
 Total NaN in row 16603 : 9
 Total NaN in row 16604 : 1
 Total NaN in row 16605 : 2
 Total NaN in row 16606 : 2
 Total NaN in row 16607 : 1
 Total NaN in row 16608 : 0
 Total NaN in row 16609 : 9
 Total NaN in row 16610 : 1
 Total NaN in row 16611 : 2
 Total NaN in row 16612 : 2
 Total NaN in row 16613 : 1
 Total NaN in row 16614 : 0
 Total NaN in row 16615 : 7
 Total NaN in row 16616 : 1
 Total NaN in row 16617 : 2
 Total NaN in row 16618 : 1
 Total NaN in row 16619 : 0
 Total NaN in row 16620 : 2
 Total NaN in row 16621 : 0
 Total NaN in row 16622 : 1
 Total NaN in row 16623 : 1
 Total NaN in row 16624 : 0
 Total NaN in row 16625 : 0
 Total NaN in row 16626 : 1
 Total NaN in row 16627 : 2
 Total NaN in row 16628 : 1
 Total NaN in row 16629 : 9
 Total NaN in row 16630 : 9
 Total NaN in row 16631 : 9
 Total NaN in row 16632 : 1
 Total NaN in row 16633 : 3
 Total NaN in row 16634 : 0
 Total NaN in row 16635 : 2
 Total NaN in row 16636 : 1
 Total NaN in row 16637 : 2
 Total NaN in row 16638 : 2
 Total NaN in row 16639 : 9
 Total NaN in row 16640 : 9
 Total NaN in row 16641 : 2
 Total NaN in row 16642 : 1
 Total NaN in row 16643 : 1
 Total NaN in row 16644 : 9
 Total NaN in row 16645 : 9
 Total NaN in row 16646 : 3
 Total NaN in row 16647 : 2
 Total NaN in row 16648 : 2
 Total NaN in row 16649 : 2
 Total NaN in row 16650 : 9
 Total NaN in row 16651 : 2
 Total NaN in row 16652 : 9
 Total NaN in row 16653 : 10
 Total NaN in row 16654 : 9
 Total NaN in row 16655 : 2
 Total NaN in row 16656 : 21
 Total NaN in row 16657 : 1
 Total NaN in row 16658 : 10
 Total NaN in row 16659 : 2
 Total NaN in row 16660 : 3
 Total NaN in row 16661 : 4
 Total NaN in row 16662 : 2
 Total NaN in row 16663 : 2
 Total NaN in row 16664 : 9
 Total NaN in row 16665 : 9
 Total NaN in row 16666 : 3
 Total NaN in row 16667 : 2
 Total NaN in row 16668 : 3
 Total NaN in row 16669 : 9
 Total NaN in row 16670 : 1
 Total NaN in row 16671 : 0
 Total NaN in row 16672 : 2
 Total NaN in row 16673 : 2
 Total NaN in row 16674 : 3
 Total NaN in row 16675 : 3
 Total NaN in row 16676 : 1
 Total NaN in row 16677 : 0
 Total NaN in row 16678 : 2
 Total NaN in row 16679 : 9
 Total NaN in row 16680 : 2
 Total NaN in row 16681 : 0
 Total NaN in row 16682 : 0
 Total NaN in row 16683 : 10
 Total NaN in row 16684 : 3
 Total NaN in row 16685 : 2
 Total NaN in row 16686 : 2
 Total NaN in row 16687 : 3
 Total NaN in row 16688 : 3
 Total NaN in row 16689 : 2
 Total NaN in row 16690 : 1
 Total NaN in row 16691 : 0
 Total NaN in row 16692 : 1
 Total NaN in row 16693 : 0
 Total NaN in row 16694 : 2
 Total NaN in row 16695 : 2
 Total NaN in row 16696 : 9
 Total NaN in row 16697 : 2
 Total NaN in row 16698 : 2
 Total NaN in row 16699 : 3
 Total NaN in row 16700 : 1
 Total NaN in row 16701 : 9
 Total NaN in row 16702 : 3
 Total NaN in row 16703 : 1
 Total NaN in row 16704 : 1
 Total NaN in row 16705 : 0
 Total NaN in row 16706 : 2
 Total NaN in row 16707 : 2
 Total NaN in row 16708 : 2
 Total NaN in row 16709 : 0
 Total NaN in row 16710 : 9
 Total NaN in row 16711 : 2
 Total NaN in row 16712 : 3
 Total NaN in row 16713 : 9
 Total NaN in row 16714 : 3
 Total NaN in row 16715 : 1
 Total NaN in row 16716 : 9
 Total NaN in row 16717 : 9
 Total NaN in row 16718 : 2
 Total NaN in row 16719 : 0
 Total NaN in row 16720 : 2
 Total NaN in row 16721 : 9
 Total NaN in row 16722 : 2
 Total NaN in row 16723 : 2
 Total NaN in row 16724 : 1
 Total NaN in row 16725 : 2
 Total NaN in row 16726 : 1
 Total NaN in row 16727 : 1
 Total NaN in row 16728 : 0
 Total NaN in row 16729 : 0
 Total NaN in row 16730 : 3
 Total NaN in row 16731 : 0
 Total NaN in row 16732 : 9
 Total NaN in row 16733 : 2
 Total NaN in row 16734 : 0
 Total NaN in row 16735 : 0
 Total NaN in row 16736 : 0
 Total NaN in row 16737 : 0
 Total NaN in row 16738 : 0
 Total NaN in row 16739 : 0
 Total NaN in row 16740 : 2
 Total NaN in row 16741 : 9
 Total NaN in row 16742 : 0
 Total NaN in row 16743 : 2
 Total NaN in row 16744 : 0
 Total NaN in row 16745 : 2
 Total NaN in row 16746 : 0
 Total NaN in row 16747 : 9
 Total NaN in row 16748 : 2
 Total NaN in row 16749 : 1
 Total NaN in row 16750 : 9
 Total NaN in row 16751 : 0
 Total NaN in row 16752 : 1
 Total NaN in row 16753 : 2

 Total NaN in row 16754 : 0
 Total NaN in row 16755 : 2
 Total NaN in row 16756 : 3
 Total NaN in row 16757 : 2
 Total NaN in row 16758 : 1
 Total NaN in row 16759 : 10
 Total NaN in row 16760 : 9
 Total NaN in row 16761 : 2
 Total NaN in row 16762 : 7
 Total NaN in row 16763 : 1
 Total NaN in row 16764 : 2
 Total NaN in row 16765 : 0
 Total NaN in row 16766 : 0
 Total NaN in row 16767 : 0
 Total NaN in row 16768 : 0
 Total NaN in row 16769 : 1
 Total NaN in row 16770 : 1
 Total NaN in row 16771 : 0
 Total NaN in row 16772 : 0
 Total NaN in row 16773 : 1
 Total NaN in row 16774 : 2
 Total NaN in row 16775 : 2
 Total NaN in row 16776 : 3
 Total NaN in row 16777 : 1
 Total NaN in row 16778 : 0
 Total NaN in row 16779 : 9
 Total NaN in row 16780 : 0
 Total NaN in row 16781 : 2
 Total NaN in row 16782 : 2
 Total NaN in row 16783 : 2
 Total NaN in row 16784 : 0
 Total NaN in row 16785 : 0
 Total NaN in row 16786 : 2
 Total NaN in row 16787 : 3
 Total NaN in row 16788 : 1
 Total NaN in row 16789 : 9
 Total NaN in row 16790 : 9
 Total NaN in row 16791 : 1
 Total NaN in row 16792 : 2
 Total NaN in row 16793 : 0
 Total NaN in row 16794 : 9
 Total NaN in row 16795 : 0
 Total NaN in row 16796 : 9
 Total NaN in row 16797 : 1
 Total NaN in row 16798 : 2
 Total NaN in row 16799 : 0
 Total NaN in row 16800 : 1
 Total NaN in row 16801 : 1
 Total NaN in row 16802 : 0
 Total NaN in row 16803 : 2
 Total NaN in row 16804 : 9
 Total NaN in row 16805 : 2
 Total NaN in row 16806 : 10
 Total NaN in row 16807 : 2
 Total NaN in row 16808 : 2
 Total NaN in row 16809 : 3
 Total NaN in row 16810 : 9
 Total NaN in row 16811 : 2
 Total NaN in row 16812 : 1
 Total NaN in row 16813 : 2
 Total NaN in row 16814 : 9
 Total NaN in row 16815 : 2
 Total NaN in row 16816 : 10
 Total NaN in row 16817 : 3
 Total NaN in row 16818 : 2
 Total NaN in row 16819 : 2
 Total NaN in row 16820 : 0
 Total NaN in row 16821 : 3
 Total NaN in row 16822 : 2
 Total NaN in row 16823 : 10
 Total NaN in row 16824 : 0
 Total NaN in row 16825 : 0
 Total NaN in row 16826 : 0
 Total NaN in row 16827 : 9
 Total NaN in row 16828 : 1
 Total NaN in row 16829 : 0
 Total NaN in row 16830 : 0
 Total NaN in row 16831 : 2
 Total NaN in row 16832 : 2
 Total NaN in row 16833 : 2
 Total NaN in row 16834 : 2
 Total NaN in row 16835 : 0
 Total NaN in row 16836 : 0
 Total NaN in row 16837 : 0
 Total NaN in row 16838 : 0
 Total NaN in row 16839 : 2
 Total NaN in row 16840 : 2
 Total NaN in row 16841 : 0
 Total NaN in row 16842 : 1
 Total NaN in row 16843 : 0
 Total NaN in row 16844 : 1
 Total NaN in row 16845 : 3
 Total NaN in row 16846 : 1
 Total NaN in row 16847 : 2
 Total NaN in row 16848 : 9
 Total NaN in row 16849 : 21
 Total NaN in row 16850 : 0
 Total NaN in row 16851 : 9
 Total NaN in row 16852 : 9
 Total NaN in row 16853 : 1
 Total NaN in row 16854 : 9
 Total NaN in row 16855 : 9
 Total NaN in row 16856 : 0
 Total NaN in row 16857 : 0
 Total NaN in row 16858 : 1
 Total NaN in row 16859 : 2
 Total NaN in row 16860 : 10
 Total NaN in row 16861 : 9
 Total NaN in row 16862 : 2
 Total NaN in row 16863 : 0
 Total NaN in row 16864 : 9
 Total NaN in row 16865 : 2
 Total NaN in row 16866 : 0
 Total NaN in row 16867 : 2
 Total NaN in row 16868 : 9
 Total NaN in row 16869 : 9
 Total NaN in row 16870 : 1
 Total NaN in row 16871 : 9
 Total NaN in row 16872 : 2
 Total NaN in row 16873 : 10
 Total NaN in row 16874 : 0
 Total NaN in row 16875 : 0
 Total NaN in row 16876 : 0
 Total NaN in row 16877 : 0
 Total NaN in row 16878 : 2
 Total NaN in row 16879 : 1
 Total NaN in row 16880 : 1
 Total NaN in row 16881 : 2
 Total NaN in row 16882 : 1
 Total NaN in row 16883 : 0
 Total NaN in row 16884 : 0
 Total NaN in row 16885 : 3
 Total NaN in row 16886 : 9
 Total NaN in row 16887 : 9
 Total NaN in row 16888 : 0
 Total NaN in row 16889 : 1
 Total NaN in row 16890 : 3
 Total NaN in row 16891 : 1
 Total NaN in row 16892 : 0
 Total NaN in row 16893 : 2
 Total NaN in row 16894 : 0
 Total NaN in row 16895 : 10
 Total NaN in row 16896 : 9
 Total NaN in row 16897 : 9
 Total NaN in row 16898 : 9
 Total NaN in row 16899 : 9
 Total NaN in row 16900 : 9
 Total NaN in row 16901 : 1
 Total NaN in row 16902 : 2
 Total NaN in row 16903 : 0
 Total NaN in row 16904 : 9
 Total NaN in row 16905 : 9
 Total NaN in row 16906 : 0
 Total NaN in row 16907 : 2
 Total NaN in row 16908 : 0
 Total NaN in row 16909 : 1
 Total NaN in row 16910 : 0
 Total NaN in row 16911 : 9
 Total NaN in row 16912 : 1
 Total NaN in row 16913 : 9
 Total NaN in row 16914 : 0
 Total NaN in row 16915 : 1
 Total NaN in row 16916 : 9
 Total NaN in row 16917 : 2
 Total NaN in row 16918 : 3
 Total NaN in row 16919 : 2
 Total NaN in row 16920 : 0
 Total NaN in row 16921 : 10
 Total NaN in row 16922 : 1
 Total NaN in row 16923 : 1
 Total NaN in row 16924 : 0
 Total NaN in row 16925 : 0
 Total NaN in row 16926 : 1
 Total NaN in row 16927 : 2
 Total NaN in row 16928 : 0
 Total NaN in row 16929 : 9
 Total NaN in row 16930 : 0
 Total NaN in row 16931 : 0
 Total NaN in row 16932 : 9
 Total NaN in row 16933 : 9
 Total NaN in row 16934 : 0
 Total NaN in row 16935 : 9
 Total NaN in row 16936 : 0
 Total NaN in row 16937 : 1
 Total NaN in row 16938 : 2
 Total NaN in row 16939 : 10
 Total NaN in row 16940 : 1
 Total NaN in row 16941 : 0
 Total NaN in row 16942 : 9
 Total NaN in row 16943 : 9
 Total NaN in row 16944 : 0
 Total NaN in row 16945 : 0
 Total NaN in row 16946 : 9
 Total NaN in row 16947 : 2
 Total NaN in row 16948 : 2
 Total NaN in row 16949 : 2
 Total NaN in row 16950 : 2
 Total NaN in row 16951 : 2
 Total NaN in row 16952 : 2
 Total NaN in row 16953 : 0
 Total NaN in row 16954 : 2
 Total NaN in row 16955 : 0
 Total NaN in row 16956 : 1
 Total NaN in row 16957 : 2
 Total NaN in row 16958 : 10
 Total NaN in row 16959 : 9
 Total NaN in row 16960 : 2
 Total NaN in row 16961 : 2
 Total NaN in row 16962 : 0
 Total NaN in row 16963 : 9
 Total NaN in row 16964 : 0
 Total NaN in row 16965 : 0
 Total NaN in row 16966 : 0
 Total NaN in row 16967 : 9
 Total NaN in row 16968 : 9
 Total NaN in row 16969 : 1
 Total NaN in row 16970 : 9
 Total NaN in row 16971 : 1
 Total NaN in row 16972 : 9
 Total NaN in row 16973 : 2
 Total NaN in row 16974 : 9
 Total NaN in row 16975 : 0
 Total NaN in row 16976 : 0
 Total NaN in row 16977 : 9
 Total NaN in row 16978 : 2
 Total NaN in row 16979 : 2
 Total NaN in row 16980 : 0
 Total NaN in row 16981 : 0
 Total NaN in row 16982 : 10
 Total NaN in row 16983 : 0
 Total NaN in row 16984 : 2
 Total NaN in row 16985 : 0
 Total NaN in row 16986 : 0
 Total NaN in row 16987 : 2
 Total NaN in row 16988 : 0
 Total NaN in row 16989 : 0
 Total NaN in row 16990 : 0
 Total NaN in row 16991 : 1
 Total NaN in row 16992 : 9
 Total NaN in row 16993 : 1
 Total NaN in row 16994 : 0
 Total NaN in row 16995 : 0
 Total NaN in row 16996 : 2
 Total NaN in row 16997 : 9
 Total NaN in row 16998 : 0
 Total NaN in row 16999 : 0
 Total NaN in row 17000 : 2
 Total NaN in row 17001 : 0
 Total NaN in row 17002 : 2
 Total NaN in row 17003 : 1
 Total NaN in row 17004 : 2
 Total NaN in row 17005 : 1
 Total NaN in row 17006 : 0
 Total NaN in row 17007 : 9
 Total NaN in row 17008 : 0
 Total NaN in row 17009 : 1
 Total NaN in row 17010 : 2
 Total NaN in row 17011 : 0
 Total NaN in row 17012 : 2
 Total NaN in row 17013 : 3
 Total NaN in row 17014 : 0
 Total NaN in row 17015 : 1
 Total NaN in row 17016 : 2
 Total NaN in row 17017 : 0
 Total NaN in row 17018 : 3
 Total NaN in row 17019 : 3
 Total NaN in row 17020 : 9
 Total NaN in row 17021 : 2
 Total NaN in row 17022 : 2
 Total NaN in row 17023 : 1
 Total NaN in row 17024 : 2
 Total NaN in row 17025 : 0
 Total NaN in row 17026 : 2
 Total NaN in row 17027 : 9
 Total NaN in row 17028 : 0
 Total NaN in row 17029 : 9
 Total NaN in row 17030 : 1
 Total NaN in row 17031 : 0
 Total NaN in row 17032 : 2
 Total NaN in row 17033 : 2
 Total NaN in row 17034 : 10
 Total NaN in row 17035 : 2
 Total NaN in row 17036 : 10
 Total NaN in row 17037 : 2
 Total NaN in row 17038 : 9
 Total NaN in row 17039 : 10
 Total NaN in row 17040 : 1
 Total NaN in row 17041 : 1
 Total NaN in row 17042 : 1
 Total NaN in row 17043 : 2
 Total NaN in row 17044 : 9
 Total NaN in row 17045 : 9
 Total NaN in row 17046 : 0
 Total NaN in row 17047 : 1
 Total NaN in row 17048 : 0
 Total NaN in row 17049 : 1
 Total NaN in row 17050 : 9
 Total NaN in row 17051 : 5
 Total NaN in row 17052 : 2
 Total NaN in row 17053 : 2
 Total NaN in row 17054 : 0
 Total NaN in row 17055 : 1
 Total NaN in row 17056 : 9
 Total NaN in row 17057 : 3
 Total NaN in row 17058 : 2
 Total NaN in row 17059 : 2
 Total NaN in row 17060 : 9
 Total NaN in row 17061 : 2
 Total NaN in row 17062 : 2
 Total NaN in row 17063 : 2
 Total NaN in row 17064 : 9
 Total NaN in row 17065 : 10
 Total NaN in row 17066 : 0
 Total NaN in row 17067 : 0
 Total NaN in row 17068 : 2
 Total NaN in row 17069 : 0
 Total NaN in row 17070 : 0
 Total NaN in row 17071 : 1
 Total NaN in row 17072 : 0
 Total NaN in row 17073 : 9
 Total NaN in row 17074 : 2
 Total NaN in row 17075 : 0
 Total NaN in row 17076 : 2
 Total NaN in row 17077 : 0
 Total NaN in row 17078 : 9
 Total NaN in row 17079 : 9
 Total NaN in row 17080 : 10
 Total NaN in row 17081 : 1
 Total NaN in row 17082 : 10
 Total NaN in row 17083 : 9
 Total NaN in row 17084 : 0
 Total NaN in row 17085 : 0
 Total NaN in row 17086 : 10
 Total NaN in row 17087 : 1
 Total NaN in row 17088 : 2
 Total NaN in row 17089 : 9
 Total NaN in row 17090 : 10
 Total NaN in row 17091 : 3
 Total NaN in row 17092 : 3
 Total NaN in row 17093 : 2
 Total NaN in row 17094 : 2
 Total NaN in row 17095 : 0
 Total NaN in row 17096 : 9
 Total NaN in row 17097 : 9
 Total NaN in row 17098 : 2
 Total NaN in row 17099 : 2
 Total NaN in row 17100 : 0
 Total NaN in row 17101 : 2
 Total NaN in row 17102 : 1
 Total NaN in row 17103 : 1
 Total NaN in row 17104 : 0

 Total NaN in row 17105 : 2
 Total NaN in row 17106 : 0
 Total NaN in row 17107 : 2
 Total NaN in row 17108 : 2
 Total NaN in row 17109 : 1
 Total NaN in row 17110 : 2
 Total NaN in row 17111 : 9
 Total NaN in row 17112 : 21
 Total NaN in row 17113 : 1
 Total NaN in row 17114 : 0
 Total NaN in row 17115 : 7
 Total NaN in row 17116 : 0
 Total NaN in row 17117 : 2
 Total NaN in row 17118 : 0
 Total NaN in row 17119 : 3
 Total NaN in row 17120 : 0
 Total NaN in row 17121 : 2
 Total NaN in row 17122 : 2
 Total NaN in row 17123 : 0
 Total NaN in row 17124 : 0
 Total NaN in row 17125 : 2
 Total NaN in row 17126 : 1
 Total NaN in row 17127 : 2
 Total NaN in row 17128 : 0
 Total NaN in row 17129 : 0
 Total NaN in row 17130 : 2
 Total NaN in row 17131 : 2
 Total NaN in row 17132 : 3
 Total NaN in row 17133 : 1
 Total NaN in row 17134 : 0
 Total NaN in row 17135 : 9
 Total NaN in row 17136 : 0
 Total NaN in row 17137 : 9
 Total NaN in row 17138 : 9
 Total NaN in row 17139 : 0
 Total NaN in row 17140 : 0
 Total NaN in row 17141 : 1
 Total NaN in row 17142 : 2
 Total NaN in row 17143 : 0
 Total NaN in row 17144 : 2
 Total NaN in row 17145 : 0
 Total NaN in row 17146 : 2
 Total NaN in row 17147 : 0
 Total NaN in row 17148 : 9
 Total NaN in row 17149 : 3
 Total NaN in row 17150 : 9
 Total NaN in row 17151 : 9
 Total NaN in row 17152 : 0
 Total NaN in row 17153 : 2
 Total NaN in row 17154 : 3
 Total NaN in row 17155 : 0
 Total NaN in row 17156 : 0
 Total NaN in row 17157 : 0
 Total NaN in row 17158 : 0
 Total NaN in row 17159 : 1
 Total NaN in row 17160 : 9
 Total NaN in row 17161 : 1
 Total NaN in row 17162 : 1
 Total NaN in row 17163 : 2
 Total NaN in row 17164 : 2
 Total NaN in row 17165 : 1
 Total NaN in row 17166 : 0
 Total NaN in row 17167 : 1
 Total NaN in row 17168 : 9
 Total NaN in row 17169 : 1
 Total NaN in row 17170 : 9
 Total NaN in row 17171 : 1
 Total NaN in row 17172 : 2
 Total NaN in row 17173 : 3
 Total NaN in row 17174 : 1
 Total NaN in row 17175 : 9
 Total NaN in row 17176 : 2
 Total NaN in row 17177 : 0
 Total NaN in row 17178 : 1
 Total NaN in row 17179 : 2
 Total NaN in row 17180 : 2
 Total NaN in row 17181 : 0
 Total NaN in row 17182 : 1
 Total NaN in row 17183 : 2
 Total NaN in row 17184 : 3
 Total NaN in row 17185 : 0
 Total NaN in row 17186 : 0
 Total NaN in row 17187 : 9
 Total NaN in row 17188 : 0
 Total NaN in row 17189 : 2
 Total NaN in row 17190 : 3
 Total NaN in row 17191 : 2
 Total NaN in row 17192 : 3
 Total NaN in row 17193 : 0
 Total NaN in row 17194 : 0
 Total NaN in row 17195 : 10
 Total NaN in row 17196 : 0
 Total NaN in row 17197 : 0
 Total NaN in row 17198 : 9
 Total NaN in row 17199 : 10
 Total NaN in row 17200 : 2
 Total NaN in row 17201 : 10
 Total NaN in row 17202 : 1
 Total NaN in row 17203 : 2
 Total NaN in row 17204 : 0
 Total NaN in row 17205 : 3
 Total NaN in row 17206 : 1
 Total NaN in row 17207 : 0
 Total NaN in row 17208 : 1
 Total NaN in row 17209 : 2
 Total NaN in row 17210 : 1
 Total NaN in row 17211 : 0
 Total NaN in row 17212 : 0
 Total NaN in row 17213 : 9
 Total NaN in row 17214 : 2
 Total NaN in row 17215 : 0
 Total NaN in row 17216 : 1
 Total NaN in row 17217 : 2
 Total NaN in row 17218 : 9
 Total NaN in row 17219 : 0
 Total NaN in row 17220 : 9
 Total NaN in row 17221 : 0
 Total NaN in row 17222 : 0
 Total NaN in row 17223 : 0
 Total NaN in row 17224 : 2
 Total NaN in row 17225 : 0
 Total NaN in row 17226 : 9
 Total NaN in row 17227 : 2
 Total NaN in row 17228 : 0
 Total NaN in row 17229 : 3
 Total NaN in row 17230 : 9
 Total NaN in row 17231 : 1
 Total NaN in row 17232 : 9
 Total NaN in row 17233 : 9
 Total NaN in row 17234 : 9
 Total NaN in row 17235 : 1
 Total NaN in row 17236 : 1
 Total NaN in row 17237 : 9
 Total NaN in row 17238 : 0
 Total NaN in row 17239 : 0
 Total NaN in row 17240 : 0
 Total NaN in row 17241 : 0
 Total NaN in row 17242 : 2
 Total NaN in row 17243 : 1
 Total NaN in row 17244 : 1
 Total NaN in row 17245 : 2
 Total NaN in row 17246 : 1
 Total NaN in row 17247 : 21
 Total NaN in row 17248 : 2
 Total NaN in row 17249 : 0
 Total NaN in row 17250 : 0
 Total NaN in row 17251 : 2
 Total NaN in row 17252 : 2
 Total NaN in row 17253 : 0
 Total NaN in row 17254 : 1
 Total NaN in row 17255 : 9
 Total NaN in row 17256 : 2
 Total NaN in row 17257 : 2
 Total NaN in row 17258 : 2
 Total NaN in row 17259 : 9
 Total NaN in row 17260 : 1
 Total NaN in row 17261 : 2
 Total NaN in row 17262 : 2
 Total NaN in row 17263 : 2
 Total NaN in row 17264 : 10
 Total NaN in row 17265 : 2
 Total NaN in row 17266 : 9
 Total NaN in row 17267 : 0
 Total NaN in row 17268 : 0
 Total NaN in row 17269 : 2
 Total NaN in row 17270 : 3
 Total NaN in row 17271 : 9
 Total NaN in row 17272 : 2
 Total NaN in row 17273 : 2
 Total NaN in row 17274 : 2
 Total NaN in row 17275 : 10
 Total NaN in row 17276 : 0
 Total NaN in row 17277 : 0
 Total NaN in row 17278 : 9
 Total NaN in row 17279 : 0
 Total NaN in row 17280 : 2
 Total NaN in row 17281 : 0
 Total NaN in row 17282 : 2
 Total NaN in row 17283 : 0
 Total NaN in row 17284 : 0
 Total NaN in row 17285 : 9
 Total NaN in row 17286 : 0
 Total NaN in row 17287 : 3
 Total NaN in row 17288 : 2
 Total NaN in row 17289 : 9
 Total NaN in row 17290 : 1
 Total NaN in row 17291 : 1
 Total NaN in row 17292 : 9
 Total NaN in row 17293 : 2
 Total NaN in row 17294 : 1
 Total NaN in row 17295 : 2
 Total NaN in row 17296 : 0
 Total NaN in row 17297 : 2
 Total NaN in row 17298 : 1
 Total NaN in row 17299 : 9
 Total NaN in row 17300 : 2
 Total NaN in row 17301 : 0
 Total NaN in row 17302 : 9
 Total NaN in row 17303 : 3
 Total NaN in row 17304 : 3
 Total NaN in row 17305 : 0
 Total NaN in row 17306 : 2
 Total NaN in row 17307 : 10
 Total NaN in row 17308 : 0
 Total NaN in row 17309 : 1
 Total NaN in row 17310 : 0
 Total NaN in row 17311 : 9
 Total NaN in row 17312 : 0
 Total NaN in row 17313 : 2
 Total NaN in row 17314 : 3
 Total NaN in row 17315 : 1
 Total NaN in row 17316 : 10
 Total NaN in row 17317 : 0
 Total NaN in row 17318 : 2
 Total NaN in row 17319 : 9
 Total NaN in row 17320 : 0
 Total NaN in row 17321 : 1
 Total NaN in row 17322 : 1
 Total NaN in row 17323 : 0
 Total NaN in row 17324 : 2
 Total NaN in row 17325 : 9
 Total NaN in row 17326 : 0
 Total NaN in row 17327 : 1
 Total NaN in row 17328 : 1
 Total NaN in row 17329 : 1
 Total NaN in row 17330 : 1
 Total NaN in row 17331 : 3
 Total NaN in row 17332 : 1
 Total NaN in row 17333 : 9
 Total NaN in row 17334 : 0
 Total NaN in row 17335 : 1
 Total NaN in row 17336 : 0
 Total NaN in row 17337 : 10
 Total NaN in row 17338 : 9
 Total NaN in row 17339 : 0
 Total NaN in row 17340 : 2
 Total NaN in row 17341 : 2
 Total NaN in row 17342 : 2
 Total NaN in row 17343 : 0
 Total NaN in row 17344 : 0
 Total NaN in row 17345 : 1
 Total NaN in row 17346 : 0
 Total NaN in row 17347 : 0
 Total NaN in row 17348 : 2
 Total NaN in row 17349 : 0
 Total NaN in row 17350 : 2
 Total NaN in row 17351 : 0
 Total NaN in row 17352 : 3
 Total NaN in row 17353 : 9
 Total NaN in row 17354 : 10
 Total NaN in row 17355 : 9
 Total NaN in row 17356 : 0
 Total NaN in row 17357 : 1
 Total NaN in row 17358 : 2
 Total NaN in row 17359 : 0
 Total NaN in row 17360 : 2
 Total NaN in row 17361 : 2
 Total NaN in row 17362 : 2
 Total NaN in row 17363 : 0
 Total NaN in row 17364 : 0
 Total NaN in row 17365 : 0
 Total NaN in row 17366 : 9
 Total NaN in row 17367 : 3
 Total NaN in row 17368 : 2
 Total NaN in row 17369 : 0
 Total NaN in row 17370 : 9
 Total NaN in row 17371 : 2
 Total NaN in row 17372 : 9
 Total NaN in row 17373 : 0
 Total NaN in row 17374 : 2
 Total NaN in row 17375 : 10
 Total NaN in row 17376 : 1
 Total NaN in row 17377 : 9
 Total NaN in row 17378 : 10
 Total NaN in row 17379 : 9
 Total NaN in row 17380 : 1
 Total NaN in row 17381 : 10
 Total NaN in row 17382 : 2
 Total NaN in row 17383 : 0
 Total NaN in row 17384 : 1
 Total NaN in row 17385 : 1
 Total NaN in row 17386 : 9
 Total NaN in row 17387 : 9
 Total NaN in row 17388 : 0
 Total NaN in row 17389 : 1
 Total NaN in row 17390 : 0
 Total NaN in row 17391 : 1
 Total NaN in row 17392 : 0
 Total NaN in row 17393 : 2
 Total NaN in row 17394 : 2
 Total NaN in row 17395 : 2
 Total NaN in row 17396 : 1
 Total NaN in row 17397 : 2
 Total NaN in row 17398 : 9
 Total NaN in row 17399 : 1
 Total NaN in row 17400 : 9
 Total NaN in row 17401 : 1
 Total NaN in row 17402 : 1
 Total NaN in row 17403 : 0
 Total NaN in row 17404 : 0
 Total NaN in row 17405 : 1
 Total NaN in row 17406 : 1
 Total NaN in row 17407 : 7
 Total NaN in row 17408 : 1
 Total NaN in row 17409 : 0
 Total NaN in row 17410 : 2
 Total NaN in row 17411 : 9
 Total NaN in row 17412 : 2
 Total NaN in row 17413 : 3
 Total NaN in row 17414 : 1
 Total NaN in row 17415 : 2
 Total NaN in row 17416 : 9
 Total NaN in row 17417 : 2
 Total NaN in row 17418 : 10
 Total NaN in row 17419 : 9
 Total NaN in row 17420 : 0
 Total NaN in row 17421 : 10
 Total NaN in row 17422 : 3
 Total NaN in row 17423 : 0
 Total NaN in row 17424 : 2
 Total NaN in row 17425 : 7
 Total NaN in row 17426 : 2
 Total NaN in row 17427 : 9
 Total NaN in row 17428 : 0
 Total NaN in row 17429 : 2
 Total NaN in row 17430 : 0
 Total NaN in row 17431 : 2
 Total NaN in row 17432 : 0
 Total NaN in row 17433 : 0
 Total NaN in row 17434 : 2
 Total NaN in row 17435 : 3
 Total NaN in row 17436 : 9
 Total NaN in row 17437 : 1
 Total NaN in row 17438 : 0
 Total NaN in row 17439 : 0
 Total NaN in row 17440 : 1
 Total NaN in row 17441 : 1
 Total NaN in row 17442 : 2
 Total NaN in row 17443 : 2
 Total NaN in row 17444 : 9
 Total NaN in row 17445 : 2
 Total NaN in row 17446 : 2
 Total NaN in row 17447 : 3
 Total NaN in row 17448 : 10
 Total NaN in row 17449 : 10
 Total NaN in row 17450 : 10
 Total NaN in row 17451 : 9
 Total NaN in row 17452 : 2
 Total NaN in row 17453 : 1
 Total NaN in row 17454 : 0
 Total NaN in row 17455 : 1
 Total NaN in row 17456 : 2
 Total NaN in row 17457 : 9
 Total NaN in row 17458 : 2
 Total NaN in row 17459 : 0
 Total NaN in row 17460 : 0
 Total NaN in row 17461 : 2
 Total NaN in row 17462 : 0
 Total NaN in row 17463 : 2
 Total NaN in row 17464 : 9
 Total NaN in row 17465 : 3
 Total NaN in row 17466 : 9
 Total NaN in row 17467 : 0
 Total NaN in row 17468 : 2
 Total NaN in row 17469 : 0
 Total NaN in row 17470 : 2
 Total NaN in row 17471 : 1
 Total NaN in row 17472 : 3
 Total NaN in row 17473 : 1
 Total NaN in row 17474 : 10
 Total NaN in row 17475 : 9
 Total NaN in row 17476 : 0
 Total NaN in row 17477 : 9
 Total NaN in row 17478 : 9
 Total NaN in row 17479 : 2
 Total NaN in row 17480 : 10
 Total NaN in row 17481 : 9
 Total NaN in row 17482 : 0
 Total NaN in row 17483 : 2
 Total NaN in row 17484 : 0
 Total NaN in row 17485 : 3
 Total NaN in row 17486 : 1
 Total NaN in row 17487 : 2
 Total NaN in row 17488 : 0
 Total NaN in row 17489 : 1
 Total NaN in row 17490 : 0
 Total NaN in row 17491 : 3
 Total NaN in row 17492 : 1
 Total NaN in row 17493 : 2
 Total NaN in row 17494 : 9
 Total NaN in row 17495 : 3
 Total NaN in row 17496 : 2
 Total NaN in row 17497 : 2
 Total NaN in row 17498 : 2
 Total NaN in row 17499 : 2
 Total NaN in row 17500 : 0
 Total NaN in row 17501 : 0

 Total NaN in row 17502 : 1
 Total NaN in row 17503 : 0
 Total NaN in row 17504 : 2
 Total NaN in row 17505 : 0
 Total NaN in row 17506 : 3
 Total NaN in row 17507 : 3
 Total NaN in row 17508 : 1
 Total NaN in row 17509 : 2
 Total NaN in row 17510 : 0
 Total NaN in row 17511 : 2
 Total NaN in row 17512 : 1
 Total NaN in row 17513 : 9
 Total NaN in row 17514 : 2
 Total NaN in row 17515 : 2
 Total NaN in row 17516 : 9
 Total NaN in row 17517 : 1
 Total NaN in row 17518 : 1
 Total NaN in row 17519 : 7
 Total NaN in row 17520 : 3
 Total NaN in row 17521 : 2
 Total NaN in row 17522 : 1
 Total NaN in row 17523 : 2
 Total NaN in row 17524 : 2
 Total NaN in row 17525 : 0
 Total NaN in row 17526 : 0
 Total NaN in row 17527 : 2
 Total NaN in row 17528 : 2
 Total NaN in row 17529 : 9
 Total NaN in row 17530 : 1
 Total NaN in row 17531 : 9
 Total NaN in row 17532 : 2
 Total NaN in row 17533 : 1
 Total NaN in row 17534 : 0
 Total NaN in row 17535 : 9
 Total NaN in row 17536 : 0
 Total NaN in row 17537 : 10
 Total NaN in row 17538 : 0
 Total NaN in row 17539 : 0
 Total NaN in row 17540 : 1
 Total NaN in row 17541 : 0
 Total NaN in row 17542 : 3
 Total NaN in row 17543 : 0
 Total NaN in row 17544 : 0
 Total NaN in row 17545 : 0
 Total NaN in row 17546 : 2
 Total NaN in row 17547 : 0
 Total NaN in row 17548 : 2
 Total NaN in row 17549 : 0
 Total NaN in row 17550 : 1
 Total NaN in row 17551 : 0
 Total NaN in row 17552 : 0
 Total NaN in row 17553 : 9
 Total NaN in row 17554 : 2
 Total NaN in row 17555 : 0
 Total NaN in row 17556 : 0
 Total NaN in row 17557 : 0
 Total NaN in row 17558 : 0
 Total NaN in row 17559 : 2
 Total NaN in row 17560 : 0
 Total NaN in row 17561 : 0
 Total NaN in row 17562 : 0
 Total NaN in row 17563 : 9
 Total NaN in row 17564 : 9
 Total NaN in row 17565 : 0
 Total NaN in row 17566 : 0
 Total NaN in row 17567 : 2
 Total NaN in row 17568 : 0
 Total NaN in row 17569 : 0
 Total NaN in row 17570 : 1
 Total NaN in row 17571 : 0
 Total NaN in row 17572 : 2
 Total NaN in row 17573 : 2
 Total NaN in row 17574 : 0
 Total NaN in row 17575 : 0
 Total NaN in row 17576 : 0
 Total NaN in row 17577 : 0
 Total NaN in row 17578 : 1
 Total NaN in row 17579 : 0
 Total NaN in row 17580 : 0
 Total NaN in row 17581 : 0
 Total NaN in row 17582 : 1
 Total NaN in row 17583 : 1
 Total NaN in row 17584 : 0
 Total NaN in row 17585 : 1
 Total NaN in row 17586 : 9
 Total NaN in row 17587 : 3
 Total NaN in row 17588 : 2
 Total NaN in row 17589 : 0
 Total NaN in row 17590 : 0
 Total NaN in row 17591 : 9
 Total NaN in row 17592 : 2
 Total NaN in row 17593 : 0
 Total NaN in row 17594 : 0
 Total NaN in row 17595 : 3
 Total NaN in row 17596 : 5
 Total NaN in row 17597 : 2
 Total NaN in row 17598 : 1
 Total NaN in row 17599 : 2
 Total NaN in row 17600 : 0
 Total NaN in row 17601 : 0
 Total NaN in row 17602 : 0
 Total NaN in row 17603 : 10
 Total NaN in row 17604 : 2
 Total NaN in row 17605 : 0
 Total NaN in row 17606 : 2
 Total NaN in row 17607 : 2
 Total NaN in row 17608 : 1
 Total NaN in row 17609 : 1
 Total NaN in row 17610 : 0
 Total NaN in row 17611 : 0
 Total NaN in row 17612 : 21
 Total NaN in row 17613 : 9
 Total NaN in row 17614 : 0
 Total NaN in row 17615 : 2
 Total NaN in row 17616 : 0
 Total NaN in row 17617 : 2
 Total NaN in row 17618 : 3
 Total NaN in row 17619 : 2
 Total NaN in row 17620 : 2
 Total NaN in row 17621 : 0
 Total NaN in row 17622 : 0
 Total NaN in row 17623 : 1
 Total NaN in row 17624 : 0
 Total NaN in row 17625 : 2
 Total NaN in row 17626 : 2
 Total NaN in row 17627 : 0
 Total NaN in row 17628 : 3
 Total NaN in row 17629 : 0
 Total NaN in row 17630 : 9
 Total NaN in row 17631 : 3
 Total NaN in row 17632 : 0
 Total NaN in row 17633 : 9
 Total NaN in row 17634 : 0
 Total NaN in row 17635 : 2
 Total NaN in row 17636 : 0
 Total NaN in row 17637 : 1
 Total NaN in row 17638 : 0
 Total NaN in row 17639 : 2
 Total NaN in row 17640 : 1
 Total NaN in row 17641 : 0
 Total NaN in row 17642 : 1
 Total NaN in row 17643 : 2
 Total NaN in row 17644 : 0
 Total NaN in row 17645 : 1
 Total NaN in row 17646 : 0
 Total NaN in row 17647 : 1
 Total NaN in row 17648 : 0
 Total NaN in row 17649 : 0
 Total NaN in row 17650 : 0
 Total NaN in row 17651 : 2
 Total NaN in row 17652 : 9
 Total NaN in row 17653 : 2
 Total NaN in row 17654 : 0
 Total NaN in row 17655 : 0
 Total NaN in row 17656 : 0
 Total NaN in row 17657 : 0
 Total NaN in row 17658 : 0
 Total NaN in row 17659 : 0
 Total NaN in row 17660 : 2
 Total NaN in row 17661 : 1
 Total NaN in row 17662 : 3
 Total NaN in row 17663 : 0
 Total NaN in row 17664 : 1
 Total NaN in row 17665 : 1
 Total NaN in row 17666 : 0
 Total NaN in row 17667 : 2
 Total NaN in row 17668 : 2
 Total NaN in row 17669 : 1
 Total NaN in row 17670 : 0
 Total NaN in row 17671 : 0
 Total NaN in row 17672 : 1
 Total NaN in row 17673 : 0
 Total NaN in row 17674 : 10
 Total NaN in row 17675 : 1
 Total NaN in row 17676 : 2
 Total NaN in row 17677 : 9
 Total NaN in row 17678 : 2
 Total NaN in row 17679 : 0
 Total NaN in row 17680 : 0
 Total NaN in row 17681 : 0
 Total NaN in row 17682 : 2
 Total NaN in row 17683 : 2
 Total NaN in row 17684 : 1
 Total NaN in row 17685 : 0
 Total NaN in row 17686 : 1
 Total NaN in row 17687 : 0
 Total NaN in row 17688 : 0
 Total NaN in row 17689 : 0
 Total NaN in row 17690 : 2
 Total NaN in row 17691 : 2
 Total NaN in row 17692 : 2
 Total NaN in row 17693 : 2
 Total NaN in row 17694 : 2
 Total NaN in row 17695 : 2
 Total NaN in row 17696 : 0
 Total NaN in row 17697 : 2
 Total NaN in row 17698 : 0
 Total NaN in row 17699 : 9
 Total NaN in row 17700 : 0
 Total NaN in row 17701 : 2
 Total NaN in row 17702 : 2
 Total NaN in row 17703 : 0
 Total NaN in row 17704 : 0
 Total NaN in row 17705 : 2
 Total NaN in row 17706 : 0
 Total NaN in row 17707 : 2
 Total NaN in row 17708 : 0
 Total NaN in row 17709 : 0
 Total NaN in row 17710 : 2
 Total NaN in row 17711 : 9
 Total NaN in row 17712 : 0
 Total NaN in row 17713 : 1
 Total NaN in row 17714 : 2
 Total NaN in row 17715 : 1
 Total NaN in row 17716 : 0
 Total NaN in row 17717 : 4
 Total NaN in row 17718 : 2
 Total NaN in row 17719 : 0
 Total NaN in row 17720 : 2
 Total NaN in row 17721 : 4
 Total NaN in row 17722 : 1
 Total NaN in row 17723 : 10
 Total NaN in row 17724 : 2
 Total NaN in row 17725 : 0
 Total NaN in row 17726 : 0
 Total NaN in row 17727 : 0
 Total NaN in row 17728 : 9
 Total NaN in row 17729 : 9
 Total NaN in row 17730 : 0
 Total NaN in row 17731 : 0
 Total NaN in row 17732 : 2
 Total NaN in row 17733 : 1
 Total NaN in row 17734 : 9
 Total NaN in row 17735 : 0
 Total NaN in row 17736 : 10
 Total NaN in row 17737 : 0
 Total NaN in row 17738 : 0
 Total NaN in row 17739 : 1
 Total NaN in row 17740 : 2
 Total NaN in row 17741 : 0
 Total NaN in row 17742 : 21
 Total NaN in row 17743 : 0
 Total NaN in row 17744 : 1
 Total NaN in row 17745 : 1
 Total NaN in row 17746 : 0
 Total NaN in row 17747 : 2
 Total NaN in row 17748 : 0
 Total NaN in row 17749 : 1
 Total NaN in row 17750 : 1
 Total NaN in row 17751 : 2
 Total NaN in row 17752 : 2
 Total NaN in row 17753 : 0
 Total NaN in row 17754 : 0
 Total NaN in row 17755 : 2
 Total NaN in row 17756 : 0
 Total NaN in row 17757 : 0
 Total NaN in row 17758 : 0
 Total NaN in row 17759 : 0
 Total NaN in row 17760 : 0
 Total NaN in row 17761 : 9
 Total NaN in row 17762 : 2
 Total NaN in row 17763 : 1
 Total NaN in row 17764 : 0
 Total NaN in row 17765 : 1
 Total NaN in row 17766 : 2
 Total NaN in row 17767 : 0
 Total NaN in row 17768 : 0
 Total NaN in row 17769 : 3
 Total NaN in row 17770 : 9
 Total NaN in row 17771 : 0
 Total NaN in row 17772 : 0
 Total NaN in row 17773 : 2
 Total NaN in row 17774 : 2
 Total NaN in row 17775 : 2
 Total NaN in row 17776 : 10
 Total NaN in row 17777 : 0
 Total NaN in row 17778 : 2
 Total NaN in row 17779 : 1
 Total NaN in row 17780 : 2
 Total NaN in row 17781 : 0
 Total NaN in row 17782 : 2
 Total NaN in row 17783 : 2
 Total NaN in row 17784 : 1
 Total NaN in row 17785 : 9
 Total NaN in row 17786 : 2
 Total NaN in row 17787 : 0
 Total NaN in row 17788 : 2
 Total NaN in row 17789 : 10
 Total NaN in row 17790 : 2
 Total NaN in row 17791 : 0
 Total NaN in row 17792 : 0
 Total NaN in row 17793 : 0
 Total NaN in row 17794 : 1

 Total NaN in row 17795 : 1
 Total NaN in row 17796 : 9
 Total NaN in row 17797 : 0
 Total NaN in row 17798 : 2
 Total NaN in row 17799 : 2
 Total NaN in row 17800 : 0
 Total NaN in row 17801 : 2
 Total NaN in row 17802 : 9
 Total NaN in row 17803 : 1
 Total NaN in row 17804 : 0
 Total NaN in row 17805 : 0
 Total NaN in row 17806 : 0
 Total NaN in row 17807 : 2
 Total NaN in row 17808 : 9
 Total NaN in row 17809 : 2
 Total NaN in row 17810 : 9
 Total NaN in row 17811 : 0
 Total NaN in row 17812 : 1
 Total NaN in row 17813 : 3
 Total NaN in row 17814 : 1
 Total NaN in row 17815 : 9
 Total NaN in row 17816 : 2
 Total NaN in row 17817 : 1
 Total NaN in row 17818 : 1
 Total NaN in row 17819 : 2
 Total NaN in row 17820 : 2
 Total NaN in row 17821 : 1
 Total NaN in row 17822 : 3
 Total NaN in row 17823 : 1
 Total NaN in row 17824 : 9
 Total NaN in row 17825 : 9
 Total NaN in row 17826 : 7
 Total NaN in row 17827 : 3
 Total NaN in row 17828 : 0
 Total NaN in row 17829 : 1
 Total NaN in row 17830 : 2
 Total NaN in row 17831 : 9
 Total NaN in row 17832 : 3
 Total NaN in row 17833 : 1
 Total NaN in row 17834 : 2
 Total NaN in row 17835 : 1
 Total NaN in row 17836 : 1
 Total NaN in row 17837 : 2
 Total NaN in row 17838 : 2
 Total NaN in row 17839 : 9
 Total NaN in row 17840 : 3
 Total NaN in row 17841 : 0
 Total NaN in row 17842 : 0
 Total NaN in row 17843 : 3
 Total NaN in row 17844 : 0
 Total NaN in row 17845 : 9
 Total NaN in row 17846 : 9
 Total NaN in row 17847 : 0
 Total NaN in row 17848 : 0
 Total NaN in row 17849 : 9
 Total NaN in row 17850 : 0
 Total NaN in row 17851 : 9
 Total NaN in row 17852 : 2
 Total NaN in row 17853 : 1
 Total NaN in row 17854 : 0
 Total NaN in row 17855 : 3
 Total NaN in row 17856 : 0
 Total NaN in row 17857 : 0
 Total NaN in row 17858 : 0
 Total NaN in row 17859 : 0
 Total NaN in row 17860 : 0
 Total NaN in row 17861 : 0
 Total NaN in row 17862 : 0
 Total NaN in row 17863 : 0
 Total NaN in row 17864 : 2
 Total NaN in row 17865 : 0
 Total NaN in row 17866 : 2
 Total NaN in row 17867 : 2
 Total NaN in row 17868 : 0
 Total NaN in row 17869 : 2
 Total NaN in row 17870 : 0
 Total NaN in row 17871 : 2
 Total NaN in row 17872 : 2
 Total NaN in row 17873 : 0
 Total NaN in row 17874 : 0
 Total NaN in row 17875 : 1
 Total NaN in row 17876 : 0
 Total NaN in row 17877 : 1
 Total NaN in row 17878 : 2
 Total NaN in row 17879 : 0
 Total NaN in row 17880 : 0
 Total NaN in row 17881 : 0
 Total NaN in row 17882 : 2
 Total NaN in row 17883 : 1
 Total NaN in row 17884 : 3
 Total NaN in row 17885 : 0
 Total NaN in row 17886 : 0
 Total NaN in row 17887 : 1
 Total NaN in row 17888 : 1
 Total NaN in row 17889 : 2
 Total NaN in row 17890 : 1
 Total NaN in row 17891 : 1
 Total NaN in row 17892 : 2
 Total NaN in row 17893 : 0
 Total NaN in row 17894 : 1
 Total NaN in row 17895 : 2
 Total NaN in row 17896 : 0
 Total NaN in row 17897 : 0
 Total NaN in row 17898 : 0
 Total NaN in row 17899 : 0
 Total NaN in row 17900 : 0
 Total NaN in row 17901 : 0
 Total NaN in row 17902 : 0
 Total NaN in row 17903 : 2
 Total NaN in row 17904 : 1
 Total NaN in row 17905 : 0
 Total NaN in row 17906 : 2
 Total NaN in row 17907 : 0
 Total NaN in row 17908 : 0
 Total NaN in row 17909 : 1
 Total NaN in row 17910 : 1
 Total NaN in row 17911 : 1
 Total NaN in row 17912 : 0
 Total NaN in row 17913 : 2
 Total NaN in row 17914 : 1
 Total NaN in row 17915 : 1
 Total NaN in row 17916 : 0
 Total NaN in row 17917 : 0
 Total NaN in row 17918 : 1
 Total NaN in row 17919 : 0
 Total NaN in row 17920 : 0
 Total NaN in row 17921 : 0
 Total NaN in row 17922 : 2
 Total NaN in row 17923 : 1
 Total NaN in row 17924 : 1
 Total NaN in row 17925 : 2
 Total NaN in row 17926 : 9
 Total NaN in row 17927 : 1
 Total NaN in row 17928 : 2
 Total NaN in row 17929 : 1
 Total NaN in row 17930 : 0
 Total NaN in row 17931 : 1
 Total NaN in row 17932 : 1
 Total NaN in row 17933 : 0
 Total NaN in row 17934 : 2
 Total NaN in row 17935 : 9
 Total NaN in row 17936 : 0
 Total NaN in row 17937 : 2
 Total NaN in row 17938 : 0
 Total NaN in row 17939 : 2
 Total NaN in row 17940 : 2
 Total NaN in row 17941 : 2
 Total NaN in row 17942 : 2
 Total NaN in row 17943 : 9
 Total NaN in row 17944 : 9
 Total NaN in row 17945 : 2
 Total NaN in row 17946 : 2
 Total NaN in row 17947 : 2
 Total NaN in row 17948 : 2
 Total NaN in row 17949 : 1
 Total NaN in row 17950 : 0
 Total NaN in row 17951 : 2
 Total NaN in row 17952 : 9
 Total NaN in row 17953 : 0
 Total NaN in row 17954 : 0
 Total NaN in row 17955 : 9
 Total NaN in row 17956 : 1
 Total NaN in row 17957 : 2
 Total NaN in row 17958 : 0
 Total NaN in row 17959 : 10
 Total NaN in row 17960 : 2
 Total NaN in row 17961 : 10
 Total NaN in row 17962 : 0
 Total NaN in row 17963 : 0
 Total NaN in row 17964 : 2
 Total NaN in row 17965 : 3
 Total NaN in row 17966 : 9
 Total NaN in row 17967 : 2
 Total NaN in row 17968 : 10
 Total NaN in row 17969 : 2
 Total NaN in row 17970 : 0
 Total NaN in row 17971 : 2
 Total NaN in row 17972 : 9
 Total NaN in row 17973 : 0
 Total NaN in row 17974 : 2
 Total NaN in row 17975 : 9
 Total NaN in row 17976 : 2
 Total NaN in row 17977 : 2
 Total NaN in row 17978 : 2
 Total NaN in row 17979 : 2
 Total NaN in row 17980 : 2
 Total NaN in row 17981 : 2
 Total NaN in row 17982 : 1
 Total NaN in row 17983 : 0
 Total NaN in row 17984 : 9
 Total NaN in row 17985 : 0
 Total NaN in row 17986 : 2
 Total NaN in row 17987 : 2
 Total NaN in row 17988 : 9
 Total NaN in row 17989 : 3
 Total NaN in row 17990 : 1
 Total NaN in row 17991 : 1
 Total NaN in row 17992 : 2
 Total NaN in row 17993 : 3
 Total NaN in row 17994 : 0
 Total NaN in row 17995 : 3
 Total NaN in row 17996 : 0
 Total NaN in row 17997 : 2
 Total NaN in row 17998 : 1
 Total NaN in row 17999 : 3
 Total NaN in row 18000 : 2
 Total NaN in row 18001 : 3
 Total NaN in row 18002 : 2
 Total NaN in row 18003 : 1
 Total NaN in row 18004 : 0
 Total NaN in row 18005 : 1
 Total NaN in row 18006 : 2
 Total NaN in row 18007 : 2
 Total NaN in row 18008 : 0
 Total NaN in row 18009 : 0
 Total NaN in row 18010 : 9
 Total NaN in row 18011 : 3
 Total NaN in row 18012 : 9
 Total NaN in row 18013 : 2
 Total NaN in row 18014 : 1
 Total NaN in row 18015 : 1
 Total NaN in row 18016 : 2
 Total NaN in row 18017 : 2
 Total NaN in row 18018 : 1
 Total NaN in row 18019 : 0
 Total NaN in row 18020 : 0
 Total NaN in row 18021 : 2
 Total NaN in row 18022 : 0
 Total NaN in row 18023 : 0
 Total NaN in row 18024 : 2
 Total NaN in row 18025 : 9
 Total NaN in row 18026 : 0
 Total NaN in row 18027 : 9
 Total NaN in row 18028 : 9
 Total NaN in row 18029 : 0
 Total NaN in row 18030 : 2
 Total NaN in row 18031 : 2
 Total NaN in row 18032 : 2
 Total NaN in row 18033 : 0
 Total NaN in row 18034 : 2
 Total NaN in row 18035 : 0
 Total NaN in row 18036 : 0
 Total NaN in row 18037 : 2
 Total NaN in row 18038 : 2
 Total NaN in row 18039 : 3
 Total NaN in row 18040 : 0
 Total NaN in row 18041 : 1
 Total NaN in row 18042 : 1
 Total NaN in row 18043 : 2
 Total NaN in row 18044 : 9
 Total NaN in row 18045 : 0
 Total NaN in row 18046 : 10
 Total NaN in row 18047 : 2
 Total NaN in row 18048 : 2
 Total NaN in row 18049 : 2
 Total NaN in row 18050 : 2
 Total NaN in row 18051 : 2
 Total NaN in row 18052 : 2
 Total NaN in row 18053 : 9
 Total NaN in row 18054 : 9
 Total NaN in row 18055 : 3
 Total NaN in row 18056 : 2
 Total NaN in row 18057 : 0
 Total NaN in row 18058 : 2
 Total NaN in row 18059 : 2
 Total NaN in row 18060 : 0
 Total NaN in row 18061 : 2
 Total NaN in row 18062 : 0
 Total NaN in row 18063 : 2
 Total NaN in row 18064 : 0
 Total NaN in row 18065 : 0
 Total NaN in row 18066 : 1
 Total NaN in row 18067 : 1
 Total NaN in row 18068 : 0
 Total NaN in row 18069 : 1
 Total NaN in row 18070 : 2
 Total NaN in row 18071 : 0
 Total NaN in row 18072 : 0
 Total NaN in row 18073 : 0
 Total NaN in row 18074 : 1
 Total NaN in row 18075 : 2
 Total NaN in row 18076 : 7
 Total NaN in row 18077 : 0
 Total NaN in row 18078 : 21
 Total NaN in row 18079 : 9
 Total NaN in row 18080 : 0
 Total NaN in row 18081 : 0
 Total NaN in row 18082 : 3
 Total NaN in row 18083 : 0
 Total NaN in row 18084 : 9
 Total NaN in row 18085 : 0
 Total NaN in row 18086 : 1
 Total NaN in row 18087 : 9
 Total NaN in row 18088 : 2
 Total NaN in row 18089 : 1
 Total NaN in row 18090 : 0
 Total NaN in row 18091 : 2
 Total NaN in row 18092 : 2
 Total NaN in row 18093 : 3
 Total NaN in row 18094 : 2
 Total NaN in row 18095 : 0
 Total NaN in row 18096 : 1
 Total NaN in row 18097 : 2
 Total NaN in row 18098 : 0
 Total NaN in row 18099 : 2
 Total NaN in row 18100 : 0
 Total NaN in row 18101 : 1
 Total NaN in row 18102 : 0
 Total NaN in row 18103 : 0
 Total NaN in row 18104 : 2

 Total NaN in row 18105 : 2
 Total NaN in row 18106 : 2
 Total NaN in row 18107 : 2
 Total NaN in row 18108 : 1
 Total NaN in row 18109 : 1
 Total NaN in row 18110 : 0
 Total NaN in row 18111 : 0
 Total NaN in row 18112 : 9
 Total NaN in row 18113 : 1
 Total NaN in row 18114 : 0
 Total NaN in row 18115 : 2
 Total NaN in row 18116 : 0
 Total NaN in row 18117 : 3
 Total NaN in row 18118 : 2
 Total NaN in row 18119 : 1
 Total NaN in row 18120 : 0
 Total NaN in row 18121 : 0
 Total NaN in row 18122 : 1
 Total NaN in row 18123 : 2
 Total NaN in row 18124 : 1
 Total NaN in row 18125 : 2
 Total NaN in row 18126 : 2
 Total NaN in row 18127 : 0
 Total NaN in row 18128 : 2
 Total NaN in row 18129 : 2
 Total NaN in row 18130 : 0
 Total NaN in row 18131 : 0
 Total NaN in row 18132 : 10
 Total NaN in row 18133 : 2
 Total NaN in row 18134 : 2
 Total NaN in row 18135 : 2
 Total NaN in row 18136 : 2
 Total NaN in row 18137 : 9
 Total NaN in row 18138 : 1
 Total NaN in row 18139 : 2
 Total NaN in row 18140 : 2
 Total NaN in row 18141 : 0
 Total NaN in row 18142 : 1
 Total NaN in row 18143 : 2
 Total NaN in row 18144 : 1
 Total NaN in row 18145 : 0
 Total NaN in row 18146 : 2
 Total NaN in row 18147 : 0
 Total NaN in row 18148 : 0
 Total NaN in row 18149 : 21
 Total NaN in row 18150 : 0
 Total NaN in row 18151 : 1
 Total NaN in row 18152 : 3
 Total NaN in row 18153 : 2
 Total NaN in row 18154 : 9
 Total NaN in row 18155 : 1
 Total NaN in row 18156 : 0
 Total NaN in row 18157 : 0
 Total NaN in row 18158 : 1
 Total NaN in row 18159 : 3
 Total NaN in row 18160 : 0
 Total NaN in row 18161 : 0
 Total NaN in row 18162 : 2
 Total NaN in row 18163 : 2
 Total NaN in row 18164 : 0
 Total NaN in row 18165 : 1
 Total NaN in row 18166 : 2
 Total NaN in row 18167 : 0
 Total NaN in row 18168 : 2
 Total NaN in row 18169 : 0
 Total NaN in row 18170 : 3
 Total NaN in row 18171 : 3
 Total NaN in row 18172 : 0
 Total NaN in row 18173 : 0
 Total NaN in row 18174 : 2
 Total NaN in row 18175 : 0
 Total NaN in row 18176 : 0
 Total NaN in row 18177 : 3
 Total NaN in row 18178 : 3
 Total NaN in row 18179 : 9
 Total NaN in row 18180 : 1
 Total NaN in row 18181 : 0
 Total NaN in row 18182 : 2
 Total NaN in row 18183 : 0
 Total NaN in row 18184 : 0
 Total NaN in row 18185 : 3
 Total NaN in row 18186 : 2
 Total NaN in row 18187 : 1
 Total NaN in row 18188 : 0
 Total NaN in row 18189 : 0
 Total NaN in row 18190 : 0
 Total NaN in row 18191 : 0
 Total NaN in row 18192 : 2
 Total NaN in row 18193 : 2
 Total NaN in row 18194 : 2
 Total NaN in row 18195 : 2
 Total NaN in row 18196 : 1
 Total NaN in row 18197 : 0
 Total NaN in row 18198 : 0
 Total NaN in row 18199 : 2
 Total NaN in row 18200 : 2
 Total NaN in row 18201 : 2
 Total NaN in row 18202 : 0
 Total NaN in row 18203 : 2
 Total NaN in row 18204 : 2
 Total NaN in row 18205 : 1
 Total NaN in row 18206 : 3
 Total NaN in row 18207 : 2
 Total NaN in row 18208 : 9
 Total NaN in row 18209 : 2
 Total NaN in row 18210 : 1
 Total NaN in row 18211 : 0
 Total NaN in row 18212 : 1
 Total NaN in row 18213 : 1
 Total NaN in row 18214 : 2
 Total NaN in row 18215 : 1
 Total NaN in row 18216 : 2
 Total NaN in row 18217 : 0
 Total NaN in row 18218 : 0
 Total NaN in row 18219 : 2
 Total NaN in row 18220 : 2
 Total NaN in row 18221 : 3
 Total NaN in row 18222 : 0
 Total NaN in row 18223 : 9
 Total NaN in row 18224 : 2
 Total NaN in row 18225 : 2
 Total NaN in row 18226 : 2
 Total NaN in row 18227 : 0
 Total NaN in row 18228 : 2
 Total NaN in row 18229 : 0
 Total NaN in row 18230 : 2
 Total NaN in row 18231 : 1
 Total NaN in row 18232 : 0
 Total NaN in row 18233 : 2
 Total NaN in row 18234 : 2
 Total NaN in row 18235 : 0
 Total NaN in row 18236 : 2
 Total NaN in row 18237 : 1
 Total NaN in row 18238 : 2
 Total NaN in row 18239 : 2
 Total NaN in row 18240 : 0
 Total NaN in row 18241 : 0
 Total NaN in row 18242 : 0
 Total NaN in row 18243 : 2
 Total NaN in row 18244 : 9
 Total NaN in row 18245 : 2
 Total NaN in row 18246 : 2
 Total NaN in row 18247 : 9
 Total NaN in row 18248 : 1
 Total NaN in row 18249 : 3
 Total NaN in row 18250 : 2
 Total NaN in row 18251 : 9
 Total NaN in row 18252 : 21
 Total NaN in row 18253 : 0
 Total NaN in row 18254 : 0
 Total NaN in row 18255 : 2
 Total NaN in row 18256 : 0
 Total NaN in row 18257 : 0
 Total NaN in row 18258 : 3
 Total NaN in row 18259 : 0
 Total NaN in row 18260 : 0
 Total NaN in row 18261 : 2
 Total NaN in row 18262 : 0
 Total NaN in row 18263 : 0
 Total NaN in row 18264 : 9
 Total NaN in row 18265 : 0
 Total NaN in row 18266 : 0
 Total NaN in row 18267 : 1
 Total NaN in row 18268 : 10
 Total NaN in row 18269 : 0
 Total NaN in row 18270 : 9
 Total NaN in row 18271 : 9
 Total NaN in row 18272 : 7
 Total NaN in row 18273 : 0
 Total NaN in row 18274 : 2
 Total NaN in row 18275 : 9
 Total NaN in row 18276 : 9
 Total NaN in row 18277 : 0
 Total NaN in row 18278 : 0
 Total NaN in row 18279 : 9
 Total NaN in row 18280 : 2
 Total NaN in row 18281 : 2
 Total NaN in row 18282 : 9
 Total NaN in row 18283 : 1
 Total NaN in row 18284 : 1
 Total NaN in row 18285 : 2
 Total NaN in row 18286 : 0
 Total NaN in row 18287 : 2
 Total NaN in row 18288 : 0
 Total NaN in row 18289 : 2
 Total NaN in row 18290 : 0
 Total NaN in row 18291 : 2
 Total NaN in row 18292 : 1
 Total NaN in row 18293 : 0
 Total NaN in row 18294 : 2
 Total NaN in row 18295 : 2
 Total NaN in row 18296 : 2
 Total NaN in row 18297 : 0
 Total NaN in row 18298 : 1
 Total NaN in row 18299 : 2
 Total NaN in row 18300 : 3
 Total NaN in row 18301 : 1
 Total NaN in row 18302 : 0
 Total NaN in row 18303 : 3
 Total NaN in row 18304 : 9
 Total NaN in row 18305 : 2
 Total NaN in row 18306 : 1
 Total NaN in row 18307 : 2
 Total NaN in row 18308 : 1
 Total NaN in row 18309 : 2
 Total NaN in row 18310 : 3
 Total NaN in row 18311 : 9
 Total NaN in row 18312 : 2
 Total NaN in row 18313 : 2
 Total NaN in row 18314 : 9
 Total NaN in row 18315 : 2
 Total NaN in row 18316 : 1
 Total NaN in row 18317 : 1
 Total NaN in row 18318 : 0
 Total NaN in row 18319 : 1
 Total NaN in row 18320 : 2
 Total NaN in row 18321 : 0
 Total NaN in row 18322 : 2
 Total NaN in row 18323 : 2
 Total NaN in row 18324 : 9
 Total NaN in row 18325 : 0
 Total NaN in row 18326 : 9
 Total NaN in row 18327 : 9
 Total NaN in row 18328 : 2
 Total NaN in row 18329 : 9
 Total NaN in row 18330 : 0
 Total NaN in row 18331 : 0
 Total NaN in row 18332 : 0
 Total NaN in row 18333 : 9
 Total NaN in row 18334 : 0
 Total NaN in row 18335 : 1
 Total NaN in row 18336 : 2
 Total NaN in row 18337 : 1
 Total NaN in row 18338 : 9
 Total NaN in row 18339 : 0
 Total NaN in row 18340 : 0
 Total NaN in row 18341 : 0
 Total NaN in row 18342 : 0
 Total NaN in row 18343 : 1
 Total NaN in row 18344 : 3
 Total NaN in row 18345 : 9
 Total NaN in row 18346 : 0
 Total NaN in row 18347 : 2
 Total NaN in row 18348 : 0
 Total NaN in row 18349 : 2
 Total NaN in row 18350 : 2
 Total NaN in row 18351 : 9
 Total NaN in row 18352 : 0
 Total NaN in row 18353 : 10
 Total NaN in row 18354 : 3
 Total NaN in row 18355 : 2
 Total NaN in row 18356 : 2
 Total NaN in row 18357 : 0
 Total NaN in row 18358 : 0
 Total NaN in row 18359 : 2
 Total NaN in row 18360 : 2
 Total NaN in row 18361 : 3
 Total NaN in row 18362 : 9
 Total NaN in row 18363 : 0
 Total NaN in row 18364 : 7
 Total NaN in row 18365 : 1
 Total NaN in row 18366 : 3
 Total NaN in row 18367 : 0
 Total NaN in row 18368 : 3
 Total NaN in row 18369 : 9
 Total NaN in row 18370 : 1
 Total NaN in row 18371 : 3
 Total NaN in row 18372 : 1
 Total NaN in row 18373 : 9
 Total NaN in row 18374 : 1
 Total NaN in row 18375 : 21
 Total NaN in row 18376 : 2
 Total NaN in row 18377 : 0
 Total NaN in row 18378 : 2
 Total NaN in row 18379 : 2
 Total NaN in row 18380 : 2
 Total NaN in row 18381 : 3
 Total NaN in row 18382 : 0
 Total NaN in row 18383 : 1
 Total NaN in row 18384 : 2
 Total NaN in row 18385 : 2
 Total NaN in row 18386 : 1
 Total NaN in row 18387 : 0
 Total NaN in row 18388 : 2
 Total NaN in row 18389 : 1
 Total NaN in row 18390 : 2
 Total NaN in row 18391 : 0
 Total NaN in row 18392 : 1
 Total NaN in row 18393 : 3
 Total NaN in row 18394 : 1
 Total NaN in row 18395 : 1
 Total NaN in row 18396 : 0
 Total NaN in row 18397 : 0
 Total NaN in row 18398 : 9
 Total NaN in row 18399 : 1
 Total NaN in row 18400 : 0
 Total NaN in row 18401 : 2
 Total NaN in row 18402 : 2
 Total NaN in row 18403 : 1
 Total NaN in row 18404 : 1
 Total NaN in row 18405 : 2

 Total NaN in row 18406 : 2
 Total NaN in row 18407 : 2
 Total NaN in row 18408 : 3
 Total NaN in row 18409 : 3
 Total NaN in row 18410 : 2
 Total NaN in row 18411 : 2
 Total NaN in row 18412 : 0
 Total NaN in row 18413 : 0
 Total NaN in row 18414 : 8
 Total NaN in row 18415 : 0
 Total NaN in row 18416 : 0
 Total NaN in row 18417 : 2
 Total NaN in row 18418 : 2
 Total NaN in row 18419 : 10
 Total NaN in row 18420 : 0
 Total NaN in row 18421 : 9
 Total NaN in row 18422 : 9
 Total NaN in row 18423 : 0
 Total NaN in row 18424 : 2
 Total NaN in row 18425 : 0
 Total NaN in row 18426 : 2
 Total NaN in row 18427 : 3
 Total NaN in row 18428 : 2
 Total NaN in row 18429 : 2
 Total NaN in row 18430 : 2
 Total NaN in row 18431 : 0
 Total NaN in row 18432 : 0
 Total NaN in row 18433 : 2
 Total NaN in row 18434 : 2
 Total NaN in row 18435 : 0
 Total NaN in row 18436 : 0
 Total NaN in row 18437 : 1
 Total NaN in row 18438 : 1
 Total NaN in row 18439 : 2
 Total NaN in row 18440 : 9
 Total NaN in row 18441 : 2
 Total NaN in row 18442 : 0
 Total NaN in row 18443 : 9
 Total NaN in row 18444 : 2
 Total NaN in row 18445 : 2
 Total NaN in row 18446 : 2
 Total NaN in row 18447 : 0
 Total NaN in row 18448 : 9
 Total NaN in row 18449 : 0
 Total NaN in row 18450 : 1
 Total NaN in row 18451 : 0
 Total NaN in row 18452 : 2
 Total NaN in row 18453 : 2
 Total NaN in row 18454 : 1
 Total NaN in row 18455 : 0
 Total NaN in row 18456 : 2
 Total NaN in row 18457 : 2
 Total NaN in row 18458 : 3
 Total NaN in row 18459 : 3
 Total NaN in row 18460 : 2
 Total NaN in row 18461 : 2
 Total NaN in row 18462 : 2
 Total NaN in row 18463 : 2
 Total NaN in row 18464 : 0
 Total NaN in row 18465 : 2
 Total NaN in row 18466 : 3
 Total NaN in row 18467 : 0
 Total NaN in row 18468 : 3
 Total NaN in row 18469 : 0
 Total NaN in row 18470 : 1
 Total NaN in row 18471 : 2
 Total NaN in row 18472 : 1
 Total NaN in row 18473 : 2
 Total NaN in row 18474 : 0
 Total NaN in row 18475 : 0
 Total NaN in row 18476 : 2
 Total NaN in row 18477 : 21
 Total NaN in row 18478 : 2
 Total NaN in row 18479 : 1
 Total NaN in row 18480 : 9
 Total NaN in row 18481 : 9
 Total NaN in row 18482 : 0
 Total NaN in row 18483 : 0
 Total NaN in row 18484 : 2
 Total NaN in row 18485 : 3
 Total NaN in row 18486 : 0
 Total NaN in row 18487 : 2
 Total NaN in row 18488 : 1
 Total NaN in row 18489 : 9
 Total NaN in row 18490 : 2
 Total NaN in row 18491 : 9
 Total NaN in row 18492 : 2
 Total NaN in row 18493 : 0
 Total NaN in row 18494 : 0
 Total NaN in row 18495 : 1
 Total NaN in row 18496 : 9
 Total NaN in row 18497 : 9
 Total NaN in row 18498 : 0
 Total NaN in row 18499 : 0
 Total NaN in row 18500 : 0
 Total NaN in row 18501 : 1
 Total NaN in row 18502 : 2
 Total NaN in row 18503 : 0
 Total NaN in row 18504 : 1
 Total NaN in row 18505 : 0
 Total NaN in row 18506 : 9
 Total NaN in row 18507 : 0
 Total NaN in row 18508 : 0
 Total NaN in row 18509 : 2
 Total NaN in row 18510 : 0
 Total NaN in row 18511 : 1
 Total NaN in row 18512 : 2
 Total NaN in row 18513 : 1
 Total NaN in row 18514 : 0
 Total NaN in row 18515 : 9
 Total NaN in row 18516 : 3
 Total NaN in row 18517 : 9
 Total NaN in row 18518 : 7
 Total NaN in row 18519 : 2
 Total NaN in row 18520 : 2
 Total NaN in row 18521 : 0
 Total NaN in row 18522 : 2
 Total NaN in row 18523 : 2
 Total NaN in row 18524 : 1
 Total NaN in row 18525 : 2
 Total NaN in row 18526 : 2
 Total NaN in row 18527 : 0
 Total NaN in row 18528 : 3
 Total NaN in row 18529 : 0
 Total NaN in row 18530 : 0
 Total NaN in row 18531 : 1
 Total NaN in row 18532 : 0
 Total NaN in row 18533 : 0
 Total NaN in row 18534 : 1
 Total NaN in row 18535 : 9
 Total NaN in row 18536 : 0
 Total NaN in row 18537 : 1
 Total NaN in row 18538 : 0
 Total NaN in row 18539 : 0
 Total NaN in row 18540 : 0
 Total NaN in row 18541 : 2
 Total NaN in row 18542 : 2
 Total NaN in row 18543 : 0
 Total NaN in row 18544 : 0
 Total NaN in row 18545 : 0
 Total NaN in row 18546 : 1
 Total NaN in row 18547 : 1
 Total NaN in row 18548 : 21
 Total NaN in row 18549 : 1
 Total NaN in row 18550 : 1
 Total NaN in row 18551 : 1
 Total NaN in row 18552 : 0
 Total NaN in row 18553 : 3
 Total NaN in row 18554 : 1
 Total NaN in row 18555 : 2
 Total NaN in row 18556 : 1
 Total NaN in row 18557 : 2
 Total NaN in row 18558 : 0
 Total NaN in row 18559 : 0
 Total NaN in row 18560 : 2
 Total NaN in row 18561 : 0
 Total NaN in row 18562 : 0
 Total NaN in row 18563 : 2
 Total NaN in row 18564 : 0
 Total NaN in row 18565 : 0
 Total NaN in row 18566 : 9
 Total NaN in row 18567 : 2
 Total NaN in row 18568 : 2
 Total NaN in row 18569 : 2
 Total NaN in row 18570 : 1
 Total NaN in row 18571 : 2
 Total NaN in row 18572 : 10
 Total NaN in row 18573 : 0
 Total NaN in row 18574 : 0
 Total NaN in row 18575 : 10
 Total NaN in row 18576 : 0
 Total NaN in row 18577 : 1
 Total NaN in row 18578 : 3
 Total NaN in row 18579 : 0
 Total NaN in row 18580 : 1
 Total NaN in row 18581 : 1
 Total NaN in row 18582 : 2
 Total NaN in row 18583 : 2
 Total NaN in row 18584 : 1
 Total NaN in row 18585 : 3
 Total NaN in row 18586 : 1
 Total NaN in row 18587 : 2
 Total NaN in row 18588 : 1
 Total NaN in row 18589 : 2
 Total NaN in row 18590 : 2
 Total NaN in row 18591 : 0
 Total NaN in row 18592 : 2
 Total NaN in row 18593 : 0
 Total NaN in row 18594 : 0
 Total NaN in row 18595 : 0
 Total NaN in row 18596 : 9
 Total NaN in row 18597 : 3
 Total NaN in row 18598 : 2
 Total NaN in row 18599 : 0
 Total NaN in row 18600 : 0
 Total NaN in row 18601 : 1
 Total NaN in row 18602 : 0
 Total NaN in row 18603 : 2
 Total NaN in row 18604 : 2
 Total NaN in row 18605 : 0
 Total NaN in row 18606 : 0
 Total NaN in row 18607 : 0
 Total NaN in row 18608 : 2
 Total NaN in row 18609 : 10
 Total NaN in row 18610 : 0
 Total NaN in row 18611 : 0
 Total NaN in row 18612 : 0
 Total NaN in row 18613 : 0
 Total NaN in row 18614 : 2
 Total NaN in row 18615 : 2
 Total NaN in row 18616 : 2
 Total NaN in row 18617 : 0
 Total NaN in row 18618 : 2
 Total NaN in row 18619 : 0
 Total NaN in row 18620 : 0
 Total NaN in row 18621 : 10
 Total NaN in row 18622 : 0
 Total NaN in row 18623 : 2
 Total NaN in row 18624 : 2
 Total NaN in row 18625 : 2
 Total NaN in row 18626 : 2
 Total NaN in row 18627 : 2
 Total NaN in row 18628 : 0
 Total NaN in row 18629 : 0
 Total NaN in row 18630 : 1
 Total NaN in row 18631 : 13
 Total NaN in row 18632 : 0
 Total NaN in row 18633 : 0
 Total NaN in row 18634 : 2
 Total NaN in row 18635 : 9
 Total NaN in row 18636 : 3
 Total NaN in row 18637 : 0
 Total NaN in row 18638 : 0
 Total NaN in row 18639 : 2
 Total NaN in row 18640 : 0
 Total NaN in row 18641 : 1
 Total NaN in row 18642 : 0
 Total NaN in row 18643 : 10
 Total NaN in row 18644 : 0
 Total NaN in row 18645 : 0
 Total NaN in row 18646 : 3
 Total NaN in row 18647 : 9
 Total NaN in row 18648 : 1
 Total NaN in row 18649 : 2
 Total NaN in row 18650 : 0
 Total NaN in row 18651 : 1
 Total NaN in row 18652 : 0
 Total NaN in row 18653 : 10
 Total NaN in row 18654 : 0
 Total NaN in row 18655 : 2
 Total NaN in row 18656 : 2
 Total NaN in row 18657 : 2
 Total NaN in row 18658 : 9
 Total NaN in row 18659 : 2
 Total NaN in row 18660 : 1
 Total NaN in row 18661 : 1
 Total NaN in row 18662 : 2
 Total NaN in row 18663 : 0
 Total NaN in row 18664 : 0
 Total NaN in row 18665 : 1
 Total NaN in row 18666 : 9
 Total NaN in row 18667 : 1
 Total NaN in row 18668 : 0
 Total NaN in row 18669 : 1
 Total NaN in row 18670 : 0
 Total NaN in row 18671 : 0
 Total NaN in row 18672 : 21
 Total NaN in row 18673 : 2
 Total NaN in row 18674 : 1
 Total NaN in row 18675 : 1
 Total NaN in row 18676 : 0
 Total NaN in row 18677 : 2
 Total NaN in row 18678 : 1
 Total NaN in row 18679 : 1
 Total NaN in row 18680 : 2
 Total NaN in row 18681 : 2
 Total NaN in row 18682 : 1
 Total NaN in row 18683 : 2
 Total NaN in row 18684 : 0
 Total NaN in row 18685 : 0
 Total NaN in row 18686 : 0
 Total NaN in row 18687 : 0
 Total NaN in row 18688 : 0
 Total NaN in row 18689 : 1
 Total NaN in row 18690 : 2
 Total NaN in row 18691 : 0
 Total NaN in row 18692 : 0
 Total NaN in row 18693 : 1
 Total NaN in row 18694 : 0
 Total NaN in row 18695 : 2
 Total NaN in row 18696 : 10
 Total NaN in row 18697 : 2
 Total NaN in row 18698 : 2
 Total NaN in row 18699 : 2
 Total NaN in row 18700 : 3
 Total NaN in row 18701 : 9
 Total NaN in row 18702 : 9
 Total NaN in row 18703 : 2
 Total NaN in row 18704 : 0
 Total NaN in row 18705 : 0
 Total NaN in row 18706 : 0
 Total NaN in row 18707 : 10
 Total NaN in row 18708 : 1
 Total NaN in row 18709 : 1
 Total NaN in row 18710 : 0
 Total NaN in row 18711 : 0
 Total NaN in row 18712 : 2
 Total NaN in row 18713 : 1
 Total NaN in row 18714 : 0
 Total NaN in row 18715 : 0
 Total NaN in row 18716 : 9
 Total NaN in row 18717 : 0
 Total NaN in row 18718 : 2
 Total NaN in row 18719 : 0
 Total NaN in row 18720 : 0
 Total NaN in row 18721 : 1
 Total NaN in row 18722 : 2
 Total NaN in row 18723 : 2
 Total NaN in row 18724 : 0
 Total NaN in row 18725 : 0
 Total NaN in row 18726 : 0
 Total NaN in row 18727 : 2
 Total NaN in row 18728 : 0
 Total NaN in row 18729 : 10
 Total NaN in row 18730 : 1
 Total NaN in row 18731 : 1
 Total NaN in row 18732 : 0
 Total NaN in row 18733 : 0
 Total NaN in row 18734 : 2
 Total NaN in row 18735 : 2
 Total NaN in row 18736 : 3
 Total NaN in row 18737 : 2
 Total NaN in row 18738 : 3
 Total NaN in row 18739 : 2
 Total NaN in row 18740 : 9
 Total NaN in row 18741 : 9
 Total NaN in row 18742 : 10
 Total NaN in row 18743 : 21
 Total NaN in row 18744 : 0
 Total NaN in row 18745 : 0
 Total NaN in row 18746 : 1
 Total NaN in row 18747 : 9
 Total NaN in row 18748 : 0
 Total NaN in row 18749 : 3
 Total NaN in row 18750 : 1
 Total NaN in row 18751 : 2
 Total NaN in row 18752 : 5
 Total NaN in row 18753 : 0
 Total NaN in row 18754 : 2
 Total NaN in row 18755 : 0
 Total NaN in row 18756 : 2
 Total NaN in row 18757 : 2
 Total NaN in row 18758 : 0
 Total NaN in row 18759 : 7
 Total NaN in row 18760 : 1
 Total NaN in row 18761 : 2
 Total NaN in row 18762 : 2
 Total NaN in row 18763 : 0
 Total NaN in row 18764 : 1
 Total NaN in row 18765 : 0
 Total NaN in row 18766 : 1
 Total NaN in row 18767 : 2
 Total NaN in row 18768 : 1
 Total NaN in row 18769 : 2
 Total NaN in row 18770 : 0
 Total NaN in row 18771 : 1
 Total NaN in row 18772 : 2
 Total NaN in row 18773 : 2
 Total NaN in row 18774 : 9
 Total NaN in row 18775 : 0
 Total NaN in row 18776 : 3
 Total NaN in row 18777 : 0
 Total NaN in row 18778 : 1
 Total NaN in row 18779 : 10
 Total NaN in row 18780 : 1
 Total NaN in row 18781 : 9
 Total NaN in row 18782 : 0
 Total NaN in row 18783 : 0
 Total NaN in row 18784 : 7
 Total NaN in row 18785 : 0
 Total NaN in row 18786 : 2
 Total NaN in row 18787 : 9
 Total NaN in row 18788 : 10
 Total NaN in row 18789 : 2
 Total NaN in row 18790 : 2
 Total NaN in row 18791 : 0
 Total NaN in row 18792 : 0
 Total NaN in row 18793 : 0
 Total NaN in row 18794 : 3
 Total NaN in row 18795 : 1
 Total NaN in row 18796 : 3
 Total NaN in row 18797 : 0
 Total NaN in row 18798 : 3
 Total NaN in row 18799 : 9
 Total NaN in row 18800 : 1
 Total NaN in row 18801 : 9
 Total NaN in row 18802 : 9
 Total NaN in row 18803 : 9
 Total NaN in row 18804 : 2
 Total NaN in row 18805 : 1
 Total NaN in row 18806 : 0
 Total NaN in row 18807 : 0
 Total NaN in row 18808 : 0
 Total NaN in row 18809 : 3
 Total NaN in row 18810 : 2
 Total NaN in row 18811 : 2
 Total NaN in row 18812 : 2
 Total NaN in row 18813 : 0
 Total NaN in row 18814 : 2
 Total NaN in row 18815 : 1
 Total NaN in row 18816 : 1
 Total NaN in row 18817 : 2
 Total NaN in row 18818 : 0
 Total NaN in row 18819 : 1
 Total NaN in row 18820 : 0
 Total NaN in row 18821 : 10

 Total NaN in row 18822 : 2
 Total NaN in row 18823 : 2
 Total NaN in row 18824 : 0
 Total NaN in row 18825 : 1
 Total NaN in row 18826 : 0
 Total NaN in row 18827 : 0
 Total NaN in row 18828 : 0
 Total NaN in row 18829 : 0
 Total NaN in row 18830 : 2
 Total NaN in row 18831 : 0
 Total NaN in row 18832 : 0
 Total NaN in row 18833 : 10
 Total NaN in row 18834 : 0
 Total NaN in row 18835 : 0
 Total NaN in row 18836 : 2
 Total NaN in row 18837 : 1
 Total NaN in row 18838 : 2
 Total NaN in row 18839 : 2
 Total NaN in row 18840 : 1
 Total NaN in row 18841 : 0
 Total NaN in row 18842 : 10
 Total NaN in row 18843 : 0
 Total NaN in row 18844 : 0
 Total NaN in row 18845 : 3
 Total NaN in row 18846 : 3
 Total NaN in row 18847 : 2
 Total NaN in row 18848 : 0
 Total NaN in row 18849 : 2
 Total NaN in row 18850 : 7
 Total NaN in row 18851 : 7
 Total NaN in row 18852 : 2
 Total NaN in row 18853 : 0
 Total NaN in row 18854 : 1
 Total NaN in row 18855 : 2
 Total NaN in row 18856 : 4
 Total NaN in row 18857 : 9
 Total NaN in row 18858 : 2
 Total NaN in row 18859 : 2
 Total NaN in row 18860 : 3
 Total NaN in row 18861 : 9
 Total NaN in row 18862 : 0
 Total NaN in row 18863 : 2
 Total NaN in row 18864 : 3
 Total NaN in row 18865 : 2
 Total NaN in row 18866 : 9
 Total NaN in row 18867 : 9
 Total NaN in row 18868 : 9
 Total NaN in row 18869 : 2
 Total NaN in row 18870 : 1
 Total NaN in row 18871 : 0
 Total NaN in row 18872 : 2
 Total NaN in row 18873 : 0
 Total NaN in row 18874 : 1
 Total NaN in row 18875 : 1
 Total NaN in row 18876 : 0
 Total NaN in row 18877 : 9
 Total NaN in row 18878 : 2
 Total NaN in row 18879 : 0
 Total NaN in row 18880 : 0
 Total NaN in row 18881 : 0
 Total NaN in row 18882 : 2
 Total NaN in row 18883 : 2
 Total NaN in row 18884 : 0
 Total NaN in row 18885 : 21
 Total NaN in row 18886 : 9
 Total NaN in row 18887 : 2
 Total NaN in row 18888 : 1
 Total NaN in row 18889 : 0
 Total NaN in row 18890 : 1
 Total NaN in row 18891 : 2
 Total NaN in row 18892 : 0
 Total NaN in row 18893 : 1
 Total NaN in row 18894 : 2
 Total NaN in row 18895 : 10
 Total NaN in row 18896 : 0
 Total NaN in row 18897 : 2
 Total NaN in row 18898 : 2
 Total NaN in row 18899 : 0
 Total NaN in row 18900 : 0
 Total NaN in row 18901 : 0
 Total NaN in row 18902 : 2
 Total NaN in row 18903 : 0
 Total NaN in row 18904 : 2
 Total NaN in row 18905 : 1
 Total NaN in row 18906 : 9
 Total NaN in row 18907 : 1
 Total NaN in row 18908 : 3
 Total NaN in row 18909 : 0
 Total NaN in row 18910 : 1
 Total NaN in row 18911 : 2
 Total NaN in row 18912 : 0
 Total NaN in row 18913 : 2
 Total NaN in row 18914 : 2
 Total NaN in row 18915 : 0
 Total NaN in row 18916 : 2
 Total NaN in row 18917 : 1
 Total NaN in row 18918 : 0
 Total NaN in row 18919 : 1
 Total NaN in row 18920 : 1
 Total NaN in row 18921 : 2
 Total NaN in row 18922 : 2
 Total NaN in row 18923 : 1
 Total NaN in row 18924 : 9
 Total NaN in row 18925 : 2
 Total NaN in row 18926 : 1
 Total NaN in row 18927 : 1
 Total NaN in row 18928 : 2
 Total NaN in row 18929 : 2
 Total NaN in row 18930 : 2
 Total NaN in row 18931 : 0
 Total NaN in row 18932 : 0
 Total NaN in row 18933 : 2
 Total NaN in row 18934 : 0
 Total NaN in row 18935 : 0
 Total NaN in row 18936 : 2
 Total NaN in row 18937 : 3
 Total NaN in row 18938 : 0
 Total NaN in row 18939 : 0
 Total NaN in row 18940 : 0
 Total NaN in row 18941 : 2
 Total NaN in row 18942 : 3
 Total NaN in row 18943 : 0
 Total NaN in row 18944 : 0
 Total NaN in row 18945 : 0
 Total NaN in row 18946 : 9
 Total NaN in row 18947 : 2
 Total NaN in row 18948 : 2
 Total NaN in row 18949 : 0
 Total NaN in row 18950 : 0
 Total NaN in row 18951 : 3
 Total NaN in row 18952 : 3
 Total NaN in row 18953 : 1
 Total NaN in row 18954 : 2
 Total NaN in row 18955 : 0
 Total NaN in row 18956 : 2
 Total NaN in row 18957 : 2
 Total NaN in row 18958 : 0
 Total NaN in row 18959 : 9
 Total NaN in row 18960 : 0
 Total NaN in row 18961 : 0
 Total NaN in row 18962 : 0
 Total NaN in row 18963 : 2
 Total NaN in row 18964 : 9
 Total NaN in row 18965 : 2
 Total NaN in row 18966 : 0
 Total NaN in row 18967 : 0
 Total NaN in row 18968 : 1
 Total NaN in row 18969 : 2
 Total NaN in row 18970 : 2
 Total NaN in row 18971 : 3
 Total NaN in row 18972 : 2
 Total NaN in row 18973 : 0
 Total NaN in row 18974 : 1
 Total NaN in row 18975 : 1
 Total NaN in row 18976 : 0
 Total NaN in row 18977 : 2
 Total NaN in row 18978 : 1
 Total NaN in row 18979 : 3
 Total NaN in row 18980 : 2
 Total NaN in row 18981 : 0
 Total NaN in row 18982 : 2
 Total NaN in row 18983 : 0
 Total NaN in row 18984 : 0
 Total NaN in row 18985 : 2
 Total NaN in row 18986 : 0
 Total NaN in row 18987 : 0
 Total NaN in row 18988 : 7
 Total NaN in row 18989 : 9
 Total NaN in row 18990 : 1
 Total NaN in row 18991 : 0
 Total NaN in row 18992 : 2
 Total NaN in row 18993 : 1
 Total NaN in row 18994 : 2
 Total NaN in row 18995 : 2
 Total NaN in row 18996 : 1
 Total NaN in row 18997 : 2
 Total NaN in row 18998 : 1
 Total NaN in row 18999 : 2
 Total NaN in row 19000 : 0
 Total NaN in row 19001 : 1
 Total NaN in row 19002 : 21
 Total NaN in row 19003 : 2
 Total NaN in row 19004 : 3
 Total NaN in row 19005 : 2
 Total NaN in row 19006 : 0
 Total NaN in row 19007 : 2
 Total NaN in row 19008 : 9
 Total NaN in row 19009 : 0
 Total NaN in row 19010 : 1
 Total NaN in row 19011 : 0
 Total NaN in row 19012 : 2
 Total NaN in row 19013 : 0
 Total NaN in row 19014 : 0
 Total NaN in row 19015 : 0
 Total NaN in row 19016 : 1
 Total NaN in row 19017 : 3
 Total NaN in row 19018 : 3
 Total NaN in row 19019 : 0
 Total NaN in row 19020 : 3
 Total NaN in row 19021 : 1
 Total NaN in row 19022 : 0
 Total NaN in row 19023 : 1
 Total NaN in row 19024 : 1
 Total NaN in row 19025 : 0
 Total NaN in row 19026 : 1
 Total NaN in row 19027 : 0
 Total NaN in row 19028 : 0
 Total NaN in row 19029 : 1
 Total NaN in row 19030 : 1
 Total NaN in row 19031 : 2
 Total NaN in row 19032 : 1
 Total NaN in row 19033 : 0
 Total NaN in row 19034 : 1
 Total NaN in row 19035 : 2
 Total NaN in row 19036 : 2
 Total NaN in row 19037 : 0
 Total NaN in row 19038 : 2
 Total NaN in row 19039 : 2
 Total NaN in row 19040 : 1
 Total NaN in row 19041 : 0
 Total NaN in row 19042 : 2
 Total NaN in row 19043 : 0
 Total NaN in row 19044 : 9
 Total NaN in row 19045 : 0
 Total NaN in row 19046 : 0
 Total NaN in row 19047 : 9
 Total NaN in row 19048 : 3
 Total NaN in row 19049 : 3
 Total NaN in row 19050 : 2
 Total NaN in row 19051 : 9
 Total NaN in row 19052 : 0
 Total NaN in row 19053 : 1
 Total NaN in row 19054 : 0
 Total NaN in row 19055 : 0
 Total NaN in row 19056 : 0
 Total NaN in row 19057 : 0
 Total NaN in row 19058 : 1
 Total NaN in row 19059 : 3
 Total NaN in row 19060 : 2
 Total NaN in row 19061 : 0
 Total NaN in row 19062 : 1
 Total NaN in row 19063 : 2
 Total NaN in row 19064 : 2
 Total NaN in row 19065 : 2
 Total NaN in row 19066 : 3
 Total NaN in row 19067 : 2
 Total NaN in row 19068 : 2
 Total NaN in row 19069 : 2
 Total NaN in row 19070 : 0
 Total NaN in row 19071 : 0
 Total NaN in row 19072 : 0
 Total NaN in row 19073 : 9
 Total NaN in row 19074 : 1
 Total NaN in row 19075 : 2
 Total NaN in row 19076 : 0
 Total NaN in row 19077 : 0
 Total NaN in row 19078 : 0
 Total NaN in row 19079 : 0
 Total NaN in row 19080 : 2
 Total NaN in row 19081 : 0
 Total NaN in row 19082 : 3
 Total NaN in row 19083 : 2
 Total NaN in row 19084 : 1
 Total NaN in row 19085 : 2
 Total NaN in row 19086 : 3
 Total NaN in row 19087 : 2
 Total NaN in row 19088 : 2
 Total NaN in row 19089 : 0
 Total NaN in row 19090 : 0
 Total NaN in row 19091 : 0
 Total NaN in row 19092 : 1
 Total NaN in row 19093 : 1
 Total NaN in row 19094 : 2
 Total NaN in row 19095 : 0
 Total NaN in row 19096 : 2
 Total NaN in row 19097 : 2
 Total NaN in row 19098 : 2
 Total NaN in row 19099 : 0
 Total NaN in row 19100 : 0
 Total NaN in row 19101 : 0
 Total NaN in row 19102 : 0
 Total NaN in row 19103 : 10
 Total NaN in row 19104 : 2
 Total NaN in row 19105 : 3
 Total NaN in row 19106 : 9
 Total NaN in row 19107 : 2
 Total NaN in row 19108 : 2
 Total NaN in row 19109 : 0
 Total NaN in row 19110 : 0
 Total NaN in row 19111 : 1
 Total NaN in row 19112 : 2
 Total NaN in row 19113 : 0
 Total NaN in row 19114 : 2
 Total NaN in row 19115 : 2
 Total NaN in row 19116 : 0
 Total NaN in row 19117 : 0
 Total NaN in row 19118 : 1
 Total NaN in row 19119 : 1
 Total NaN in row 19120 : 2
 Total NaN in row 19121 : 2
 Total NaN in row 19122 : 2
 Total NaN in row 19123 : 0
 Total NaN in row 19124 : 1
 Total NaN in row 19125 : 1
 Total NaN in row 19126 : 9
 Total NaN in row 19127 : 9

 Total NaN in row 19128 : 0
 Total NaN in row 19129 : 0
 Total NaN in row 19130 : 0
 Total NaN in row 19131 : 2
 Total NaN in row 19132 : 1
 Total NaN in row 19133 : 0
 Total NaN in row 19134 : 0
 Total NaN in row 19135 : 0
 Total NaN in row 19136 : 1
 Total NaN in row 19137 : 0
 Total NaN in row 19138 : 3
 Total NaN in row 19139 : 2
 Total NaN in row 19140 : 0
 Total NaN in row 19141 : 1
 Total NaN in row 19142 : 2
 Total NaN in row 19143 : 0
 Total NaN in row 19144 : 3
 Total NaN in row 19145 : 0
 Total NaN in row 19146 : 2
 Total NaN in row 19147 : 0
 Total NaN in row 19148 : 2
 Total NaN in row 19149 : 1
 Total NaN in row 19150 : 0
 Total NaN in row 19151 : 0
 Total NaN in row 19152 : 2
 Total NaN in row 19153 : 10
 Total NaN in row 19154 : 9
 Total NaN in row 19155 : 9
 Total NaN in row 19156 : 9
 Total NaN in row 19157 : 0
 Total NaN in row 19158 : 0
 Total NaN in row 19159 : 0
 Total NaN in row 19160 : 2
 Total NaN in row 19161 : 2
 Total NaN in row 19162 : 3
 Total NaN in row 19163 : 0
 Total NaN in row 19164 : 9
 Total NaN in row 19165 : 2
 Total NaN in row 19166 : 0
 Total NaN in row 19167 : 9
 Total NaN in row 19168 : 2
 Total NaN in row 19169 : 2
 Total NaN in row 19170 : 1
 Total NaN in row 19171 : 0
 Total NaN in row 19172 : 2
 Total NaN in row 19173 : 2
 Total NaN in row 19174 : 1
 Total NaN in row 19175 : 2
 Total NaN in row 19176 : 1
 Total NaN in row 19177 : 10
 Total NaN in row 19178 : 9
 Total NaN in row 19179 : 9
 Total NaN in row 19180 : 1
 Total NaN in row 19181 : 0
 Total NaN in row 19182 : 0
 Total NaN in row 19183 : 0
 Total NaN in row 19184 : 1
 Total NaN in row 19185 : 3
 Total NaN in row 19186 : 0
 Total NaN in row 19187 : 3
 Total NaN in row 19188 : 9
 Total NaN in row 19189 : 0
 Total NaN in row 19190 : 1
 Total NaN in row 19191 : 2
 Total NaN in row 19192 : 0
 Total NaN in row 19193 : 2
 Total NaN in row 19194 : 0
 Total NaN in row 19195 : 0
 Total NaN in row 19196 : 0
 Total NaN in row 19197 : 9
 Total NaN in row 19198 : 1
 Total NaN in row 19199 : 0
 Total NaN in row 19200 : 0
 Total NaN in row 19201 : 0
 Total NaN in row 19202 : 3
 Total NaN in row 19203 : 3
 Total NaN in row 19204 : 0
 Total NaN in row 19205 : 0
 Total NaN in row 19206 : 0
 Total NaN in row 19207 : 1
 Total NaN in row 19208 : 0
 Total NaN in row 19209 : 2
 Total NaN in row 19210 : 3
 Total NaN in row 19211 : 9
 Total NaN in row 19212 : 1
 Total NaN in row 19213 : 0
 Total NaN in row 19214 : 0
 Total NaN in row 19215 : 10
 Total NaN in row 19216 : 10
 Total NaN in row 19217 : 3
 Total NaN in row 19218 : 1
 Total NaN in row 19219 : 2
 Total NaN in row 19220 : 0
 Total NaN in row 19221 : 0
 Total NaN in row 19222 : 3
 Total NaN in row 19223 : 0
 Total NaN in row 19224 : 10
 Total NaN in row 19225 : 1
 Total NaN in row 19226 : 9
 Total NaN in row 19227 : 1
 Total NaN in row 19228 : 2
 Total NaN in row 19229 : 3
 Total NaN in row 19230 : 0
 Total NaN in row 19231 : 0
 Total NaN in row 19232 : 0
 Total NaN in row 19233 : 0
 Total NaN in row 19234 : 9
 Total NaN in row 19235 : 1
 Total NaN in row 19236 : 0
 Total NaN in row 19237 : 3
 Total NaN in row 19238 : 0
 Total NaN in row 19239 : 0
 Total NaN in row 19240 : 2
 Total NaN in row 19241 : 0
 Total NaN in row 19242 : 3
 Total NaN in row 19243 : 2
 Total NaN in row 19244 : 9
 Total NaN in row 19245 : 2
 Total NaN in row 19246 : 0
 Total NaN in row 19247 : 0
 Total NaN in row 19248 : 1
 Total NaN in row 19249 : 0
 Total NaN in row 19250 : 2
 Total NaN in row 19251 : 0
 Total NaN in row 19252 : 2
 Total NaN in row 19253 : 1
 Total NaN in row 19254 : 3
 Total NaN in row 19255 : 1
 Total NaN in row 19256 : 3
 Total NaN in row 19257 : 9
 Total NaN in row 19258 : 0
 Total NaN in row 19259 : 1
 Total NaN in row 19260 : 0
 Total NaN in row 19261 : 0
 Total NaN in row 19262 : 1
 Total NaN in row 19263 : 2
 Total NaN in row 19264 : 1
 Total NaN in row 19265 : 2
 Total NaN in row 19266 : 1
 Total NaN in row 19267 : 2
 Total NaN in row 19268 : 0
 Total NaN in row 19269 : 2
 Total NaN in row 19270 : 0
 Total NaN in row 19271 : 0
 Total NaN in row 19272 : 0
 Total NaN in row 19273 : 3
 Total NaN in row 19274 : 1
 Total NaN in row 19275 : 0
 Total NaN in row 19276 : 2
 Total NaN in row 19277 : 3
 Total NaN in row 19278 : 3
 Total NaN in row 19279 : 0
 Total NaN in row 19280 : 2
 Total NaN in row 19281 : 1
 Total NaN in row 19282 : 2
 Total NaN in row 19283 : 3
 Total NaN in row 19284 : 0
 Total NaN in row 19285 : 0
 Total NaN in row 19286 : 0
 Total NaN in row 19287 : 9
 Total NaN in row 19288 : 21
 Total NaN in row 19289 : 1
 Total NaN in row 19290 : 0
 Total NaN in row 19291 : 2
 Total NaN in row 19292 : 2
 Total NaN in row 19293 : 0
 Total NaN in row 19294 : 2
 Total NaN in row 19295 : 2
 Total NaN in row 19296 : 2
 Total NaN in row 19297 : 2
 Total NaN in row 19298 : 2
 Total NaN in row 19299 : 0
 Total NaN in row 19300 : 1
 Total NaN in row 19301 : 9
 Total NaN in row 19302 : 0
 Total NaN in row 19303 : 0
 Total NaN in row 19304 : 2
 Total NaN in row 19305 : 0
 Total NaN in row 19306 : 0
 Total NaN in row 19307 : 0
 Total NaN in row 19308 : 0
 Total NaN in row 19309 : 2
 Total NaN in row 19310 : 2
 Total NaN in row 19311 : 2
 Total NaN in row 19312 : 2
 Total NaN in row 19313 : 0
 Total NaN in row 19314 : 9
 Total NaN in row 19315 : 1
 Total NaN in row 19316 : 2
 Total NaN in row 19317 : 0
 Total NaN in row 19318 : 2
 Total NaN in row 19319 : 0
 Total NaN in row 19320 : 0
 Total NaN in row 19321 : 9
 Total NaN in row 19322 : 0
 Total NaN in row 19323 : 2
 Total NaN in row 19324 : 0
 Total NaN in row 19325 : 0
 Total NaN in row 19326 : 2
 Total NaN in row 19327 : 1
 Total NaN in row 19328 : 0
 Total NaN in row 19329 : 0
 Total NaN in row 19330 : 3
 Total NaN in row 19331 : 1
 Total NaN in row 19332 : 2
 Total NaN in row 19333 : 0
 Total NaN in row 19334 : 1
 Total NaN in row 19335 : 0
 Total NaN in row 19336 : 0
 Total NaN in row 19337 : 2
 Total NaN in row 19338 : 0
 Total NaN in row 19339 : 3
 Total NaN in row 19340 : 0
 Total NaN in row 19341 : 2
 Total NaN in row 19342 : 1
 Total NaN in row 19343 : 0
 Total NaN in row 19344 : 3
 Total NaN in row 19345 : 0
 Total NaN in row 19346 : 0
 Total NaN in row 19347 : 0
 Total NaN in row 19348 : 2
 Total NaN in row 19349 : 0
 Total NaN in row 19350 : 1
 Total NaN in row 19351 : 2
 Total NaN in row 19352 : 2
 Total NaN in row 19353 : 2
 Total NaN in row 19354 : 3
 Total NaN in row 19355 : 0
 Total NaN in row 19356 : 3
 Total NaN in row 19357 : 1
 Total NaN in row 19358 : 1
 Total NaN in row 19359 : 1
 Total NaN in row 19360 : 3
 Total NaN in row 19361 : 0
 Total NaN in row 19362 : 0
 Total NaN in row 19363 : 0
 Total NaN in row 19364 : 2
 Total NaN in row 19365 : 1
 Total NaN in row 19366 : 0
 Total NaN in row 19367 : 9
 Total NaN in row 19368 : 0
 Total NaN in row 19369 : 2
 Total NaN in row 19370 : 2
 Total NaN in row 19371 : 0
 Total NaN in row 19372 : 2
 Total NaN in row 19373 : 9
 Total NaN in row 19374 : 3
 Total NaN in row 19375 : 9
 Total NaN in row 19376 : 0
 Total NaN in row 19377 : 1
 Total NaN in row 19378 : 2
 Total NaN in row 19379 : 2
 Total NaN in row 19380 : 9
 Total NaN in row 19381 : 3
 Total NaN in row 19382 : 0
 Total NaN in row 19383 : 10
 Total NaN in row 19384 : 9
 Total NaN in row 19385 : 2
 Total NaN in row 19386 : 9
 Total NaN in row 19387 : 0
 Total NaN in row 19388 : 2
 Total NaN in row 19389 : 2
 Total NaN in row 19390 : 1
 Total NaN in row 19391 : 0
 Total NaN in row 19392 : 0
 Total NaN in row 19393 : 2
 Total NaN in row 19394 : 10
 Total NaN in row 19395 : 10
 Total NaN in row 19396 : 1
 Total NaN in row 19397 : 2
 Total NaN in row 19398 : 2
 Total NaN in row 19399 : 0
 Total NaN in row 19400 : 2
 Total NaN in row 19401 : 2
 Total NaN in row 19402 : 2
 Total NaN in row 19403 : 0
 Total NaN in row 19404 : 0
 Total NaN in row 19405 : 1
 Total NaN in row 19406 : 0
 Total NaN in row 19407 : 2
 Total NaN in row 19408 : 0
 Total NaN in row 19409 : 10
 Total NaN in row 19410 : 2
 Total NaN in row 19411 : 0
 Total NaN in row 19412 : 2
 Total NaN in row 19413 : 2
 Total NaN in row 19414 : 9
 Total NaN in row 19415 : 1
 Total NaN in row 19416 : 0
 Total NaN in row 19417 : 10
 Total NaN in row 19418 : 1
 Total NaN in row 19419 : 1
 Total NaN in row 19420 : 2
 Total NaN in row 19421 : 9
 Total NaN in row 19422 : 9
 Total NaN in row 19423 : 2
 Total NaN in row 19424 : 10
 Total NaN in row 19425 : 0
 Total NaN in row 19426 : 2
 Total NaN in row 19427 : 0
 Total NaN in row 19428 : 2
 Total NaN in row 19429 : 0
 Total NaN in row 19430 : 2
 Total NaN in row 19431 : 1
 Total NaN in row 19432 : 9
 Total NaN in row 19433 : 0
 Total NaN in row 19434 : 0
 Total NaN in row 19435 : 1
 Total NaN in row 19436 : 0

 Total NaN in row 19437 : 0
 Total NaN in row 19438 : 2
 Total NaN in row 19439 : 0
 Total NaN in row 19440 : 4
 Total NaN in row 19441 : 2
 Total NaN in row 19442 : 3
 Total NaN in row 19443 : 9
 Total NaN in row 19444 : 1
 Total NaN in row 19445 : 2
 Total NaN in row 19446 : 10
 Total NaN in row 19447 : 1
 Total NaN in row 19448 : 0
 Total NaN in row 19449 : 1
 Total NaN in row 19450 : 0
 Total NaN in row 19451 : 0
 Total NaN in row 19452 : 1
 Total NaN in row 19453 : 1
 Total NaN in row 19454 : 0
 Total NaN in row 19455 : 2
 Total NaN in row 19456 : 0
 Total NaN in row 19457 : 1
 Total NaN in row 19458 : 2
 Total NaN in row 19459 : 2
 Total NaN in row 19460 : 2
 Total NaN in row 19461 : 9
 Total NaN in row 19462 : 1
 Total NaN in row 19463 : 2
 Total NaN in row 19464 : 9
 Total NaN in row 19465 : 0
 Total NaN in row 19466 : 2
 Total NaN in row 19467 : 0
 Total NaN in row 19468 : 0
 Total NaN in row 19469 : 3
 Total NaN in row 19470 : 10
 Total NaN in row 19471 : 0
 Total NaN in row 19472 : 2
 Total NaN in row 19473 : 0
 Total NaN in row 19474 : 0
 Total NaN in row 19475 : 2
 Total NaN in row 19476 : 10
 Total NaN in row 19477 : 2
 Total NaN in row 19478 : 9
 Total NaN in row 19479 : 3
 Total NaN in row 19480 : 2
 Total NaN in row 19481 : 3
 Total NaN in row 19482 : 2
 Total NaN in row 19483 : 0
 Total NaN in row 19484 : 1
 Total NaN in row 19485 : 0
 Total NaN in row 19486 : 0
 Total NaN in row 19487 : 2
 Total NaN in row 19488 : 0
 Total NaN in row 19489 : 1
 Total NaN in row 19490 : 2
 Total NaN in row 19491 : 0
 Total NaN in row 19492 : 2
 Total NaN in row 19493 : 10
 Total NaN in row 19494 : 0
 Total NaN in row 19495 : 9
 Total NaN in row 19496 : 0
 Total NaN in row 19497 : 9
 Total NaN in row 19498 : 9
 Total NaN in row 19499 : 0
 Total NaN in row 19500 : 2
 Total NaN in row 19501 : 0
 Total NaN in row 19502 : 2
 Total NaN in row 19503 : 2
 Total NaN in row 19504 : 9
 Total NaN in row 19505 : 2
 Total NaN in row 19506 : 1
 Total NaN in row 19507 : 3
 Total NaN in row 19508 : 1
 Total NaN in row 19509 : 1
 Total NaN in row 19510 : 7
 Total NaN in row 19511 : 1
 Total NaN in row 19512 : 3
 Total NaN in row 19513 : 1
 Total NaN in row 19514 : 9
 Total NaN in row 19515 : 0
 Total NaN in row 19516 : 2
 Total NaN in row 19517 : 2
 Total NaN in row 19518 : 2
 Total NaN in row 19519 : 1
 Total NaN in row 19520 : 1
 Total NaN in row 19521 : 0
 Total NaN in row 19522 : 3
 Total NaN in row 19523 : 2
 Total NaN in row 19524 : 2
 Total NaN in row 19525 : 2
 Total NaN in row 19526 : 0
 Total NaN in row 19527 : 9
 Total NaN in row 19528 : 2
 Total NaN in row 19529 : 10
 Total NaN in row 19530 : 2
 Total NaN in row 19531 : 9
 Total NaN in row 19532 : 9
 Total NaN in row 19533 : 0
 Total NaN in row 19534 : 2
 Total NaN in row 19535 : 0
 Total NaN in row 19536 : 2
 Total NaN in row 19537 : 1
 Total NaN in row 19538 : 0
 Total NaN in row 19539 : 0
 Total NaN in row 19540 : 1
 Total NaN in row 19541 : 9
 Total NaN in row 19542 : 3
 Total NaN in row 19543 : 0
 Total NaN in row 19544 : 2
 Total NaN in row 19545 : 1
 Total NaN in row 19546 : 0
 Total NaN in row 19547 : 0
 Total NaN in row 19548 : 0
 Total NaN in row 19549 : 1
 Total NaN in row 19550 : 0
 Total NaN in row 19551 : 2
 Total NaN in row 19552 : 1
 Total NaN in row 19553 : 0
 Total NaN in row 19554 : 0
 Total NaN in row 19555 : 9
 Total NaN in row 19556 : 0
 Total NaN in row 19557 : 2
 Total NaN in row 19558 : 0
 Total NaN in row 19559 : 2
 Total NaN in row 19560 : 2
 Total NaN in row 19561 : 2
 Total NaN in row 19562 : 9
 Total NaN in row 19563 : 2
 Total NaN in row 19564 : 2
 Total NaN in row 19565 : 0
 Total NaN in row 19566 : 2
 Total NaN in row 19567 : 2
 Total NaN in row 19568 : 0
 Total NaN in row 19569 : 2
 Total NaN in row 19570 : 0
 Total NaN in row 19571 : 1
 Total NaN in row 19572 : 0
 Total NaN in row 19573 : 2
 Total NaN in row 19574 : 10
 Total NaN in row 19575 : 3
 Total NaN in row 19576 : 1
 Total NaN in row 19577 : 0
 Total NaN in row 19578 : 2
 Total NaN in row 19579 : 3
 Total NaN in row 19580 : 0
 Total NaN in row 19581 : 0
 Total NaN in row 19582 : 0
 Total NaN in row 19583 : 10
 Total NaN in row 19584 : 3
 Total NaN in row 19585 : 1
 Total NaN in row 19586 : 2
 Total NaN in row 19587 : 0
 Total NaN in row 19588 : 2
 Total NaN in row 19589 : 3
 Total NaN in row 19590 : 2
 Total NaN in row 19591 : 3
 Total NaN in row 19592 : 0
 Total NaN in row 19593 : 2
 Total NaN in row 19594 : 3
 Total NaN in row 19595 : 0
 Total NaN in row 19596 : 1
 Total NaN in row 19597 : 2
 Total NaN in row 19598 : 2
 Total NaN in row 19599 : 0
 Total NaN in row 19600 : 2
 Total NaN in row 19601 : 0
 Total NaN in row 19602 : 9
 Total NaN in row 19603 : 2
 Total NaN in row 19604 : 1
 Total NaN in row 19605 : 2
 Total NaN in row 19606 : 1
 Total NaN in row 19607 : 2
 Total NaN in row 19608 : 1
 Total NaN in row 19609 : 1
 Total NaN in row 19610 : 1
 Total NaN in row 19611 : 0
 Total NaN in row 19612 : 4
 Total NaN in row 19613 : 2
 Total NaN in row 19614 : 0
 Total NaN in row 19615 : 0
 Total NaN in row 19616 : 2
 Total NaN in row 19617 : 0
 Total NaN in row 19618 : 0
 Total NaN in row 19619 : 1
 Total NaN in row 19620 : 0
 Total NaN in row 19621 : 3
 Total NaN in row 19622 : 0
 Total NaN in row 19623 : 1
 Total NaN in row 19624 : 1
 Total NaN in row 19625 : 3
 Total NaN in row 19626 : 1
 Total NaN in row 19627 : 2
 Total NaN in row 19628 : 0
 Total NaN in row 19629 : 3
 Total NaN in row 19630 : 2
 Total NaN in row 19631 : 2
 Total NaN in row 19632 : 0
 Total NaN in row 19633 : 0
 Total NaN in row 19634 : 1
 Total NaN in row 19635 : 1
 Total NaN in row 19636 : 1
 Total NaN in row 19637 : 2
 Total NaN in row 19638 : 0
 Total NaN in row 19639 : 1
 Total NaN in row 19640 : 0
 Total NaN in row 19641 : 2
 Total NaN in row 19642 : 21
 Total NaN in row 19643 : 0
 Total NaN in row 19644 : 2
 Total NaN in row 19645 : 3
 Total NaN in row 19646 : 2
 Total NaN in row 19647 : 2
 Total NaN in row 19648 : 0
 Total NaN in row 19649 : 0
 Total NaN in row 19650 : 0
 Total NaN in row 19651 : 0
 Total NaN in row 19652 : 1
 Total NaN in row 19653 : 2
 Total NaN in row 19654 : 2
 Total NaN in row 19655 : 2
 Total NaN in row 19656 : 10
 Total NaN in row 19657 : 9
 Total NaN in row 19658 : 0
 Total NaN in row 19659 : 0
 Total NaN in row 19660 : 2
 Total NaN in row 19661 : 2
 Total NaN in row 19662 : 9
 Total NaN in row 19663 : 0
 Total NaN in row 19664 : 5
 Total NaN in row 19665 : 0
 Total NaN in row 19666 : 9
 Total NaN in row 19667 : 0
 Total NaN in row 19668 : 9
 Total NaN in row 19669 : 1
 Total NaN in row 19670 : 2
 Total NaN in row 19671 : 0
 Total NaN in row 19672 : 0
 Total NaN in row 19673 : 2
 Total NaN in row 19674 : 3
 Total NaN in row 19675 : 0
 Total NaN in row 19676 : 0
 Total NaN in row 19677 : 1
 Total NaN in row 19678 : 2
 Total NaN in row 19679 : 1
 Total NaN in row 19680 : 2
 Total NaN in row 19681 : 1
 Total NaN in row 19682 : 1
 Total NaN in row 19683 : 0
 Total NaN in row 19684 : 1
 Total NaN in row 19685 : 2
 Total NaN in row 19686 : 9
 Total NaN in row 19687 : 0
 Total NaN in row 19688 : 1
 Total NaN in row 19689 : 9
 Total NaN in row 19690 : 9
 Total NaN in row 19691 : 3
 Total NaN in row 19692 : 2
 Total NaN in row 19693 : 3
 Total NaN in row 19694 : 1
 Total NaN in row 19695 : 0
 Total NaN in row 19696 : 2
 Total NaN in row 19697 : 0
 Total NaN in row 19698 : 0
 Total NaN in row 19699 : 3
 Total NaN in row 19700 : 2
 Total NaN in row 19701 : 0
 Total NaN in row 19702 : 0
 Total NaN in row 19703 : 0
 Total NaN in row 19704 : 1
 Total NaN in row 19705 : 2
 Total NaN in row 19706 : 1
 Total NaN in row 19707 : 2
 Total NaN in row 19708 : 9
 Total NaN in row 19709 : 3
 Total NaN in row 19710 : 0
 Total NaN in row 19711 : 0
 Total NaN in row 19712 : 1
 Total NaN in row 19713 : 2
 Total NaN in row 19714 : 2
 Total NaN in row 19715 : 2
 Total NaN in row 19716 : 2
 Total NaN in row 19717 : 0
 Total NaN in row 19718 : 1
 Total NaN in row 19719 : 2
 Total NaN in row 19720 : 0
 Total NaN in row 19721 : 0
 Total NaN in row 19722 : 0
 Total NaN in row 19723 : 0
 Total NaN in row 19724 : 1
 Total NaN in row 19725 : 2
 Total NaN in row 19726 : 2
 Total NaN in row 19727 : 3
 Total NaN in row 19728 : 10
 Total NaN in row 19729 : 2
 Total NaN in row 19730 : 2
 Total NaN in row 19731 : 1
 Total NaN in row 19732 : 2
 Total NaN in row 19733 : 1
 Total NaN in row 19734 : 3
 Total NaN in row 19735 : 0
 Total NaN in row 19736 : 9
 Total NaN in row 19737 : 0
 Total NaN in row 19738 : 1
 Total NaN in row 19739 : 1
 Total NaN in row 19740 : 2
 Total NaN in row 19741 : 0
 Total NaN in row 19742 : 2
 Total NaN in row 19743 : 2
 Total NaN in row 19744 : 1
 Total NaN in row 19745 : 1
 Total NaN in row 19746 : 0
 Total NaN in row 19747 : 2
 Total NaN in row 19748 : 2
 Total NaN in row 19749 : 2
 Total NaN in row 19750 : 3
 Total NaN in row 19751 : 2
 Total NaN in row 19752 : 10
 Total NaN in row 19753 : 2
 Total NaN in row 19754 : 1
 Total NaN in row 19755 : 2
 Total NaN in row 19756 : 0
 Total NaN in row 19757 : 2
 Total NaN in row 19758 : 1
 Total NaN in row 19759 : 1
 Total NaN in row 19760 : 0
 Total NaN in row 19761 : 1
 Total NaN in row 19762 : 9
 Total NaN in row 19763 : 1
 Total NaN in row 19764 : 2
 Total NaN in row 19765 : 10
 Total NaN in row 19766 : 0
 Total NaN in row 19767 : 2
 Total NaN in row 19768 : 2
 Total NaN in row 19769 : 0
 Total NaN in row 19770 : 2
 Total NaN in row 19771 : 0
 Total NaN in row 19772 : 0
 Total NaN in row 19773 : 0
 Total NaN in row 19774 : 0
 Total NaN in row 19775 : 2
 Total NaN in row 19776 : 0
 Total NaN in row 19777 : 0
 Total NaN in row 19778 : 2
 Total NaN in row 19779 : 0
 Total NaN in row 19780 : 0
 Total NaN in row 19781 : 1
 Total NaN in row 19782 : 0
 Total NaN in row 19783 : 1
 Total NaN in row 19784 : 9
 Total NaN in row 19785 : 3
 Total NaN in row 19786 : 1
 Total NaN in row 19787 : 2
 Total NaN in row 19788 : 1
 Total NaN in row 19789 : 9
 Total NaN in row 19790 : 1
 Total NaN in row 19791 : 1
 Total NaN in row 19792 : 0
 Total NaN in row 19793 : 2
 Total NaN in row 19794 : 1
 Total NaN in row 19795 : 9
 Total NaN in row 19796 : 3
 Total NaN in row 19797 : 3
 Total NaN in row 19798 : 1
 Total NaN in row 19799 : 0
 Total NaN in row 19800 : 10
 Total NaN in row 19801 : 0
 Total NaN in row 19802 : 1
 Total NaN in row 19803 : 1
 Total NaN in row 19804 : 0
 Total NaN in row 19805 : 0
 Total NaN in row 19806 : 9
 Total NaN in row 19807 : 0
 Total NaN in row 19808 : 0
 Total NaN in row 19809 : 0
 Total NaN in row 19810 : 2
 Total NaN in row 19811 : 0
 Total NaN in row 19812 : 1
 Total NaN in row 19813 : 2
 Total NaN in row 19814 : 2
 Total NaN in row 19815 : 10
 Total NaN in row 19816 : 0
 Total NaN in row 19817 : 0
 Total NaN in row 19818 : 2
 Total NaN in row 19819 : 0
 Total NaN in row 19820 : 2
 Total NaN in row 19821 : 2
 Total NaN in row 19822 : 0
 Total NaN in row 19823 : 0
 Total NaN in row 19824 : 0
 Total NaN in row 19825 : 2
 Total NaN in row 19826 : 2
 Total NaN in row 19827 : 2
 Total NaN in row 19828 : 3
 Total NaN in row 19829 : 0
 Total NaN in row 19830 : 2
 Total NaN in row 19831 : 1
 Total NaN in row 19832 : 3
 Total NaN in row 19833 : 2
 Total NaN in row 19834 : 2
 Total NaN in row 19835 : 0
 Total NaN in row 19836 : 0
 Total NaN in row 19837 : 0
 Total NaN in row 19838 : 2
 Total NaN in row 19839 : 2
 Total NaN in row 19840 : 1
 Total NaN in row 19841 : 0
 Total NaN in row 19842 : 1
 Total NaN in row 19843 : 0
 Total NaN in row 19844 : 2
 Total NaN in row 19845 : 1
 Total NaN in row 19846 : 0
 Total NaN in row 19847 : 0
 Total NaN in row 19848 : 0
 Total NaN in row 19849 : 2
 Total NaN in row 19850 : 0
 Total NaN in row 19851 : 2
 Total NaN in row 19852 : 2
 Total NaN in row 19853 : 0
 Total NaN in row 19854 : 9
 Total NaN in row 19855 : 1
 Total NaN in row 19856 : 3
 Total NaN in row 19857 : 5
 Total NaN in row 19858 : 4
 Total NaN in row 19859 : 2
 Total NaN in row 19860 : 3
 Total NaN in row 19861 : 1
 Total NaN in row 19862 : 4
 Total NaN in row 19863 : 3
 Total NaN in row 19864 : 1
 Total NaN in row 19865 : 1
 Total NaN in row 19866 : 4
 Total NaN in row 19867 : 3
 Total NaN in row 19868 : 3
 Total NaN in row 19869 : 4
 Total NaN in row 19870 : 9
 Total NaN in row 19871 : 9
 Total NaN in row 19872 : 2
 Total NaN in row 19873 : 2

 Total NaN in row 19874 : 3
 Total NaN in row 19875 : 2
 Total NaN in row 19876 : 4
 Total NaN in row 19877 : 4
 Total NaN in row 19878 : 1
 Total NaN in row 19879 : 2
 Total NaN in row 19880 : 3
 Total NaN in row 19881 : 3
 Total NaN in row 19882 : 4
 Total NaN in row 19883 : 5
 Total NaN in row 19884 : 4
 Total NaN in row 19885 : 3
 Total NaN in row 19886 : 4
 Total NaN in row 19887 : 3
 Total NaN in row 19888 : 2
 Total NaN in row 19889 : 1
 Total NaN in row 19890 : 4
 Total NaN in row 19891 : 1
 Total NaN in row 19892 : 9
 Total NaN in row 19893 : 4
 Total NaN in row 19894 : 4
 Total NaN in row 19895 : 2
 Total NaN in row 19896 : 4
 Total NaN in row 19897 : 10
 Total NaN in row 19898 : 9
 Total NaN in row 19899 : 4
 Total NaN in row 19900 : 7
 Total NaN in row 19901 : 2
 Total NaN in row 19902 : 4
 Total NaN in row 19903 : 3
 Total NaN in row 19904 : 2
 Total NaN in row 19905 : 9
 Total NaN in row 19906 : 3
 Total NaN in row 19907 : 10
 Total NaN in row 19908 : 9
 Total NaN in row 19909 : 2
 Total NaN in row 19910 : 2
 Total NaN in row 19911 : 1
 Total NaN in row 19912 : 2
 Total NaN in row 19913 : 2
 Total NaN in row 19914 : 1
 Total NaN in row 19915 : 5
 Total NaN in row 19916 : 1
 Total NaN in row 19917 : 4
 Total NaN in row 19918 : 2
 Total NaN in row 19919 : 3
 Total NaN in row 19920 : 3
 Total NaN in row 19921 : 4
 Total NaN in row 19922 : 1
 Total NaN in row 19923 : 3
 Total NaN in row 19924 : 4
 Total NaN in row 19925 : 3
 Total NaN in row 19926 : 1
 Total NaN in row 19927 : 3
 Total NaN in row 19928 : 2
 Total NaN in row 19929 : 3
 Total NaN in row 19930 : 4
 Total NaN in row 19931 : 4
 Total NaN in row 19932 : 4
 Total NaN in row 19933 : 1
 Total NaN in row 19934 : 2
 Total NaN in row 19935 : 3
 Total NaN in row 19936 : 3
 Total NaN in row 19937 : 4
 Total NaN in row 19938 : 4
 Total NaN in row 19939 : 3
 Total NaN in row 19940 : 4
 Total NaN in row 19941 : 3
 Total NaN in row 19942 : 4
 Total NaN in row 19943 : 2
 Total NaN in row 19944 : 1
 Total NaN in row 19945 : 3
 Total NaN in row 19946 : 2
 Total NaN in row 19947 : 4
 Total NaN in row 19948 : 4
 Total NaN in row 19949 : 2
 Total NaN in row 19950 : 21
 Total NaN in row 19951 : 9
 Total NaN in row 19952 : 2
 Total NaN in row 19953 : 1
 Total NaN in row 19954 : 2
 Total NaN in row 19955 : 1
 Total NaN in row 19956 : 1
 Total NaN in row 19957 : 3
 Total NaN in row 19958 : 2
 Total NaN in row 19959 : 3
 Total NaN in row 19960 : 3
 Total NaN in row 19961 : 4
 Total NaN in row 19962 : 3
 Total NaN in row 19963 : 4
 Total NaN in row 19964 : 4
 Total NaN in row 19965 : 2
 Total NaN in row 19966 : 3
 Total NaN in row 19967 : 4
 Total NaN in row 19968 : 1
 Total NaN in row 19969 : 10
 Total NaN in row 19970 : 5
 Total NaN in row 19971 : 4
 Total NaN in row 19972 : 1
 Total NaN in row 19973 : 5
 Total NaN in row 19974 : 5
 Total NaN in row 19975 : 2
 Total NaN in row 19976 : 3
 Total NaN in row 19977 : 9
 Total NaN in row 19978 : 1
 Total NaN in row 19979 : 2
 Total NaN in row 19980 : 4
 Total NaN in row 19981 : 2
 Total NaN in row 19982 : 5
 Total NaN in row 19983 : 4
 Total NaN in row 19984 : 4
 Total NaN in row 19985 : 4
 Total NaN in row 19986 : 4
 Total NaN in row 19987 : 1
 Total NaN in row 19988 : 2
 Total NaN in row 19989 : 1
 Total NaN in row 19990 : 2
 Total NaN in row 19991 : 4
 Total NaN in row 19992 : 3
 Total NaN in row 19993 : 3
 Total NaN in row 19994 : 2
 Total NaN in row 19995 : 2
 Total NaN in row 19996 : 1
 Total NaN in row 19997 : 1
 Total NaN in row 19998 : 3
 Total NaN in row 19999 : 1
 Total NaN in row 20000 : 2
 Total NaN in row 20001 : 3
 Total NaN in row 20002 : 2
 Total NaN in row 20003 : 3
 Total NaN in row 20004 : 2
 Total NaN in row 20005 : 1
 Total NaN in row 20006 : 2
 Total NaN in row 20007 : 3
 Total NaN in row 20008 : 1
 Total NaN in row 20009 : 3
 Total NaN in row 20010 : 2
 Total NaN in row 20011 : 5
 Total NaN in row 20012 : 1
 Total NaN in row 20013 : 1
 Total NaN in row 20014 : 3
 Total NaN in row 20015 : 1
 Total NaN in row 20016 : 3
 Total NaN in row 20017 : 4
 Total NaN in row 20018 : 3
 Total NaN in row 20019 : 4
 Total NaN in row 20020 : 2
 Total NaN in row 20021 : 1
 Total NaN in row 20022 : 3
 Total NaN in row 20023 : 1
 Total NaN in row 20024 : 9
 Total NaN in row 20025 : 4
 Total NaN in row 20026 : 2
 Total NaN in row 20027 : 3
 Total NaN in row 20028 : 3
 Total NaN in row 20029 : 2
 Total NaN in row 20030 : 3
 Total NaN in row 20031 : 4
 Total NaN in row 20032 : 3
 Total NaN in row 20033 : 1
 Total NaN in row 20034 : 2
 Total NaN in row 20035 : 3
 Total NaN in row 20036 : 2
 Total NaN in row 20037 : 1
 Total NaN in row 20038 : 9
 Total NaN in row 20039 : 2
 Total NaN in row 20040 : 3
 Total NaN in row 20041 : 3
 Total NaN in row 20042 : 3
 Total NaN in row 20043 : 2
 Total NaN in row 20044 : 5
 Total NaN in row 20045 : 3
 Total NaN in row 20046 : 2
 Total NaN in row 20047 : 5
 Total NaN in row 20048 : 3
 Total NaN in row 20049 : 2
 Total NaN in row 20050 : 4
 Total NaN in row 20051 : 5
 Total NaN in row 20052 : 2
 Total NaN in row 20053 : 2
 Total NaN in row 20054 : 4
 Total NaN in row 20055 : 3
 Total NaN in row 20056 : 3
 Total NaN in row 20057 : 4
 Total NaN in row 20058 : 4
 Total NaN in row 20059 : 2
 Total NaN in row 20060 : 2
 Total NaN in row 20061 : 1
 Total NaN in row 20062 : 4
 Total NaN in row 20063 : 1
 Total NaN in row 20064 : 3
 Total NaN in row 20065 : 3
 Total NaN in row 20066 : 4
 Total NaN in row 20067 : 4
 Total NaN in row 20068 : 9
 Total NaN in row 20069 : 2
 Total NaN in row 20070 : 1
 Total NaN in row 20071 : 1
 Total NaN in row 20072 : 2
 Total NaN in row 20073 : 1
 Total NaN in row 20074 : 1
 Total NaN in row 20075 : 1
 Total NaN in row 20076 : 2
 Total NaN in row 20077 : 9
 Total NaN in row 20078 : 4
 Total NaN in row 20079 : 5
 Total NaN in row 20080 : 3
 Total NaN in row 20081 : 4
 Total NaN in row 20082 : 2
 Total NaN in row 20083 : 2
 Total NaN in row 20084 : 2
 Total NaN in row 20085 : 3
 Total NaN in row 20086 : 2
 Total NaN in row 20087 : 2
 Total NaN in row 20088 : 21
 Total NaN in row 20089 : 1
 Total NaN in row 20090 : 3
 Total NaN in row 20091 : 4
 Total NaN in row 20092 : 2
 Total NaN in row 20093 : 1
 Total NaN in row 20094 : 2
 Total NaN in row 20095 : 3
 Total NaN in row 20096 : 9
 Total NaN in row 20097 : 1
 Total NaN in row 20098 : 1
 Total NaN in row 20099 : 3
 Total NaN in row 20100 : 2
 Total NaN in row 20101 : 2
 Total NaN in row 20102 : 1
 Total NaN in row 20103 : 3
 Total NaN in row 20104 : 1
 Total NaN in row 20105 : 3
 Total NaN in row 20106 : 3
 Total NaN in row 20107 : 3
 Total NaN in row 20108 : 4
 Total NaN in row 20109 : 3
 Total NaN in row 20110 : 3
 Total NaN in row 20111 : 2
 Total NaN in row 20112 : 3
 Total NaN in row 20113 : 5
 Total NaN in row 20114 : 3
 Total NaN in row 20115 : 3
 Total NaN in row 20116 : 4
 Total NaN in row 20117 : 3
 Total NaN in row 20118 : 4
 Total NaN in row 20119 : 10
 Total NaN in row 20120 : 3
 Total NaN in row 20121 : 9
 Total NaN in row 20122 : 1
 Total NaN in row 20123 : 1
 Total NaN in row 20124 : 2
 Total NaN in row 20125 : 9
 Total NaN in row 20126 : 9
 Total NaN in row 20127 : 1
 Total NaN in row 20128 : 1
 Total NaN in row 20129 : 5
 Total NaN in row 20130 : 3
 Total NaN in row 20131 : 9
 Total NaN in row 20132 : 3
 Total NaN in row 20133 : 2
 Total NaN in row 20134 : 5
 Total NaN in row 20135 : 1
 Total NaN in row 20136 : 9
 Total NaN in row 20137 : 5
 Total NaN in row 20138 : 2
 Total NaN in row 20139 : 3
 Total NaN in row 20140 : 9
 Total NaN in row 20141 : 2
 Total NaN in row 20142 : 1
 Total NaN in row 20143 : 3
 Total NaN in row 20144 : 5
 Total NaN in row 20145 : 2
 Total NaN in row 20146 : 2
 Total NaN in row 20147 : 4
 Total NaN in row 20148 : 4
 Total NaN in row 20149 : 10
 Total NaN in row 20150 : 7
 Total NaN in row 20151 : 4
 Total NaN in row 20152 : 2
 Total NaN in row 20153 : 3
 Total NaN in row 20154 : 2
 Total NaN in row 20155 : 4
 Total NaN in row 20156 : 4
 Total NaN in row 20157 : 3
 Total NaN in row 20158 : 2
 Total NaN in row 20159 : 2
 Total NaN in row 20160 : 3
 Total NaN in row 20161 : 2
 Total NaN in row 20162 : 4
 Total NaN in row 20163 : 3
 Total NaN in row 20164 : 2
 Total NaN in row 20165 : 2
 Total NaN in row 20166 : 3
 Total NaN in row 20167 : 4
 Total NaN in row 20168 : 4
 Total NaN in row 20169 : 3
 Total NaN in row 20170 : 9
 Total NaN in row 20171 : 3
 Total NaN in row 20172 : 3
 Total NaN in row 20173 : 7
 Total NaN in row 20174 : 4
 Total NaN in row 20175 : 5
 Total NaN in row 20176 : 1
 Total NaN in row 20177 : 9
 Total NaN in row 20178 : 3
 Total NaN in row 20179 : 2
 Total NaN in row 20180 : 2
 Total NaN in row 20181 : 2
 Total NaN in row 20182 : 3
 Total NaN in row 20183 : 1
 Total NaN in row 20184 : 4
 Total NaN in row 20185 : 2
 Total NaN in row 20186 : 5
 Total NaN in row 20187 : 5
 Total NaN in row 20188 : 2
 Total NaN in row 20189 : 3
 Total NaN in row 20190 : 2
 Total NaN in row 20191 : 4
 Total NaN in row 20192 : 9
 Total NaN in row 20193 : 4
 Total NaN in row 20194 : 2
 Total NaN in row 20195 : 3
 Total NaN in row 20196 : 3
 Total NaN in row 20197 : 3
 Total NaN in row 20198 : 5
 Total NaN in row 20199 : 9
 Total NaN in row 20200 : 9
 Total NaN in row 20201 : 9
 Total NaN in row 20202 : 1
 Total NaN in row 20203 : 4
 Total NaN in row 20204 : 4
 Total NaN in row 20205 : 9
 Total NaN in row 20206 : 5
 Total NaN in row 20207 : 4
 Total NaN in row 20208 : 7
 Total NaN in row 20209 : 3
 Total NaN in row 20210 : 5
 Total NaN in row 20211 : 1
 Total NaN in row 20212 : 9
 Total NaN in row 20213 : 3
 Total NaN in row 20214 : 3
 Total NaN in row 20215 : 1
 Total NaN in row 20216 : 2
 Total NaN in row 20217 : 4
 Total NaN in row 20218 : 3
 Total NaN in row 20219 : 4
 Total NaN in row 20220 : 1
 Total NaN in row 20221 : 8
 Total NaN in row 20222 : 1
 Total NaN in row 20223 : 1
 Total NaN in row 20224 : 1
 Total NaN in row 20225 : 1
 Total NaN in row 20226 : 3
 Total NaN in row 20227 : 2
 Total NaN in row 20228 : 9
 Total NaN in row 20229 : 2
 Total NaN in row 20230 : 2
 Total NaN in row 20231 : 2
 Total NaN in row 20232 : 5
 Total NaN in row 20233 : 2
 Total NaN in row 20234 : 9
 Total NaN in row 20235 : 4
 Total NaN in row 20236 : 1
 Total NaN in row 20237 : 3
 Total NaN in row 20238 : 3
 Total NaN in row 20239 : 5
 Total NaN in row 20240 : 10
 Total NaN in row 20241 : 3
 Total NaN in row 20242 : 3
 Total NaN in row 20243 : 2
 Total NaN in row 20244 : 4
 Total NaN in row 20245 : 2
 Total NaN in row 20246 : 4
 Total NaN in row 20247 : 4
 Total NaN in row 20248 : 1
 Total NaN in row 20249 : 1
 Total NaN in row 20250 : 2
 Total NaN in row 20251 : 3
 Total NaN in row 20252 : 4
 Total NaN in row 20253 : 4
 Total NaN in row 20254 : 2
 Total NaN in row 20255 : 2
 Total NaN in row 20256 : 4
 Total NaN in row 20257 : 1
 Total NaN in row 20258 : 2
 Total NaN in row 20259 : 4
 Total NaN in row 20260 : 4
 Total NaN in row 20261 : 3
 Total NaN in row 20262 : 3
 Total NaN in row 20263 : 1
 Total NaN in row 20264 : 2
 Total NaN in row 20265 : 3
 Total NaN in row 20266 : 3
 Total NaN in row 20267 : 3
 Total NaN in row 20268 : 8
 Total NaN in row 20269 : 10
 Total NaN in row 20270 : 3
 Total NaN in row 20271 : 3
 Total NaN in row 20272 : 3
 Total NaN in row 20273 : 2
 Total NaN in row 20274 : 9
 Total NaN in row 20275 : 5
 Total NaN in row 20276 : 1
 Total NaN in row 20277 : 4
 Total NaN in row 20278 : 2
 Total NaN in row 20279 : 3
 Total NaN in row 20280 : 2
 Total NaN in row 20281 : 1
 Total NaN in row 20282 : 2
 Total NaN in row 20283 : 1
 Total NaN in row 20284 : 2
 Total NaN in row 20285 : 3
 Total NaN in row 20286 : 4
 Total NaN in row 20287 : 1
 Total NaN in row 20288 : 2
 Total NaN in row 20289 : 2
 Total NaN in row 20290 : 3
 Total NaN in row 20291 : 1
 Total NaN in row 20292 : 5
 Total NaN in row 20293 : 3
 Total NaN in row 20294 : 3
 Total NaN in row 20295 : 9
 Total NaN in row 20296 : 9
 Total NaN in row 20297 : 2
 Total NaN in row 20298 : 2
 Total NaN in row 20299 : 3
 Total NaN in row 20300 : 9
 Total NaN in row 20301 : 4
 Total NaN in row 20302 : 3
 Total NaN in row 20303 : 9
 Total NaN in row 20304 : 4
 Total NaN in row 20305 : 2
 Total NaN in row 20306 : 4

 Total NaN in row 20307 : 2
 Total NaN in row 20308 : 3
 Total NaN in row 20309 : 2
 Total NaN in row 20310 : 1
 Total NaN in row 20311 : 10
 Total NaN in row 20312 : 1
 Total NaN in row 20313 : 3
 Total NaN in row 20314 : 3
 Total NaN in row 20315 : 3
 Total NaN in row 20316 : 4
 Total NaN in row 20317 : 4
 Total NaN in row 20318 : 1
 Total NaN in row 20319 : 2
 Total NaN in row 20320 : 3
 Total NaN in row 20321 : 9
 Total NaN in row 20322 : 3
 Total NaN in row 20323 : 4
 Total NaN in row 20324 : 5
 Total NaN in row 20325 : 3
 Total NaN in row 20326 : 2
 Total NaN in row 20327 : 2
 Total NaN in row 20328 : 5
 Total NaN in row 20329 : 2
 Total NaN in row 20330 : 1
 Total NaN in row 20331 : 9
 Total NaN in row 20332 : 4
 Total NaN in row 20333 : 2
 Total NaN in row 20334 : 2
 Total NaN in row 20335 : 5
 Total NaN in row 20336 : 5
 Total NaN in row 20337 : 2
 Total NaN in row 20338 : 5
 Total NaN in row 20339 : 1
 Total NaN in row 20340 : 2
 Total NaN in row 20341 : 2
 Total NaN in row 20342 : 3
 Total NaN in row 20343 : 3
 Total NaN in row 20344 : 3
 Total NaN in row 20345 : 3
 Total NaN in row 20346 : 2
 Total NaN in row 20347 : 9
 Total NaN in row 20348 : 3
 Total NaN in row 20349 : 10
 Total NaN in row 20350 : 3
 Total NaN in row 20351 : 2
 Total NaN in row 20352 : 1
 Total NaN in row 20353 : 1
 Total NaN in row 20354 : 4
 Total NaN in row 20355 : 1
 Total NaN in row 20356 : 1
 Total NaN in row 20357 : 1
 Total NaN in row 20358 : 3
 Total NaN in row 20359 : 3
 Total NaN in row 20360 : 3
 Total NaN in row 20361 : 3
 Total NaN in row 20362 : 2
 Total NaN in row 20363 : 1
 Total NaN in row 20364 : 3
 Total NaN in row 20365 : 4
 Total NaN in row 20366 : 2
 Total NaN in row 20367 : 3
 Total NaN in row 20368 : 2
 Total NaN in row 20369 : 1
 Total NaN in row 20370 : 4
 Total NaN in row 20371 : 2
 Total NaN in row 20372 : 4
 Total NaN in row 20373 : 2
 Total NaN in row 20374 : 4
 Total NaN in row 20375 : 2
 Total NaN in row 20376 : 5
 Total NaN in row 20377 : 1
 Total NaN in row 20378 : 1
 Total NaN in row 20379 : 4
 Total NaN in row 20380 : 10
 Total NaN in row 20381 : 2
 Total NaN in row 20382 : 2
 Total NaN in row 20383 : 4
 Total NaN in row 20384 : 3
 Total NaN in row 20385 : 2
 Total NaN in row 20386 : 4
 Total NaN in row 20387 : 2
 Total NaN in row 20388 : 5
 Total NaN in row 20389 : 2
 Total NaN in row 20390 : 2
 Total NaN in row 20391 : 2
 Total NaN in row 20392 : 3
 Total NaN in row 20393 : 2
 Total NaN in row 20394 : 4
 Total NaN in row 20395 : 10
 Total NaN in row 20396 : 9
 Total NaN in row 20397 : 1
 Total NaN in row 20398 : 3
 Total NaN in row 20399 : 4
 Total NaN in row 20400 : 1
 Total NaN in row 20401 : 3
 Total NaN in row 20402 : 2
 Total NaN in row 20403 : 3
 Total NaN in row 20404 : 3
 Total NaN in row 20405 : 2
 Total NaN in row 20406 : 2
 Total NaN in row 20407 : 3
 Total NaN in row 20408 : 3
 Total NaN in row 20409 : 3
 Total NaN in row 20410 : 4
 Total NaN in row 20411 : 5
 Total NaN in row 20412 : 3
 Total NaN in row 20413 : 3
 Total NaN in row 20414 : 3
 Total NaN in row 20415 : 2
 Total NaN in row 20416 : 3
 Total NaN in row 20417 : 4
 Total NaN in row 20418 : 7
 Total NaN in row 20419 : 2
 Total NaN in row 20420 : 2
 Total NaN in row 20421 : 2
 Total NaN in row 20422 : 5
 Total NaN in row 20423 : 21
 Total NaN in row 20424 : 4
 Total NaN in row 20425 : 3
 Total NaN in row 20426 : 1
 Total NaN in row 20427 : 3
 Total NaN in row 20428 : 2
 Total NaN in row 20429 : 2
 Total NaN in row 20430 : 3
 Total NaN in row 20431 : 3
 Total NaN in row 20432 : 1
 Total NaN in row 20433 : 10
 Total NaN in row 20434 : 2
 Total NaN in row 20435 : 1
 Total NaN in row 20436 : 2
 Total NaN in row 20437 : 2
 Total NaN in row 20438 : 4
 Total NaN in row 20439 : 3
 Total NaN in row 20440 : 1
 Total NaN in row 20441 : 1
 Total NaN in row 20442 : 2
 Total NaN in row 20443 : 3
 Total NaN in row 20444 : 9
 Total NaN in row 20445 : 4
 Total NaN in row 20446 : 4
 Total NaN in row 20447 : 3
 Total NaN in row 20448 : 4
 Total NaN in row 20449 : 9
 Total NaN in row 20450 : 4
 Total NaN in row 20451 : 2
 Total NaN in row 20452 : 4
 Total NaN in row 20453 : 1
 Total NaN in row 20454 : 3
 Total NaN in row 20455 : 2
 Total NaN in row 20456 : 3
 Total NaN in row 20457 : 10
 Total NaN in row 20458 : 3
 Total NaN in row 20459 : 4
 Total NaN in row 20460 : 2
 Total NaN in row 20461 : 2
 Total NaN in row 20462 : 1
 Total NaN in row 20463 : 9
 Total NaN in row 20464 : 4
 Total NaN in row 20465 : 3
 Total NaN in row 20466 : 4
 Total NaN in row 20467 : 4
 Total NaN in row 20468 : 1
 Total NaN in row 20469 : 3
 Total NaN in row 20470 : 1
 Total NaN in row 20471 : 4
 Total NaN in row 20472 : 5
 Total NaN in row 20473 : 3
 Total NaN in row 20474 : 1
 Total NaN in row 20475 : 4
 Total NaN in row 20476 : 3
 Total NaN in row 20477 : 4
 Total NaN in row 20478 : 9
 Total NaN in row 20479 : 9
 Total NaN in row 20480 : 9
 Total NaN in row 20481 : 4
 Total NaN in row 20482 : 4
 Total NaN in row 20483 : 2
 Total NaN in row 20484 : 10
 Total NaN in row 20485 : 4
 Total NaN in row 20486 : 4
 Total NaN in row 20487 : 2
 Total NaN in row 20488 : 5
 Total NaN in row 20489 : 2
 Total NaN in row 20490 : 3
 Total NaN in row 20491 : 2
 Total NaN in row 20492 : 1
 Total NaN in row 20493 : 4
 Total NaN in row 20494 : 2
 Total NaN in row 20495 : 4
 Total NaN in row 20496 : 3
 Total NaN in row 20497 : 21
 Total NaN in row 20498 : 2
 Total NaN in row 20499 : 4
 Total NaN in row 20500 : 9
 Total NaN in row 20501 : 3
 Total NaN in row 20502 : 3
 Total NaN in row 20503 : 4
 Total NaN in row 20504 : 9
 Total NaN in row 20505 : 4
 Total NaN in row 20506 : 3
 Total NaN in row 20507 : 2
 Total NaN in row 20508 : 10
 Total NaN in row 20509 : 5
 Total NaN in row 20510 : 2
 Total NaN in row 20511 : 3
 Total NaN in row 20512 : 3
 Total NaN in row 20513 : 3
 Total NaN in row 20514 : 3
 Total NaN in row 20515 : 4
 Total NaN in row 20516 : 4
 Total NaN in row 20517 : 4
 Total NaN in row 20518 : 4
 Total NaN in row 20519 : 3
 Total NaN in row 20520 : 5
 Total NaN in row 20521 : 2
 Total NaN in row 20522 : 1
 Total NaN in row 20523 : 1
 Total NaN in row 20524 : 4
 Total NaN in row 20525 : 1
 Total NaN in row 20526 : 1
 Total NaN in row 20527 : 9
 Total NaN in row 20528 : 4
 Total NaN in row 20529 : 2
 Total NaN in row 20530 : 1
 Total NaN in row 20531 : 2
 Total NaN in row 20532 : 2
 Total NaN in row 20533 : 10
 Total NaN in row 20534 : 10
 Total NaN in row 20535 : 1
 Total NaN in row 20536 : 3
 Total NaN in row 20537 : 2
 Total NaN in row 20538 : 3
 Total NaN in row 20539 : 4
 Total NaN in row 20540 : 4
 Total NaN in row 20541 : 4
 Total NaN in row 20542 : 3
 Total NaN in row 20543 : 3
 Total NaN in row 20544 : 4
 Total NaN in row 20545 : 3
 Total NaN in row 20546 : 4
 Total NaN in row 20547 : 3
 Total NaN in row 20548 : 2
 Total NaN in row 20549 : 3
 Total NaN in row 20550 : 4
 Total NaN in row 20551 : 3
 Total NaN in row 20552 : 8
 Total NaN in row 20553 : 1
 Total NaN in row 20554 : 2
 Total NaN in row 20555 : 4
 Total NaN in row 20556 : 4
 Total NaN in row 20557 : 4
 Total NaN in row 20558 : 10
 Total NaN in row 20559 : 4
 Total NaN in row 20560 : 4
 Total NaN in row 20561 : 3
 Total NaN in row 20562 : 9
 Total NaN in row 20563 : 3
 Total NaN in row 20564 : 2
 Total NaN in row 20565 : 2
 Total NaN in row 20566 : 4
 Total NaN in row 20567 : 10
 Total NaN in row 20568 : 2
 Total NaN in row 20569 : 2
 Total NaN in row 20570 : 3
 Total NaN in row 20571 : 5
 Total NaN in row 20572 : 2
 Total NaN in row 20573 : 3
 Total NaN in row 20574 : 1
 Total NaN in row 20575 : 3
 Total NaN in row 20576 : 3
 Total NaN in row 20577 : 2
 Total NaN in row 20578 : 4
 Total NaN in row 20579 : 3
 Total NaN in row 20580 : 4
 Total NaN in row 20581 : 3
 Total NaN in row 20582 : 5
 Total NaN in row 20583 : 2
 Total NaN in row 20584 : 3
 Total NaN in row 20585 : 3
 Total NaN in row 20586 : 1
 Total NaN in row 20587 : 4
 Total NaN in row 20588 : 10
 Total NaN in row 20589 : 10
 Total NaN in row 20590 : 2
 Total NaN in row 20591 : 4
 Total NaN in row 20592 : 3
 Total NaN in row 20593 : 2
 Total NaN in row 20594 : 9
 Total NaN in row 20595 : 3
 Total NaN in row 20596 : 2
 Total NaN in row 20597 : 3
 Total NaN in row 20598 : 4
 Total NaN in row 20599 : 2
 Total NaN in row 20600 : 1
 Total NaN in row 20601 : 3
 Total NaN in row 20602 : 3
 Total NaN in row 20603 : 1
 Total NaN in row 20604 : 8
 Total NaN in row 20605 : 3
 Total NaN in row 20606 : 3
 Total NaN in row 20607 : 4
 Total NaN in row 20608 : 3
 Total NaN in row 20609 : 9
 Total NaN in row 20610 : 3
 Total NaN in row 20611 : 3
 Total NaN in row 20612 : 1
 Total NaN in row 20613 : 3
 Total NaN in row 20614 : 1
 Total NaN in row 20615 : 2
 Total NaN in row 20616 : 2
 Total NaN in row 20617 : 2
 Total NaN in row 20618 : 4
 Total NaN in row 20619 : 4
 Total NaN in row 20620 : 3
 Total NaN in row 20621 : 2
 Total NaN in row 20622 : 1
 Total NaN in row 20623 : 2
 Total NaN in row 20624 : 4
 Total NaN in row 20625 : 3
 Total NaN in row 20626 : 3
 Total NaN in row 20627 : 2
 Total NaN in row 20628 : 1
 Total NaN in row 20629 : 2
 Total NaN in row 20630 : 3
 Total NaN in row 20631 : 2
 Total NaN in row 20632 : 4
 Total NaN in row 20633 : 4
 Total NaN in row 20634 : 9
 Total NaN in row 20635 : 4
 Total NaN in row 20636 : 4
 Total NaN in row 20637 : 2
 Total NaN in row 20638 : 3
 Total NaN in row 20639 : 2
 Total NaN in row 20640 : 1
 Total NaN in row 20641 : 2
 Total NaN in row 20642 : 4
 Total NaN in row 20643 : 2
 Total NaN in row 20644 : 1
 Total NaN in row 20645 : 1
 Total NaN in row 20646 : 2
 Total NaN in row 20647 : 5
 Total NaN in row 20648 : 3
 Total NaN in row 20649 : 1
 Total NaN in row 20650 : 5
 Total NaN in row 20651 : 2
 Total NaN in row 20652 : 1
 Total NaN in row 20653 : 4
 Total NaN in row 20654 : 3
 Total NaN in row 20655 : 1
 Total NaN in row 20656 : 3
 Total NaN in row 20657 : 1
 Total NaN in row 20658 : 3
 Total NaN in row 20659 : 3
 Total NaN in row 20660 : 2
 Total NaN in row 20661 : 2
 Total NaN in row 20662 : 1
 Total NaN in row 20663 : 3
 Total NaN in row 20664 : 4
 Total NaN in row 20665 : 4
 Total NaN in row 20666 : 4
 Total NaN in row 20667 : 5
 Total NaN in row 20668 : 2
 Total NaN in row 20669 : 9
 Total NaN in row 20670 : 3
 Total NaN in row 20671 : 2
 Total NaN in row 20672 : 9
 Total NaN in row 20673 : 3
 Total NaN in row 20674 : 1
 Total NaN in row 20675 : 2
 Total NaN in row 20676 : 4
 Total NaN in row 20677 : 2
 Total NaN in row 20678 : 2
 Total NaN in row 20679 : 9
 Total NaN in row 20680 : 3
 Total NaN in row 20681 : 3
 Total NaN in row 20682 : 9
 Total NaN in row 20683 : 4
 Total NaN in row 20684 : 3
 Total NaN in row 20685 : 5
 Total NaN in row 20686 : 2
 Total NaN in row 20687 : 3
 Total NaN in row 20688 : 9
 Total NaN in row 20689 : 9
 Total NaN in row 20690 : 1
 Total NaN in row 20691 : 2
 Total NaN in row 20692 : 1
 Total NaN in row 20693 : 4
 Total NaN in row 20694 : 3
 Total NaN in row 20695 : 1
 Total NaN in row 20696 : 21
 Total NaN in row 20697 : 4
 Total NaN in row 20698 : 2
 Total NaN in row 20699 : 3
 Total NaN in row 20700 : 10
 Total NaN in row 20701 : 2
 Total NaN in row 20702 : 10
 Total NaN in row 20703 : 4
 Total NaN in row 20704 : 5
 Total NaN in row 20705 : 4
 Total NaN in row 20706 : 3
 Total NaN in row 20707 : 2
 Total NaN in row 20708 : 4
 Total NaN in row 20709 : 3
 Total NaN in row 20710 : 3
 Total NaN in row 20711 : 3
 Total NaN in row 20712 : 4
 Total NaN in row 20713 : 4
 Total NaN in row 20714 : 5
 Total NaN in row 20715 : 3
 Total NaN in row 20716 : 2
 Total NaN in row 20717 : 2
 Total NaN in row 20718 : 1
 Total NaN in row 20719 : 3
 Total NaN in row 20720 : 3
 Total NaN in row 20721 : 1
 Total NaN in row 20722 : 3
 Total NaN in row 20723 : 4
 Total NaN in row 20724 : 5
 Total NaN in row 20725 : 3
 Total NaN in row 20726 : 1
 Total NaN in row 20727 : 4
 Total NaN in row 20728 : 3
 Total NaN in row 20729 : 4
 Total NaN in row 20730 : 1
 Total NaN in row 20731 : 4
 Total NaN in row 20732 : 2
 Total NaN in row 20733 : 4

 Total NaN in row 20734 : 5
 Total NaN in row 20735 : 4
 Total NaN in row 20736 : 3
 Total NaN in row 20737 : 1
 Total NaN in row 20738 : 1
 Total NaN in row 20739 : 4
 Total NaN in row 20740 : 1
 Total NaN in row 20741 : 3
 Total NaN in row 20742 : 1
 Total NaN in row 20743 : 3
 Total NaN in row 20744 : 3
 Total NaN in row 20745 : 3
 Total NaN in row 20746 : 2
 Total NaN in row 20747 : 2
 Total NaN in row 20748 : 2
 Total NaN in row 20749 : 3
 Total NaN in row 20750 : 3
 Total NaN in row 20751 : 4
 Total NaN in row 20752 : 3
 Total NaN in row 20753 : 3
 Total NaN in row 20754 : 3
 Total NaN in row 20755 : 3
 Total NaN in row 20756 : 3
 Total NaN in row 20757 : 3
 Total NaN in row 20758 : 4
 Total NaN in row 20759 : 4
 Total NaN in row 20760 : 3
 Total NaN in row 20761 : 1
 Total NaN in row 20762 : 2
 Total NaN in row 20763 : 3
 Total NaN in row 20764 : 3
 Total NaN in row 20765 : 9
 Total NaN in row 20766 : 9
 Total NaN in row 20767 : 10
 Total NaN in row 20768 : 1
 Total NaN in row 20769 : 2
 Total NaN in row 20770 : 4
 Total NaN in row 20771 : 1
 Total NaN in row 20772 : 8
 Total NaN in row 20773 : 5
 Total NaN in row 20774 : 10
 Total NaN in row 20775 : 4
 Total NaN in row 20776 : 4
 Total NaN in row 20777 : 4
 Total NaN in row 20778 : 2
 Total NaN in row 20779 : 3
 Total NaN in row 20780 : 3
 Total NaN in row 20781 : 3
 Total NaN in row 20782 : 3
 Total NaN in row 20783 : 9
 Total NaN in row 20784 : 4
 Total NaN in row 20785 : 5
 Total NaN in row 20786 : 2
 Total NaN in row 20787 : 1
 Total NaN in row 20788 : 9
 Total NaN in row 20789 : 3
 Total NaN in row 20790 : 9
 Total NaN in row 20791 : 7
 Total NaN in row 20792 : 1
 Total NaN in row 20793 : 2
 Total NaN in row 20794 : 4
 Total NaN in row 20795 : 10
 Total NaN in row 20796 : 2
 Total NaN in row 20797 : 9
 Total NaN in row 20798 : 4
 Total NaN in row 20799 : 2
 Total NaN in row 20800 : 9
 Total NaN in row 20801 : 5
 Total NaN in row 20802 : 9
 Total NaN in row 20803 : 1
 Total NaN in row 20804 : 3
 Total NaN in row 20805 : 3
 Total NaN in row 20806 : 2
 Total NaN in row 20807 : 2
 Total NaN in row 20808 : 1
 Total NaN in row 20809 : 4
 Total NaN in row 20810 : 9
 Total NaN in row 20811 : 1
 Total NaN in row 20812 : 3
 Total NaN in row 20813 : 1
 Total NaN in row 20814 : 3
 Total NaN in row 20815 : 2
 Total NaN in row 20816 : 4
 Total NaN in row 20817 : 2
 Total NaN in row 20818 : 2
 Total NaN in row 20819 : 1
 Total NaN in row 20820 : 1
 Total NaN in row 20821 : 4
 Total NaN in row 20822 : 2
 Total NaN in row 20823 : 4
 Total NaN in row 20824 : 1
 Total NaN in row 20825 : 3
 Total NaN in row 20826 : 2
 Total NaN in row 20827 : 2
 Total NaN in row 20828 : 2
 Total NaN in row 20829 : 4
 Total NaN in row 20830 : 4
 Total NaN in row 20831 : 3
 Total NaN in row 20832 : 2
 Total NaN in row 20833 : 2
 Total NaN in row 20834 : 3
 Total NaN in row 20835 : 10
 Total NaN in row 20836 : 3
 Total NaN in row 20837 : 4
 Total NaN in row 20838 : 1
 Total NaN in row 20839 : 21
 Total NaN in row 20840 : 2
 Total NaN in row 20841 : 2
 Total NaN in row 20842 : 1
 Total NaN in row 20843 : 2
 Total NaN in row 20844 : 1
 Total NaN in row 20845 : 5
 Total NaN in row 20846 : 9
 Total NaN in row 20847 : 9
 Total NaN in row 20848 : 9
 Total NaN in row 20849 : 2
 Total NaN in row 20850 : 4
 Total NaN in row 20851 : 1
 Total NaN in row 20852 : 2
 Total NaN in row 20853 : 1
 Total NaN in row 20854 : 1
 Total NaN in row 20855 : 1
 Total NaN in row 20856 : 3
 Total NaN in row 20857 : 4
 Total NaN in row 20858 : 3
 Total NaN in row 20859 : 4
 Total NaN in row 20860 : 2
 Total NaN in row 20861 : 2
 Total NaN in row 20862 : 2
 Total NaN in row 20863 : 2
 Total NaN in row 20864 : 5
 Total NaN in row 20865 : 3
 Total NaN in row 20866 : 9
 Total NaN in row 20867 : 2
 Total NaN in row 20868 : 3
 Total NaN in row 20869 : 1
 Total NaN in row 20870 : 1
 Total NaN in row 20871 : 3
 Total NaN in row 20872 : 2
 Total NaN in row 20873 : 2
 Total NaN in row 20874 : 3
 Total NaN in row 20875 : 4
 Total NaN in row 20876 : 4
 Total NaN in row 20877 : 3
 Total NaN in row 20878 : 1
 Total NaN in row 20879 : 4
 Total NaN in row 20880 : 2
 Total NaN in row 20881 : 21
 Total NaN in row 20882 : 4
 Total NaN in row 20883 : 3
 Total NaN in row 20884 : 9
 Total NaN in row 20885 : 4
 Total NaN in row 20886 : 2
 Total NaN in row 20887 : 4
 Total NaN in row 20888 : 4
 Total NaN in row 20889 : 3
 Total NaN in row 20890 : 1
 Total NaN in row 20891 : 4
 Total NaN in row 20892 : 2
 Total NaN in row 20893 : 3
 Total NaN in row 20894 : 4
 Total NaN in row 20895 : 2
 Total NaN in row 20896 : 2
 Total NaN in row 20897 : 3
 Total NaN in row 20898 : 4
 Total NaN in row 20899 : 3
 Total NaN in row 20900 : 2
 Total NaN in row 20901 : 4
 Total NaN in row 20902 : 1
 Total NaN in row 20903 : 5
 Total NaN in row 20904 : 9
 Total NaN in row 20905 : 3
 Total NaN in row 20906 : 9
 Total NaN in row 20907 : 5
 Total NaN in row 20908 : 4
 Total NaN in row 20909 : 1
 Total NaN in row 20910 : 1
 Total NaN in row 20911 : 5
 Total NaN in row 20912 : 1
 Total NaN in row 20913 : 5
 Total NaN in row 20914 : 4
 Total NaN in row 20915 : 3
 Total NaN in row 20916 : 1
 Total NaN in row 20917 : 4
 Total NaN in row 20918 : 1
 Total NaN in row 20919 : 2
 Total NaN in row 20920 : 4
 Total NaN in row 20921 : 2
 Total NaN in row 20922 : 1
 Total NaN in row 20923 : 1
 Total NaN in row 20924 : 3
 Total NaN in row 20925 : 1
 Total NaN in row 20926 : 1
 Total NaN in row 20927 : 3
 Total NaN in row 20928 : 4
 Total NaN in row 20929 : 1
 Total NaN in row 20930 : 4
 Total NaN in row 20931 : 4
 Total NaN in row 20932 : 2
 Total NaN in row 20933 : 4
 Total NaN in row 20934 : 3
 Total NaN in row 20935 : 2
 Total NaN in row 20936 : 4
 Total NaN in row 20937 : 5
 Total NaN in row 20938 : 3
 Total NaN in row 20939 : 1
 Total NaN in row 20940 : 2
 Total NaN in row 20941 : 7
 Total NaN in row 20942 : 2
 Total NaN in row 20943 : 6
 Total NaN in row 20944 : 3
 Total NaN in row 20945 : 5
 Total NaN in row 20946 : 4
 Total NaN in row 20947 : 4
 Total NaN in row 20948 : 7
 Total NaN in row 20949 : 3
 Total NaN in row 20950 : 3
 Total NaN in row 20951 : 4
 Total NaN in row 20952 : 4
 Total NaN in row 20953 : 4
 Total NaN in row 20954 : 5
 Total NaN in row 20955 : 4
 Total NaN in row 20956 : 4
 Total NaN in row 20957 : 4
 Total NaN in row 20958 : 2
 Total NaN in row 20959 : 4
 Total NaN in row 20960 : 4
 Total NaN in row 20961 : 3
 Total NaN in row 20962 : 2
 Total NaN in row 20963 : 6
 Total NaN in row 20964 : 9
 Total NaN in row 20965 : 1
 Total NaN in row 20966 : 9
 Total NaN in row 20967 : 5
 Total NaN in row 20968 : 4
 Total NaN in row 20969 : 5
 Total NaN in row 20970 : 1
 Total NaN in row 20971 : 4
 Total NaN in row 20972 : 4
 Total NaN in row 20973 : 2
 Total NaN in row 20974 : 2
 Total NaN in row 20975 : 2
 Total NaN in row 20976 : 3
 Total NaN in row 20977 : 2
 Total NaN in row 20978 : 9
 Total NaN in row 20979 : 3
 Total NaN in row 20980 : 10
 Total NaN in row 20981 : 1
 Total NaN in row 20982 : 3
 Total NaN in row 20983 : 3
 Total NaN in row 20984 : 4
 Total NaN in row 20985 : 4
 Total NaN in row 20986 : 4
 Total NaN in row 20987 : 4
 Total NaN in row 20988 : 3
 Total NaN in row 20989 : 3
 Total NaN in row 20990 : 4
 Total NaN in row 20991 : 4
 Total NaN in row 20992 : 4
 Total NaN in row 20993 : 3
 Total NaN in row 20994 : 4
 Total NaN in row 20995 : 9
 Total NaN in row 20996 : 4
 Total NaN in row 20997 : 4
 Total NaN in row 20998 : 4
 Total NaN in row 20999 : 2
 Total NaN in row 21000 : 2
 Total NaN in row 21001 : 1
 Total NaN in row 21002 : 3
 Total NaN in row 21003 : 1
 Total NaN in row 21004 : 2
 Total NaN in row 21005 : 10
 Total NaN in row 21006 : 4
 Total NaN in row 21007 : 3
 Total NaN in row 21008 : 1
 Total NaN in row 21009 : 4
 Total NaN in row 21010 : 4
 Total NaN in row 21011 : 4
 Total NaN in row 21012 : 2
 Total NaN in row 21013 : 3
 Total NaN in row 21014 : 3
 Total NaN in row 21015 : 5
 Total NaN in row 21016 : 3
 Total NaN in row 21017 : 3
 Total NaN in row 21018 : 2
 Total NaN in row 21019 : 2
 Total NaN in row 21020 : 9
 Total NaN in row 21021 : 3
 Total NaN in row 21022 : 1
 Total NaN in row 21023 : 2
 Total NaN in row 21024 : 1
 Total NaN in row 21025 : 9
 Total NaN in row 21026 : 1
 Total NaN in row 21027 : 4
 Total NaN in row 21028 : 4
 Total NaN in row 21029 : 2
 Total NaN in row 21030 : 1
 Total NaN in row 21031 : 9
 Total NaN in row 21032 : 3
 Total NaN in row 21033 : 5
 Total NaN in row 21034 : 2
 Total NaN in row 21035 : 4
 Total NaN in row 21036 : 10
 Total NaN in row 21037 : 3
 Total NaN in row 21038 : 2
 Total NaN in row 21039 : 3
 Total NaN in row 21040 : 4
 Total NaN in row 21041 : 3
 Total NaN in row 21042 : 10

 Total NaN in row 21043 : 7
 Total NaN in row 21044 : 4
 Total NaN in row 21045 : 4
 Total NaN in row 21046 : 1
 Total NaN in row 21047 : 2
 Total NaN in row 21048 : 4
 Total NaN in row 21049 : 4
 Total NaN in row 21050 : 3
 Total NaN in row 21051 : 5
 Total NaN in row 21052 : 4
 Total NaN in row 21053 : 9
 Total NaN in row 21054 : 4
 Total NaN in row 21055 : 1
 Total NaN in row 21056 : 21
 Total NaN in row 21057 : 10
 Total NaN in row 21058 : 3
 Total NaN in row 21059 : 3
 Total NaN in row 21060 : 2
 Total NaN in row 21061 : 3
 Total NaN in row 21062 : 4
 Total NaN in row 21063 : 9
 Total NaN in row 21064 : 3
 Total NaN in row 21065 : 3
 Total NaN in row 21066 : 3
 Total NaN in row 21067 : 4
 Total NaN in row 21068 : 4
 Total NaN in row 21069 : 7
 Total NaN in row 21070 : 1
 Total NaN in row 21071 : 10
 Total NaN in row 21072 : 3
 Total NaN in row 21073 : 2
 Total NaN in row 21074 : 1
 Total NaN in row 21075 : 3
 Total NaN in row 21076 : 3
 Total NaN in row 21077 : 2
 Total NaN in row 21078 : 1
 Total NaN in row 21079 : 3
 Total NaN in row 21080 : 9
 Total NaN in row 21081 : 7
 Total NaN in row 21082 : 4
 Total NaN in row 21083 : 4
 Total NaN in row 21084 : 4
 Total NaN in row 21085 : 9
 Total NaN in row 21086 : 4
 Total NaN in row 21087 : 3
 Total NaN in row 21088 : 4
 Total NaN in row 21089 : 3
 Total NaN in row 21090 : 10
 Total NaN in row 21091 : 9
 Total NaN in row 21092 : 1
 Total NaN in row 21093 : 5
 Total NaN in row 21094 : 3
 Total NaN in row 21095 : 4
 Total NaN in row 21096 : 4
 Total NaN in row 21097 : 1
 Total NaN in row 21098 : 1
 Total NaN in row 21099 : 4
 Total NaN in row 21100 : 3
 Total NaN in row 21101 : 5
 Total NaN in row 21102 : 2
 Total NaN in row 21103 : 5
 Total NaN in row 21104 : 1
 Total NaN in row 21105 : 1
 Total NaN in row 21106 : 1
 Total NaN in row 21107 : 4
 Total NaN in row 21108 : 4
 Total NaN in row 21109 : 3
 Total NaN in row 21110 : 2
 Total NaN in row 21111 : 5
 Total NaN in row 21112 : 1
 Total NaN in row 21113 : 1
 Total NaN in row 21114 : 3
 Total NaN in row 21115 : 4
 Total NaN in row 21116 : 4
 Total NaN in row 21117 : 7
 Total NaN in row 21118 : 2
 Total NaN in row 21119 : 9
 Total NaN in row 21120 : 1
 Total NaN in row 21121 : 4
 Total NaN in row 21122 : 3
 Total NaN in row 21123 : 3
 Total NaN in row 21124 : 9
 Total NaN in row 21125 : 4
 Total NaN in row 21126 : 1
 Total NaN in row 21127 : 9
 Total NaN in row 21128 : 2
 Total NaN in row 21129 : 2
 Total NaN in row 21130 : 2
 Total NaN in row 21131 : 2
 Total NaN in row 21132 : 1
 Total NaN in row 21133 : 3
 Total NaN in row 21134 : 3
 Total NaN in row 21135 : 4
 Total NaN in row 21136 : 7
 Total NaN in row 21137 : 3
 Total NaN in row 21138 : 10
 Total NaN in row 21139 : 9
 Total NaN in row 21140 : 10
 Total NaN in row 21141 : 3
 Total NaN in row 21142 : 1
 Total NaN in row 21143 : 3
 Total NaN in row 21144 : 4
 Total NaN in row 21145 : 2
 Total NaN in row 21146 : 3
 Total NaN in row 21147 : 2
 Total NaN in row 21148 : 3
 Total NaN in row 21149 : 2
 Total NaN in row 21150 : 1
 Total NaN in row 21151 : 3
 Total NaN in row 21152 : 5
 Total NaN in row 21153 : 1
 Total NaN in row 21154 : 1
 Total NaN in row 21155 : 3
 Total NaN in row 21156 : 2
 Total NaN in row 21157 : 3
 Total NaN in row 21158 : 2
 Total NaN in row 21159 : 5
 Total NaN in row 21160 : 3
 Total NaN in row 21161 : 3
 Total NaN in row 21162 : 3
 Total NaN in row 21163 : 2
 Total NaN in row 21164 : 1
 Total NaN in row 21165 : 4
 Total NaN in row 21166 : 3
 Total NaN in row 21167 : 2
 Total NaN in row 21168 : 2
 Total NaN in row 21169 : 4
 Total NaN in row 21170 : 1
 Total NaN in row 21171 : 4
 Total NaN in row 21172 : 2
 Total NaN in row 21173 : 2
 Total NaN in row 21174 : 7
 Total NaN in row 21175 : 9
 Total NaN in row 21176 : 3
 Total NaN in row 21177 : 3
 Total NaN in row 21178 : 1
 Total NaN in row 21179 : 3
 Total NaN in row 21180 : 2
 Total NaN in row 21181 : 1
 Total NaN in row 21182 : 9
 Total NaN in row 21183 : 9
 Total NaN in row 21184 : 10
 Total NaN in row 21185 : 4
 Total NaN in row 21186 : 2
 Total NaN in row 21187 : 3
 Total NaN in row 21188 : 2
 Total NaN in row 21189 : 9
 Total NaN in row 21190 : 5
 Total NaN in row 21191 : 2
 Total NaN in row 21192 : 4
 Total NaN in row 21193 : 4
 Total NaN in row 21194 : 3
 Total NaN in row 21195 : 9
 Total NaN in row 21196 : 4
 Total NaN in row 21197 : 4
 Total NaN in row 21198 : 1
 Total NaN in row 21199 : 2
 Total NaN in row 21200 : 3
 Total NaN in row 21201 : 3
 Total NaN in row 21202 : 1
 Total NaN in row 21203 : 3
 Total NaN in row 21204 : 2
 Total NaN in row 21205 : 3
 Total NaN in row 21206 : 2
 Total NaN in row 21207 : 2
 Total NaN in row 21208 : 3
 Total NaN in row 21209 : 1
 Total NaN in row 21210 : 3
 Total NaN in row 21211 : 2
 Total NaN in row 21212 : 3
 Total NaN in row 21213 : 3
 Total NaN in row 21214 : 5
 Total NaN in row 21215 : 2
 Total NaN in row 21216 : 4
 Total NaN in row 21217 : 1
 Total NaN in row 21218 : 4
 Total NaN in row 21219 : 1
 Total NaN in row 21220 : 7
 Total NaN in row 21221 : 21
 Total NaN in row 21222 : 10
 Total NaN in row 21223 : 3
 Total NaN in row 21224 : 5
 Total NaN in row 21225 : 4
 Total NaN in row 21226 : 1
 Total NaN in row 21227 : 4
 Total NaN in row 21228 : 4
 Total NaN in row 21229 : 5
 Total NaN in row 21230 : 3
 Total NaN in row 21231 : 1
 Total NaN in row 21232 : 2
 Total NaN in row 21233 : 9
 Total NaN in row 21234 : 3
 Total NaN in row 21235 : 3
 Total NaN in row 21236 : 3
 Total NaN in row 21237 : 1
 Total NaN in row 21238 : 2
 Total NaN in row 21239 : 3
 Total NaN in row 21240 : 3
 Total NaN in row 21241 : 10
 Total NaN in row 21242 : 1
 Total NaN in row 21243 : 4
 Total NaN in row 21244 : 3
 Total NaN in row 21245 : 4
 Total NaN in row 21246 : 1
 Total NaN in row 21247 : 6
 Total NaN in row 21248 : 4
 Total NaN in row 21249 : 5
 Total NaN in row 21250 : 4
 Total NaN in row 21251 : 3
 Total NaN in row 21252 : 4
 Total NaN in row 21253 : 9
 Total NaN in row 21254 : 3
 Total NaN in row 21255 : 2
 Total NaN in row 21256 : 4
 Total NaN in row 21257 : 1
 Total NaN in row 21258 : 4
 Total NaN in row 21259 : 8
 Total NaN in row 21260 : 1
 Total NaN in row 21261 : 4
 Total NaN in row 21262 : 2
 Total NaN in row 21263 : 4
 Total NaN in row 21264 : 2
 Total NaN in row 21265 : 1
 Total NaN in row 21266 : 1
 Total NaN in row 21267 : 3
 Total NaN in row 21268 : 2
 Total NaN in row 21269 : 5
 Total NaN in row 21270 : 3
 Total NaN in row 21271 : 5
 Total NaN in row 21272 : 1
 Total NaN in row 21273 : 3
 Total NaN in row 21274 : 4
 Total NaN in row 21275 : 5
 Total NaN in row 21276 : 3
 Total NaN in row 21277 : 3
 Total NaN in row 21278 : 2
 Total NaN in row 21279 : 2
 Total NaN in row 21280 : 4
 Total NaN in row 21281 : 2
 Total NaN in row 21282 : 3
 Total NaN in row 21283 : 4
 Total NaN in row 21284 : 4
 Total NaN in row 21285 : 3
 Total NaN in row 21286 : 3
 Total NaN in row 21287 : 2
 Total NaN in row 21288 : 4
 Total NaN in row 21289 : 1
 Total NaN in row 21290 : 4
 Total NaN in row 21291 : 3
 Total NaN in row 21292 : 3
 Total NaN in row 21293 : 1
 Total NaN in row 21294 : 1
 Total NaN in row 21295 : 3
 Total NaN in row 21296 : 3
 Total NaN in row 21297 : 4
 Total NaN in row 21298 : 3
 Total NaN in row 21299 : 4
 Total NaN in row 21300 : 4
 Total NaN in row 21301 : 2
 Total NaN in row 21302 : 2
 Total NaN in row 21303 : 3
 Total NaN in row 21304 : 3
 Total NaN in row 21305 : 4
 Total NaN in row 21306 : 4
 Total NaN in row 21307 : 3
 Total NaN in row 21308 : 7
 Total NaN in row 21309 : 2
 Total NaN in row 21310 : 5
 Total NaN in row 21311 : 10
 Total NaN in row 21312 : 3
 Total NaN in row 21313 : 3
 Total NaN in row 21314 : 4
 Total NaN in row 21315 : 2
 Total NaN in row 21316 : 3
 Total NaN in row 21317 : 3
 Total NaN in row 21318 : 1
 Total NaN in row 21319 : 10
 Total NaN in row 21320 : 9
 Total NaN in row 21321 : 9
 Total NaN in row 21322 : 3
 Total NaN in row 21323 : 4
 Total NaN in row 21324 : 5
 Total NaN in row 21325 : 2
 Total NaN in row 21326 : 3
 Total NaN in row 21327 : 4
 Total NaN in row 21328 : 2
 Total NaN in row 21329 : 4
 Total NaN in row 21330 : 2
 Total NaN in row 21331 : 3
 Total NaN in row 21332 : 4
 Total NaN in row 21333 : 3
 Total NaN in row 21334 : 3
 Total NaN in row 21335 : 4
 Total NaN in row 21336 : 1
 Total NaN in row 21337 : 2
 Total NaN in row 21338 : 3
 Total NaN in row 21339 : 2
 Total NaN in row 21340 : 1
 Total NaN in row 21341 : 4
 Total NaN in row 21342 : 2
 Total NaN in row 21343 : 3
 Total NaN in row 21344 : 21
 Total NaN in row 21345 : 10
 Total NaN in row 21346 : 3
 Total NaN in row 21347 : 4
 Total NaN in row 21348 : 3
 Total NaN in row 21349 : 2
 Total NaN in row 21350 : 4
 Total NaN in row 21351 : 3
 Total NaN in row 21352 : 9
 Total NaN in row 21353 : 5
 Total NaN in row 21354 : 2
 Total NaN in row 21355 : 3
 Total NaN in row 21356 : 3
 Total NaN in row 21357 : 1
 Total NaN in row 21358 : 10
 Total NaN in row 21359 : 1
 Total NaN in row 21360 : 4
 Total NaN in row 21361 : 2
 Total NaN in row 21362 : 9
 Total NaN in row 21363 : 1
 Total NaN in row 21364 : 3

 Total NaN in row 21365 : 3
 Total NaN in row 21366 : 3
 Total NaN in row 21367 : 2
 Total NaN in row 21368 : 2
 Total NaN in row 21369 : 2
 Total NaN in row 21370 : 1
 Total NaN in row 21371 : 1
 Total NaN in row 21372 : 9
 Total NaN in row 21373 : 3
 Total NaN in row 21374 : 3
 Total NaN in row 21375 : 3
 Total NaN in row 21376 : 1
 Total NaN in row 21377 : 2
 Total NaN in row 21378 : 5
 Total NaN in row 21379 : 5
 Total NaN in row 21380 : 2
 Total NaN in row 21381 : 3
 Total NaN in row 21382 : 1
 Total NaN in row 21383 : 10
 Total NaN in row 21384 : 3
 Total NaN in row 21385 : 2
 Total NaN in row 21386 : 2
 Total NaN in row 21387 : 2
 Total NaN in row 21388 : 2
 Total NaN in row 21389 : 4
 Total NaN in row 21390 : 3
 Total NaN in row 21391 : 3
 Total NaN in row 21392 : 4
 Total NaN in row 21393 : 2
 Total NaN in row 21394 : 4
 Total NaN in row 21395 : 1
 Total NaN in row 21396 : 1
 Total NaN in row 21397 : 9
 Total NaN in row 21398 : 3
 Total NaN in row 21399 : 3
 Total NaN in row 21400 : 3
 Total NaN in row 21401 : 1
 Total NaN in row 21402 : 3
 Total NaN in row 21403 : 4
 Total NaN in row 21404 : 4
 Total NaN in row 21405 : 4
 Total NaN in row 21406 : 2
 Total NaN in row 21407 : 2
 Total NaN in row 21408 : 2
 Total NaN in row 21409 : 3
 Total NaN in row 21410 : 1
 Total NaN in row 21411 : 4
 Total NaN in row 21412 : 5
 Total NaN in row 21413 : 1
 Total NaN in row 21414 : 1
 Total NaN in row 21415 : 4
 Total NaN in row 21416 : 3
 Total NaN in row 21417 : 3
 Total NaN in row 21418 : 3
 Total NaN in row 21419 : 2
 Total NaN in row 21420 : 7
 Total NaN in row 21421 : 3
 Total NaN in row 21422 : 3
 Total NaN in row 21423 : 7
 Total NaN in row 21424 : 4
 Total NaN in row 21425 : 2
 Total NaN in row 21426 : 2
 Total NaN in row 21427 : 4
 Total NaN in row 21428 : 2
 Total NaN in row 21429 : 3
 Total NaN in row 21430 : 2
 Total NaN in row 21431 : 2
 Total NaN in row 21432 : 2
 Total NaN in row 21433 : 3
 Total NaN in row 21434 : 2
 Total NaN in row 21435 : 3
 Total NaN in row 21436 : 4
 Total NaN in row 21437 : 3
 Total NaN in row 21438 : 1
 Total NaN in row 21439 : 1
 Total NaN in row 21440 : 5
 Total NaN in row 21441 : 10
 Total NaN in row 21442 : 9
 Total NaN in row 21443 : 1
 Total NaN in row 21444 : 2
 Total NaN in row 21445 : 1
 Total NaN in row 21446 : 3
 Total NaN in row 21447 : 3
 Total NaN in row 21448 : 2
 Total NaN in row 21449 : 10
 Total NaN in row 21450 : 10
 Total NaN in row 21451 : 10
 Total NaN in row 21452 : 3
 Total NaN in row 21453 : 2
 Total NaN in row 21454 : 2
 Total NaN in row 21455 : 2
 Total NaN in row 21456 : 1
 Total NaN in row 21457 : 3
 Total NaN in row 21458 : 3
 Total NaN in row 21459 : 2
 Total NaN in row 21460 : 2
 Total NaN in row 21461 : 4
 Total NaN in row 21462 : 4
 Total NaN in row 21463 : 4
 Total NaN in row 21464 : 4
 Total NaN in row 21465 : 4
 Total NaN in row 21466 : 9
 Total NaN in row 21467 : 10
 Total NaN in row 21468 : 1
 Total NaN in row 21469 : 7
 Total NaN in row 21470 : 9
 Total NaN in row 21471 : 9
 Total NaN in row 21472 : 9
 Total NaN in row 21473 : 10
 Total NaN in row 21474 : 2
 Total NaN in row 21475 : 2
 Total NaN in row 21476 : 4
 Total NaN in row 21477 : 2
 Total NaN in row 21478 : 1
 Total NaN in row 21479 : 3
 Total NaN in row 21480 : 3
 Total NaN in row 21481 : 2
 Total NaN in row 21482 : 2
 Total NaN in row 21483 : 2
 Total NaN in row 21484 : 2
 Total NaN in row 21485 : 3
 Total NaN in row 21486 : 4
 Total NaN in row 21487 : 2
 Total NaN in row 21488 : 9
 Total NaN in row 21489 : 3
 Total NaN in row 21490 : 3
 Total NaN in row 21491 : 2
 Total NaN in row 21492 : 4
 Total NaN in row 21493 : 1
 Total NaN in row 21494 : 3
 Total NaN in row 21495 : 3
 Total NaN in row 21496 : 3
 Total NaN in row 21497 : 2
 Total NaN in row 21498 : 9
 Total NaN in row 21499 : 5
 Total NaN in row 21500 : 4
 Total NaN in row 21501 : 4
 Total NaN in row 21502 : 4
 Total NaN in row 21503 : 3
 Total NaN in row 21504 : 1
 Total NaN in row 21505 : 3
 Total NaN in row 21506 : 3
 Total NaN in row 21507 : 2
 Total NaN in row 21508 : 4
 Total NaN in row 21509 : 10
 Total NaN in row 21510 : 1
 Total NaN in row 21511 : 3
 Total NaN in row 21512 : 7
 Total NaN in row 21513 : 1
 Total NaN in row 21514 : 2
 Total NaN in row 21515 : 3
 Total NaN in row 21516 : 2
 Total NaN in row 21517 : 2
 Total NaN in row 21518 : 9
 Total NaN in row 21519 : 3
 Total NaN in row 21520 : 4
 Total NaN in row 21521 : 2
 Total NaN in row 21522 : 1
 Total NaN in row 21523 : 4
 Total NaN in row 21524 : 1
 Total NaN in row 21525 : 4
 Total NaN in row 21526 : 9
 Total NaN in row 21527 : 3
 Total NaN in row 21528 : 1
 Total NaN in row 21529 : 4
 Total NaN in row 21530 : 3
 Total NaN in row 21531 : 3
 Total NaN in row 21532 : 1
 Total NaN in row 21533 : 4
 Total NaN in row 21534 : 9
 Total NaN in row 21535 : 1
 Total NaN in row 21536 : 8
 Total NaN in row 21537 : 1
 Total NaN in row 21538 : 1
 Total NaN in row 21539 : 2
 Total NaN in row 21540 : 4
 Total NaN in row 21541 : 1
 Total NaN in row 21542 : 4
 Total NaN in row 21543 : 4
 Total NaN in row 21544 : 9
 Total NaN in row 21545 : 2
 Total NaN in row 21546 : 1
 Total NaN in row 21547 : 4
 Total NaN in row 21548 : 4
 Total NaN in row 21549 : 4
 Total NaN in row 21550 : 9
 Total NaN in row 21551 : 2
 Total NaN in row 21552 : 5
 Total NaN in row 21553 : 4
 Total NaN in row 21554 : 4
 Total NaN in row 21555 : 5
 Total NaN in row 21556 : 4
 Total NaN in row 21557 : 3
 Total NaN in row 21558 : 3
 Total NaN in row 21559 : 1
 Total NaN in row 21560 : 3
 Total NaN in row 21561 : 4
 Total NaN in row 21562 : 2
 Total NaN in row 21563 : 4
 Total NaN in row 21564 : 3
 Total NaN in row 21565 : 2
 Total NaN in row 21566 : 2
 Total NaN in row 21567 : 4
 Total NaN in row 21568 : 3
 Total NaN in row 21569 : 3
 Total NaN in row 21570 : 4
 Total NaN in row 21571 : 2
 Total NaN in row 21572 : 10
 Total NaN in row 21573 : 1
 Total NaN in row 21574 : 3
 Total NaN in row 21575 : 3
 Total NaN in row 21576 : 1
 Total NaN in row 21577 : 4
 Total NaN in row 21578 : 2
 Total NaN in row 21579 : 2
 Total NaN in row 21580 : 9
 Total NaN in row 21581 : 1
 Total NaN in row 21582 : 4
 Total NaN in row 21583 : 1
 Total NaN in row 21584 : 3
 Total NaN in row 21585 : 6
 Total NaN in row 21586 : 5
 Total NaN in row 21587 : 3
 Total NaN in row 21588 : 4
 Total NaN in row 21589 : 3
 Total NaN in row 21590 : 9
 Total NaN in row 21591 : 3
 Total NaN in row 21592 : 3
 Total NaN in row 21593 : 3
 Total NaN in row 21594 : 4
 Total NaN in row 21595 : 4
 Total NaN in row 21596 : 3
 Total NaN in row 21597 : 3
 Total NaN in row 21598 : 3
 Total NaN in row 21599 : 4
 Total NaN in row 21600 : 3
 Total NaN in row 21601 : 3
 Total NaN in row 21602 : 1
 Total NaN in row 21603 : 21
 Total NaN in row 21604 : 3
 Total NaN in row 21605 : 1
 Total NaN in row 21606 : 3
 Total NaN in row 21607 : 4
 Total NaN in row 21608 : 9
 Total NaN in row 21609 : 2
 Total NaN in row 21610 : 2
 Total NaN in row 21611 : 2
 Total NaN in row 21612 : 2
 Total NaN in row 21613 : 3
 Total NaN in row 21614 : 3
 Total NaN in row 21615 : 1
 Total NaN in row 21616 : 7
 Total NaN in row 21617 : 4
 Total NaN in row 21618 : 2
 Total NaN in row 21619 : 4
 Total NaN in row 21620 : 3
 Total NaN in row 21621 : 2
 Total NaN in row 21622 : 2
 Total NaN in row 21623 : 5
 Total NaN in row 21624 : 2
 Total NaN in row 21625 : 1
 Total NaN in row 21626 : 4
 Total NaN in row 21627 : 3
 Total NaN in row 21628 : 4
 Total NaN in row 21629 : 3
 Total NaN in row 21630 : 4
 Total NaN in row 21631 : 10
 Total NaN in row 21632 : 3
 Total NaN in row 21633 : 2
 Total NaN in row 21634 : 1
 Total NaN in row 21635 : 2
 Total NaN in row 21636 : 2
 Total NaN in row 21637 : 3
 Total NaN in row 21638 : 2
 Total NaN in row 21639 : 5
 Total NaN in row 21640 : 1
 Total NaN in row 21641 : 3
 Total NaN in row 21642 : 4
 Total NaN in row 21643 : 4
 Total NaN in row 21644 : 3
 Total NaN in row 21645 : 1
 Total NaN in row 21646 : 1
 Total NaN in row 21647 : 2
 Total NaN in row 21648 : 2
 Total NaN in row 21649 : 2
 Total NaN in row 21650 : 3
 Total NaN in row 21651 : 2
 Total NaN in row 21652 : 4
 Total NaN in row 21653 : 5
 Total NaN in row 21654 : 3
 Total NaN in row 21655 : 2
 Total NaN in row 21656 : 6
 Total NaN in row 21657 : 4
 Total NaN in row 21658 : 2
 Total NaN in row 21659 : 9
 Total NaN in row 21660 : 3
 Total NaN in row 21661 : 4
 Total NaN in row 21662 : 2

 Total NaN in row 21663 : 2
 Total NaN in row 21664 : 4
 Total NaN in row 21665 : 4
 Total NaN in row 21666 : 4
 Total NaN in row 21667 : 7
 Total NaN in row 21668 : 7
 Total NaN in row 21669 : 3
 Total NaN in row 21670 : 3
 Total NaN in row 21671 : 9
 Total NaN in row 21672 : 4
 Total NaN in row 21673 : 1
 Total NaN in row 21674 : 3
 Total NaN in row 21675 : 9
 Total NaN in row 21676 : 4
 Total NaN in row 21677 : 1
 Total NaN in row 21678 : 1
 Total NaN in row 21679 : 3
 Total NaN in row 21680 : 9
 Total NaN in row 21681 : 1
 Total NaN in row 21682 : 3
 Total NaN in row 21683 : 3
 Total NaN in row 21684 : 2
 Total NaN in row 21685 : 3
 Total NaN in row 21686 : 2
 Total NaN in row 21687 : 3
 Total NaN in row 21688 : 1
 Total NaN in row 21689 : 4
 Total NaN in row 21690 : 1
 Total NaN in row 21691 : 2
 Total NaN in row 21692 : 9
 Total NaN in row 21693 : 1
 Total NaN in row 21694 : 5
 Total NaN in row 21695 : 4
 Total NaN in row 21696 : 3
 Total NaN in row 21697 : 2
 Total NaN in row 21698 : 1
 Total NaN in row 21699 : 4
 Total NaN in row 21700 : 1
 Total NaN in row 21701 : 3
 Total NaN in row 21702 : 6
 Total NaN in row 21703 : 4
 Total NaN in row 21704 : 2
 Total NaN in row 21705 : 4
 Total NaN in row 21706 : 3
 Total NaN in row 21707 : 10
 Total NaN in row 21708 : 4
 Total NaN in row 21709 : 3
 Total NaN in row 21710 : 4
 Total NaN in row 21711 : 2
 Total NaN in row 21712 : 1
 Total NaN in row 21713 : 4
 Total NaN in row 21714 : 3
 Total NaN in row 21715 : 1
 Total NaN in row 21716 : 2
 Total NaN in row 21717 : 4
 Total NaN in row 21718 : 3
 Total NaN in row 21719 : 1
 Total NaN in row 21720 : 1
 Total NaN in row 21721 : 2
 Total NaN in row 21722 : 2
 Total NaN in row 21723 : 9
 Total NaN in row 21724 : 1
 Total NaN in row 21725 : 4
 Total NaN in row 21726 : 3
 Total NaN in row 21727 : 2
 Total NaN in row 21728 : 4
 Total NaN in row 21729 : 5
 Total NaN in row 21730 : 1
 Total NaN in row 21731 : 4
 Total NaN in row 21732 : 1
 Total NaN in row 21733 : 1
 Total NaN in row 21734 : 1
 Total NaN in row 21735 : 2
 Total NaN in row 21736 : 9
 Total NaN in row 21737 : 1
 Total NaN in row 21738 : 1
 Total NaN in row 21739 : 4
 Total NaN in row 21740 : 4
 Total NaN in row 21741 : 2
 Total NaN in row 21742 : 5
 Total NaN in row 21743 : 3
 Total NaN in row 21744 : 2
 Total NaN in row 21745 : 3
 Total NaN in row 21746 : 2
 Total NaN in row 21747 : 2
 Total NaN in row 21748 : 4
 Total NaN in row 21749 : 1
 Total NaN in row 21750 : 5
 Total NaN in row 21751 : 2
 Total NaN in row 21752 : 3
 Total NaN in row 21753 : 1
 Total NaN in row 21754 : 2
 Total NaN in row 21755 : 3
 Total NaN in row 21756 : 4
 Total NaN in row 21757 : 9
 Total NaN in row 21758 : 4
 Total NaN in row 21759 : 1
 Total NaN in row 21760 : 9
 Total NaN in row 21761 : 2
 Total NaN in row 21762 : 3
 Total NaN in row 21763 : 3
 Total NaN in row 21764 : 4
 Total NaN in row 21765 : 1
 Total NaN in row 21766 : 2
 Total NaN in row 21767 : 2
 Total NaN in row 21768 : 2
 Total NaN in row 21769 : 4
 Total NaN in row 21770 : 9
 Total NaN in row 21771 : 4
 Total NaN in row 21772 : 2
 Total NaN in row 21773 : 3
 Total NaN in row 21774 : 1
 Total NaN in row 21775 : 4
 Total NaN in row 21776 : 2
 Total NaN in row 21777 : 1
 Total NaN in row 21778 : 1
 Total NaN in row 21779 : 2
 Total NaN in row 21780 : 9
 Total NaN in row 21781 : 2
 Total NaN in row 21782 : 3
 Total NaN in row 21783 : 3
 Total NaN in row 21784 : 1
 Total NaN in row 21785 : 1
 Total NaN in row 21786 : 9
 Total NaN in row 21787 : 2
 Total NaN in row 21788 : 3
 Total NaN in row 21789 : 9
 Total NaN in row 21790 : 3
 Total NaN in row 21791 : 3
 Total NaN in row 21792 : 4
 Total NaN in row 21793 : 10
 Total NaN in row 21794 : 3
 Total NaN in row 21795 : 2
 Total NaN in row 21796 : 3
 Total NaN in row 21797 : 3
 Total NaN in row 21798 : 1
 Total NaN in row 21799 : 3
 Total NaN in row 21800 : 1
 Total NaN in row 21801 : 3
 Total NaN in row 21802 : 3
 Total NaN in row 21803 : 1
 Total NaN in row 21804 : 2
 Total NaN in row 21805 : 4
 Total NaN in row 21806 : 8
 Total NaN in row 21807 : 2
 Total NaN in row 21808 : 2
 Total NaN in row 21809 : 1
 Total NaN in row 21810 : 4
 Total NaN in row 21811 : 3
 Total NaN in row 21812 : 2
 Total NaN in row 21813 : 2
 Total NaN in row 21814 : 9
 Total NaN in row 21815 : 3
 Total NaN in row 21816 : 4
 Total NaN in row 21817 : 3
 Total NaN in row 21818 : 9
 Total NaN in row 21819 : 10
 Total NaN in row 21820 : 4
 Total NaN in row 21821 : 9
 Total NaN in row 21822 : 1
 Total NaN in row 21823 : 2
 Total NaN in row 21824 : 3
 Total NaN in row 21825 : 1
 Total NaN in row 21826 : 4
 Total NaN in row 21827 : 2
 Total NaN in row 21828 : 4
 Total NaN in row 21829 : 2
 Total NaN in row 21830 : 3
 Total NaN in row 21831 : 2
 Total NaN in row 21832 : 2
 Total NaN in row 21833 : 4
 Total NaN in row 21834 : 2
 Total NaN in row 21835 : 4
 Total NaN in row 21836 : 3
 Total NaN in row 21837 : 2
 Total NaN in row 21838 : 7
 Total NaN in row 21839 : 10
 Total NaN in row 21840 : 4
 Total NaN in row 21841 : 3
 Total NaN in row 21842 : 1
 Total NaN in row 21843 : 2
 Total NaN in row 21844 : 3
 Total NaN in row 21845 : 2
 Total NaN in row 21846 : 2
 Total NaN in row 21847 : 9
 Total NaN in row 21848 : 3
 Total NaN in row 21849 : 5
 Total NaN in row 21850 : 3
 Total NaN in row 21851 : 2
 Total NaN in row 21852 : 2
 Total NaN in row 21853 : 2
 Total NaN in row 21854 : 3
 Total NaN in row 21855 : 2
 Total NaN in row 21856 : 9
 Total NaN in row 21857 : 2
 Total NaN in row 21858 : 4
 Total NaN in row 21859 : 2
 Total NaN in row 21860 : 3
 Total NaN in row 21861 : 4
 Total NaN in row 21862 : 1
 Total NaN in row 21863 : 2
 Total NaN in row 21864 : 3
 Total NaN in row 21865 : 2
 Total NaN in row 21866 : 2
 Total NaN in row 21867 : 2
 Total NaN in row 21868 : 2
 Total NaN in row 21869 : 3
 Total NaN in row 21870 : 1
 Total NaN in row 21871 : 2
 Total NaN in row 21872 : 1
 Total NaN in row 21873 : 3
 Total NaN in row 21874 : 3
 Total NaN in row 21875 : 3
 Total NaN in row 21876 : 1
 Total NaN in row 21877 : 2
 Total NaN in row 21878 : 4
 Total NaN in row 21879 : 2
 Total NaN in row 21880 : 3
 Total NaN in row 21881 : 1
 Total NaN in row 21882 : 3
 Total NaN in row 21883 : 4
 Total NaN in row 21884 : 2
 Total NaN in row 21885 : 9
 Total NaN in row 21886 : 3
 Total NaN in row 21887 : 2
 Total NaN in row 21888 : 4
 Total NaN in row 21889 : 3
 Total NaN in row 21890 : 2
 Total NaN in row 21891 : 3
 Total NaN in row 21892 : 3
 Total NaN in row 21893 : 2
 Total NaN in row 21894 : 4
 Total NaN in row 21895 : 2
 Total NaN in row 21896 : 1
 Total NaN in row 21897 : 5
 Total NaN in row 21898 : 2
 Total NaN in row 21899 : 3
 Total NaN in row 21900 : 1
 Total NaN in row 21901 : 3
 Total NaN in row 21902 : 1
 Total NaN in row 21903 : 1
 Total NaN in row 21904 : 1
 Total NaN in row 21905 : 1
 Total NaN in row 21906 : 3
 Total NaN in row 21907 : 9
 Total NaN in row 21908 : 7
 Total NaN in row 21909 : 4
 Total NaN in row 21910 : 4
 Total NaN in row 21911 : 2
 Total NaN in row 21912 : 2
 Total NaN in row 21913 : 1
 Total NaN in row 21914 : 9
 Total NaN in row 21915 : 1
 Total NaN in row 21916 : 1
 Total NaN in row 21917 : 1
 Total NaN in row 21918 : 4
 Total NaN in row 21919 : 3
 Total NaN in row 21920 : 9
 Total NaN in row 21921 : 3
 Total NaN in row 21922 : 3
 Total NaN in row 21923 : 1
 Total NaN in row 21924 : 1
 Total NaN in row 21925 : 2
 Total NaN in row 21926 : 3
 Total NaN in row 21927 : 1
 Total NaN in row 21928 : 1
 Total NaN in row 21929 : 3
 Total NaN in row 21930 : 3
 Total NaN in row 21931 : 2
 Total NaN in row 21932 : 10
 Total NaN in row 21933 : 1
 Total NaN in row 21934 : 1
 Total NaN in row 21935 : 2
 Total NaN in row 21936 : 2
 Total NaN in row 21937 : 4
 Total NaN in row 21938 : 2
 Total NaN in row 21939 : 2
 Total NaN in row 21940 : 3
 Total NaN in row 21941 : 4
 Total NaN in row 21942 : 2
 Total NaN in row 21943 : 2
 Total NaN in row 21944 : 3
 Total NaN in row 21945 : 1
 Total NaN in row 21946 : 9
 Total NaN in row 21947 : 3
 Total NaN in row 21948 : 3
 Total NaN in row 21949 : 2
 Total NaN in row 21950 : 2
 Total NaN in row 21951 : 3
 Total NaN in row 21952 : 4
 Total NaN in row 21953 : 4
 Total NaN in row 21954 : 3
 Total NaN in row 21955 : 3
 Total NaN in row 21956 : 9
 Total NaN in row 21957 : 1
 Total NaN in row 21958 : 1
 Total NaN in row 21959 : 2

 Total NaN in row 21960 : 9
 Total NaN in row 21961 : 2
 Total NaN in row 21962 : 5
 Total NaN in row 21963 : 3
 Total NaN in row 21964 : 1
 Total NaN in row 21965 : 2
 Total NaN in row 21966 : 4
 Total NaN in row 21967 : 2
 Total NaN in row 21968 : 9
 Total NaN in row 21969 : 1
 Total NaN in row 21970 : 1
 Total NaN in row 21971 : 2
 Total NaN in row 21972 : 4
 Total NaN in row 21973 : 1
 Total NaN in row 21974 : 4
 Total NaN in row 21975 : 1
 Total NaN in row 21976 : 4
 Total NaN in row 21977 : 1
 Total NaN in row 21978 : 2
 Total NaN in row 21979 : 2
 Total NaN in row 21980 : 2
 Total NaN in row 21981 : 3
 Total NaN in row 21982 : 2
 Total NaN in row 21983 : 2
 Total NaN in row 21984 : 1
 Total NaN in row 21985 : 3
 Total NaN in row 21986 : 7
 Total NaN in row 21987 : 1
 Total NaN in row 21988 : 3
 Total NaN in row 21989 : 3
 Total NaN in row 21990 : 4
 Total NaN in row 21991 : 1
 Total NaN in row 21992 : 5
 Total NaN in row 21993 : 2
 Total NaN in row 21994 : 1
 Total NaN in row 21995 : 2
 Total NaN in row 21996 : 3
 Total NaN in row 21997 : 4
 Total NaN in row 21998 : 1
 Total NaN in row 21999 : 1
 Total NaN in row 22000 : 3
 Total NaN in row 22001 : 2
 Total NaN in row 22002 : 2
 Total NaN in row 22003 : 3
 Total NaN in row 22004 : 21
 Total NaN in row 22005 : 2
 Total NaN in row 22006 : 3
 Total NaN in row 22007 : 1
 Total NaN in row 22008 : 2
 Total NaN in row 22009 : 2
 Total NaN in row 22010 : 1
 Total NaN in row 22011 : 4
 Total NaN in row 22012 : 1
 Total NaN in row 22013 : 1
 Total NaN in row 22014 : 1
 Total NaN in row 22015 : 1
 Total NaN in row 22016 : 3
 Total NaN in row 22017 : 3
 Total NaN in row 22018 : 1
 Total NaN in row 22019 : 2
 Total NaN in row 22020 : 1
 Total NaN in row 22021 : 1
 Total NaN in row 22022 : 3
 Total NaN in row 22023 : 1
 Total NaN in row 22024 : 4
 Total NaN in row 22025 : 3
 Total NaN in row 22026 : 4
 Total NaN in row 22027 : 9
 Total NaN in row 22028 : 2
 Total NaN in row 22029 : 4
 Total NaN in row 22030 : 3
 Total NaN in row 22031 : 3
 Total NaN in row 22032 : 2
 Total NaN in row 22033 : 5
 Total NaN in row 22034 : 2
 Total NaN in row 22035 : 9
 Total NaN in row 22036 : 4
 Total NaN in row 22037 : 2
 Total NaN in row 22038 : 2
 Total NaN in row 22039 : 9
 Total NaN in row 22040 : 2
 Total NaN in row 22041 : 3
 Total NaN in row 22042 : 5
 Total NaN in row 22043 : 3
 Total NaN in row 22044 : 2
 Total NaN in row 22045 : 3
 Total NaN in row 22046 : 9
 Total NaN in row 22047 : 2
 Total NaN in row 22048 : 2
 Total NaN in row 22049 : 3
 Total NaN in row 22050 : 3
 Total NaN in row 22051 : 1
 Total NaN in row 22052 : 4
 Total NaN in row 22053 : 4
 Total NaN in row 22054 : 3
 Total NaN in row 22055 : 1
 Total NaN in row 22056 : 2
 Total NaN in row 22057 : 1
 Total NaN in row 22058 : 2
 Total NaN in row 22059 : 5
 Total NaN in row 22060 : 4
 Total NaN in row 22061 : 7
 Total NaN in row 22062 : 2
 Total NaN in row 22063 : 3
 Total NaN in row 22064 : 9
 Total NaN in row 22065 : 1
 Total NaN in row 22066 : 2
 Total NaN in row 22067 : 2
 Total NaN in row 22068 : 4
 Total NaN in row 22069 : 3
 Total NaN in row 22070 : 1
 Total NaN in row 22071 : 1
 Total NaN in row 22072 : 1
 Total NaN in row 22073 : 1
 Total NaN in row 22074 : 3
 Total NaN in row 22075 : 9
 Total NaN in row 22076 : 1
 Total NaN in row 22077 : 4
 Total NaN in row 22078 : 2
 Total NaN in row 22079 : 4
 Total NaN in row 22080 : 2
 Total NaN in row 22081 : 4
 Total NaN in row 22082 : 1
 Total NaN in row 22083 : 3
 Total NaN in row 22084 : 3
 Total NaN in row 22085 : 3
 Total NaN in row 22086 : 1
 Total NaN in row 22087 : 2
 Total NaN in row 22088 : 1
 Total NaN in row 22089 : 1
 Total NaN in row 22090 : 9
 Total NaN in row 22091 : 3
 Total NaN in row 22092 : 1
 Total NaN in row 22093 : 3
 Total NaN in row 22094 : 2
 Total NaN in row 22095 : 9
 Total NaN in row 22096 : 10
 Total NaN in row 22097 : 3
 Total NaN in row 22098 : 4
 Total NaN in row 22099 : 3
 Total NaN in row 22100 : 2
 Total NaN in row 22101 : 1
 Total NaN in row 22102 : 2
 Total NaN in row 22103 : 1
 Total NaN in row 22104 : 3
 Total NaN in row 22105 : 1
 Total NaN in row 22106 : 5
 Total NaN in row 22107 : 3
 Total NaN in row 22108 : 2
 Total NaN in row 22109 : 1
 Total NaN in row 22110 : 21
 Total NaN in row 22111 : 3
 Total NaN in row 22112 : 4
 Total NaN in row 22113 : 2
 Total NaN in row 22114 : 3
 Total NaN in row 22115 : 1
 Total NaN in row 22116 : 2
 Total NaN in row 22117 : 2
 Total NaN in row 22118 : 4
 Total NaN in row 22119 : 3
 Total NaN in row 22120 : 3
 Total NaN in row 22121 : 2
 Total NaN in row 22122 : 3
 Total NaN in row 22123 : 3
 Total NaN in row 22124 : 4
 Total NaN in row 22125 : 1
 Total NaN in row 22126 : 3
 Total NaN in row 22127 : 2
 Total NaN in row 22128 : 9
 Total NaN in row 22129 : 4
 Total NaN in row 22130 : 1
 Total NaN in row 22131 : 3
 Total NaN in row 22132 : 2
 Total NaN in row 22133 : 4
 Total NaN in row 22134 : 3
 Total NaN in row 22135 : 2
 Total NaN in row 22136 : 4
 Total NaN in row 22137 : 1
 Total NaN in row 22138 : 3
 Total NaN in row 22139 : 4
 Total NaN in row 22140 : 2
 Total NaN in row 22141 : 1
 Total NaN in row 22142 : 9
 Total NaN in row 22143 : 2
 Total NaN in row 22144 : 3
 Total NaN in row 22145 : 2
 Total NaN in row 22146 : 2
 Total NaN in row 22147 : 2
 Total NaN in row 22148 : 2
 Total NaN in row 22149 : 1
 Total NaN in row 22150 : 2
 Total NaN in row 22151 : 4
 Total NaN in row 22152 : 3
 Total NaN in row 22153 : 2
 Total NaN in row 22154 : 2
 Total NaN in row 22155 : 3
 Total NaN in row 22156 : 8
 Total NaN in row 22157 : 2
 Total NaN in row 22158 : 2
 Total NaN in row 22159 : 1
 Total NaN in row 22160 : 9
 Total NaN in row 22161 : 1
 Total NaN in row 22162 : 4
 Total NaN in row 22163 : 9
 Total NaN in row 22164 : 3
 Total NaN in row 22165 : 2
 Total NaN in row 22166 : 4
 Total NaN in row 22167 : 1
 Total NaN in row 22168 : 9
 Total NaN in row 22169 : 1
 Total NaN in row 22170 : 2
 Total NaN in row 22171 : 3
 Total NaN in row 22172 : 4
 Total NaN in row 22173 : 1
 Total NaN in row 22174 : 9
 Total NaN in row 22175 : 9
 Total NaN in row 22176 : 2
 Total NaN in row 22177 : 1
 Total NaN in row 22178 : 1
 Total NaN in row 22179 : 3
 Total NaN in row 22180 : 3
 Total NaN in row 22181 : 2
 Total NaN in row 22182 : 2
 Total NaN in row 22183 : 2
 Total NaN in row 22184 : 2
 Total NaN in row 22185 : 10
 Total NaN in row 22186 : 5
 Total NaN in row 22187 : 2
 Total NaN in row 22188 : 4
 Total NaN in row 22189 : 3
 Total NaN in row 22190 : 5
 Total NaN in row 22191 : 2
 Total NaN in row 22192 : 3
 Total NaN in row 22193 : 4
 Total NaN in row 22194 : 9
 Total NaN in row 22195 : 2
 Total NaN in row 22196 : 4
 Total NaN in row 22197 : 2
 Total NaN in row 22198 : 8
 Total NaN in row 22199 : 1
 Total NaN in row 22200 : 3
 Total NaN in row 22201 : 4
 Total NaN in row 22202 : 4
 Total NaN in row 22203 : 3
 Total NaN in row 22204 : 9
 Total NaN in row 22205 : 3
 Total NaN in row 22206 : 1
 Total NaN in row 22207 : 5
 Total NaN in row 22208 : 2
 Total NaN in row 22209 : 5
 Total NaN in row 22210 : 1
 Total NaN in row 22211 : 3
 Total NaN in row 22212 : 3
 Total NaN in row 22213 : 4
 Total NaN in row 22214 : 2
 Total NaN in row 22215 : 1
 Total NaN in row 22216 : 9
 Total NaN in row 22217 : 1
 Total NaN in row 22218 : 4
 Total NaN in row 22219 : 3
 Total NaN in row 22220 : 2
 Total NaN in row 22221 : 9
 Total NaN in row 22222 : 3
 Total NaN in row 22223 : 3
 Total NaN in row 22224 : 3
 Total NaN in row 22225 : 9
 Total NaN in row 22226 : 2
 Total NaN in row 22227 : 4
 Total NaN in row 22228 : 2
 Total NaN in row 22229 : 2
 Total NaN in row 22230 : 1
 Total NaN in row 22231 : 1
 Total NaN in row 22232 : 4
 Total NaN in row 22233 : 2
 Total NaN in row 22234 : 10
 Total NaN in row 22235 : 8
 Total NaN in row 22236 : 9
 Total NaN in row 22237 : 9
 Total NaN in row 22238 : 3
 Total NaN in row 22239 : 9
 Total NaN in row 22240 : 2
 Total NaN in row 22241 : 5
 Total NaN in row 22242 : 2
 Total NaN in row 22243 : 3
 Total NaN in row 22244 : 3
 Total NaN in row 22245 : 7
 Total NaN in row 22246 : 4
 Total NaN in row 22247 : 3
 Total NaN in row 22248 : 4
 Total NaN in row 22249 : 1
 Total NaN in row 22250 : 3
 Total NaN in row 22251 : 1
 Total NaN in row 22252 : 3
 Total NaN in row 22253 : 4
 Total NaN in row 22254 : 3
 Total NaN in row 22255 : 3
 Total NaN in row 22256 : 1
 Total NaN in row 22257 : 3
 Total NaN in row 22258 : 2
 Total NaN in row 22259 : 2
 Total NaN in row 22260 : 1
 Total NaN in row 22261 : 1
 Total NaN in row 22262 : 2
 Total NaN in row 22263 : 1
 Total NaN in row 22264 : 1
 Total NaN in row 22265 : 3
 Total NaN in row 22266 : 3
 Total NaN in row 22267 : 4
 Total NaN in row 22268 : 3
 Total NaN in row 22269 : 5
 Total NaN in row 22270 : 3
 Total NaN in row 22271 : 3
 Total NaN in row 22272 : 2
 Total NaN in row 22273 : 2
 Total NaN in row 22274 : 3
 Total NaN in row 22275 : 3
 Total NaN in row 22276 : 2
 Total NaN in row 22277 : 1
 Total NaN in row 22278 : 3
 Total NaN in row 22279 : 4
 Total NaN in row 22280 : 9
 Total NaN in row 22281 : 9

 Total NaN in row 22282 : 2
 Total NaN in row 22283 : 2
 Total NaN in row 22284 : 1
 Total NaN in row 22285 : 2
 Total NaN in row 22286 : 3
 Total NaN in row 22287 : 4
 Total NaN in row 22288 : 4
 Total NaN in row 22289 : 21
 Total NaN in row 22290 : 1
 Total NaN in row 22291 : 3
 Total NaN in row 22292 : 3
 Total NaN in row 22293 : 1
 Total NaN in row 22294 : 4
 Total NaN in row 22295 : 9
 Total NaN in row 22296 : 3
 Total NaN in row 22297 : 9
 Total NaN in row 22298 : 5
 Total NaN in row 22299 : 2
 Total NaN in row 22300 : 1
 Total NaN in row 22301 : 4
 Total NaN in row 22302 : 9
 Total NaN in row 22303 : 4
 Total NaN in row 22304 : 4
 Total NaN in row 22305 : 1
 Total NaN in row 22306 : 3
 Total NaN in row 22307 : 3
 Total NaN in row 22308 : 3
 Total NaN in row 22309 : 4
 Total NaN in row 22310 : 2
 Total NaN in row 22311 : 1
 Total NaN in row 22312 : 2
 Total NaN in row 22313 : 3
 Total NaN in row 22314 : 5
 Total NaN in row 22315 : 4
 Total NaN in row 22316 : 3
 Total NaN in row 22317 : 4
 Total NaN in row 22318 : 2
 Total NaN in row 22319 : 1
 Total NaN in row 22320 : 3
 Total NaN in row 22321 : 4
 Total NaN in row 22322 : 4
 Total NaN in row 22323 : 9
 Total NaN in row 22324 : 3
 Total NaN in row 22325 : 3
 Total NaN in row 22326 : 9
 Total NaN in row 22327 : 4
 Total NaN in row 22328 : 3
 Total NaN in row 22329 : 2
 Total NaN in row 22330 : 2
 Total NaN in row 22331 : 2
 Total NaN in row 22332 : 1
 Total NaN in row 22333 : 2
 Total NaN in row 22334 : 9
 Total NaN in row 22335 : 10
 Total NaN in row 22336 : 5
 Total NaN in row 22337 : 3
 Total NaN in row 22338 : 3
 Total NaN in row 22339 : 2
 Total NaN in row 22340 : 3
 Total NaN in row 22341 : 2
 Total NaN in row 22342 : 3
 Total NaN in row 22343 : 1
 Total NaN in row 22344 : 4
 Total NaN in row 22345 : 4
 Total NaN in row 22346 : 2
 Total NaN in row 22347 : 5
 Total NaN in row 22348 : 3
 Total NaN in row 22349 : 1
 Total NaN in row 22350 : 4
 Total NaN in row 22351 : 5
 Total NaN in row 22352 : 3
 Total NaN in row 22353 : 4
 Total NaN in row 22354 : 1
 Total NaN in row 22355 : 9
 Total NaN in row 22356 : 4
 Total NaN in row 22357 : 9
 Total NaN in row 22358 : 4
 Total NaN in row 22359 : 2
 Total NaN in row 22360 : 2
 Total NaN in row 22361 : 3
 Total NaN in row 22362 : 4
 Total NaN in row 22363 : 2
 Total NaN in row 22364 : 10
 Total NaN in row 22365 : 3
 Total NaN in row 22366 : 4
 Total NaN in row 22367 : 4
 Total NaN in row 22368 : 3
 Total NaN in row 22369 : 3
 Total NaN in row 22370 : 4
 Total NaN in row 22371 : 1
 Total NaN in row 22372 : 5
 Total NaN in row 22373 : 1
 Total NaN in row 22374 : 1
 Total NaN in row 22375 : 5
 Total NaN in row 22376 : 3
 Total NaN in row 22377 : 4
 Total NaN in row 22378 : 1
 Total NaN in row 22379 : 4
 Total NaN in row 22380 : 4
 Total NaN in row 22381 : 10
 Total NaN in row 22382 : 4
 Total NaN in row 22383 : 6
 Total NaN in row 22384 : 10
 Total NaN in row 22385 : 3
 Total NaN in row 22386 : 3
 Total NaN in row 22387 : 2
 Total NaN in row 22388 : 4
 Total NaN in row 22389 : 3
 Total NaN in row 22390 : 2
 Total NaN in row 22391 : 3
 Total NaN in row 22392 : 2
 Total NaN in row 22393 : 3
 Total NaN in row 22394 : 2
 Total NaN in row 22395 : 2
 Total NaN in row 22396 : 9
 Total NaN in row 22397 : 4
 Total NaN in row 22398 : 2
 Total NaN in row 22399 : 3
 Total NaN in row 22400 : 2
 Total NaN in row 22401 : 3
 Total NaN in row 22402 : 2
 Total NaN in row 22403 : 3
 Total NaN in row 22404 : 3
 Total NaN in row 22405 : 4
 Total NaN in row 22406 : 2
 Total NaN in row 22407 : 1
 Total NaN in row 22408 : 1
 Total NaN in row 22409 : 4
 Total NaN in row 22410 : 4
 Total NaN in row 22411 : 4
 Total NaN in row 22412 : 10
 Total NaN in row 22413 : 3
 Total NaN in row 22414 : 3
 Total NaN in row 22415 : 2
 Total NaN in row 22416 : 3
 Total NaN in row 22417 : 1
 Total NaN in row 22418 : 3
 Total NaN in row 22419 : 3
 Total NaN in row 22420 : 4
 Total NaN in row 22421 : 1
 Total NaN in row 22422 : 2
 Total NaN in row 22423 : 3
 Total NaN in row 22424 : 1
 Total NaN in row 22425 : 1
 Total NaN in row 22426 : 4
 Total NaN in row 22427 : 9
 Total NaN in row 22428 : 2
 Total NaN in row 22429 : 9
 Total NaN in row 22430 : 9
 Total NaN in row 22431 : 4
 Total NaN in row 22432 : 2
 Total NaN in row 22433 : 2
 Total NaN in row 22434 : 4
 Total NaN in row 22435 : 5
 Total NaN in row 22436 : 3
 Total NaN in row 22437 : 4
 Total NaN in row 22438 : 4
 Total NaN in row 22439 : 3
 Total NaN in row 22440 : 10
 Total NaN in row 22441 : 3
 Total NaN in row 22442 : 9
 Total NaN in row 22443 : 2
 Total NaN in row 22444 : 3
 Total NaN in row 22445 : 1
 Total NaN in row 22446 : 4
 Total NaN in row 22447 : 5
 Total NaN in row 22448 : 2
 Total NaN in row 22449 : 4
 Total NaN in row 22450 : 2
 Total NaN in row 22451 : 4
 Total NaN in row 22452 : 3
 Total NaN in row 22453 : 3
 Total NaN in row 22454 : 4
 Total NaN in row 22455 : 4
 Total NaN in row 22456 : 1
 Total NaN in row 22457 : 1
 Total NaN in row 22458 : 1
 Total NaN in row 22459 : 4
 Total NaN in row 22460 : 2
 Total NaN in row 22461 : 9
 Total NaN in row 22462 : 8
 Total NaN in row 22463 : 4
 Total NaN in row 22464 : 3
 Total NaN in row 22465 : 2
 Total NaN in row 22466 : 5
 Total NaN in row 22467 : 2
 Total NaN in row 22468 : 3
 Total NaN in row 22469 : 9
 Total NaN in row 22470 : 4
 Total NaN in row 22471 : 3
 Total NaN in row 22472 : 1
 Total NaN in row 22473 : 1
 Total NaN in row 22474 : 3
 Total NaN in row 22475 : 2
 Total NaN in row 22476 : 3
 Total NaN in row 22477 : 5
 Total NaN in row 22478 : 4
 Total NaN in row 22479 : 3
 Total NaN in row 22480 : 3
 Total NaN in row 22481 : 10
 Total NaN in row 22482 : 2
 Total NaN in row 22483 : 4
 Total NaN in row 22484 : 1
 Total NaN in row 22485 : 2
 Total NaN in row 22486 : 1
 Total NaN in row 22487 : 1
 Total NaN in row 22488 : 4
 Total NaN in row 22489 : 4
 Total NaN in row 22490 : 1
 Total NaN in row 22491 : 3
 Total NaN in row 22492 : 4
 Total NaN in row 22493 : 4
 Total NaN in row 22494 : 1
 Total NaN in row 22495 : 2
 Total NaN in row 22496 : 9
 Total NaN in row 22497 : 9
 Total NaN in row 22498 : 3
 Total NaN in row 22499 : 4
 Total NaN in row 22500 : 5
 Total NaN in row 22501 : 2
 Total NaN in row 22502 : 4
 Total NaN in row 22503 : 1
 Total NaN in row 22504 : 9
 Total NaN in row 22505 : 4
 Total NaN in row 22506 : 1
 Total NaN in row 22507 : 2
 Total NaN in row 22508 : 3
 Total NaN in row 22509 : 3
 Total NaN in row 22510 : 1
 Total NaN in row 22511 : 4
 Total NaN in row 22512 : 3
 Total NaN in row 22513 : 4
 Total NaN in row 22514 : 4
 Total NaN in row 22515 : 2
 Total NaN in row 22516 : 9
 Total NaN in row 22517 : 3
 Total NaN in row 22518 : 4
 Total NaN in row 22519 : 2
 Total NaN in row 22520 : 1
 Total NaN in row 22521 : 3
 Total NaN in row 22522 : 5
 Total NaN in row 22523 : 2
 Total NaN in row 22524 : 3
 Total NaN in row 22525 : 1
 Total NaN in row 22526 : 2
 Total NaN in row 22527 : 4
 Total NaN in row 22528 : 4
 Total NaN in row 22529 : 10
 Total NaN in row 22530 : 4
 Total NaN in row 22531 : 4
 Total NaN in row 22532 : 3
 Total NaN in row 22533 : 1
 Total NaN in row 22534 : 1
 Total NaN in row 22535 : 3
 Total NaN in row 22536 : 2
 Total NaN in row 22537 : 2
 Total NaN in row 22538 : 5
 Total NaN in row 22539 : 4
 Total NaN in row 22540 : 3
 Total NaN in row 22541 : 9
 Total NaN in row 22542 : 2
 Total NaN in row 22543 : 3
 Total NaN in row 22544 : 2
 Total NaN in row 22545 : 7
 Total NaN in row 22546 : 4
 Total NaN in row 22547 : 10
 Total NaN in row 22548 : 1
 Total NaN in row 22549 : 2
 Total NaN in row 22550 : 1
 Total NaN in row 22551 : 4
 Total NaN in row 22552 : 1
 Total NaN in row 22553 : 3
 Total NaN in row 22554 : 2
 Total NaN in row 22555 : 4
 Total NaN in row 22556 : 3
 Total NaN in row 22557 : 4
 Total NaN in row 22558 : 3
 Total NaN in row 22559 : 1
 Total NaN in row 22560 : 2
 Total NaN in row 22561 : 9
 Total NaN in row 22562 : 1
 Total NaN in row 22563 : 2
 Total NaN in row 22564 : 2
 Total NaN in row 22565 : 4
 Total NaN in row 22566 : 5
 Total NaN in row 22567 : 4
 Total NaN in row 22568 : 3
 Total NaN in row 22569 : 3
 Total NaN in row 22570 : 3
 Total NaN in row 22571 : 3
 Total NaN in row 22572 : 4
 Total NaN in row 22573 : 4
 Total NaN in row 22574 : 2
 Total NaN in row 22575 : 1
 Total NaN in row 22576 : 3
 Total NaN in row 22577 : 3
 Total NaN in row 22578 : 3

 Total NaN in row 22579 : 3
 Total NaN in row 22580 : 4
 Total NaN in row 22581 : 3
 Total NaN in row 22582 : 4
 Total NaN in row 22583 : 2
 Total NaN in row 22584 : 3
 Total NaN in row 22585 : 1
 Total NaN in row 22586 : 2
 Total NaN in row 22587 : 3
 Total NaN in row 22588 : 4
 Total NaN in row 22589 : 4
 Total NaN in row 22590 : 3
 Total NaN in row 22591 : 3
 Total NaN in row 22592 : 2
 Total NaN in row 22593 : 1
 Total NaN in row 22594 : 5
 Total NaN in row 22595 : 2
 Total NaN in row 22596 : 2
 Total NaN in row 22597 : 4
 Total NaN in row 22598 : 4
 Total NaN in row 22599 : 3
 Total NaN in row 22600 : 1
 Total NaN in row 22601 : 1
 Total NaN in row 22602 : 1
 Total NaN in row 22603 : 2
 Total NaN in row 22604 : 3
 Total NaN in row 22605 : 4
 Total NaN in row 22606 : 5
 Total NaN in row 22607 : 4
 Total NaN in row 22608 : 5
 Total NaN in row 22609 : 3
 Total NaN in row 22610 : 1
 Total NaN in row 22611 : 9
 Total NaN in row 22612 : 2
 Total NaN in row 22613 : 4
 Total NaN in row 22614 : 4
 Total NaN in row 22615 : 4
 Total NaN in row 22616 : 1
 Total NaN in row 22617 : 4
 Total NaN in row 22618 : 4
 Total NaN in row 22619 : 4
 Total NaN in row 22620 : 3
 Total NaN in row 22621 : 4
 Total NaN in row 22622 : 9
 Total NaN in row 22623 : 1
 Total NaN in row 22624 : 2
 Total NaN in row 22625 : 4
 Total NaN in row 22626 : 2
 Total NaN in row 22627 : 2
 Total NaN in row 22628 : 2
 Total NaN in row 22629 : 3
 Total NaN in row 22630 : 2
 Total NaN in row 22631 : 9
 Total NaN in row 22632 : 4
 Total NaN in row 22633 : 2
 Total NaN in row 22634 : 4
 Total NaN in row 22635 : 1
 Total NaN in row 22636 : 2
 Total NaN in row 22637 : 2
 Total NaN in row 22638 : 2
 Total NaN in row 22639 : 2
 Total NaN in row 22640 : 2
 Total NaN in row 22641 : 4
 Total NaN in row 22642 : 2
 Total NaN in row 22643 : 2
 Total NaN in row 22644 : 3
 Total NaN in row 22645 : 2
 Total NaN in row 22646 : 3
 Total NaN in row 22647 : 3
 Total NaN in row 22648 : 1
 Total NaN in row 22649 : 3
 Total NaN in row 22650 : 4
 Total NaN in row 22651 : 2
 Total NaN in row 22652 : 4
 Total NaN in row 22653 : 1
 Total NaN in row 22654 : 3
 Total NaN in row 22655 : 3
 Total NaN in row 22656 : 4
 Total NaN in row 22657 : 5
 Total NaN in row 22658 : 4
 Total NaN in row 22659 : 3
 Total NaN in row 22660 : 2
 Total NaN in row 22661 : 1
 Total NaN in row 22662 : 3
 Total NaN in row 22663 : 2
 Total NaN in row 22664 : 1
 Total NaN in row 22665 : 4
 Total NaN in row 22666 : 9
 Total NaN in row 22667 : 2
 Total NaN in row 22668 : 9
 Total NaN in row 22669 : 3
 Total NaN in row 22670 : 1
 Total NaN in row 22671 : 1
 Total NaN in row 22672 : 3
 Total NaN in row 22673 : 2
 Total NaN in row 22674 : 3
 Total NaN in row 22675 : 3
 Total NaN in row 22676 : 2
 Total NaN in row 22677 : 5
 Total NaN in row 22678 : 9
 Total NaN in row 22679 : 4
 Total NaN in row 22680 : 9
 Total NaN in row 22681 : 1
 Total NaN in row 22682 : 3
 Total NaN in row 22683 : 2
 Total NaN in row 22684 : 4
 Total NaN in row 22685 : 4
 Total NaN in row 22686 : 5
 Total NaN in row 22687 : 2
 Total NaN in row 22688 : 9
 Total NaN in row 22689 : 2
 Total NaN in row 22690 : 2
 Total NaN in row 22691 : 2
 Total NaN in row 22692 : 3
 Total NaN in row 22693 : 3
 Total NaN in row 22694 : 3
 Total NaN in row 22695 : 2
 Total NaN in row 22696 : 3
 Total NaN in row 22697 : 5
 Total NaN in row 22698 : 9
 Total NaN in row 22699 : 4
 Total NaN in row 22700 : 1
 Total NaN in row 22701 : 4
 Total NaN in row 22702 : 9
 Total NaN in row 22703 : 9
 Total NaN in row 22704 : 10
 Total NaN in row 22705 : 21
 Total NaN in row 22706 : 1
 Total NaN in row 22707 : 3
 Total NaN in row 22708 : 3
 Total NaN in row 22709 : 4
 Total NaN in row 22710 : 1
 Total NaN in row 22711 : 2
 Total NaN in row 22712 : 2
 Total NaN in row 22713 : 3
 Total NaN in row 22714 : 2
 Total NaN in row 22715 : 7
 Total NaN in row 22716 : 4
 Total NaN in row 22717 : 9
 Total NaN in row 22718 : 2
 Total NaN in row 22719 : 4
 Total NaN in row 22720 : 4
 Total NaN in row 22721 : 3
 Total NaN in row 22722 : 5
 Total NaN in row 22723 : 4
 Total NaN in row 22724 : 3
 Total NaN in row 22725 : 5
 Total NaN in row 22726 : 1
 Total NaN in row 22727 : 2
 Total NaN in row 22728 : 2
 Total NaN in row 22729 : 3
 Total NaN in row 22730 : 2
 Total NaN in row 22731 : 4
 Total NaN in row 22732 : 4
 Total NaN in row 22733 : 5
 Total NaN in row 22734 : 9
 Total NaN in row 22735 : 2
 Total NaN in row 22736 : 4
 Total NaN in row 22737 : 3
 Total NaN in row 22738 : 1
 Total NaN in row 22739 : 3
 Total NaN in row 22740 : 5
 Total NaN in row 22741 : 4
 Total NaN in row 22742 : 2
 Total NaN in row 22743 : 4
 Total NaN in row 22744 : 4
 Total NaN in row 22745 : 3
 Total NaN in row 22746 : 3
 Total NaN in row 22747 : 1
 Total NaN in row 22748 : 4
 Total NaN in row 22749 : 2
 Total NaN in row 22750 : 4
 Total NaN in row 22751 : 1
 Total NaN in row 22752 : 4
 Total NaN in row 22753 : 1
 Total NaN in row 22754 : 3
 Total NaN in row 22755 : 2
 Total NaN in row 22756 : 2
 Total NaN in row 22757 : 1
 Total NaN in row 22758 : 10
 Total NaN in row 22759 : 1
 Total NaN in row 22760 : 3
 Total NaN in row 22761 : 2
 Total NaN in row 22762 : 2
 Total NaN in row 22763 : 4
 Total NaN in row 22764 : 1
 Total NaN in row 22765 : 4
 Total NaN in row 22766 : 9
 Total NaN in row 22767 : 3
 Total NaN in row 22768 : 1
 Total NaN in row 22769 : 2
 Total NaN in row 22770 : 2
 Total NaN in row 22771 : 2
 Total NaN in row 22772 : 2
 Total NaN in row 22773 : 2
 Total NaN in row 22774 : 3
 Total NaN in row 22775 : 2
 Total NaN in row 22776 : 5
 Total NaN in row 22777 : 2
 Total NaN in row 22778 : 4
 Total NaN in row 22779 : 2
 Total NaN in row 22780 : 4
 Total NaN in row 22781 : 2
 Total NaN in row 22782 : 5
 Total NaN in row 22783 : 1
 Total NaN in row 22784 : 3
 Total NaN in row 22785 : 4
 Total NaN in row 22786 : 2
 Total NaN in row 22787 : 2
 Total NaN in row 22788 : 2
 Total NaN in row 22789 : 4
 Total NaN in row 22790 : 2
 Total NaN in row 22791 : 2
 Total NaN in row 22792 : 1
 Total NaN in row 22793 : 3
 Total NaN in row 22794 : 4
 Total NaN in row 22795 : 2
 Total NaN in row 22796 : 2
 Total NaN in row 22797 : 3
 Total NaN in row 22798 : 3
 Total NaN in row 22799 : 2
 Total NaN in row 22800 : 3
 Total NaN in row 22801 : 1
 Total NaN in row 22802 : 9
 Total NaN in row 22803 : 3
 Total NaN in row 22804 : 1
 Total NaN in row 22805 : 1
 Total NaN in row 22806 : 3
 Total NaN in row 22807 : 3
 Total NaN in row 22808 : 9
 Total NaN in row 22809 : 2
 Total NaN in row 22810 : 2
 Total NaN in row 22811 : 2
 Total NaN in row 22812 : 9
 Total NaN in row 22813 : 10
 Total NaN in row 22814 : 1
 Total NaN in row 22815 : 2
 Total NaN in row 22816 : 2
 Total NaN in row 22817 : 2
 Total NaN in row 22818 : 2
 Total NaN in row 22819 : 3
 Total NaN in row 22820 : 4
 Total NaN in row 22821 : 1
 Total NaN in row 22822 : 2
 Total NaN in row 22823 : 4
 Total NaN in row 22824 : 7
 Total NaN in row 22825 : 4
 Total NaN in row 22826 : 3
 Total NaN in row 22827 : 3
 Total NaN in row 22828 : 4
 Total NaN in row 22829 : 1
 Total NaN in row 22830 : 2
 Total NaN in row 22831 : 3
 Total NaN in row 22832 : 9
 Total NaN in row 22833 : 3
 Total NaN in row 22834 : 4
 Total NaN in row 22835 : 3
 Total NaN in row 22836 : 9
 Total NaN in row 22837 : 3
 Total NaN in row 22838 : 2
 Total NaN in row 22839 : 3
 Total NaN in row 22840 : 2
 Total NaN in row 22841 : 2
 Total NaN in row 22842 : 4
 Total NaN in row 22843 : 3
 Total NaN in row 22844 : 3
 Total NaN in row 22845 : 3
 Total NaN in row 22846 : 4
 Total NaN in row 22847 : 3
 Total NaN in row 22848 : 3
 Total NaN in row 22849 : 3
 Total NaN in row 22850 : 4
 Total NaN in row 22851 : 1
 Total NaN in row 22852 : 3
 Total NaN in row 22853 : 1
 Total NaN in row 22854 : 1
 Total NaN in row 22855 : 5
 Total NaN in row 22856 : 3
 Total NaN in row 22857 : 2
 Total NaN in row 22858 : 4
 Total NaN in row 22859 : 3
 Total NaN in row 22860 : 5
 Total NaN in row 22861 : 2
 Total NaN in row 22862 : 2
 Total NaN in row 22863 : 2
 Total NaN in row 22864 : 5
 Total NaN in row 22865 : 2
 Total NaN in row 22866 : 5
 Total NaN in row 22867 : 3
 Total NaN in row 22868 : 2
 Total NaN in row 22869 : 3
 Total NaN in row 22870 : 4
 Total NaN in row 22871 : 4
 Total NaN in row 22872 : 3
 Total NaN in row 22873 : 3
 Total NaN in row 22874 : 2
 Total NaN in row 22875 : 9
 Total NaN in row 22876 : 4
 Total NaN in row 22877 : 1
 Total NaN in row 22878 : 5
 Total NaN in row 22879 : 1
 Total NaN in row 22880 : 4
 Total NaN in row 22881 : 9
 Total NaN in row 22882 : 4
 Total NaN in row 22883 : 1
 Total NaN in row 22884 : 2
 Total NaN in row 22885 : 2
 Total NaN in row 22886 : 2
 Total NaN in row 22887 : 5
 Total NaN in row 22888 : 2
 Total NaN in row 22889 : 4

 Total NaN in row 22890 : 3
 Total NaN in row 22891 : 7
 Total NaN in row 22892 : 1
 Total NaN in row 22893 : 9
 Total NaN in row 22894 : 4
 Total NaN in row 22895 : 4
 Total NaN in row 22896 : 4
 Total NaN in row 22897 : 2
 Total NaN in row 22898 : 2
 Total NaN in row 22899 : 5
 Total NaN in row 22900 : 9
 Total NaN in row 22901 : 2
 Total NaN in row 22902 : 2
 Total NaN in row 22903 : 4
 Total NaN in row 22904 : 4
 Total NaN in row 22905 : 7
 Total NaN in row 22906 : 2
 Total NaN in row 22907 : 1
 Total NaN in row 22908 : 4
 Total NaN in row 22909 : 9
 Total NaN in row 22910 : 4
 Total NaN in row 22911 : 5
 Total NaN in row 22912 : 3
 Total NaN in row 22913 : 3
 Total NaN in row 22914 : 4
 Total NaN in row 22915 : 1
 Total NaN in row 22916 : 3
 Total NaN in row 22917 : 9
 Total NaN in row 22918 : 1
 Total NaN in row 22919 : 21
 Total NaN in row 22920 : 2
 Total NaN in row 22921 : 2
 Total NaN in row 22922 : 3
 Total NaN in row 22923 : 7
 Total NaN in row 22924 : 7
 Total NaN in row 22925 : 4
 Total NaN in row 22926 : 2
 Total NaN in row 22927 : 2
 Total NaN in row 22928 : 5
 Total NaN in row 22929 : 3
 Total NaN in row 22930 : 1
 Total NaN in row 22931 : 9
 Total NaN in row 22932 : 3
 Total NaN in row 22933 : 1
 Total NaN in row 22934 : 1
 Total NaN in row 22935 : 1
 Total NaN in row 22936 : 4
 Total NaN in row 22937 : 4
 Total NaN in row 22938 : 4
 Total NaN in row 22939 : 6
 Total NaN in row 22940 : 5
 Total NaN in row 22941 : 4
 Total NaN in row 22942 : 4
 Total NaN in row 22943 : 3
 Total NaN in row 22944 : 5
 Total NaN in row 22945 : 5
 Total NaN in row 22946 : 6
 Total NaN in row 22947 : 3
 Total NaN in row 22948 : 9
 Total NaN in row 22949 : 2
 Total NaN in row 22950 : 1
 Total NaN in row 22951 : 2
 Total NaN in row 22952 : 2
 Total NaN in row 22953 : 3
 Total NaN in row 22954 : 4
 Total NaN in row 22955 : 5
 Total NaN in row 22956 : 9
 Total NaN in row 22957 : 2
 Total NaN in row 22958 : 2
 Total NaN in row 22959 : 3
 Total NaN in row 22960 : 4
 Total NaN in row 22961 : 1
 Total NaN in row 22962 : 3
 Total NaN in row 22963 : 4
 Total NaN in row 22964 : 4
 Total NaN in row 22965 : 1
 Total NaN in row 22966 : 2
 Total NaN in row 22967 : 9
 Total NaN in row 22968 : 4
 Total NaN in row 22969 : 3
 Total NaN in row 22970 : 3
 Total NaN in row 22971 : 3
 Total NaN in row 22972 : 4
 Total NaN in row 22973 : 3
 Total NaN in row 22974 : 4
 Total NaN in row 22975 : 4
 Total NaN in row 22976 : 4
 Total NaN in row 22977 : 9
 Total NaN in row 22978 : 4
 Total NaN in row 22979 : 2
 Total NaN in row 22980 : 4
 Total NaN in row 22981 : 4
 Total NaN in row 22982 : 3
 Total NaN in row 22983 : 3
 Total NaN in row 22984 : 2
 Total NaN in row 22985 : 1
 Total NaN in row 22986 : 4
 Total NaN in row 22987 : 7
 Total NaN in row 22988 : 1
 Total NaN in row 22989 : 9
 Total NaN in row 22990 : 2
 Total NaN in row 22991 : 4
 Total NaN in row 22992 : 3
 Total NaN in row 22993 : 3
 Total NaN in row 22994 : 1
 Total NaN in row 22995 : 3
 Total NaN in row 22996 : 4
 Total NaN in row 22997 : 1
 Total NaN in row 22998 : 3
 Total NaN in row 22999 : 3
 Total NaN in row 23000 : 2
 Total NaN in row 23001 : 1
 Total NaN in row 23002 : 5
 Total NaN in row 23003 : 2
 Total NaN in row 23004 : 3
 Total NaN in row 23005 : 4
 Total NaN in row 23006 : 2
 Total NaN in row 23007 : 9
 Total NaN in row 23008 : 3
 Total NaN in row 23009 : 5
 Total NaN in row 23010 : 4
 Total NaN in row 23011 : 3
 Total NaN in row 23012 : 2
 Total NaN in row 23013 : 1
 Total NaN in row 23014 : 3
 Total NaN in row 23015 : 3
 Total NaN in row 23016 : 2
 Total NaN in row 23017 : 7
 Total NaN in row 23018 : 5
 Total NaN in row 23019 : 4
 Total NaN in row 23020 : 3
 Total NaN in row 23021 : 7
 Total NaN in row 23022 : 7
 Total NaN in row 23023 : 2
 Total NaN in row 23024 : 3
 Total NaN in row 23025 : 3
 Total NaN in row 23026 : 2
 Total NaN in row 23027 : 1
 Total NaN in row 23028 : 1
 Total NaN in row 23029 : 2
 Total NaN in row 23030 : 3
 Total NaN in row 23031 : 2
 Total NaN in row 23032 : 10
 Total NaN in row 23033 : 3
 Total NaN in row 23034 : 3
 Total NaN in row 23035 : 1
 Total NaN in row 23036 : 3
 Total NaN in row 23037 : 2
 Total NaN in row 23038 : 3
 Total NaN in row 23039 : 4
 Total NaN in row 23040 : 3
 Total NaN in row 23041 : 9
 Total NaN in row 23042 : 1
 Total NaN in row 23043 : 2
 Total NaN in row 23044 : 1
 Total NaN in row 23045 : 5
 Total NaN in row 23046 : 2
 Total NaN in row 23047 : 1
 Total NaN in row 23048 : 1
 Total NaN in row 23049 : 4
 Total NaN in row 23050 : 3
 Total NaN in row 23051 : 1
 Total NaN in row 23052 : 2
 Total NaN in row 23053 : 4
 Total NaN in row 23054 : 2
 Total NaN in row 23055 : 3
 Total NaN in row 23056 : 10
 Total NaN in row 23057 : 9
 Total NaN in row 23058 : 3
 Total NaN in row 23059 : 3
 Total NaN in row 23060 : 9
 Total NaN in row 23061 : 1
 Total NaN in row 23062 : 3
 Total NaN in row 23063 : 2
 Total NaN in row 23064 : 5
 Total NaN in row 23065 : 2
 Total NaN in row 23066 : 10
 Total NaN in row 23067 : 2
 Total NaN in row 23068 : 2
 Total NaN in row 23069 : 3
 Total NaN in row 23070 : 3
 Total NaN in row 23071 : 4
 Total NaN in row 23072 : 2
 Total NaN in row 23073 : 9
 Total NaN in row 23074 : 5
 Total NaN in row 23075 : 4
 Total NaN in row 23076 : 3
 Total NaN in row 23077 : 4
 Total NaN in row 23078 : 1
 Total NaN in row 23079 : 2
 Total NaN in row 23080 : 3
 Total NaN in row 23081 : 4
 Total NaN in row 23082 : 4
 Total NaN in row 23083 : 9
 Total NaN in row 23084 : 9
 Total NaN in row 23085 : 4
 Total NaN in row 23086 : 9
 Total NaN in row 23087 : 4
 Total NaN in row 23088 : 1
 Total NaN in row 23089 : 4
 Total NaN in row 23090 : 1
 Total NaN in row 23091 : 1
 Total NaN in row 23092 : 4
 Total NaN in row 23093 : 4
 Total NaN in row 23094 : 9
 Total NaN in row 23095 : 3
 Total NaN in row 23096 : 4
 Total NaN in row 23097 : 2
 Total NaN in row 23098 : 1
 Total NaN in row 23099 : 3
 Total NaN in row 23100 : 4
 Total NaN in row 23101 : 10
 Total NaN in row 23102 : 1
 Total NaN in row 23103 : 4
 Total NaN in row 23104 : 3
 Total NaN in row 23105 : 1
 Total NaN in row 23106 : 9
 Total NaN in row 23107 : 1
 Total NaN in row 23108 : 5
 Total NaN in row 23109 : 1
 Total NaN in row 23110 : 4
 Total NaN in row 23111 : 2
 Total NaN in row 23112 : 3
 Total NaN in row 23113 : 2
 Total NaN in row 23114 : 1
 Total NaN in row 23115 : 2
 Total NaN in row 23116 : 7
 Total NaN in row 23117 : 2
 Total NaN in row 23118 : 5
 Total NaN in row 23119 : 1
 Total NaN in row 23120 : 2
 Total NaN in row 23121 : 2
 Total NaN in row 23122 : 10
 Total NaN in row 23123 : 1
 Total NaN in row 23124 : 1
 Total NaN in row 23125 : 3
 Total NaN in row 23126 : 1
 Total NaN in row 23127 : 3
 Total NaN in row 23128 : 2
 Total NaN in row 23129 : 4
 Total NaN in row 23130 : 5
 Total NaN in row 23131 : 9
 Total NaN in row 23132 : 2
 Total NaN in row 23133 : 2
 Total NaN in row 23134 : 9
 Total NaN in row 23135 : 3
 Total NaN in row 23136 : 2
 Total NaN in row 23137 : 4
 Total NaN in row 23138 : 1
 Total NaN in row 23139 : 3
 Total NaN in row 23140 : 2
 Total NaN in row 23141 : 9
 Total NaN in row 23142 : 2
 Total NaN in row 23143 : 3
 Total NaN in row 23144 : 3
 Total NaN in row 23145 : 4
 Total NaN in row 23146 : 3
 Total NaN in row 23147 : 1
 Total NaN in row 23148 : 5
 Total NaN in row 23149 : 3
 Total NaN in row 23150 : 3
 Total NaN in row 23151 : 2
 Total NaN in row 23152 : 1
 Total NaN in row 23153 : 4
 Total NaN in row 23154 : 21
 Total NaN in row 23155 : 1
 Total NaN in row 23156 : 2
 Total NaN in row 23157 : 1
 Total NaN in row 23158 : 3
 Total NaN in row 23159 : 1
 Total NaN in row 23160 : 2
 Total NaN in row 23161 : 2
 Total NaN in row 23162 : 3
 Total NaN in row 23163 : 3
 Total NaN in row 23164 : 1
 Total NaN in row 23165 : 2
 Total NaN in row 23166 : 3
 Total NaN in row 23167 : 9
 Total NaN in row 23168 : 4
 Total NaN in row 23169 : 2
 Total NaN in row 23170 : 2
 Total NaN in row 23171 : 2
 Total NaN in row 23172 : 3
 Total NaN in row 23173 : 2
 Total NaN in row 23174 : 4
 Total NaN in row 23175 : 2
 Total NaN in row 23176 : 7
 Total NaN in row 23177 : 3
 Total NaN in row 23178 : 4
 Total NaN in row 23179 : 1
 Total NaN in row 23180 : 2
 Total NaN in row 23181 : 1
 Total NaN in row 23182 : 1
 Total NaN in row 23183 : 3
 Total NaN in row 23184 : 4

 Total NaN in row 23185 : 1
 Total NaN in row 23186 : 5
 Total NaN in row 23187 : 2
 Total NaN in row 23188 : 9
 Total NaN in row 23189 : 2
 Total NaN in row 23190 : 2
 Total NaN in row 23191 : 3
 Total NaN in row 23192 : 2
 Total NaN in row 23193 : 1
 Total NaN in row 23194 : 1
 Total NaN in row 23195 : 9
 Total NaN in row 23196 : 2
 Total NaN in row 23197 : 5
 Total NaN in row 23198 : 4
 Total NaN in row 23199 : 2
 Total NaN in row 23200 : 4
 Total NaN in row 23201 : 9
 Total NaN in row 23202 : 2
 Total NaN in row 23203 : 3
 Total NaN in row 23204 : 1
 Total NaN in row 23205 : 2
 Total NaN in row 23206 : 4
 Total NaN in row 23207 : 3
 Total NaN in row 23208 : 9
 Total NaN in row 23209 : 2
 Total NaN in row 23210 : 2
 Total NaN in row 23211 : 2
 Total NaN in row 23212 : 1
 Total NaN in row 23213 : 9
 Total NaN in row 23214 : 9
 Total NaN in row 23215 : 10
 Total NaN in row 23216 : 1
 Total NaN in row 23217 : 2
 Total NaN in row 23218 : 1
 Total NaN in row 23219 : 9
 Total NaN in row 23220 : 1
 Total NaN in row 23221 : 4
 Total NaN in row 23222 : 2
 Total NaN in row 23223 : 1
 Total NaN in row 23224 : 3
 Total NaN in row 23225 : 1
 Total NaN in row 23226 : 9
 Total NaN in row 23227 : 9
 Total NaN in row 23228 : 2
 Total NaN in row 23229 : 3
 Total NaN in row 23230 : 3
 Total NaN in row 23231 : 2
 Total NaN in row 23232 : 2
 Total NaN in row 23233 : 9
 Total NaN in row 23234 : 2
 Total NaN in row 23235 : 2
 Total NaN in row 23236 : 4
 Total NaN in row 23237 : 1
 Total NaN in row 23238 : 1
 Total NaN in row 23239 : 2
 Total NaN in row 23240 : 6
 Total NaN in row 23241 : 3
 Total NaN in row 23242 : 4
 Total NaN in row 23243 : 2
 Total NaN in row 23244 : 4
 Total NaN in row 23245 : 3
 Total NaN in row 23246 : 1
 Total NaN in row 23247 : 4
 Total NaN in row 23248 : 1
 Total NaN in row 23249 : 9
 Total NaN in row 23250 : 1
 Total NaN in row 23251 : 3
 Total NaN in row 23252 : 1
 Total NaN in row 23253 : 2
 Total NaN in row 23254 : 2
 Total NaN in row 23255 : 4
 Total NaN in row 23256 : 3
 Total NaN in row 23257 : 2
 Total NaN in row 23258 : 2
 Total NaN in row 23259 : 2
 Total NaN in row 23260 : 1
 Total NaN in row 23261 : 1
 Total NaN in row 23262 : 9
 Total NaN in row 23263 : 2
 Total NaN in row 23264 : 1
 Total NaN in row 23265 : 2
 Total NaN in row 23266 : 2
 Total NaN in row 23267 : 4
 Total NaN in row 23268 : 9
 Total NaN in row 23269 : 1
 Total NaN in row 23270 : 3
 Total NaN in row 23271 : 1
 Total NaN in row 23272 : 2
 Total NaN in row 23273 : 3
 Total NaN in row 23274 : 1
 Total NaN in row 23275 : 3
 Total NaN in row 23276 : 1
 Total NaN in row 23277 : 1
 Total NaN in row 23278 : 1
 Total NaN in row 23279 : 2
 Total NaN in row 23280 : 3
 Total NaN in row 23281 : 2
 Total NaN in row 23282 : 2
 Total NaN in row 23283 : 4
 Total NaN in row 23284 : 2
 Total NaN in row 23285 : 2
 Total NaN in row 23286 : 2
 Total NaN in row 23287 : 4
 Total NaN in row 23288 : 5
 Total NaN in row 23289 : 3
 Total NaN in row 23290 : 1
 Total NaN in row 23291 : 3
 Total NaN in row 23292 : 3
 Total NaN in row 23293 : 3
 Total NaN in row 23294 : 3
 Total NaN in row 23295 : 4
 Total NaN in row 23296 : 2
 Total NaN in row 23297 : 3
 Total NaN in row 23298 : 3
 Total NaN in row 23299 : 9
 Total NaN in row 23300 : 1
 Total NaN in row 23301 : 2
 Total NaN in row 23302 : 3
 Total NaN in row 23303 : 5
 Total NaN in row 23304 : 2
 Total NaN in row 23305 : 3
 Total NaN in row 23306 : 2
 Total NaN in row 23307 : 2
 Total NaN in row 23308 : 2
 Total NaN in row 23309 : 3
 Total NaN in row 23310 : 2
 Total NaN in row 23311 : 4
 Total NaN in row 23312 : 9
 Total NaN in row 23313 : 3
 Total NaN in row 23314 : 3
 Total NaN in row 23315 : 2
 Total NaN in row 23316 : 3
 Total NaN in row 23317 : 2
 Total NaN in row 23318 : 1
 Total NaN in row 23319 : 2
 Total NaN in row 23320 : 4
 Total NaN in row 23321 : 3
 Total NaN in row 23322 : 3
 Total NaN in row 23323 : 4
 Total NaN in row 23324 : 3
 Total NaN in row 23325 : 3
 Total NaN in row 23326 : 4
 Total NaN in row 23327 : 4
 Total NaN in row 23328 : 4
 Total NaN in row 23329 : 5
 Total NaN in row 23330 : 2
 Total NaN in row 23331 : 5
 Total NaN in row 23332 : 3
 Total NaN in row 23333 : 2
 Total NaN in row 23334 : 9
 Total NaN in row 23335 : 4
 Total NaN in row 23336 : 2
 Total NaN in row 23337 : 3
 Total NaN in row 23338 : 9
 Total NaN in row 23339 : 4
 Total NaN in row 23340 : 1
 Total NaN in row 23341 : 3
 Total NaN in row 23342 : 21
 Total NaN in row 23343 : 2
 Total NaN in row 23344 : 4
 Total NaN in row 23345 : 3
 Total NaN in row 23346 : 2
 Total NaN in row 23347 : 1
 Total NaN in row 23348 : 4
 Total NaN in row 23349 : 3
 Total NaN in row 23350 : 3
 Total NaN in row 23351 : 2
 Total NaN in row 23352 : 3
 Total NaN in row 23353 : 9
 Total NaN in row 23354 : 2
 Total NaN in row 23355 : 8
 Total NaN in row 23356 : 4
 Total NaN in row 23357 : 2
 Total NaN in row 23358 : 1
 Total NaN in row 23359 : 4
 Total NaN in row 23360 : 3
 Total NaN in row 23361 : 3
 Total NaN in row 23362 : 4
 Total NaN in row 23363 : 1
 Total NaN in row 23364 : 4
 Total NaN in row 23365 : 3
 Total NaN in row 23366 : 1
 Total NaN in row 23367 : 1
 Total NaN in row 23368 : 2
 Total NaN in row 23369 : 2
 Total NaN in row 23370 : 3
 Total NaN in row 23371 : 1
 Total NaN in row 23372 : 3
 Total NaN in row 23373 : 1
 Total NaN in row 23374 : 1
 Total NaN in row 23375 : 2
 Total NaN in row 23376 : 3
 Total NaN in row 23377 : 3
 Total NaN in row 23378 : 2
 Total NaN in row 23379 : 2
 Total NaN in row 23380 : 4
 Total NaN in row 23381 : 1
 Total NaN in row 23382 : 1
 Total NaN in row 23383 : 1
 Total NaN in row 23384 : 2
 Total NaN in row 23385 : 9
 Total NaN in row 23386 : 9
 Total NaN in row 23387 : 2
 Total NaN in row 23388 : 1
 Total NaN in row 23389 : 3
 Total NaN in row 23390 : 3
 Total NaN in row 23391 : 3
 Total NaN in row 23392 : 1
 Total NaN in row 23393 : 2
 Total NaN in row 23394 : 4
 Total NaN in row 23395 : 1
 Total NaN in row 23396 : 9
 Total NaN in row 23397 : 3
 Total NaN in row 23398 : 4
 Total NaN in row 23399 : 9
 Total NaN in row 23400 : 9
 Total NaN in row 23401 : 10
 Total NaN in row 23402 : 9
 Total NaN in row 23403 : 9
 Total NaN in row 23404 : 1
 Total NaN in row 23405 : 3
 Total NaN in row 23406 : 5
 Total NaN in row 23407 : 3
 Total NaN in row 23408 : 2
 Total NaN in row 23409 : 2
 Total NaN in row 23410 : 4
 Total NaN in row 23411 : 1
 Total NaN in row 23412 : 4
 Total NaN in row 23413 : 2
 Total NaN in row 23414 : 3
 Total NaN in row 23415 : 7
 Total NaN in row 23416 : 1
 Total NaN in row 23417 : 2
 Total NaN in row 23418 : 3
 Total NaN in row 23419 : 4
 Total NaN in row 23420 : 3
 Total NaN in row 23421 : 1
 Total NaN in row 23422 : 9
 Total NaN in row 23423 : 10
 Total NaN in row 23424 : 10
 Total NaN in row 23425 : 2
 Total NaN in row 23426 : 1
 Total NaN in row 23427 : 2
 Total NaN in row 23428 : 1
 Total NaN in row 23429 : 2
 Total NaN in row 23430 : 3
 Total NaN in row 23431 : 3
 Total NaN in row 23432 : 9
 Total NaN in row 23433 : 4
 Total NaN in row 23434 : 9
 Total NaN in row 23435 : 1
 Total NaN in row 23436 : 2
 Total NaN in row 23437 : 2
 Total NaN in row 23438 : 4
 Total NaN in row 23439 : 3
 Total NaN in row 23440 : 2
 Total NaN in row 23441 : 1
 Total NaN in row 23442 : 1
 Total NaN in row 23443 : 3
 Total NaN in row 23444 : 2
 Total NaN in row 23445 : 4
 Total NaN in row 23446 : 2
 Total NaN in row 23447 : 1
 Total NaN in row 23448 : 4
 Total NaN in row 23449 : 1
 Total NaN in row 23450 : 9
 Total NaN in row 23451 : 5
 Total NaN in row 23452 : 1
 Total NaN in row 23453 : 1
 Total NaN in row 23454 : 2
 Total NaN in row 23455 : 2
 Total NaN in row 23456 : 3
 Total NaN in row 23457 : 1
 Total NaN in row 23458 : 2
 Total NaN in row 23459 : 4
 Total NaN in row 23460 : 1
 Total NaN in row 23461 : 2
 Total NaN in row 23462 : 2
 Total NaN in row 23463 : 2
 Total NaN in row 23464 : 1
 Total NaN in row 23465 : 10
 Total NaN in row 23466 : 4
 Total NaN in row 23467 : 4
 Total NaN in row 23468 : 1
 Total NaN in row 23469 : 9
 Total NaN in row 23470 : 1
 Total NaN in row 23471 : 2
 Total NaN in row 23472 : 2
 Total NaN in row 23473 : 4
 Total NaN in row 23474 : 2
 Total NaN in row 23475 : 2
 Total NaN in row 23476 : 1
 Total NaN in row 23477 : 3
 Total NaN in row 23478 : 2
 Total NaN in row 23479 : 4
 Total NaN in row 23480 : 2
 Total NaN in row 23481 : 2
 Total NaN in row 23482 : 4
 Total NaN in row 23483 : 1

 Total NaN in row 23484 : 9
 Total NaN in row 23485 : 4
 Total NaN in row 23486 : 2
 Total NaN in row 23487 : 2
 Total NaN in row 23488 : 2
 Total NaN in row 23489 : 2
 Total NaN in row 23490 : 3
 Total NaN in row 23491 : 1
 Total NaN in row 23492 : 2
 Total NaN in row 23493 : 3
 Total NaN in row 23494 : 5
 Total NaN in row 23495 : 10
 Total NaN in row 23496 : 3
 Total NaN in row 23497 : 2
 Total NaN in row 23498 : 2
 Total NaN in row 23499 : 3
 Total NaN in row 23500 : 3
 Total NaN in row 23501 : 1
 Total NaN in row 23502 : 3
 Total NaN in row 23503 : 1
 Total NaN in row 23504 : 2
 Total NaN in row 23505 : 4
 Total NaN in row 23506 : 2
 Total NaN in row 23507 : 3
 Total NaN in row 23508 : 3
 Total NaN in row 23509 : 1
 Total NaN in row 23510 : 1
 Total NaN in row 23511 : 3
 Total NaN in row 23512 : 4
 Total NaN in row 23513 : 4
 Total NaN in row 23514 : 7
 Total NaN in row 23515 : 3
 Total NaN in row 23516 : 9
 Total NaN in row 23517 : 2
 Total NaN in row 23518 : 3
 Total NaN in row 23519 : 1
 Total NaN in row 23520 : 3
 Total NaN in row 23521 : 2
 Total NaN in row 23522 : 2
 Total NaN in row 23523 : 2
 Total NaN in row 23524 : 4
 Total NaN in row 23525 : 4
 Total NaN in row 23526 : 1
 Total NaN in row 23527 : 1
 Total NaN in row 23528 : 2
 Total NaN in row 23529 : 9
 Total NaN in row 23530 : 10
 Total NaN in row 23531 : 2
 Total NaN in row 23532 : 1
 Total NaN in row 23533 : 1
 Total NaN in row 23534 : 1
 Total NaN in row 23535 : 4
 Total NaN in row 23536 : 3
 Total NaN in row 23537 : 5
 Total NaN in row 23538 : 2
 Total NaN in row 23539 : 2
 Total NaN in row 23540 : 3
 Total NaN in row 23541 : 9
 Total NaN in row 23542 : 1
 Total NaN in row 23543 : 3
 Total NaN in row 23544 : 9
 Total NaN in row 23545 : 1
 Total NaN in row 23546 : 2
 Total NaN in row 23547 : 2
 Total NaN in row 23548 : 1
 Total NaN in row 23549 : 2
 Total NaN in row 23550 : 9
 Total NaN in row 23551 : 1
 Total NaN in row 23552 : 2
 Total NaN in row 23553 : 2
 Total NaN in row 23554 : 1
 Total NaN in row 23555 : 4
 Total NaN in row 23556 : 10
 Total NaN in row 23557 : 1
 Total NaN in row 23558 : 2
 Total NaN in row 23559 : 1
 Total NaN in row 23560 : 2
 Total NaN in row 23561 : 4
 Total NaN in row 23562 : 3
 Total NaN in row 23563 : 1
 Total NaN in row 23564 : 3
 Total NaN in row 23565 : 2
 Total NaN in row 23566 : 3
 Total NaN in row 23567 : 5
 Total NaN in row 23568 : 2
 Total NaN in row 23569 : 9
 Total NaN in row 23570 : 3
 Total NaN in row 23571 : 2
 Total NaN in row 23572 : 2
 Total NaN in row 23573 : 3
 Total NaN in row 23574 : 9
 Total NaN in row 23575 : 2
 Total NaN in row 23576 : 2
 Total NaN in row 23577 : 4
 Total NaN in row 23578 : 9
 Total NaN in row 23579 : 3
 Total NaN in row 23580 : 3
 Total NaN in row 23581 : 9
 Total NaN in row 23582 : 2
 Total NaN in row 23583 : 5
 Total NaN in row 23584 : 1
 Total NaN in row 23585 : 9
 Total NaN in row 23586 : 4
 Total NaN in row 23587 : 4
 Total NaN in row 23588 : 3
 Total NaN in row 23589 : 2
 Total NaN in row 23590 : 7
 Total NaN in row 23591 : 4
 Total NaN in row 23592 : 2
 Total NaN in row 23593 : 1
 Total NaN in row 23594 : 2
 Total NaN in row 23595 : 2
 Total NaN in row 23596 : 2
 Total NaN in row 23597 : 3
 Total NaN in row 23598 : 3
 Total NaN in row 23599 : 1
 Total NaN in row 23600 : 1
 Total NaN in row 23601 : 4
 Total NaN in row 23602 : 4
 Total NaN in row 23603 : 4
 Total NaN in row 23604 : 9
 Total NaN in row 23605 : 2
 Total NaN in row 23606 : 3
 Total NaN in row 23607 : 2
 Total NaN in row 23608 : 1
 Total NaN in row 23609 : 2
 Total NaN in row 23610 : 2
 Total NaN in row 23611 : 3
 Total NaN in row 23612 : 4
 Total NaN in row 23613 : 2
 Total NaN in row 23614 : 1
 Total NaN in row 23615 : 7
 Total NaN in row 23616 : 4
 Total NaN in row 23617 : 2
 Total NaN in row 23618 : 4
 Total NaN in row 23619 : 2
 Total NaN in row 23620 : 2
 Total NaN in row 23621 : 4
 Total NaN in row 23622 : 3
 Total NaN in row 23623 : 3
 Total NaN in row 23624 : 1
 Total NaN in row 23625 : 3
 Total NaN in row 23626 : 4
 Total NaN in row 23627 : 9
 Total NaN in row 23628 : 2
 Total NaN in row 23629 : 3
 Total NaN in row 23630 : 2
 Total NaN in row 23631 : 9
 Total NaN in row 23632 : 4
 Total NaN in row 23633 : 1
 Total NaN in row 23634 : 9
 Total NaN in row 23635 : 3
 Total NaN in row 23636 : 2
 Total NaN in row 23637 : 6
 Total NaN in row 23638 : 3
 Total NaN in row 23639 : 2
 Total NaN in row 23640 : 9
 Total NaN in row 23641 : 2
 Total NaN in row 23642 : 4
 Total NaN in row 23643 : 2
 Total NaN in row 23644 : 1
 Total NaN in row 23645 : 2
 Total NaN in row 23646 : 3
 Total NaN in row 23647 : 2
 Total NaN in row 23648 : 5
 Total NaN in row 23649 : 2
 Total NaN in row 23650 : 3
 Total NaN in row 23651 : 3
 Total NaN in row 23652 : 2
 Total NaN in row 23653 : 1
 Total NaN in row 23654 : 4
 Total NaN in row 23655 : 3
 Total NaN in row 23656 : 3
 Total NaN in row 23657 : 1
 Total NaN in row 23658 : 2
 Total NaN in row 23659 : 1
 Total NaN in row 23660 : 5
 Total NaN in row 23661 : 4
 Total NaN in row 23662 : 5
 Total NaN in row 23663 : 9
 Total NaN in row 23664 : 1
 Total NaN in row 23665 : 5
 Total NaN in row 23666 : 2
 Total NaN in row 23667 : 3
 Total NaN in row 23668 : 4
 Total NaN in row 23669 : 2
 Total NaN in row 23670 : 1
 Total NaN in row 23671 : 2
 Total NaN in row 23672 : 2
 Total NaN in row 23673 : 1
 Total NaN in row 23674 : 2
 Total NaN in row 23675 : 8
 Total NaN in row 23676 : 4
 Total NaN in row 23677 : 1
 Total NaN in row 23678 : 2

In [11]:
df.isnull().sum().sum()

69669

In [12]:
sum([True for idx,row in df.iterrows() if any(row.isnull())])

17482

In [13]:
df.isnull().values.ravel().sum()

69669

In [14]:
df.loc[:, df.isnull().any()].columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [15]:
def rmissingvaluecol(df,threshold):
    l = []
    l = list(df.drop(df.loc[:,list((100*(df.isnull().sum()/len(df.index))>=threshold))].columns, 1).columns.values)
    print("# Columns having more than %s percent missing values:"%threshold,(df.shape[1] - len(l)))
    print("Columns:\n",list(set(list((df.columns.values))) - set(l)))
    return l


rmissingvaluecol(df,30)

# Columns having more than 30 percent missing values: 3
Columns:
 ['CouncilArea', 'BuildingArea', 'YearBuilt']

['Suburb',
 'Address',
 'Rooms',
 'Type',
 'Price',
 'Method',
 'SellerG',
 'Date',
 'Distance',
 'Postcode',
 'Bedroom2',
 'Bathroom',
 'Car',
 'Landsize',
 'Lattitude',
 'Longtitude',
 'Regionname',
 'Propertycount']

In [16]:
l = rmissingvaluecol(df,30)
df_1 = df[l]

# Columns having more than 30 percent missing values: 3
Columns:
 ['CouncilArea', 'BuildingArea', 'YearBuilt']

In [17]:
df_1

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,2.0,1.0,1.0,126.0,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,2.0,1.0,1.0,202.0,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,2.0,1.0,0.0,156.0,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,3.0,2.0,1.0,0.0,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,0.0,134.0,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,3.0,1.0,0.0,552.0,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,4.0,3.0,2.0,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,4.0,1.0,1.0,362.0,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,4.0,2.0,2.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [18]:
import numpy as np
df_2 = np.where(df.isnull().sum(axis=1)>5)

In [19]:
df_2

(array([   15,    16,    19, ..., 23639, 23662, 23674], dtype=int64),)

In [20]:
df.drop(df[df.isnull().sum(axis=1)>5].index,axis=0,inplace=True)

print(round(100*(1-df.count()/len(df)),2))

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.67
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2          0.00
Bathroom          0.01
Car               0.70
Landsize          8.64
BuildingArea     47.43
YearBuilt        39.44
CouncilArea      17.84
Lattitude         0.14
Longtitude        0.14
Regionname        0.00
Propertycount     0.00
dtype: float64

In [21]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,19055.000000,1.492600e+04,19055.000000,19055.000000,19055.000000,19054.000000,18921.000000,17408.000000,10018.000000,11540.000000,19029.000000,19029.000000,19055.000000
mean,2.975020,1.067117e+06,10.222556,3109.772763,2.951929,1.570956,1.626235,551.822151,154.527895,1964.636742,-37.812187,145.000471,7474.095565
std,0.972329,6.382375e+05,6.055921,93.808492,0.996002,0.712765,0.974048,3544.489659,462.535765,37.595504,0.080002,0.106099,4312.653403
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.184180,144.431620,129.000000
25%,2.000000,6.410000e+05,6.100000,3048.000000,2.000000,1.000000,1.000000,181.000000,95.000000,1940.000000,-37.859010,144.939000,4442.000000
50%,3.000000,9.000000e+05,9.200000,3101.000000,3.000000,1.000000,2.000000,448.000000,129.000000,1970.000000,-37.809260,145.004690,6567.000000
75%,4.000000,1.320000e+06,13.000000,3150.000000,4.000000,2.000000,2.000000,656.000000,180.000000,2000.000000,-37.759500,145.063530,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,30.000000,12.000000,26.000000,433014.000000,44515.000000,2106.000000,-37.407580,145.526350,21650.000000